### ISSUE TITLE
maven build fail on jenkins with lombok

### ISSUE THREAD

**Issue by okihouse** [rzwitserloot/lombok#1000]
What steps will reproduce the problem?
1. create a maven project
2. Add a class with @ Data annotation 
3. call setter method .
3. Do a mvn compile in jenkins.

What is the expected output?
build success.

What do you see instead?
Cannot find symbol errors

What version of the product are you using?
1.16.6

On what operating system?
Ubuntu 12

Please provide any additional information below.

It was successful when I built my application in IDE.
but with jenkins, error is occured in setter method.

What should i do??

![734635345645](https://cloud.githubusercontent.com/assets/13760160/12283382/1d229dc0-b9e9-11e5-9312-eabda1894645.JPG)

**Comment by nvdh** [comment]
Did you add the lombok maven dependency in your pom?

**Comment by okihouse** [comment]
@nvdh yes, I do.

This problem was caused by version difference of maven-compiler-plugin.

when used maven-compiler-plugin 2.4 version with lombok, there was no problem.(current 3.3)
but with the 2.3.2 version, the error has occurred.

I would like to know what is updated from 2.3.2 to 2.4 version.
or, do you know why this happened?

**Comment by rspilker** [comment]
I have no clue. Versio 2.4 has been available since april 2012, so I don't think it is necessary to spend too much time on figuring this out.
