### ISSUE TITLE
[Feature Request] lombok-light.jar

### ISSUE THREAD

**Issue by JFixby** [rzwitserloot/lombok#1001]
Hello guys,

Nice library!

I just have one feature request. :)

Currently there is this ```lombok.jar``` available on the project homepage (https://projectlombok.org/download.html) for download.
The jar contains lombok functionality + lombok installer. Practically the installer is used only once to configure eclipse. It is not necessary to keep it on board afterwards.

Could you please also produce ```lombok-light.jar``` - a light version of the jar that contains only the  minimal lombok functionality (no installer)?

Usually I produce ```lombok-light.jar``` myself by repacking the original jar and surgically removing the installer. The resulting ```.jar``` weights about 3 times less and still works as a charm. However I believe that you are more competent for that operation than me.

So I'm asking you to supply both ```lombok.jar``` and ```lombok-light.jar``` in the future. 

Thanks in advance and have a nice day!

**Comment by rspilker** [comment]
I don't really see the point. Lombok is a compile time only dependency you don't need to ship with your product, and the jar is currently less the 2 MB. So I don't see any reason to complicate the build process   and confuse the users with too many choices.

**Comment by JFixby** [comment]
Ok, I see your point.
I didn't know it is compile time only dependency.

It's just when I export project to final jar, the Eclipse also includes the lombok.jar content.
But I guess I can handle that.
