### ISSUE TITLE
allow @Value to not create final classes

### ISSUE THREAD

**Issue by rmannibucau** [rzwitserloot/lombok#1004]
Hi

when using a framework the final constraint can be quite intrusive so having a

    @Value(useFinal=false)

would be very welcomed

**Comment by rschmitt** [comment]
It is impossible to guarantee that a non-final class is actually immutable, which is the whole point of `@Value`. Why not just use `@Data`?

**Comment by rmannibucau** [comment]
@rschmitt agree, even the exact reason why @Value fails when used with such frameworks. Goal is mainly to not expose setters at all. @Data(readOnly=true) would work also but sounds better on @Value IMHO. Idea being to avoid to add yet another annotation (@Setter) on all "value" objects.

**Comment by jmax01** [comment]
@NonFinal is already available.

**Comment by rspilker** [comment]
Correct

**Comment by rspilker** [comment]
As documented on the [`@Value` page](https://projectlombok.org/features/Value.html) adding `@NonFinal` on the type gives you the desired behavior.

**Comment by tobq** [comment]
@rspilker does tht make the fields nonfinal too?

**Comment by jmax01** [comment]
> @rspilker does that make the fields nonfinal too?

It does not.  Fields stay final.
