### ISSUE TITLE
Release an artifact without the ShadowClassLoader for compiling custom handlers

### ISSUE THREAD

**Issue by smoyer64** [rzwitserloot/lombok#1005]
This was suggested by David Nelson on and mailing list and I believe it would provide a much more consistent environment for developing extensions.  His rationale is pretty extensive and can be found at https://groups.google.com/forum/#!searchin/project-lombok/shadowclassloader/project-lombok/LK975m4cGig/qdeTq3ZkoBYJ.

As an aside, Reinier Zwitserloot asked that this issue be created in that thread - I couldn't find it but hope I'm not somehow overstepping my bounds.

Thanks!

**Comment by RomainPiel** [comment]
I really like the idea. Is there any plan for that?

**Comment by rzwitserloot** [comment]
I believe we added this now, otherwise, see issue 1927.

**Comment by smoyer64** [comment]
@rzwitserloot Can you provide an example of how Lombok is now easier to extend?  I've been playing around with the technique used by the Maven plugin but that's really opaque.  Is there documentation?  Or even just a couple bullet points to start in the right direction?
