### ISSUE TITLE
@NonNull should be allowed on abstract methods

### ISSUE THREAD

**Issue by cristian-mocanu-mob** [rzwitserloot/lombok#1011]
Lombok throws an error when using ``@NonNull`` on abstract method (in abstract class or interface): ``@NonNull is meaningless on a parameter of an abstract method``.

``@NonNull`` not meaningless in this situation.
It is actually very useful for documentation purposes.

Also, to keep things easy to understand, probably Lombok should require ``@NonNull`` for implementations of these methods (even for abstract overrides - e.g. add a throws declaration in a subclass).

**Comment by rspilker** [comment]
Already fixed in issue #807 and available in the [edge release](https://projectlombok.org/download-edge.html)
