### ISSUE TITLE
Allow specifying field name in @Log annotation

### ISSUE THREAD

**Issue by RAnders00** [rzwitserloot/lombok#1021]
Currently, the name of the field the logger will be accessible through is always `log`. I think it would help if that was customizable. Currently, I am using `LOGGER` as a name all through my project and it's the only thing holding me back on migrating logger fields to lombok.

**Comment by kazuki-ma** [comment]
I think it is already configurable. 

https://projectlombok.org/features/Log.html

```
Supported configuration keys:

lombok.log.fieldName = an identifier (default: log)
The generated logger fieldname is by default 'log', but you can change it to a different name with this setting.
```

**Comment by rspilker** [comment]
That is correct. This might also an opportunity for you to which the logger fields in your codebase to lowercase, as suggested in [this comment](https://github.com/rzwitserloot/lombok/issues/473#issuecomment-121382733).
