### ISSUE TITLE
Calling an Extension Method While Invoking A Method Throws Verify Error: Bad type on operand stack

### ISSUE THREAD

**Issue by ntroutman** [rzwitserloot/lombok#1022]
**Description**
Using @ExtensionMethod where a parameter to the extended method is the result of invoking a method will result in a Verify Error: Bad operand type on stack. See the example for clarification.

**What steps will reproduce the problem?**

Run the example code below in a clean Eclipse project that uses lombok.

**What is expected output? What do you see instead?**

A VerifyError is thrown.

**What version of the produce are you using? On what operating system?**
Lombok v1.16.6
Eclipse Mars.1 Release (4.5.1) Build id: 20150924-1200
Java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
Linux

**Please provide any additional information below**
Exception:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    VerifyErrorBadOperandLombokExtensionMethodTest.main([Ljava/lang/String;)V @19: checkcast
  Reason:
    Type integer (current frame, stack[1]) is not assignable to 'java/lang/Object'
  Current Frame:
    bci: @19
    flags: { }
    locals: { '[Ljava/lang/String;', 'VerifyErrorBadOperandLombokExtensionMethodTest$CanReturnInt' }
    stack: { 'java/lang/Object', integer }
  Bytecode:
    0x0000000: bb00 1059 b700 124c bb00 0359 b700 082b
    0x0000010: b600 13c0 0017 b800 19b2 001f 1225 b600
    0x0000020: 27b1                                   

    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
    at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
    at java.lang.Class.getMethod0(Class.java:3018)
    at java.lang.Class.getMethod(Class.java:1784)
    at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
```

Minimal example that fails when run in Eclipse, but will pass from the command line:

```
import lombok.experimental.ExtensionMethod;

@ExtensionMethod(VerifyErrorBadOperandLombokExtensionMethodTest.Extensions.class)
public class VerifyErrorBadOperandLombokExtensionMethodTest {

    public static class Extensions {
        public static void invoke(Object o, int i) {
        }
    }

    public static class CanReturnInt {
        public int returnsInt() {
            return 0;
        }
    }

    public static void main(String[] args) {
        CanReturnInt anIntReturner = new CanReturnInt();
        new Object().invoke( anIntReturner.returnsInt());

        System.out.println("If you are seeing this then things worked.");
    }

}
```

**Comment by ntroutman** [comment]
Updated description. Turns out the default method was a red herring.

**Comment by ntroutman** [comment]
Further investigation makes be believe this is an issue with auto-boxing. If the call the extension method is written as below it passes:

    new Object().invoke( (int) anIntReturner.returnsInt());

Not the explicit cast to an "int".

**Comment by MrPowerGamerBR** [comment]
Can confirm this issue, very annoying.
