### ISSUE TITLE
About setter and the JavaBean standard

### ISSUE THREAD

**Issue by henry1992007** [rzwitserloot/lombok#1023]
Recently I encountered a problem when using @getter function.

I have a field named "pId" in my java bean but i cannot get the origin data after the bean is deserialized.

so i removed the @getter annotation and used the defaults getters that are generated by the intellij idea instead, which is named "setpId", problem solved.

which means the deserializer could not find the correct setter for the field "pId". i supposed lombok generated a setter named "setPId".

According to the java bean standard, if the second letter of the name is a capital, the first letter should remain what it is in getters and setters.

i'll be grateful if you help to take a look at the problem.
thanks again for your contribution.

**Comment by askoning** [comment]
As described in #757 and a lot of related issues, this (unfortunately) won't be changed.

**Comment by rzwitserloot** [comment]
Duplicate of #2693
