### ISSUE TITLE
Allow defining exception message on @NonNull

### ISSUE THREAD

**Issue by olivergierke** [rzwitserloot/lombok#1029]
It would be cool if `@NonNull` got an optional `value` attribute which allows to define the exception message to be thrown if the `null`-check fails. Maybe you can define a placeholder to include the field's name into the message.

``` java
@RequiredArgsConstructor(onConstructor = @__(@Inject))
class MyComponent {

  @NonNull("MyDependency must not be null! (${field})") 
  private final MyDependency myDependency;
  …
}
```

**Comment by rspilker** [comment]
Sorry, not common enough to warrant the added code complexity and maintenance time on.

**Comment by jianchengwang** [comment]
> Sorry, not common enough to warrant the added code complexity and maintenance time on.

i think it maybe a cool design, it will reduce many coding works which judge configure exception, for example, i have a config properties, and the `bucket` is required, i need write judge code like

`if (S.isEmpty(bucket)) {
            E.invalidConfiguration("Kodo bucket not found in the configuration");
        }`

but if `@NonNULL`can support defining exception

`@NonNull("Kodo bucket not found in the configuration")
`

it look good and if can throw our identify exception will be best in my opinion

`@NonNull(value="Kodo bucket not found in the configuration", exception=ConfigurationException.class)`
