### ISSUE TITLE
@Builder and javadoc

### ISSUE THREAD

**Issue by kuipercm** [rzwitserloot/lombok#1033]
Hi guys,

Maybe I missed it, but if I create a class with an @Builder annotation and I add javadoc to the fields, I find that this javadoc is not "transported" onto the builder methods. It would be very helpful if this were possible. 

If it is possible, I'm probably doing something wrong. How can I get it right?

My code looks like this:

``` java
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Builder
@ToString
public class SomeClass {
    /** The name of the item */
    private final String name;
}
```

Cheers!

**Comment by jcayzac** [comment]
This is a problem for us as well. Lombok is great for removing boilerplate but it shouldn't also remove all our documentation 😢

**Comment by keeperlink** [comment]
Same issue. Any plans to fix it?
