### ISSUE TITLE
@SneakyThrows on lambdas

### ISSUE THREAD

**Issue by xbohdpukc** [rzwitserloot/lombok#1038]
Intellij plugin incorrectly thinks that this @sneakythrows usage is valid:

@SneakyThrows(ClonableNotSupported.class)
void myfunc() {
...
List<ClonableObj> list = some-array-list...
list.forEach(o -> {
   ClonableObj o1 = o.clone(); <-- this gives compile error (ClonableNotSupported? exception should be caught
});

However the annotation on the method incorrectly suppresses the IDE indication of that error. When you compile this code, it correctly points out that that "clone" line still throws unchecked exception AND that @sneakythrows is on a try block that doesn't throw exception. I suspect it's because lambda is an anonymous method of its own, so the clonable exception is thrown in that anonymous method and there's no way of attaching @SneakyThrows to it (or is there?)

So at a minimum, Intellij plugin should not suppress IDE compile error in this case.

**Comment by askoning** [comment]
Since this seems to be plugin-only, closing it here.
