### ISSUE TITLE
Delombok ant task can fail to take format options

### ISSUE THREAD

**Issue by AsturaPhoenix** [rzwitserloot/lombok#1040]
As stated at http://ant.apache.org/manual/develop.html#nested-elements, when both createX and addX are present, the method chosen to support nested Ant elements is JVM-dependent. createX was being chosen for my setup (via Gradle on Java 8) and it did not register Format objects.

Proposed fix:
In [Tasks.Delombok#createFormat()](https://github.com/rzwitserloot/lombok/blob/master/src/delombok/lombok/delombok/ant/DelombokTask.java#L145-L147), the `new Format()` needs to be added to `formatOptions`.

**Comment by bdhandap** [comment]
I'm facing the same issue in OS X. Ant target ignores any `format` option passed. Not able to find a workaround when I've to use the ant for delombok. Any idea when this will get fixed?

**Comment by AsturaPhoenix** [comment]
It's been a while since I've looked at this, but can you try applying my proposed fix locally? (i.e. check out, build, and use your own copy of Lombok.)

Looking back without looking deeper, perhaps it could even be as simple as removing createFormat entirely. But if that doesn't work, maybe what I originally proposed would, as I think I tested this locally when I ran into it.

I'm afraid I don't think I can submit a pull request or offer a complete code fragment due to #1044.
