### ISSUE TITLE
Preserve leading whitespace on comments

### ISSUE THREAD

**Issue by AsturaPhoenix** [rzwitserloot/lombok#1041]
Leading whitespace on comments can be significant within in-doc code samples, so we should do our best to preserve it.

Proposed fix:
Change the regex for [DocCommentIntegrator.CONTENT_STRIPPER](https://github.com/rzwitserloot/lombok/blob/master/src/delombok/lombok/delombok/DocCommentIntegrator.java#L76) to `"^(?:\\s*\\*)?(.*?)$"`, and add

```
 * <pre><code>
 *     Some.sample(code);
 * </code></pre>
```

to a pertinent test case, like [GetterSetterJavadoc2](https://github.com/rzwitserloot/lombok/blob/master/test/transform/resource/before/GetterSetterJavadoc.java#L16-L21).

**Comment by Rawi01** [comment]
Fixed in 2f1069e48c4641928ab3151a13a52b49062a29af
