### ISSUE TITLE
@Wither and inherited properties

### ISSUE THREAD

**Issue by RAnders00** [rzwitserloot/lombok#1059]
Consider the following scenario:

``` java
@Getter
@RequiredArgsConstructor
public class MyBaseClass {
    private String baseProperty;
}
```

``` java
@Getter
public class MySuperClass extends MyBaseClass {

    public MySuperClass(@NonNull String baseProperty, @NonNull String superProperty) {
        super(baseProperty);
        this.superProperty = superProperty;
    }

    @Wither
    private String superProperty;
}
```

Expected: A `withSuperProperty(String s)` is generated that creates a new object with the same inherited `baseProperty` (by using the provided constructor).

Actual: The code does not compile, since no appropriate constructor with only the parameter `java.lang.String` is found.

---

I am not sure whether this it's right to start resolving this issue at `@Wither` - `@XArgsConstructor` for example does not support these inherited properties as well. Maybe, if the issue is first resolved there, it may be easier for `@Wither`? I haven't had a look at the codebase, so this is only a thought. If it's nonsense, just ignore it, please.

**Comment by Maaartinus** [comment]
@RAnders00 FYI: You're right, the constructors are the right place to start. Sadly, it's [close to impossible](https://github.com/rzwitserloot/lombok/wiki/LOMBOK-CONCEPT:-Resolution) to implement.
