### ISSUE TITLE
Library source does not match the bytecode

### ISSUE THREAD

**Issue by 8bitel1te** [rzwitserloot/lombok#1062]
There is an error when trying to add source with lombok inside to IntellJ Idea.
![screenshot_3](https://cloud.githubusercontent.com/assets/7823342/14088065/98aecd2c-f52d-11e5-986a-28dd7f65710f.png)

**Comment by 8bitel1te** [comment]
Got the latest version (0.10.16)

**Comment by AlexejK** [comment]
If we ignore the fact that intellij plugin is the one providing you support for Lombok (however Lombok is still needed on classpath) and that the plugin itself is developed in a different repo, the issue you are seeing probably cannot be avoided:

Lombok generates a code and outputs it into class files,  so when decompiler runs it will see all the methods generated..

 Source packages however contain no such methods and only Lombok annotations. Therefore source packages will always differ from byte code. 

Intellij has a byte code viewer and attempts to be smart,  but the warning is safe to ignore. 

You can try reporting it in intellij plugin repo: https://github.com/mplushnikov/lombok-intellij-plugin and possibly the author will be able to do something about it (but I don't understand why would this be a problem when you know how it works and what Lombok does -  it seems logical). 

Ofc you could also make delombok run and generate sources before packaging those,  but it seems to give quite little benefit,  IMO.

**Comment by kinggggg** [comment]
i encounter THE SAME issue.

**Comment by rspilker** [comment]
Nothing we can do here. Possibly, the intellij plugin can inform the decompiler, but I wouldn't count on it
