### ISSUE TITLE
Feature Request: Groovy inspired "Elvis operator" and "Safe navigation operator"

### ISSUE THREAD

**Issue by dhendry** [rzwitserloot/lombok#1070]
Groovy offers two very useful operators, the "Elvis operator" (`?:`) and the "Safe navigation operator" (`?.`). 

From http://www.oracle.com/technetwork/articles/java/java8-optional-2175753.html: "Languages such as Groovy have a safe navigation operator represented by '?.' to safely navigate through potential null references. ... In addition, Groovy also includes the Elvis operator '?:' (if you look at it sideways, you'll recognize Elvis' famous hair), which can be used for simple cases when a default value is needed."

Which leads to (from the oracle link):

```
String version = computer?.getSoundcard()?.getUSB()?.getVersion() ?: "UNKNOWN";
```

~~Java's~~ Oracles answer in Java 8 is the `java.util.Optional<T>` but its nowhere near as concise or pretty (modified from their example to achieve the same results as above):

```
String version = Optional.ofNullable(computer).flatMap(Computer::getSoundcard)
                          .flatMap(Soundcard::getUSB)
                          .map(USB::getVersion)
                          .orElse("UNKNOWN");
```

It would be awesome if lombok supported the groovy-esque style operators, probably delegating to the Optional structures under the covers. I know nothing about the lombok internals at this point so have no idea how feasible this is.

**Comment by Maaartinus** [comment]
This is a wonderful demonstration of uselessness of `Optional`. AFAIK Lombok can do nothing here, as it does AST transformations only, but you get no AST as the javac (ecj) parser chokes on `?.` or `?:`. You'd need something syntactically valid like

    String version = computer.$.getSoundcard().$.getUSB().$.getVersion() ?$: "UNKNOWN";

or maybe

     @Nullsafe
     String version = firstNonNull(computer.getSoundcard().getUSB().getVersion(), "UNKNOWN");

and this doesn't look really appealing anymore.

**Comment by askoning** [comment]
More discussion on the feasability of this: see #1280.
