### ISSUE TITLE
version 1.16.8 still fails with jdk 9

### ISSUE THREAD

**Issue by torstenwerner** [rzwitserloot/lombok#1077]
Hi,

I am using build 9-ea+113 which contains the jigsaw module system. Compiling java code fails with:
`Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.file.BaseFileObject
    at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:418)`

My build is actually a gradle build with the following configuration:
    export GRADLE_OPTS='-XaddExports:
    jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED,
    jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED,
    jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED,
    jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED,
    jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED,
    jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED,
    jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED'

**Comment by rspilker** [comment]
I've reformatted the original report in order to compare the parameters.

According to my test as described in #985 you're missing two options:

    jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED,
    jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED

Can you verify that adding those fixes your problem?

**Comment by torstenwerner** [comment]
I have added your options and jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED too but i am still getting the same exception. I can try to extract a sample project that reproduces the error.

**Comment by rspilker** [comment]
Ah, now I've read your original report again, I have something to work with.

**Comment by rspilker** [comment]
We will ship jdk9 support in the next release, probably within a few hours. Please see issue #985 for the latest instructions on the options to pass to the java compiler
