### ISSUE TITLE
@UtilityClass - calling a method declared without 'static' breaks the compilation

### ISSUE THREAD

**Issue by jakub-bochenski** [rzwitserloot/lombok#1082]
I have an `@UtilityClass` which declares a method like this:

```
@Slf4j
@UtilityClass
public class Mdcs {
    public Runnable inContext(Runnable delegate, Map<String, String> headers) {
```

The above method is being called directly, _not_ as a static import, e.g. `Mdcs.inContext(arg0, context)`

One day compilation started to spew a lot of errors for no apparent reason. The errors were not reported on the `Mdcs` class nor on the calling classes but for seemingly unrelated sections of source code.

I started reverting recent changes until I've isolated a fix - adding an explicit `static` modifier to the method

```
-    public Runnable inContext(Runnable delegate, Map<String, String> headers) {
+    public static Runnable inContext(Runnable delegate, Map<String, String> headers) {
```

**Comment by rspilker** [comment]
If I look at the code, both in Eclipse and javac we always add the `static` modifier. What compiler do you use? Eclipse or javac or mvn?

**Comment by jakub-bochenski** [comment]
AFAIR this failed in Maven, but I was using the stock compiler (=javac) there, nothing fancy. I think Eclipse was fine. 
I'll double-check this once I have a bit of time to go back to that revision in our repo.

**Comment by askoning** [comment]
Do you have any more information on this?

**Comment by jakub-bochenski** [comment]
I no longer have access to the code in question
