### ISSUE TITLE
IntelliJ plugin fails "PSI and index do not match"

### ISSUE THREAD

**Issue by Zteve** [rzwitserloot/lombok#1083]
IntelliJ plugin failure.

Attachments (and original names):
1. (Attachment#1.txt) /Users/spowell/.m2/repository/io/projectrreactor/reactor-core/2.5.0.BUILD-SNAPSHOT/reactor-core-2.5.0.BUILD-20160412.121921-507-sources.jar!/reactor/core/util/BackpressureUtils.java_file.txt
2. (Attachment#2.txt) stubTree.txt
3. (null—not attached) stubTreeFromIndex.txt
4. (Details.txt) The details given in the IntelliJ error log, including a stack trace.

[Details.txt](https://github.com/rzwitserloot/lombok/files/216952/Details.txt)
[Attachment#2.txt](https://github.com/rzwitserloot/lombok/files/216953/Attachment.2.txt)
[Attachment#1.txt](https://github.com/rzwitserloot/lombok/files/216954/Attachment.1.txt)

**Comment by AlexejK** [comment]
This is an intellij plugin related issue.
Please report this in https://github.com/mplushnikov/lombok-intellij-plugin including the following:

- IDEA Version used
- Plugin version
- Sample project used to reproduce the problem
- JVM environment

**Comment by Zteve** [comment]
Thank you; I have raised this on the repository you suggest.
