### ISSUE TITLE
About call chaining

### ISSUE THREAD

**Issue by Tconan99** [rzwitserloot/lombok#1088]
Will add the "@Chain" of "call chaining"? I think it's a good idea.

For example,  use the code

@Data
@Chain
@NoArgsConstructor
@AllArgsConstructor
public class Result {
    private BaseService baseService;
    private boolean success = false;
    private String message = "";
    private Object tag;
}

instance of the code

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Result {
    private BaseService baseService;
    private boolean success = false;
    private String message = "";
    private Object tag;

    public Result baseService(BaseService baseService) {
        this.baseService = baseService;
        return this;
    }

    public Result success(boolean success) {
        this.success = success;
        return this;
    }

    public Result message(String message) {
        this.message = message;
        return this;
    }

    public Result tag(Object tag) {
        this.tag = tag;
        return this;
    }
}

**Comment by Maaartinus** [comment]
IIUYC this feature already exists, see https://projectlombok.org/features/experimental/Accessors.html

**Comment by Tconan99** [comment]
Thanks!
