### ISSUE TITLE
Add support for @Specialized

### ISSUE THREAD

**Issue by dcapwell** [rzwitserloot/lombok#1096]
When building a collection that supports generics, if its common to support primitives then the class needs to be rewritten to avoid needing to box.  It would be great if lombok could add a `@Specialized` annotation that would convert generic classes into having specialized versions for primitive types.

**Comment by Rawi01** [comment]
If I understand you correctly you want to generate new classes for each primitve e.g. `IntArrayList`. Lombok does not generate new classes, thats something a regular annotation processor does.

**Comment by rzwitserloot** [comment]
@dcapwell This is a bad idea for many reasons.

1. There are no specialized versions in the core java libraries. There is no `new IntArrayList()`.
2. Had there hypothetically been such a thing, you only gain less than half the benefits for using it. If the API ends up having `public List<Integer> getValues()`, but the actual object this returns is some hypothetical `IntArrayList`, every value you retrieve from this list gets autoboxed.
3. Project Valhalla will fix this, and is not all that far away from java's future.

**Comment by dcapwell** [comment]
thanks for the reply.  Currently I rely on https://github.com/carrotsearch/hppc, but the request was mostly targeted at custom classes which are not provided by hppc; at the moment we manually generate each type when needed.
