### ISSUE TITLE
@setter bug

### ISSUE THREAD

**Issue by lvbolvtian** [rzwitserloot/lombok#1097]
I define three variables in java , like:
```
    @Setter
    private int cityId;
    @Setter
    private int cityID;
    @Setter
    private int cityid;
```

the compile result in xxx.class shows only one set method ,does not have the other two methods , like:

 ```
public void setCityId(int cityId) {
        this.cityId = cityId;
    }
```
no setCityid , no setCityID

**Comment by rspilker** [comment]
It is not a bug since this is the [documented behavior](https://projectlombok.org/features/GetterSetter.html). In the `Small print` section it says:

> No method is generated if any method already exists with the same name (case insensitive) and same parameter count.
