### ISSUE TITLE
Inconsistent creation of java.beans.ConstructorProperties annotation

### ISSUE THREAD

**Issue by mawis** [rzwitserloot/lombok#1099]
I got irritated by the fact, that the addition of the `@ConstructorProperties` annotation is not consistent.

    // Class gets @ConstructorProperties annotation
    @Value public class TestClass {
        private final double foo;
    }

    // Class has *no* @ConstructorProperties annotation
    @Builder @Value public class TestClass {
        private final double foo;
    }

    // Class gets @ConstructorProperties annotation
    @AllArgsConstructor @Builder @Value public class TestClass {
        private final double foo;
    }

In my opinion this is irritating behaviour. Why is the `@ConstructorProperties` annotation removed when there is a `@Builder` annotation but no `@AllArgsConstructor` annotation? If the reason is, that with a `@Builder` the constructors are not meant to be used by the user, than they better should be declared private. At least I propose that the documentation should be clarified. All I have found there is that lombok would by default add this annotation to all constructors with at least one argument.

**Comment by rspilker** [comment]
The reason why you don't get the ConstructorProperties annotation is that the generated constructor is package private. Only protected and public constuctors get the annotation.

According to [the documentation](https://projectlombok.org/features/Builder.html):

> Finally, applying `@Builder` to a class is as if you added `@AllArgsConstructor(access = AccessLevel.PACKAGE)` to the class and applied the `@Builder` annotation to this all-args-constructor. This only works if you haven't written any explicit constructors yourself. If you do have an explicit constructor, put the `@Builder` annotation on the constructor instead of on the class.
