### ISSUE TITLE
Suggestion @AbstractGetter

### ISSUE THREAD

**Issue by ehabrefaat82** [rzwitserloot/lombok#1107]
**Create @AbstractGetter , @AbstractSetter**

example
_With Lombok_ 

```
@Getter
String userName;
```

_Vanilla Java_ 

```
String getUserName(){
return userName;
}
```

---

_With Lombok_ 

```
@AbstractGetter
String userName;
```

_Vanilla Java_ 
`abstract String getUserName();`

**Comment by tafit3** [comment]
You have omitted the userName field in the vanilla version. Do you want AbstractGetter to remove the field leaving only the method, or should you have written the vanilla version as follows:

```java
String userName;
abstract String getUserName();
```
?

**Comment by ehabrefaat82** [comment]
as you wrote

```
String userName;
abstract String getUserName();
```

My Suggestion is to write abstract method, it helps in inheritance, if i want every subclass to initialize this field.

**Comment by tafit3** [comment]
Could you provide an example implementation of getUserName method in two different subclasses?

**Comment by ehabrefaat82** [comment]
If you would like to make an abstract field, you can define it with abstract setter and getter to let children classes assign it's value.

**Comment by tafit3** [comment]
Sure, but why would you want different assignments in the children classes? How would you complete the JuniorAccount and SeniorAccount classes below?

```java
abstract class Account {

    @AbstractGetter
    String userName;

}

class JuniorAccount extends Account {

    String getUserName() {
        ...
    }

    void setUserName(String userName) {
        ...
    }

}

class SeniorAccount extends Account {

    String getUserName() {
        ...
    }

    void setUserName(String userName) {
        ...
    }

}
```

**Comment by oterrien** [comment]
I would also be very interested of this functionality. But it would not be required to define a new annotation. Using the existing ones should be sufficient. 

```
abstract class User {
    @Getter(abstract = true) // abstract = false by default
    String userName;
}

class Me extends User {

   @Override
   public String getUserName(){
   
   }
}
```

**Comment by ehabrefaat82** [comment]
public class MasterBean {
	public long editorScreenId; // should be implemented
}
------
public class ProductBean extends MasterBean {
	// editorScreenId = 70;

	public void setEditorScreenId(long editorScreenId) {
		this.editorScreenId = editorScreenId;
	}
}
------
public class InventoryBean extends MasterBean {
	// editorScreenId = 150;

	public void setEditorScreenId(long editorScreenId) {
		this.editorScreenId = editorScreenId;
	}
}

**Comment by Agraphie** [comment]
I would also be interested in this. Is this still debated?

**Comment by askoning** [comment]
If I understand it right, you want
```
@AbstractGetter String name;
```
to become
```
String name;
public abstract String getName();
```
so that the subclasses are forced to specify their own implementations of this `getName()` method.
Thing is, there's no way to be sure that these implementations use that `name` field, for all I care, my implementation could go
```
@Override
public String getName() {
  return "John Doe";
}
```
while the annotation in combination with the field suggests that there _is_ a relation.
Since no boilerplate code is removed (only a method declaration) the gain is minimal.
To be honest, I don't think this will make it.

**Comment by oterrien** [comment]
It would be interesting for portability to let @Getter and @Setter as is with adding a property to enable abstraction or not. 
Example: @Getter(abstract=true or false) with false by default.

**Comment by omega09** [comment]
@askoning There was a relevant discussion on #1285.

**Comment by askoning** [comment]
Indeed, so we'll resolve this one the same:
Duplicates #1285

**Comment by mkurz** [comment]
Because it's also about getters and setters: What do you think about #1114?
