### ISSUE TITLE
@SneakyThrows hiding compile errors from IntelliJ

### ISSUE THREAD

**Issue by jnape** [rzwitserloot/lombok#1111]
It seems that the SneakyThrows annotation is being transitively applied to all method-scoped lambdas, such that the following does not highlight a compile error in the IntelliJ editor (but of course fails in javac):

``` java
class OverlyOptimistic {

    @SneakyThrows
    public static void main(String... args) {
        Runnable r = () -> {
            //no complaints by the editor
            throw new Exception();
        };
        r.run();
    }
}
```

This issue is immediately exposed by expanding the lambda into an anonymous class:

``` java
class Realistic {

    @SneakyThrows
    public static void main(String... args) {
        Runnable r = new Runnable() {
            @Override
            public void run() {
                //compile error exposed
                throw new Exception();
            }
        };
        r.run();
    }
}
```

Naturally, this is only an issue when the JDK language level is set to 8 or above, where lambdas are supported. Tested with IntelliJ 2016.1.2 64bit on Ubuntu.

**Comment by askoning** [comment]
This seems to be an intellij plugin thing, since the compiler flags it correctly. Since I can still reproduce it in IntelliJ 2016.3.4 and plugin 0.14.16, I've referenced it there.
