### ISSUE TITLE
minor bug in @Builder documentation

### ISSUE THREAD

**Issue by jason-s** [rzwitserloot/lombok#1115]
see https://projectlombok.org/features/Builder.html

```
 public BuilderExampleBuilder occupation(String occupation) {
37       if (this.occupations == null) {
38         this.occupations = new java.util.ArrayList<String>();
39       }
40       
41       this.occupations.add(occupation);
42       return this;
43     }
44     
45     public BuilderExampleBuilder occupations(Collection<? extends String> occupations) {
46       if (this.occupations == null) {
47         this.occupations = new java.util.ArrayList<String>();
48       }
49 
50       this.occupations.addAll(occupations);
51       return this;
52     }
```

Isn't there an `else` missing?

```
 public BuilderExampleBuilder occupation(String occupation) {
37       if (this.occupations == null) {
38         this.occupations = new java.util.ArrayList<String>();
39       }
40       else {
41         this.occupations.add(occupation);
           }
42       return this;
43     }
44     
45     public BuilderExampleBuilder occupations(Collection<? extends String> occupations) {
46       if (this.occupations == null) {
47         this.occupations = new java.util.ArrayList<String>();
48       }
49       else {
50         this.occupations.addAll(occupations);
           }
51       return this;
52     }
```

**Comment by rspilker** [comment]
No, we always need to add the `occupation` or `occupations` to the list, even if we just created the list.

**Comment by jason-s** [comment]
Those semantics are bizarre, though. What it means is that a `null` value (unlike non-null values) causes the list to be cleared... and instead of an empty list, you get a list containing a `null` value.

**Comment by jason-s** [comment]
OH -- never mind, this was a case of programmer dyslexia on my part. I misread the lazy initialization as

 public BuilderExampleBuilder occupation(String occupation) {
37       if (occupation == null) {
38         this.occupations = new java.util.ArrayList<String>();
39       }
40       
41       this.occupations.add(occupation);
42       return this;
43     }
44     
45     public BuilderExampleBuilder occupations(Collection<? extends String> occupations) {
46       if (occupations == null) {
47         this.occupations = new java.util.ArrayList<String>();
48       }
49 
50       this.occupations.addAll(occupations);
51       return this;
52     }

My mistake!
