### ISSUE TITLE
No processor claimed any of these annotations: lombok.Data

### ISSUE THREAD

**Issue by aaron-haskins** [rzwitserloot/lombok#1117]
When building a maven project with **-Werror** compiler option, the projcet produces a warning:
`No processor claimed any of these annotations: lombok.Data`
, and then fails with a compilation error:
`warnings found and -Werror specified`

**Maven compiler:**

    <plugin>
       <groupId>org.apache.maven.plugins</groupId>
       <artifactId>maven-compiler-plugin</artifactId>
       <configuration>
          <showDeprecation>true</showDeprecation>
          <showWarnings>true</showWarnings>
          <compilerArgs>
             <arg>-Werror</arg>
             <arg>-Xlint:all</arg>           
          </compilerArgs> 
       </configuration>
    </plugin>`

**Comment by rspilker** [comment]
To fix this without breaking lombok, I added a second annotation processor that claims all annotations starting with `lombok.`.

Will be in the next release, but is already available in the [edge release](https://projectlombok.org/download-edge.html).

Can you verify this solves your problem, and that lombok still works?

**Comment by aaron-haskins** [comment]
Yes, it builds successfully with this edge release.
Thank you and looking forward to the next release!

**Comment by aaron-haskins** [comment]
I believe this fix causes the problem described in [No processor claimed any of these annotations #6421 ticket](https://github.com/spring-projects/spring-boot/issues/6421). Should it be re-opened?
