### ISSUE TITLE
Builder enhacement request

### ISSUE THREAD

**Issue by muhmud-v** [rzwitserloot/lombok#1120]
Would be possible to have a builder accept a current instance of an object in order to initialise itself? This would let you keep your class immutable but go through the builder to tweak it.

Thanks for some great code!

**Comment by SaltOfTheFlame** [comment]
I use the **_toBuilder_** field in **_@Builder_** annotaion for this now. Try this out

**Comment by muhmud-v** [comment]
Perfect, thanks!!
