### ISSUE TITLE
Bulletproof `assert`

### ISSUE THREAD

**Issue by almson** [rzwitserloot/lombok#1122]
I like the syntax of the assert statement. It's very clean. What I hate are the semantics. I would love to be able to use `assert` for actual checking of preconditions, postconditions, and invariants instead of `if` statements. Here is my proposal:

	@BulletproofAsserts
	public class Foo {
		void bar(int param) {
			assert param >= 0 : new IllegalArgumentException ("param");

			...
		}
	}

becomes:

	public class Foo {
		void bar(int param) {
			if (!(param >= 0))
				throw new IllegalArgumentException ("param");

			...
		}
	}

The assertions become always-enabled and we can pick what exception is thrown. If the expression to the right of `:` is not a Throwable, then we should wrap that object in an AssertionError (as usual).

There is no mechanism to disable the assertions. Disabling assertions is usually a bad idea. It is critically important that invariant checks continue to be done in production. This is because perfect test coverage is impossible, and all production code will have bugs which assertions should help to diagnose and mitigate.

**Comment by rspilker** [comment]
I understand your suggestion and I totally agree that in most cases you want an exception.

However, we're going to reject this feature request.

1) If you allow single line if-statement on the same line, it is about as long, so not a lot of boilerplate to remove:
```java
assert param >= 0 : new IllegalArgumentException ("param");
if (param < 0) throw new IllegalArgumentException ("param");
```
2) You can already fix this with static methods from libraries, like Guava's  [checkArgument(expression, message)](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/base/Preconditions.html#checkArgument(boolean,%20java.lang.Object))
```java
checkArgument(param >= 0, "param");
```
3) If it is not in [Preconditions](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/base/Preconditions.html), it is not boilerplate, and not the domain of Lombok.

Finally, lombok can only work if the java file is a valid file as seen by the parser. I get a syntax error if I use `assert 1 < 0 : throw new RuntimeException()`.

According the JLS the expression after the colon is not allowed to be a `void` expression. And even the parser can see the `throw`, and that is a `void` expression. So even if we would add this to lombok, we're not sure if it will work on all current compatible java compilers and keep working when updates or new versions are installed.

**Comment by almson** [comment]
You have to remove `throw` when writing `assert 1 < 0 : new RuntimeException()`

**Comment by almson** [comment]
The point of `assert condition : new Exception()` vs `Utils.assert (condition, new Exception())` is to salvage the `assert` keyword. The keyword is nice, since it receives IDE highlighting and leaves out extraneous parentheses. I don't think anyone actually uses the keyword (or checks invariants often enough), which is sad.

**Comment by almson** [comment]
Please consider a smaller request: prevent assertions from being disabled by converting `assert condition : object` to `if (!condition) throw new AssertionError (object)`, leaving Java semantics intact.
