### ISSUE TITLE
lombok.equalsAndHashCode.callSuper does not affect warnings in Eclipse

### ISSUE THREAD

**Issue by tterrag1098** [rzwitserloot/lombok#1123]
Setting this config flag to `call` does generate the super calls (see [this](http://pastebin.com/hPi8AbCZ) `@Value` class), however eclipse still displays a warning, i.e.:

> Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.

Adding the annotation as per the warning does solve the issue, but it does not change the output class.

Lombok: 1.16.8
Eclipse: Luna 4.4.2

**Comment by rspilker** [comment]
Are you sure the code generated includes the call to super and that the location of `lombok.config` is correct?

To test this, run `java -jar lombok.jar config g --key=lombok.equalsAndHashCode.callSuper /path/to/your/File.java`. That should display the effective value of given configuration key. If you also supply --verbose (or -v) you can even find out what lombok.config files are being considered, and if they also specify the key and on what lines (just discovered that empty lines are not taken into account).

I've just tested it with the same version of Eclipse and Lombok, and cannot reproduce the described behavior. Also, I've [just added tests](https://github.com/rzwitserloot/lombok/commit/ea219cd7ce76fa1140901050cce73e58f9ddb6d1) and those are also fine.

**Comment by tterrag1098** [comment]
```
X:\Development\MC_1_9\ctb-api-java>java -jar lombok.jar config --key=lombok.equa
lsAndHashCode.callSuper src\main\java\com\creatubbles\api\core\Creation.java
lombok.equalsAndHashCode.callSuper = CALL
```

A clarification, the config is working as expected, the problem is just that I still see the warning in eclipse which says I need to add callSuper=true.

**Comment by koraytaylan** [comment]
not breaking anything but those warnings are bugging me also.

**Comment by rspilker** [comment]
I cannot reproduce this (anymore). Did you do a Project/Clean?
