### ISSUE TITLE
java.util.Optional with @Setter

### ISSUE THREAD

**Issue by foror** [rzwitserloot/lombok#1125]
```     
public class Foo {
    @Getter @Setter
    private Optional<String> bar;
}
```
it may be better to generate for @Setter code like this:
```
public class Foo {
    ...
    public void setBar(String value) {
        this.bar = Optional.ofNullable(value);
    }
}
```

**Comment by rspilker** [comment]
See [this explanation](http://stackoverflow.com/questions/31670785/optional-in-lombok) why we're not going to add this.

**Comment by foror** [comment]
>https://www.voxxed.com/blog/2015/01/embracing-void-6-refined-tricks-dealing-nulls-java/

yeah, your @NonNull realy powerfull feature!
```
public class Foo {
    @NonNull @Getter
    private String bar;

    public void foobar() {
        this.bar = null;
    }
}
```
```
    ...
    Foo foo = new Foo()
    foo.foobar();
    System.out.println(foo.getBar().length() * 10) // uuupppsss
    ...
```

Someone don't understand what is Optional...

**Comment by Tswiggs** [comment]
@rspilker I understand that you all need to prioritize other features first, but I would like to voice my support for an auto optional feature like the one described by @foror.  I work on a production system with millions of potential configurations, optional features and a requirement for backward comparability, so as you can imagine optionals are a abundant in our codebase. I run into this issue constantly and it would be so nice not to have to copy/paste/replace setters and getters. 

Also I love your tool, so thanks for making it :)

**Comment by Maaartinus** [comment]
> yeah, your @NonNull realy powerfull feature!

@foror Indeed it is. Unless you prefer to spend your time by chasing errors caused by forgetting to handle the *absent* case. Most of the time, you needn't do anything, but sometimes you do and then the NPE is a gentle reminder. There is lot of tools issuing a warning for your above code, so just use some.

@Tswiggs Storing `Optional` is an [anti-pattern even according to its author](http://stackoverflow.com/a/26328555/581205). I could imagine going the other way round, i.e. transforming

```
public class Foo {
    @Nullable @OptionalGetter @Setter
    private String bar;
}
```

into

```
public class Foo {
    @Nullable private String bar;

    public Optional getBar() {
        return Optional.ofNullable(bar);
    }

    public void setBar(@Nullable String bar) {
        this.bar = bar;
    }
}
```

Maybe this is something the Lombok authors would more probably support...

**Comment by foror** [comment]
>Storing Optional is an anti-pattern even according to its author
@Maaartinus I don't store Optional, "its purpose is to help design more-comprehensible APIs" and frameworks like jackson, fluent-jdbc and maybe other able to serialize Optional fields. I use this feature in the class fields for a clearer code, because in Java I don't have other official features to show for programmer where the value for the field can be optional.

Declare field as Optional better idea than adding NotNull annotation for required field and leaving other fields without any explanation for the programmer. Example, what means NotNull? It's for validator before write to DB? Or it's for java code? Or it's have other sense? It confuses other programmers.

If a field is NotNull, it should always have some default value. But in some situations, you just need to have an empty class. But with the NotNull you can't create an empty class. And if you can, you will confuse other programmers. With Optional field, the default value is always Optional.empty().

I agree that "You should almost never use it as a method parameter" or a constructor parameter. And that "never use it for something that returns an array of results, or a list of results; instead return an empty array or list" (and use empty array/list as default field value).

**Comment by foror** [comment]
>"You should almost never use it as a method parameter"
But, Lombok does it!
