### ISSUE TITLE
New feature to use thread safe way to lazy get and create instances.

### ISSUE THREAD

**Issue by xeagle2** [rzwitserloot/lombok#1139]
It would be nice to introduce the lazy object creation feature while getting the value with ability to specify the getter prefix and class to instantiate. 

For instance:

**Without lombok**

```java
private volatile List<StringBuilder> content;

public List<StringBuilder> getCreateContent() {
    if (content == null) {
      synchronized (this) {
        if (content == null) {
          content = new ArrayList<>();
        }
      }
    }

    return content;
  }
```

**With lombok**

```java
@CreateGetter(prefix="Create", clazz=ArrayList.class)
private volatile List<StringBuilder> content;
```
Thanks,

**Comment by rspilker** [comment]
You can already do this using [`@Getter(lazy=true)`](https://projectlombok.org/features/GetterLazy.html):

```java
@Getter(lazy=true)
private final List<StringBuilder> content = new ArrayList<>();
```

The resulting code uses `AtomicReference`s, but behaves as your code.

**Comment by xeagle2** [comment]
Unfortunately it's impossible to accomplish this behavior using @Getter(lazy = true), because the option requires field to be private and final (the final is unacceptable in most of the cases).

**Comment by rspilker** [comment]
@xeagle2 Can you explain how the `final` would be a problem? As you can see in [the documentation](https://projectlombok.org/features/GetterLazy.html), the initializer to the field is not run during instance construction, but only when the getter is accessed. 

Regarding the prefix, in your case, you get the same behavior if you would rename the field to `createContent`.

**Comment by xeagle2** [comment]
Yes, prefix shouldn't be an issue here. 

Regarding the final field: 

yes, the field is instantiated later and variable becomes final right after it is initialized, however in some cases for example when the business logic should assign the null to variable or assign a completely new empty instance of object I make getXXX and face NPE, therefore I need to check for null every time what makes a mess in code, so that's why I follow the "get and create" pattern to avoid this.

Additionally the value is accessed by multiple threads, so that's the reason why it is recommended for the operation to be synchronized the last right value is accessed by thread through volatile.

Does it make sense from your point of view?
