### ISSUE TITLE
Add a var annotation

### ISSUE THREAD

**Issue by AugierLe42e** [rzwitserloot/lombok#1140]
`val` is really nice but making the variable final is quite limitating. I think Lombok should have a `var` annotation too for non-final variables, like there is in Kotlin and Scala.

(BTW, I'm curious about how the `val` annotation works. How did you managed to get rid of the `@` without triggering a compilation error?)

**Comment by czyzby** [comment]
> (BTW, I'm curious about how the val annotation works. How did you managed to get rid of the @ without triggering a compilation error?)

Actually, this is not the unusual part. Annotation instances can be assigned to regular variables and do not require `@` operator when used like that. For example, this is a valid Java code line:

```Java
  java.lang.Override annotationInstance = null;
```
You can even initiate it, but keep in mind that its treated as an interface, so you have to implement all methods!

The hard part was convincing the compiler that `val` is not actually a `val` instance.

**Comment by AugierLe42e** [comment]
> The hard part was convincing the compiler that `val` is not actually a `val` instance.

An how did you do that?

**Comment by czyzby** [comment]
I did not, I'm afraid. I'm not even a contributor - I was just browsing through issues and saw your question. Your best bet is to inspect Lombok sources.

**Comment by raderio** [comment]
Any news about this feature?

**Comment by rspilker** [comment]
Yes, `var` already exists: https://projectlombok.org/features/experimental/var

In the upcoming release, we're going to promote it from experimental to stable.

**Comment by rspilker** [comment]
>An how did you do that?

By replacing `val` and `var` just-in-time by the infered type of the initializer.

**Comment by raderio** [comment]
When is expected to release new version with var?

**Comment by AugierLe42e** [comment]
Nice to see that happen. Thx for your work :clap:

**Comment by raderio** [comment]
http://mail.openjdk.java.net/pipermail/announce/2018-March/000247.html
Local-Variable Type Inference                  http://openjdk.java.net/jeps/286
