### ISSUE TITLE
New feature to use thread safe way to lazy get and create instances.

### ISSUE THREAD

**Issue by xeagle2** [rzwitserloot/lombok#1141]
There is a copy of https://github.com/rzwitserloot/lombok/issues/1139, because the previous one has been closed without any discussion.

It would be nice to introduce the lazy object creation feature while getting the value with ability to specify the getter prefix and class to instantiate. 

For instance:

**Without lombok**

```java
private volatile List<StringBuilder> content;

public List<StringBuilder> getCreateContent() {
    if (content == null) {
      synchronized (this) {
        if (content == null) {
          content = new ArrayList<>();
        }
      }
    }

    return content;
  }
```

**With lombok**

```java
@CreateGetter(prefix="Create", clazz=ArrayList.class)
private volatile List<StringBuilder> content;
```
Thanks,

>> You can already do this using @Getter(lazy=true):
>>@Getter(lazy=true)
>>private final List<StringBuilder> content = new ArrayList<>();
>>The resulting code uses AtomicReferences, but behaves as your code.

Unfortunately it's impossible to accomplish this behavior using @Getter(lazy = true), because the option requires field to be private and final (the final is unacceptable in most of the cases).

**Comment by rspilker** [comment]
Can you please continue this conversation in the previous issue #1139 ?

**Comment by xeagle2** [comment]
Sure, thanks!
