### ISSUE TITLE
Is it possible to customize builder?

### ISSUE THREAD

**Issue by fedotxxl** [rzwitserloot/lombok#1144]
1. Can builder call setter (or any other custom method) on setting field value?
2. Is it possible to customize `build` method? Suppose I want to change some values (e.g. trim them) before building. I think calling private custom postBuild method will be a good solution for this problem

**Comment by jmax01** [comment]
If you declare the builder class yourself you can do all sorts of things.

I would try to avoid mucking with generated build methods directly if I needed to modify the values I would do that with setters..

```java
    public static interface WithNumericValue {

        Number getValue();

        public static interface WithNumericValueSetter<BLDR extends WithNumericValue.WithNumericValueSetter<BLDR, VALUE>, VALUE extends Number> {
            BLDR value(VALUE value);
        }
    }

    @Value
    @Builder(toBuilder = true)
    public static class MyClass implements WithNumericValue {

        private Double value;

        public static class MyClassBuilder implements
                WithNumericValue.WithNumericValueSetter<MyClass.MyClassBuilder, Double> {

            @Override
            public MyClassBuilder value(Double value) {
                this.value = value;
                System.out.println("Set value to:" + value);
                return this;
            }

        }
    }
```

**Comment by fedotxxl** [comment]
Simplified solution:

```
@Builder
@Getter
public class Abc {

    private String title;
    private Date createdOn;


    public static class AbcBuilder {

        public AbcBuilder title(String title) {
            this.title = title.trim();
            return this;
        }

    }
}

```

**Comment by fedotxxl** [comment]
But still... is it possible to execute custom logic before building? Suppose I want to print message before object is build

**Comment by alexanderkjeldaas** [comment]
I have a use-case that is similar to this.

In general, the builder interface might not be the same as the value interface.  An example of this:

```
interface ClassWithId {
    Pattern("[^:]+:[^:]+:.*") String id;
}

public class Person implements ClassWithId {
      public Person(String firstIdSection, String lastIdSection) {
         this.id = firstIdSection + ":person:" + lastIdSection;
     }
}

public class Vehicle implements ClassWithId {
      public Person(String firstIdSection, String lastIdSection) {
         this.id = firstIdSection + ":vehicle:" + lastIdSection;
     }
}

```

In this case the `id` field has two `String` values during building of the object, and the object knows how to construct the aggregated `id`.

Configuring what happens in the building step allows the separation of the builder interface and the value interface.

**Comment by julianosam** [comment]
I've been banging my head for hours on this. Came up with this solution. Hope this helps somebody:




```java
@Builder
@Getter
public class Person {

    private String name;
    private String address;

    /**
     * Uses custom builder class
     */
    public static PersonBuilder builder() {
        return new CustomPersonBuilder();
    }

    /**
     * Cusotm  builder class
     */
    private static class CustomPersonBuilder extends PersonBuilder {
        
        @Override
        public Person build() {
            // Validates required fields
            Validate.notBlank(super.name, "Policy Parameter KEY cannot be null or empty!");
            return super.build();
        }
       
    }


}



```

**Comment by wenerme** [comment]
Also, if you don't want to create another builder.

```java

  @Value
  @Builder(toBuilder = true)
  @AllArgsConstructor
  public static class User {
    private String name;

    public static UserBuilder builder() {
      return new UserBuilder(){
        @Override
        public User build() {
          prebuild();
          return super.build();
        }
      };
    }

    public static class UserBuilder  {
      void prebuild(){
        name="const";
      }
    }
  }
```

**Comment by rzwitserloot** [comment]
We've thought about this a lot too and concluded it's just not nice enough to bother including.

You can always make a constructor or static 'factory' method that does your checks, and then slap a `@Builder` on that.

**Comment by Sergey80** [comment]
one more solution: ` .build().validate();`

just add the validate() method that does the validation and returns 'this'

**Comment by nullset2** [comment]
@Sergey80 but the issue with that is that you end up exposing an inconsistent interface to whoever will use your code. You're basically asking them to run `.validate()` at every step of the way, which sort of defeats the purpose of the builder to begin with.

**Comment by Sergey80** [comment]
I know. It is just I did not find another way.  another way to create your own builder without Lombok (which I do not want).
none of these above didn't help me. 
In my case, were is nobody but my app will use my code, validate() is a consistent interface, but depending on the problem it may not be so.
What I put is work-around, not a solution.

**Comment by fabiencelier** [comment]
@julianosam 

Your solution is nice but it does not work with a `toBuilder()` method's as it won't use your custom builder:

```java
@Builder(toBuilder = true)
@Getter
public class Person {

	private String name;
	private String address;

	/**
	 * Uses custom builder class
	 */
	public static PersonBuilder builder() {
		return new CustomPersonBuilder();
	}

	/**
	 * Custom  builder class
	 */
	private static class CustomPersonBuilder extends PersonBuilder {

		/** Validates required fields. */
		private void validate() {
			if (super.name.isBlank()) {
				throw new IllegalArgumentException("Persons NAME cannot be null or empty!");
			}
		}

		@Override
		public Person build() {
			validate();
			return super.build();
		}

	}

	public static void main(final String[] args) {
		final Person person = Person.builder().name("OK").build(); // OK

		person.toBuilder().name("").build(); // should fail but is OK

		Person.builder().name("").build(); // fails

	}


}
```

I have an alternative solution which consists in using 2 build methods:

```java
@Builder(toBuilder = true, buildMethodName = "buildWithoutValidation")
@Getter
public class Person {

	private String name;
	private String address;

	/**
	 * Custom  builder class
	 */
	private static class PersonBuilder {

		public Person build() {
			final Person person = buildWithoutValidation();
			validate(person);
			return person;
		}

		private static void validate(final Person person) {
			if (person.name.isBlank()) {
				throw new IllegalArgumentException("Persons NAME cannot be null or empty!");
			}
		}

	}

}
```

This behave as expected and works with `toBuilder`, however this exposes a new public method called `buildWithoutValidation` to the API with is not super clean as it allows the user to build invalid objects.

To be 100% clean, we would need some protected `preBuild()` and `postBuild()` hooks to override, or a protected `buildInternal()` methods so we can easily override the `build()` method and call `buildInternal()`
