### ISSUE TITLE
Do you want a website makeover?

### ISSUE THREAD

**Issue by tipsy** [rzwitserloot/lombok#1149]
I decided to spend a few hours on giving the website a makeover. So far I've only made the frame and the credits page, mainly to find out if GitHub-pages was a viable option. Check it out:

https://projectlombok.github.io/ (website source [here](https://github.com/projectlombok/projectlombok.github.io))

GitHub pages seems like it will work fine. Please let me know if you want me to continue working on this.

Edit: Added some more stuff. Still trying to figure out how to actually structure all the information contained on the current website.

**Comment by tipsy** [comment]
@rzwitserloot maybe?

**Comment by rspilker** [comment]
We really do want a website makeover. But one of the constraints is that we want to be able to build at least part of it as part of the release process.

One of the reasons is that we automatically update the website as part of a release. That way we can also render the changelog, and for an edge-release, we generate a special changelog.

Is that something you could work with?

**Comment by tipsy** [comment]
> @rspilker one of the constraints is that we want to be able to build at least part of it as part of the release process. ... Is that something you could work with?

Could you elaborate a bit on what's being generated automatically and how? In general I don't think it would be a problem for me, but it might exclude GithHb-pages as a CMS/hosting solution. Do you still want the website to be part of this repo?

**Comment by tipsy** [comment]
@rspilker @rzwitserloot Had a chance to look at this yet?

**Comment by btiernay** [comment]
Any word on this. No offense, but this version is much easier on the eyes :)

**Comment by rspilker** [comment]
Yes, we are using this design, but with a different implementation. We expect some results soon, but it is quite some work.

**Comment by stepio** [comment]
New design is nice, but it's not readable  on small screens, worse then the old one. At least in portrait mode - landscape is more or less fine.

**Comment by tipsy** [comment]
Looks like there's a new website now, so I'll close this.
