### ISSUE TITLE
new function suggestion

### ISSUE THREAD

**Issue by sdw2332** [rzwitserloot/lombok#1151]
could you please add the javadoc on the field to it's generated methods?

for example.
@Data
public class App {
	
	/**
	 * str field
	 * @note it's just a simple str field
	 */
	private String str;
	
}

i hope the generated methods is like below:
	/**
	 * @param str str field
	 * @note it's just a simple str field
	 */
	public void setStr(String str) {
		this.str = str;
	}
	
	/**
	 * @return str field
	 * @note it's just a simple str field
	 */
	public String getStr() {
		return str;
	}

thanks!

**Comment by Shredder121** [comment]
Exerpt from https://projectlombok.org/features/GetterSetter.html

> _NEW in lombok v1.12.0:_ javadoc on the field will now be copied to generated getters and setters. Normally, all text is copied, and `@return` is _moved_ to the getter, whilst `@param` lines are _moved_ to the setter. Moved means: Deleted from the field's javadoc. It is also possible to define unique text for each getter/setter. To do that, you create a 'section' named `GETTER` and/or `SETTER`. A section is a line in your javadoc containing 2 or more dashes, then the text 'GETTER' or 'SETTER', followed by 2 or more dashes, and nothing else on the line. If you use sections, `@return` and `@param` stripping for that section is no longer done (move the `@return` or `@param` line into the section).
