### ISSUE TITLE
[Feature Request] ToString inclusion of super fields?

### ISSUE THREAD

**Issue by oleersoy** [rzwitserloot/lombok#1158]
http://stackoverflow.com/questions/38417662/can-lombok-tostring-include-a-field-from-a-supertype-without-using-callsuper

**Comment by rspilker** [comment]
As already suggested in the stackoverflow comments, this is not a common scenario, therefore not boilerplate. Also, there is some interaction with other settings like when to use direct field access and when to use getters.

A toString method is for debugging purposes only. If it becomes part of you API you definitely want to have a handwritten toString method including Javadoc to explain the format.

So as far as I'm concerned, the maintenance burden and added complexity for the user outweigh the benefits.
