### ISSUE TITLE
Define excludes from @ToString and @EqualsAndHashCode on the field

### ISSUE THREAD

**Issue by srsp** [rzwitserloot/lombok#1163]
At the moment the only way to exclude fields from `@ToString` or `@EqualsAndHashCode` is: 

```
@ToString(exclude = "bar")
@EqualsAndHashCode(exclude = "bar")
public class Foo {

  private String bar;

}
```

I think something like this would be nice:

```
@ToString
@EqualsAndHashCode
public class Foo {

  @ToStringExclude
  @EqualsAndHashCodeExclude
  private String bar;

}
```

I would prefer this solution for several reasons:
- You don't have to type the field's name.
- Less hassle when renaming or deleting the field.  
- The information of whether the field is included / excluded in `@ToString` is bundled with field definition.

The annotation name is just an idea. You could also consider something in lines of `@ToString(exclude = true)` on the field.

What do you think?

**Comment by rzwitserloot** [comment]
Working on it: https://github.com/rzwitserloot/lombok/wiki/FEATURE-IDEA:-Annotation-based-Include-Exclude-for-ToString,-EqualsAHC,-etc
