### ISSUE TITLE
JBoss Developer Studio 10 - fails to install lombok

### ISSUE THREAD

**Issue by mwelser** [rzwitserloot/lombok#1164]
Lombok 1.16.10 does not detect JBDS 10 under OS X.

**Comment by dozherel-ucop** [comment]
same here...  can't install Lombok on Jboss Developer Studio 10 under Windows.

**Comment by jludvice** [comment]
Hello, I had the same issue and there might be workaround.
During the installation lombok needs to copy `lombok.jar` and modify `eclipse.ini`.

In RHDS 10 the file is called `devstudio.ini`. Try to add symlink to this file :)

```bash
$ cd $RHDS_INSTALL
$ find . -name "devstudio.ini"
./studio/devstudio.ini
$ cd studio
$ ln -s devstudio.ini eclipse.ini
```

Try to install lombok to folder `$RHDS_INSTALL/studio`. It worked for me.

**Comment by rspilker** [comment]
Can you try out the [edge release](https://projectlombok.org/download-edge.html) and see if it works now?
