### ISSUE TITLE
@AllArgsConstructor(staticName = "of") - generated private ctor doesn't have @ConstructorProperties

### ISSUE THREAD

**Issue by eeichinger** [rzwitserloot/lombok#1180]
When setting "staticName", the generated private constructor doesn't get @ConstructorProperties annotation applied, which makes the use with Jackson hard

**Comment by djendroska** [comment]
I have the same issue, also when using Lombok with Jackson. The problem also appears when I use `@Value(staticConstructor = "of")` and `@Value(staticConstructor = "of")`.

**Comment by rspilker** [comment]
Fixed in ae54fa51ac6162a53dc0ac424d0ba17cdac89ba3, will be in the next release, exepected winin a few hours.
