### ISSUE TITLE
Ability to annotate the base class with @Getter(inherit=true) @Setter(inherit=true)

### ISSUE THREAD

**Issue by mih-kopylov** [rzwitserloot/lombok#1181]
```
@Getter (inherit=true)
@Setter (inherit=true)
public class Base{
  private Long id;
}
public class Extend extends Base{
  private String name;
}
```

I'd like to have ability to annotate base class with `@Getter` and `@Setter`, do not annotate all his successors, but have getters & setters generated for successors.

Is this possible?

**Comment by cmckn** [comment]
I thought I needed this today, but have decided against the idea.

I'm using lombok to flesh out  "configuration" classes for Dropwizard applications. I thought It'd be really neat to enable an experimental feature like `@Accessors( chain = true )` across all of my configurations by adding it to a base class. However, my "best practice" opinion: this would be an inappropriate usage of lombok. If a reader happens upon `Extend.java` they'd have no expectation that the compiled class would define accessors. I think this would diverge too far from the behavior and interface users have come to expect from both `javac` and annotations. Lombok eliminates a lot of verbosity already -- best to just stick with class definitions that are concise *and* complete.

**Comment by janrieke** [comment]
I agree. And besides: This requires resolution and is, thus, very difficult to impossible to implement.

**Comment by rspilker** [comment]
Without any judgment on the merits, [resolution](https://github.com/rzwitserloot/lombok/wiki/LOMBOK-CONCEPT:-Resolution) is a very big problem.
