### ISSUE TITLE
@Value makes static field with default visibility appear private

### ISSUE THREAD

**Issue by methylene** [rzwitserloot/lombok#1187]
Assuming Alice and Bob are top level classes in the same package.
Then the following doesn't compile:

``` java
package secrets;

@lombok.Value
class Alice {
    static String MESSAGE = "Hi Bob";
}
```

``` java
package secrets;

class Bob {
    final String message = Alice.MESSAGE;
}
```

Compilation fails with this message:

> Bob.java:[4,32] error: MESSAGE has private access in Alice

**Comment by chaitan64arun** [comment]
I couldn't reproduce this issue. 

Compilation was successful. I could also print Bob.message successfully at runtime.

I tried to reproduce it with 1.18.6 version

**Comment by rspilker** [comment]
We do have starts for this:
The code [before](https://github.com/rzwitserloot/lombok/blob/master/test/transform/resource/before/ValueStaticField.java) gets transformed into after in [javac](https://github.com/rzwitserloot/lombok/blob/master/test/transform/resource/after-delombok/ValueStaticField.java) and [eclipse](https://github.com/rzwitserloot/lombok/blob/master/test/transform/resource/after-ecj/ValueStaticField.java).

What compiler do you use? Could this be an IntelliJ problem?

**Comment by rspilker** [comment]
No response from reporter, closing issue
