### ISSUE TITLE
More readable Builder interface

### ISSUE THREAD

**Issue by xasx** [rzwitserloot/lombok#1200]
By generating two more methods alongside with `builder()` and related stuff, readability could be improved further:

``` java
// wrap the builder
static SomethingBuilder $Something() { return Something.builder(); }

// wrap the build
static Something a(SomethingBuilder builder) { return builder.build(); }

```

glued together plus prefixing all properties with `with`, they would allow for

``` java

Something something = a($Something.withProperty("whatsoever"));

```

Any opinions on that?
The idea is inspired by some recent ix magazine article.

**Comment by rzwitserloot** [comment]
... no.

The discoverability of this is in the dumps. You'd have to know you have to write that. That's not how normal people write java code. They guess at what class they probably want, type it in, and hit ctrl+space, and then hunt for something that sounds useful.
