### ISSUE TITLE
Eclipse: Duplicate field error when using Singular

### ISSUE THREAD

**Issue by vbhavdal** [rzwitserloot/lombok#1203]
The class below leads to "Duplicate field Foo.FooBuilder.strings" errors in Eclipse, whereas it's fine in IntelliJ as well as when building with maven manually. 

Lombok 1.16.10
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Fully patched Eclipse 4.6.1 with Lombok installed using installer. 
OSX 10.11.6

```
@lombok.Value
@lombok.Builder(toBuilder = true)
public class Foo {

    @lombok.Singular
    private java.util.List<String> strings;

    @lombok.Builder(toBuilder = true)
    private Foo(final java.util.List<String> strings) {
        this.strings = strings;
    }

}
```

**Comment by rzwitserloot** [comment]
But this IS an error; you're asking lombok to generate builders, twice, and the names conflict.

Lombok should produce a better error message, and should consistently error across all platforms, but 'error' is the correct response.

This is a mirror of #730
