### ISSUE TITLE
Where is lombok-api.jar?

### ISSUE THREAD

**Issue by aggro80** [rzwitserloot/lombok#1204]
Almost every project provides api-jar, e.g.
<groupId>org.hibernate.javax.persistence</groupId>
<artifactId>hibernate-jpa-2.1-api</artifactId>

<groupId>com.fasterxml.jackson.module</groupId>
<artifactId>jackson-module-jaxb-annotations</artifactId>

This makes it possible to use various annotations in your own api-packages and share those without heavy dependencies. But Lombok is different, there is no public lombok-api.jar provided with the lombok.jar. Instead one is adviced to create api.jar yourself. Sure, I could create it but how do I then distribute it. I don't understand why doesn't lombok provide api.jar at the same time when it distributes the lombok.jar, because then it would be trivial and easy to use.

This is a bit of a showstopper for using Lombok in any api. Especially since the work-a-round, delombok doesn't work properly ( https://github.com/rzwitserloot/lombok/issues/219 ). I would imagine that creating such a jar should be quite trivial if it can be created with a single command?

**Comment by Maaartinus** [comment]
According to this [SO answer][SO], the `api.jar` is what you need for compiling. That's the whole `lombok.jar` as the annotation work at compile time and you need the whole lombok for it to work.

All your example libraries work with annotations used at run time. If you distribute their `*-api.jar`, others can compile them. If you distributed `lombok-api.jar` containing annotations only, no-one could compile it (because of missing getters etc.), so I'm unsure if it could help you.

[SO]: http://stackoverflow.com/a/9819775/581205

**Comment by aggro80** [comment]
I started testing this to prove my point, but then I figured out that the lombok-api.jar is actually not necessary if you mark the dependency in pom.xml to "provided" scope, maven will use lombok during the compilation and generate all the getters and setters. 

<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<version>1.14.8</version>
	<scope>provided</scope>
</dependency>

And when you use this in another project, the lombok dependency is no longer needed. This works at least with:
@Getter
@Setter
@EqualsAndHashCode
@AllArgsConstructor

 I'm not sure if some annotations cause problems, but it seems that during the compile phase, the lombok annotations are also removed from the generated jar.

As far as I can tell, this solution works for me and this ticket can be closed,  unless you want to use it as an opportunity to improve documentation somewhere.

**Comment by Maaartinus** [comment]
Lombok is no run time dependencies (`lombok-impl.jar` would be empty). When you distribute your jar, lombok has already done its job, and at runtime, unknown annotations [get simply ignored][a], too.

So feel free to close this (I can't; I'm neither the OP nor a project maintainer).

[a]: http://stackoverflow.com/a/3568041/581205
