### ISSUE TITLE
javadoc is not being generated for lombok annotated field

### ISSUE THREAD

**Issue by anidotnet** [rzwitserloot/lombok#1208]
If I have a class like as below and a lombok annotated field,

``` java
public class Main {
    /**
     * Determines if it is opened in readonly mode.
     *
     * @return true if it is opened in readonly mode; otherwise false.
     * */
    @Getter @Setter(AccessLevel.PACKAGE)
    private boolean readOnly;
}
```

lombok is not generating javadoc for readOnly. The getter is missing from javadoc. It is not recognising it as a public entity. I am using gradle-lombok plugin - https://github.com/franzbecker/gradle-lombok. And here is my config

``` groovy
buildscript {
    repositories {
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
        maven { url "https://plugins.gradle.org/m2/" }
        jcenter()
        mavenCentral()
        mavenLocal()
    }
    dependencies {
        classpath "io.franzbecker:gradle-lombok:1.7"
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.3'
    }
}

apply plugin: 'io.franzbecker.gradle-lombok'

lombok {
        version = "1.16.10"
        sha256 = ""
    }

repositories {
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
        mavenLocal()
    }
```

I raised an issue in the gradle-lombok plugin repo here - https://github.com/franzbecker/gradle-lombok/issues/13, but the author says it might be a lombok issue.

I am using gradle 3.1 with JDK 8 and generating javadoc using `./gradlew javadoc`

**Comment by franzbecker** [comment]
This is not an issue with the plugin or with Lombok but a configuration issue as pointed out here: https://github.com/franzbecker/gradle-lombok/issues/13#issuecomment-256376930
