### ISSUE TITLE
Feature Request: Add @NoSetter annotation

### ISSUE THREAD

**Issue by seb0stian** [rzwitserloot/lombok#1210]
Right now, if you want to set setters for attributes in a class 
you can 
a) write @Setter above the class or
b) write @Setter above every attribute that you think should have one, individually.

I suggest you add @NoSetter to make it possible to simplify the coding if you only want one attribute not to have a setter.

```Java
//current:

@Getter
...
public class PrivateCustomer extends AbstractCustomer {

private long id;

@Setter
private String name;

@Setter
private String email;
}


//new:

@Getter
@Setter
...
public class PrivateCustomer extends AbstractCustomer {

@NoSetter
private long id;

private String name;

private String email;
}
```

**Comment by Maaartinus** [comment]
Use `@Setter(AccessLevel=NONE)` on the field.
