### ISSUE TITLE
Add a @Dirty annotation

### ISSUE THREAD

**Issue by KangoV** [rzwitserloot/lombok#1212]
I've been trying to find some way of creating simple classes with getters and setters that can track changes. What I'm thinking is that when Lombok  encounters a class with `@Dirty`, the setter methods would be written in such a way that the changes are added to an internal map.

The following methods would then be added:

`boolean isDirty()`
`Map<String,Object> getChanges()`
`void reset()`

Of course this would only work for `@Data` and not `@Value`. It would be a little more complex, but if a builder was involved and had `toBuilder=true`, then the builder could copy the values and flag a change is the builder overrides the value. This would then work for immutable classes with `@Value`.

**Comment by ChrisBrenton** [comment]
Intuitively, this doesn't particularly feel like an addition that is geared toward the boilerplate elimination of Lombok. It feels like quite a specific task that you would need. Perhaps an interface should be used in place of this?

**Comment by rzwitserloot** [comment]
Any new feature proposal must be evaluated based on comparing a great many things:

* How much boilerplate does this remove?
* How often do projects in general run into the scenario where you'd need this?
* How confusing might it be to someone who sees this lombok feature in use without knowing it? How 'self evident' is it?
* How much effort is it to add this to lombok.

And this one seems to miss the requisite numbers by a large margin.

**Comment by KangoV** [comment]
I suppose this one is quite specific to our use case. I've been trying to solve this by using Bytebuddy and the interface listed above. The idea is to have an instant dirty tracking object without having implement any of the setters to catch changed values.

**Comment by silkentrance** [comment]
The boilerplate it removes is implementing your own setters, set the dirty flag if the new value is different from the existing value and then optionally set the value.

I.e.

```
public void setSomething(Something something) {
   if (!Objects.equals(m_something, something)) {
     m_dirty = true;
     m_something = something;
  }
}
```
