### ISSUE TITLE
Eclispe broken formatting with @Singular

### ISSUE THREAD

**Issue by cdallagnola** [rzwitserloot/lombok#1220]
Hello,

I've got a problem with the @Singular annotation.
Taken a code like this, when I save, the automatic formatting gives something like:

Do you have the same behavior ?

```

@Value
@Builder(toBuilder = true)
@NoArgsConstructor(force = true)
@AllArgsConstructor
public class MyClass {

    @Singular
    private final Map properties;
```

```

@Value
final final final final final final final final final final final final final @Builder(toBuilder = true) @NoArgsConstructor(force = true) @AllArgsConstructor public class MyClass {

    @Singular
    private final Map properties;
```

Thanks a lot

**Comment by cdallagnola** [comment]
Up please, it's really annoying.

**Comment by MLuet** [comment]
Hi,
I can reproduce this problem. It seems to happen if  **@Singular** and **@Builder** are used within the same class:

`@Builder
final public class FormatFail implements ITest {

    @Singular
    Set<Integer> foos;
}
`

**Comment by Maaartinus** [comment]
This happened to me, too, and I'm rather sure, I was using different annotations. My conclusion was that this happens during save actions, whenever there's some special compilation error. It used to happen rather often, but it's got much better (I haven't seen this for maybe one year).

Sometimes, fixing the problem and temporarily commenting out some annotation helped. At other times, I had to temporarily switch save actions off, clean up the mess and save the file. Thereafter, everything worked well for a while.

**Comment by rzwitserloot** [comment]
I cannot reproduce this; I turned on save actions, turned on 'format my code', and in the actions, turned on every checkbox I could find that mentions 'final', and then I made this file, and saved:

	@Value @Builder(toBuilder = true) @NoArgsConstructor(force = true) @AllArgsConstructor public class TestFooLombok {
		private @Singular final List<String> foos;
	}

give this another shot with the edge release from https://projectlombok.org/download-edge and reopen the issue if there's still a problem? Please include details that seem relevant for me to try and reproduce it (including the exact source you use, the exact settings of your save actions, which version of eclipse, etc).
