### ISSUE TITLE
Hashcode generation: enum ordinal option?

### ISSUE THREAD

**Issue by Xorlev** [rzwitserloot/lombok#1223]
This is more of a request for discussion than an issue, and if this proposal is interesting I'd be happy to spearhead a PR to implement it. In any case let me start by saying that we love Lombok. We use it almost everywhere we can to drastically simplify the amount of code we have to write. We're huge fans of `@EqualsAndHashcode` and other annotations that use it such as `@Value`. However, one place where we struggle with Lombok is enum hashcodes. 

This isn't fundamental to Lombok in any way, but more a sad consequence of how enums work under the hood. Enums are assigned a random 32-bit integer as hashcode (aka the identity hash code). Enum hashcodes aren't wrong. In isolation, it makes the most sense as a means by which an individual enum case can be identified safely. However, they're pretty inconvenient when composed as a part of a POJO's hashcode as things like set ordering become inconsistent across runs of your application. For us, this often presents as two servers serving JSON payloads which are semantically equal but not byte equal.

You could argue that you should never rely on set semantics (or hashcode semantics) across JVMs anyways as hashcode generation isn't intended to be stable across JVMs (especially JVM versions), however it's a footgun ready to breed inconsistent behavior. We've found cases where scoring algorithms use sets internally and end up with slightly different behavior across machines.

For the cases where we have POJOs that contain enums, we usually end up hand-defining the hashcode method, and incorporate the enum via its ordinal. e.x.:

```java
    @Override
    public int hashCode() {
        int result = coverage.ordinal();
        result = 31 * result + term.hashCode();
        return result;
    }
```

I would like to propose adding a hashcode generation option to include enums as their ordinal. There's a few special cases to handle here, such as multiple enums in the same POJO & ensuring that those are represented uniquely, or a POJO having a single field that is that enum. The ordinal alone isn't sufficient, but perhaps the combination of the hashcode of the enum classname + the ordinal would be enough in those cases.

If this is something you'd potentially be willing to accept upstream, I'd be happy to give it a go and start the conversation that way.

**Comment by Xorlev** [comment]
I did just run across [Improve @Tolerate, so it really works with @EqualsAndHashCode](https://github.com/rzwitserloot/lombok/pull/52) which doesn't give me much hope that this'll be a popular proposal. I do think there's value in deterministic hashcodes as the non-determinism of enums have bitten us more than once. However, it is perhaps more niche than I'd thought.

**Comment by rspilker** [comment]
Right now we just call the hashCode and equals method on all reference type variable. This is something we can determine compile time. We do that by excluding all built-in types and arrays, and what remains is an Object. Unfortunately, we are currently unable to use resolution to inspect the concrete type of a reference field. So we don't know if it is an enum.

We could determine it in the generated code at runtime, but that would impact the performance of all hashCode implementations.

Also, if you have a collection's hashCode method or Array.deepHashCode, those will still use the enum's built-in hashCode. 

I think this is something for the JDK to solve.

**Comment by Xorlev** [comment]
Fair enough. Thanks for the time! :)
