### ISSUE TITLE
@Tolerate not working for @Builder methods?

### ISSUE THREAD

**Issue by nakagawa-atsushi** [rzwitserloot/lombok#1230]
**Using lombok version:** 1.16.10
**IDE:** Eclipse Neon.1a Release (4.6.1)

According to [this StackOverflow answer](http://stackoverflow.com/a/33998171/1036728), `@Tolerate` supposedly prevents lombok from not generating a method due to signature conflicts.  `@Tolerate` however does not seem to prevent this with `@Builder`'s field methods:

### Example of `@Tolerate` not working:
```java
@lombok.Builder
public class Foo {
	private final int value;

	public static void main(String[] args) {
		Foo.builder().valueAsString("42").build();
	}

	public static class FooBuilder {
		@Tolerate
		public FooBuilder value(String s) {
			return this.value(Integer.parseInt(s));
		}
	}
}
```
```
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	The method value(String) in the type Foo.FooBuilder is not applicable for the arguments (int)

	at Foo$FooBuilder.value(Foo.java:19)
	at Foo.main(Foo.java:12)
```

### Working alternative 1:

```java
@lombok.Builder
public class Foo {
	private final int value;

	public static class FooBuilder {
		public FooBuilder valueAsString(String s) {
			return this.value(Integer.parseInt(s));
		}
	}
}
```

### Working alternative 2:

```java
@lombok.Builder
public class Foo {
	private final int value;

	public static class FooBuilder {
		public FooBuilder value(String s) {
			return this.value(Integer.parseInt(s));
		}

		public FooBuilder value(int value) {
			this.value = value;
			return this;
		}
	}
}
```

**Comment by bulgakovalexander** [comment]
I haven't found a code in the project that implements support `@Tolerate` for `@Builder`. Only for `@Getter`, `@Setter` and `@Wither`. 
I made branch with this supporting ([link](https://github.com/bulgakovalexander/lombok/tree/bugfix/builderWithTolerate)). But I think it is no good idea. Maybe we should try to improve the builder code to support such behavior without @Tolerate?

**Comment by nakagawa-atsushi** [comment]
> But I think it is no good idea. Maybe we should try to improve the builder code to support such behavior without @Tolerate?

If you mean to do this by comparing parameter types to check whether the same [method signature](https://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.4.2) exists, I agree that's a better idea.

I think the same however can be said about `@Getter` / `@Setter` / `@Wither`.

**Comment by Maaartinus** [comment]
> If you mean to do this by comparing parameter types to check whether the same method signature exists, I agree that's a better idea.

I don't thing so:
- Checking same method signature when generics are involved is rather complicated.
- Due to how lombok works, the needed information mayn't be  available.
- Due to erasure, methods having different signatures may conflict.

While using `@Tolerate` is slightly more verbose than optimal, it prevents problems.
