### ISSUE TITLE
Support @Value with optional getters

### ISSUE THREAD

**Issue by olivergierke** [rzwitserloot/lombok#1237]
I very often find myself a situation where I want *all* traits of `@Value` but don't want to expose the components making up that value via getters. That leaves me two options:

1. An additional `@Getter(access = AccessLevel.PRIVATE)` to hide them from the outside but that generates unnecessary code. It's also sort of breaking the general usage pattern to add annotations to add functionality. Now I am adding one, to prevent stuff from happening.

2. I can go back to listing all annotations that make up `@Value` myself but I would have to repeat that over and over again. Fixing #557 would mitigate this problem a lot.

**Comment by rspilker** [comment]
You could also prefix the fields that you want to exclude with `$`.

**Comment by rspilker** [comment]
If you don't want any getters, you could also put `@Getter(AccessLevel.NONE)` on the type.

**Comment by olivergierke** [comment]
Well, that's sort of equivalent to number one I described above. Without being able to use Lombok annotations as meta-annotations (#557) that still means I scatter the very same set of annotations around my codebase.
