### ISSUE TITLE
Support auto generation of constants for field names

### ISSUE THREAD

**Issue by yuflyud** [rzwitserloot/lombok#1240]
It would be great if Lombok provided some annotation to generate constants for field names. E.g.:
```
class User{
String name;
}
```
to
```
class User{
public static final String NAME_PROP="name";
String name;
}
```

I use multiple JPA annotations that refer to field properties and it is hard to maintain the consistency when the name of the field changes. In case of constants - the compilation error would occur. Sample:
`@UniqueConstraint(columnNames = { "policyId", "tenantId" })`
to
`@UniqueConstraint(columnNames = { Policy.POLICY_ID_PROP, Tenant.TENANT_ID_PROP })`

There is no a huge need for this feature, but I find it useful in some situations so decided to share.

**Comment by vadipp** [comment]
#46 was merged, so this issue should be closed, imo.
