### ISSUE TITLE
@Builder.ObtainVia is not working for me

### ISSUE THREAD

**Issue by rfgamaral** [rzwitserloot/lombok#1244]
I'm using the latest v1.16.10 of Lombok and `@Builder.ObtainVia` is not working for me.

Here's my code:

```java
@Builder(builderMethodName = "newBuilder", toBuilder = true)
public class Data {

    private String foo;

    private String bar;

    @Builder.ObtainVia(method = "generate")
    private String baz;

    private String generate() {
        return foo.concat(bar);
    }
    
}

Data data = Data.newBuilder()
    .foo("FOOOOOOO")
    .bar("BAAAAAAR")
    .build();
```

**Expected:** `data.baz = "FOOOOOOOBAAAAAAR"`
**Result:** `data.baz = null`

What am I doing wrong?

**Comment by Maaartinus** [comment]
I guess, you're expecting something it just doesn't do. Try
```
Data.newBuilder()
    .foo("FOOOOOOO")
    .bar("BAAAAAAR")
    .build()
    .toBuilder()
    .build();
```
AFAIK, this is only relevant for `toBuilder`. Otherwise, there's no place where the method could be called.

**Comment by rfgamaral** [comment]
You are right, I expected it to do something it doesn't do. To obtain the value automatically during the `build()` phase without explicitly setting such field.

I actually came here to post that as I just found that same solution. Seems a bit too much boilerplate to me, something Lombok aims to reduce.

All in all, I was expecting that this `@Builder.ObtainVia` annotation would set the field for me automatically **and** hide the set method from the builder. It does neither. Hopefully something like this could be added (or perhaps another annotation to actually hide some fields from the Builder as I've seen this being requested a couple of times.

What do you think?

Feel free to close this whenever you want :)

**Comment by Maaartinus** [comment]
> To obtain the value automatically during the build() phase without explicitly setting such field.

For calling the method, you need the `Data` object first. My "solution" is obviously inefficient and ugly.

> I was expecting that this @Builder.ObtainVia annotation would set the field for me automatically and hide the set method from the builder.

You simply thought about something working exactly in the opposite direction. It makes sense, but you'd need a method on the `builder` for this to work. Something like
```
@Builder(builderMethodName = "newBuilder", toBuilder = true)
public class Data {
     class Builder {
       private String generate() {
         return foo.concat(bar);
       }
     }
   
    private String foo;

    private String bar;

    @Builder.NiatboAiv(method = "generate")
    private String baz;
}
```

Hiding the setter should probably be optional.

> Feel free to close this whenever you want. :)

I'm not a project owner. :)

**Comment by rfgamaral** [comment]
Well, I'm currently using that "inefficient and ugly" solution as I can't think of another work around... Well, I can think of one alternative.

Have an instance method inside `Data` that sets `baz` with `foo.concat(bar)` and `return this` and then call that method after calling `.build()`. Probably more efficient but still slightly ugly.

Is there any other alternative? From the two, which would you pick and why?

> I'm not a project owner. :)

I saw "contributor" and thought you manage this too...

**Comment by rspilker** [comment]
In your class `Data` you could add the following:

    @Getter(lazy = true)
    private final String baz = generate();

You do need to call the getter instead of doing direct field access. If you only need the getter in the type itself, you can also add `access = AccessLevel.PRIVATE` to the Getter annotation.
