### ISSUE TITLE
Provide possibility to define @EqualsAndHashCode by using interfaces 

### ISSUE THREAD

**Issue by Scheka007** [rzwitserloot/lombok#1245]
Please provide possibility to define @EqualsAndHashCode by using interfaces

**Comment by rspilker** [comment]
I have no idea what that means.

**Comment by Scheka007** [comment]
Oh,
may i should provide some example to make it clear.

Let have an interface "User"

public interface User {
    String  getUserName();
}

Let have two classes which implements this interface, one is mutable, the second immutable.
I want to be able to use equals method to compare the mutable instane with the immutable one.
Therefore it's enough for me if only the interface related equals will be used, such kind of follow.

@EqualsAndHashCode(of=User.class)
public class MutabaleUser implements User {

    @Getter
    @Setter
    private String userName;

}

@EqualsAndHashCode(of=User.class)
public class MutabaleUser implements User {

    @Getter
    private final String userName;

}

**Comment by Maaartinus** [comment]
I guess, this is already doable: Define `canEqual` in a common superclass (or a default method in the interface, or in both classes) like
```
protected boolean canEqual(Object other) {
    return other instanceof User;
}
```
Then add `@EqualsAndHashCode` to both classes. Take care they contain exactly the same fields, or exclude them from EQHC, so that you don't break symmetry.

PS: It doesn't really have much to do with interfaces (replace "interface" by "abstract class" in your posting to see why).

**Comment by Scheka007** [comment]
Hi @Maaartinus ,

i've try your suggestion, but doesn't get the expected result. May i understood  something wrong, so i hope you can show me my mistake.



public abstract class TestUser {

    public abstract String getUserName();
    
    protected boolean canEqual(final Object other) {
        return other instanceof TestUser;
    }
}

@Data
public class TestUserImmutable extends TestUser {

    private final String userName;

}

@Data
public class TestUserMutable extends TestUser {

    private String userName;
    
}

public class TestUserTest {

    @Test
    public void shouldBeEqual() {
        
        final String anyUserName = "superUser";
        
        final TestUserImmutable immutable = new TestUserImmutable(anyUserName);
               
        final TestUserMutable mutable = new TestUserMutable();
        mutable.setUserName(anyUserName);
       
        assertThat(immutable, IsEqual.equalTo(mutable));
    }

}

Currently the result of testrun is 
java.lang.AssertionError: 
   Expected: <TestUserMutable(userName=superUser)>
     but: was <TestUserImmutable(userName=superUser)>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
...

**Comment by Maaartinus** [comment]
I guess, I was wrong on this part:

> Define canEqual in a common superclass (or a default method in the interface, or in both classes)

I guess, Lombok always generates `canEqual`, so the superclass method won't get used. I'm afraid, you have to add it to both implementation (I hope it helps, as that's why `canEqual` exists).

PS: Would you reformat your posting using triple-backquotes for code? This way it's unreadable. Example:
\`\`\`
code
\`\`\`

**Comment by Scheka007** [comment]
Hi,
i've try also to add canEqual to both implementation but have still the same test run error
´´´
public abstract class TestUser {

    public abstract String getUserName();

}

@Data
public class TestUserMutable extends TestUser {

    private String userName;
 
    protected boolean canEqual(final Object other) {
        return other instanceof TestUser;
    }
}

@Data
public class TestUserImmutable extends TestUser {

    private final String userName;

    protected boolean canEqual(final Object other) {
        return other instanceof TestUser;
    }
}

public class TestUserTest {

    @Test
    public void shouldBeEqual() {
        
        final String anyUserName = "superUser";
        
        final TestUserImmutable immutable = new TestUserImmutable(anyUserName);
               
        final TestUserMutable mutable = new TestUserMutable();
        mutable.setUserName(anyUserName);
       
        assertThat(immutable, IsEqual.equalTo(mutable));
    }

}
´´´

**Comment by Scheka007** [comment]
Hi again, it's looks like lombok has a bug.
After delombok the class TestUserMutable i see that canEquals get called to late.

```
...
    protected boolean canEqual(final Object other) {
        return other instanceof TestUser;
    }
...
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof TestUserMutable)) return false;
        final TestUserMutable other = (TestUserMutable)o;
        if (!other.canEqual((java.lang.Object)this)) return false; // <- to late !!!
        final java.lang.Object this$userName = this.getUserName();
        final java.lang.Object other$userName = other.getUserName();
        if (this$userName == null ? other$userName != null : !this$userName.equals(other$userName)) return false;
        return true;
    }
```

**Comment by Maaartinus** [comment]
> Hi again, it's looks like lombok has a bug.

It's no bug, it's just like things are, which I didn't realize. Sorry for the confusion, I really thought it'd work.

The `instanceof` check comes first and spoils the game. It's no bug as without it, lombok can't call `canEquals`. You could, but lombok has no good access to the superclass definition and doesn't know that casting to `TestUser` would do.

**Comment by Scheka007** [comment]
> lombok has no good access to the superclass definition
The class which i have delombok was TestUserImmutable which already include the ```canEquals``` inside.
So there is no need to have knowledge about the super class.
So does there exist a possibility to reach my target, get rid of boiler plate code?

**Comment by Maaartinus** [comment]
> The class which i have delombok was TestUserImmutable which already include the canEquals inside.

Yes, but it's `other.canEquals(this)` (with a cast), what gets called and not the other way round. IIRC this is necessary, so that a subclass can decide if it wants to be equal or not (there may be some `RoamingMutableUser extends MutableUser` which adds a location (which gets used in its `equals`) and never `equals` to a plain `User`).

> So does there exist a possibility to reach my target, get rid of boiler plate code?

I'm afraid no, but the project owners may know better.
