### ISSUE TITLE
IntelliJ IDEA does not generate equals () and hashCode () using Lombok.

### ISSUE THREAD

**Issue by BorzdeG** [rzwitserloot/lombok#1250]
https://youtrack.jetbrains.com/issue/IDEA-164829

**Comment by rspilker** [comment]
I don't think that we can help here. Possibly you should file a bug report on [the Lombok IntelliJ plug-in](https://github.com/mplushnikov/lombok-intellij-plugin) project.

**Comment by BorzdeG** [comment]
the bug has already been fixed in the Jetbrains IDEA link above
