### ISSUE TITLE
Coverage w/ Jacoco

### ISSUE THREAD

**Issue by onlinegeek101** [rzwitserloot/lombok#1256]
I know multiple issue proposals exist as far as flagging content as 'Generated' so that code coverage tools can skip checking that content. Has any consideration been given to just making a lombok annotation that can generate tests for lombok pojo's (for any generated code). This would provide a solution to the code coverage problem that would be universal.

Would this even be possible?

I am envisioning something like.

```java
package com.pojotown.newpojos;

import lombok.testing.GenerateTests;

@GenerateTests(annotations={ @Setters, @Getters, @EqualsAndHashcode })
public class PojoTests {
 //Put all tests for manual code here 
}
```

Also a lombok.config entry to set the testing suite
lombok.testing.framework = testng|junit;

Does this seem like a possible to implement?

**Comment by rspilker** [comment]
I would consider generating tests outside the scope of Lombok. It is possible to generate them using a regular annotation processor.
