### ISSUE TITLE
Not able to generate getter and setter throwing compile time error

### ISSUE THREAD

**Issue by pankajkh** [rzwitserloot/lombok#1257]
Hi,

I am getting compile time error "cannot find symbol for getter and setter". I have tried different combinations of lombok, maven-compiler-plugin and java but it failed in all cases. Here is the details of version ;
maven-compiler-plugin: 3.2
java.version : 1.7 / 1.8
lombok : 1.16.4

mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T17:27:37+05:30)
Maven home: /Users/pakhan/Software/apache-maven-3.3.3
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"

Can you please help me to debug the issue ?
I have attached the code snippets.

Thanks,
Pankaj

<img width="631" alt="screen shot 2016-12-10 at 11 52 41 am" src="https://cloud.githubusercontent.com/assets/9314203/21071723/7c92122c-becf-11e6-9a06-c6aaa88e3d48.png">

<img width="407" alt="screen shot 2016-12-10 at 11 53 23 am" src="https://cloud.githubusercontent.com/assets/9314203/21071719/6324066a-becf-11e6-94c8-92e49e7eefc0.png">

**Comment by rspilker** [comment]
I would try updating the compiler plugin to a more recent version, no idea if that would help. The current version is `3.6.0`.
