### ISSUE TITLE
@EqualsAndHashCode(unsupported) wanted

### ISSUE THREAD

**Issue by jborgers** [rzwitserloot/lombok#1261]
Hi,

If I have classes which are not designed to be called equals nor hashCode on, I implement those as follows:

public boolean equals(Object other) {
   throw new UnsupportedOperationException("equals not designed: object not intended for use in collection.");
}
 
public int hashCode() {
   throw new UnsupportedOperationException("hashCode not designed: object not intended for use in collection.");
}

This has the advantage of fail-fast when the object is used in a wrong way and additionally, there is no waste with unneeded code that deals with the properties.

I would like to have support for this in Lombok with something like @EqualsAndHashCode(unsupported).

**Comment by jborgers** [comment]
I think it would be good to make the methods final, to prevent subclasses to override the methods with an actual implementation and get into trouble with the equals contract.

**Comment by Maaartinus** [comment]
That's wrong. You class is a subclass of `Object` and there's nothing about `equals` being optional. You're also making `equals` non-reflexive, which isn't allowed either. Moreover, it gets often used in tests.

Anyone is free to put any object in a collection, at least in Java.

Doing nothing seems to be the right thing as then the inherited identity based `equals` gets called and that's probably just right.

**Comment by jborgers** [comment]
Maaartinus,
Let me explain me this more to you. I come across lots of code when I do reviewing for performance. One of the things that strike me is that equals and hashCode are most of the time not implemented. They are just implemented when something breaks and they find that. Usually in dev or test and sometimes this leads to serious production problems which can be very expensive.
When I confront them, the answer usually is that they don't want to code stuff that is not needed, because the methods are not used. And in fact, I find that a valid argument, unneeded code is waste. 

However, then the objects are not prepared for normal use with collections and this can easily lead to production problems. The equals and hashCode methods of Object typically make no sense, identity checking is different from equality checking. Hence, the solution to throw the unsupportedexception in case the object is not intended to be used in a collection. You get fail-fast instead of unintended behavior.

Of course Lombok make equals and hashCode much easier to deal with. However, for the classes which you intentionally don't want to use in a collection and not have equals called on, you still have think about how to specify it, e.g. have excludes, deal with super; and unneeded code gets generated.

I think the non-reflexity, as with other aspects of the equals contract, only needs to hold when it is supported. Unsupported means no contract, no support.

However, you get into trouble when you define unsupported on the super level and want to override that to an actual implementation in the sub class, like:
(case 1)
aSub.equals(aSuper); // returns false (or possible true if instanceof is used)
aSuper.equals(aSub); // throws unsupported exception
So, this is not symmetric.

(case 2)
And also the simpler case with Dog not supporting equals and Cat supporting it:
aCat.equals(aDog); // returns false
aDog.equals(aCat); // throws unsupported exception
is not symmetric.

I think case 1 should be made impossible by making the methods final.
And case 2 is a matter of getting a fail-fast with the conclusion: equals/hashCode should be implemented, a programming error. Equals contract should be fixed.

**Comment by Maaartinus** [comment]
> One of the things that strike me is that equals and hashCode are most of the time not implemented. They are just implemented when something breaks and they find that.

I've never heard about something like that. When you write just a couple of unit tests (which you really should), there will be some `assertEquals` there and then you'll need it.

> equals... you still have think about how to specify it

Sure, but for me it's an important part of designing the class. I think about equality, so that I better understand what I'm doing. Usually, it's trivial (identity-based equals works for most classes, my entities compare nothing their ID, my value classes compare everything (except for cached fields, if any), etc.).

> I think the non-reflexity, as with other aspects of the equals contract, only needs to hold when it is supported. Unsupported means no contract, no support.

In a sense, I agree. Unsupported means you *are already* violating the contract, so you may happily continue violating it.

I'm not in charge of Lombok, but the authors will most probably have the same doubts. Wouldn't logging (`@EqualsAndHashCode(log=true)`) be good enough for you? It's feature idea which may be more usable and violates no contract.

**Comment by rspilker** [comment]
The problem with `log` is that you would also need to configure the logging system/field.

We're not going to make it easy to break the general contract.

The only thing that I can imagine is that we add a flag to use the object's identity (`System.identityHashCode()` and `other == this`) but we have no concrete plans to add this.

**Comment by Maaartinus** [comment]
> The problem with `log` is that you would also need to configure the logging system/field.

You could require an additional `@Log` annotation or configuration (IMHO a log configuration would be better than having multiple log annotations, anyway). I personally don't care.
