### ISSUE TITLE
Feature request, customize short formats for GregorianCalendars in @ToString 

### ISSUE THREAD

**Issue by edpichler** [rzwitserloot/lombok#1262]
`GregorianCalendars` has a long `toString()`. It's painful to override it. 
I need a feature on `@ToString` annotation to `GregorianCalendars` being represented shortly in toString methods.

**Comment by edpichler** [comment]
Maybe, on ToString annotation, it would be nice to pass the date time format I would like, e.g.: "dd/mm/yyy HH:mm:ss".

**Comment by rspilker** [comment]
The toString method is meant just for debugging. Since jsr310, GregorianCalendar is on its way out. The toString for collections and arrays wouldn't do this either.

Enough reasons not to implement this.
