### ISSUE TITLE
Eclipse Neon 1a showing errors for lombok annotation for version 1.16.12

### ISSUE THREAD

**Issue by c0demark** [rzwitserloot/lombok#1264]
Hi Team

I am currently using eclispe neon 1a build 4.6.1. I installed lobok.jar version 1.16.12 into my eclipse following the steps as mentioned in the link [https://projectlombok.org/download.html](url). Also I added lombok jars version 1.16.12 as maven dependencies in my project. Now when I See my entity class annotations for @Data eclispe shows error. And when I try to correct it by suing eclipse ctrl-space intellisense it shows some error popup. (shared as screenshot). It takes very long for the auto-completion box to come up. Still it doesnot show lombok as a suggestion. However when I change my maven dependencies to version 1.16.10 the error vanishes. Please help in this regard.
![lombok-1 16 12-error-in-eclispe-neon-1a-4 6 1](https://cloud.githubusercontent.com/assets/16079018/21296573/b2bf3322-c594-11e6-9fd4-b9e497b58614.png)

**Comment by rspilker** [comment]
I cannot reproduce your problem.

```
Eclipse IDE for Java Developers

Version: Neon.1a Release (4.6.1)
Build id: 20161007-1200
```

**Comment by rspilker** [comment]
Closed due to no feedback from the reporter.
