### ISSUE TITLE
@Builder not preserve default value of field

### ISSUE THREAD

**Issue by ChinaXing** [rzwitserloot/lombok#1272]
When use @Builder annotation, to the following code:

```
@Data
@Builder
public class ShardInfo {
    public static final int NO_SHARD_INDEX = -1;
    private int index = NO_SHARD_INDEX;
    private String name;
}
```

user code:

```
ShardInfo sd = ShardInfo.builder().name("hello").build();
System.out.println(sd.index); // expected -1, but got 0
```

hope you can fix this problem.

**Comment by tsabirgaliev** [comment]
I suggest adding an optional build strategy to `@Builder`: `constructor`(default), `field`, `property`.

- Call the current behaviour: `constructor`, that implies building through a `@AllArgsConstructor`. 
- `field` strategy builds via assigning fields directly, thus implies a `@NoArgsConstructor`.
- `property` strategy builds via `@Setter`s and also implies `@NoArgsConstructor`

**Comment by rzwitserloot** [comment]
This intentional behavior. We're away it's perhaps somewhat unexpected, and in general some way to specify defaults would be nice. We haven't figured out a nice way to make it happen.
