### ISSUE TITLE
Propagate annotations from field to getter / setter

### ISSUE THREAD

**Issue by loolooyyyy** [rzwitserloot/lombok#1282]
Suggestion:

Including a flag in `Getter` and `Setter` (generally annotations which generate methods for fields) to put every annotation already present on the field, on the generated method too (if the annotation type is applicable to method). Or instead of including a flag, have a special class for @__ annotations, say @__(@PropagateAnnotations.class), although a separate flag is less verbose.

Why?
Regarding this post on stackoverflow: http://stackoverflow.com/questions/9037955/spring-mvc-json-infinite-recursion sometimes the getter / setter must be explicitly annotated not just the field.

Tricky part:
1. Should the annotations be propagated to constructors too?
2. Is it that useful? :D

**Comment by manuel-hegner** [comment]
There already is a way to do this. You can write 
`@Getter(onMethod=@__({@YourAnnotationThatWillBeOnTheGetter}))`
to add annotations to your getter

**Comment by loolooyyyy** [comment]
But the class level getter is shared for all fields.

```java
@Getter(onMethod=@__(@JsonIgnore))
public class Person {
    private int age;
    private Set<Person> friends;
}
```

Will result in 

```java
public class Person {
    // ...

     // shouldn't be annotated
    @JsonIgnore
    public int getAge() {
         return this.age;
    }

    @JsonIgnore
    public Set<Person> getFriends() {
         return this.friends;
    }
}
```

But, with propagation,

```java
@Getter
@Accessors(propagate=true)
public class Person {
    private int age;
    @JsonIgnore
    private Set<Person> friends;
}
```

Becomes:

```java
public class Person {
    // ...

    // no annotation here!
    public int getAge() {
         return this.age;
    }

    @JsonIgnore
    public Set<Person> getFriends() {
         return this.friends;
    }
}
```

**Comment by loolooyyyy** [comment]
But of-course you can put getter on each field separately! stupid me.
