### ISSUE TITLE
Add a @OverrideConstructors annotation

### ISSUE THREAD

**Issue by manuel-hegner** [rzwitserloot/lombok#1286]
It would be nice to have an @OverrideConstructors annotation. This annotation would create one constructor for each constructor of the super class. That is a common use case if you subclass classes with multiple constructors.

I would be willing to try my hand on a pull request if you deem this annotation useful.

**Comment by omega09** [comment]
Can you give a code example of with and without your annotation?

**Comment by manuel-hegner** [comment]
Sure:
Without Lombok:
```java
public class CustomException extends Exception {

    public CustomException(String message) {
        super(message);
    }

    public CustomException(String message, Throwable throwable) {
        super(message, throwable);
    }

    public CustomException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }

    ...
}
```
With Lombok:
```java
@OverrideConstructors
public class CustomException extends Exception {}
```

**Comment by omega09** [comment]
#375

**Comment by rspilker** [comment]
This requires resolution, not something lombok can do right now.
