### ISSUE TITLE
Something with annotation values that use a constant instead of a literal

### ISSUE THREAD

**Issue by JGSergey** [rzwitserloot/lombok#1287]
...
public class User {   
   @Column(name = "login", unique = true, nullable = false)
    @NotNull
    @Pattern(regexp = PublicConstants.LOGIN_PATTERN) // issue here
    @Size(min = 5, max = 20)
    @Valid
    String login;
....
}

@UtilityClass
@FieldDefaults(level = AccessLevel.PUBLIC, makeFinal = true)
public class PublicConstants {
    String LOGIN_PATTERN = "^[a-zA-Z0-9._-]{5,20}$";
    ...
}

If you are use constants with lombok into annotation, you will have compile error

**Comment by rzwitserloot** [comment]
I think this qualifies as the most exotic thing ever in the entire world. How did you find this bug? I'm... flabbergasted.

To wit:

* If you put `@FieldDefaults(makeFinal=true)` on a class, then static fields are _skipped_.
* If you put the above _and_ `@UtilityClass` on a class, then you do end up with a static and final field even if you started out with a non-static, non-final one. This is a bug in lombok, but not a particularly important one.
* Given the above bug, you end up twisting something like `String foo = "hello";` into `static final String foo = "hello";` but in a way that javac, at least, does NOT mark it as a compile-time constant. This is generally not relevant.
* ... unless you then try to use a ref to that field in an annotation. Then it matters.

**Comment by Maaartinus** [comment]
> If you put the above and `@UtilityClass` on a class, then you do end up with a static and final field even if you started out with a non-static, non-final one. This is a bug in lombok, but not a particularly important one.

I don't think so. IIUYC your fix makes combining `@UtilityClass` and `@FieldDefaults(makeFinal = true)` pointless as the latter will *never* do anything. Therefore, the old execution order was actually the right one, making the combined annotations to a constant definition tool. :)

Not that I'd care...

**Comment by rzwitserloot** [comment]
FieldDefaults is not intended to _ever_ turn static things final. If the two now combine to do nothing useful, at best that means lombok should warn you that what you're doing isn't useful.

**Comment by david-g-williams** [comment]
How do we create a Lombok annotated class of public static constants, without the repetitious `public static final` modifiers?
