### ISSUE TITLE
Feature: Allow fields to be specified only via builder's constructor

### ISSUE THREAD

**Issue by atnak** [rzwitserloot/lombok#1303]
I'm looking to make some fields mandatory by having to specify it in a parameter to `.builder()`:

e.g.:
```java
SomeClass.builder("abc").bar(42).build();
```

I tried a construct like this, but this currently results *"The final field SomeClass.foo cannot be assigned"* at the `@Builder` line:

```java
@Builder
public class SomeClass {
    private String foo;
    private Integer bar;

    // @RequiredArgsConstructor
    public static class SomeClassBuilder {
        private final String foo;
    }
}
```

The expected outcome was this resulting in:

```java
new SomeClassBuilder("abc"); // returns builder instance
SomeClass.builder("abc"); // returns builder instance

new SomeClassBuilder(); // error: no such constructor
new SomeClassBuilder("abc").foo("abc"); // error: no such method "foo(String)"
```

**Comment by rzwitserloot** [comment]
We'd want to support mandatory params in a nicer way than this. Part of the point of builder is to have faux named arguments, and making the mandatory aspects part of the 'builder' call removes that, missing the point.

**Comment by rzwitserloot** [comment]
See issue #1202 for more discussion on how mandatory builder fields would work.
