### ISSUE TITLE
@Singleton

### ISSUE THREAD

**Issue by edpichler** [rzwitserloot/lombok#1304]
This feature would be very handy.

**Comment by rspilker** [comment]
The correct way to declare a singleton is using an enum:

From [Effective Java (2nd Edition)](https://www.amazon.com/Effective-Java-2nd-Joshua-Bloch/dp/0321356683):
```java
// Enum singleton - the preferred approach
public enum Elvis {
    INSTANCE;

    public void leaveTheBuilding() { ... }
}
```

**Comment by gMan1990** [comment]
https://github.com/peichhorn/lombok-pg/wiki/%40Singleton
un-recommend
