### ISSUE TITLE
Slf4j customize Logger name

### ISSUE THREAD

**Issue by driverpt** [rzwitserloot/lombok#1306]
e.g.:

```
@Slf4j(value="LOGGER")
```

equivalent to:

```
private static final org.slf4j.Logger LOGGER = org.slf4j.LoggerFactory.getLogger(LogExample.class);
```

**Comment by bgunnink** [comment]
FYI, you can do this with configuration keys.  See https://projectlombok.org/features/Log.html & https://projectlombok.org/features/configuration.html

**Comment by askoning** [comment]
Indeed, lombok's configuration system is the way to go here.
