### ISSUE TITLE
Support for Logback?

### ISSUE THREAD

**Issue by kppgs** [rzwitserloot/lombok#1307]
I see that [Logback](https://logback.qos.ch/) is not yet [supported](https://projectlombok.org/features/Log.html) by Lombok

Will you please support it?

**Comment by bgunnink** [comment]
Lombok doesn't support specific SLF4J implementations.  It supports [SLF4J](https://projectlombok.org/features/Log.html), which binds an implementation at runtime.

**Comment by askoning** [comment]
Spot on.
