### ISSUE TITLE
Lombok installation breaks eclipse shortcut

### ISSUE THREAD

**Issue by dhakshin83** [rzwitserloot/lombok#1308]
Following the installation steps described here https://projectlombok.org/download.html
>>Eclipse and variants run lombok.jar as a java app (i.e. doubleclick it, usually) to install. Also add lombok.jar to your project. Supported variants: Springsource Tool Suite, JBoss Developer Studio

ISSUE: 
Post Lombok installation on windows the eclipse shortcut breaks. This can be overcome by recreating a new shortcut but initial thought was that Lombok installation didn't work or rather it broke eclipse. Would be nice if this is fixed. Thanks.

**Comment by rspilker** [comment]
After installation, the lombok installer displays the following text:

> If you start Eclipse with a custom -vm parameter, you'll need to add:
> -vmargs -javaagent:lombok.jar
> as a parameter as well

Did you see this message? Did you check your shortcut? Was that the fix?

**Comment by l-scott-warner** [comment]
I fix this by manually adding the full path to the lombok.jar in the eclipse.ini file.

**Comment by rspilker** [comment]
I think that that's the best we can do, unfortunately.

**Comment by cnsgithub** [comment]
Hi, I noticed that moving the eclipse install (with lombok bundled) to a different machine causes it to crash on start, this is probably because the full path to the lombok.jar is added.

Wouldn't it be better if you add only "lombok.jar" without path on the lombok installer when no -vm argument is set? Then the eclipse installation is portable.

**Comment by anmoldeep0123** [comment]
-vmargs -javaagent:lombok.jar

This helped . thanks .

**Comment by Rawi01** [comment]
@riddhisanyal-aa Check #2810
