### ISSUE TITLE
Create @Decorate annotation to make decoration painless

### ISSUE THREAD

**Issue by rtisma** [rzwitserloot/lombok#1313]
Would be nice if there was a `@Decorate` feature. The Decorator Pattern is a great design pattern, however it is sometimes cumbersome to implement for Interfaces with many methods. The following example shows a proposal for the usage of the `@Decorate` feature before and after being Delomboked: 

```java

public interface Vehicle {
    String getA();
    int getB(int n);
    <T> T getC(T t);
    String getD();
    //... and so on
}

public interface Component {
    String getName();
    //... and so on
}

```

**Lombok-ed version**
```java

@RequiredArgsConstructor
public class Car implements Vehicle, Component {
    
    @Decorate(class=Vehicle.class)
    private final Vehicle vehicle;

    @Decorate(class=Component.class)
    private final Component component;

    //User override
    @Override
    public String getD(){
        return "this is a Car calling getD";
    }
}

```

**Delomboked version**

```java

public class Car implements Vehicle {
    private final Vehicle vehicle;
    private final Component component;

    public Car(Vehicle vehicle, Component component){
        this.vehicle = vehicle;
        this.component = component;
    }
    
    //Lombok Override
    @Override
    public String getA(){
        return this.vehicle.getA();
    }

    //Lombok Override
    @Override
    public int getB(int n){
        return this.vehicle.getB(n);
    }

    //Lombok Override
    @Override
    public <T> T getC(T t){
        return this.vehicle.getC(t);
    }

    //User override
    @Override
    public String getD(){
        return "this is a Car calling getD";
    }

    //Lombok override
    @Override
    public String getName(){
        return this.component.getName();
    }
}

```

**Comment by rspilker** [comment]
It already exists, but is still experimental. it is called [@Delegate](https://projectlombok.org/features/experimental/Delegate.html).

The reasons it is still experimental:
- It need resolution, and that's still brittle
- The java compiler needs to determine all field and method signatures at the same time, and that's before resolution is possible. However, for this to work properly, the fields need to be resolved before the methods can be created.

For now, we got it working for most use cases.
