### ISSUE TITLE
Builder with toBuilder=true doesn't work properly with inner classes 

### ISSUE THREAD

**Issue by bademux** [rzwitserloot/lombok#1316]
hello,
I have and issue with @Builder(toBuilder=true), while compiling got error "@Builder(toBuilder=true) is only supported if you return your own type."

sample code
```java
public class SearchClient {

    private final Service service;

    @Autowired
    public SearchClient(Service service) {
        this.service = service;
    }

    @AllArgsConstructor(access = AccessLevel.PRIVATE)
    public class Requester {

        private final String source;

        public void sendRequest() {
            service.search(source);
        }

    }

    // Hackfix for https://github.com/rzwitserloot/lombok/issues/1302
    @Builder(toBuilder = true)
    private Requester createRequester(String source) {
        return new Requester(source);
    }

}
```

**Comment by rzwitserloot** [comment]
Yes, that's intentional, as per the error.

**Comment by bademux** [comment]
Can you please explain what is wrong? What is "your own type" in this case?
Thanks.

**Comment by Maaartinus** [comment]
Just guessing: `toBuilder=true` on a method returning `Requester` adds a method to the class `Requester` and you must be inside the class for it to work. IMHO it should work for any classes declared inside the same source file, but this may be a non-trivial feature.

IIUIC you're trying to work around the problem with `@Builder` not working for inner non-static classes by using a factory method, but this fails with the above error message.

I'd suggest to use a static nested class. Usually, all you need is to add the `static` modifier, add the enclosing class as a member `searchClient` and fix the errors by prefixing flagged accesses with `searchClient.`.

**Comment by bademux** [comment]
@Maaartinus I still see no  problem with adding SearchClient#toBuilder to SearchClient class, as SearchClient #builder works fine (just remove "toBuilder = true" ).

Please see that Requester should have SearchClient as a context as it uses SearchClient.service property.

Thanks for your answer, I really want to understand how to make it work or why it is impossible.
