### ISSUE TITLE
can lombok plugin support visual studio code?

### ISSUE THREAD

**Issue by xiaoyw** [rzwitserloot/lombok#1323]
vscode can't find getter setter method in java class which using getter setter annotation

**Comment by askoning** [comment]
Visual Studio Code is not supported by the maintainers of Lombok. As a matter of fact, Java is not even a core language of this IDE. 
But maybe this helps? https://github.com/redhat-developer/vscode-java/wiki/Lombok-support

**Comment by sungiklee** [comment]
It works. Thank you.

**Comment by alejandrosaucedo** [comment]
It works me too. Thanks

**Comment by abhinavkadam** [comment]
It worked for me too. Thanks so much!

**Comment by bilguunb-UMS** [comment]
It kinda works. When I open the java file the error goes away. 
However when I restart VS the error keeps coming back>??? 
Any idea?

**Comment by biligunb** [comment]
It kinda works. When I open the java file the error goes away.
However when I restart VS the error keeps coming back>???
Any idea?

**Comment by biligunb** [comment]
Never mind. I think it is fixed by updating the project from POM.xml :D

**Comment by GabrielBB** [comment]
@abhinavkadam  @biligunb @alejandrosaucedo Hi, Lombok is officially supported in Visual Studio Code now. Please visit: https://github.com/GabrielBB/vscode-lombok

**Comment by bilguunb-UMS** [comment]
@GabrielBB good news. :) (thumbsup)

**Comment by conteit** [comment]
@GabrielBB: I've tried to install it in my VS Code but it asserts that `there is no available version compatible with VS Code '1.20.1'` :-(

**Comment by GabrielBB** [comment]
@conteit Update your Visual Studio code. It’s  just one click. The last version is needed because I’m using a new feature introduced in the version 1.21.0

**Comment by rzwitserloot** [comment]
Re-opening; we need to get this stuff on the projectlombok.org pages pronto. Gracias to @GabrielBB and the rest of the team for the plugin.

I trust the documentation that @askoning posted, given that it was very recently updated, still holds: https://github.com/redhat-developer/vscode-java/wiki/Lombok-support ?

This issue is for writing the documentation in /website/setup.

**Comment by GabrielBB** [comment]
@rzwitserloot The plugin does exactly what is written in that documentation. However is missing this part:

> Old versions of Java might need an additional -Xbootclasspath/a:/path/to/lombok.jar flag. The a: prefix in the Xbootclasspath flag is critical, make sure it's added.

The plugin previously added that parameter in all projects but that was causing projects with newer versions of java to fail. However, the documentation says that not adding it with old versions of Java might fail too. So I really don’t know what to do with the parameter. If only I could know which Java version is being used so I can conditionally add the parameter

**Comment by GabrielBB** [comment]
> @rzwitserloot The plugin does exactly what is written in that documentation. However is missing this part:
> 
> > Old versions of Java might need an additional -Xbootclasspath/a:/path/to/lombok.jar flag. The a: prefix in the Xbootclasspath flag is critical, make sure it's added.
> 
> The plugin previously added that parameter in all projects but that was causing projects with newer versions of java to fail. However, the documentation says that not adding it with old versions of Java might fail too. So I really don’t know what to do with the parameter. If only I could know which Java version is being used so I can conditionally add the parameter

I just opened [an issue](https://github.com/redhat-developer/vscode-java/issues/1253) to [vscode-java](https://github.com/redhat-developer/vscode-java) so they be more specific when they say " Old versions of Java", If they tell me which maximum java version needs that parameter then I might be able to conditionally add it

**Comment by rzwitserloot** [comment]
What the....

I can't remember, but git blame says I did this.. I've done precisely what i was planning (add some docs) in late 2018. @GabrielBB is this still up to date? https://projectlombok.org/setup/vscode

@xiaoyw The site apparently has been linking to the vscode plugin for well over a year now :)

**Comment by GabrielBB** [comment]
@rzwitserloot haha yes, it's been in the page for a while and the instructions are up to date. I thought you were worried about the plugin functionality after vscode-java changed a little the documentation

**Comment by rzwitserloot** [comment]
Nope. Perfect, all is well and thanks again for the plugin!
