### ISSUE TITLE
toBuilder throws an NPE when a @SIngular collection field is null

### ISSUE THREAD

**Issue by jgraglia** [rzwitserloot/lombok#1324]
Hi, I'm facing the following pb : 

Given this POJO :

> @Data
> @Builder(toBuilder = true)
> public class BuilderDemo {
> 
>     private final Set<String> names;
> 
>     @Singular
>     private final Set<String> singularNames;
> }
> 

a NPE is thrown when using toBuilder method on an instance created with a null singularNames field.

>         final BuilderDemo nullNames = new BuilderDemo(Collections.EMPTY_SET, null);
> 
>         nullNames.toBuilder()  <= NPE ! 
> 
>         final BuilderDemo fromBuilder =  BuilderDemo.builder().build();
> 
>         fromBuilder.toBuilder()  <= NO NPE 
> 

I can reproduce the problem always, and here is the link to a simple maven project demonstrating the problem : 
https://github.com/jgraglia/lombokbuilderbug

I'm using lombok 1.16.14 on a JDK 8 project.

PS: I can not simply replace _new BuilderDemo (...)_ with _Builderdemo.builder()_ calls as this happens when deserializing a BuilderDemo from a json stream (using Jackson ObjectMapper)

Thx!

**Comment by jgraglia** [comment]
still no luck with lombok 1.16.16

**Comment by sarthak-nandi** [comment]
+1, facing the same issue.

**Comment by jesantana** [comment]
+1

**Comment by DmitryWh** [comment]
still no luck with lombok 1.16.18
