### ISSUE TITLE
@Data doesn't honor configuration keys for @ToString @EqualsAndHashCode

### ISSUE THREAD

**Issue by sinuhepop** [rzwitserloot/lombok#1329]
As a example, let's have these classes:

```
public class Test {
	public static void main(String... args) {
		System.out.println(new A("a"));
		System.out.println(new B("b"));
	}
}
```
```
@ToString
@RequiredArgsConstructor
public class A {
	private final String x;

	public String getX() {
		System.out.println("getX() invoked on " + this.getClass());
		return x;
	}
}
```
```
@Data
public class B {
	private final String x;

	public String getX() {
		System.out.println("getX() invoked on " + this.getClass());
		return x;
	}
}
```
And a lombok.config file:
```
config.stopBubbling = true
lombok.toString.doNotUseGetters = true
```
Execution prints:
```
A(x=a)
getX() invoked on class lombok.test.B
B(x=b)
```

So,  property `lombok.toString.doNotUseGetters` isn't read by `@Data`. Maybe it's not a bug, but a wanted functionality. I probably won't agree with that, but I think at least som property like `lombok.data.toString.doNotUseGetters` is needed. Same happens for other properties of `@ToString` and `@EqualsAndHashCode`, but not for `@Getter`/`@Setter`.

**Comment by rspilker** [comment]
Fixed in 969ed9125e239380ce70b1c0abc78abc614eebaa

**Comment by rspilker** [comment]
Thanks for bringing this up.

**Comment by sinuhepop** [comment]
Thanks to you, guys
