### ISSUE TITLE
Logger generated with @Log must mach constant naming convention

### ISSUE THREAD

**Issue by vbors** [rzwitserloot/lombok#1330]
The @Log will generate:
`private static final java.util.logging.Logger log`
This is a static final field  - it is a constant and the name must comply  with java naming convention.
http://www.oracle.com/technetwork/java/codeconventions-135099.html

> The names of variables declared class constants and of ANSI constants should be all uppercase with words separated by underscores ("_"). (ANSI constants should be avoided, for ease of debugging.)

**Comment by Maaartinus** [comment]
No. A definition of what is a constant is missing. Oracle AFAIK says nothing and Google [says][1]

> Constants are static final fields whose contents are deeply immutable and whose methods have no detectable side effects.

If logging qualifies as a "detectable side effect" could lead to quite some bikeshedding, too.

[1]: https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

**Comment by vbors** [comment]
OK, for explanation!
