### ISSUE TITLE
Cannot apply @Value to an enum

### ISSUE THREAD

**Issue by jwdevel** [rzwitserloot/lombok#1331]
Apparently this is by design, but I don't quite see the reason.

See: https://github.com/lightoze/lombok/blob/a1831a1ecf5d1d67e4f782ecb140ba6a844fd82a/src/core/lombok/javac/handlers/HandleValue.java#L63

Putting @Value on an enum seems like a reasonable choice - ensures fields are final, generates toString, etc.

Is there a reason for this restriction?

**Comment by omega09** [comment]
The conflicts are at least caused by `@Value`

* generating `@EqualsAndHashCode` also, which is meaningless for an enum,
* applying `final` on the type which is illegal on an enum.

I guess it's possible to not do the above 2 for enums.

**Comment by rspilker** [comment]
We don't see enough added value to account for the added complexity:
- We shouldn't override equals, hashcode and toString
- We cannot make the enum final
- We might generate a constructor, make the fields private and final and generate getters.

For the latter, you could just use `@AllArgsConstructor`, `@Getter` and possibly `lombok.fieldDefaults.defaultPrivate = true` and `lombok.fieldDefaults.defaultFinal = true` in `lombok.config`
