### ISSUE TITLE
Lombok + empty jar = no error code from javac

### ISSUE THREAD

**Issue by gshakhn** [rzwitserloot/lombok#1336]
Steps to reproduce:

Setup:
Create file Main.java with a simple Hello World example.
```
public class Main {
  public static void main(String [] args) {
    System.out.println("Hello World");
  }
}
```

Create an empty jar file:
`touch emptyjar.jar`

---

Compile Main.java with no classpath:
`javac Main.java`

This succeeds.

---

Add emptyjar to the classpath and try to compile.
`javac -cp emptyjar.jar Main.java`

This logs an error and returns with an exit code of 1.

---

Add lombok to the classpath and try to compile:
`javac -cp lombok-1.16.14.jar:emptyjar.jar Main.java`

This logs an error and returns with an exit code of 0.

**Comment by jnape** [comment]
I wonder if there is a larger concern here, which is that because Lombok can exit with a code of 0, anything that would have otherwise triggered a non-successful response code can theoretically be occluded by Lombok's exit code.

In this case, it happened to be due to an empty jar, sure -- and perhaps an empty jar is the only thing that would otherwise cause a non-successful exit code that also allows the annotation processing phase to run -- but it might be worth taking a look at in general.

**Comment by rspilker** [comment]
Lombok does not exit the java process nor override the exit code.

We have to investigate what's going on here. What version of javac are you using? What OS, and what OS version?

Also, is this only when you provide an empty jar? Or does the presence of lombok also influence the return code of javac in an actual use case?

**Comment by gshakhn** [comment]
```
$ javac -version
javac 1.8.0_112
$ cat /etc/issue
Ubuntu 14.04.4 LTS \n \l
```

Not sure if I fully understand your last question.
With just lombok on the classpath, the exit code is 0, as expected.
With the empty jar on the classpath, the exit code is 1, as expected.
With both, the exit code is 0. I would expect it to be 1.

**Comment by gshakhn** [comment]
Some background on the issue that prompted this:
We have a job on our build server that cleans up parts of the maven cache to preserve disk space. Unfortunately, this occasionally happens while there is a build going. Javac logs an error due to an empty jar. With lombok on the classpath, javac returns 0 and maven thinks everything is fine. Maven then packages a bad artifact that isn't detected until runtime.

We need to figure the timing and scope of the clean job to make sure it doesn't interfere with an actual build, but lack of proper exit code from javac is troubling.

**Comment by jnape** [comment]
What's also important to note is that with annotation processing off, javac exits with the expected code of 1.

`javac -proc:none -cp lombok-1.16.14.jar:emptyjar.jar Main.java`

This logs an error and returns with an exit code of 1.

**Comment by rzwitserloot** [comment]
Clearly a javac bug; we don't get anywhere near it.

We'll investigate if we can work around javac's bug here though, this is definitely a Bad Thing (TM).

**Comment by rzwitserloot** [comment]
Bug confirmed; even with an empty annotation processor that does nothing, this happens.

Fortunately, it only seems to occur with broken jar files on the classpath, not other javac errors, and it is _definitely_ javac's fault.

There's really nothing we can do about it. You'll have to file this one at bugs.oracle.com. My condolences in advance.
