### ISSUE TITLE
Universal @Stereotype via preprocessing

### ISSUE THREAD

**Issue by t1** [rzwitserloot/lombok#1340]
More and more annotations seem to be gathering nowadays. In our projects, it's not unusual to have classes with 10+ annotations. [Stereotypes](http://docs.oracle.com/javaee/7/api/javax/enterprise/inject/Stereotype.html) are a very powerful concept to the rescue: You declare the logical role something has, and the stereotype is resolved to the actual annotations required to fulfil that role. This is similar to the `@Value` or `@Data` annotations that are (more or less) a shortcut for a bunch of other annotations, but they are specifically hand-programmed. And the `@javax.enterprise.inject.Stereotype` annotation only works for annotations explicitly supporting it, i.e. not Lombok, not Swagger, etc.. Actually, Spring is (again) ahead of Java EE here with their [configuration-metadata-annotation-processor](http://docs.spring.io/spring-boot/docs/1.5.2.RELEASE/reference/htmlsingle/#configuration-metadata-annotation-processor).

It would be _really_ cool, if Lombok would add this at compile time at a completely generic level. Maybe a new annotation `@Meta` that could be used to, e.g., implement `@Data`:

```java
@ToString
@EqualsAndHashCode
@Getter
@Setter
@RequiredArgsConstructor
@Meta
@Target(TYPE)
@Retention(RUNTIME)
public @interface Data {
}
```

What do you think?

**Comment by t1** [comment]
BTW: I've [asked the Java Architects at Devoxx Belgium 2016](https://www.youtube.com/watch?v=OKIKEccotUg) (around 32:30) if this could be added to Java SE, but they didn't think so.

**Comment by grimly** [comment]
I wish this could come at least for lombok annotations in a first time.

**Comment by nimo23** [comment]
See https://github.com/rzwitserloot/lombok/issues/2294

**Comment by t1** [comment]
This is more or less a duplicate of #557
