### ISSUE TITLE
Configuration key to activate @ToString(callSuper=true) for a whole project

### ISSUE THREAD

**Issue by mederel** [rzwitserloot/lombok#1349]
Hi,

recently was added to Lombok the possibility to add a lombok.equalsAndHashCode.callSuper in a lombok.config in a given project for generated equals() and hashCode() to always call the super class version if any.

I would like to have the same for @ToString, so a configuration key lombok.toString.callSuper so one could set callSuper=true for a whole project.

**Comment by ewirch** [comment]
When having this setting, Lombok should not call `super.toString()` if the class extends `Object`.

**Comment by namero999** [comment]
It was surprising to find the config key for EqualsAndHashCode but not for ToString. Should be there. Actually, I believe there should be a data.callSuper config key which applies to both EqualsAndHashCode and ToString (or support it on the @Data annotation) because those things goes together 99% and will be "ready" for future similar annotations.

**Comment by sharpau** [comment]
I'd also like to see it apply to `@Data` as @namero999 mentioned.

**Comment by rzwitserloot** [comment]
Working on it: https://github.com/rzwitserloot/lombok/wiki/FEATURE-IDEA:-@SuperToString

**Comment by snekse** [comment]
I know this ticket is old and closed, but I'd like to bring it back. 

`SuperToString` hasn't become a feature and the request in this ticket seems simpler than that.

The request seems to be asking for just a global configuration option to override the default `callSuper` property on `toString` 

My understanding from the OP's request is if you had set `lombok.toString.callSuper=true` 
then this

```
@Data
@ToString
public MyClass {}
```

would be treated as this:

```
@Data
@ToString(callSuper=true)
public MyClass {}
```

and ideally in my mind, this too would be automatically "toString::callSuper", but I don't know how much this would increase the complexity.

```
@Data
public MyClass {}
```
