### ISSUE TITLE
@NonNull on field ignored with manual constructor

### ISSUE THREAD

**Issue by udalrich** [rzwitserloot/lombok#1350]
Given this class

    import lombok.NonNull;
    import lombok.ToString;

    @ToString
    public class Test {
        @NonNull String foo;

        Test() {
            foo = null;
        }

        public static void main(String[] args) {
            Test test = new Test();
            System.out.println("Created a Test " + test);
        }

    }

I had expected an exception when calling the `Test` constructor.  Instead, it printed the Created message, including "foo=null".  Reading the documentation, it seems that a manual constructor prevents the null checks on a field, but this should be highlighted much more strongly.

A better fix would be to have lombok add `if (foo == null) throw ...` to the end of the constructor.  This would preserve the intuitive contract of "a @NonNull field will not be null"

**Comment by rzwitserloot** [comment]
This is intentional behaviour.
