### ISSUE TITLE
Support for @Immutable in lombok

### ISSUE THREAD

**Issue by shankyty** [rzwitserloot/lombok#1357]
Support for  `@Immutable` in lombok, which will be combination of 

- `@Builder`
- `@Getter`
- `@AllArgsConstructor(access = AccessLevel.PRIVATE)`

and all field can be forced to final not sure though for this part

**Comment by robschia** [comment]
You can use the ```@Value```([docs](https://projectlombok.org/features/Value.html)) and ```@Builder``` annotations to achieve what you want.
