### ISSUE TITLE
lombok.val not replaced in lambdas

### ISSUE THREAD

**Issue by ewirch** [rzwitserloot/lombok#1367]
This fails to compile:
```
Runnable r = () -> {
	val a = 5;
};
```

**Comment by Maaartinus** [comment]
For me it does, both in eclipse and gradle (1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13).

**Comment by ewirch** [comment]
I can confirm it does compile for 1.16.14. It did not compile for 1.16.10.
