### ISSUE TITLE
@ToString(exclude) option is not working as expected

### ISSUE THREAD

**Issue by DejvidTopler** [rzwitserloot/lombok#1373]
Since version 16.16 I have problems with @ToString(exclude = "myProperty1, myProperty2") example.
Properties are included in toString method.

**Comment by Maaartinus** [comment]
Do you really mean
`@ToString(exclude = "myProperty1, myProperty2") `
or is it a "mental typo" and you mean
`@ToString(exclude = {"myProperty1", "myProperty2"}) `? The former is wrong.

**Comment by DejvidTopler** [comment]
@ToString(exclude = "myProperty1, myProperty2") example worked until 1.16.14.

Your example solved my problem in 1.16.16.

Thank you for you time.
