### ISSUE TITLE
Wish we could have @EnumId in lombok

### ISSUE THREAD

**Issue by demongaorui** [rzwitserloot/lombok#1375]
In lombok-pg, there is [@EnumId](https://github.com/peichhorn/lombok-pg/wiki/%40EnumId) annotation, feels very useful. While lombok-pg stop updating about 4 years ago. And it's told that lombok-pg does not work well with java 8. So I wish we could have @EnumId in lombok

**Comment by rspilker** [comment]
Duplicate of #706
