### ISSUE TITLE
Incorrectly generated equals() for final nonnull field causes findbugs errors

### ISSUE THREAD

**Issue by smanna1729** [rzwitserloot/lombok#1379]
@Data
public class DocumentExtraData {
    private final String identifier = "ExtraData";
    private boolean active;
    private Map<String, Object> extraData = new HashMap<>();
}

It generates null check which causes findbug issue. Since I have some hard coded value it should not generate the null check.

**Comment by rspilker** [comment]
Without more details it is hard to understand your problem.

But we're probably not going to change anything in the equals/hashcode implementation.

To get rid of the warnings by findbugs, you can instruct findbugs to no longer look at code having the `@lombok.Generated` annotation.
