### ISSUE TITLE
@NonNull should be allowed for type usage

### ISSUE THREAD

**Issue by cvmocanu** [rzwitserloot/lombok#1384]
Enhancement request, similar in purpose to #1011.

The ``@NonNull`` annotation is not allowed on ``ElementType.TYPE_USE``.
This is a pity, since we are using this not only for null checks, but  also for:
- documentation
- IntelliJ inspections

Consider the following code:
```java
List<@NotNull String> list = Arrays.asList("", "");

if (list.get(0) == null) {
    System.out.println("always true");
}
```
IntelliJ correctly shows a warning that the condition is always false. These inspections are very valuable.
But the Lombok annotation cannot be used in this case.

Alternatively, maybe Lombok should allow configuration of the fully qualified class name of the NonNull annotation. This would allow us to use ``org.jetbrains.annotations.NotNull`` which can includes target ``ElementType.TYPE_USE``.

Obviously, we don't expect Lombok to modify any bytecode when the annotation is used in this place.

**Comment by rspilker** [comment]
I have two problems with this:
1. It doesn't do anything apart from documentation
2. If we do this, we probably loose support for java6 and java7, since this constant is introduced  in java8
