### ISSUE TITLE
Changing retention policy to RUNTIME?

### ISSUE THREAD

**Issue by jlecount-qadium** [rzwitserloot/lombok#1388]
Is there a downside to this?  

The reason is, I've got some tests that are generated dynamically and I'd like to be able to get the annotations off lombok-processed classes via reflection.  

Thanks!
Jason

**Comment by jdimeo** [comment]
Yes- Lombok currently isn't required to be bundled/packaged with the final compiled code, so that would throw ClassNotFound exceptions if the annotations were still present. It's nice not to have the installation binaries bloated with the lombok .jar.

**Comment by Maaartinus** [comment]
@jdimeo No, it [would not throw](https://stackoverflow.com/q/3567413/581205). There's currently [hardly any reason](https://stackoverflow.com/q/37064357/581205) to use anything but `Retention.RUNTIME`, but let me try:

- It increases the memory consumption a bit.
- Changing the retention might break binary compatibility (no idea).
- Leaving annotations behind feels "dirty".

I guess, lombok could be *configured* to keep it's annotations? Change the retention to `RUNTIME` and remove or keep them according to the configuration?

**Comment by jdimeo** [comment]
I stand corrected! thanks for the helpful context.

**Comment by jlecount-qadium** [comment]
Thanks, appreciate the feedback.   I've changed it locally in my fork, but makes sense why you might not want it by default.

**Comment by rcomblen** [comment]
It would be great to have RUNTIME retention, so that we can use https://www.archunit.org/ to validate patterns of usage of lombok features.

Of course that would be optional (e.g. a different jar with that feature).

Could this be considered ?

**Comment by rspilker** [comment]
Yes there is a good reason not to make the RUNTIME.

Is would be a new API, used by only a few people, but would require us to keep the annotations. Currently, we remove them. Some code we've written depends on them being removed when processed. So this would require a change in the existing code.

Also, some of the features, like `onConstructor` are not valid java, although they are valid java syntax.

The added maintenance burden outweighs the expected benefits.

**Comment by rcomblen** [comment]
Understood. Thanks for the feedback.
