### ISSUE TITLE
FeatureRequest: @ToString, add a parameter to limit length of fields representation

### ISSUE THREAD

**Issue by jonathanlermitage** [rzwitserloot/lombok#1392]
Use case: I work with an object that represents a magazine article. Title and authors are short, but content may very long. I'd like to show `toString` output in a log file, but the N first characters of article content only.  
Proposal: add a parameter to `@ToString` annotation to set a max length for every field representation.

**Comment by Maaartinus** [comment]
I've just posted a proposal you may like: #1393.

**Comment by jonathanlermitage** [comment]
https://github.com/rzwitserloot/lombok/issues/1393 is a better idea :)  
Closing current issue.
