### ISSUE TITLE
Allow methods to be used in @ToString and @EqualsAndHashCode

### ISSUE THREAD

**Issue by Maaartinus** [rzwitserloot/lombok#1393]
There are many requests for customizing `@ToString` and other annotations, so I'm proposing a simple way (based on ideas from this [discussion][1]) how many such requests can be easily fullfilled: Allow to exclude fields (already possible) and include methods in the computation. So the solution for #1392 would be simply

```
@ToString
class Article {
    private String author;
    private String title;
    @ToString.Exclude
    private String content;

    @ToString.Include
    private String shortenedContent() {
        return content.substring(0, Math.min(content.length, 100));
    }
}
```

This is surely more verbose than some `@ToString(maxLength=100)`, but imagine you need to append the field length. Or there's another field which should never be shortened. Or another field `signature` which is uninteresting, but you want to see its length. This all can be achieved easily with methods inclusion.

---

An alternative stringly typed syntax: `@ToString(exclude="content", include="shortenedContent()")`.

[1]: https://groups.google.com/d/msg/project-lombok/dc5nXTI3xMU/tkgk0OfbAQAJ

**Comment by omega09** [comment]
Includes #1385?

**Comment by Maaartinus** [comment]
@omega09 I don't think, it "includes" it, especially it wouldn't allow you to call the Apache builders. But it'd allow you to do about everything their builders can do, except for [styling][], which is an orthogonal feature.

My proposal is good in case you want to change what happens for some fields while leaving lombok do its usual job for the others. Leaving out an offending field has always been possible, but sometimes, that's too harsh. When you want to summarize it instead, my proposal helps. It tries to combine the flexibility of a hand-written method with Lombok's power of handling boilderplate for free.

[styling]: https://commons.apache.org/proper/commons-lang/javadocs/api-3.1/org/apache/commons/lang3/builder/ToStringStyle.html

**Comment by liweys** [comment]
It will be good if these methods can be customized. I would like to use json presentation for toString().

**Comment by rzwitserloot** [comment]
Working on it: Working on it: https://github.com/rzwitserloot/lombok/wiki/FEATURE-IDEA:-Annotation-based-Include-Exclude-for-ToString,-EqualsAHC,-etc
