### ISSUE TITLE
Configuration lombok.equalsAndHashCode.callSuper is documented to skip the super-call in case of extending Object, but doesn't do  this

### ISSUE THREAD

**Issue by ewirch** [rzwitserloot/lombok#1407]
Documentation says:

> If set to call, lombok will generate calls to the superclass implementation of hashCode and equals if your class extends something.

The important part is *"if your class extends something"*. However, setting the setting to `call` leads to `equals()/hashCode()` implementations which call the super implementation in all cases.

**Comment by rspilker** [comment]
I cannot reproduce the problem. I did add a test to verify the `extends Object` case, but that also works.

The relevant implementations for:

- [eclipse](https://github.com/rzwitserloot/lombok/blob/master/src/core/lombok/eclipse/handlers/HandleEqualsAndHashCode.java#L181)
- [javac](https://github.com/rzwitserloot/lombok/blob/master/src/core/lombok/javac/handlers/HandleEqualsAndHashCode.java#L144)

The tests:

- [before](https://github.com/rzwitserloot/lombok/blob/master/test/transform/resource/before/EqualsAndHashCodeConfigKeys2.java)
- [after-delombok](https://github.com/rzwitserloot/lombok/blob/master/test/transform/resource/after-delombok/EqualsAndHashCodeConfigKeys2.java)
- [after-ecj](https://github.com/rzwitserloot/lombok/blob/master/test/transform/resource/after-ecj/EqualsAndHashCodeConfigKeys2.java)

Please verify the tests and, if possible the implementation. 

If you're still not convinced, please give us an example java file and lombok.config to reproduce the problem.

**Comment by ewirch** [comment]
I can confirm Lombok 1.16.16 behaves correctly. I was observing the delombok output of IntelliJ Lombok Plugin, wich still uses Lombok 1.16.12.

**Comment by rspilker** [comment]
Thanks for the feedback.
