### ISSUE TITLE
@Data is not equivalent to @RequiredArgsConstructor

### ISSUE THREAD

**Issue by cowwoc** [rzwitserloot/lombok#1411]
The Javadoc for `@Data` says it is equivalent to `@Getter @Setter @RequiredArgsConstructor @ToString @EqualsAndHashCode` but I believe that `@RequiredArgsConstructor` should be replaced by `@AllArgsConstructor`

**Comment by novaterata** [comment]
`@RequiredArgsConstructor` means all final fields are required by the constructor.
`@AllArgsConstructor` means all fields including non-final are required by the constructor.
At least in my experience, `@Data` behaves as `@RequiredArgsConstructor`
Here are examples to demonstrate:

    @Data
    static class Foo {
        private final String bar;
        private String baz;

        static Foo create() {
            Foo bar = new Foo("bar");
            bar.setBaz("baz");
            return bar;
        }
    }

    @RequiredArgsConstructor
    static class Foo1 {
        @Getter
        private final String bar;
        @Getter
        @Setter
        private String baz;

        static Foo1 create() {
            Foo1 bar = new Foo1("bar");
            bar.setBaz("baz");
            return bar;
        }
    }

    @AllArgsConstructor
    static class Foo2 {
        @Getter
        private final String bar;
        @Getter
        @Setter
        private String baz;

        static Foo2 create() {
            Foo2 bar = new Foo2("bar", "baz");
            return bar;
        }
    }
