### ISSUE TITLE
Failing to calculate the hashCode with bidirectional references

### ISSUE THREAD

**Issue by avk2** [rzwitserloot/lombok#1413]
I'm using lombok with Spring Data MongoDB entities. 
I'm getting InvocationTargetException when I try to get hashCode from a object that represents this class:

```
@Data
@Document(collection="foos")
public abstract class Foo {
		
	@Id
	protected UUID uid;
	protected final FooType type;
        @DBRef
        protected User user;

}
```

Doing a quick debugging, it fails when it tries to calculate the hashCode from the last attribute: user. The problem I think is caused because of the bidirectional relation. **User has a reference to Foo** too. 

The workaround I do is excluding the reference (from one of the sides) on EqualsAndHashCode

**Comment by Maaartinus** [comment]
I'd expect a `StackOverflowException`. However, I can't recall *any* `hashCode` implementation suited for cyclic structures. It's surely doable, but there's a cost as you have to keep track of all already visited objects (somewhere in a `ThreadLocal<IdentityHashMap<Object, Object>>`).

It still blows whenever you do something like `List l = new ArrayList(); l.add(l); myThing.add(l); myThing.hashCode();`.

So I'm afraid, the workaround is the (only sane) solution.
