### ISSUE TITLE
Feature request: @ParameterSetClass

### ISSUE THREAD

**Issue by victorwss** [rzwitserloot/lombok#1419]
I'm frequently hitting a case like this:

```java
public SomeType someMethod(int dog, @NonNull String cat, Foo bird, Bar cow) {
    // ...
}
```

And I would like to use this:

```java
someMethod(SomeMethodParams.create().dog(123).cat("meow").bird(new Foo()).cow(new Bar()));
```

So, I end up doing that:

```java
@Value
@Accessors(chain = true, fluent = true)
public static class SomeMethodParams {
    private int dog;
    @NonNull private String cat;
    private Foo bird;
    private Bar cow;
}

public SomeType someMethod(SomeMethodParams params) {
    int dog = params.getDog();
    @NonNull String cat = params.getCat();
    Foo bird = params.getBird();
    Bar cow = params.getCow();
    // ...
}
```

However, I would really like that the `SomeMethodParams` class and the getter chain in `someMethod` could be generated by lombok, so I could write something like that:

```java
@ParameterSetClass("SomeMethodParams")
public SomeType someMethod(int dog, @NonNull String cat, Foo bird, Bar cow) {
    // ...
}

private void someOtherMethod() {
    someMethod(SomeMethodParams.create().dog(123).cat("meow").bird(new Foo()).cow(new Bar()));
}
```

Further, the `@ParameterSetClass` annotation could have some fields `onClass` and `onConstructor`. If the value of the `@ParameterSetClass` is not unique, all the clashing methods must have exactly the same set of parameters (but possibly not necessarily in the same order) and the generated class would be reused. Further, that annotation should have some scope rules specifying where the generated class should be placed (nested inside the declaring class, package-level, some other package, etc).

**Comment by rspilker** [comment]
This is already possible with [`@Builder`](https://projectlombok.org/features/Builder). You probably want to provide a builderMethodName, a builderMethodName and a buildMethodName.

You API/code would look slightly different:

```java

class Something {
    @Builder(buildMethodName="execute", builderMethodName="createMethodCaller", builderClassName="SomeMethodExecutor")
    public SomeType someMethod(int dog, @NonNull String cat, Foo bird, Bar cow) {
        // ...
    }
}
```

Then the calling code would look something like this:

```java
Something s = createSomething();
SomeMethodExecutor e = s.createMethodCaller().dog(123).cat("meow").bird(new Foo()).cow(new Bar());
e.execute();
```
