### ISSUE TITLE
static import on @Getter field breaks compilation

### ISSUE THREAD

**Issue by Kosta2206** [rzwitserloot/lombok#1421]
Hi,
@Getter is not working on static fields - compilation error.
I'm using lombok 1.16.10 and java 1.8.0_131.
Example:
```
package utils;
import lombok.Getter;

@Getter
public class TestVariables {
    private static String test = "test";
}

package main;
import utils.TestVariables;

public class Main {
    public static void main(String[] args) {
        System.out.println(TestVariables.getTest());
    }
}

```

**Comment by Maaartinus** [comment]
It does.

https://projectlombok.org/features/GetterSetter (emphasis mine)
> You can **also** put a `@Getter` and/or `@Setter` annotation on a class. In that case, it's as if you annotate **all the non-static fields** in that class with the annotation.

**Comment by Kosta2206** [comment]
When I remove static, then everything fine.

```
package utils;

import lombok.Getter;

@Getter
public class TestVariables {
    private String test = "test";
}
```
```
import utils.TestVariables;

public class Main {

    public static void main(String[] args) {
        System.out.println(new TestVariables().getTest());
    }

}
```
```
 mvn compile
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building test-lombok 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test-lombok ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ test-lombok ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 2 source files to C:\Dev\GIT\TEST\testlombok\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

```

**Comment by victorwss** [comment]
You can annotate the static field directly. So instead of this:

```java
@Getter
public class MyTest {

    private static int x;

    public static void foo() {
        MyTest.getX();
    }
}
```

You should write this:

```java
public class MyTest {

    @Getter
    private static int x;

    public static void foo() {
        MyTest.getX();
    }
}
```

The `@Getter` annotation in the class only create getters for non-static fields. There are a couple of reasons for that, (e.g. you will not want a getter for `serialVersionUID`). To make a static getter, the `@Getter` annotation must be directly in the field.

You could argue that annotating every static field is cumbersome and that some solution should be addressed. But, in my personal opinion and experience, the developer rarely would like to add a bunch of getters en mass to static fields, (s)he whould want to do that only to instance fields. So, I think that the current behaviour makes perfect sense for now. Another possibility would be to suggest something like `@Getter(includeStatic = true)`, but I don't think that this is a common case deserving that.

**Comment by Kosta2206** [comment]
Thanks for explanation.
I finally found the problem, and it is with static imports. Even if @Getter will be on field, like in your example, if you would use static import in some other class you would have compilation exception.
Example with failure:
```
package utils;

import lombok.Getter;

public class TestVariables {
    @Getter
    private static String test = "test";
}
```
```
import static utils.TestVariables.getTest;

public class Main {

    public static void main(String[] args) {
        System.out.println(getTest());
    }
}
```

**Comment by victorwss** [comment]
That issue with static imports seems to be a bug. I was able to reproduce it.

**Comment by omega09** [comment]
See #979 and possibly #884.

**Comment by niks-** [comment]
I have NO static imports BUT still have compilation error when I am trying to use getter created on static field by lombok.

`mport lombok.Getter;
import lombok.extern.log4j.Log4j2;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

@Log4j2
public class TestConfig {
    private static @Getter String browser;
}

public class TestRun {
    public void test() {
        String browser = TestConfig.getBrowser();
    }
}`

Got error
Error:(13, 90) java: cannot find symbol
  symbol:   method getBrowser()
  location: class .TestConfig

Using IntelliJ IDEA + plugin

**Comment by myhau** [comment]
Can I somehow enable (and if I can, I think it should be enabled by default) Lombok's debug / error messages during compilation for things like that ?

**Comment by rzwitserloot** [comment]
As @Maaartinus said lombok does not generate getters for static fields if you put `@Getter` on the class by design. Separate from that, if you attempt to do a static _named_ (i.e. not .*) import of a thing lombok generates, that doesn't work in javac, see bug #2044

**Comment by alexanderankin** [comment]
any chance this will be fixed?
