### ISSUE TITLE
No instruction for Gradle

### ISSUE THREAD

**Issue by bitsal** [rzwitserloot/lombok#1425]
I didn't find any instruction how to configure lombok for Gradle project.
My working version is:
**build.gradle**
```
dependencies {
  compileOnly "org.projectlombok:lombok:1.16.16" // required for Intellij Idea
...
}

apply from: 'gradle/lombok.gradle'
```
where
**lombok.gradle**
```
apply plugin: "net.ltgt.apt"

dependencies {
  compileOnly "org.projectlombok:lombok:1.16.16"
  apt "org.projectlombok:lombok:1.16.16"
}
```

\+ Annotation Processor for Intellij Idea

Could you add it? I think it will be helpful for the community.

**P.S.:**
Let me know if there are any mistakes in my configuration.

**Comment by omega09** [comment]
> I didn't find any instruction how to configure lombok for Gradle project.

This? https://projectlombok.org/mavenrepo/

**Comment by bitsal** [comment]
@omega09 I saw it but `dependencies` is not enough

**Comment by shalugin** [comment]
I use this configuration with MapStruct:

```
plugins {
    id 'net.ltgt.apt' version '0.9'
}

dependencies {
    compileOnly "org.mapstruct:mapstruct-jdk8:1.2.0.Beta3"

    apt "org.mapstruct:mapstruct-processor:1.2.0.Beta3"
    apt "org.projectlombok:lombok:1.16.14"
}

```

**Comment by bitsal** [comment]
@shalugin thank you! it is what I'm talking about. The current version of the doc doesn't cover the real configuration, only part of it.

**Comment by shalugin** [comment]
@bitsal You can submit PR.
I think description on this page - https://github.com/rzwitserloot/lombok/blob/ec6c61d82ac9ac4d8421fdc31176d373d8042e92/website/templates/setup/gradle.html

**Comment by bitsal** [comment]
Ready
