### ISSUE TITLE
Not Working In Eclipse Oxygen

### ISSUE THREAD

**Issue by jakking** [rzwitserloot/lombok#1427]
I know it was just released, but just so people are aware, this does not work for eclipse oxygen. It has validation errors for everything that you were doing with lombok annotations.

**Comment by jinyahuan** [comment]
Since try eclipse oxygen, project do not unwell. And work with:
OS: Win7 X64 , 
Eclipse: eclipse-jee-oxygen-R-win32-x86_64, 
Lombok: lombok-1.16.10.

**Comment by mauricio-ms** [comment]
For me, after installing Lombok on Eclipse Oxygen, it doesn't open anymore.
I've tried several versions of Lombok.

**Comment by cardamon** [comment]
My Eclipse install seems to be working just fine. Setup:
```
Eclipse Java EE IDE for Web Developers.
...
Version: Oxygen Release (4.7.0)
Build id: 20170620-1800
...
Lombok v1.16.16 "Dancing Elephant" is installed. https://projectlombok.org/
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by jakking** [comment]
Mine is not working, and my setup is:

> Eclipse Java EE IDE for Web Developers.
> Version: Oxygen Release (4.7.0)
> Build id: 20170620-1800
 Using Windows 7 Pro 64 bit

My eclipse is opening, it just has validation errors saying that getters and setters do not exist

**Comment by rspilker** [comment]
Hmm. It just works on my machine:
![image](https://user-images.githubusercontent.com/93318/27708336-dd86bea6-5d18-11e7-9bb4-c97b05efc87c.png)

**Comment by rspilker** [comment]
Can you try lombok version 1.16.16?

**Comment by jakking** [comment]
I uninstalled and re installed and now it is showing Lombok is installed.

**Comment by Glamdring** [comment]
Do a Project -> Clean and it picks it up

**Comment by jfzr** [comment]
I cannot get it to work, Oxygen and Lombok 1.16. returns exit = 1 on eclipse launch. Tried re-installing everything.

**Comment by remondeklerk** [comment]
Had the same problem.

My solution: returned from java version 8u144 to 8u141.

**Comment by cardamon** [comment]
I just reinstalled my Ubuntu machine, and couldn't get it to work.
It was caused by creating and using a launcher (a `.desktop` file) _before_ Lombok was installed by using 'lock to launcher'. The `Exec` property in the file will end up missing the `-javaagent` argument.
In this case the solution was simple: unlock from laucher, restart Eclipse, and then lock to launcher again...

**Comment by anthonyz-davis** [comment]
I have Eclipse:

Version: Oxygen Release (4.7.0)
Build id: 20170620-1800

and when I install Lombok 1.16.18 it won't open at all.  

On Windows 10.

**Comment by SudheendraSingh** [comment]
I installed lombok on Eclipse Oxygen and it had issues.
In my case Lombok was installed and the eclipse.ini file had this entry
-javaagent:lombok.jar

I had to edit it to give the correct path and it worked.

**Comment by caijq4ever** [comment]
Eclipse version: Oxygen
OS: Ubuntu 14.04
Java version: 1.8.0_144

**If eclipse.desktop exist, remove it.**
1. java -jar /path/to/lombok.jar
2. cd /path/to/eclipse & ./eclipse
3. lock Eclipse to the Launcher

![2017-10-09 17 04 52](https://user-images.githubusercontent.com/5621857/31331267-3a850a04-ad14-11e7-89cd-0de0b54e8645.png)

**Comment by nrohluap** [comment]
My installation quit working properly after installing SpringToolSuite. Eclipse now flags any instance of log in a class annotated with @Slf4j, and also flags any class using getter/setters of @Data objects. 

Re-installing, upgrading from 1.16.18 to 1.16.20, cleaning projects .... nothing. Sometimes (!) doing a project clean "fixes" the issue, until I do a "Run as ... SpringBoot application" Then all the red flags show up again, and Eclipse says it can't run the project due to compilation problems. Running from gradle command line or just java -jar works fine.

**Comment by fco271292** [comment]
I am use Eclipse Oxygen v3, and tried to install Lombock, but is not show description in About Eclipse, also down grade the version of java to 1.8.0_152, but no recongnize Lombock and send errors in project, tell me please what need to do.
![eo3](https://user-images.githubusercontent.com/20331087/38174744-b8f09334-3597-11e8-8f4d-5eadc6d92107.PNG)

**Comment by xingchch** [comment]
Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200
Lombok v1.16.20 "Dancing Elephant" is installed.

lombok installed success, but lombok still cannot be resolved

**Comment by golangscott** [comment]
> Do a Project -> Clean and it picks it up

well done!

**Comment by joiscadz** [comment]
> For me, after installing Lombok on Eclipse Oxygen, it doesn't open anymore.
> I've tried several versions of Lombok.

Hi, Could you solve this problem?
