### ISSUE TITLE
Compilation fails without stub of builder class

### ISSUE THREAD

**Issue by chriskessel** [rzwitserloot/lombok#1434]
I'm using 1.16.16.

I can't figure out what causes this or why only one file seems to be the culprit. I have a class like so that fails to compile. All usages of the lombok accessors result in "can't find symbol" errors.
```
@Value
@EqualsAndHashCode(callSuper = true)
Class Foo extends Bar {
  ...lots of instance vars...

  @Builder(toBuilder=true) // When I have superclasses, I need @Builder on the constructor since lombok doesn't generate constructors that call the super-constructor
  public Foo(...args for all the instance vars...)  {
    super("a superclass var value");
    this.varA = varA;
    ...etc...
  }
}
```

However, if I add the builder class myself, just the stub, that's enough that it works again. I have no idea why, but it's very consistent. If I comment out the Builder class stub, it fails, comment it back in, it works...and only for this one class. The class does have a lot of instance vars (maybe 40), it's a big POJO.

This works:
```
@Value
@EqualsAndHashCode(callSuper = true)
Class Foo extends Bar {
  ...lots of instance vars...

  @Builder(toBuilder=true) // When I have superclasses, I need @Builder on the constructor since lombok doesn't generate constructors that call the super-constructor)
  public Foo(...args for all the instance vars...)  {
    super(varA, varB);
    this.varC = varC;
    ...etc...
  }

  public static class FooBuilder {}  // Why is this necessary? What makes this particular lombok'd class special?
}
```

I have another class that literally does the same exact lombok things (just far fewer instance vars) and it's fine without this hack. It has an inheritance, it has @Builder on the constructors, it's in the same package. I can't find anything to distinguish why one class is fine without stubbing the builder and the other isn't.

**Comment by rzwitserloot** [comment]
We've done a lot of work on builder; I doubt this is still a problem. If it still doesn't work on the current edge release from https://projectlombok.org/download-edge please re-open and show us exactly what error you're getting. "It errors" is a bit hard to go on.
