### ISSUE TITLE
@ExtensionMethod fails on Eclipse Oxygen if there is more than 1 parameter 

### ISSUE THREAD

**Issue by Kilrath** [rzwitserloot/lombok#1441]
Following simple example fails with an ArrayIndexOutOfBoundsException due to compiling with Eclipse Oxygen (jdk 1.8+):

public class A {
    public static Object test(Object object, **_Object returnThis_**) {
        return returnThis;
    }
}

@ExtensionMethod(A.class)
class B {
    public Object testExtensionMethod(Object object) {
        return object.test(new Object());
    }
}

**Exception**
Internal compiler error: 
 java.lang.ArrayIndexOutOfBoundsException

In Eclipse Neon it works!

**Comment by dtmendes** [comment]
I have the same problem and Eclipse show that error
Internal compiler error: java.lang.ArrayIndexOutOfBoundsException: 1 at org.eclipse.jdt.internal.compiler.ast.MessageSend.analyseCode(MessageSend.java:182)

**Comment by janaroj** [comment]
Having the same issue with Eclipse Oxygen:
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.analyseCode(MessageSend.java:182)

**Comment by mad-pojo** [comment]
I make a correction: @ExtensionMethod fails if there are exactly 2 parameters.
Workaround: in the preferences "Java / Compiler / Errors/Warnings" switch the options "Unlikely argument type for collection methods using 'Object'" and "Unlikely argument type for method equals()" to "Ignore". 
[This feature](http://www.eclipse.org/eclipse/news/4.7/jdt.php#unlikely-argument-types) will be ignored.
