### ISSUE TITLE
@EqualsAndHashCode sub-property

### ISSUE THREAD

**Issue by bojanv55** [rzwitserloot/lombok#1446]
Is it possible to supply `@EqualsAndHashCode` with subproperty?

e.g. 

`@EqualsAndHashCode(of = "currentProperty.subProperty")`

**Comment by Maaartinus** [comment]
AFAIK no, and I can't remember such a request. I guess, my proposal would help: #1393.
```
@EqualsAndHashCode.Exclude
private Whatever currentProperty;

@EqualsAndHashCode.Include
private Whatever2 subprop() {
    return currentProperty.subProperty;
}
```
It's rather verbose, but pretty general. If you like it, please vote for it (by using the smiley icon, not by posting +1!).

**Comment by rzwitserloot** [comment]
Via annotate-inclusion-on-methods you can add this behaviour. We're working on that: Working on it: https://github.com/rzwitserloot/lombok/wiki/FEATURE-IDEA:-Annotation-based-Include-Exclude-for-ToString,-EqualsAHC,-etc
