### ISSUE TITLE
toBuilder needs the ability to override the toBuilder method name.

### ISSUE THREAD

**Issue by chriskessel** [rzwitserloot/lombok#1448]
I have a class Foo and a subclass FooBar and I want both to have @Builder(toBuilder=true). It won't compile because it says:

```
error: toBuilder() in SubFoo cannot override toBuilder() in Foo
  return type SubFooBuilder is not compatible with FooBuilder
1 error
```
I've been trying different ways of manually writing some of the builder generated code instead of letting lombok do it, but I haven't found a way to make this work without completely writing my own myToBuilder() in one of the classes and dropping the toBuilder=true.

**Comment by chriskessel** [comment]
Ok, despite hours of hacking at it, I stumbled on a simple work around shortly after filing this issue. It'd still be nice to be able to override the toBuilder() method name though. The workaround is you declare the builder class in the superclass, then have the subclass builder class extend it.

``
public static class FooBuilder {
    protected FooBuilder() {} // Required or the subclass can't access the generated private no-arg constructor.
}
public static class FooBarBuilder extends FooBuilder {}
```

**Comment by rzwitserloot** [comment]
using `@Builder` on a class that has a parent class is not really supported.

However, `@SuperBuilder` is designed specifically for that usecase! give it a shot. Support for `@SuperBuilder` is available in the current edge release: https://projectlombok.org/download-edge
