### ISSUE TITLE
Cannot find Symbol error while using Lombok Annotations.

### ISSUE THREAD

**Issue by mukeshkamboj** [rzwitserloot/lombok#1449]
I am getting below error while using the lombok.

> cannot find symbol
> [ERROR]   symbol:   method builder()
> [ERROR] symbol: getXXXXXX()

below are the annotation, I am using.
```
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Builder(toBuilder = true)
@Data
@NoArgsConstructor(access = AccessLevel.PRIVATE,force = true)
```

Maven version is 3.5.0
Below is the pom.xml entries.

```
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.2</version>
				<configuration>
					<compilerVersion>1.8</compilerVersion>
					<source>1.8</source>
					<target>1.8</target>
					<encoding>UTF-8</encoding>
					<compilerArgument>-proc:none</compilerArgument>
					<annotationProcessors>
<annotationProcessor>lombok.launch.AnnotationProcessorHider$AnnotationProcessor</annotationProcessor>
					</annotationProcessors>
				</configuration>
			</plugin>
		</plugins>
	</build>

<dependencies>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.16.18</version>
			<scope>provided</scope>
		</dependency>

</dependencies>
```

Please advise what is this issue?

**Comment by jscharett** [comment]
Was able to resolve my issue.  Did not realize that variables declared final had no setter.

**Comment by mukeshkamboj** [comment]
@rspilker Could you please help on this? I m still facing this error.

**Comment by mukeshkamboj** [comment]
I got the [solution](https://github.com/rzwitserloot/lombok/issues/905) of this problem. I had to remove <compilerArgument>-proc:none</compilerArgument> that was preventing the lombok annotation to be processed.

**Comment by BhargavChoksi** [comment]
> I got the [solution](https://github.com/rzwitserloot/lombok/issues/905) of this problem. I had to remove -proc:none that was preventing the lombok annotation to be processed.
@mukeshkamboj Thanks Mukesh! I just tried every damn thing with my intellij. Your comment helped me to get rid of the issue.

**Comment by pengw00** [comment]
hi, where is the -proc:none located?

> I got the [solution](https://github.com/rzwitserloot/lombok/issues/905) of this problem. I had to remove -proc:none that was preventing the lombok annotation to be processed.

**Comment by xiaotiao** [comment]
i don't know but it solve my problem.

i have two classes use @Builder to generate build method. but one is normal, another is abnormal,everything check is ok. but when i run mvn to compile my project, the error as fellow:

can't not find the symbol method builder()

i try to replace the version of the lombok jar, but even through i make the version is latest, it's not ok.

so, i try to import lombok per class that i reference.

it works! it seems a bug.
