### ISSUE TITLE
@Delegate's page should note that methods generated by it are not displayed in IDEs' outline

### ISSUE THREAD

**Issue by omega09** [rzwitserloot/lombok#1455]
The "small print" section on the `@Delegate` page on the Lombok site should mention that methods generated by this annotation do not appear in the outline view in IDEs (in contrast to everything generated by `@Data` for example).

**Comment by wiwie** [comment]
is this indeed intended? I was just trying out @Delegate and first thought it didn't work alltogether because no delegates were shown in the outline (eclipse).
