### ISSUE TITLE
new Annotation @Fluent only for method calls to avoid long parameter lists

### ISSUE THREAD

**Issue by nimo23** [rzwitserloot/lombok#1464]
Please provide a new annotation "@Fluent", which can be annotated only on a method and makes the method-call with all its properties fluently. Such as 

```

@Fluent
public static void test(@Optional User user, int age, ...){
// @Optional makes a parameter optional (default is not optional for all parameters)
..
}
```

To call this method with fluent-style:

`method().builder().addUser(user).addAge(25).invoke();`

The "@Builder"-Pattern is good but not specialized to the needs for a fluent **method** call.

https://stackoverflow.com/questions/46083756/lombok-builder-on-method#46084015

**Comment by nimo23** [comment]
The "@Fluent" Api 
- should not override toString().
- should provide different builders for same return type but different method (no property sharing).

**Comment by rspilker** [comment]
It is. You can put @Builder on any static method. You might want to add a few tweaking parameter. In your example you can even make the method private.

```java
@Builder(builderClassName = "TestBuilder", buildMethodName = "execute", builderMethodName = "test")
private static void _test(User user, int age) {
}

void foo() {
  test().user(new User("me")).age(18).execute();
}
```
