### ISSUE TITLE
get WARNING while maven package with JDK-9 released yesterday.

### ISSUE THREAD

**Issue by xiongchen2012** [rzwitserloot/lombok#1471]
$maven package
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by lombok.javac.apt.LombokProcessor to field com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs
WARNING: Please consider reporting this to the maintainers of lombok.javac.apt.LombokProcessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
My lombok version is 1.16.16

JavacTransformer become unresolved?

**Comment by xiongchen2012** [comment]
1.16.18 get the same warning.

**Comment by ottlinger** [comment]
+1 same with https://github.com/ottlinger/fotorenamer/

**Comment by rspilker** [comment]
The solution is to add some -J--add-opens arguments to the compiler, however, that won't help you for now because of a bug in the compiler-plugin. Please vote for issue MCOMPILER-291 to get this fixed.

One other thing, it did compile on my machine, but possibly I just didn't fail on warnings.

**Comment by ottlinger** [comment]
@rspilker thanks for the reference to [MCOMPILER-291](https://issues.apache.org/jira/browse/MCOMPILER-291) - I tried to add the references, but still get errors .... can you reference a project that works on github/travis? Thanks.

**Comment by rspilker** [comment]
The fix is described in https://github.com/rzwitserloot/lombok/issues/985#issuecomment-337741287

**Comment by ajeet0203** [comment]
we can change manually our error through the actual code which written in in maven site or its jar file..
copy and write our program and test what is actual problem..
its maven fault or our programming error or any problem in our own system..
@sorry when its wrong ...
i'm just give you my point of view..
