### ISSUE TITLE
@EqualsAndHashCode(callSuper=false)

### ISSUE THREAD

**Issue by lly835** [rzwitserloot/lombok#1477]
when i build project, show
`ating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type. @Data ^`
i don't want to add @EqualsAndHashCode(callSuper=false) at every object, what should i do?

**Comment by rspilker** [comment]
As you can read in [the documentation](https://projectlombok.org/features/EqualsAndHashCode#supported-configuration-keys) in the section "Supported configuration keys" it is possible to put the following line in a `lombok.config` file:
```
lombok.equalsAndHashCode.callSuper=skip
```

I would recommend to put this `lombok.config` file in the directory containing the code where you are sure that that's the right behavior.

If you want it in your whole project, you can put it in the root of all your source code.
