### ISSUE TITLE
@Builder(toBuilder = true) compiling error when used on constructor of a sub class

### ISSUE THREAD

**Issue by buwoyouwo** [rzwitserloot/lombok#1488]
Origin issue on stackoverflow : <https://stackoverflow.com/questions/46481383>

My code is as followd

```java
package test.lombok;

import lombok.*;

@AllArgsConstructor(access = AccessLevel.PROTECTED)
@Getter
public class SuperClass {

    private int foo;

    @Getter
    public static class SubClass extends SuperClass {

        private int bar;

        @Builder(toBuilder = true)
        private SubClass(int foo, int bar) {
            super(foo);
            this.bar = bar;
        }

    }
}
```

As showed above, I'm trying to use `@Builder(toBuilder = true)` on a sub class.

When `toBuilder` set to false, there is no problem at all.

But when I set `toBuilder = true`, I got an compilation error "Error:java: foo has private access in test.lombok.SuperClass".

**Comment by rzwitserloot** [comment]
We can't fix this; builder in general is not compatible with classes that extend stuff.

If you control all the classes in your hierarchy (except j.l.Object of course), there's `@SuperBuilder`, a new feature to be released in 18.4 (we'll get that out the door soon).
