### ISSUE TITLE
No getter method generated from private static final String with Data annotated to a class

### ISSUE THREAD

**Issue by cinqs** [rzwitserloot/lombok#1493]
Hi,

With Lombok 1.16.18,
Java 8
and following java code:

```java
@Data
@AllArgsConstructor
@Slf4j
public abstract class FinancialSecuritiesFileScanner implements IFinancialSecuritiesFileScanner {

	protected String folderPath;
	protected SupportedFormat extension;
	protected boolean enableScheduling;
	
	@Getter
	private static final String DEFAULT_CRON = "20 * * * * *";
	
	protected boolean determineScheduling(String cron) {
		return ":20 * * * * *".equals(cron);
	}
	
	public enum SupportedFormat {
		CSV("csv"),
		XML("xml"),
		XLS("xls"),
		XLSX("xlsx");
		
		private String extension;
		SupportedFormat(String extension) {
			this.extension = extension;
		}
		
		public String getExtension() {
			return this.extension;
		}
	}
}
```

if not annotate `DEFAULT_CRON` with `Getter`, there won't be a getter method for it.

But according to your documentation, here

> All together now: A shortcut for @ToString, @EqualsAndHashCode, @Getter on all fields, and @Setter on all non-final fields, and @RequiredArgsConstructor!

this should work, but didn't

**Comment by Maaartinus** [comment]
You're right. This sounds like a documentation bug. AFAIK `@Data` is supposed to work like

*`@ToString`, `@EqualsAndHashCode`, `@Getter`, `@Setter` and `@RequiredArgsConstructor` on the whole class*

This makes sense, as etters for static fields hardly ever make sense. Usually, classes have a few private static fields which should stay really private and auto-generating etters for them would make `@Data` harder to use.

**Comment by cinqs** [comment]
I don't think `private static` fields in classes *should stay really private*, I think a `@Getter` method for them is usually necessary. Don't you think so?

**Comment by Maaartinus** [comment]
@cinqs Me? Sure.

As a `static` field means global state, it's better to avoid it, unless it's a constant (but then you usually just make it `public static final`). If you need static non-constants, then it's better to keep them private. Etters make it slightly better by providing some control.

Singletons are evil, but considered to be better than statics. Dependency injection is considered to be the ultimate good.

For anything global, I use Guice with `@Singleton`, so I get a proper object with non-static fields, which gets injected where needed. This works nicely with Lombok: https://softwareengineering.stackexchange.com/a/256177/14167

I can't recall when I recently used any etters with static fields. I'm not saying, it's *never* needed, but it should be used very rarely. Therefore, I consider `@Data` ignoring statics right.

**Comment by cinqs** [comment]
ok, then, I will add `@Getter` myself. And you fix the documentation declaration.
