### ISSUE TITLE
Property accessors naming not according Java bean specification

### ISSUE THREAD

**Issue by tinustate** [rzwitserloot/lombok#1496]
Yesterday i bumped into a problem regarding the naming of the generated getter method which causes problems when used with commons.BeanUtils.

I made a topic on stackoverflow which contains all the "dirty" details:
https://stackoverflow.com/questions/46753938/beanutils-unknown-property-on-class-pinkymoreandmore-works-pmoreandmore-not

Fixing this might be a bit of a problem cause lombok wouldn't be backward compatible. Maybe implement a configuration setting that allows you to use strict java bean specification?

Cheers!

**Comment by victorwss** [comment]
This seems to be a duplicate of #1453 and #757.

**Comment by rzwitserloot** [comment]
Duplicate of #2693
