### ISSUE TITLE
use lombok at android studio 3.0 stable and gradle 3.0.0

### ISSUE THREAD

**Issue by aliang5820** [rzwitserloot/lombok#1506]
i config these:
```
dependencies{
    compile 'org.projectlombok:lombok:1.16.18'
    annotationProcessor "org.projectlombok:lombok:1.16.18"
}
```
IDE: android studio 3.0 stable
Gradle version: 3.0.0
JDK8, Windows10 pro

so I can use debug ,but can't release apk.

`
Warning: lombok.ConfigurationKeys$1: can't find superclass or interface lombok.core.configuration.ConfigurationKey

Warning: lombok.delombok.ant.Tasks$Delombok: can't find superclass or interface org.apache.tools.ant.Task

Warning: lombok.javac.apt.Processor: can't find superclass or interface javax.annotation.processing.AbstractProcessor

Warning: lombok.launch.AnnotationProcessorHider$AnnotationProcessor: can't find superclass or interface javax.annotation.processing.AbstractProcessor

Warning: lombok.launch.AnnotationProcessorHider$AstModificationNotifier: can't find superclass or interface org.mapstruct.ap.spi.AstModifyingAnnotationProcessor

Warning: lombok.launch.AnnotationProcessorHider$ClaimingProcessor: can't find superclass or interface javax.annotation.processing.AbstractProcessor

Warning: lombok.launch.PatchFixesHider$ExtensionMethod: can't find referenced class org.eclipse.jdt.internal.compiler.lookup.TypeBinding
`  
more than 700+ this warning

and i have a  question: I use android studio, why need eclipse jars?
`Warning: lombok.launch.PatchFixesHider$ExtensionMethod: can't find referenced class org.eclipse.jdt.internal.compiler.lookup.TypeBinding`

**Comment by rspilker** [comment]
First of all, you don't need eclipse jars, nor the ant task.

Do you have any ideas what generates these warnings? A am not a Gradle export, but possibly, using `compileOnly` instead of `compile` helps?

**Comment by aliang5820** [comment]
@rspilker thanks,let me try today.

**Comment by rspilker** [comment]
Did you try?

**Comment by Michels10** [comment]
I'm also receiving this error with Android Studio 3.0 and gradle 3.0

```
Error:Execution failed for task ':app:javaPreCompileDebug'.
> Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
    - lombok-1.16.18.jar (org.projectlombok:lombok:1.16.18)
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
  See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.
```

**Comment by rspilker** [comment]
Any feedback?

**Comment by mck182** [comment]
I can confirm that using `compileOnly` instead of
`compile` fixed the build for me.
