### ISSUE TITLE
Compilation errors issued for correct lombok annotations

### ISSUE THREAD

**Issue by marcingrabda** [rzwitserloot/lombok#1507]
Hi,

I have recently worked on upgrading some libraries in my project, and I faced an issue, where lombok would report compilation errors for correctly applied annotations. There were other problems in the project that had to be fixed, but lombok was simply causing unnecessary noise with these annotations, which made it more difficult to fix errors. Once I chased down and fixed the root cause issues, it worked fine, but initially it looked like something was wrong with lombok itself.

The most common error was related to Builder annotation, and looked like this:

```
/path/to/SomeClass.java:18: error: cannot find symbol
   public static SomeClass.Builder fromClass(SomeClass someClass) {
                           ^
  symbol:   class Builder
  location: class SomeClass
```

Thanks and regards,
Marcin

**Comment by rspilker** [comment]
Without more information, I don't have a way to reproduce this problem.

**Comment by marcingrabda** [comment]
I don't see a way I could create a sample configuration in a reasonable amount of time, since it's also very project dependent. If I do, then I'll let you know, but let's close the issue for now.

**Comment by rspilker** [comment]
Thanks for your quick response.
