### ISSUE TITLE
Use lombok to handle DI stuff

### ISSUE THREAD

**Issue by dawei101** [rzwitserloot/lombok#1511]
Currently,Most Dependency Inject is done under framework, like Spring context, Guice .But most of these framework have to work in runtime, and it have to work under a context-like things. 

Lombok run in compile-time, if dependency-Inject could be managed by it , that would be an excellent feature which would crush all other "FRAMEWORK" then.

 @rzwitserloot  @rspilker , How do you think? I could spend time work on it immediately.

**Comment by Maaartinus** [comment]
I don't think, Lombok could help with DI, as it need to inspect other classes. Which is a big problem at the compilation stage when Lombok works.

But DI using annotation processing seems to be a solved problem: https://github.com/google/dagger

**Comment by rspilker** [comment]
I totally agree with Maaartinus.
