### ISSUE TITLE
Lombok 1.16.18 @RequiredArgsConstructor Doesn't support nested abstract classes that extend their parent class

### ISSUE THREAD

**Issue by jasonCodesAway** [rzwitserloot/lombok#1513]
The code speaks!: 

```
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public abstract class Animal {

    private final String name;

    @RequiredArgsConstructor
    public static class Eagle extends Animal {

        private final int maxSpeedKnots;
    }
}
```

> -------------------------------------------------------------
> COMPILATION ERROR : 
> -------------------------------------------------------------
> com/test/Animal.java:[12,5] constructor Animal in class com.test.Animal cannot be applied to given types;
>   required: java.lang.String
>   found: no arguments
>   reason: actual and formal argument lists differ in length
> 1 error

**Comment by wrprice** [comment]
It has nothing to do with nested and/or abstract classes.  The `@...Constructor` annotations don't support parent classes that _don't have_ an accessible no-argument constructor.  The error is the same whether or not the child is nested and whether or not the parent is abstract.

The cause is the `@RequiredArgsConstructor` on `Animal` which gives the class the single, following constructor:

```
public Animal(String name) {
    this.name = name;
}
```

It doesn't make much sense in this example, but if there were a sensible default value for `name` then adding the following constructor to `Animal` would resolve the error.  (But all `Eagle` instances should share the same default name.):

```
protected Animal() {
    this("default name");
}
```

**Comment by jasonCodesAway** [comment]
> It has nothing to do with nested and/or abstract classes. The @...Constructor annotations on subclasses don't support parent classes without an accessible no-argument constructor. 

Here is a subclass that has a parent without an accessible no-argument constructor, and javac is happy. 

```
@RequiredArgsConstructor
public abstract class Animal {

    private final String name;

    @RequiredArgsConstructor
    public static class Eagle extends Animal {

        private final int maxSpeedKnots;

        public Eagle(int maxSpeedKnots, String name) {
            super(name);
            this.maxSpeedKnots = maxSpeedKnots;
        }
    }
}
```

> ------------------------------------------------------------------------
> BUILD SUCCESS
> ------------------------------------------------------------------------

Examining the "Animal" class in Netbean's navigator shows that @RequiredArgsConstructor does indeed generate the expected "public Animal(String name)" constructor. 

I know I've seen other examples where I've had @RequiredArgsConstructor work effectively the same as Netbean's default constructor generator, even with final variables in the parent class. I'll look for a repro case.

**Comment by Maaartinus** [comment]
> Here is a subclass that has a parent without an accessible no-argument constructor, and javac is happy.

@jasonCodesAway Javac may be happy, but my eclipse is depressed. I wonder what `Eagle` constructor did generated as the only sane choice has the same signature as your explicit constructor. So there should be at least a warning.

> The `@...Constructor` annotations on subclasses don't support parent classes without an accessible no-argument constructor.

@wrprice In general, you're right as Lombok normally knows nothing about other classes. But it does know all the classes in *the same source file* and I believe to remember that it worked. I'm not sure at all.

**Comment by wrprice** [comment]
@Maaartinus thanks for that clarification, I didn't know that.

FYI, I locally tested on a project using *1.16.4* and get the same error, even when the classes are nested.  So, if Lombok _could_ in this case, it hasn't for a number of releases now.

```
@RequiredArgsConstructor
public class Foo {
    private final String s1;

    @RequiredArgsConstructor
    public static class Bar extends Foo {
        private final String s2;
    }
}
```

<blockquote>
consturctor Foo in class Foo cannot be applied to given types;<br>
  required: String<br>
  found: no arguments<br>
  reason: actual and formal argument lists differ in length
</blockquote>

NetBeans shows Foo has constructor `Foo(String s1)`, and Bar has constructor `Bar(String s2)`.

**Comment by wrprice** [comment]
@jasonCodesAway yes, Animal has `public Animal(String name)`, but the problem is that _Eagle's constructor_ is assuming it can implicitly or explicitly call `super()` -- which doesn't exist in Animal.

I loaded your most recent code snippet into NetBeans on 1.16.4 and it complains, same error.  Javac also complains.  I can't understand how you'd get _BUILD SUCCESSFUL_ with that code as-is, built from a clean workspace.

**Comment by jasonCodesAway** [comment]
I'm on jdk 1.8_144, how about you?
Netbeans did complain but javac was happy. Its odd, I've been using this
annotation in abstract classes in a large code base with lots of private
finals and haven't had issues until recently. I might revert back to the
older version of lombok that I was using and see how that goes.


On Nov 10, 2017 at 12:24, <William Price <notifications@github.com>> wrote:

@jasonCodesAway <https://github.com/jasoncodesaway> yes, Animal has public
Animal(String name), but the problem is that *Eagle's constructor* is
assuming it can implicitly or explicitly call super() -- which doesn't
exist in Animal.

I loaded your most recent code snippet into NetBeans on 1.16.4 and it
complains, same error. Javac also complains. I can't understand how you'd
get *BUILD SUCCESSFUL* with that code as-is, built from a clean workspace.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rzwitserloot/lombok/issues/1513#issuecomment-343534738>,
or mute the thread

**Comment by Maaartinus** [comment]
@wrprice I may have been talking nonsense. In
https://github.com/rzwitserloot/lombok/blob/master/src/core/lombok/eclipse/handlers/HandleConstructor.java#L329
I can't see any handling of super-fields. Maybe it was just a proposal... I really can't recall.

**Comment by wrprice** [comment]
@jasonCodesAway - NetBeans and javac (via Gradle) unhappy with the generated `Eagle(String)` c'tor on 8u92 and 8u152, both using Lombok 1.16.4.

**Comment by jasonCodesAway** [comment]
Java 1.8.0_144 seems happy + Maven 3.5.0 seem happy:
![lombok1](https://user-images.githubusercontent.com/14617506/32782428-609678c2-c916-11e7-9d14-eef48a84eebc.png)

**Comment by jasonCodesAway** [comment]
Oh wow. That is scary. This does **not** compile with JDK 1.8_152. I have a lot of code that depends on this feature (makes it easy to create lots of small java classes used with GSON). Would the Lombok Team be inclined to support @RequiredArgsConstructor with nesting if the classes are defined in the same file (or better yet, defined anywhere, i.e. replace each IDE's automated constructor generation)?

**Comment by wrprice** [comment]
@jasonCodesAway bizarre. Have you tried looking at the `javap` output from the successfully compiled class on 8u144?  I wonder what `javac` is actually emitting in the "successful" case.

**Comment by jasonCodesAway** [comment]
@wrprice sorry to disappear, I'm on vacation and won't be back until January. Unfortunately I haven't used javap in the past. I believe my best course of action is to go through my code base and manually generate all the constructors using Netbeans's auto-generate constructor feature for any classes that extend another class. Lombok is amazing.! This is a minor inconvenience :) I'll close this issue as I think the support for my case wasn't intentional.
