### ISSUE TITLE
HandleGetter (et al) failed on my-java-file: NoSuchFieldError: members_field using Intellij

### ISSUE THREAD

**Issue by bohemian** [rzwitserloot/lombok#1514]
Lombok 1.16.14 has introduced a problem not found in 1.16.12

JDK: 1.8
Lombok: 1.16.14
Environment: Intellij Ultimate 2017.2.5 (latest) with lombok plugin (latest, installed today)
Project type: maven

Downgrading to lombok 1.16.12 fixes the problem
The problem does not occur when building from the command line using mvn

All annotations I used gave this error, specifically `@Getter`, `@Data` and `@RequiredArgsConstructor`

Compiler error message (1 for every use of a lombok annotation):

> Error:java: Lombok annotation handler class lombok.javac.handlers.HandleGetter failed on MyClass.java: java.lang.NoSuchFieldError: members_field

Probably obvious, but for completeness, "members_field" does not appear anywhere in my source code.

**Comment by rspilker** [comment]
This is a jdk9 problem, solved in 1.16.18.

**Comment by bohemian** [comment]
@rspilker Except, as per the report, I was using 1.8 not 1.9.

**Comment by rspilker** [comment]
Can you try 1.16.18 or [the edge release](https://projectlombok.org/download-edge). It is related to jdk9.
