### ISSUE TITLE
Builder should allow copying values from other instance

### ISSUE THREAD

**Issue by jaroslawrosiek** [rzwitserloot/lombok#1524]
I would like to use lombok to create immutable data objects. Right now it is very cumbersome because it is hard to create a copy of a data object with some fields changed. For example:

```
@Getter
@Builder
public class X {
  private String a;
  private int b;

  public X withA(String value) {
    return builder()
        .a(value)
        // here I have to manually copy all remaining fields
        .b(b)
        .build()
  }
}
```

I would be really handy be able to do:
```
X x1 = ...;
X.builder()
    .from(x1)
    .a(newValueForA)
    .build()
```

**Comment by Maaartinus** [comment]
`x1.toBuilder()` (needs to be enabled in the annotation).

See also `@Wither`.

**Comment by jaroslawrosiek** [comment]
Great! 

Thanks, I think we can close this issue :)
