### ISSUE TITLE
@Builder.Default: error: non-static type variable T cannot be referenced from a static context

### ISSUE THREAD

**Issue by hosswald** [rzwitserloot/lombok#1527]
### Short description
_Using ```@Builder``` on a generic class with a ```@Default``` T-typed variable, I get the above compile error._

### Expected behavior
_It should compile._

### Version information

 * **IDEA Version:** _IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.3727.22, built on November 15, 2017
IntelliJ IDEA EAP User
Expiration date: December 15, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0_
 * **JDK Version:** _I believe it's the same as the JRE version_
 * **OS Type & Version:** _Windows 10 Version 1703_
 * **Lombok Plugin Version:** _0.15.17.2_
 * **Lombok Dependency Version:** _1.16.18_

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Try to compile the following minimal example:
```
import lombok.Builder;
import lombok.Builder.Default;

@Builder
public class GenericsBuilderExample<T> {
    @Default private T variable = null; // it compiles if I remove the redundant initializer
}
```
 2. Get the following compile error:
```
C:\Users\...\GenericsBuilderExample.java:4: error: non-static type variable T cannot be referenced from a static context
@Builder
^
```
I tried compiling with --stacktrace, --info and --debug, but got no useful information.

Removing the initializer is not an option (and silly when using @Default), since my concrete use case looks more like this:
```
@Default private Function<T, Boolean> function = (x) -> true; // leads to the same compile error
```

Apart from being incorrect (no handling of `@Default` resulting in incorrect semantics), the Delombok'd version compiles:
```
import lombok.Builder.Default;

public class GenericsBuilderExample<T> {
    @Default private T variable = null;

    @java.beans.ConstructorProperties({"variable"})
    GenericsBuilderExample(T variable) {
        this.variable = variable;
    }

    public static <T> GenericsBuilderExampleBuilder<T> builder() {return new GenericsBuilderExampleBuilder<>();}

    public static class GenericsBuilderExampleBuilder<T> {
        private T variable;

        GenericsBuilderExampleBuilder() {}

        public GenericsBuilderExampleBuilder<T> variable(T variable) {
            this.variable = variable;
            return this;
        }

        public GenericsBuilderExample<T> build() {
            return new GenericsBuilderExample<>(variable);
        }

        public String toString() {return "GenericsBuilderExample.GenericsBuilderExampleBuilder(variable=" + this.variable + ")";}
    }
}
```

**Comment by rspilker** [comment]
I can reproduce the problem.

**Comment by linehammer** [comment]
Java main() method cannot access a non-static member of its class. That means, public static void main(String[] args) is a static method. Instance variables (variables defined in the class but not marked as static keyword) cannot be accessed from a static method without referencing an instance of the class. An attempt to use the variables and methods of the class which do not have the static modifier without creating an instance of the class is caught by the Java compiler at compile time and flagged as an error: Cannot Be Referenced From a [Static Context](http://net-informations.com/java/err/static.htm) . To solve your problem, you need to create an instance of your class and then you can access the methods and variables of the class that have not been declared with the static modifier .

Static methods are useful if you have only one instance where you're going to use the method, and you don't need multiple copies (objects). Non-static methods are used if you're going to use your method to create multiple copies.
