### ISSUE TITLE
@changeState feature proposal

### ISSUE THREAD

**Issue by publicocean0** [rzwitserloot/lombok#1535]
this feature could improve alot the java performance for many projects.
synchronzed keyword in java is essentially a exclusive lock so every time multiple threads are entering ,all threads except one will be blocked. The block generate a switch context in OS that comsumes a lot of time. A better solution would be replace exclusive lock with read-write lock. 
Normally developers use synchronized because it is easy to use and normally in the code there are many read accesses and few write accesses.
Using instrumentation is possible read byte code synchnization blocks , understand if the object synchonized inside the block is read or written and replace monitorenter,monitorexit with a rw lock. 
Essentially for understanding if the lock is read or write you can  check is there is no assignment inside to synchronized object.
This feature can be used non only for emproving performance but also for making working Fibers in legacy code or in the tons of projects containing synchonized keyword. In fact fibers can t work using standard synchonized block because you have to use RW lock developed by quasar not blocking the thread but just fiber(the cost to switch a fiber is about 100 instruction , instead thread is many thousands of instructions)

Theoretically it is possible to check recursivelly if inside a block there is a assigment to a object  but if it is too much difficult or slow you can do a simplier method:
- direct assigment 
- reference calling method starting with set
- method having annotation @changeState
 will be considered write locks

**Comment by grimly** [comment]
Can you provide an example showing the difference between synchronized methods and your improved version with some usecase?

I think that you may even give your feedback to oracle so they can improve the jvm on your use cases or at least they can tell you why it would break.

**Comment by Maaartinus** [comment]
@publicocean0 I'm afraid, this is much too hacky. Moreover, the read-write lock has a rather big overhead, so it's inefficient for low contention. At the same time, monitor-enter-exit gets heavily optimized. You're surely right that the context switch is very costly, but you don't know upfront, if it happens often enough. You surely shouldn't replace monitors with rw-locks blindly as the gain/loss depends on usage.

A half-baked analysis of what gets done inside a block is looking for troubles. Lombok can't access other classes, so you must give up on any method call on anything but `this`. I'm afraid, this has to be done manually or by some static analysis tool.

I can imagine annotations like `@ReplaceSynchronizedByReadLock` and `@ReplaceSynchronizedByWriteLock`, but if you'd have to insert it into a legacy class, you can rewrite it instead (it's more verbose, but I'm afraid, you need to think hard about any change).

**Comment by publicocean0** [comment]
There are man kind of of Locks and mutexes. synchronized is a generic good solution but if for example you have few writes and many read in block , there are lock better fits this needs. In addition now there is the problem with fibers. The fibers cant use synchronized blocks, you have to replace all of them with special locks not locking really the thread. So the uses of this feature could be multiple. If you use a jar you can modify the code manually , but using instrumentation you can do.
