### ISSUE TITLE
ClassNotFoundException: lombok.core.AnnotationProcessor

### ISSUE THREAD

**Issue by abbas-mohamad** [rzwitserloot/lombok#1536]
Hello,

I've created a simple project with 1 class inside:
```
@Getter
public class Test {
   private String val = "some value";
}
```

I put the Lombok jar inside a my-libs directory within the project.

When I try to compile this class using `javac -cp my-libs/lombok-1.16.18.jar src/main/java/Test.java`, everything works as expected.

When I rename the 'my-libs' directory to 'my+libs' and try to compile the class again using `javac -cp my+libs/lombok-1.16.18.jar src/main/java/Main.java`, i am getting this error:

`error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider lombok.launch.AnnotationProcessorHider$AnnotationProcessor could not be instantiated: java.lang.RuntimeException: java.lang.ClassNotFoundException: lombok.core.AnnotationProcessor`

The only difference between the 2 cases, is the presence of the '+' sign in the name of the directory.

Please find an example ([lombok-test.zip](https://github.com/rzwitserloot/lombok/files/1555648/lombok-test.zip)) that shows how to reproduce the problem.

It is not common to have a '+' in the name of the directory, but I can't just understand why it is not working.

Regards,

**Comment by chickenkiller** [comment]
Hello, any news about this issue? It can be blocking in some cases....

**Comment by janrieke** [comment]
Also seems to affect the installer, see https://stackoverflow.com/questions/61013290/
