### ISSUE TITLE
Javac9 java.lang.NoSuchFieldError: pid

### ISSUE THREAD

**Issue by yugantshah** [rzwitserloot/lombok#1537]
Trying to compile java9 with groovy and getting 
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project services: Fatal error compiling: java.lang.NoSuchFieldError: pid -> [Help 1]

Had raised https://issues.apache.org/jira/browse/MCOMPILER-318 as i thought its a maven issue.

Thanks,
Yugant Shah

**Comment by rspilker** [comment]
Should be fixed in 1.16.18, or otherwise in the [edge release](https://projectlombok.org/download-edge).

**Comment by yugantshah** [comment]
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project services: Compilation failure: Compilation failure:
Using 1.16.18 and adding lombok as a module in module-info.java is giving below error.

[ERROR] lombok/dummy/ForceNewRound0.java:[1,1] file should be on source path, or on patch path for module
[ERROR] /Users/yushah/home/git/JigsawTest/com.allstate.jigsaw.services/src/main/java/com/allstate/jigsaw/services/domain/PolicyDetail.java:[2,8] package lombok is not visible
[ERROR] (package lombok is declared in the unnamed module, but module lombok does not read it)
[ERROR] -> [Help 1]

**Comment by rzwitserloot** [comment]
should be fixable by adding 'require lombok;' to your module-info. Use the current edge release.

**Comment by likaiqing** [comment]
check the version of jdk in project setting-->project
