### ISSUE TITLE
@GetSet annotation for Jpa/Hibernate Entities

### ISSUE THREAD

**Issue by kamilors** [rzwitserloot/lombok#1539]
Could you add a new annotation from get and set combinations. We dont use @data annotation with jpa/hibernate entities, becouse the hashcode generation can affect hibernate.

So, using @setter @getter annotations separately creates two lines of code pollution.

Thanks.

@Getter
@Setter
public @interface GetSet { }

**Comment by rspilker** [comment]
You can put them on one line.

**Comment by kamilors** [comment]
yes we can write in a single line is an ingenious idea but the ide's standard formats automatically convert it to double lines :)
