### ISSUE TITLE
add @Property

### ISSUE THREAD

**Issue by web-xiaxia** [rzwitserloot/lombok#1544]
With Lombok 

@Property
public class PropertyExample{
       private int age;
}

Vanilla Java

@Property
public class PropertyExample{
       private int age;
       public static class Property{
             public static String age="age";
      }
}

**Comment by grimly** [comment]
Your example is more about class metadata.

I would point out your example is doable without hacks like lombok does, only using annotation processor.

I can't find a good example but you can find a way to get your hands on all the [VariableElement](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/element/VariableElement.html)s from all annotated types.

**Comment by web-xiaxia** [comment]
My English is very bad     ,   Would you do it  for  example  ??

**Comment by grimly** [comment]
Late answer but still this is a valid example of this metadata : https://docs.jboss.org/hibernate/orm/5.0/topical/html/metamodelgen/MetamodelGenerator.html

**Comment by web-xiaxia** [comment]
thank you， My idea is  @FieldNameConstants
