### ISSUE TITLE
[FeatureRequest] @ReturnNull

### ISSUE THREAD

**Issue by rasperin** [rzwitserloot/lombok#1552]
Probably a crazy one, but if possible being able to have method parameters with @ReturnNull that checks if the method parameter is null and if so, has the method short circuit and return null.

**Comment by Maaartinus** [comment]
@rasperin This would be handy.... until you get an NPE and have no idea why. `null`s are evil, you should fight them ASAP. Anything making it easier to propagate `null` helps to counter the best practice of being fail-fast. Propagating `null`s is only good in a world with perfect null analysis.

**Comment by rasperin** [comment]
I'm not sure if I should debate that, but I'll give a quick rationalization.

if(data doesn't exist in database) (returned as null in database) {
    don't execute this method
}

instead of having to do that over and over in code an annotation would be rather handy.

That said, I can fully understand why this particular thing could be dangerous outside of the context I was considering (and even then it hides the real intent of what the code is doing, which could be further dangerous). I'll close this :).
