### ISSUE TITLE
AllArgsConstructor does not supper "callSuper"

### ISSUE THREAD

**Issue by huehnerlady** [rzwitserloot/lombok#1557]
As in "equalsAndHashCode" and in "toString" the AllArgsConstructor should support the fields of superclasses as well.

**Comment by manueljordan** [comment]
Some thoughts from `Lombok` developers? I think it is a valuable feature.

**Comment by Maaartinus** [comment]
@manueljordan For sure, it is, but it's complicated. At the time Lombok runs, the information isn't available.

See "Working around the chicken and egg problem" in https://github.com/rzwitserloot/lombok/wiki/LOMBOK-CONCEPT:-Resolution.

**Comment by manueljordan** [comment]
Thanks for the information, for the moment I have created the constructor manually.
