### ISSUE TITLE
How to use lombok to create custom exception faster.

### ISSUE THREAD

**Issue by scolia** [rzwitserloot/lombok#1559]
I need to create some custom exception which extends RuntimeException like:

    @NoArgsConstructor
    public class DuplicateException extends RuntimeException {
        private static final long serialVersionUID = 2610477518423283258L;

        public DuplicateException(String message) {
            super(message);
        }

        public DuplicateException(String message, Throwable cause) {
            super(message, cause);
        }

        public DuplicateException(Throwable cause) {
            super(cause);
        }
    }

They are basically the same, but some is subclass of this.

How to create them faster using lombok?

**Comment by grimly** [comment]
Use a template. For instance on netbeans you have templates for classes, interfaces and so on, you can copy one and give it the shape of your choice.
I have the same needs as you do and creating exceptions from three clicks and typing the name cannot be beaten by any annotation.

**Comment by quiram** [comment]
I would love for this to be a feature of Lombok. In the same way that we have annotations to create constructors based on properties, it would be nice to have an annotation that creates the usual constructors for Exceptions.

**Comment by itgold** [comment]
@Exception annotation would be so helpful

**Comment by janrieke** [comment]
See also #375 and https://groups.google.com/forum/#!topic/project-lombok/x1DdJvG-PKc

**Comment by verglor** [comment]
Hi @rzwitserloot, I can see that @StandardException is merged. Could you release a new version, please ?
