### ISSUE TITLE
Add but() method to builder

### ISSUE THREAD

**Issue by galgalats** [rzwitserloot/lombok#1561]
Sometimes you want to build many instances, but only one (or some) of the attributes are different.
In order to do so, as it is now, you should build a new Builder for each attribues combination.
I suggest to add a but() method that creates a new builder instance with the same attribues values.
In general it is the clone method, but it has the meaning that I want the same builder as it is now "but" set some attributes as i need.

For example, we have class A:

```
@Builder
public @Data class A {
     private final String a1;
     private final String a2;
}
```

The implementation in the builder should be like that:
```
...
public ABuilder but() {
    return A.builder().a1(a1).a2(a2);
}
....
```

I would like to do the following:
```
ABuilder builder = A.builder().a1(A_STRING);
ABuilder builderWithSomething = builder.but().a2(SOMETHING)
ABuilder builderWithSomethingElse = builder.but().a2(SOMETHING_ELSE)
```

By that I can create an hierarchical of builders, while each one of them sets the attributes they need without change it to the other builders.

**Comment by Maaartinus** [comment]
This can be already done using `Builder(toBuilder=true)` and
```
ABuilder builder = A.builder().a1(A_STRING);
ABuilder builderWithSomething = builder.build().toBuilder().a2(SOMETHING)
ABuilder builderWithSomethingElse = builder.build().toBuilder().a2(SOMETHING_ELSE);
```
which is pretty wasteful, but usually can be written in a better way.

You may want to use a `@Wither` instead.

That said, maybe there should be an option to make the builder `Cloneable`. IMHO, `clone` is a much better name than `but` and despite the `Cloneable interface being stupid, `clone` is the right thing here (there's no reason to name the method `copy` or alike). It should handle the collections and maps understood by `@Singular` and ignore problems with mutable crap like `j.u.Date`.

[Allowing `@Wither` on the builder would solve it, too.](#731 ).

**Comment by galgalats** [comment]
Thanks for the answer.

How can I add `@Wither` to the `@Builder`?

**Comment by Maaartinus** [comment]
> How can I add `@Wither` to the `@Builder`?

You can't. It would look like
```
@Builder
class Thing {
   @Wither // <--- forbidden
   class ThingBuilder {}
}
```
but most annotations are forbidden on the builder. #731

**Comment by galgalats** [comment]
Can you allow this functionality or something similar to that, like:

```
@Builder.Wither
class Thing {

}
```

**Comment by rspilker** [comment]
I still do not understand the use-case. I do have two way to 'implement' similar behavior:
- Reuse an existing Builder instance
- Use `toBuilder`

```java

@Builder(toBuilder=true)
class Foo {
  int x;
  int y;
}

FooBuilder b = Foo.builder().x(0).y(0);
Foo origin = b.build();
Foo unit = n.x(1).build();

Foo imagine = origin.toBuilder().y(1).build();
```

Did I miss a substantial use-case?

**Comment by picimako** [comment]
Sorry if I miss any point from the discussion.
From my experience the `toBuilder()` method called `but()` is useful and more fluent when the builder methods are prefixed with `with`, `for`, `using`, etc. (for which I also couldn't find a way to configure @Builder with, but that's another topic).

**Comment by Maaartinus** [comment]
@picimako The names have a system:

- The `@Wither` uses the "with" prefix and creates a new object rather than setting anything. It rarely makes sense with mutable objects.
- The builder uses "fluent" "chained" setters, i.e., setters returning `this` and having no "set" prefix. The former is rather necessary and the latter is quite convenient. Using the "with" prefix for setters would be very confusing.

There's no configuration for this and I guess, this won't change. All you can configure are the classical `@Getter` and `@Setter` using `@Accessors` or `lombok.config`.


Concerning `but`, `for`, `using`, etc., I guess, they'd make it all even more confusing. The "with" prefix has its place as there must be something allowing to tell it from a setter, `builder` and `toBuilder` do just what they say, but the others feel very redundant to me.

**Comment by picimako** [comment]
@Maaartinus Thank you for the explanation.

I agree with you about `for` and `using` being confusing. That should change on our side.

And I can definitely live with having non-prefixed builder methods, I was just hoping for that I could migrate some frequently used builder classes (with methods mainly prefixed with `with`) to Lombok Builder without having to update the many references of those methods.

**Comment by rzwitserloot** [comment]
I don't know what 'but' is trying to accomplish, here. I think you misunderstand how builder works. Relevant notes:

* You can generate a builder off of an instance using `@Builder(toBuilder = true)`.
* You can just continue to use a builder; they do NOT become invalid after using them to build. The builder continues to remember all properties you set. It is even smart enough to know what to do with `@Singular`, and there's a clearX() method to reset some singular field for a builder.

If I'm missing something, please reopen and be really specific and serve it up on a silver platter for me:

Write some java that has lombok and this mythical 'but' thing, then show what it would look like delomboked, and make sure to write the example such that it is inherently obvious as to what its for. Right now I don't get it.
