### ISSUE TITLE
local variable PRIME in hashCode not used

### ISSUE THREAD

**Issue by sahlex** [rzwitserloot/lombok#1567]
Hi there. 

While de-compiling a class orchestrated by lombok (1.16.20) I found that in generated `hashCode` method the local type PRIME is not used. Generated code seems to be like this:

    public int hashCode()
    {
        int PRIME = 59;
        int result = 1;
        Object $id = getId();
        result = result * 59 + ($id != null ? $id.hashCode() : 43);
        return result;
    }

Is it just due to the de-compilation or is it in deed  generated this way?

**Comment by rspilker** [comment]
Yes, that's the decompilation. the variable is inlined.
