### ISSUE TITLE
Using lombok in Spring Boot 1.5.10 leads to a ClassNotFoundException

### ISSUE THREAD

**Issue by choda** [rzwitserloot/lombok#1576]
Using Lombok in a Spring Boot 1.5.10 project build and run using NetBeans 8.2 leads to a ClassNotFoundExpcetion. 

To reproduce the error, check out this [sample project](https://github.com/choda/netbeans-issues). It's a stripped down version of a much larger project that I recently upgraded to Spring Boot 1.5.10.
When built manually with Maven (`mvn clean package`), the project runs fine, both in console (`mvn spring-boot:run`) or in NetBeans (8.2 and latest nightbuild 201802080002). 
When built in NetBeans, the project fails at startup with a ClassNotFoundException, though the class not found is indeed generated (by QueryDSL). See the [attached log](https://github.com/rzwitserloot/lombok/files/1711571/spring-boot.log).
The same maven-3.5.2 binary is used in both cases.

If I downgrade Spring Boot to 1.5.9, which depends on Lombok 1.16.18, or keep Spring Boot 1.5.10 but downgrade the Lombok dependendy to 1.16.18, everything works fine.
The project also runs fine when build with Spring Tool Suite.

It seems to be a NetBeans specific issue, but I want to run things here first. Any feedback would be appreciated.

**Comment by choda** [comment]
For the record, I just tested lombok-edge, to no avail.

**Comment by AlexFalappa** [comment]
Maybe related to #1577 that in turn may be related to #1592 that I just reported.

**Comment by choda** [comment]
As suggested in the threads mentioned by @AlexFalappa and in this [Spring Boot thread](https://github.com/spring-projects/spring-boot/issues/11924), this is a NetBeans specific issue, for which a workaround is to disable the "Compile on Save" option.
