### ISSUE TITLE
Netbeans 8.x compile on save not working with lombok 1.16.20

### ISSUE THREAD

**Issue by Massinissab** [rzwitserloot/lombok#1577]
During debugging of my application I'm used to use hot code replace.
This feature of netbeans allows to replace code on a running jvm.
To make it work you have to enable "compile on save".
So, with lombok 1.16.18 all is working good but with the new version 1.16.20, the hot code replace feature doesn't work.
I can see that my compiled class are removed from the target folder when hitting the save button (I'm working with maven).

**Comment by AlexFalappa** [comment]
May be related to #1592 that I just reported. Do you get the same tooltip?

**Comment by Massinissab** [comment]
No I didn't get the same tooltip.
As I mentionned above, the only trouble I got is that, when I hit save button, the class current class is removed from the target directory. Even if there's no lombok annotation on the class.
I face this issue since I use lombok 1.16.20. Before this upgrade all was OK.
The bugged feature is "compile on save". The last lombok release make it fail.

**Comment by AlexFalappa** [comment]
@Massinissab I can confirm this issue, in NetBeans 8.2 the IDE is aware of Lombok generated methods but compile on save deletes the class.

**Comment by balta3** [comment]
I stepped through the commits and https://github.com/rzwitserloot/lombok/commit/4710d20e180c35674b2d934aafb0a8171ff1608e seems to be the breaking commit

**Comment by victorwss** [comment]
@AlexFalappa, @Massinissab, @balta3 Which JDK are you using to run Netbeans? From which JDK is the compiler invoked? Maybe an `if` before the `replaceFileManagerJdk9` to not invoke it when running on JDK <= 8 could solve this?

**Comment by Massinissab** [comment]
@victorwss I'm running netbeans with jdk8. The compiler is invoked from the same jdk.

**Comment by balta3** [comment]
@victorwss I'm running JDK 9

**Comment by Massinissab** [comment]
@victorwss I'm using jdk8 to run netbeans. Same to compile.

**Comment by nayomnik** [comment]
same with GWT. doent compile even if 'compile on save' is checked.

**Comment by michael-rhoese** [comment]
Same with Netbeans8.2, Oracle JDK8 and Lombok 1.18.0.

**Comment by charphi** [comment]
Same with NetBeans 8.2, Oracle JDK8 1.8.0_171 and lombok 1.18.0.

**Comment by charphi** [comment]
I confirm that the problem comes from `LombokProcessor#replaceFileManagerJdk9`.

Unfortunately, checking for java compiler version is not enough to prevent the bug. 
For example, my current config (NetBeans 8.2 + JDK8 + JDK10) returns `9` when calling `Javac#getJavaCompilerVersion()` during compile-on-save even if JDK8 is the only JDK configured in the ide.

So I have added a second test to check if the compilation is done during compile-on-save: `JavacHandlerUtil#inNetbeansCompileOnSave(Context)`.

It seems to work properly with NetBeans 8.2 (I haven't tested it on NetBeans 9).
