### ISSUE TITLE
Jackson can't readValue() of abstract type with lombok v 1.16.20

### ISSUE THREAD

**Issue by Serg-Maximchuk** [rzwitserloot/lombok#1581]
I have some abstract classes and implementations in my project, it was fine to transform json to java object with lombok 1.16.18, but something vent wrong after update to 1.16.20.
Here is my abstract classes:
```
@NoArgsConstructor
public abstract class Loop implements Documentable {

    protected Loop(Loop from) {
        setEntries(from.getEntries());
    }

    public abstract List<LoopEntry> getEntries(); // LoopEntry is an abstract class

    public abstract void setEntries(List<LoopEntry> entries); // LoopEntry is an abstract class

}
```
And another:
```
@NoArgsConstructor
public abstract class LoopEntry {
    // abstract stuff, nothing special
}
```
Their concrete realizations:
```
@Data
@AllArgsConstructor
@NoArgsConstructor
public class LoopEntryDTO extends LoopEntry implements Serializable {
    // some stuff, nothing special
}
```
```
@Data
@AllArgsConstructor
@NoArgsConstructor
public class LoopDTO extends Loop implements Serializable {

    private List<LoopEntryDTO> entries; // concrete class

    // constructor

    @Override
    public List<LoopEntry> getEntries() { // abstract
        return (entries == null) ? null : new ArrayList<>(entries); // but concrete
    }

    @Override
    public void setEntries(List<LoopEntry> entries) { // abstract
        this.entries = (entries == null) ? null
                : entries.stream().map(LoopEntryDTO::new).collect(Collectors.toList()); // concrete
    }
}
```
So earlier when running tests for my controller, lombok 1.16.18 handled all this abstract stuff, and after update to 1.16.20 I've got this error:

> 2018-02-16 00:05:07,058 WARN  org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver - Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Can not construct instance of com.imcode.imcms.model.LoopEntry: abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.imcode.imcms.model.LoopEntry: abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: java.io.PushbackInputStream@57f9f387; line: 1, column: 36] (through reference chain: com.imcode.imcms.domain.dto.LoopDTO["entries"]->java.util.ArrayList[0])

Am I doing something wrong? Or it's something with latest lombok version? I see that there is nothing about lombok in exception, but switching back to 1.16.18 helps and everything is ok, I've checked few times that exactly latest lombok version is the cause. Also I've checked simple `objectMapper.readValue()` with json of my object and it fails with 1.16.20 but is ok with 1.1618. I don't want to have frozen lombok version in my project.
Thank you!
P.S. Lombok is used in my classes for other fields getter/setter/toString/EAHC but here I need concrete way of setting/getting with abstract type for getter/setter

**Comment by Serg-Maximchuk** [comment]
I've looked what is the difference between decompiled code for both versions and found only one - lombok's @AllArgsConstructor no more adds @ConstructorProperties on generated constructor.

**Comment by Maaartinus** [comment]
@Serg-Maximchuk I guess, that's it. AFAIK it's off by default now. Use `lombok.config` to change it.

**Comment by Serg-Maximchuk** [comment]
Oh, now I understand. Thank you!
