### ISSUE TITLE
Add flag @Singuar to disallow null singular items

### ISSUE THREAD

**Issue by Robrowski** [rzwitserloot/lombok#1586]
It would be nice if `@Singular` could be configured to disallow null items. The use case is the same as any use case for `@NonNull`, but for items in a collection.
```java
@Value
@Builder(toBuilder = true)
public class ValueObject {

    @Singular(allowNullValues = true )
    private List<String> values;
}
```
I would then expect this to throw a NullPointerException similar to what `@NonNull` would for a non-collection field:
```java
ValueObject.builder()
    .value(null)
    .build();
```

**Comment by bschlenk** [comment]
This is related to https://github.com/rzwitserloot/lombok/issues/1074

**Comment by Robrowski** [comment]
Ah yes it is.
