### ISSUE TITLE
Expanding the problem mentioned in #1278 (with generating getters & setters for fields that contains one lowercase letter in front followed by capital letter)

### ISSUE THREAD

**Issue by amseager** [rzwitserloot/lombok#1593]
Connected issue that was closed too early: #1278

This problem occurs not only with 'x' in front of fields and there is nothing wrong with lombok intellij plugin.

Every field starting with one lowercase letter causes jackson serializing problems. F.e. fields 'aTest', 'bTest', 'cTest' etc. will all cause this bug.

It happens because for that type of fields Lombok is generating getters & setters with wrong names.
model.getXMyField() - should be model.getxMyField(). Same with setter.
Looks weird, but Jackson can only understand that type of names while converting json into object and vise versa.
If you try to generate G&S in IDEA and Eclipse the result will be correct (in this case, model.getxMyField()).

**Comment by rzwitserloot** [comment]
Duplicate of #2693
