### ISSUE TITLE
Separate artifacts for apt and implementation for Gradle 4.6 annotationProcessor configuration

### ISSUE THREAD

**Issue by soberich** [rzwitserloot/lombok#1594]
Hi,
Gradle introduced the [annotationProcessor](https://docs.gradle.org/4.6/release-notes.html#convenient-declaration-of-annotation-processor-dependencies) config.
Is't it worth to separate those now?
Feature request

**Comment by thetric** [comment]
With regard of Gradle 5 this is a good idea. Perhaps this issue should be closed in favor of #1611
