### ISSUE TITLE
Cert issues on projectlombok.org

### ISSUE THREAD

**Issue by bcoughlan** [rzwitserloot/lombok#1596]
Hi,

Currently https://projectlombok.org/ is not viewable due to cert issues:

![image](https://user-images.githubusercontent.com/421683/36840783-2afc287a-1d3e-11e8-9bfc-b85232ec95f2.png)

**Comment by Maaartinus** [comment]
@bcoughlan For me, it works with both Chromium (Version 64.0.3282.167 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)) and Firefox (58.0.2 (64-bit)). And with lynx (2.8.9dev.8 (21 Dec 2015)), too. Click on learn more to learn more?

**Comment by bcoughlan** [comment]
Seemed to have been exclusive to Firefox Nightly. Probably was a bug in the Firefox trunk.

**Comment by krzyk** [comment]
@bcoughlan @Maaartinus This is not an issue with Firefox Nightly (since 60), same happens with Chrome Cannary (since 66) - this is probably ongoing removal of Symantec issued certificates:
1. https://blog.nightly.mozilla.org/2018/03/05/these-weeks-in-firefox-issue-33/
2. https://security.googleblog.com/2017/09/chromes-plan-to-distrust-symantec.html

It looks like you need to get new certificates.

**Comment by Maaartinus** [comment]
@krzyk You're right. My Chrome writes a warning in the console:

_The SSL certificate used to load resources from https://projectlombok.org will be distrusted in M66. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information._

@rzwitserloot @rspilker The certificate expires on 2018-05-02, Chrome 66 won't accept it (as it was issued before June 1, 2016). Chrome 66 beta is planned for on 2018-03-05, Chrome 66 stable is planned for 2018-04-17.

**Comment by fengin** [comment]
see https://dotblogs.com.tw/grayyin/2018/08/14/120458
1、compile the class InstallCert.java :  "javac InstallCert.java"
2、run the class :  "java  InstallCert projectlombok.org"
3、input "1"  enter
4、 copy the cert which output form steps before  to  "JAVA_HOME/jre/lib/security"
5、enjoy it !
