### ISSUE TITLE
Website feature pages should have the feature name in the page title

### ISSUE THREAD

**Issue by thrnio** [rzwitserloot/lombok#1608]
It would be really convenient if the feature pages on the website had the feature name in the title. For example, if the page https://projectlombok.org/features/Builder had a title something like "@Builder - Project Lombok" instead of just "Project Lombok". I sometimes find myself with multiple feature pages open in tabs and no clue which one is which without opening them, and it also makes it hard to load the page from the browser history.

**Comment by rspilker** [comment]
We do change the title on navigation.

**Comment by rspilker** [comment]
Now also added the titles on initial rendering
