### ISSUE TITLE
@Data annotated POJO starting two Capital letter misbehavior when serializing it with Jackson 

### ISSUE THREAD

**Issue by ahmed-abdelmoneim** [rzwitserloot/lombok#1609]
I'm annotating POJO called EBilling with `@Data` which is a part of another class BillingAccount(exposed through REST API) , What I'm founding is repeated occurrence of the EBilling object within the JSON, when I've changed the name to anything but not starting with two capital letters then problem solved, also when I'm using my own setters and getters instead of `@Data`, this issue occurs with lombok lombok:1.16.18 and Jackson 2.8.9

**Comment by rspilker** [comment]
Sorry I cannot help you, you need a Jackson specialist to help you with this.

**Comment by Maaartinus** [comment]
@ahmed-abdelmoneim > starting with two capital letters

What's the name of the field? Something like `eBilling`? Then note that they're two incompatible interpretation of Javabeans rules (something like `geteBilling` and `getEBilling`) and Lombok and Jackson disagree on them.

**Comment by rspilker** [comment]
See #1661

**Comment by rzwitserloot** [comment]
Duplicate of #2693
