### ISSUE TITLE
@Reflector - new annotataion - proposal - to "reflect" class/interface/field/method run-time properties at compile-time.

### ISSUE THREAD

**Issue by wheredevel** [rzwitserloot/lombok#1610]
From time to time I need to access a data about package/class/interface/field/method reflected information.  
For example:
- Package simple name
- Package fully qualified name
- Class simple name
- Class fully qualified name
- Class implemented interfaces
- Class fields
- Class methods
- Class modifiers
- Field signanture (incl. names, types)
- Field modifiers
- Method signanture (incl. names, types, position)
- Method modifiers
- etc. etc. etc.

This information is easily available at _run-time_.  
But I must have it at *compile-time*.  

Here's where Lombok can come to help.  

In Vanilla Java:  
```Java

package org.example;

import org.apache.commons.lang3.BooleanUtils;

public class system {

	public static String _fqn = "org.example.system";

	public static class feature {

		public static String _fqn = system._fqn + ".feature";

		public static class processor {

			public static String _fqn = feature._fqn + ".processor";

			public static class gpu {

				public static String _fqn = processor._fqn + ".gpu";

				public static final boolean enabled = BooleanUtils.toBoolean(system.feature(_fqn + ".enabled"));

				public static final int threads = NumberUtils.toInt(system.feature(_fqn + ".threads", 1));

				public final String id = "id";

				public final String uid = system.feature(_fqn + ".id");
			}
		}
	}
}
```

With Lombok:  
```Java

package org.example;

import org.apache.commons.lang3.BooleanUtils;

public class system {

	public static class feature {

		public static class processor {

			@Reflector
			public static class gpu {

				@Reflector
				public static final boolean enabled = BooleanUtils.toBoolean(system.feature($reflector.fqn + "." + enabled$reflector.name));

				@Reflector
				public static final int threads = NumberUtils.toInt(system.feature(threads$reflector.fqn, 1));

				@Reflector
				public final String id = id$reflector.name;

				public final String uid = system.feature(id$reflector.fqn);
			}
		}
	}
}

```

Assuming, `system.properties` file:
```Properties
org.example.system.feature.processor.gpu.enabled = true
org.example.system.feature.processor.gpu.threads = 16
```

**Comment by FilipMalczak** [comment]
What stops you from doing:

```
package org.example;

import org.apache.commons.lang3.BooleanUtils;

public class system {

	public static class feature {

		public static class processor {

			@Reflector
			public static class gpu {

				public static final boolean enabled = BooleanUtils.toBoolean(system.feature(gpu.class.getCanonicalName() + ".enabled"));

				public static final int threads = NumberUtils.toInt(system.feature(gpu.class.getCanonicalName() + ".threads", 1));
			}
		}
	}
}
```

See [here](https://stackoverflow.com/a/15203417/1219585) for exact difference between name, canonical name and simple name.

**Comment by wheredevel** [comment]
Yeah, the example is not complete yet.  
Your point is correct: there's some stuff available via Class.  
I proposed the @Reflector as a complement to those abilities.  

...the rationale is not obvious.
I'm still looking for better examples.

**Comment by wheredevel** [comment]
One thing is clear, though: `reflector()` is resolved without mentioning the actual class name (`gpu` in this case).

**Comment by Maaartinus** [comment]
@wheredevel Why do you need it at compile-time? Do you really want to access properties at compile-time? Wouldn't an annotation processor generating a new file do?

**Comment by wheredevel** [comment]
I added a few more examples.  
Going to think of more...

**Comment by victorwss** [comment]
I really don't understand what you are trying to do and it seems to be a case too specific and localized to be worth to be added in lombok.

**Comment by wheredevel** [comment]
I agree. It's not well formulated.
