### ISSUE TITLE
Compatibility with STS4

### ISSUE THREAD

**Issue by geoemm** [rzwitserloot/lombok#1613]
Hello, Lombok is unable to recognize STS4 as an IDE. Is it possible to install it manually?

![lombok](https://user-images.githubusercontent.com/62142/37511536-d37d2e66-2907-11e8-91b5-e2c267539bc9.png)

**Comment by rspilker** [comment]
Can you tell me the name of the executable and of the ini file?

**Comment by rspilker** [comment]
I think they renamed STS.exe and STS.ini to SpringToolsSuit4.exe and SpringToolsSuit4.ini.

**Comment by rspilker** [comment]
You can always install it manually by copying the jar file and modifying the ini file. 

In the installer, just click on the link `Show me what this installer will do to my IDE installation.` and execute the actions yourself.

**Comment by geoemm** [comment]
Hi, the name is **SpringToolSuite4**. I found "STSLocationProvider" class which I guess is for Spring Tool Suite. Is it OK to change and create a PR for this?

**Comment by rspilker** [comment]
Working on it already

**Comment by geoemm** [comment]
Ok, great! I already installed it manually by the way.

**Comment by rspilker** [comment]
Can you also test we fixed it using the [edge release](https://projectlombok.org/download-edge)?

**Comment by geoemm** [comment]
I was able to install the edge release on STS4 without issues!

![a](https://user-images.githubusercontent.com/62142/38353157-45c8b4c0-38be-11e8-84f6-520b5a28e71c.png)
