### ISSUE TITLE
Can't get installer to work with STS 4 Beta

### ISSUE THREAD

**Issue by AixNPanes** [rzwitserloot/lombok#1618]
I can't select the SpringToolSuite4.ini file in the installer IDE.

Tims-MacBook-Pro:Eclipse tim.daley$ ls -al /Applications/SpringToolSuite4.app/Contents/Eclipse/SpringToolSuite4.ini
-rw-r--r--@ 1 tim.daley  admin  535 Mar 19 18:53 /Applications/SpringToolSuite4.app/Contents/Eclipse/SpringToolSuite4.ini
Tims-MacBook-Pro:Eclipse tim.daley$ java -jar  ~/.m2/repository/org/projectlombok/lombok/1.16.20/lombok-1.16.20.jar install /Applications/SpringToolSuite4.app/Contents/Eclipse/SpringToolSuite4.ini
WARNING: Can't find any IDE at: /Applications/SpringToolSuite4.app/Contents/Eclipse/SpringToolSuite4.ini
WARNING: Zero valid locations found; so nothing was done!
Tims-MacBook-Pro:Eclipse tim.daley$ mv SpringToolSuite4.ini eclipse.ini
Tims-MacBook-Pro:Eclipse tim.daley$ java -jar  ~/.m2/repository/org/projectlombok/lombok/1.16.20/lombok-1.16.20.jar install /Applications/SpringToolSuite4.app/Contents/Eclipse/eclipse.ini
Lombok installed to: /Applications/SpringToolSuite4.app/Contents/Eclipse
Tims-MacBook-Pro:Eclipse tim.daley$ mv eclipse.ini SpringToolSuite4.ini
Tims-MacBook-Pro:Eclipse tim.daley$

**Comment by AixNPanes** [comment]
After renaming the .ini file back, STS4 About shows lombok is installed. However, I'm getting MANY errors related to lombok that I didn't get in STS 3.9. Resulting project runs without compile errors with maven test and when I start with Boot dashboard.

**Comment by AixNPanes** [comment]
Hmmm. After making any single edit (add and delete a blank for example) and saving the module, errors disappeared in that module.

**Comment by victorwss** [comment]
Related to #1613 (possibly a dup).

**Comment by AixNPanes** [comment]
Likely. I didn't find that one before.

**Comment by rspilker** [comment]
This should be fixed in the [edge release](https://projectlombok.org/download-edge). Can you verify that it now works?
