### ISSUE TITLE
lombok 1.16.20 installer.  Unable to set eclipse location

### ISSUE THREAD

**Issue by johaw** [rzwitserloot/lombok#1638]
lombok 1.16.20 installer, unable to select eclipse locations.  Resolution is 3000 x 2000 (Microsoft Surface book 2). 

I'm unable to select the eclipse installation dir.  Please see attached screenshots.

![cant_find_ide](https://user-images.githubusercontent.com/9937036/38159153-d67f7bf6-345f-11e8-82ae-213e78c2fe88.jpg)
![installer](https://user-images.githubusercontent.com/9937036/38159154-d8befefa-345f-11e8-8d20-c7e0706f6a80.jpg)

**Comment by rspilker** [comment]
Ok, we have so many problems with this, and no solutions yet because we cannot reproduce this on any of our machines.

To solve your installation problem, you can use the command line:
```cmd
java -jar lombok.jar install <path-to-eclipse>
```

**Comment by johaw** [comment]
@rspilker Thanks for the response. I'm not sure of the cause,  but this seems to be java version related.  If I use java 9, the UI is displayed properly.   However, if I just java 8, I get the behavior that I initially described.  

Apologies for not seeing this earlier, but I just forked the repo and had to install java 9 to get the build to work and then when I tried the jar I built it worked, but if I switch back to java 8 with the same jar I get the bad layout.

**Comment by johaw** [comment]
For comparison, I ran 'java -jar lombok.jar' with both java 8 and java 9.  The upper windows is java 8 and the lower window is java 9. 

![image](https://user-images.githubusercontent.com/9937036/38397066-c91bc828-38f8-11e8-9eff-d0d8378be3c9.png)

**Comment by johaw** [comment]
Just found this change in java 9.  [JEP 263: HiDPI Graphics on Windows and Linux](http://openjdk.java.net/jeps/263)

This might explain why the installer is sized properly in java 9 and not java 8.

**Comment by rspilker** [comment]
Can someone who encounters this problem try `java -Dsun.java2d.uiScale=2.5 -jar lombok.jar`?

**Comment by johaw** [comment]
Just tried `java -Dsun.java2d.uiScale=2.5 -jar lombok.jar`. No change in behavior.

![image](https://user-images.githubusercontent.com/9937036/38528946-3f06e45e-3c1f-11e8-9f43-1a11430c779c.png)

However, I found this [link](https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) which has an answer about changing the Compatability settings of the java.exe and this did work. 

![image](https://user-images.githubusercontent.com/9937036/38529143-5b34a1e2-3c20-11e8-87ff-394b817e4794.png)

The more I've read, this just might not be fixable with java 8 and current swing based installer.

**Comment by rspilker** [comment]
Thanks for the research!

**Comment by wudc** [comment]
Hi just ran this:
$ java -jar lombok-1.18.6.jar

Got this.
Segmentation fault

**Comment by rspilker** [comment]
Wow, cool. That sounds like a JRE bug to me. What JRE did you use?

**Comment by wudc** [comment]
Actually, I was running the command in the git bash shell and probably did set it up correctly. I ran the same command using PowerShell (windows 10). I didn't get the Segmentation fault error. But instead, the UI shows up, then disappears quickly. I tried both 1.18.6 and 1.18 version of the jar files. Any suggestion?

My java version is:
java version "1.8.0_121"

**Comment by wudc** [comment]
Well, I solved the problem. I have to install the latest JDK. Now STS is working with Lombok. Thanks.
