### ISSUE TITLE
EqualsAndHashCode - Equals Fails When Only Using Super Class's fields

### ISSUE THREAD

**Issue by taylorKonigsmark** [rzwitserloot/lombok#1642]
# Description
EqualsAndHashCode does not implement equals correctly when calling super, and super's EqualsAndHashCode implementation is using the "of" parameter.

# Example
```java
@EqualsAndHashCode(of = {"id"})
@Getter
@AllArgsConstructor
public class Foo {
    private String id;
}

@EqualsAndHashCode(callSuper = true)
@Getter
@AllArgsConstructor
public class Bar extends Foo {
    private String otherParam;
}

public class MainApp {
    public static void main(String[] args) {
        Bar bar1 = new Bar("id", "otherParam1");
        Bar bar2 = new Bar("id", "otherParam2");
        bar1.equals(bar2); //should equal true, but returns false
    }
}
```

I would expect that bar1 should equal bar2 since they have the same id, and should be using the Foo's implementation of equals.

**Comment by taylorKonigsmark** [comment]
I can work on getting this fixed, just want confirmation if the code maintainers agree it's a bug

**Comment by rspilker** [comment]
I thought we fixed this already. Let me check.

**Comment by rspilker** [comment]
I think the code is incomplete (Bar constructor calling super is missing), so not 100% certain if my assumptions are correct.

I think that the problem is that you also need to override `canEqual` to make it work.

**Comment by Maaartinus** [comment]
> I think that the problem is that you also need to override `canEqual` to make it work.

@rspilker No, this should work out of the box as overriding `canEqual` is necessary for equaling different classes (like `Point` and `ColoredPoint` or `CarthesianPoint` and `PolarPoint`). And it actually does, the OP makes a false assuption.

@taylorKonigsmark You're assuming that `callSuper=true` just calls super and ignores all fields. That's not true, but you can get this behavior by adding `of={}`. IMHO everything works as designed, maybe the documentation could be improved, but it already says:

> Call on the superclass's implementations of `equals` and `hashCode` before calculating for the fields in this class.

**Comment by taylorKonigsmark** [comment]
Right, this is what I did to resolve my issue while this bug was discussed. However, I get compiler warnings that the id does not exist for Bar because id is in Foo. Could there be an issue there of a false positive?

**Comment by taylorKonigsmark** [comment]
I'm going to close this out. If anything, this should be another ticket to enhance documentation or the feature itself. I would not qualify this as a bug after the discussion

Thanks!
