### ISSUE TITLE
Chain Setter

### ISSUE THREAD

**Issue by BerryWang1996** [rzwitserloot/lombok#1648]
### Short description
I want the chain call setter like 
`new User().setUsername().setPassword();`

### Expected behavior
maby u should add a annonation like `@ChainSetter` .
and this annonation can replace
```
public User setUsername(String username) {
    this.username = username;
    return this;
}
public User setPassword(String password) {
    this.password= password;
    return this;
}
```

### Version information

 * **IDEA Version:**                                    2018.1
 * **JDK Version:**                                      1.8
 * **OS Type & Version:**                           Windows
 * **Lombok Plugin Version:**                    0.17-2018.1
 * **Lombok Dependency Version:**          1.16.20

**Comment by randakar** [comment]
This feature already exists:
https://projectlombok.org/features/configuration


Op zo 8 apr. 2018 08:59 schreef wangbor <notifications@github.com>:

**Comment by BerryWang1996** [comment]
ok. thanks..

**Comment by BerryWang1996** [comment]
hello,
i have a new question:
when i use 
```
@Setter
@Getter
@Accessors(chain = true)
public String username;
```
the chain setter is ok!
but how to use common(no chain) setter ? i expect the lombok can relplace these code:
```
public User setPassword(String password) {
    this.password= password;
    return this;
}
public void setPassword(String password) {
    this.password= password;
}
```
these two setter need exist together.

**Comment by BerryWang1996** [comment]
if use chain setter , 
```
        BeanInfo beanInfo = Introspector.getBeanInfo(Foo.class);
        PropertyDescriptor[] propertyDescriptors = beanInfo.getPropertyDescriptors();
        for (PropertyDescriptor propertyDescriptor : propertyDescriptors) {
            Method writeMethod = propertyDescriptor.getWriteMethod(); // writeMethod is null
        }
```

**Comment by gajarajkalburgi** [comment]
@BerryWang1996 , Java does not allow method overloading by return type. So you can't have such 2 methods in same class.
