### ISSUE TITLE
getMxxx

### ISSUE THREAD

**Issue by Puppy-Love** [rzwitserloot/lombok#1649]
实体类参数是mXXX，生成的get方法是getMxxx,能智能取消掉M吗？

**Comment by rspilker** [comment]
1. [`@Accessors(prefix="m")`](https://projectlombok.org/features/experimental/Accessors)

2. `lombok.config`:
```cmd
lombok.accessors.prefix += m
```

**Comment by Puppy-Love** [comment]
@rspilker 唔该~thank you
