### ISSUE TITLE
Installation within nixos Eclipse

### ISSUE THREAD

**Issue by PierreR** [rzwitserloot/lombok#1650]
I would like to install `lombok` in the eclipse installation of [nixos](https://nixos.org).

`nixos` won't let anyone writing in its system store (/nix/store), so running the executable will fail. 

What does the installation script doing ? Could you point me the right place ?

Thanks

**Comment by PierreR** [comment]
As a note, I can easily get a reference to where the `lombok` jar is in the nix store.

But ideally I would prefer to install it in user space only. Is there a way to make this happen using the `eclipse` command line ?

**Comment by PierreR** [comment]
Ok I have found this:
![lombok](https://user-images.githubusercontent.com/93115/38504621-71ddf3f4-3c15-11e8-9975-fffe82a9348b.PNG)

**Comment by PierreR** [comment]
Will it work if I just use the eclipse dropins folder ?

**Comment by rspilker** [comment]
Probably.

**Comment by rspilker** [comment]
Can you confirm it works?

**Comment by PierreR** [comment]
So far all my attempts have failed. I will keep trying to understand why today. 
Cheers

**Comment by Maaartinus** [comment]
@PierreR Did you try an absolute path to lombok.jar?

**Comment by PierreR** [comment]
I have been trying to install it as a regular plugin (dropins folder) but it does not work. It looks like Eclipse is expecting a formal structure (`features`/`plugins` folder).
I suspect `lombok` might not really be a plugin as `testng`, `egit` m2e`, `jdt` or `yedit`, is it ?

My next try has been to just change the ini configuration as you can see from the attached picture. But that does not do anything.

![eclipse](https://user-images.githubusercontent.com/93115/38546262-7945ad8e-3cac-11e8-8942-a54ff5a13068.png)

**Comment by rzwitserloot** [comment]
Lombok isn't a normal plugin, it's an agent. I am not sure why '-javaagent:' is being ignored there; trying to fire up a java agent that does not exist is a fail condition causing the VM to early exit (unlike specifying non-existing jars on the classpath). However, something is off about that entire file; how can the thing that parses this file tell the difference between the block representing the vmargs, and the equinox.init.uuid thing, which is not a vmarg but the next 'property' in the file? Possibly 'well, there is no equals in any of these lines until then' but that sounds like a ridiculously bad policy. Possibly some ending backslashes or such are needed here, or, perhaps `\n`, ir, _gasp_ the exact actual line ending used matters or some such (0x0D0A vs. 0x0D vs 0x0A).

I'm unfortunately not aware of the exact mechanics of the ini file here.

NB: Normal eclipse ini files are very different. They have on one line the property, and then on the next, the value, and the `-vmargs` property is special in that this marks the rest of the file as consisting of the value. That's how the 'multiline' nature of vmargs is supported on.

**Comment by PierreR** [comment]
@rzwitserloot I believe you might have pinpointed the problem. I will try further tweaks based on your comment. Thanks for your help !
