### ISSUE TITLE
Feature request:  @Builder to use setters rather than @AllArgsConstructor

### ISSUE THREAD

**Issue by OndraZizka** [rzwitserloot/lombok#1655]
The `@AllArgsConstructor` is a bit controversial. It makes an ugly API,  it causes issues with Jackson, sometimes Hibernate and JAXB, the way it is used it makes the .class file a bit larger just for a single purpose, JVM needs to check for potential super constructors...

It would be nice if the builder class could (optionally) directly call setters on a newly created object, and then simply return that object on `build()`.

What would be the point of having a builder then, right? Two reasons:

1) Getting rid of a constructor with parameters,

2) The setters could be (package) private. `Foo.Builder` could access them, but setters would not be visible outside. This would allow package (or inner static) classes to alter the object, but from the outside, the class would be "unmodifiable".

As a bonus, a builder class implemented this way would be faster create smaller .class file.

**Comment by randakar** [comment]
So you propose to replace the implicit allargsconstructor with implicit
setters then. ;)
What about classes that do not need setters?

Frankly, this is very much a matter of taste and preferences. I for one
hate setters for a whole bunch of reasons. If it was possibly to get rid of
them entirely, I would.
Your list of problems with the allargsconstructor does not really convince
me, either.
- Jackson works fine with it. Works fine with builders, too.
- Generated setters would make that object even bigger (one method per
field, not just one method)
- The ugly API isn't even directly visible
- The JVM always needs to check for super constructors, also for the no
args constructor the builder still needs to call (and generate).

Conversely, making objects only partially immutable like that makes a whole
host of optimisations harder. Having fields final, not having setters,
gives the JVM guarantees your version won't be able to give.

So no, not an improvement.




Op za 14 apr. 2018 03:46 schreef Ondrej Zizka <notifications@github.com>:

**Comment by rspilker** [comment]
Having final fields be set in the constructor also guarantees safe publication and gives [better performance](https://docs.oracle.com/javase/specs/jls/se9/html/jls-17.html#jls-17.5).
