### ISSUE TITLE
@UtilityClass compile error

### ISSUE THREAD

**Issue by Wangxiz** [rzwitserloot/lombok#1658]
when I use `@UtilityClass` to annotate a utility class, for example:
```java
@UtilityClass
public class Utils {
    public void print(String s) {
        System.out.println(s);
    }
}
```
I can not use:
```java
import static util.Utils.print;
```
to import the method `print` statically. 
And I got an error:
```cmd
Error:(1,1) java: can not find the symbol
symbol: static print
location: class
```

**Comment by victorwss** [comment]
I was skeptical of this and made a test intending to refute this bug. However, for my surprise, I just confirmed it.

I have a somewhat large project that uses some classes with `@UtilityClass`. Using `import static mypackage.SomeUtilityClass.*;` works nice for me. However, if I use `import static mypackage.SomeUtilityClass.someStaticMethod;`, then javac spits a lot of compile-time errors, even in some other unrelated classes that have nothing to do with that.

**Comment by rspilker** [comment]
Oh, this is a big sorry for the javac compiler for you.

For some reason, non-star static imports are evaluated before the annotation processor gives lombok a chance, meaning that an error occurs, and the annotation processors will not be triggered at all.

This is a known bug, and not something we can change easily in lombok.

**Comment by victorwss** [comment]
@rspilker So, you consider this to be a javac bug instead?
