### ISSUE TITLE
lombok build getters/setters not by standard Java Beans specification

### ISSUE THREAD

**Issue by jsbxyyx** [rzwitserloot/lombok#1661]
# question
lombok version: lastest
lombok build getters/setters not by standard Java Beans specification

# code
## standard java beans getter/setter
```java
public class A {
private String vNum;
public void setvNum(String vNum) {
    this.vNum=vNum;
}
public String getvNum() {
    return vNum;
}
}
```

## lombok getter/setter (decoder result)
```java
public class A {
private String vNum;
public void setVNum(String vNum) {
    this.vNum=vNum;
}
public String getVNum() {
    return vNum;
}
}
```
# resolve
you can use Introspector.decapitalize(name) get property

**Comment by victorwss** [comment]
Seems to be another dupe in the pile: #757, #1593, #1496, #1453, #1454.

**Comment by rspilker** [comment]
There are conflicting implementations, even in java.beans.
- java.beans.NameGenerator.capitalize
```java
    public static String capitalize(String name) {
        if (name == null || name.length() == 0) {
            return name;
        }
        return name.substring(0, 1).toUpperCase(ENGLISH) + name.substring(1);
    }
```
- java.beans.PropertyDescriptor (constructor uses NameGenerator)
- Introspector.decapitalize
```java
    public static String decapitalize(String name) {
        if (name == null || name.length() == 0) {
            return name;
        }
        if (name.length() > 1 && Character.isUpperCase(name.charAt(1)) &&
                        Character.isUpperCase(name.charAt(0))){
            return name;
        }
        char chars[] = name.toCharArray();
        chars[0] = Character.toLowerCase(chars[0]);
        return new String(chars);
    }
```

If we would have started lombok right now we might have made a different choice.

**Comment by xxzkid** [comment]
@rspilker 
most open sources frameworks use Introspector.decapitalize(name) method build java beans
example: spring, dozer, jackson etc...

**Comment by rzwitserloot** [comment]
Duplicate of #2693
