### ISSUE TITLE
Add @toMap Annotation ?

### ISSUE THREAD

**Issue by xie19900123** [rzwitserloot/lombok#1667]
Dear Lombok team, is can add  `@ToMap` Annotation ,
something like this:

```java
@ToMap
public DemoBean {
   String code;
   String name;
} 
```
to:
```java
public DemoBean{
   String code;
   String name;

  public Map<String,Object> parseMap(){
    Map<String,Object> map = new HashMap<String,Object>();
    map.put("code",this.code);
    map.put("name",this.name);
    return map;
  }
}
```
Although it can be created through beanUtil or BeanCopier, this performance is better?

**Comment by chenjazz** [comment]
@ToMap is T,not t

**Comment by rspilker** [comment]
Although I can imagine some use cases, it is for now below our threshold regarding the effort versus benefits.
