### ISSUE TITLE
cannot find symbol class Data if import inner inner class

### ISSUE THREAD

**Issue by zhugw** [rzwitserloot/lombok#1684]
There is an inner inner class Bar,

```
    @Data
    public static class Foo{
        private int id;
        private List<Bar> barList;
        @Data
        public static class Bar{
            private String name;
        }
    }
```

At first execute below code it's OK

```
        Foo.Bar bar = new Foo.Bar();
        bar.setName("aaa");
        System.out.println(bar);
```

but after add an import 
```
        import Test.Foo.Bar;

        Bar bar = new Bar();
        bar.setName("aaa");
        System.out.println(bar);
```
it compiles failed
```
Error:(222, 6) java: cannot find symbol
  symbol:   class Data
  location: class Test
```

why in this case `import` cannot co-exists with `@Data` upper Foo ?

**Comment by rspilker** [comment]
This is a known bug in javac. Static imports are resolved before annotation processors get the opportunity to generate the code. Please submit a bug report at Oracle.

It should be possible to also reproduce this behavior with a regular annotation processor, which might increase the change that they'll fix it.
