### ISSUE TITLE
Any ways to difine self  extentions?Any wikis?

### ISSUE THREAD

**Issue by cholf** [rzwitserloot/lombok#1687]
I wan to define self extentions,some examples on Internet,but too old, can't compile,Any Offical ways?Thanks.

**Comment by grimly** [comment]
What kind of extension are you looking for ?

You can hook the use of annotation on compilation time with the `Processor` SPI if you want to, but lombok don't really have to help you on that matter.

**Comment by rzwitserloot** [comment]
Only real way is to git clone the lombok repo and build lombok.jars with your custom extensions. For inspiration, look at lombok's existing featureset and read the wiki pages on this github project.
