### ISSUE TITLE
Unable to use Multiple @Builder in one class

### ISSUE THREAD

**Issue by GerroDen** [rzwitserloot/lombok#1688]
Hi,

i had the concept to build several builders in one class like this:
```
public class M {
  @Builder(builderClassName="ABuilder", builderMethodName="a")
  public static A a(String p1, Z p2) {
  }

  @Builder(builderClassName="BBuilder", builderMethodName="b")
  public static B b(X p1, Y p2) {
  }
}
```
and i would have expected to be able to use the builders like this:
```
M.a().p1("").p2(new Z()).build();
M.b().p1(new X()).p2(new Y()).build();
```

And this worked for 2 builders. But somehow with the third builder, my maven project did not compile on my mashine anymore, although it did on other mashines. I do not understand why it sometimes worked and sometimes not.
The problem is fixed, when i wrap the builder methods with inner classes of `M`, but i would like to spare that boiler plate.

**Comment by rspilker** [comment]
No feedback
