### ISSUE TITLE
Allow to create costume annotations containing a set of zlombok annotations

### ISSUE THREAD

**Issue by idosu** [rzwitserloot/lombok#1691]
lets say I have a lot of classes that need to have `@Getter @Setter @ToString ....` annotations, instead of writing all the annotations on all the classes I would like to create a costume annotation that will "inherit" from those annotations and use it. for e.g.
``` java
// src/main/java/Pojo.java
// @Retention(SOURCE)
@Target(TYPE)
@Getter @Setter @ToString
public @interface @Pojo {
}

// src/main/java/MyObject.java
@Pojo
public class MyObject {
    int myField;
    ....
}

// src/main/java/NotMyObject.java
@Pojo
public class NotMyObject {
    int notMyField;
    ....
}
```

**Comment by rspilker** [comment]
Unfortunately not possible, since it would require resolution.
