### ISSUE TITLE
Compilation error of @SneakyThrows for generic exceptions in JDK 10

### ISSUE THREAD

**Issue by kgeorgiy** [rzwitserloot/lombok#1693]
The following code causes `SneakyThrowsRemover` to fail with 

> Error during the transformation of 'RunnableE'; post-compiler 'lombok.bytecode.SneakyThrowsRemover' caused an exception: java.lang.IllegalArgumentException`

    @FunctionalInterface
    public interface RunnableE<E extends Exception> {
        void run() throws E;

        @lombok.SneakyThrows static <E extends Exception> void sneaky(final RunnableE<E> runnable) {
            runnable.run();
        }
    }

This behavior reproduces on both Oracle and Open JDK 10.0.1.

The root cause of this `IllegalArgumentException` is `org.objectweb.asm.ClassReader`:

> java.lang.IllegalArgumentException
   at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
   at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
   at lombok.bytecode.AsmUtil.fixJSRInlining(AsmUtil.java:37)
   at lombok.bytecode.SneakyThrowsRemover.applyTransformations(SneakyThrowsRemover.java:47)
   at lombok.core.PostCompiler.applyTransformations(PostCompiler.java:43)
   at lombok.core.PostCompiler$1.close(PostCompiler.java:74)
   ...

The provider of `ClassReader` is [lombok.patcher](https://github.com/rzwitserloot/lombok.patcher) that bundles version 6.0 of `org.ow2.asm`. Version 6.1 of `org.ow2.asm` fixed this error.

Proposed fix: [Upgrade ASM to version 6.1 in lombok.patcher](/rzwitserloot/lombok.patcher/pull/5), and, in turn, upgrade dependency of Lombok itself to the new version of [lombok.patcher](https://github.com/rzwitserloot/lombok.patcher).

**Comment by victorwss** [comment]
Better update to 6.1.1.

6.1.1 was a fix to address some bug on 6.1 in Java 10. See [this](https://gitlab.ow2.org/asm/asm/issues/317815).

**Comment by iherasymenko** [comment]
Better wait for 6.2. They gonna address the Java 11 support as well.

https://gitlab.ow2.org/asm/asm/issues/317830

**Comment by rspilker** [comment]
Working on it right now.
