### ISSUE TITLE
Feature Request: Google Flogger

### ISSUE THREAD

**Issue by omaric** [rzwitserloot/lombok#1697]
Sorry if this is the wrong place for feature requests.

Lombok is great, and the concept of ```@Log``` and other loggers is very good. However, out of the many logger options, it doesn't include the best logger: [Flogger](https://github.com/google/flogger). Compare the other loggers:

- Log, Log4j, and CommonsLog have no support for parameters at all
- Log4j2, Slf4j, and XSlf4j use {} instead of %s. This can be confusing when you have String.format() statements in the same file.
- JBossLog isn't Flogger

Flogger is very fast (including optimized parameterized logging) and includes features like:
```
// Log 1 in 100 messages to avoid spamming the logs.
logger.atInfo().every(100).log("My message", args);
// Log at most once every 5 seconds.
logger.atInfo().atMostEvery(5, SECONDS).log("My message", args);
// This obviates the need to create exceptions just to see the stack
logger.atInfo().withStackTrace(LARGE).log("Message");
```

Thanks for consideration.

**Comment by omaric** [comment]
I didn't realize that was the reasoning behind the log annotations. I thought it was to reduce boilerplate.

Are you certain the stack trace call is expensive? I ask because everything else in Flogger is highly optimized, and the main two operations are a single, cached reflective Class.forName() call, and a Throwable.getStackTrace() call, which should be quicker than the expensive Thread.getStackTrace.

I would _definitely_ use it if it were added to Lombok, as I have used it in other projects. I think other users might enjoy it, too. :)

**Comment by Maaartinus** [comment]
> Are you certain the stack trace call is expensive?

I can't speak for him, but I'm sure, it's *relatively* expensive. It'd very bad for performance when done for every log line, but it hardly matters when done once per class. I guess, it can (and will) be optimized using JEP 259, but I'd bet, hardly anybody will notice.
