### ISSUE TITLE
Lombok v0.17 with property (of type boolean) with name that start with "is"

### ISSUE THREAD

**Issue by roussi** [rzwitserloot/lombok#1702]
If a class field of type **boolean** starts with "**is**" for example `isActivated` lombok provide setter name as `setActivated` ( normaly it should be `setIsActivated` for clarity reason)

**Comment by rspilker** [comment]
I don't know if I agree, I general you probably shouldn't even start fields with `is`, just use `activated`.

But that isn't relevant. We didn't do it, not we have a lot of users. 

If we ever look at configuration options for getter and setter names, we might take this into account.

P.S. Lombok v0.17 is not a version I recognize.
