### ISSUE TITLE
@EqualsAndHashCode(of = {}, callSuper = true) analogue in new syntax

### ISSUE THREAD

**Issue by soberich** [rzwitserloot/lombok#1707]
Hi,
Previously there was a workaround to certain cases.
What would be the analogue in new syntax?
```java
@EqualsAndHashCode(of = {}, callSuper = true)
```

**Comment by cptwunderlich** [comment]
According to the docs, that would be `@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)`. But this seems to be broken right now: #1709

**Comment by rzwitserloot** [comment]
1709 is now fixed, to be released soon.
