### ISSUE TITLE
ClassCastException for Lombok 1.6.22 and Gradle 4.8

### ISSUE THREAD

**Issue by pkubowicz** [rzwitserloot/lombok#1716]
To reproduce:

Run `gradle init --type java-library` and modify generated project:

build.gradle
```
plugins { id 'java-library' }

dependencies {
    compileOnly 'org.projectlombok:lombok:1.16.22'
    annotationProcessor 'org.projectlombok:lombok:1.16.22'
}

compileJava {
    options.incremental = true
}

repositories {
    jcenter()
}
```

Foo.java
```
import lombok.Data;

@Data
public class Foo {
    private final boolean historical;
}
```

Running `gradle build` causes error:
```
> Task :compileJava FAILED
src/main/java/Library.java:4: warning: lombok.javac.apt.LombokProcessor could not be initialized. Lombok will not run during this compilation: java.lang.ClassCastException: org.gradle.api.internal.tasks.compile.processing.IncrementalFiler cannot be cast to com.sun.tools.javac.processing.JavacFiler
public class Library {
       ^
        at lombok.javac.apt.LombokProcessor.getJavacFiler(LombokProcessor.java:447)
        at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:90)
        at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:112)
        at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:165)
        at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:73)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.init(DelegatingProcessor.java:57)
        at org.gradle.api.internal.tasks.compile.processing.IsolatingProcessor.init(IsolatingProcessor.java:44)
```

Note that the error appears in file not annotated with Lombok annotations (created by `gradle init`).

Workaround - either:
1. Downgrade Lombok to 1.16.20 (implicitly disables incremental compilation); or
2. Downgrade Gradle to 4.7

**Comment by victorwss** [comment]
The title is wrong. It is not 1.16.12, it is 1.16.22.

What happens with 1.18.0?

**Comment by pkubowicz** [comment]
1.18.0 causes the same error with the same stacktrace.

**Comment by arana198** [comment]
I have a similar issue:

`
../user/service/impl/UserServiceImpl.java:178: error: cannot find symbol
    userBO.getRoles()
          ^
  symbol:   method getRoles()
  location: variable userBO of type UserBO
`

I'm using Java 10, Lombok 1.18.0 and Gradle 4.8 (also tried with 4.7)

**Comment by ryonday** [comment]
With:
* Oracle Java 9.0.4,
* Gradle 4.8 
* Lombok 1.6.22 AND 1.18.0

I receive this error.

Reverting to Gradle 4.7 results in proper functionality.

**Comment by victorwss** [comment]
@arana198 Your problem seems to be something else unrelated to this. Perhaps #1572?

**Comment by soberich** [comment]
@pkubowicz  @arana198  This started with Gradle 4.6 see https://github.com/rzwitserloot/lombok/issues/1603
@victorwss  You've asked for MVCE there. So, finally we have a kind of it. It is hardly reproducible while I was trying to provide MVCE on a small project and minimal setup - it did not appear. Now this example is finally small and shows the issue, while this one uses Eclipse - this may be a hint to investigate the cause, because neither me nor many other related similar issue reporters were not using Eclipse, so maybe the difference in compilers may be a hint...

**Comment by mszabo-wikia** [comment]
looks like Gradle internals changed in 4.8, necessitating some case handling— ☝️ should address that

**Comment by victorwss** [comment]
Funny, this is the code where the error happens:

https://github.com/rzwitserloot/lombok/blob/master/src/core/lombok/javac/apt/LombokProcessor.java#L429-L448:

```java
	/**
	 * This class casts the given filer to a JavacFiler. In case of
	 * gradle incremental compilation, the delegate Filer of the gradle wrapper is returned.
	 */
	public JavacFiler getJavacFiler(Filer filer) {
		final Class<?> filerSuperClass = filer.getClass().getSuperclass();
		if (filerSuperClass.getName().equals("org.gradle.api.internal.tasks.compile.processing.IncrementalFiler")) {
			try {
				Field field = filerSuperClass.getDeclaredField("delegate");
				field.setAccessible(true);
				Object delegate = field.get(filer);
				return (JavacFiler) delegate;
			} catch (final Exception e) {
				e.printStackTrace();
				processingEnv.getMessager().printMessage(Kind.WARNING,
						"Can't get the delegate of the gradle IncrementalFiler. Lombok won't work.");
			}
		}
		return (JavacFiler) filer;
	}
```

The code is clearly aware of gradle's `IncrementalFiler`, but something was wrong anyway. It tests if the `filer` has `IncrementalFiler` as a **superclass**, but the message suggests that it is a direct instance of `IncrementalFiler` and not a subclass of that.

Also, that if a reflection exception happens and is caught in the exception handler, a `ClassCastException` will be throw in the end of the method, but this is not the real problem.

**Comment by victorwss** [comment]
Also, the code could test if the `filer` is something that is neither `JavacFiler` nor `IncrementalFiler`, giving a better error message in this case to help us with future debugging and issue reporting.

**Comment by pkubowicz** [comment]
Can you release this soon?

In Gradle 4.9 you cannot use Lombok 1.18.0 or 1.16.22 at all - not even for non-incremental compilation (tested on the same project configuration as in the original bug report).

To get Java sources compiled with Gradle 4.9 you need to downgrade to Lombok 1.16.20.

**Comment by gerritdrost** [comment]
[Gradle 4.9 just hit the Arch Linux repo](https://git.archlinux.org/svntogit/community.git/log/trunk?h=packages/gradle), so I suspect more people will start suffering from this.

**Comment by sergey-morenets** [comment]
@pkubowicz Unfortunately I cannot downgrade Lombok to 1.16.20 because I use JDK 10 and this version doesn't support it
