### ISSUE TITLE
overload setter Feature Proposal

### ISSUE THREAD

**Issue by Zephor5** [rzwitserloot/lombok#1719]
I think `lombok.javac.handlers.JavacHandlerUtil.methodExists` should check the type of param.

Now I need to write an overload set method to cast some type into the original type of a field, then I have to write that method and the original setter method as well.

eg: `String egField`  I need to write `public void setEgField(int egField)` which will cast `int` to `String` and I also want the `public void setEgField(String egField)`

Does this make sense?

**Comment by Maaartinus** [comment]
> I think `lombok.javac.handlers.JavacHandlerUtil.methodExists` should check the type of param.

I'm afraid this isn't done as it'd be too complicated due to generics and [resolution](https://github.com/rzwitserloot/lombok/wiki/LOMBOK-CONCEPT:-Resolution).

> Now I need to write an overload set method to cast some type into the original type of a field, then I have to write that method and the original setter method as well.

No, you don't. Just mark your method with `@lombok.Tolerate`. Your case is exactly the motivation behind this annotation.

**Comment by Zephor5** [comment]
@Maaartinus thank you
