### ISSUE TITLE
lombock generated equals() not working as it did anymore

### ISSUE THREAD

**Issue by metas-ts** [rzwitserloot/lombok#1724]
Hi guys 
the following worked with lombok 1.16.16, but not with 1.16.22.

here are the failing test's reports:
* 1.16.22: https://jenkins.metasfresh.com/job/metasfresh/job/gh4033-material/18/testReport/de.metas.material.event.commons/AttributesKeyTest/ofAttributeValueIds/
* 1.18.0: https://jenkins.metasfresh.com/job/metasfresh/job/master/8116/testReport/junit/de.metas.material.event.commons/AttributesKeyTest/testSerializeDeserialize/

here is the commit that fixed the test for 1.16.22 
https://github.com/metasfresh/metasfresh/commit/e2393a63eaa0830f71dc48de865f3210a71e69e4 (see line 48)

Here is the "fixed" AttributesKey file: https://github.com/metasfresh/metasfresh/blob/e2393a63eaa0830f71dc48de865f3210a71e69e4/de.metas.material/event/src/main/java/de/metas/material/event/commons/AttributesKey.java

Here is the test case
https://github.com/metasfresh/metasfresh/blob/e2393a63eaa0830f71dc48de865f3210a71e69e4/de.metas.material/event/src/test/java/de/metas/material/event/commons/AttributesKeyTest.java

As a side note, I think I have other cases where `@EqualsAndHashCode(doNotUseGetters = true)` didn't help me out, e.g. this test failure: @EqualsAndHashCode(doNotUseGetters = true) ..at least not in 1.16.22, but I'm not definitive about 1.18.0

**Comment by potentcocktail** [comment]
I've noticed that @EqualsAndHashCode doesn't auto-exclude transient fields any more, ever since 1.16.22, even though the documentation says it does.

**Comment by rspilker** [comment]
Oops. Looking into it now.

**Comment by rspilker** [comment]
Thanks! I've also added some tests to prevent similar problems in the future.
