### ISSUE TITLE
non-static variable this cannot be referenced from a static context

### ISSUE THREAD

**Issue by aikar** [rzwitserloot/lombok#1725]
Code: https://gist.github.com/aikar/2358353bd3033dea000a64d59baf5572

In Lombok state, I get: 
```
[ERROR] LootContext.java:[20,1] non-static variable entity cannot be referenced from a static context
```

When I delombok the file, no error occurs.

Version: 1.18.0

Looks related to https://github.com/rzwitserloot/lombok/issues/1527 but since that was fixed, this is either a regression or something new.

**Comment by aikar** [comment]
I now notice the delomboked code did not generate correctly.

my expectation is that if the builder is supplied a value, it uses that value, else it executes the statement provided to default to calculate the default.

goal being I pass in an entity,  and all of the effective values are pre calculated, but the builder can override the precalc ones.

**Comment by Maaartinus** [comment]
@aikar I'm afraid, it can't work. This snippet

    @Default
    @Nullable
    Entity entity;
    @Default
    double difficulty = Survival.getEntityEffectiveDifficulty(this.entity);

without using a builder, initializes `difficulty` as

     Survival.getEntityEffectiveDifficulty(null);

When you assign `entity` in the constructor, then it's too late as the initializer expressions get evaluated *before* the constructor (which I find stupid as it's strictly less usable than the other way round, but Sun failed to ask me :laughing:).

> my expectation is that if the builder is supplied a value, it uses that value, else it executes the statement provided to default to calculate the default.

I'm afraid, that's too optimistic. AFAIK Lombok just copies the expressions to the builder. So they get *always* executed and this happens before you can set any fields manually.

This basically restrict its usefulness to constant expressions plus some rare cases like `private long start = System.nanoTime()`. Note that this is exactly like without using `@Builder`.

**Comment by rspilker** [comment]
As @Maaartinus already said, initializer expressions for fields should be possible to be evaluated in a static context. You could see the constructor as a static method. You could refer to other already initialized fields, but then those must be evaluable in a static context.

We could try and make an effort to allow for referencing previously initialized fields. But that's a lot of work. 

But referring to uninitialized fields would never work. Theoretically we could reorder initialization order, but that would be so unexpected, that we're not going to consider that.
