### ISSUE TITLE
Allow defining exception type on @NonNull

### ISSUE THREAD

**Issue by odupuy** [rzwitserloot/lombok#1728]
The default of `@NonNull` ([doc](https://projectlombok.org/features/NonNull)) is to throw a `RuntimeException` or an `IllegalArgumentException` if the value is null. However, this does not help when we want a specific exception (the other one of the two above) for a given check instead of the default one or a user defined exception.
In the following example, Lombok does not help.
```
   public Client addClient(UUID subGroupId,@NonNull() UUID clientId) {
      if(clientId == null) {
         throw new SubscriberGroupRequestException("Invalid client id.");
      }
   ...
```
However, it would if it was possible to specify the class of the exception e.g. 
```
   public Client addClient(UUID subGroupId,@NonNull(type=SubscriberGroupRequestException.class) UUID clientId) {
      // however no choice on the message
      }
   ...
```
this would be even better if #1029 was implemented to have a custom message, possibly with a placeholder
```
   public Client addClient(UUID subGroupId,@NonNull(text="Invalid client id.", type=SubscriberGroupRequestException.class) UUID clientId) {
   ...
```

Thanks

**Comment by rspilker** [comment]
According to Effective Java and other sources, a NullPointerException is the thing you should throw if an arguments is null but shouldn't. We did already make it configurable to also cater for IllegalArgumentException. For now, we consider everything else not common enough to spend increased code complexity and maintenance time on.
