### ISSUE TITLE
IntelliJ IDEA plugin development does not keep pace

### ISSUE THREAD

**Issue by soberich** [rzwitserloot/lombok#1729]
Hi.
I am very concerned about @mplushnikov 's team seems not to keep their plugin in active deveplopment.
Just bumping versions and that is it.
Without proper IDE support Lombok users will struggle.
Is there any possibility to give a watchword (if correct to say so) to the community to find one(s) who's freely familiar with IntelliJ IDEA plugins ecosystem to quickly fork and continue or smth like that,
I am not familiar at all, that is why I post this.

**Comment by hc-codersatlas** [comment]
Maybe the best way is not to fork it but help contribute to that project? I'm sure the plugin would appreciate a pull request or 2.

**Comment by soberich** [comment]
@hc-codersatlas  Sure. The poit is not "how" but "what". I a kind of overestimate to eliminate the problem.

**Comment by soberich** [comment]
@mplushnikov silently released current stable version support plugin though keeping almost total silence e.g. not responding to most of the issue tracker messages. Might be busy, but not clear why so non-comunicative in issue tracker. Great they made it overall. Thanks.
