### ISSUE TITLE
I don't see Lombok generated code in .class files, but in Delombok-ed version the code is present

### ISSUE THREAD

**Issue by gprincip** [rzwitserloot/lombok#1739]
I have a Spring web app with hibernate, I am using Maven and Eclipse. I Delombok-ed the code, and in `target/generated-sources/delombok` the code is as it should be, with all generated methods. But when I check `war/WEB-INF/classes` for `.class` files, I don't see any Lombok generated code. Maven builds the project successfully, Tomcat starts with no problems, but when I send web request which invokes the method where I use a getter which should be generated by Lombok, I get an exception that says that the getter method is undefined.  Here is the sample of class I am using: 

```
@XmlRootElement
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table
public class HeroEntity
{
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	@Version
	private int version;

	@Column
	private String name;

	@ManyToMany(mappedBy = "heroes")
	private List<ComicBookEntity> comicBooks;
}

```

**Comment by Maaartinus** [comment]
@gprincip There's nothing wrong with your class, but nobody can help you without more details. Others are using Lombok with Maven, Eclipse and Hibernate and it works for them. I'd suggest to

- Do a clean build. Code what compiles can hardly throw a `NoSuchMethodError`.
- Try the most recent published Lombok version (AFAIK 1.18.0).
- Try to create an [sscce](http://sscce.org/).
- Do not rephrase what the exception says, post the stacktrace instead.
- Give more details (your Java version, OS, ....).

**Comment by gprincip** [comment]
@Maaartinus  Thanks for the answer.

I did a clean build and it didin't help, also updated Lombok dependency to 1.18.0 version.

I am using Ubuntu 16.04 and java JDK 1.8.0_171

Here is the source code: https://www.github.com/gprincip/comicbooks

Here is the exception stack trace : http://textuploader.com/dzkvn

And here is the maven clean build : http://textuploader.com/dzkvb

**Comment by Maaartinus** [comment]
@gprincip I tried it using `mvn compile -DskipTests=true` and it didn't compile. The first error is
```
[ERROR] /tmp/mg/180625-162439-453964667/comicbooks/src/main/java/rs/ac/ni/pmf/marko/comics/server/provider/impl/ComicBookProviderImpl.java:[41,33] unreported exception rs.ac.ni.pmf.marko.comics.server.exception.ResourceNotFoundException; must be caught or declared to be thrown
```
That's unrelated to Lombok. I wouldn't bother investigating any further before all such problems are cleared. There are more such errors (e.g., [here](https://github.com/gprincip/comicbooks/blob/master/src/main/java/rs/ac/ni/pmf/marko/comics/server/api/HeroDTO.java#L28), fix them first.

Your exception is actually a compile-time error. Eclipse (unlike javac) produces class files even when the source code contains errors and adds exceptions generating compile-time error messages like "The method getId() is undefined for the type HeroEntity".

There must be something in your Eclipse showing that the project didn't really compile. Open the "Problems" view or alike to see it.

You're using `lombok-maven-plugin` version `1.18.0.0`, but `lombok` version `1.16.20`, which isn't the most recent (but this shouldn't matter).

**Comment by janrieke** [comment]
Also remember to update the lombok that is installed in Eclipse (simply by reinstalling the current version). Having different lombok versions in Eclipse and Maven may lead to code compiling in Eclipse but not in Maven, or vice versa.

**Comment by gprincip** [comment]
@Maaartinus @janrieke
I actually didn't know that there was such thing as lombok for eclipse. Now when I installed it I saw all errors that wasn't the ones related to missing getter/setter/constructor, and everything works fine. Thanks again.
