### ISSUE TITLE
Delombok javadoc output doesn't work correctly under Windows

### ISSUE THREAD

**Issue by grv87** [rzwitserloot/lombok#1745]
Given the source:
```
  /**
   * @param websiteUrl project website URL
   * @return project website URL
   */
  @Getter @Setter
  private String websiteUrl;

  /**
   * @param issuesUrl issues URL
   * @return issues URL
   */
  @Getter @Setter
  private String issuesUrl;
```
using delombok under Windows (CR+LF line endings) I got extra empty lines that are not parsed correctly by javadoc:
```
  /**
   *

   * @return issues URL
   */
  @java.lang.SuppressWarnings("all")
  public String getIssuesUrl() {
    return this.issuesUrl;
  }

  /**
   * @param issuesUrl issues URL

   */
  @java.lang.SuppressWarnings("all")
  public void setIssuesUrl(final String issuesUrl) {
    this.issuesUrl = issuesUrl;
  }
```

**Comment by grv87** [comment]
Sorry for delay.
Lombok 1.18.2
JDK 1.8.0u172
Yes, I use Gradle.

Test case: https://github.com/grv87/delombok-windows

Additional info: the problem occurs only when both `@param` and `@return` are used.

**Comment by grv87** [comment]
The problem arises under Windows only and with source files having CRLF line endings only.
Under Linux, even if CRLF line endings are used, no problem.

**Comment by rosti-il** [comment]
Please consider my pull request of #2548
Change of the JavacHandlerUtil.java in that PR fixes this issue by the right way.
https://github.com/rzwitserloot/lombok/pull/2548/commits/87d8e0016f17472af46aba8cec76445eae142d0d

**Comment by rzwitserloot** [comment]
PR 2548 fixes this.
