### ISSUE TITLE
@Builder does not respect @Accessors in Intellij Lombok Plugin

### ISSUE THREAD

**Issue by fredlee0109** [rzwitserloot/lombok#1748]
I'm on Lombok Plugin Version 0.18-2018.1 on Intellij Ultimate 2018.1.3 Version.

Essentially, when you use @Accessors(prefix = ..), lombok's builder will not respect this, and will continue to force you to use with the prefix. In comparison, @Getter and @Setter will respect removing the prefix.

Code Example:

```
@Builder
public class TestClass {
@Accessors(prefix = "m")
private String mSample = "sample 1";

// Intellij plugin will give you "Cannot resolve sample" on this builder chain, but compiles successfully. It will give you OK if you make it "builder().mSample(...)" but will fail to compile.
private static TestClass sInstance = TestClass.builder().sample("sample 2").build();
}
```

**Comment by mplushnikov** [comment]
@rzwitserloot  Can be closed here... 👍

**Comment by evookelj** [comment]
@mplushnikov Can you clarify why it has been closed here? I am still getting the same issue and would like to know how to fix it, so it'd be great if you could elaborate
