### ISSUE TITLE
@Slf4j why not support @Inherited ? 

### ISSUE THREAD

**Issue by liujinjin777** [rzwitserloot/lombok#1750]

**Comment by janrieke** [comment]
It's a bit difficult to guess what you are referring to, without any explanation or use case.
But what I think you want is that any subclass of a class that has an `@Slf4j` annotation also automatically gets the `log` declaration generated.

First con is that not every subclass will actually use the logger. Then lombok would generate unused code.
Second con is technical: At the time lombok steps in and generates code, resolution did not take place, yet. I.e., the type hierachy has not been established by the compiler, and thus lombok cannot resolve superclasses. And that means that lombok annotations cannot be inherited from superclasses.

**Comment by rzwitserloot** [comment]
I think @janrieke covered it well. Feel free to re-file another issue with more details if you meant something else, @liujinjin777
