### ISSUE TITLE
Lombok Installer Is Not Finding my STS 3.9.5 / Eclipse Photon Installation

### ISSUE THREAD

**Issue by adamzr** [rzwitserloot/lombok#1756]
I am running the lombok jar file, but it doesn't find my new STS installation, justr the old one taht already has lombok in it.

**Comment by rspilker** [comment]
Can you tell us that the full path to your installation directory is, what platform you use, and the name of both the executable and the ini file,

**Comment by rspilker** [comment]
Closed due to no response from reporter.
