### ISSUE TITLE
lombok.builder.flagUsage doesn't work

### ISSUE THREAD

**Issue by kaiako** [rzwitserloot/lombok#1759]
trying to set this property to error or warning doesn't work. I can set flagUsage for getter,setter,data but builder doesn't work.

this is what is in my lombok.config:

config.stopBubbling = true
lombok.val.flagUsage = error
lombok.var.flagUsage = error
lombok.nonNull.flagUsage = error
lombok.cleanup.flagUsage = error
lombok.equalsAndHashCode.flagUsage =error
lombok.requiredArgsConstructor.flagUsage = error
lombok.allArgsConstructor.flagUsage = error
lombok.value.flagUsage = error
lombok.builder.flagUsage = error
lombok.sneakyThrows.flagUsage = error
lombok.synchronized.flagUsage = error
lombok.getter.lazy.flagUsage = error
lombok.experimental.flagUsage = error

---------------------------------------
Version: Oxygen.3 Release (4.7.3)
Build id: 20180308-1800

lombok version: 1.18.0

**Comment by janrieke** [comment]
Can confirm. For ecj, it got lost in commit 63aefa41e432a050496e9f96c6ce570dde276e18 over 3 years ago :-)

**Comment by janrieke** [comment]
5ec61bb only fixed this for javac, eclipse's HandleBuilder is still missing it.
