### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by rPraml** [rzwitserloot/lombok#1769]
I played around a bit with jprofiler and identified some hotspot methods that can easily be optimized.
I've created several PRs for each optimization:

#1760 #1761 #1762 #1763 #1764 #1765 #1766 #1768 

All in all the performance gain is not much, it's about 5% (except #1766 - if you using a non-lombok project - and #1768 ) - so decide if it is worth to have the minor changes in the code base.

As far as I see, the critical paths are the traverse/traverseChildren methods. The AST tree is traversed several times (one time for each handler-priority)
I do not yet understand each detail of lombok, but is it really neccessary to traverse the same tree several times for each priority. Wouldn't it be better to traverse the tree one time, gather all data of used annotations and do the whole work afterwards?

**Comment by rPraml** [comment]
Thanks to the commets of @randakar, I reflected all the changes and made one PR #1771 that really improves performance (not only 5%) by mainly reducing method invocations. I only adopted the most important changes

**Comment by rspilker** [comment]
I think I've incorporated the relevant pull requests.
