### ISSUE TITLE
NetBeans compile on save does not work with 1.18.0

### ISSUE THREAD

**Issue by md-5** [rzwitserloot/lombok#1770]
Using Maven 3.5.0 on NetBeans 8.1, or Maven 3.3.9 on NetBeans 9.0 RC1, the result is the same.
* Create a file and compile it
* Observe it being in the class directory
* Edit the file
* File is no longer in the class directory

Issue does not occur on 1.16.18 or older versions, but does on all newer versions.

**Comment by md-5** [comment]
So 4ac941acca350b889ae6ccd6f455c992a5e49dce / #1555 is actually the commit that introduced this bug according to git bisect

**Comment by md-5** [comment]
Reverting that commit fixes compile on save, but re introduces red warnings all over the IDE itself.
Will investigate further.

**Comment by md-5** [comment]
Only NetBeans 8.1 is fixed by reverting that commit, not NetBeans 9 RC1

Guessing compile on save uses a different file manager that is not accounted for

**Comment by md-5** [comment]
Completely disabling the file manager hooking produces results which work everywhere, with the side effect that the dummy force new round file is left behind and the SneakyThrows ASM processing doesn't work - neither of which are issues to me. Unfortunately I can only figure out a way to disable this via a system property and not via the Lombok config which requires an AST to already be created.

My second attempt was to rewrite the FileManager hooking to be much more minimal, and I did this quite simply in a way that worked on Java 8 and Java 10 without any special code for either, unfortunately it did not work on Netbeans compile on save, and I'm not particularly sure how to debug that.

**Comment by md-5** [comment]
I think the only reason that commit appears to work is because lombok doesn't even run at all when thats reverted....


I give up for now, but advice on a way to implement the option in my first paragraph would be good.

**Comment by charphi** [comment]
Same as #1577 
I've submitted a pull request (#1775 ) just before discovering your comments :)

**Comment by lathspell** [comment]
I had the same problems (SpringBoot Devtools not working due to missing class files) and it now works again with NetBeans 9.0 and lombok-edge. Time for a 1.18.3 release before Lombok gets a reputation of mysteriously breaking things?

**Comment by asbachb** [comment]
I guess the bug could be closed?!

**Comment by charphi** [comment]
Thats ok for me
