### ISSUE TITLE
lombok/launch/Patclombok/launch/PatchFixesHider$TransformhFixesHider$Transform

### ISSUE THREAD

**Issue by alan933** [rzwitserloot/lombok#1778]
I got this after installing for Eclipse Kepler and relaunch. 
What would cause this?

Also, I can no longer open ANY files in Eclipse.
I get:
lombok/launch/PatchFixesHider$Transform
and
lombok/launch/PatchFixesHider$ValPortal

**Comment by rzwitserloot** [comment]
I don't understand your bug report. What did you 'get'? If that was a reference to the title, where did you 'get' that? Perhaps add some screenshots or a more in-depth description.
