### ISSUE TITLE
Eclipse removes "import lombok.var;" on Organize imports

### ISSUE THREAD

**Issue by phcouton** [rzwitserloot/lombok#1783]
In Eclipse, the action "Source / Organize Imports" removes `import lombok.var;`, leading to compile errors when `var` is used. The "Do not create imports for types starting with a lowercase letter" parameter of the "Organize imports" settings has no effect on the problem. This problem occurs also indirectly when Organize Imports is used in Save Actions.

Seen with Eclipse Photon (4.8.0) and Lombok 1.18.0. If I remember well, this problem existed with the previous version of Eclispe.

Code used for tests :
```java
import lombok.var;

public class VarImportTest {
    public static void main(String[] args) {
        var myVar = "Foo";
        System.out.println(myVar);
    }
}
```

**Comment by victorwss** [comment]
What is your Java version? Hopefully this is not an issue for Java >= 10. But for Java 6-9, pretty much it is.

**Comment by phcouton** [comment]
Java 8 (jre1.8.0_172)

**Comment by akrestan** [comment]
Hello, may I ask about how this issue has been resolved if it's been resolved?

With the latest _Eclipse Java EE IDE for Web Developers Version: 2018-09_  and the latest _lombok 1.18.2_ I am still getting this error when the Eclipse's JVM is instrumented with `-javaagent:lombok.jar` even if there is no import of the `lombok.var ` type anywhere in the Java source code and lombok.jar is not among the project's dependencies
