### ISSUE TITLE
Restarting Eclipse or switching workspaces injects Lombok a second time

### ISSUE THREAD

**Issue by Pokechu22** [rzwitserloot/lombok#1789]
Restarting Eclipse or switching workspaces injects Lombok a second time.  I'm not sure if this causes issues in practice, but it seems problematic.

To reproduce:

1. Start eclipse
2. Select Help &rarr; About Eclipse
3. Note that "Lombok v1.18.0 "Envious Ferret" is installed. https://projectlombok.org/" is at the bottom.
4. Select File &rarr; Restart (or File &rarr; Switch Workspace)
5. Once Eclipse has opened again, select Help &rarr; About Eclipse
6. Note that the "Lombok v1.18.0 "Envious Ferret" is installed. https://projectlombok.org/" text is repeated twice.
7. Further restarts or workspace switches each add the text an additional time.  Fully closing eclipse and starting it again does clear it, though.

Eclipse version: Photon Release (4.8.0) (there's a lot of other eclipse info, but I'm not sure exactly what of it is useful and some of it contains somewhat personal information; if there's something else about the version that is needed let me know).

**Comment by rspilker** [comment]
Oh nice.

**Comment by rspilker** [comment]
New in Photon

**Comment by rzwitserloot** [comment]
Lombok wasn't really being loaded twice, just, the code that updates the eclipse about text was being called again. That code is now smarter about not re-applying the change.
