### ISSUE TITLE
ShadowClassLoader doesn't find files in META-INF/services/ in external jars

### ISSUE THREAD

**Issue by ftbe** [rzwitserloot/lombok#1792]
I have an external jar containing a custom annotation/annotation handler, and ShadowClassLoader doesn't load the files located in META-INF/services/ in this jar.
Here is a patch for this issue : [ShadowClassLoader.patch.gz](https://github.com/rzwitserloot/lombok/files/2231443/ShadowClassLoader.patch.gz)

**Comment by victorwss** [comment]
You should either publish a PR or at least state that the two occurences of `if (!partOfShadow` should be replaced by `if (!inOwnBase` on the `ShadowClassLoader` class.

**Comment by rspilker** [comment]
We currently cannot oversee the impact of this change. Our current advice is to fork lombok and add your code.
[Why we closed this issue](https://github.com/rzwitserloot/lombok/wiki/ISSUES:-Why-we-close-issues-without-a-lot-of-explanation.)
