### ISSUE TITLE
New feature: simple copy function for current instance

### ISSUE THREAD

**Issue by vyemialyanchyk** [rzwitserloot/lombok#1793]
I do not find a way.. @CopyFunction may be not a best name. It would be nice to have:

```
@CopyFunction
public class A {
  private final String field01;
  private final int field02;
}
```
will turn to
```
public class A {
  private final String field01;
  private final int field02;
  public void copy(A specimen) {
    this.field01 = specimen.field01;
    this.field02 = specimen.field02;
  }
}

```

**Comment by janrieke** [comment]
This can already be achieved using `@Builder(toBuilder=true)`: `specimen.toBuilder().build();`
Or you can use `@Wither` if you have immutable classes and want to create a copy with one value changed.
Is there a special use case you are thinking of that cannot be solved in this way?

**Comment by vyemialyanchyk** [comment]
no, no, you didn't understand, I use @Builder(toBuilder=true):
specimen.toBuilder().build();
this will create **new copy**
copy function intended to initialize existing class instance with values like in other class, sometimes there is a sense to have such functionality, i.e. this is replacement for chain of setters.

**Comment by janrieke** [comment]
Hmm, then I doubt the general usefulness of such an annotation. Why should I alter an existing instance in such a way that makes it an exact copy of another instance?
Could you describe your use case a litte more? Right now it looks to me like this is only useful in cases of inferior design, but I may as well be missing a point.

**Comment by Maaartinus** [comment]
It looks just like [Delphi Assign](https://stackoverflow.com/a/34481560/581205) and is IMHO really a case of a inferior design. Sometimes, you have an object in use somewhere and can't just replace it; then mutating it is the only choice (IIRC, I needed it a few months ago). Even more rarely, creating a new object is an unacceptable overhead... @vyemialyanchyk I just can't imagine needed this on a regular basis.

**Comment by vyemialyanchyk** [comment]
@Maaartinus "There are more things in heaven and earth, Horatio, than are dreamt of in your philosophy" )
I need this in JUnits for WebFlux code, when get response from WebClient body, the instanse is available and I can set these properties, but I can't update reference there.
Somethng like this:
```
    Aa ret02 = Aa.builder().build();
    webClient
        .get()
        .uri("/Aa/xx/{id}", 10)
        .accept(MediaType.APPLICATION_JSON_UTF8)
        .exchange()
        .expectStatus().isOk()
        .expectBody(Aa.class)
        .consumeWith(res -> {
          final Aa aa = res.getResponseBody();
          ret02.copy(aa);
        });
    Assertions.assertThat(ret02.getStatus()).isEqualTo("terminated");

```

**Comment by Maaartinus** [comment]
Why to copy all the data? Do they change when the `webClient` finishes?

As Lambdas want (effectively) final variables, you need a hack: A mutable reference. It can be a single element array or a an `AtomicReference<Aa>`. I chose the former:
```
Aa ret02 = new Aa[1]; 
webClient
        ...
        .consumeWith(res -> {
          ret02[0] = res.getResponseBody();
        });
    Assertions.assertThat(ret02[0].getStatus()).isEqualTo("terminated");
```

In case the data change (so you have to copy), combine my trick with cloning.

**Comment by vyemialyanchyk** [comment]
@Maaartinus I did not ask suggestion how to solve a problem in code, I've proposed a feature, in any case it seems reasonable for me, I can't insist someone should implement this cause this is open source project. Proceeding with example, why do you think 1 assertion for 1 property there? This is strange for me what same concepts conquer minds so they become missioners, like **immutable** for example, these are pretty relevant in some cases, but other part is mutable and having possibility to easy copy implementation have the equal sense as copy constructor. In any way guys this is your lombok team decision accept or reject the feature, with respect for good useful tool.

**Comment by randakar** [comment]
Thing is, that feature you want already exists in various different forms.

Tobuilder is one. BeanUtils.copyProperties() is another. Then there is the
Wither annotation, and the Clonable interface, and...

Op vr 27 jul. 2018 11:38 schreef vyemialyanchyk <notifications@github.com>:

**Comment by Maaartinus** [comment]
@vyemialyanchyk  I'm not opposed to the feature... actually, I had such an idea myself, but for every use case, I found a different solution, which was at least equally good.

> Proceeding with example, why do you think 1 assertion for 1 property there?

Do I?

You wanted to copy *all* properties of `Aa` and I copied the reference to the *whole* `Aa` object instead. There's nothing like "1 assertion for 1 property" in what I added.

---

I'm not part of the team, just a fan. The reason for Lombok providing relatively few features is that it has a much higher implementation overhead than any library. Writing a code generator or a reflective solution would be a matter of a few minutes. Doing the same with Lombok may take hours and there may be many more of maintenance.

This feature sounds rather harmless w.r.t. to the implementation... it might be a nice extension to `@Data`. It'd surely need a much better name (`copy` and `assign` are out of question; I'd propose `copyFrom` or `overwriteBy`) and some use case, where it can be easily replaced by something existing.

**Comment by rzwitserloot** [comment]
Well, as one of the two dictators as far as feature requests are concerned:

I understand what you're asking for, it may from time to time by useful, but not often enough to be worth the mental load of having this be something we'd need to list on the feature page and such.
