### ISSUE TITLE
建议@Data注解 支持子类继承

### ISSUE THREAD

**Issue by MincoXie** [rzwitserloot/lombok#1798]
这样做 对于企业级开发 以及自动生成代码 是非常友好的

实现思路：
   @Data注解 增加个属性 是否开启继承
   然后在    HandleData.java 中 增加代码如下：
  1.判断是否开启继承
  2.获取子类
  3.如果不为空，循环子类 再次调用
		handleGetter.generateGetterForType(typeNode, annotationNode, AccessLevel.PUBLIC, true, Collections.<Annotation>emptyList());
		handleSetter.generateSetterForType(typeNode, annotationNode, AccessLevel.PUBLIC, true, Collections.<Annotation>emptyList(), Collections.<Annotation>emptyList());
		handleEqualsAndHashCode.generateEqualsAndHashCodeForType(typeNode, annotationNode);

 同时也非常希望贡献自己的力量

**Comment by randakar** [comment]
... ok, I'm sure you want to communicate. But I highly doubt anyone here
speaks whatever language this is. Please try again in english.

Op wo 1 aug. 2018 04:44 schreef Minco <notifications@github.com>:

**Comment by janrieke** [comment]
This seems to be about letting `@Data` support inherited fields. This topic has been discussed a few times, and it is not easily possible.
