### ISSUE TITLE
New feature: Add support for customized builders in class for @SuperBuilder

### ISSUE THREAD

**Issue by philippeboyd** [rzwitserloot/lombok#1802]
The error is pretty explanatory : 
```
@SuperBuilder does not support customized builders. Use @Builder instead.
```

For instance, I'd like to have the following

```java
@SuperBuilder
public class User extends BaseModel {
    private String username;
    private String password;

    public static class UserBuilder {
        public User.UserBuilder password(PasswordService passwordService, String password) {
            this.password = passwordService.verifyAndEncode(password);
            return this;
        }
    }
}
```

**Comment by janrieke** [comment]
I decided explicitly against this feature, at least for the start. The reason is that the generated code is quite complex, and checking for existing implementation for all of the different elements is extensive and tedious.
So it's doable, but I'll focus on bugs and smaller features first.

**Comment by janrieke** [comment]
PR #1871 adds limited customization possibilities. However, you cannot replace the setter methods in the builder. But instead you could replace the `build()` method and do `this.password = passwordService.verifyAndEncode(password);` in there.
So this PR should at least fix this concrete issue.

**Comment by rspilker** [comment]
[Why we closed this issue](https://github.com/rzwitserloot/lombok/wiki/ISSUES:-Why-we-close-issues-without-a-lot-of-explanation.)
