### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by Wei0Wang** [rzwitserloot/lombok#1804]
@Setter(onMethod_ = {@Autowired}) on a type ，it compiler correct but delombok dosnot generate @Autowired

**Comment by victorwss** [comment]
Additional information like environment, java version, lombok version and a minimal code that reproduces the problem would be really welcome.

**Comment by Wei0Wang** [comment]
os: windows10、ide: inteliJ idea 2018.1.6、lombok plugin: 0.19-2018.1 、jdk: 1.8.0_40、 lombok: 1.18.2
use inteliJ idea delombok 

@Setter(onMethod_ = {@Autowired})
//@Setter(onMethod=@__({@Autowired}))
public class Test {
    private String param1;
    private String param2;
}

**Comment by rspilker** [comment]
Alternatively, in the [edge release](https://projectlombok.org/download-edge) we introduced `lombok.copyableAnnotations`. You could consider adding `@AutoWired` to the list, and put them on the fields.

**Comment by rspilker** [comment]
In hindsight, I think that it would put them on the parameter, not on then method.
