### ISSUE TITLE
Error: java.lang.module.ResolutionException: Module lombok does not read a module that exports org.mapstruct.ap.spi

### ISSUE THREAD

**Issue by arrowman53** [rzwitserloot/lombok#1806]
In my Java 11 Module project I have added the Maven dependency:
```
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.18.2</version>
    <scope>provided</scope>
</dependency>
```
In my module-info I added 
```
requires static lombok
```
but when I run my application in Eclipse Photon I get the error:
```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module lombok does not read a module that exports org.mapstruct.ap.spi
```

Did I forget to declare something?

**Comment by arrowman53** [comment]
There is a module jar that exposes the package: mapstruct-processor-1.3.0.Beta1.jar
The module-info.java of lombok has to be extended with  'requires transitive org.mapstruct.processor;' to solve this issue.

**Comment by tzieleniewski** [comment]
I've got the same error when trying to investigate project dependencies with jdeps with module-path.

**Comment by rzwitserloot** [comment]
'transitive' seems like that'd be wrong. I've added `requires static org.mapstruct.processor;` instead. Not sure this will work, the entire concept is basically FUBAR here and it seems impossible to have a lombok which CAN interact with mapstruct if you have that in your compilation run but doesn't require it to be there.

We weren't quite ready to mess with j11 just yet; we'd love some feedback if the hack we just cooked up actually would work.

Mind giving the edge-release a spin, @tzieleniewski / @arrowman53 ?

https://projectlombok.org/download-edge

**Comment by tzieleniewski** [comment]
I did some tests and got the following:
* when project is packaged as modular JAR it works with lombok version 1.18.2.
* when project is packaged as non-modular JAR it doesn't work with version 1.18.2 but works with edge.

You can try here - an example project for this.
https://github.com/tzieleniewski/jdeps-error-with-lombok

**Environment**
Apache Maven 3.5.3
Java version: 10.0.1, vendor: Oracle Corporation
Default locale: pl_PL, platform encoding: Cp1250
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Modular JAR**
```bash
C:\Users\tomasz.zieleniewski\Desktop\tmp\jdeps-error-with-lombok>jdeps --module-path target/dependency -R target/jdeps-error-with-lombok-1.0.0-SNAPSHOT.jar
com.intive
 [file:///C:/Users/tomasz.zieleniewski/Desktop/tmp/jdeps-error-with-lombok/target/jdeps-error-with-lombok-1.0.0-SNAPSHOT.jar]
   requires mandated java.base (@10.0.1)
   requires static lombok
com.intive -> java.base
   com.intive                                         -> java.lang                                          java.base
```
**Non-modular JAR with 1.18.2**
```bash
C:\Users\tomasz.zieleniewski\Desktop\tmp\jdeps-error-with-lombok>jdeps --module-path target/dependency -R target/jdeps-error-with-lombok-1.0.0-SNAPSHOT.jar
Error: Module lombok does not read a module that exports org.mapstruct.ap.spi
```

**Non-modular JAR with edge**
```bash
C:\Users\tomasz.zieleniewski\Desktop\tmp\jdeps-error-with-lombok>jdeps --module-path target/dependency -R target/jdeps-error-with-lombok-1.0.0-SNAPSHOT.jar
jdeps-error-with-lombok-1.0.0-SNAPSHOT.jar -> java.base
   com.intive                                         -> java.lang                                          java.base
   com.intive                                         -> java.lang.invoke                                   java.base
lombok
 [file:///C:/Users/tomasz.zieleniewski/Desktop/tmp/jdeps-error-with-lombok/target/dependency/lombok-edge.jar]
   requires mandated java.base (@9.0.1)
   requires java.compiler (@9.0.1)
   requires java.instrument (@9.0.1)
   requires jdk.unsupported (@9.0.1)
   requires static org.mapstruct.processor
lombok -> java.base
lombok -> java.compiler
lombok -> java.instrument
lombok -> jdk.compiler
lombok -> jdk.unsupported
lombok -> not found
lombok -> org.mapstruct.processor
   lombok                                             -> java.lang                                          java.base
...
```

**Comment by shashi7049** [comment]
I also faced such issue then I realized like 
a) I have added the Lombok jar manually that is the main cause once I add the entries of Lombok in pom.xml it worked 
   and I have removed that jar dependency jar which I added Earlier.
