### ISSUE TITLE
Support multiple log name and specified logger name

### ISSUE THREAD

**Issue by ppsnumi** [rzwitserloot/lombok#1811]
Hello 

I have some enhancement that support multiple log name and specified Logger name.

@Slf4j(logger={"", "loggerName1", "loggerName2"}, name={"", "log1", "LOG2"})
or
@Slf4j(logger={LombokLog.NAME, "loggerName1", "loggerName2"}, 
           name={LombokLogger.NAME, "log1", "LOG2"})
public class SomeClass {
           ~ Logger log = ~.getLogger(SomeClass.class);
           ~ Logger log1 = ~.getLogger("loggerName1");
           ~ Logger LOG2 = ~.getLogger("loggerName2");

Could it be more convenient?
(LombokLog and LombokLogger is an arbitrary name.)

thanks.

**Comment by rzwitserloot** [comment]
We intentionally do not make the name of the logger configurable via the annotation. Having multiple loggers seems like an exotic use (i.e. not for lombok), and having 2 arrays passed in where the reader has to figure out that the Xth element of the first array and the Xth element of the second are a pair is really ugly code, so this is not a workable idea in many ways. Sorry :(

**Comment by nbali** [comment]
@rzwitserloot what about using @Log and @Slf4j together? there are more use-cases for that than I would call exotic... normally @Slf4j is much handier, but it lacks a few methods for example @Log have
