### ISSUE TITLE
I got a warning message "Can't get the delegate of the gradle IncrementalProcessingEnvironment." on Eclipse.

### ISSUE THREAD

**Issue by yuu-suzuki** [rzwitserloot/lombok#1813]
I installed Lombok v1.18.2 to Eclipse Luna, to became get a warning message.
Warning message is "Can't get the delegate of the gradle IncrementalProcessingEnvironment.".
This warning message point out under class name.

I wanna fix this proble, I reverse installed Lombok version to v1.16.23.
I can fix and no proble.

**Comment by cabbonizio** [comment]
I have never received this before until I just switched over to Eclipse Photon, then installed latest Lombok and get this warning.  It's only a nuisance warning at this point, but it's popping up for most classes.

**Comment by jkeruzec** [comment]
Got the same thing here with latest lombok v1.18.2 and Eclipse Photon!

**Comment by HorusInfo** [comment]
Got the same problem!  
Version: Photon Release (4.8.0)
Build id: 20180619-1200

**Comment by XinYang-Pan** [comment]
Same for me, I'm using STS 3.9.3.

It seems that it got resolved in v1.18.3, currently in edge release.

It worked for me.

https://projectlombok.org/download-edge

**Comment by javacraft** [comment]
To confirm the above, I ran into the same issue with v1.18.2 with Eclipse Photon. Upgrading to the edge release resolved the issue.

**Comment by momomo** [comment]
Me four
