### ISSUE TITLE
default case in switch statements

### ISSUE THREAD

**Issue by punkratz312** [rzwitserloot/lombok#1814]
as its a bad behaviour not to cover the default case in a switch statement, but mostly or at least sometimes you dont want to handle it and just throw a runtime that tells this case can/should not happen its boilerplate that coud be covered by lombok that just throws the mentioned runtime exception.

thx for the nice tool

**Comment by Maaartinus** [comment]
IMHO covering the default is sometimes much worse... you write `default` and get no warning when the enum gets extended. What I usually do is extracting the switch into something like
```
private Something f(MyEnum e) {
    switch (e) {
        case A: return ...;
        case B: return ...;
        // no default!
    }
    throw new MyMissingCaseException(e);
}
```

The sad news is that a statement can't be annotated, so there's no way to tell Lombok what to do. I'd personally love something like
```
@ThrowOnMissingCase 
Whatever w = switch (e) {....};
```
but Lombok can't fix invalid Java syntax, so I can't see how to express this.

**Comment by rzwitserloot** [comment]
The only feasible way forward, given that annotating statements is [A] hard and [B] is probably MORE boilerplate, in the end, then the oneliner `default: throw new AssertionError("Missing case");` you're trying to avoid here, is the following:

A (probably lombok.config-powered) completely automatic, blanket application where lombok will, silently and without ANY annotation to indicate this magic is happening, add such defaults to EVERY switch statement you care to compile with javac/ecj whilst lombok so happens to be on the classpath.

Which does solve the dilemma quite well: The whole point is to be a lint-like catchall, designed explicitly to help you out when you forget.
The downside is rather obvious though: That' some voodoo magic. We're basically saying: With lombok on the classpath, java's switch statement is _different_, if you want uncovered cases to no-op their way through a switch statement, you gotta end with `default:` and then close your block.

I can see the case for a 'rewrite java to be more stringent', a kind of `"use strict";` from javascript, but then for java.

But that's a much bigger deal than this simple issue, and if the _only_ thing that you get is this switch behaviour I don't think it's worth it.

So, we need to [A] decide that this is a direction lombok should take, and [B] make a longer list of things we can automatically 'strict-ify'.

That just feels like the job for a different tool. Let's not go there for now.
