### ISSUE TITLE
lombok.config files are not taken into account for Gradle cache

### ISSUE THREAD

**Issue by ewirch** [rzwitserloot/lombok#1817]
How to reproduce:

1. Take any Java project
1. Add a `lombok.config` file to the root of the project. Contents:  `lombok.anyConstructor.addConstructorProperties=false`
1. Compile the project: `gradle compileJava` 
1. Repeat the command. Since the compiled artifacts are cached, the second invocation should take significantly shorter, maybe even 0s.
1. Change the `lombok.config`: `lombok.anyConstructor.addConstructorProperties=true`
1. Re-invoke the compile command. It takes 0s.

Gradle thinks everything is up to date since Lombok processor does not declare the config file as an input.

**Comment by rzwitserloot** [comment]
gradle gives you 4 options:

* You can not set anything in which case your mere presence completely disables incremental compilation.
* You can say you are an isolated AP (this is what lombok does and is _mostly_ correct), in which case incremental compilation works fine.
* You can say you're an aggregating AP. Not relevant here; lombok isn't.
* You can say you're dynamic, and then answer at runtime... but you have to answer pretty much immediately before you get to know what files you are supposed to process.

Therefore, gradle makes it impossible for us to interact and say that something changed in a way that requires a rebuild.

We can't fix this problem; gradle needs to expand on their API first, then we may be able to do something. Please file with gradle.
