### ISSUE TITLE
@Log / @Slf4j on interface - better error notification

### ISSUE THREAD

**Issue by walec51** [rzwitserloot/lombok#1824]
Today I've spend a couple of hours with this error message in my gradle build:

```
:some-project:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':some-project:compileJava'.
> Compilation failed; see the compiler error output for details.
```

Adding any sort of --info or JVM compiler flags didn't give me any more information other than the fact that the javac process exited with a unsuccessful return code and with no message.

After isolating the code that caused the error I found that this was the source of the problem

```
@Slf4j
public interface SomeInterface {
    // ...
```

It was kind of obvious once I understood this - you cannot add a 'private log` field to an interface.

But I think we should try to provide a better error message. Maybe the pre-procesor should throw an exception if one tries to do this?

**Comment by janrieke** [comment]
Lombok raises an error in this case, and both Maven and Eclipse use that error to print a meaningful error message: `@Log is legal only on classes and enums.` So this is either an issue in Gradle itself or in the Gradle configuration.

**Comment by walec51** [comment]
@janrieke thanks for the info, I'll investigate and report this issue to gradle if its not my configuration problem
