### ISSUE TITLE
Getters in Builders

### ISSUE THREAD

**Issue by paulolieuthier** [rzwitserloot/lombok#1825]
I could not find another issue related to that, so forgive me if it's a duplicate.

I would be very useful to have getters in builders, as in many occasions objects are not fully filled at once and some properties depend on others. There could be a specific option for `@Builder` (e.g. `getters = true`) or something more general (`onBuilder = @__(@Getter)`, although I'm not sure it works).

Is there a reason for not having this?

**Comment by paulolieuthier** [comment]
```java
...
MyClass.MyClassBuilder partiallyBuilt = buildPartially();
return partiallyBuilt
        .missingField(partiallyBuilt.getAlreadyFilledField() * 2)
        .build();
```

**Comment by Maaartinus** [comment]
+1 #731

**Comment by rspilker** [comment]
[Why we closed this issue](https://github.com/rzwitserloot/lombok/wiki/ISSUES:-Why-we-close-issues-without-a-lot-of-explanation.)

**Comment by rspilker** [comment]
Workaround: call build and use the getters of the generated object.

**Comment by adrian-skybaker** [comment]
>Workaround: call build and use the getters of the generated object.

That's inefficient if you have several stages that you want to inspect the object before building, and it doesn't work if the builder has incomplete properties (eg @NonNull fields that are not yet populated).

**Comment by wingsofovnia** [comment]
Having no getters also makes it impossible to use from Kotlin:
```java
@Value
@Builder(setterPrefix="set")
class MyClass {
  String text;
}
```
```kotlin
fun myClassWith(block: MyClass.MyClassBuilder.() -> Unit) = TODO("builder impl")
fun main() {
  myClassWith {
    text = "my text" // doesn't work because there is no getter -> not a valid bean -> isn't recognized as property
  }
}
```
