### ISSUE TITLE
There should be @SuperBuilder.Default annotation in my understanding 

### ISSUE THREAD

**Issue by kingraser** [rzwitserloot/lombok#1826]
I used lombok 1.18.2, and I find @Builder.Default is not supported by the class which annotated by @SuperBuilder

**Comment by kingraser** [comment]
Thanks for your work!
I am wondering when can we get the fixed stable version?

**Comment by kingraser** [comment]
@janrieke Another question is that when I use both Data and SuperBuilder in Idea, I got a warning that ToString's callsuper is false, can Data manage callsuper boolean value?

**Comment by koenverwimp** [comment]
Hi, I running into the same problem. Please let us know when this update is available.

**Comment by janrieke** [comment]
That `@Data` problem (not calling `super`) seems to be a different problem unrelated to `@SuperBuilder`. I'm getting the warning even without the `@SuperBuilder` annotation. Can you also confirm that, @kingraser?

**Comment by kingraser** [comment]
@janrieke 
Yes, I think you are right. The problem is unrelated to `@SuperBuilder` annotation.

I just wondering if we can have annotation like this `@Data(callSuper=true)` ,
so the code will be much more elegant than explicitly add `@EqualsAndHashCode(callSuper=true)` annotation.

**Comment by janrieke** [comment]
@kingraser: All PRs relevant to this issue are now merged. Could you give the [latest edge release](https://projectlombok.org/download-edge) a try to confirm this issue is fixed?

**Comment by kingraser** [comment]
@janrieke  
Thanks very much, I've just tried and I think the issue is fixed.
Another thing is that can We have a annotation like this `@Data(callSuper=true)`
So the `callSuper` can be used for both `@EqualsAndHashCode` and `@ToString`
Thanks for your dedicated work.

**Comment by janrieke** [comment]
You can configure lombok to always callSuper without a warning using `lombok.config`:

    lombok.equalsAndHashCode.callSuper=call

If this is not sufficient for you, there are already some other issue open on that topic, and there are some ideas related to it (e.g., https://github.com/rzwitserloot/lombok/wiki/FEATURE-IDEA:-@SuperToString). Please use the existing issues to discuss that topic.

This issue can be closed here.

**Comment by kingraser** [comment]
@janrieke  Thx very much
