### ISSUE TITLE
@NoArgsConstructor complains about unassignable final field in IDE

### ISSUE THREAD

**Issue by olivergierke** [rzwitserloot/lombok#1829]
With Lombok 1.18.2, the following class produces a compiler error on the `@NoArgsConstructor` annotation stating the final field `foo` cannot be assigned:

```java
@NoArgsConstructor(force = true)
class Sample {
  private final String foo = "bar";
}
```

On the command line the project compiles properly. Shouldn't the generated no-arg constructor simply skip the initialized, final field?

**Comment by janrieke** [comment]
Can confirm that this bug only affects Eclipse. Likely cause: `lombok.eclipse.handlers.HandleConstructor.fieldsNeedingExplicitDefaults()` does not check for initializing expression, but `lombok.javac.handlers.HandleConstructor.fieldsNeedingExplicitDefaults()` does (line 401).

**Comment by olivergierke** [comment]
Lovely, thanks for debugging it that deeply, @janrieke!
