### ISSUE TITLE
Add installer support for Genuitec Angular IDE

### ISSUE THREAD

**Issue by pgalbraith** [rzwitserloot/lombok#1830]
It seems that the Lombok installer won't recognize Angular IDE (the default vanilla install downloaded from Genuitec's website -- I tried on Windows 10), I'm guessing because it has its own executable name in Windows (angularide.exe).  Also by default it gets installed under the user's AppData folder rather than the standard Windows program files location, so that may be another hitch to get it auto-detected by the lombok installer.  Having this supported out of the box would be a nice feature.

**Comment by rspilker** [comment]
Thanks for the suggestion.
