### ISSUE TITLE
Improving @Wither implementation and making SpotBugs happy with it.

### ISSUE THREAD

**Issue by victorwss** [rzwitserloot/lombok#1832]
Hi, consider the following code:

```java
//import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Value;
import lombok.experimental.Wither;

@Value
@Wither
@Getter
@AllArgsConstructor
//@SuppressFBWarnings({"ES_COMPARING_PARAMETER_STRING_WITH_EQ", "RC_REF_COMPARISON"})
public class Example {
    String element1;
    Integer element2;
}
```

Currently (both with Lombok 1.18.2 and edge), [SpotBugs](https://github.com/spotbugs/spotbugs) complains about the wither methods, which accordingly to delombok are that:

```java
    @java.lang.SuppressWarnings("all")
    public Example withElement1(final String element1) {
        return this.element1 == element1 ? this : new Example(element1, this.element2);
    }

    @java.lang.SuppressWarnings("all")
    public Example withElement2(final Integer element2) {
        return this.element2 == element2 ? this : new Example(this.element1, element2);
    }
```

The reasons of the complaint are using `==` to compare `String`s (which SpotBugs complains as `ES_COMPARING_PARAMETER_STRING_WITH_EQ`) and using `==` to compare primitive wrappers (which SpotBugs complains as `RC_REF_COMPARISON`).

It's truth that those methods are annotated with `@java.lang.SuppressWarnings("all")`. However, since `@SuppressWarnings` have source-retention and SpotBugs works on bytecode, it can't be aware of it.

This is not a critical issue, since it can be easily workarounded by adding a few `@SuppressFBWarnings` on the class (those commented-out in the class above). However, this have the downside that it would disable some SpotBugs' analysis in the entire class instead of just in lombok generated methods.

I've created a minimal, complete and verifiable test case for that using gradle [**here**](https://github.com/victorwss/lombok-bug-tests/tree/master/equals-spotbugs-complains).

So, I'm looking for ideas of how could Lombok make SpotBugs happy without having to rely in the user adding `@SuppressFBWarnings`. And I have one:

* In those `@Wither` methods, `this.element1 == element1` could be replaced with `(this.element1 == null ? element1 == null : this.element1.equals(element1))`.

This approach also have the advantage that it avoids that `exampleInstance.withElement1("X").withElement1("X")` creates a new instance twice.

However, it have the downside that we don't know about the implementation of `element1`'s `equals` method, so using it might be is risky. There is several approaches about that:

* **A**: Lombok could simply assume the risk and call `equals` anyway. If the object does not have a safe and sane `equals` implementation, it would be not Lombok's problem. Most of the classes have sane and safe `equals` implementation, including those that inherits it directly from `java.lang.Object`. However, a few types like `java.net.URL` are notable for not having a safe and sane `equals` implementation. Also, using `equals` on mutable types may lead to some bad surprises.

* **B**: Selectively special-case the use of `equals` or `==`. The `equals` method would be used if `element1` is of some type that have a known safe and sane implementation of `equals` and is worth of it. This is the case of `String`, primitive wrappers, `java.time.*` types, `BigInteger`, `BigDecimal`, `OptionalInt`, `OptionalDouble`, `OptionalLong` and a few other types. The case of `Optional<X>` when `X` also have a safe and sane implementation of `equals` sould theoretically also use `equals`, but this is probably very hard to implement (possibly even undecidible), so it might be better to just fallback to `==`.

* **C**: Add some sort of field in the `@Wither` annotation to allow the programmer specify what to do: (1) Always create a new object regardless of anything; (2) avoid the creation of a new object if possible by testing the value with `==`; (3) avoid the creation of a new object if possible by testing the value with `equals`; (4) guess the best implementation using approach **B** and fallback to `==` and perhaps give a warning if it is too hard to determine.

**Comment by Maaartinus** [comment]
Just add this line to `lombok.config`
```
lombok.extern.findbugs.addSuppressFBWarnings=true
```
It's not the default as it leads to warnings for those not using FB/SB.

> This approach also have the advantage that it avoids that `exampleInstance.withElement1("X").withElement1("X")` creates a new instance twice.

Actually, it doesn't as `"X" == "X"` because of all string literals being interned. But I see what you mean, but the choice of `==` over `equals` was intentional. It avoids copying in some cases using a trivial fast test, while `equals` can be arbitrarily expensive.

I guess, I proposed once an option of `@Wither` covering cases 1-3, but nobody seemed to care. I guess, case 4 makes sense, too, and there should probably be an option making it to default. However, the possible gain is rather limited and nobody was willing to implement it. I'm also rather happy with how it works now...

**Comment by rspilker** [comment]
I would not go for a list of sane types, Resolution is already tricky, and we would never be able to expand the list if newer types are released.

There could be a list specified in `lombok.config` but that is also not so nice, and the resolution problem would still exist.

No solutions yet, just sharing my thoughts.

**Comment by rspilker** [comment]
[Why we closed this issue](https://github.com/rzwitserloot/lombok/wiki/ISSUES:-Why-we-close-issues-without-a-lot-of-explanation.)
