### ISSUE TITLE
IntelliJ doesn't understand ExtensionMethod

### ISSUE THREAD

**Issue by m-kuklinski** [rzwitserloot/lombok#1838]
When using @ExtensionMethod in IntelliJ with the Lombok plugin, IntelliJ marks all uses of generated method calls as errors as it does not recognize the method.

Compilation works fine - only IntelliJs... 'IntelliSense' doesn't.

**Comment by janrieke** [comment]
That's not a lombok bug, see mplushnikov/lombok-intellij-plugin#21.

**Comment by rspilker** [comment]
Correct.
