### ISSUE TITLE
Suggestion: A 'Trace' for logging method's input / output params

### ISSUE THREAD

**Issue by itay-keller** [rzwitserloot/lombok#1843]
Considering the following code:

```
@Slf4j
...

public String doX(String userName, double age){
   log.debug("userName: " + userName);
   log.debug("age: " + age);
   ....
  log.debug("return value will be: " + "something");
  return "something";
}
```

It will be nice to have an annotation that will replace all these logging.
Maybe something like that:

```
@Slf4j
...
@Trace
public String doX(String userName, double age){
   ....
  return "something";
}
```

With `input` / `output ` options.

**Comment by rspilker** [comment]
[Why we closed this issue](https://github.com/rzwitserloot/lombok/wiki/ISSUES:-Why-we-close-issues-without-a-lot-of-explanation.)
