### ISSUE TITLE
lombok.var conflicts with auto import in IDEA

### ISSUE THREAD

**Issue by nlwillia** [rzwitserloot/lombok#1845]
I have a Java 10 lombok (1.18.2) project in IDEA (2018.2.3) with the lombok plugin (latest) enabled.

IDEA is configured with `Editor | General | Auto Import | Add unambiguous imports on the fly` enabled.

With this configuration, if I type `for (var x`, what happens is that after I type the space before `x` it does an auto import check.  I'm not sure exactly what's going on at this point; it doesn't actually add an import for `lombok.var`, but in the process of whatever lookup it's doing, the space I typed is removed, so I end up with `for (varx` instead.  It's pretty frustrating, because it repeats if I backspace and try again so some cursor gymnastics are needed to type the correct thing.

I realized that I can prevent this by adding "lombok.var" to the `Exclude from import and completion` section, so there is a reasonable workaround.

I guess `lombok.var` is a feature for pre-Java 10 projects.  It's an unusual identifier.  (If I try to create my own "var" annotation, IDEA marks it as an error "'var' is a restricted local variable type and cannot be used for type declarations".)  It may not make sense to remove it yet, and I'm not sure whether this is a lombok plugin issue or just a weird interaction with an unexpected name, but I wanted to report the case since it took me a while to understand why this was happening and how to avoid it.

**Comment by rspilker** [comment]
You should probably report an issue in the [lombok-intellij-plugin  issue tracker](https://github.com/mplushnikov/lombok-intellij-plugin/issues).
