### ISSUE TITLE
@ToString should Support configuration keys: lombok.toString.callSuper

### ISSUE THREAD

**Issue by kingraser** [rzwitserloot/lombok#1846]
I used the latest edge version(1.18.3) and find out that there is no `lombok.toString.callSuper` key in lombok configuration

**Comment by rspilker** [comment]
`lombok.toString.callSuper does not exist, you need to specify that for each class separately. Since `toString` is meant for debugging purposes only, we don't find this a big problem.

**Comment by Maaartinus** [comment]
> Since `toString` is meant for debugging purposes only, we don't find this a big problem.

It's surely no big deal, but "debugging only" makes the config key more important, rather than less (as a course-grained setting is more probably acceptable).
