### ISSUE TITLE
Delombok does not support -p arg for javac >= 9

### ISSUE THREAD

**Issue by newcron** [rzwitserloot/lombok#1848]
Hi, 

thanks a lot for this project! It has helped the java community a lot. I don't want to go back to not using it anymore! 

When using Delombok with Java 9 or 10 on a project that has a module-info.java file, the build will fail.

I found this via the lombok-maven-plugin. It turns out that this happens because when delombok starts javac, it does not put itself into the modules path. As a result, javac will refuse to compile: 

* the _module-info.java_ itself
* and all classes using Lombok annotations

The fix - as pointed out on lombok's website - is to add lombok to the _module path_ via the `-p` arg. However, currently Delombok does not handle that behaviour on it's own, neither does it expose the `-p` arg via it's api, which would allow the lombok-maven-plugin to work with java 9 and module-info.java 

Thanks again for the great project!

**Comment by rzwitserloot** [comment]
docs also updated but that'll only go live when we push a stable release. lombok now adds itself as module, and you can now pass --module-path to delombok. Give it a spin in edge: https://projectlombok.org/download-edge
