### ISSUE TITLE
lombok Automation Generating toString method with the same name and parameter although I @Override toString method already

### ISSUE THREAD

**Issue by nerostamas** [rzwitserloot/lombok#1852]
Hello,

In my code using lombok, I override method toString (no parameter) with return an empty string (Because I don't want to show any information to be protected my data) but whenI I build my project, lombok also generating a same method toString (with no parameter) with all attributes information of class.
My override methon:
@Override
  public String toString() {
    return "This Is My Class{}";
  }

But when build have 2 methods:

public String toString() {
      return "myClassName.myClassNameBuilder(id=" + this.id + ", startDate=" + this.startDate + ", endDate=" + this.endDate + ")";
 }

public String toString() {
    return "This Is My Class{}";
  }

**Comment by Wecks** [comment]
@nerostamas It would be very useful to include few more details regarding the class you're testing. Defining your own `toString()` method will take priority over the version generated by Lombok.

You can find more details regarding this in [Lombok's @ToString description](https://projectlombok.org/features/ToString).
