### ISSUE TITLE
[NFR] enum class inherits static methods from implements interface

### ISSUE THREAD

**Issue by sdw2332** [rzwitserloot/lombok#1853]
usually, we will use customize field to index enum values instead of using ordinal field, like the code below.
```java
public interface IndexedEnum {
	Integer getIndex();
}

@AllArgsConstructor
public enum Alphabet implements IndexedEnum {
	A(0),
	B(1),
	;

	private final @Getter Integer index;
	
	public static Alphabet indexOf(Integer index) {
		for (Alphabet e : values()) {
			if (e.getIndex().equals(index)) {
				return e;
			}
		}
		return null;
	}

}
```

then, we have to write the same indexOf method in every enum class which implements IndexedEnum interface. it's too bad, right?
so, i think lombok can resolve it by adding a method annotation, @StaticHeritable, which is used to add interface static method to all implementation classes. like the code below.
```java
public interface IndexedEnum {
	
	Integer getIndex();
	
	/**
	 * get enum by index
	 * @param cls implementation enum class
	 * @param index index
	 * @return target enum
	 * @note first argument should be a Class with generic type T which extends IndexedEnum
	 */
	@StaticHeritable
	static <T extends Enum<?> & IndexedEnum>T indexOf(Class<T> cls, Integer index) {
		for (T e : cls.getEnumConstants()) {
			if (e.getIndex().equals(index)) {
				return e;
			}
		}
		return null;
	}
	
}

@AllArgsConstructor
public enum Alphabet implements IndexedEnum {
	A(0),
	B(1),
	;

	private final @Getter Integer index;

}
```
then lombok will generate indexOf method in Alphabet class like below.
```java
@AllArgsConstructor
public enum Alphabet implements IndexedEnum {
	A(0),
	B(1),
	;

	private final @Getter Integer index;
	
	/**
	 * get enum by index
	 * @param index index
	 * @return target enum
	 */
	@Generated("lombok")
	public static Alphabet indexOf(Integer index) {
		return IndexedEnum.indexOf(Alphabet.class, index);
	}

}
```

as you see, this annotation will help reduce a lot senseless repeative code. please consider implementing it, thanks.

**Comment by Maaartinus** [comment]
@sdw2332 I'm afraid, Lombok can't do `@StaticHeritable` because of [resolution](https://github.com/rzwitserloot/lombok/wiki/LOMBOK-CONCEPT:-Resolution).

> usually, we will use customize field to index enum values instead of using ordinal field

Lombok could do it, but all it saves is a one-liner method. Given the very high overhead for implementing Lombok features, I'm rather skeptical.

**Comment by sdw2332** [comment]
tks
