### ISSUE TITLE
@Slf4j annotation can not find log.info() method

### ISSUE THREAD

**Issue by sun-shining** [rzwitserloot/lombok#1855]
My idea version is 2017.3.4,i try to use Lombok plugin in my project.
My stepts are:
1 Install Plugin
2 Restart IDE
3 Enable Annotation Processing
4 Added  Lombok dependency to my project

butttt.... I still can not find info() method .Why???

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/8711496/45253364-80141200-b398-11e8-93ff-f3c0fa14df75.png">

![image](https://user-images.githubusercontent.com/8711496/45253325-fc5a2580-b397-11e8-89a1-233ed4de009a.png)

**Comment by rspilker** [comment]
You should probably report an issue in the [lombok-intellij-plugin  issue tracker](https://github.com/mplushnikov/lombok-intellij-plugin/issues).

**Comment by sun-shining** [comment]
lombok only is not enough,you need slf4j and log4j. Someone met the same question can see:https://stackoverflow.com/questions/12532339/no-appenders-could-be-found-for-loggerlog4j

**Comment by domainy** [comment]
@rspilker  I have created a demo for this issue using gradle and spring boot project from start.spring.io. Here is the repo - https://github.com/domainy/spring-lombok-issue

**Comment by luisrenva** [comment]
This is related to Intellij,

here the steps I followed to resolve it:

1.-  Enabled annotation processing for your project under File -> Settings -> Build, Execution, Deployment -> Compiler -> Annotation Processor
2.- I am not sure if this was required but I installed the plugin for lombok.
           - Install lombok plugin in IntelliJ IDE after that restart IDE. Screenshot (find this option in setting for the project then plugins)

**Comment by Cheshta1828** [comment]
I did everything mentioned ,still it did not work.
Then only resort was to try changing the version of JAVA. So if you guys are using JAVA,version 17 worked for me .do check yours.
And this is not for the installed versions,just check which version your project is using so that you can change it accordingly.
Hope it helps :)
Thanks.
