### ISSUE TITLE
@FieldNameConstants static String in inner class configuration

### ISSUE THREAD

**Issue by Streamline27** [rzwitserloot/lombok#1856]
Saw current version of @FieldNameConstants and the version described in [#1774.](https://github.com/rzwitserloot/lombok/issues/1774)
In project that I work on enum would not make much sense, because it is required to get field names as string. In case of enum the .name() method would be called every time. It is inconvenient an causes boilerplate.

My suggestion is that there should be separate annotation @FieldNameEnum 
Also configurable or default behaviour for @FieldNameConstants can be like this:

**Lombok:**
```
@FieldNameConstants
public class User {
    public String firstName;
    public String lastName;
}
```

**Vanilla:**
```
public class User {
    public String firstName;
    public String lastName;

    class Field {
        public static final String FIRST_NAME = "firstName";
        public static final String LAST_NAME = "lastName";

        private Field() {
        }
    }
}
```

So that the constants can be referenced in the following way.
```
    public static void main(String[] args) {
        String fieldName = User.Field.FIRST_NAME;
    }
```

When user needs to find property constant he will search it in autocomplete by prefix. In this configuration prefix is replaced with inner class, so that autocomplete is not polluted with extra suggestions.

**Comment by rspilker** [comment]
.... but the feature already works this way! Just try it (on the latest version, though, we did change how it works).

NB: The fields are named equal to the real field, so it'd be 'public static final firstName = "firstName";'. Also the generated class is called `Fields`, not `Field`. Other than that, `@FieldNameConstants` already works as described.

See https://github.com/rzwitserloot/lombok/blob/0038b48eeacac0389980902e65b4976dd5605c69/test/transform/resource/after-delombok/FieldNameConstantsBasic.java

**Comment by Streamline27** [comment]
Cool. Thanks for the answer. Btw Field would be a better name for that
imho. Would look more declarative 🙂
