### ISSUE TITLE
属性名生成的getter、setter错误

### ISSUE THREAD

**Issue by zcap** [rzwitserloot/lombok#1857]
针对属性名的形式为第一个字母为小写，第二个字母为大写的情况，Lombok所生成的getter、setter错误。
例如：
String aBc;
这个属性正确的getter、setter方法为：
public void setaBc(String aBc){……
public String getaBc(){……
但是Lombok所生成getter、setter方法为：
public void setABc(String aBc){……
public String getABc(String aBc){……
这样的结果会导致使用像Spring时会导致注入失败。。。望修复。

**Comment by NekoCaffeine** [comment]
Please speak English, thank you.
请用英文谢谢，别给中国的开发者丢人。
写两个注解可以设置字段名前缀。
并不是设计缺陷。

**Comment by Maaartinus** [comment]
Looks like a duplicate of #1661.

**Comment by zcap** [comment]
@NekoCaffeine 不好意思，英语不好。
非常崇拜想你这样英语强大的中国开发者，只是你的鄙视低端开发者、高傲自大性格，像我这样的一般人很不喜欢。
望你生活幸福。

**Comment by Maaartinus** [comment]
@zcap Note that the majority of people here understands no Chinese and all we can do with your posts is to run them through translate.google.com. Ideally, you'd do it yourself and post the translated text or both, so that not everybody has to do it.

**Comment by rzwitserloot** [comment]
Duplicate of #2693
