### ISSUE TITLE
Setup guide mentions 1.18.3 but this version not in central

### ISSUE THREAD

**Issue by mercer** [rzwitserloot/lombok#1859]
Searching maven central, I don't find 1.18.3.

https://search.maven.org/search?q=g:org.projectlombok%20AND%20a:lombok&core=gav

Currently, setup guide mentions this version

https://projectlombok.org/setup/gradle

![image](https://user-images.githubusercontent.com/95358/45371477-6589a500-b5f3-11e8-9f68-ac7da795fdcb.png)

**Comment by victorwss** [comment]
Traditionally, lombok release versions never ends in an odd number (not that I personally agree with that, but anyway, that is how it is today). It probably should be 1.18.2. The version 1.18.3 probably refers to the current [edge](https://projectlombok.org/download-edge) version.

**Comment by rspilker** [comment]
That is correct, we accidentally used the edge version on the website.

**Comment by rzwitserloot** [comment]
Yeah the site's been saying that since monday evening, my bad, published the edge variant of the website. Fixed.
