### ISSUE TITLE
Eclipse: Provide wrong context assist menu when enable lombok

### ISSUE THREAD

**Issue by yaohaizh** [rzwitserloot/lombok#1860]
See scrennshot. 

Eclipse Version: Photon Release (4.8.0)
Build id: 20180619-1200

1. Install lombok tools for Eclipse IDE: https://projectlombok.org/setup/eclipse
2. Create a class, add lombok annotation `@Data`, `@ToString` to the class 
3. Put cursor to the `@ToString`, trigger content assist

There are some assist menu should be provided here.

![untitled](https://user-images.githubusercontent.com/17268517/45465007-c45f3380-b745-11e8-9400-9f45ee58843e.png)

**Comment by rspilker** [comment]
The problem is that Eclipse doesn't know about generated code. All generated code is placed at the location of the annotation, so that 'Open Declaration (F3)' jumps to the right location.

I don't think it is worth putting a lot of effort in fixing this.
