### ISSUE TITLE
No args constructor is already defined in class

### ISSUE THREAD

**Issue by godpit** [rzwitserloot/lombok#1863]
```java
@Data
@Accessors(chain = true)
@NoArgsConstructor
@Entity(value = "emoji", noClassnameStored = true)
@Indexes({@Index("userId"), @Index("emojiId")})
public class Emoji implements Serializable {
       ......

public Emoji(ObjectId emojiId, String userId, int type, String url, String msgId, String msg, String roomJid,
                 long createTime) {
        this.emojiId = emojiId;
        this.userId = userId;
        this.type = type;
        this.url = url;
        this.msgId = msgId;
        this.msg = msg;
        this.roomJid = roomJid;
        this.createTime = createTime;
    }
}
```

Error:(16, 1) java: constructor Emoji() is already defined in class cn.xyz.mianshi.vo.Emoji with 1.16.22.

how to solve it?

**Comment by Maaartinus** [comment]
I'd suggest to post the real code first. I doubt, there's `@DaTa` written like this. Please copy&paste your code and enclose it in triple backquotes like this ` ``` code ``` `.

AFAIK, `@Data` implies `@NoArgsConstructor`, so you can simply remove the latter. However, it should work as is and it does for me (Lombok v1.18.0  in Eclipse). There may be a bug in the older version.

You can also remove your lengthy constructor and use `@AllArgsConstructor` instead, assuming it really covers all fields.

**Comment by rspilker** [comment]
You should update to the latest version of Lombok: 1.18.2
