### ISSUE TITLE
Add @Supplied annotation for method parameters [Suggestion]

### ISSUE THREAD

**Issue by JarvisCraft** [rzwitserloot/lombok#1869]
`@Supplied` annotation may be added for method parameters so that there is an equivalent of a method which replaces parameter `T arg` with `Supplier<T> arg` whose `get()` method is invoked when the value of a field is needed.
For example (logging seams to be the most obvoius one)
```Java
// in class Logger
void debug(final String message) {
    if (debug) log(LogLevel.DEBUG, message);
}
```
call like `logger.debug("Manager set to ".concat(manager.toString())); // manager.toString() is a heavy operation` would perform a heavy operation of creating a `String` object although this may be useless if `debug` in `logger` is set to `false`.
Instead Lombok would generate
```Java
// in class Logger
void debug(final Supplier<String> message) {
    if (debug) log(LogLevel.DEBUG, message.get());
}
```
so that the developer could use `logger.debug(() -> "Manager set to ".concat(manager.toString())); // manager.toString() is a heavy operation` which (thanks to lambda) would not allocate and calculate new `String`s unless they are needed.

As for annotation paramaters there would be some which may be helpful in order to exand this feature's functionalitity:
- `boolean` `keepDefault` or `keepBasic` or `keepExact` etc. — whether lombok should keep method without supplier or not (default value is to be discussed)
- `String` `generatedName` — if `keepDefault` is to `true` then which names to use for generated method
- `boolean` `cache` — whether the value should be cached once got from supplier or each refererence to the field should be replaced with `Supplier#get()` (defaults to `true` of course). It's to be discussed whether this feature is required or not as the `false`-case is a really specific one.
- `boolean` `allowExceptions` whether to use default `Supplier<T>` or some equivalent which has a signature of `T get() throws Throwable` so that the developer should not catch exceptions in lambda body. This should be discussed as defult JRE does not have such class and so Lombok has to generate its own, probably for each class, otherwise, if generating one single class for the whole application, the developer should decide how to name it in `lombok.config` and/or annotation parameter (e.g. `generatedSupplierClassName`)

**Comment by rspilker** [comment]
[Why we closed this issue](https://github.com/rzwitserloot/lombok/wiki/ISSUES:-Why-we-close-issues-without-a-lot-of-explanation.)

**Comment by rspilker** [comment]
I'm not saying it is a bad idea per se, it's just that I don't see this happening any time soon. Also, we will not accept pull requests, because of the maintenance load.
