### ISSUE TITLE
if use chain setter writeMethod is null  

### ISSUE THREAD

**Issue by donaldfischer** [rzwitserloot/lombok#1874]
```
        BeanInfo beanInfo = Introspector.getBeanInfo(Foo.class);
        PropertyDescriptor[] propertyDescriptors = beanInfo.getPropertyDescriptors();
        for (PropertyDescriptor propertyDescriptor : propertyDescriptors) {
            Method writeMethod = propertyDescriptor.getWriteMethod(); // writeMethod is null
        }
```

_Originally posted by @BerryWang1996 in https://github.com/rzwitserloot/lombok/issues/1648#issuecomment-379528556_

**Comment by Maaartinus** [comment]
This is a javabeans crapspec problem, which only allows `void` setters. If you want `this`-returning setters, then you can't have javabeans compatibility and *there's nothing Lombok could do about it*.

In theory, you could generate two setters, but then you'd have to call them differently and having two setters per field is simply too bad.

**Comment by donaldfischer** [comment]
> This is a javabeans crapspec problem, which only allows `void` setters. If you want `this`-returning setters, then you can't have javabeans compatibility and _there's nothing Lombok could do about it_.
> 
> In theory, you could generate two setters, but then you'd have to call them differently and having two setters per field is simply too bad.

all right
