### ISSUE TITLE
Sonar Warning on .hashCode()

### ISSUE THREAD

**Issue by beckysargent** [rzwitserloot/lombok#1876]
Method .hashCode() stores return result in local before immediately returning it.

This method stores the return result in a local variable, and then immediately returns the local variable. It would be simpler just to return the value that is assigned to the local variable, directly.

**Comment by rspilker** [comment]
You should configure sonar and lombok not to check generated code. I'm on my phone so I don't have the right settings available here.

The warning doesn't make sense in generated code, since the compiler emits the same bytecode
