### ISSUE TITLE
Using lombok.Builder in src/test/java doesn't work with JDK 11 + Gradle

### ISSUE THREAD

**Issue by seratch** [rzwitserloot/lombok#1877]
I found that a class using `lombok.Builder` in test scope is not readable when using JDK 11. Interestingly, the failure doesn't happen when you place the class under `src/main/java`.

I've created a minimum working example to reproduce the issue and ran it in TravisCI environment.

* https://github.com/seratch/lombok-jdk11
* https://travis-ci.org/seratch/lombok-jdk11/builds/434868142

```
* What went wrong:
Execution failed for task ':test'.
> failed to read class file /home/travis/build/seratch/lombok-jdk11/build/classes/java/test/example/Sample$SampleBuilder.class
```

<img width="1184" alt="screen shot 2018-09-29 at 10 13 38" src="https://user-images.githubusercontent.com/19658/46239215-5dda4680-c3d0-11e8-89ec-b0becdcba3be.png">

**Comment by rspilker** [comment]
For me it is not clear:
- If it is only `@Builder(toBuilder=true)` or that `@Builder` also has problems
- If this problem is new in JDK11

**Comment by seratch** [comment]
@rspilker 

>If it is only @Builder(toBuilder=true) or that @Builder also has problems

No matter whether the `toBuilder` attribute is specified, the error occurs. Here is the result: https://travis-ci.org/seratch/lombok-jdk11/builds/438861029

>If this problem is new in JDK11

Yes, it is. Please refer to the TravisCI build results.

**Comment by rspilker** [comment]
I have no clue. Is this a gradle specific problem?

**Comment by rspilker** [comment]
I don't expect that you know how to do the equivalent in maven.

**Comment by rspilker** [comment]
Did you also try other lombok annotations, like `@Getter`?

**Comment by seratch** [comment]
As far as I know, the issue never happens with other annotations. That's specific to `@Builder`.

**Comment by seratch** [comment]
@rspilker It seems you're right. The problem is specific to (Open|Oracle)JDK11 + Gradle. https://travis-ci.org/seratch/lombok-jdk11/builds/441973023

**Comment by rspilker** [comment]
We think we've found the source of the problems.

**Comment by rspilker** [comment]
I think it does have something to do with annotation processors that behave differently when compiling test code. See also https://github.com/tbroyer/gradle-errorprone-plugin/issues/2

**Comment by rspilker** [comment]
I cannot reproduce the problem in maven.

Can you also modify the build.gradle file as suggested on https://projectlombok.org/setup/gradle#gradle-v212-and-up

**Comment by miroslavhornak** [comment]
What worked for me was to remove the "annotationProcessor = " part(s) from the build.gradle for both mapstruct and the lombok ... and simply include those as the compile dependencies (runnning Oracle JDK 11.0.1 (java version "11.0.1" 2018-10-16 LTS)) ... :
compile "org.projectlombok:lombok:1.18.4"
compile "org.mapstruct:mapstruct:1.3.0.Beta2"

**Comment by lgwozniak** [comment]
I met same problem. It's occure on maven 3.3.9+ when i migrate to junit5.

**Comment by wreulicke** [comment]
This issue is project-specific problem.
I wrote PR for example.

https://github.com/seratch/lombok-jdk11/pull/1

**Comment by wreulicke** [comment]
I read this issue again.
This error is gradle error for test.
This is not issue related to lombok.

Gradle uses ASM. but, gradle wrapper in this example is old.
So, this error occurred.

Gradle 5.x supports Java 11.
Example should update gradle.

> * What went wrong:
> Execution failed for task ':test'.
> > failed to read class file /home/travis/build/seratch/lombok-jdk11/build/classes/java/test/example/Sample$SampleBuilder.class

**Comment by seratch** [comment]
@wreulicke Thank you for sharing the solution for this. I'm happy to hear Gradle 5 doesn't have this issue. I believe we can close this issue. Thanks again.
