### ISSUE TITLE
Lombok not working with Maven

### ISSUE THREAD

**Issue by MrPencilBox** [rzwitserloot/lombok#1880]
Hello! My project can't compile with lombok. 

Dependency:
```xml
      <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.6.6</version>
            <scope>provided</scope>
       </dependency>
```

Maven Compiler Plugin:
```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
```
I got errors like this

[ERROR] /B:/DMS/MobArena/MobArena/src/main/java/yt/dms/mobarena/arena/MaArena.java:[90,37] cannot find symbol
  symbol: method getSpawnersList()
[ERROR] /B:/DMS/MobArena/MobArena/src/main/java/yt/dms/mobarena/arena/MaArena.java:[94,77] cannot find symbol

*it's lines with annotations*

**Comment by rspilker** [comment]
Version 1.6.6 never existed. I suggest using 1.18.2.
