### ISSUE TITLE
Compiler error with lazy @Getter and Error Prone

### ISSUE THREAD

**Issue by msridhar** [rzwitserloot/lombok#1881]
A small-ish repro is at https://github.com/msridhar/lombok-ep-minimal.

If you clone and run `./gradlew compileJava` you get:

```
src/main/java/lomboktest/Test.java:14: error: incompatible types: String cannot be converted to Map<String,String>
  @Getter(lazy = true)
  ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error
```

But if you remove the Error Prone stuff from `build.gradle` (the first three lines and line 21) it compiles fine.

This may be related to the use of the JDK 9 compiler by Error Prone; [This StackOverflow question](https://stackoverflow.com/questions/52101387/incompatible-types-error-using-lombok-getterlazy-true-with-java-10) around JDK 10 reported a similar issue.

**Comment by msridhar** [comment]
For easier reference, here is the code.  `HasId.java`:

```java
package lomboktest;
public interface HasId {
  String getId();
}
```

`Test.java`:
```java
package lomboktest;

import com.google.common.collect.ImmutableMap;
import lombok.Getter;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.locks.StampedLock;

public abstract class Test implements HasId {
  @Getter(lazy = true)
  private final Inner1 i1 =
      new Inner1(getId(), new Inner2(ImmutableMap.of("fff", getId())));
  static class Inner1 {
    private final StampedLock s;
    private static final ConcurrentHashMap<String, StampedLock> m = new ConcurrentHashMap<>();
    private final Inner2 i2;
    public Inner1(String s2, Inner2 i2) {
      this.i2 = i2;
      this.s = m.computeIfAbsent(s2, k -> new StampedLock());
    }
  }
  static class Inner2 {
    Inner2(Map<String,String> m) {}
  }
}
```

**Comment by rspilker** [comment]
In this case, I suspect that adding generic parameters to the ImmutableMap factory method fixes your problems.

`new Inner1(getId(), new Inner2(ImmutableMap.<String,String>of("fff", getId())));`

My suggestion for lazy getters that cause problems is to move the initialization to a private (if possible static) method.


```java
public abstract class Test implements HasId {
  @Getter(lazy = true)
  private final Inner1 i1 = initializeI1();

  private Inner1 initializeI1() {
    return new Inner1(getId(), new Inner2(ImmutableMap.of("fff", getId())));
  }

  static class Inner1 {
    private final StampedLock s;
    private static final ConcurrentHashMap<String, StampedLock> m = new ConcurrentHashMap<>();
    private final Inner2 i2;
    public Inner1(String s2, Inner2 i2) {
      this.i2 = i2;
      this.s = m.computeIfAbsent(s2, k -> new StampedLock());
    }
  }
  static class Inner2 {
    Inner2(Map<String,String> m) {}
  }
}
```

**Comment by msridhar** [comment]
Thanks a lot for the suggested workaround!  Is this an issue that is difficult to fix within Lombok?  I ask because I work on a developer tools team and if this is hard to fix within Lombok, we'll have to do some documentation / developer education in order to let other devs know about the problem.  Is this issue with lazy getters already documented somewhere?

**Comment by rspilker** [comment]
Unfortunately we do not know what the cause is.

**Comment by rspilker** [comment]
The next release, the documentation contains the recommendation above.
