### ISSUE TITLE
@Getter not work when I compile (Intellij IDEA)

### ISSUE THREAD

**Issue by x9nico** [rzwitserloot/lombok#1884]
Hi, when I build my module, on Intellij IDEA, it is not finding the symbol on my Getter's method.

**Comment by ambujmehra** [comment]
need more context here, what I can think of right now is enable Annotation processors in IntelliJ
Build, Execution, Deployment > Compiler > Annotation Processors.
Hope it helps

**Comment by MCMicS** [comment]
Do you use modules?
There are Problems with modules (module-info.java) within the idea plugin.
