### ISSUE TITLE
Current edge 1.18.3 breaks toBuilder on Singular fields with wildcards

### ISSUE THREAD

**Issue by janrieke** [rzwitserloot/lombok#1885]
The following code compiles with 1.18.2, but not with the current 1.18.3 snapshot (downloaded today) today), using Java 8.

    @Builder(toBuilder = true)
    public class ExampleToBuilder {
        @Singular
        private List<?> objects;
    }

Eclipse says

    Wildcard is not allowed at this location

javac says:

    method emptyList in class java.util.Collections cannot be applied to given types;
    [ERROR]   required: no arguments
    [ERROR]   found: no arguments
    [ERROR]   reason: explicit type argument ? does not conform to declared bound(s) java.lang.Object"

I think 6a42bcc and af55bd0 broke it, but I have not checked that.

**Comment by rspilker** [comment]
Although you are right about the breaking backwards compatibility, I don't think it is a common case. It is a bit strange to add elements to a wildcard collections.

That said, we can support this by in the builder always use the lower bound, both for the field and the methods.

**Comment by janrieke** [comment]
I created PR #1898 that should fix this.
