### ISSUE TITLE
Improvement on @Builder annotation

### ISSUE THREAD

**Issue by rafael-andrade** [rzwitserloot/lombok#1886]
Could you guys automatically add `@NoArgsConstructor` when the annotation of `@Builder` is alone on class? As it is for example with `@Data` that already has `@RequiredArgsContructor`.

**Comment by rafael-andrade** [comment]
I was getting a problem in my application cause I was not using `@NoArgsConstructor` with `@Builder`. And reading `https://projectlombok.org/features/Builder` and others things about Builder patterns I thought that when you call `YouClass.builder()` the `builder()` method would instantiate a new class with no args.

**Comment by Maaartinus** [comment]
@rafael-andrade 
> I thought that when you call `YouClass.builder()` the `builder()` method would instantiate a new class with no args.

Taken literally, yes. `YouClass.builder()` returns `new `YouClassBuilder()`, i.e., a new builder created using the no-args ctor.

That's probably not what you mean, but nobody knows what you mean. AFAIK `@Builder` needs an all-args ctor and it adds it, too.

If anything doesn't work for you, give us an [example](http://sscce.org/).
