### ISSUE TITLE
@Data creates private default constructor if there are any other constructors

### ISSUE THREAD

**Issue by Selindek** [rzwitserloot/lombok#1887]
```java
@Data
public class Parent {
  private String s;

  public Parent(String s) {
    this.s = s;
  }
}
```
In the above example I cannot use 
Parent p= new Parent();

because the generated default constructor's visibility is private.

If there is no manually created constructor then the visibility of the default constructor is public, as it's expected.

**Comment by laur89** [comment]
Add `@NoArgsConstructor` _before_ `@Data` to have public default one.

**Comment by Selindek** [comment]
> Add `@NoArgsConstructor` _before_ `@Data` to have public default one.

Yep. That works, as a quick fix, thank you.

But I still believe that the order of the annotations shouldn't affect their behaviour.

**Comment by rspilker** [comment]
What version are you using?

**Comment by rspilker** [comment]
No response from reporter

[Why we closed this issue](https://github.com/rzwitserloot/lombok/wiki/ISSUES:-Why-we-close-issues-without-a-lot-of-explanation.)
