### ISSUE TITLE
Feature request: Allow toString to accept a format template.

### ISSUE THREAD

**Issue by jcalcote** [rzwitserloot/lombok#1891]
It would be really nice if @toString could be configured with a display template and field separator as in, for example:

lombok.config:
    lombok.toString.template="%classname={%fieldlist}"
    lombok.toString.fieldSeparator="; "

**Comment by rspilker** [comment]
https://github.com/rzwitserloot/lombok/wiki/FEATURE-IDEA:-@SuperToString
