### ISSUE TITLE
Can't install lombok to Spring tool 4 on macos

### ISSUE THREAD

**Issue by wzlee** [rzwitserloot/lombok#1892]
The install dialog can't search the spring tool 4, but STS 3.9.x disappear in it.
![image](https://user-images.githubusercontent.com/4182865/46794435-5b85ce00-cd7a-11e8-8e15-728eaaae2dd5.png)

![image](https://user-images.githubusercontent.com/4182865/46794341-37c28800-cd7a-11e8-8253-8b7b20945ac6.png)

**Comment by rzwitserloot** [comment]
Should be fixed in v1.18.4. If not, please file a new bug.
