### ISSUE TITLE
Feature request:Allow @SuperBuilder and @XConstructor all exist

### ISSUE THREAD

**Issue by liudaomanbu** [rzwitserloot/lombok#1893]
I use the lombok 1.18.2
I am very happy about @SuperBuilder,this annotation is very good for super class fields question.

But sometimes,the super class may be extends by external class.
so,i want to use @AllArgsConstructor in the super class to add a super constructor that not acccept a builder.
If not,the external child class must use the @SuperBuilder or implements build Pattern by self.

For example:
![image](https://user-images.githubusercontent.com/21155988/46843632-61c18c00-ce06-11e8-911e-2d05622c5ad2.png)

I think that @AllArgsConstructor in super class just added an other constructor.
The child class also use the old super constructor of accept builder.
Why the child class has the error?

I want to get the result like this.
![image](https://user-images.githubusercontent.com/21155988/46844392-6471b080-ce09-11e8-9fe1-7403408257c3.png)

What are the difficulties?

**Comment by liudaomanbu** [comment]
> I cannot reproduce this. Eclipse and maven/javac compile, both 1.18.2 and the current 1.18.3 work. I'm quite sure that this is an IntelliJ plugin problem. Please check whether it compiles when building with javac.
> If it also does not compile with javac, could you provide a minimal example and push it to a Github repository?
> 
> PS: The problem is _not_ a second additional constructor, the problem is that something from `Child` tries to call the default constructor of `Parent` (which doesn't exist any more because of the `@AllArgsConstructor`). And the code generated by `@SuperBuilder` never calls a default constructor. My suggestion is that because of the lack of `@SuperBuilder` support in the IntelliJ plugin, it does not generate the builder-based constructor. Thus, a default constructor in `Parent` is required to instantiate `Child`, and you do not have that.

Thank you for your answer.
You are right.
It it a IntelliJ plugin problem. 
It compile error,but execute success.
Maybe it also because idea plugin can't support @AllArgsConstructor

**Comment by liudaomanbu** [comment]
This issue should transform to idea lombok plugin.

**Comment by rzwitserloot** [comment]
yup, file this one with the [lombok-intellij](https://github.com/mplushnikov/lombok-intellij-plugin) plugin.
