### ISSUE TITLE
Bug:idea plugin can't support @SuperBuilder

### ISSUE THREAD

**Issue by liudaomanbu** [rzwitserloot/lombok#1894]
```
@SuperBuilder
public abstract class Parent {
  Number number;
}
```
```
@SuperBuilder
public class Child extends Parent {

  @Singular
  ImmutableList<Long> ids;
}
```
![image](https://user-images.githubusercontent.com/21155988/46845685-05af3580-ce0f-11e8-8341-484265a29465.png)
![image](https://user-images.githubusercontent.com/21155988/46845697-0e077080-ce0f-11e8-98ce-0743a1ea12e3.png)
compile error,excute success.

**Comment by janrieke** [comment]
It's a problem of the IntelliJ plugin, and there is already an issue for it: mplushnikov/lombok-intellij-plugin#513

**Comment by wichy13-js** [comment]
<img width="785" alt="Screen Shot 2562-10-12 at 08 19 13" src="https://user-images.githubusercontent.com/54887481/66692535-8e360f80-ecc9-11e9-9451-0a29ee5db577.png">
https://github.com/mplushnikov/lombok-intellij-plugin

**Comment by janrieke** [comment]
I think you want to say "the IntelliJ plugin finally supports `@SuperBuilder`". Yeah! :clap: :smiley:

**Comment by liudaomanbu** [comment]
> I think you want to say "the IntelliJ plugin finally supports `@SuperBuilder`". Yeah! 👏 😃

👍

**Comment by janrieke** [comment]
Ah, you did say it, just my Github app did not show the image. :expressionless:

**Comment by wichy13** [comment]
> Ah, you did say it, just my Github app did not show the image. 😑

I saw the image. 
Yes, the Last version (0.27) plugin supports `@SuperBuilder`.
