### ISSUE TITLE
Bug:@SuperBuilder can't support @NonNull

### ISSUE THREAD

**Issue by liudaomanbu** [rzwitserloot/lombok#1895]
```
@SuperBuilder
public abstract class Parent {
  @NonNull
  Number number;
}
```
```
@SuperBuilder
public class Child extends Parent {

  @Singular
  ImmutableList<Long> ids;
}
```
![image](https://user-images.githubusercontent.com/21155988/46845925-18763a00-ce10-11e8-8f5c-35e1df7d6e79.png)
compile error

**Comment by janrieke** [comment]
Duplicate of #1800 and already fixed in the current edge release.
