### ISSUE TITLE
Code compiling with JDK 8 does not compile with JDK 11

### ISSUE THREAD

**Issue by jrmyr** [rzwitserloot/lombok#1896]
Hello!

Now, that JDK 11 is released I want to use it. :-)
While migrating a project I face a problem with the lombok `@Builder` annotation. With Java 8, it compiles, but the same code fails to compile with Java 11.
Please see my captured console output here:
![image](https://user-images.githubusercontent.com/11019052/46852748-45205680-cdfc-11e8-9c75-df119206eb9c.png)

I checked the open issues and searched the web. Even if I found things sounding similar, I cannot say that they are really the same so I open a dedicated issue. Please tell me if I overlooked or misunderstood something.

**Comment by rspilker** [comment]
Without source code, we cannot fix this.

[Why we closed this issue](https://github.com/rzwitserloot/lombok/wiki/ISSUES:-Why-we-close-issues-without-a-lot-of-explanation.)
