### ISSUE TITLE
Add a copy like constructor to the @lombok.Builder()

### ISSUE THREAD

**Issue by Zavster** [rzwitserloot/lombok#1897]
It is often useful to be able to update an immutable object and change one field, which obviously requires that a new instance be created. It would be useful to use the builder to do this. For example, something as follows with the 'with()' method applies all values from the source object and therefore we can update just the field we want to affect. Make sense?

```java
var value = getAccount();
var update = Account.builder().with(value).name("John Doe").build();
```

**Comment by Zavster** [comment]
Ah, my bad, should have read the docs more closely.  Thanks!

**Comment by Maaartinus** [comment]
@Zavster In case you want to change a single field, `@Wither` is the way to go.

**Comment by randakar** [comment]
This already exists. The Builder annotation has a "toBuilder" flag. Set
that to true, and a toBuilder() method is generated on the objects that can
be used for this.

Op vr 12 okt. 2018 15:18 schreef Xavier Witdouck <notifications@github.com>:
