### ISSUE TITLE
Support setter name prefixes and annotate generate methods in @Builder

### ISSUE THREAD

**Issue by mmanciop** [rzwitserloot/lombok#1899]
First of all, let me state just how awesome Lombok is: it's very, very awesome :-)

I recently fell in love with `@Builder` and started using is massively in conjunction with Jackson, and I think there are two things that could change to make `@Builder` even better:

1. Allowing to set a desired prefix for the setter names: in many codebases there is a convention to use `withXXX` as setter names on builders, so much that the default value of [JsonPOJOBuilder](https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/annotation/JsonPOJOBuilder.html)'s `prefix` property is `with`.
2. Allow to specify annotations for the setter methods generated by Lombok. The usecase here is, for example, `@JsonAnySetter`, which must be annotated on the setter method on the Builder class. Lombok currently won't allow to specify methods with the same names as those automatically generated for `@Builder`, so the only workaround I found so far is the following:

<pre>
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import java.util.Map;
import javax.validation.constraints.NotNull;
import lombok.Builder;
import lombok.Singular;
import lombok.Value;

@Value
@Builder(builderClassName = "Builder", toBuilder = true)
@JsonDeserialize(builder = ApplicationSettings.Builder.class)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class MyObject {

  @Singular
  @NotNull
  @JsonIgnore
  private final Map<String, Object> additionalProperties;

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return unmodifiableMap(additionalProperties);
  }

  @JsonPOJOBuilder(withPrefix = "")
  @JsonIgnoreProperties(ignoreUnknown = true)
  public static class Builder {

    /*
     * Overload for #additionalProperty to accommodate the @JsonAnySetter.
     * We keep it package-private to hide this work-around from the rest of the codebase.
     */
    @JsonAnySetter
    Builder addAdditionalProperty(final String key, final Object value) {
      return additionalProperty(key, value);
    }

  }

}
</pre>
I would imagine that a good way to support annotation of methods generated by `@Builder` would be to:
* Allow the builder class to be declared as an interface or, even better, abstract (to be then turned into full class by Lombok, or a BuilderImpl class to be generated from it)
* Declare the (abstract) methods on the builder interface/abstract class with all the fancy annotations, but without the need of actually providing an implementation
* Profit!

**Comment by rspilker** [comment]
Regarding copying annotations to the builder, we have "copyable annotations" in the next release, please try our [edge release](https://projectlombok.org/download-edge).

Sorry, withXXX is for immutables that return a copy with one field different. We have `@Wither` for that.
[Why we closed this issue](https://github.com/rzwitserloot/lombok/wiki/ISSUES:-Why-we-close-issues-without-a-lot-of-explanation.)

**Comment by rspilker** [comment]
Sorry for the misunderstanding, I only mentioned `@Wither` as an example of a "with"-prefix that returns an immutable copy, not as a solution for unmarshalling.

It is possible to generate a no-args constructor that provide empty default values using `@NoArgsConstructor(force=true)`
