### ISSUE TITLE
Bug:staticConstructor of @Value Invalid when @Builder exist

### ISSUE THREAD

**Issue by liudaomanbu** [rzwitserloot/lombok#1900]
version:1.18.2

![image](https://user-images.githubusercontent.com/21155988/46908634-2c2cb800-cf58-11e8-8abf-f0fb115cf102.png)
![image](https://user-images.githubusercontent.com/21155988/46908639-38b11080-cf58-11e8-80fb-17de02247546.png)
the staticConstructor  not in result.
I think this is a bug.
Why builder can't exist with staticConstructor?

**Comment by rzwitserloot** [comment]
Because it can't. What's the point? You already have a builder, use that.
