### ISSUE TITLE
Information Request: @Delegate

### ISSUE THREAD

**Issue by ameisen** [rzwitserloot/lombok#1903]
Second-to-last one for the day...

I know that `@Delegate` is marked as `@Deprecated` and is expected to be removed.

There have been a _ton_ of times in both my personal libraries and at work where `@Delegate` would have been useful but I am avoiding using it because I expect it to be removed. It serves a purpose that is often painful to do otherwise - our libraries (which span many teams) often throw around `String`s, `Long`s, and other types which I have been wanting to give explicit type aliases with additional functionality, but I do not want to have to re-implement _every single member method_ (had to avoid saying member function, the C++ is leaking) by hand. `@Delegate` would have been incredibly useful, but without knowing what's going on with it, I cannot bring myself to use it as it would become a maintenance hazard.

If it is removed, can it instead be moved to either a 'deprecated' library that we could alternatively include, or a separate package (like `lombok.deprecated.Delegate`)? This would enable me to actually use it, continually upgrade lombok in the future, and not have downstream projects break horribly, potentially. I don't want to fork lombok to force the feature to stay added, as that is another maintenance issue.

**Comment by rzwitserloot** [comment]
We love `@Delegate` but we're swamped with just replying to issues, implementing PRs, dealing with the fallout from JDK9+, and in general wanting to do some abstraction on resolution-requiring features before tackling `@Delegate` properly.

However, where did you get the idea that we're removing it?

Just read the delegate note: We've moved it to 'experimental' to reflect its status: IF it is broken, we're not going to hold off on a release until we fix it. It will not be deleted.

**Comment by ameisen** [comment]
@rzwitserloot 

You just made my day (well, evening, I suppose) with it not being deleted, just staying experimental. 

I suppose it was due to both my reading of [https://projectlombok.org/features/experimental/Delegate](this) suggesting that it may be dropped, coupled with the `@Deprecated` annotation that it has.
