### ISSUE TITLE
FieldNameConstants has not prefix in lombok 18.3

### ISSUE THREAD

**Issue by daniel-exceed** [rzwitserloot/lombok#1906]
I'm using lomok 18.2 and enjoying the FieldNameConstants and i set my own convenient prefix, now i tried the edge build of 18.3 and the annotation lacks the prefix field, so it breaks my code
i know this feature  has been redesigned but is it possible to bring it back?

**Comment by rzwitserloot** [comment]
We redesigned how FNC works in 18.3. The prefix thing is just gone, and we have no intention of bringing it back. 18.4 will be released soon and then you get to see the docs. Until then...

https://github.com/rzwitserloot/lombok/blob/0038b48eeacac0389980902e65b4976dd5605c69/website/templates/features/experimental/FieldNameConstants.html
