### ISSUE TITLE
@Builder annotation causes compile error with Java 11

### ISSUE THREAD

**Issue by jrmyr** [rzwitserloot/lombok#1907]
Hello!

My code using the `@Builder` annotation does not compile with Java 11 (or Java 10) while it compiles properly with Java 8.
As issue #1896 was closed and I could not reopen it, I create this issue to provide the code; please see here: https://github.com/jrmyr/lombokbuilder.

To reproduce the problem, just clone the repo and execute a simple `gradle compileJava` in it. Depending on the Java version in use, it will pass (8) or fail (10, 11). Tested on Mac.

Please tell me if you need more info.
Thanks.

**Comment by rspilker** [comment]
Can you try to sign the result of the build method to a local variable first?

**Comment by rspilker** [comment]
I don't know if we can configure the issue tracker to allow reopening by the reporter.

**Comment by rspilker** [comment]
I just found out that even the reporter cannot open an issues that they didn't close themselves.

**Comment by jrmyr** [comment]
> I just found out that even the reporter cannot open an issues that they didn't close themselves.

No problem. Creating a new one and linking the old one is not an issue for me.

> Can you try to assign the result of the build method to a local variable first?

I tried this but the behavior did not change. I updated the [github repo](https://github.com/jrmyr/lombokbuilder) with my changes.
Please tell me should I miss and/or misunderstand something.

**Comment by jrmyr** [comment]
It seems this issue is similar to #1877.
I checked with maven and with maven the project compiles under Java 8, 10 and 11.
So, seems gradle-specific.

**Comment by rzwitserloot** [comment]
Here's a real simple test case for it:

	import lombok.Builder;
	import lombok.Getter;

	class BuilderOnConstructor {
		@Builder
		BuilderOnConstructor(int a, boolean b) {}
	
		static class BuilderOnConstructorBuilder {
			void from() {
				a(x()).b(y());
			}
		}
	
		static int x() {
			return 0;
		}
	
		static boolean y() {
			return true;
		}
	}

**Comment by rzwitserloot** [comment]
confirmed failure with error: `BuilderOnConstructor.java:2: error: incompatible types: boolean cannot be converted to int` on java9, 10, and 11. Not on 8.

**Comment by rzwitserloot** [comment]
NB: Just plain 'javac' is enough, you don't need gradle or maven to be involved. The chaining is key; if you write `var x = a(x()); x.b(y());` it compiles fine.

**Comment by jrmyr** [comment]
Great! Thanks!
