### ISSUE TITLE
@FieldNameConstants FIELD_xxx cannot find symbol

### ISSUE THREAD

**Issue by lynings** [rzwitserloot/lombok#1908]
## Demo
```java

@Data
@FieldNameConstants
public class Customer {
    private String name;
}

  
@Data
public static class CustomerDTO {
    @Like(alias = Customer.FIELD_NAME)
    private String name;
}
```
`@Like` is my custom annotation

## Gradle log（error in the compileJava phase）
`
CustomerDTO.java: error: cannot find symbol @Like(alias = Customer.FIELD_NAME)                                                                                                                                                                
`

## Environment
Gradle 4.8
JDK 1.8
Intellij IDEA 2018.2.5
lombok 1.18.2

Please help me solve this problem, thank you！

**Comment by rzwitserloot** [comment]
starting with lombok 1.18.4, FieldNameConstants works differently. See the docs. It's `Customer.Fields.name` now instead of `customer.NAME`
