### ISSUE TITLE
SneakyThrowsRemover fails on Java 11 if inner classes are present

### ISSUE THREAD

**Issue by askoning** [rzwitserloot/lombok#1909]
**Observed**
When compiling a class with an inner class on Java 11, and `SneakyThrows` is present, the `SneakyThrowsRemover` causes an UnsupportedOperationException.

**Reproduction**
- Clone https://github.com/VagrantBlackbird/lombok-java-11-bug
- `mvn compile`

**Environment**
```
$ mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: C:\Program Files\Maven
Java version: 11, vendor: Oracle Corporation, runtime: C:\Program Files\java\jdk-11
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Complete output**
```
$ mvn compile
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< com.vbb:lombok-java-11-bug >---------------------
[INFO] Building lombok-java-11-bug 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ lombok-java-11-bug ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\workspaces\lombok-java-11-bug\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ lombok-java-11-bug ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to D:\workspaces\lombok-java-11-bug\target\classes
[WARNING] /D:/workspaces/lombok-java-11-bug/src/main/java/com/vbb/sneakythrows/ClassWithInnerClass.java: Error during the transformation of 'com.vbb.sneakythrows.ClassWithInnerClass'; post-compiler 'lombok.bytecode.SneakyThrowsRemover' caused an exception: java.lang.UnsupportedOperationException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.557 s
[INFO] Finished at: 2018-10-18T10:22:31+02:00
[INFO] ------------------------------------------------------------------------
```

**Cause**
Java 11 introduced nest hosts and mates.

`AsmUtil` uses a `ClassVisitor` with the ASM6 version flag. This visitor is passed to `ClassReader`, which does support the newly introduced nest feature, but only if version ASM7_EXPERIMENTAL is used. (see `ClassVisitor::visitNestHostExperimental`)

We've shown this to Roel already.

**Comment by micheljung** [comment]
It'd be lovely if Lombok made use of Java early access builds to ensure it works when the version in question is released - especially since this is going to happen every 6 months from now on.

As it stands right now, Lombok is lagging behind. This might have been ok in the past but I don't think it's any longer - it's a big argument against Lombok.

**Comment by rspilker** [comment]
@micheljung We are getting faster.

@askoning 2 days ago, ASM7 has been released. This should be fixed in https://github.com/rzwitserloot/lombok/commit/182cb0cb9e8db6341fb4633c3849b5e90ba6d088
