### ISSUE TITLE
Switch-case block does not see final attribute

### ISSUE THREAD

**Issue by damienmiheev** [rzwitserloot/lombok#1910]
When i run code below i have an Error: java: constant string expression required.
Looks like final modifier is ignored.
Java8, LombokVersion 1.16.14

By the way, idea see final attribute as well and I have no ability to change variable.
The error is only running code.

```
public class TestClas {
  public static void main(String[] args) {
    switch ("a") {
      case Test.A:
    }
  }
  @FieldDefaults(level = AccessLevel.PUBLIC, makeFinal = true)
  public static class Test {
    static String A = "a";
  }
}
```

**Comment by rzwitserloot** [comment]
intended behavior. As the docs say, `@FieldDefaults` only applies to instance fields. It does nothing to static methods.
