### ISSUE TITLE
By some some reason class mark as not implemented interface but build is ok

### ISSUE THREAD

**Issue by mrkeuz** [rzwitserloot/lombok#1911]
By some some reason class mark as not implemented interfaces 

i.e. writes not implemented  setLineId() getLineId() (interface WithLineNumber), but build is OK.

![selection_199](https://user-images.githubusercontent.com/6247921/47207478-ffcbce00-d393-11e8-87b2-531b03c34f81.png)

Intellijidea 2018.1, 2018.2

I made invalidate cache and reinstall plugin

Lombok 1.16.20, maven, multi module project.

Colleagues project with same settings are ok. 
Can provide some additional info.

**Comment by rzwitserloot** [comment]
I have no idea what the problem is. It sounds like you should file this bug with the [lombok-intellij-plugin](https://github.com/mplushnikov/lombok-intellij-plugin) project, though.
