### ISSUE TITLE
Feature Request.  Class constructor (shallow and deep)

### ISSUE THREAD

**Issue by robertsearle** [rzwitserloot/lombok#1913]
I would like a deep and shallow class copy constructor.  E.G.

```
@DeepClassCopyConstructor
class Car {
   String license;
   String model;
   Engine engine;

  Car (Car c){
      this.license = c.license;
      this.model = c.model;
      this.engine = new Engine(c.engine);
  }

}
```

```
@ShallowClassCopyConstructor
class Car {
   String license;
   String model;
   Engine engine;

  Car (Car c){
      this.license = c.license;
      this.model = c.model;
      this.engine = c.engine;
  }

}
```

**Comment by rzwitserloot** [comment]
There's no way for us to know that, to make a deep copy of `engine` we'd have to call `new Engine(c.engine)`, and there's also no way for us to know that, for example, `java.math.BigInteger` is immutable and therefore does not need a deep copy, unless we hardcode every immutable type as a big list in lombok someplace. This is hard for `java.*` and utterly impossible for the entire greater java ecosystem.

That makes this feature request impossible to implement.

**Comment by robertsearle** [comment]
Actually can you just do a new Integer(c.id)

Sent from my iPad

On Nov 5, 2018, at 2:36 PM, Reinier Zwitserloot <notifications@github.com<mailto:notifications@github.com>> wrote:


There's no way for us to know that, to make a deep copy of engine we'd have to call new Engine(c.engine), and there's also no way for us to know that, for example, java.math.BigInteger is immutable and therefore does not need a deep copy, unless we hardcode every immutable type as a big list in lombok someplace. This is hard for java.* and utterly impossible for the entire greater java ecosystem.

That makes this feature request impossible to implement.
