### ISSUE TITLE
Feature Request: @ToString transient config option

### ISSUE THREAD

**Issue by JoachimVandersmissen** [rzwitserloot/lombok#1914]
As discussed in #996, this project doesn't aim for @ ToString to ignore transient fields by default. In that case, I'd like to suggest a configuration option, something like `lombok.toString.ignoreTransient` (default being false). At the moment, end users have to manually exclude every single transient field in every single class, which is very inconvenient. If needed, and if this project is open to this option, I'd be willing to create a pull request to implement it.

**Comment by rzwitserloot** [comment]
Too exotic, sorry. We can't have `@ToString` having 58 separate parameters, and given that whether to include transients or not is likely to be different depending on what class you're putting `@ToString` on, making a `lombok.config` option (where we still have 'let's avoid a million options' as a rule, but it's less stringent) isn't a good idea either.

toString really needs some amazing templatey concept but we've never seen anything workable that we like well enough.

So, when you have somewhat exotic toString needs, write your toString impl by hand, I'm afraid.
