### ISSUE TITLE
Proposal: @ToString(delegateSuper=[true/false]) - add an attribute saying: "delegate to superClass toString() only".

### ISSUE THREAD

**Issue by wheredevel** [rzwitserloot/lombok#1915]
Consider the following case in Vanilla Java:
---------------------
```java

abstract class Expression {
}

abstract class BinaryExpression extends Expression {
  Expression left;
  String op;
  Expression right;

  public String toString() {
    return left + " " + op + " " + right;
  }
}

class Mulitplication extends BinaryExpression {
  Mulitplication() {
    this.op = "*";
  }
}

class Number extends Expression {
  double value;

  Number(double value) {
    this.value = value;
  }

  public String toString() {
    return value;
  }
}

class Main {

  public static void main() {
    Expression exp = new Multiplication(new Number(10), new Number(20));
    System.out.println(exp); 
  }
}
```

This should print:
```
10 * 20
```

Now with Lombok:
---------------------
```java
...
@ToString // or @Data or @Value
class Mulitplication extends BinaryExpression
...
@Data
class Number extends Expression
...
```

This time it would print something like:
```
Multiplication[]
```

The reason this doesn't work as expected is:  
```@ToString``` on Multiplication has no indicator of delegating to superClass.  

Of course, I could, simply, remove ```@ToString``` to leave it work the ordinary Java way.  
But that's impossible, for example, if I decide to use ```@Data``` or ```@Value``` annotation...  
Of course, I could specify ```@Getter``` ```@Setter``` ```@EqualsAndHashCode``` WITHOUT ```@ToString``` - but that's much more writing and maintenance to do than just specifying something like:  
```@ToString(delegateSuper = true)```

Note: there's no problem with Number's ```@ToString```/```@Data```/```@Value``` - as it's implemented in the class itself, preventing Lombok from generating ```toString()```.

Note: ```@ToString(callSuper=true)``` on Multiplication, in this case, doesn't help, but worsens the matter.  
Cos' its purpose it to add super's printout to child's ```toString()```.  
Something like that would be printed:
```
Multiplication[super=10 * 20]
```

**Comment by rzwitserloot** [comment]
Writing `public String toString() {return super.toString();}` is probably less effort than this. We don't add options like this lightly. Adding them lightly means `@ToString` ends up having 58 different parameters and we don't think that's a good idea.

**Comment by wheredevel** [comment]
OK. I hope it will be reconsidered in the future.
