### ISSUE TITLE
@ToString over enum to incorporate enum field name

### ISSUE THREAD

**Issue by wizzlerr** [rzwitserloot/lombok#1916]
Tested on 1.18.2 and 1.16.18

```
@ToString
enum SampleEnum {
    SOME_FIELD;
}
```
Currently above enum is compiled into below code.

```
enum SampleEnum {
    SOME_FIELD;

 public String toString() {
        return "SampleEnum ()";
    }
}
```

So whenever i run toString on List<SampleEnum> I will get N "SampleEnum()" strings. 

It should be compiled to:

```
enum SampleEnum {
    SOME_FIELD;

 public String toString() {
        return "SampleEnum (name())";
    }
}
```

or anything that indicates enums field name.

**Comment by rspilker** [comment]
I suggest to use `return "SampleEnum." + name() + "()";`

**Comment by rzwitserloot** [comment]
this is now available in edge release: https://projectlombok.org/download-edge
