### ISSUE TITLE
Property lombok.toString.callSuper = call

### ISSUE THREAD

**Issue by zbynekvavros** [rzwitserloot/lombok#1918]
I really hope I don't duplicate anything but I haven't found this anywhere.
We have property 'lombok.equalsAndHashCode.callSuper = call' but no
'lombok.toString.callSuper = call'. Is there any particular reason why such a property
is missing in configuration?

**Comment by zbynekvavros** [comment]
I am talking about property in lombok.properties (having lombok.toString.callSuper = call).
Is this possible?

**Comment by rzwitserloot** [comment]
It'll be in the next version :)

**Comment by zbynekvavros** [comment]
Thanks :)

**Comment by mgohin** [comment]
Guys, the doc speaks about it but as I understand it's not release yet ?
https://projectlombok.org/features/ToString : `lombok.toString.callSuper = [call | skip | warn] (default: skip)`

We are trying to use it for one hour with no success, and I step into this github issue :/

**Comment by rzwitserloot** [comment]
this is now available in edge release: https://projectlombok.org/download-edge

a new full lombok release will be out soon, we have one more change we'd like to run in edge release first before then.

**Comment by celdridge91190** [comment]
There are a couple of spots in the documentation where there are references to callSuper = true, which I've seen cause people some confusion. If the current released version now supports call, would it be possible to have the documentation cleaned up to remove references to true/false? This is true of both [toString](https://projectlombok.org/features/ToString) and [EqualsAndHashCode(https://projectlombok.org/features/EqualsAndHashCode)]. Big fan of the update to include the warn though given the impact :)

i.e. . By setting callSuper to true, you can include the output of the superclass implementation of toString to the output.

**Comment by CH-LuizGerosa** [comment]
I upgraded to version 1.18.6 and I'm still receiving the error message `Unknown key 'lombok.toString.callSuper'` during the build.
