### ISSUE TITLE
@Value generates private default constructor

### ISSUE THREAD

**Issue by alwins0n** [rzwitserloot/lombok#1919]
according to java doc `@Value` is equivalent to `@Getter @FieldDefaults(makeFinal=true, level=AccessLevel.PRIVATE) @AllArgsConstructor @ToString @EqualsAndHashCode`

but the bytecode output on jdk11 with -parameters flag is generating a private default constructor. you can get rid of it by explicitly marking the class with `@AllArgsConstructor` but still - this is unexpected and causes frameworks that rely in on a single constructor via reflection to fail.

version lombo 1.16.22

**Comment by rspilker** [comment]
This is already fixed in 1.18.2
