### ISSUE TITLE
1.16.22 version bug

### ISSUE THREAD

**Issue by hifishzlj** [rzwitserloot/lombok#1920]
spring boot1.x中使用1.16.10正常，升级到spring boot2.x后，lombok版本同时也升级到1.16.22，这时候一个类定义多个不同参数的构造函数后，@NoArgsConstructor注解就会报错，已在类 xxxx 定义了构造器 xxx()，但是并没有定义无参构造函数，降级到1.16.10版本后无此问题。

**Comment by rspilker** [comment]
I think this is fixed in version 1.18.2.
