### ISSUE TITLE
Feature Idea Refactoring should not exclude methods from IDE outline

### ISSUE THREAD

**Issue by arnaldop** [rzwitserloot/lombok#1926]
https://github.com/rzwitserloot/lombok/wiki/FEATURE-IDEA:-Lombok-Refactoring says:

> A related idea: Allow hiding lombok generated methods from the IDE outline. While lombok keeps the written code concise, the outline shows all the boilerplate which often isn’t useful. Graying out the generated stuff would be an option, too.

This should not be implemented.

I use IntelliJ, but I believe this worked the same in Eclipse.
Currently, the only way to find usages of a generated method is by going to the outline and selecting "Find Usages" of that generated method.

Without it, our only resort is to do text searches.

For example, say class A has a generated no-args constructor and a manual all-args constructor. Currently, I can search for references to the no-args constructor by using "Find Usages". If we remove this feature, I'll have to resort to doing a full text search of the text "A(", which will give me all constructor calls, including the all-args constructor.

The outline should reflect the methods the class implements, regardless of their source, Lombok or the dev.

This might an issue for each IDE plugin to deal with. And a config flag would work fine for me also. I just don't want to lose that functionality altogether.

**Comment by Maaartinus** [comment]
@arnaldop This was my idea... I proposed this as I've got (entity) classes with tons of fields and generated getters and setters, which make finding "real" (i.e., manually written) methods hard. I surely do agree that removing generated methods from the outline without any substitute would be a bad idea. I've just edited the wiki.

**Comment by rzwitserloot** [comment]
Great, sounds like this issue is sorted :)

Thinking about what you said, clearly the right answer is to mark generated methods as generated somehow. Probably greying them out (logos would, if anything, draw MORE attention to them; the goal is to draw less).

NB: I edited it some more, looks good now and thanks for reminding us about the necessity of the outline view entries.
