### ISSUE TITLE
Use Jigsaw to hide classes instead of the SCL

### ISSUE THREAD

**Issue by smoyer64** [rzwitserloot/lombok#1927]
I love Lombok but as noted in #1005, the SCL has made if far more difficult to write extensions.  I'd like to see a condition where extension authors aren't constantly writing the same code to simply access the guts of the system.

**Comment by rzwitserloot** [comment]
jigsaw requires java9. Adoption rate of java9 is not exactly stellar, and there'll be like 20%+ of the community 'stuck' on java8 or below for probably a decade.

So, never gonna happen.

But 'make lombok easier to extend' is definitely on our todo list! We'd just go about it differently.
