### ISSUE TITLE
Add lombock to https://wiki.openjdk.java.net/display/quality/Quality+Outreach

### ISSUE THREAD

**Issue by Jeansen** [rzwitserloot/lombok#1928]
I would suggest to list this project here for reference: https://wiki.openjdk.java.net/display/quality/Quality+Outreach

**Comment by rzwitserloot** [comment]
Go ahead and do so, by all means :)

**Comment by Jeansen** [comment]
I cannot do this, someone from the lombok project has to do this and should provide information relevant to the different jdk versions and a contact person and maybe even more.
