### ISSUE TITLE
lombok stable version does not work with sts 4

### ISSUE THREAD

**Issue by sms17** [rzwitserloot/lombok#1930]
hi contributors, 

i am facing issues when i tried to install lombok stable in STS 4. please let me know if there is any other work around other than using edge version.

Thanks.

**Comment by rspilker** [comment]
Which version did you try to install?

**Comment by arjunsekar1991** [comment]
1.18.4  is not working

**Comment by rzwitserloot** [comment]
'facing issues' is not really something we can work with. I guess we could install STS4 and just pray we run into some problem, then assume it's what you're running into.

But that takes way too much time. We get more bug reports than we can handle. Nothing personal, but given that we're so swamped, serve it up for us on a silver platter. What is going wrong _exactly_, which STS did you download, how do you install that, what errors do you get, paste the entire stack trace if there is one, yadayada.

slated for closing @ 2018-12-01

**Comment by arjunsekar1991** [comment]
I downloaded sts 4 version and nothing works. It's did not recognize lombok to be an add-on in the about page of sts.

**Comment by rspilker** [comment]
Interesting, since I did as STS4 to the installer, and at that time everything worked.

**Comment by rspilker** [comment]
Where is you sts installed? What is the name of the executable? What os are you using?

**Comment by arjunsekar1991** [comment]
It's a Windows 10 vm . Sts installed on c drive . Ide downloaded from here https://spring.io/tools

**Comment by rspilker** [comment]
What path?

**Comment by rspilker** [comment]
I have no idea what goes wrong on your PC.

I just downloaded spring-tool-suite-4-4.0.1.RELEASE-e4.9.0-win32.win32.x86_64.zip

I created a directory called "c:\sts", and move the contents of the zip's sts-4.0.1.RELEASE directory to it, so that `c:\sts\SpringToolsSuit4.exe` exists.

Then I installed lombok using `java -jar lombok.jar`. That found my installation by scanning the harddrives. Install/Update installed lombok; the `Help - About Spring Tools Suite 4` dialog's last line in the white scrollable area that starts with 
```
Spring Tool Suite 4 

Version: 4.0.1.RELEASE
Build Id: 201810300749
```
says
```
Lombok v1.18.5 "Edgy Guinea Pig" - 2018-11-06 is installed. https://projectlombok.org/
```

**Comment by arjunsekar1991** [comment]
Only edge version works sir that's the issue stable version is not working

**Comment by arjunsekar1991** [comment]
I clealy mentioned "lombok stable" in the issue name

**Comment by rspilker** [comment]
The reason I asked for the exact version number you used was that we released a new version at the time you created the issue. So we couldn't know for sure which stable version you meant.

**Comment by arjunsekar1991** [comment]
Sure I will check and let you know. It's holiday for Diwali festival. Tomorrow I will let you know the version. 1.18.4 is the version if I am not wrong

**Comment by machadowelton** [comment]
@arjunsekar1991 

i get same problem on STS 4 using the OpenJDK 1.8.0_40. I always have problem on use openJDK. My solution workaround is :

Execute the lombok jar with Oracle JDK to configure on STS 4. Then execute STS 4 with OpenJDK.

**Comment by amitkumarhota** [comment]
lombok edge worked for me. There are some issues with stable lombok version. I was using 1.18.12
https://projectlombok.org/download-edge
