### ISSUE TITLE
@SuperBuilder dont generate any code

### ISSUE THREAD

**Issue by AndreKoepke** [rzwitserloot/lombok#1931]
*  **IDE** 
IntelliJ  

 *  **Plugin** 
IntelliJ Lombok plugin v 0.22.2018.2

*  **Dependency**
org.projectlombok.lombok:1.18.4

```java
@SuperBuilder
@Getter
public class CellBaseData {
    public enum HorizontalAlignment {
        LEFT, CENTER, RIGHT
    }

    @Setter
    private Row row;

    private Color backgroundColor;
    private Color borderColor;
    private int span = 1;
    private HorizontalAlignment alignment = HorizontalAlignment.LEFT;
    private float paddingLeft = 4;
    private float borderWidthTop = 0;

    public boolean hasBorderTop() {
        return getBorderWidthTop() > 0;
    }
}

@SuperBuilder
@Getter
public class CellText extends CellBaseData {
    private final String text;
    private final PDFont font;

     public PDFont getFont() {
        return Optional.ofNullable(font).orElse(getRow().getFont());
    }
}
```

## The problem
For this example lombok dosn't generate any code for the ` @SuperBuilder`-annotation.  
When I try to access the builder via `CellBaseDate.builder()` or `CellText.builder()`, then IntelliJ says, that this method is missing.

**Comment by mplushnikov** [comment]
It's currently not supported by lombok-plugin for Intellij: https://github.com/mplushnikov/lombok-intellij-plugin/issues/513

**Comment by AndreKoepke** [comment]
Ok, thanks.

**Comment by dvsingh9** [comment]
Hi @mplushnikov, is there any other way to use @SuperBuilder with intelliJ ?

**Comment by mplushnikov** [comment]
@dvsingh9 Unfortunately not. Only when this functionality was implemented in the plugin, which unfortunately proved to be more difficult than initially thought.
