### ISSUE TITLE
Add configuration property to restrict all lombok features except some

### ISSUE THREAD

**Issue by mih-kopylov** [rzwitserloot/lombok#1933]
Now there's a way to restrict some concrete features, like 
```
lombok.data.flagUsage=ERROR
```

I'd like to configure my project allowing using only `@Getter` and `@Setter`. So I expect having something like that
```
lombok.allFlagsUsage=ERROR
lombok.getter.flagUsage=ALLOW
lombok.setter.flagUsage=ALLOW
```

**Comment by rzwitserloot** [comment]
Feels a little too exotic. We don't add main features lightly, and you can already blanket-disable experimental (right now, a blanket ERROR/WARNING set on all experimentals can NOT be overridden by explicitly mentioning individual features. There's some merit to this but we'd have to document that the more specific stuff overrides the less specific stuff. Hmm, _maybe_ that is obvious enough).

The main problem is that the way the flagUsage system is implemented, this would be a relatively large amount of work, and we're a bit swamped. Good idea though; I'd accept a PR with this update.

**Comment by mih-kopylov** [comment]
@rzwitserloot so why have you closed the ticket if you'd accept a PR for it?

**Comment by Maaartinus** [comment]
> There's some merit to this but we'd have to document that the more specific stuff overrides the less specific stuff. Hmm, maybe that is obvious enough.

@rzwitserloot It is not. IMHO it's actually wrong. Stuff in a single file should be processed as written, crazy rules like "more specific" can quickly converge to some CSS rule strength mess and you'll need a computer to understand what you just wrote. The optimal rule is: *Later option wins.*

This usually also the easiest behavior to implement, just treat setting "experimental" to X as a shortcut for setting all experimental features to X.
