### ISSUE TITLE
Mvnrepository pom dependency provided or optional

### ISSUE THREAD

**Issue by serfin15** [rzwitserloot/lombok#1937]
Why pom dependecy in maven central is marked with scope=provided. If the library is only used for compilaion time it wouldn't be better use it as '<optional>true</optional>' instead <scope>provided</scope>?

**Comment by rspilker** [comment]
Can you supply actual pom files to explain what you mean?

**Comment by serfin15** [comment]
yes sorry, my question is not a bug properly and maybe this is not the location to get information about it, so i close the issue.
Thanks
