### ISSUE TITLE
FieldNameConstants documentation doesn't match code

### ISSUE THREAD

**Issue by Jazzepi** [rzwitserloot/lombok#1938]
https://projectlombok.org/features/experimental/FieldNameConstants

Shows `@FieldNameConstants` being used on a field (which makes sense) but the code restricts the annotation to `Target(ElementType.TYPE)`

```
    @FieldNameConstants
    public class FieldNameConstantsExample {
        private final String iAmAField;
        @FieldNameConstants(level = AccessLevel.PACKAGE)
        private final int andSoAmI;
    }
```

**Comment by rzwitserloot** [comment]
Good point. Modified it to show off the `@FieldNameConstants.Exclude` way of doing this; this is a holdover from how `@FNC` used to work. Good eye :)
