### ISSUE TITLE
@AllArgsConstructor mixed with @NoArgsConstructor for class without fields = compilation error

### ISSUE THREAD

**Issue by pp-dusza** [rzwitserloot/lombok#1939]
Assume we have a class without any field, annotated with both `@AllArgsConstructor` and `@NoArgsConstructor`:

```java
@AllArgsConstructor
@NoArgsConstructor
public class Data
{
}
```

it results with compilation error:

> constructor Data() is already defined in class Data

I think `@AllArgsConstructor` should generate constructor only when there are fields in the class.

**Comment by pp-dusza** [comment]
It's obvious what's the cause of the error. But isn't it more desired for `@AllArgsConstructor` to state: 'no field - no constructor'?

**Comment by Maaartinus** [comment]
@pp-dusza No, using the `@AllArgsConstructor` for classes having no fields is perfectly correct. I surely do this from time to time as, sometimes, it's conceptually what I want. "all" may mean the empty set and there's nothing wrong with it.

The problem only comes from the conflict of the two. The error message could be better, but given how trivial it is to spot and to fix the problem, it's IMHO not worth discussing.

**Comment by pp-dusza** [comment]
OK, you convinced me.
