### ISSUE TITLE
Incompitable with IntelliJ IDEA 2018.3(ultimate edition)

### ISSUE THREAD

**Issue by YinAqu** [rzwitserloot/lombok#1954]
OS: arch linux
JAVA: openjdk 1.8
IDE:  IntelliJ IDEA 2018.3(ultimate edition)

**Comment by janrieke** [comment]
That's not a Lombok bug. Please report at https://github.com/mplushnikov/lombok-intellij-plugin.

**Comment by YinAqu** [comment]
sorry.

**Comment by shalomFrog** [comment]
there is an updated Lombok plugin that solves the problem (0.22)
