### ISSUE TITLE
JDK11: illegal access warning

### ISSUE THREAD

**Issue by nonongodup** [rzwitserloot/lombok#1962]
I tried to run mvn clean package and got this. not able to run with jdk 11. 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by lombok.javac.apt.LombokProcessor to field com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs
WARNING: Please consider reporting this to the maintainers of lombok.javac.apt.LombokProcessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by sheroying** [comment]
Same issue with above

**Comment by captainleviftw** [comment]
Use this lombok version: `1.18.4`

**Comment by rspilker** [comment]
@nonongodup What version of lombok did you use?

**Comment by qinghuazs** [comment]
hi, i use lombok plugin in idea, and the version is v0.23-2018.3, now the same issue coming with me, seriously， i can not build my project, anything else can i do to solve this issue？

**Comment by kuschuermann** [comment]
This issue is biting me with lombok 1.18.12 as well. Is there a fix or at least a workaround?

**Comment by RSully** [comment]
Same here on 1.18.12

**Comment by randakar** [comment]
Please try it with 1.18.16
