### ISSUE TITLE
Website https://projectlombok.org/ menu is non-clickable in China

### ISSUE THREAD

**Issue by paulvi** [rzwitserloot/lombok#1964]
All Google services are unavailable in China (without VPN)

see https://no-google-in-china.github.io/

So jQuery fails to load
`<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"`

and menu is non-usable.

Please use other server to download jQuery 
https://jquery.com/download/#other-cdns

**Comment by rspilker** [comment]
We're now serving it ourselves. Also serving some other dependencies.

**Comment by paulvi** [comment]
thank so much
