### ISSUE TITLE
Working with Lombok without any IDE plugin

### ISSUE THREAD

**Issue by Cepr0** [rzwitserloot/lombok#1967]
Is it possible to work with Lombok without any IDE plugin? As we can do it with [Immutables](https://immutables.github.io/), for example? 
It's a [pain](https://github.com/mplushnikov/lombok-intellij-plugin/issues/513) to be dependent on third-party plugins (

**Comment by janrieke** [comment]
Of course you can. Just ensure `lombok.jar` is on the classpath when invoking `javac`. Maven or Gradle will do that for you if you add Lombok as dependency. But you can also do it completely manual.
However, if you use IntelliJ, you will still get error markers, and its internal compiler will not work. That means you have to invoke Maven/Gradle each time you make a change, and things like hot code replace won't work.

**Comment by Cepr0** [comment]
I have Lombok dependency in Maven pom.xml like the follows (it's generated with Spring starter):

```xml
    <dependencies>
        ...
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        ...
    </dependencies>
```

Then I comile the project I can see comiled classes in the `target/classess/` folder with Lombok code. But I can't see any generated source files in the `target/generated-sources` folder (as other code generators do, for example Immutables or MapStruct). So then I turn off the Lombock plugin in IntelliJ IDEA I get error markers in the code. So is it possible to make Lombok to generate such source code?

**Comment by janrieke** [comment]
Lombok is not a code generator. It makes its changes directly during compilation, so Lombok only affects the compiled class files.

You can use `delombok` to get what would be the Java code for what Lombok generates, and work with that. However, you loose all Lombok annotations and, thus, the brevity of them.

**Comment by Cepr0** [comment]
Thank you for clarification. )
It would be great if code generation was implemented - we wouldn't depend on third-party plug-ins...

**Comment by janrieke** [comment]
That is conceptionally impossible, because Lombok's annotations modify the source file they are in. You cannot achieve this functionality with a classic code generator.

**Comment by Maaartinus** [comment]
@Cepr0 What you want is plain impossible. You want to write `@Getter` in your IDE and to get it now. In the same class, in your IDE. You don't want a generated read-only code somewhere, which your IDE could simply reload; you want you IDE to see changes in the file you're just editing.

In Eclipse and Netbeans, all you need is `lombok.jar` installed in the IDE. It's not third party, it's the only file this project produces. For intellij idea, you indeed need a third party plugin.
