### ISSUE TITLE
`FieldNameConstants` generates an enum with empty `values()`

### ISSUE THREAD

**Issue by Maaartinus** [rzwitserloot/lombok#1969]
I'm using `@FieldNameConstants(asEnum=true)` and I get an inner `enum Fields` as expected and can access its members by name. However, `Fields.values()` returns an empty array.

I've made sure there's no older Lombok version hanging around and recompiled everything. My setup:

Eclipse IDE for Java Developers
Version: 2018-09 (4.9.0)
Build id: 20180917-1800
Lombok v1.18.4 "Envious Ferret" is installed.
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by jason-kong** [comment]
I'm having the same issue, my IntelliJ using teammates don't have this issue I believe

**Comment by Rawi01** [comment]
I am working on a fix for this one right now
