### ISSUE TITLE
How to generate builders using a java program

### ISSUE THREAD

**Issue by hemikak** [rzwitserloot/lombok#1971]
Hi All,

I would like to generate my builder classes using a java Main program. How can I do it ?

Regards,
Hemika

**Comment by hemikak** [comment]
Yes exactly. I think I can refer this https://github.com/awhitford/lombok.maven/blob/master/lombok-maven-plugin/src/main/java/lombok/maven/AbstractDelombokMojo.java if I am not wrong.

**Comment by janrieke** [comment]
Yes, that should do the trick. I still see no issue here. What exactly is your problem?

**Comment by hemikak** [comment]
Closing the issue, needed a reference.
