### ISSUE TITLE
Eclipse 2018-09 issue with installing lombok.jar on macOS 10.13 (High Sierra)

### ISSUE THREAD

**Issue by robmarano** [rzwitserloot/lombok#1977]
Hi all,

After downloading the latest Eclipse version 2018-09 and tried to install lombok.jar, it was not working correctly, with the error:
```
Error opening zip file or JAR manifest missing : lombok.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```
I noticed the install into Eclipse via java -jar lombok.jar did not configure the eclipse.ini properly. It was missing the XbootClasspath variable. (See https://www.eclipse.org/openj9/docs/xbootclasspath/)

Under the -vmargs in eclipse.ini, it should include the following configuration for lombok
```
-vmargs
-Xbootclasspath/a:/Applications/Eclipse.app/Contents/Eclipse/lombok.jar
-javaagent:/Applications/Eclipse.app/Contents/Eclipse/lombok.jar
```

Btw, if you installed Eclipse using Homebrew, like
```brew cask install eclipse-jee```

You will need to rename /Applications/Eclipse JEE.app to /Applications/Eclipse.app for the current version of lombok (1.18.4) to install into Eclipse properly.

I hope this helps! It works for me now.
/rob

**Comment by rspilker** [comment]
Closed due too no response from reporter.

**Comment by robmarano** [comment]
Sorry, rspilker, for my tardy response.

Yes, this does work. But then when I updated the cask, it no longer works. I get the following error:

rob@~$ /Applications/Eclipse\ JEE.app/Contents/MacOS/eclipse
Error opening zip file or JAR manifest missing : /Applications/Eclipse\ JEE.app/Contents/Eclipse/lombok.jar
Error occurred during initialization of VM
agent library failed to init: instrument

Any clue?
/rob
