### ISSUE TITLE
Recursive lookup occurs in JPA one-to-many environments

### ISSUE THREAD

**Issue by littleHH** [rzwitserloot/lombok#1978]
When I delete the parent node of a one-to-many relationship in the same table, I always do hashCode operations.

```
@Entity
@Table(name = "t_category")
@Data
public class GoodsCategory extends IdentifyObject {
    private static final long serialVersionUID = 5142505254986315016L;

    private String name;

    @ManyToOne()
    @JoinColumn(name = "pid")
    private GoodsCategory parent;

    @OneToMany(mappedBy = "parent",cascade = {CascadeType.REMOVE})
    private Set<GoodsCategory> categories = new HashSet<>();
}
```

log：

![image](https://user-images.githubusercontent.com/14009808/49978068-bb1f7600-ff83-11e8-9445-9ecead8e4cac.png)

**Comment by Maaartinus** [comment]
That's actually to be expected. You defined `GoodsCategory` as consisting of other categories and a parent, so the `hashCode` computation needs their hashes first. Try to compute the `hashCode` manually... I've spent some time thinking of a better algorithm, but haven't found anything really good.

Use `@EqualsAndHashCode.Exclude` on the parent or on the children or on both to break the cycle. Use also `@String.Exclude` as this has the same problem. What you want to exclude depends on the semantics. For entities, I include nothing but `id` in the computation, YMMV.

**Comment by littleHH** [comment]
Thank you for your reply. I found that I added @Data to my super class. This problem has been solved.
