### ISSUE TITLE
lombok support for open jdk 11[FEATURE] 

### ISSUE THREAD

**Issue by BhartiL** [rzwitserloot/lombok#1985]
**Before submitting**
Please check our [wiki](https://github.com/rzwitserloot/lombok/wiki) because some feature requests are asked _a lot_ and there are good reasons (as explained on the wiki) why we can't (yet) implement them or why we won't implement them.

**Describe the feature**
A clear and concise description of what the feature request/enhancement is. What is the goal of adding this feature request? This should include 2 java snippets: One 'lomboked' version, which is java code with (for example) an annotation that is short and boilerplate free, and a second snippet that shows precisely what lombok will do under the hood. Lombok can only turn java code that is valid java syntax into different java code.

**Describe the target audience**
Describe which programmers and/or which kinds of programs would benefit from your feature proposal. If the feature proposal interacts with a library that isn't part of the core java libraries, link to this project.

**Additional context**
Add any other context about the feature / enhancement here.

**Comment by rzwitserloot** [comment]
lombok works fine on openjdk11.
