### ISSUE TITLE
val assigning incorrect class to Arrays.asList() in Eclipse

### ISSUE THREAD

**Issue by dastamatis** [rzwitserloot/lombok#1986]
In the latest version of lombok and Eclipse, val is incorrectly assigning variable "x" to Object instead of List<Class<? extends java.io.Serializable>> in the code below:
```java
package com.github.rzwitserloot;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;
import lombok.val;

public class ValBug {
	public static void main(String[] args) throws Exception {
		val x = Arrays.asList(String.class, BigDecimal.class);
		for (val y : x) {
			
		}
	}
}
```

**Comment by rspilker** [comment]
Is that a regression; did a previous version of lombok do this differently? 

Is is only in Eclipse, or also on javac?

**Comment by dastamatis** [comment]
I tried it with 1.14.6, 1.16.10, 1.16.16, and latest version 1.18.4, both in Eclipse and on the command line.

Error is the same:
Exception in thread "main" java.lang.Error: Unresolved compilation problem:
	Type mismatch: cannot convert from List<Class<? extends Object&Serializable&Comparable<?>>> to List<Class<? extends Object>>

**Comment by dastamatis** [comment]
And by "on the command line", I mean I compiled it with javac in a terminal window (not from Eclipse's UI).

**Comment by rspilker** [comment]
Wow, good catch.

**Comment by rspilker** [comment]
I cannot reproduce the problem using 1.18.6 and javac 11.

**Comment by rspilker** [comment]
Oh, and we will not create `List<Class<? extends Serializable>>` but `List`

**Comment by rspilker** [comment]
Can you verify your Eclipse works with the latest [edge release](https://projectlombok.org/download-edge)?

**Comment by dastamatis** [comment]
Yup, works now. Thanks for the fix!
