### ISSUE TITLE
Why read me is worse than 80s websites ? 

### ISSUE THREAD

**Issue by goxr3plus** [rzwitserloot/lombok#1991]
This is one of the worst read me i have ever seen and will ....

Like look at other projects like  :

https://github.com/spring-projects/spring-boot
https://immutables.github.io/

I can be listing for years .... **why there is no proper read me** ? **Even the website has a video from 60s   quality .**

Feel free to close but fix someway the read me of this project .

**Comment by kaqqao** [comment]
@goxr3plus Why not make a pull request and contribute some examples yourself? It's an open source project, after all. Screaming isn't exactly helpful to anyone.

**Comment by goxr3plus** [comment]
Just wanted to know :) So popular project.

**Comment by goxr3plus** [comment]
@kaqqao   I will try to make a pull request , just wanted to know why after so many years nobody considered adding stuff on read me ;)
