### ISSUE TITLE
[BUG] "val" not able to infer lambda expressions types with Java 8 and Eclipse 4.10

### ISSUE THREAD

**Issue by galegofer** [rzwitserloot/lombok#1994]
**Describe the bug**
I don´t know exactly if that's is a bug or a feature indeed, but when you try to do the next code at Eclipse:

val function = value -> "Hello world";

Compiler complaints with the next message: 

"val is not allowed with lambda expressions" and "Cannot convert from String to Class<? extends annotation>"

I guess that message is happening because the compiler is unable to infer the "value" parameter at the lambda expression, but even if you provide it:

val function = (Integer value) -> "Hello world";

You get the same error.

**To Reproduce**
Use:

val function = value -> "Hello world";

or

val function = (Integer value) -> "Hello world";

**Expected behavior**

The compiler should be able to infer the type of val for the given function or functional interface.

**Version info (please complete the following information):**
 - 1.18.4
 - Java 1.8.0_192, eclipse 4.10

**Comment by rzwitserloot** [comment]
This is just how java works; java11's own 'var' can't do it either. Lambdas work like this:

FIRST, check where and how the entire thing is intended to be used, so, forget about the lambda, check the outer context (look from the lambda node in the AST __outwards__), which usually is either 'this is a parameter to a method' or 'this is the initializing expression for a variable', then check what type is needed, and armed what that info, try to figure out what kind of FunctionalInterface the lambda is trying to masquerade as.

With `val`, by definition there's no 'outward' type info.

Said differently: with `val function = (String a, String b) -> -1;` what value would you like lombok to infer? `BiFunction<String, String, Integer>`? Why not `Comparator<String>`? What you want is not possible and is not how java works.

**Comment by galegofer** [comment]
Very good answer and clear, I was thinking about the Scala system to infer lambda parameters, but what you said makes sense, Thanks

**Comment by zzSleep** [comment]
谢谢老板,你的回答对我很有帮助,我想知道 val到底在什么情况下使用呢?
