### ISSUE TITLE
[BUG] @EqualsAndHashCode(of = ...) silently ignores non-existing fields

### ISSUE THREAD

**Issue by dbardbar** [rzwitserloot/lombok#1996]
**Describe the bug**
`@EqualsAndHashCode(of = ...)` silently ignores non-existing fields

**To Reproduce**
```java
import lombok.EqualsAndHashCode;
@EqualsAndHashCode(of = {"field2", "mistake"})
public class EqualsAndHashCodeBug {
	public int field1;
	public int field2;
}
```
See that the code compiles with no warnings.

**Expected behavior**
Compilation error that field "mistake" does not exist

**Version info (please complete the following information):**
 - Lombok version 1.18.4
 - javac version 1.8.0_151

**Comment by amiraf** [comment]
According EqualsAndHashCode.of() javadoc:

>  Will soon be marked {@code @Deprecated}; use the {@code @EqualsAndHashCode.Include} annotation together with {@code @EqualsAndHashCode(onlyExplicitlyIncluded = true)}.

Is it still required?

**Comment by rspilker** [comment]
I thought we do generate a warning. I just added tests that verify that we actually do. 720b7cbc920940ec41fe96d7f91a80109bdf7ea8

**Comment by rspilker** [comment]
So I cannot reproduce the problem.
