### ISSUE TITLE
[BUG] Delombok not working with try-with-resources

### ISSUE THREAD

**Issue by dungba88** [rzwitserloot/lombok#1997]
**Describe the bug**
Delombok is not working with the try-with-resource, when the resource creation is done outside, throwing error.

**To Reproduce**
Put a code like this (the syntax is valid)

```
var inputStream = createSomeInputStream();
if (inputStream != null) {
    try (inputStream) {
        ...
    }
}
```

Using delombok in maven plugin and run the following command:

```
mvn clean install
```

**Expected behavior**
The command should return without any errors

**Actual behavior**
The command throwing error

```
Failed to execute goal org.projectlombok:lombok-maven-plugin:1.18.0.0:delombok (default) on project gridgo-jetty-http: Unable to delombok: InvocationTargetException: class com.sun.tools.javac.tree.JCTree$JCIdent cannot be cast to class com.sun.tools.javac.tree.JCTree$JCVariableDecl (com.sun.tools.javac.tree.JCTree$JCIdent and com.sun.tools.javac.tree.JCTree$JCVariableDecl are in module jdk.compiler of loader 'app') -> [Help 1]
```

**Version info (please complete the following information):**
 - Lombok version: 1.18.0.0
 - Platform (javac or eclipse, and if so, what is the output of `javac -version` / the version listed in the _about..._ dialog of eclipse.

JDK 11, Eclipse 2018.09

**Additional context**

**Comment by rzwitserloot** [comment]
An [edge release](https://projectlombok.org/download-edge) is now live with this fix included. We deemed it just barely inconsequential enough to _not_ make the changelog, though.
