### ISSUE TITLE
Lombok Issue with windows 10

### ISSUE THREAD

**Issue by Ravattailor** [rzwitserloot/lombok#2005]
I have latest Lombok jar and STS 4, but when double click on Lombok jar the popup is not coming properly.

Not Sure it is a Lombok Issue or Windows Issue

**Comment by NekoCaffeine** [comment]
Have you tried the command line startup?
java -jar lombok.jar

**Comment by Ravattailor** [comment]
I tried that way too

**Comment by NekoCaffeine** [comment]
output from the command line?

**Comment by NekoCaffeine** [comment]
I can reproduce it on my Windows 10 x64 when use Java8.

**Comment by Ravattailor** [comment]
Yes with same configuration I am facing the Issue

**Comment by NekoCaffeine** [comment]
Looks like a problem in the swing of Java8

**Comment by Ravattailor** [comment]
Tried with 1.6.12 it is working fine but after that, it is creating Issue.

**Comment by rspilker** [comment]
If the problem is the layout, we are very sorry, but will not be able to fix it. 

You can also install using the command line
```cmd
java -jar lombok.jar install auto
```

**Comment by rspilker** [comment]
@Ravattailor Do you now have lombok installed, either by modifying the init file by hand or by running `java -jar lombok.jar install auto`?

**Comment by rspilker** [comment]
No response from reporter, closing the issue

**Comment by Ravattailor** [comment]
Getting warning : Zero valid location found

**Comment by Ravattailor** [comment]
but worked with java -jar lombok.jar install <sts installation directory path>, Thanks
