### ISSUE TITLE
[FEATURE] @Delegate - automatic detection of already implemented methods

### ISSUE THREAD

**Issue by bsideup** [rzwitserloot/lombok#2006]
**Describe the feature**
`@Delegate` could detect already implemented methods and simply ignore them (as it does with getters)

**Describe the target audience**
Users of `@Delegate` who want to delegate all methods but some.

**Comment by rzwitserloot** [comment]
Yeah we want this too. Our workload currently simply does not give us any time to rework how delegate works, though.

**Comment by IgnatBeresnev** [comment]
@rzwitserloot if there's no strict deadlines on this, I could give it a shot, doesn't seem that difficult

**Comment by ly641921791** [comment]
I also want this feature.

**Comment by daliclass** [comment]
Great idea, going to have a good at implementing this

**Comment by daliclass** [comment]
Update: Still working on this when I can, delay is getting the ECJ side working as this seems quite involved when compared with the javac side.

**Comment by avirlrma** [comment]
Any update on this?

**Comment by Rawi01** [comment]
I have almost finished this one and will create a pull request soon.

**Comment by rspilker** [comment]
Can someone verify the fix using the [edge release](https://projectlombok.org/download-edge)?
