### ISSUE TITLE
[BUG] Copy field annotations feature copies only the first nullity annotation

### ISSUE THREAD

**Issue by ewirch** [rzwitserloot/lombok#2007]
The new copy field annotations feature copies nullity annotations by default. But it only does so for the first annotation. Problem: there are multiple nullity annotations which have different meaning.

```
@RequiredArgsConstructor
class Test {
    @javax.annotation.Nonnull
    @javax.validation.constraints.NotNull
    final String s1;
}
```

Actual delombok result:
```
    @java.beans.ConstructorProperties({"s1"})
    public Test(@NotNull String s1) {
        this.s1 = s1;
    }
```

Expected:
```
    @java.beans.ConstructorProperties({"s1"})
    public Test(@NotNull @Nonnull String s1) {
        this.s1 = s1;
    }
```

`javax.validation.constraints.NotNull` is used for bean validation. `javax.annotation.Nonnull` is used for static code analysis.

**Comment by rspilker** [comment]
We don't do anything with `javax.validation.constraints.NotNull` by default. So this has in my opinion nothing to do with the fact that there are multiple annotations.

I couldn't even reproduce your delombok result that the parameters is marked `@NotNull`, and I'm pretty sure it is typed by hand. Only `@Nonnull` would make sense.

**Comment by ewirch** [comment]
Then that's a bug of IntelliJ Lombok plugin. I'll open an issue in their project.

But seriously, simply closing an issue without even waiting for a reply. That's rude.

**Comment by ewirch** [comment]
No, no typo. It is a bug in IntelliJ Lombok plugin. Their "delombok" implementation generates a different class (with wrong annotations).

**Comment by rspilker** [comment]
Ah, ok, thanks for the update.
