### ISSUE TITLE
gradle deprecated apt, please update official site doc

### ISSUE THREAD

**Issue by kid1412621** [rzwitserloot/lombok#2009]
the official doc suggests to use `apt` in gradle to use lombok
https://projectlombok.org/setup/gradle
`dependencies {
	compileOnly 'org.projectlombok:lombok:1.18.4'
	
	apt 'org.projectlombok:lombok:1.18.4'
}`

however gradle deprecated apt replacing with annotationProcessor.
It is better to update the doc.

**Comment by rspilker** [comment]
Do you have any links to the gradle documentation? Is using `annotationProcessor` a drop-in replacement for `apt`?

**Comment by kid1412621** [comment]
> Do you have any links to the gradle documentation? Is using `annotationProcessor` a drop-in replacement for `apt`?

I cannot find in its doc (which is weird).
I did get warn from console printed by latest gradle.

https://discuss.gradle.org/t/regarding-the-annotation-processors-on-compile-classpath-warning-in-gradle-4-6/26144

**Comment by rspilker** [comment]
I'm happy to update the documentation on the lombok website. However, I am not a gradle expert.

Also, from which version of gradle should you use the `annotationProcessor` syntax. Currently we have two sections: 

- Gradle prior to v2.12
- Gradle v2.12 and up

I think we need at least 3 sections, or possibly we can drop the "Gradle prior to v2.12". But I'm hesitant to do so, there are always people that cannot use more recent versions.

**Comment by remy-tiitre** [comment]
I think its since 4.5 - https://docs.gradle.org/5.0/userguide/upgrading_version_4.html#rel4.6:annotation_processor_configuration

Also, better practice is to have 2 separate libraries, one for annotations and another for processor as they are used in 2 different classpaths. Not sure if this issue is opened somewhere else already.

**Comment by rzwitserloot** [comment]
Fixed in 2a8225a6af39d4a82f20928409fcb96ae72d363f – we'll roll out a website update later.
