### ISSUE TITLE
Using Class in custom annotation attributes

### ISSUE THREAD

**Issue by trks1970** [rzwitserloot/lombok#2012]
I am trying to develop some own annotations, but I am not able to get annotation attributes of type Class work properly under eclipse (4.9).

E.g.:
@MyAnnotation(clazz=MyClass.class)

results in error: cannot translate ClassLiteral to a class object.
It works fine with javac.

Anyone got a hint, how to solve this in eclipse?

**Comment by rspilker** [comment]
We do something like that when generateing logger instances: https://github.com/rzwitserloot/lombok/blob/master/src/core/lombok/eclipse/handlers/HandleLog.java#L96

**Comment by trks1970** [comment]
This is not the same as my example. 
The ClassLiteral you are referring to is in the generated code, not in the annotation. The error above happens when you try to get an instance of the annotation in the handler, if the annotation.
Actually in Eclipse the Class.forName method fails.
https://github.com/rzwitserloot/lombok/blob/f2d03973d59d96d8bfef51d8378a4069d8d46205/src/core/lombok/core/AnnotationValues.java#L353
