### ISSUE TITLE
[BUG][Documentation] addConstructorParameters not documented on the configuration page

### ISSUE THREAD

**Issue by dalewking** [rzwitserloot/lombok#2013]
1.16.20 deprecated suppressConstructorParameters and added addConstructorParameters config flag. The [configuration documentation page](https://projectlombok.org/features/configuration) does not reflect that change. While that page says it is a "sampling" it is probably not a good idea to list a deprecated property in the documentation.

**Comment by rzwitserloot** [comment]
Heh, wow. Our bad. Nice catch, @dalewking
