### ISSUE TITLE
[FEATURE] configuration for adding @Singular to collections by default for builders

### ISSUE THREAD

**Issue by kevcgrant** [rzwitserloot/lombok#2014]
Would be useful to have a configuration property that would let lombok builders add singular methods for collections by default, so I wouldn't need to add `@Singular` everywhere. 

E.g. `lombok.singular.always = [ true | false] `

**Comment by rspilker** [comment]
Hmm, tempting.

I have some concerns. 

The list of supported types changes over time.  Which means that a new version of lombok would change your API. 

And we would probably also have a way to suppress it for certain classes or fields.

**Comment by rzwitserloot** [comment]
I'm closing this; adding `@Singular` is good for readability, is not that difficult to add, and addresses all sorts of problems, such as the ones @rspilker raised.
