### ISSUE TITLE
[BUG] Jigsaw breaks Lombok and IntelliJ plugin

### ISSUE THREAD

**Issue by bojanantonovic** [rzwitserloot/lombok#2017]
**Describe the bug**
See 
- https://github.com/mplushnikov/lombok-intellij-plugin/issues/573#issuecomment-453544847
- 
https://groups.google.com/forum/m/#!topic/project-lombok/zw0Bk9xTvv4
- example code: 
https://github.com/bojanantonovic/lombok-jigsaw

I‘m placed a the circle of responsibilities. That‘s why I‘m opening a new bug report.

Sorry if something is unclearly described. I‘m new to this topic.

**To Reproduce**
1. check out/clone the exaple code
2. try to run it in IntelliJ => works
3. place a module-info.java => it breaks

This is without even using Maven to build it.

**Expected behavior**
Modularization with Jigsaw should not break Lombok. It should run out of the box, without using the command line.

**Version info (please complete the following information):**
 Latest of all.

**Additional context**
See given links.

**Comment by rzwitserloot** [comment]
I'm closing this one, as we have various tests in place for modules. I'm pretty sure it's a bug in the intellij plugin.
