### ISSUE TITLE
[BUG] @Builder.Default also applies to @NoArgConstructor - Backward compatibility

### ISSUE THREAD

**Issue by rasenfer** [rzwitserloot/lombok#2020]
After lombok 1.18.X anonnation @Builder.Default also applies values to constructor generated by @NoArgConstructor, that doesn't append in 1.16.20 version. 
1.17 is not tested we choose version 1.18 to use @SuperBuilder

This test fails on 1.18.4

	public class LombokBuilderTest {
		@Data
		@Builder(toBuilder = true)
		@NoArgsConstructor
		@AllArgsConstructor
		private static class InstanceA {
			@Builder.Default
			private String value = StringUtils.EMPTY;
		}

		@Test
		public void testBuild() {
			assertNull(new InstanceA().getValue());
			assertNotNull(InstanceA.builder().build().getValue());
		}
	}

Maybe this is the expected behaviour. But in this case I think that can be useful to add a feature to allow the use of defautl values only for builder or allow a secondary use to builders without applies default values.

Current behaviour breaks the use of this example in spring JPA that works well in previous versions.

	@Data
	@Builder(toBuilder = true)
	@NoArgsConstructor
	@AllArgsConstructor
	public void Entity {
		@Id
		private Integer id;

		@Builder.Default
		private Double value = NumberUtils.DOUBLE.ZERO;

		private String version;
	}

	Entity search = new Entity();
	search.setVersion("A")
	repository.findAll(Example.of(search))

We expect to find all entities with 'version' = 'A. But in this case search all entities with 'version' = 'A and value = 0. This can be managed with low number of fields setting it to null, but we have entities with a larger number of default values.

Tested with lombok 1.18.4 with differents eclipse versions and maven too.

**Comment by rzwitserloot** [comment]
Yeah, we changed how it works. We could introduce a setting, but we won't. Introducing a setting for this implies introducing about 100 other settings, and maintaining that + having lombok's documentation throw you a book's worth of options like it's a take-out menu would make for a worse product.

**Comment by byjay** [comment]
`we changed how it works.`....
