### ISSUE TITLE
[BUG] @FieldNameConstants causes Eclipse error messages on save

### ISSUE THREAD

**Issue by focdanisch** [rzwitserloot/lombok#2024]
**Describe the bug**
Using lombok 1.18.4 and Eclipse (tested with 4.7.3a and 2018-12), enabling one of the save actions "Organize imports" or "Additional actions" on a class annotated with @FieldNameConstants causes Eclipse to print out error messages when saving the file:

![image](https://user-images.githubusercontent.com/40798549/51310527-1fcc6580-1a47-11e9-8468-184cf21a5032.png)

The file is saved, but no further actions are applied (e.g., removing orphaned imports).

**To Reproduce**
I created a small maven eclipse project which showcases the problem. You can find the code [here](https://github.com/focdanisch/lombok-fieldnameconstants-issue).

The only thing I have changed in the project properties is enabling "Save Actions" under "Java Editor". "Format source code" works without problems, but enabling "Organize imports" or "Additional actions" triggers the error message above.

**Expected behavior**
Eclipse should do its reorganization tasks without error and save the file which is annotated with @FieldNameConstants.

**Version info (please complete the following information):**
 - Lombok version 1.18.4 and 1.18.5 (lombok-edge from website snapshot download)
 - Java jdk1.8.0_191
 - Eclipse 4.7.3a and 2018-12

**Additional context**
The problem does not occur when using lombok 1.18.2. But the field names are of course in the old format (FIELD_XYZ instead of Fields.xyz => see test main method), as the implementation changed in 1.18.4.

**Comment by focdanisch** [comment]
[lombokSaveErrorStacktrace.txt](https://github.com/rzwitserloot/lombok/files/2768630/lombokSaveErrorStacktrace.txt)

Stacktrace after file save.

**Comment by rzwitserloot** [comment]
yup. Reproduced. Trying to see if I can fix this. We can't exactly write a unit test for this kind of thing (at least, we don't have the infrastructure to do it).

**Comment by rzwitserloot** [comment]
this is now available in edge release: https://projectlombok.org/download-edge
