### ISSUE TITLE
[FEATURE] Support for uniform property access

### ISSUE THREAD

**Issue by fwgreen** [rzwitserloot/lombok#2026]
I would like the option of having getters and setters based on the [Uniform Access Principle](https://en.wikipedia.org/wiki/Uniform_access_principle). 
```Java
@Getter(PropertyAccess.UNIFORM)
@Setter(PropertyAccess.UNIFORM)
@AllArgsConstructor
class Person {
    String name;
    Integer age;
}
//...
var name = person.name();
person.age(35);
```
I apologize if this topic has already been covered:  I searched for this feature request before posting and didn't find any references to it.

**Comment by InsomniaKitten** [comment]
I think you will find that [@Accessors](https://projectlombok.org/features/experimental/Accessors) will achieve what you are requesting.

**Comment by fwgreen** [comment]
@InsomniaKitten Thank you!  I hope they keep this feature:  It seems to have been experimental for some time now.
