### ISSUE TITLE
[BUG] inner classes in @Utility classes are static in eclipse, not static in javac.

### ISSUE THREAD

**Issue by rzwitserloot** [rzwitserloot/lombok#2038]
**Describe the bug**
inner methods and fields are auto-marked as 'static' in a `@Utility` class. However, for inner types, evidently in eclipse they are marked as static, but in javac they are not.

**To Reproduce**

```java
@lombok.Utility public class Test {
    public void example() {
        return new Foo();
     }

    public class Foo {}
}
```

The above compiles in eclipse, but in javac will fail, erroring out on the `new Foo` call, saying that `this` cannot be referenced in a static context.

lombok v1.18.4

**Expected behavior**
All inner types in `@Utility` classes should be static, there's no point having them be instance-based.

**Comment by rspilker** [comment]
Cannot reproduce.
