### ISSUE TITLE
[FEATURE] Annotation that allows user to set a POJO property by name

### ISSUE THREAD

**Issue by vhir19** [rzwitserloot/lombok#2041]
**Problem**
I use lombok's @Getter and @Builder almost everywhere. However, both of these implementations expect the property to be known during run-time. I faced a particular challenge while coding recently in which I had to map a set of object properties to a hashmap. Hence the properties could only be referenced using their names during runtime which was nothing but the key in the hashmap. 

**Solution**
I ended up writing a custom annotation and used Java Reflections to achieve something as follows.
```
 @ItemProperty(name = "flow", type = "String")
   private String flow;

  public String getValueByPropertyName(String name){
      for(Field f: Shipment.class.getDeclaredFields()){
         ItemProperty property = f.getAnnotation(ItemProperty.class);
         if(property != null && property.name().equals(name)){
            try {
               return String.valueOf(f.get(this));
            } catch (IllegalAccessException e) {
               return null;
            }
         }
      }
      return null;
   }

   public void setValueByPropertyName(String name, String value){
      for(Field f: Shipment.class.getDeclaredFields()){
         ItemProperty property = f.getAnnotation(ItemProperty.class);
         if(property != null && property.name().equals(name)){
            try{
               f.set(this, getValueOf(property.type(), value));
               break;
            } catch (IllegalAccessException e) { }
         }
      }
   }

   private Object getValueOf(String type, String value){
      switch(type){
      case "Boolean":
         return Boolean.valueOf(value);
      case "Integer":
         return Integer.valueOf(value);
      default:
         return value;
      }
   }

```
**Target audience**
I think such functionality can be inbuilt in lombok and can be used easily when certain properties can be attributes of one model but have to be modelled as a first class construct of another model

_P.S. I am very new to this and Java in the first place, so bear with me for my naviety._

**Comment by vhir19** [comment]
@rzwitserloot Can you help me with this? I feel such a feature can make a nice addition to Lombok. I would be more than happy to get any inputs on this.

**Comment by Maaartinus** [comment]
@vhir19 I'm afraid, you're wrong. This can all be done without Lombok as you have shown and there's nothing Lombok  could do better. It could replace the reflection by field access, but that's no real win. What's worse: You can imagine that there are many possible variants for the above code. You could add support for more primitives, allow xpath-like access, handle casting in various ways....

This may be good for a library, but not for Lombok, where the implementation and maintenance overhead are maybe two orders of magnitude higher.

> I am very new to this and Java in the first place....

I allow myself to give you a piece of advice, I personally consider very important, especially in Java: Never ever swallow an exception. Anything else (including hard crash) is better 99.9% of time.

**Comment by rzwitserloot** [comment]
@Maaartinus covered it all. Property support as a concept is quite a can of worms. There are a billion concerns, and many different takes on it. No matter what lombok would do, we'd disappoint 90% of the folks who want this. Without an _extremely_ fully fledged proposal that really tries to corner ALL the use cases and analysis the full impact on ALL the major frameworks involved in property support, we'll probably just deny/close all PRs/feature requests.
