### ISSUE TITLE
[BUG] lombok.copyableAnnotations key does not work

### ISSUE THREAD

**Issue by RobertMlo** [rzwitserloot/lombok#2042]
**Describe the bug**
I have been writing a REST application using Spring Boot. In one endpoint Spring has to deserialize some JSON into a Java object. This object is DTO, which includes Lombok annotations, such as `@Builder` etc. 

I use also Jackson's `@JsonProperty` annotations there, which does not work. The values for these properties are not set in DTO during deserializing. I had tried to set a `lombok.copyableAnnotations` key to force it, i.e. to copy `@JsonProperty` annotations to the builder class, but it does not help.

**To Reproduce**
`lombok.config` is located in the root of project:

	config.stopBubbling = true
	lombok.copyableAnnotations += com.fasterxml.jackson.annotation.JsonProperty

`DTO` model:

	import com.fasterxml.jackson.annotation.JsonInclude;
	import com.fasterxml.jackson.annotation.JsonProperty;
	import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
	import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
	import lombok.Builder;
	import lombok.Getter;
	import lombok.ToString;

	@Builder
	@Getter
	@JsonDeserialize(builder = ServiceSpecDto.ServiceSpecDtoBuilder.class)
	@ToString
	public class ServiceSpecDto {
		private final String name;
		@JsonProperty("connect_timeout")
		private final Integer connectTimeout;
		@JsonProperty("write_timeout")
		private final Integer writeTimeout;
		@JsonProperty("read_timeout")
		private final Integer readTimeout;

		@JsonPOJOBuilder(withPrefix = "")
		public static class ServiceSpecDtoBuilder {}
	}

`Endpoint` class:

	@RestController
	@RequestMapping("/services")
	class ServiceEndpoint {
		// ...

		@PostMapping
		ResponseEntity<ServiceDto> createService(@RequestBody ServiceSpecDto serviceSpecDto) {
			// Output: ServiceSpecDto(name=test, connectTimeout=null, writeTimeout=null, readTimeout=null)
			System.out.println(serviceSpecDto.toString());
			ServiceDto createdService = serviceFacade.createService(serviceSpecDto);
			return new ResponseEntity<>(createdService, HttpStatus.CREATED);
		}
	}

JSON, which I send:

	{
	  "name": "test",
	  "connect_timeout": 50000,
	  "write_timeout": 50000
	  "read_timeout": 50000
	}

**Expected behavior**
The timeout fields should be filled in the DTO object.

**Version info (please complete the following information):**
 - Lombok version: 1.18.4 and 1.18.6
 - Java: 11.0.2
 - IDE: IntelliJ IDEA 2018.3.3 (Community Edition), Build #IC-183.5153.38, built on January 9, 2019
 - Gradle: 5.1.1

**Additional context**
`build.gradle:`

	plugins {
		id 'org.springframework.boot' version '2.1.2.RELEASE'
	}

	apply plugin: 'java'
	apply plugin: 'groovy'
	apply plugin: 'war'
	apply plugin: 'idea'
	apply plugin: 'io.spring.dependency-management'

	group 'test'

	sourceCompatibility = JavaVersion.VERSION_11
	targetCompatibility = JavaVersion.VERSION_11

	repositories {
		mavenCentral()
	}

	ext {
		springBootVersion = '2.1.2.RELEASE'
		lombokVersion = '1.18.6'
		// ...
	}

	dependencies {
		// Lombok
		compileOnly("org.projectlombok:lombok:${lombokVersion}")
		testCompileOnly("org.projectlombok:lombok:${lombokVersion}")
		annotationProcessor("org.projectlombok:lombok:${lombokVersion}")
		testAnnotationProcessor("org.projectlombok:lombok:${lombokVersion}")

		// ...
	}

**Comment by rzwitserloot** [comment]
copyable annotations end up in the class file just fine. Your example requires a ton of deps. I've tried to reduce it to a simple reproducible test case:

in dir: `ROOT/pkg`

### lombok.config

```
config.stopBubbling = true
lombok.copyableAnnotations += pkg.Ann
```

### Ann.java

```java
package pkg;

import static java.lang.annotation.ElementType.*;
import static java.lang.annotation.RetentionPolicy.*;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

@Target({METHOD, FIELD, PARAMETER})
@Retention(RUNTIME)
public @interface Ann {}
```

### Test.java

```java
package pkg;

import pkg.Ann;

@lombok.Getter @lombok.Builder
public class Test {
	@Ann
	private int foo;
}
```

### test the effect

in `ROOT/pkg`: `javac -cp lombok.jar *.java` to compile it all, then:

`javap -p -v Test` to show that the generated getter has the annotation, and `javap -p -v Test\$TestBuilder` to show that the `foo(int)` method in the generated builder has the annotation.


I suggest you run javap on the produced class files to at least ensure that the annotation is there first. Then, can you make a fully self contained and small test that shows precisely what lombok is doing wrong?

**Comment by rspilker** [comment]
Closed due to no feedback from the reporter.
