### ISSUE TITLE
Lombok specific IntelliJ inspections

### ISSUE THREAD

**Issue by picimako** [rzwitserloot/lombok#2043]
Hi guys,

I created and collected a couple of IntelliJ inspections (Structural Search and Replace templates) for Lombok and I would like to get your opinion about them whether at least the concept of them is correct or they may need refinements. Also if you know any other such code inspection that could help Lombok users, please let me know.

You can find the document here: https://paper.dropbox.com/doc/Lombok-inspections--AX3NQGoGN5gbgPU2AT9FlpZrAQ-A3YaGGSh10Fn3Y7WK5tHX

**Comment by rzwitserloot** [comment]
Not sure I get the point of the 'turn lombok-generated nullchecks via the lombok.NonNull annotation into explicit nullcheck' one, and I can think of a lot more of these, but this is _awesome_.

I'm not too familiar with intellij, and lombok support for intellij is provided via the [lombok intellij plugin](https://plugins.jetbrains.com/plugin/6317-lombok-plugin) which is a separate project. I assume you would add this XML to the config of the plugin at which point these templates show up as available inspections?

The next step would be to file an enhancement over at the [github issue tracker for lombok-intellij-plugin](https://github.com/mplushnikov/lombok-intellij-plugin/issues), possibly with a PR, but if Michael Plushnikov is anywhere near as positively inclined as I am about further IDE support, this should be accepted forthwith :)

If I misunderstood and there's some more action we need to take, by all means let us know :)

**Comment by picimako** [comment]
@rzwitserloot Thanks. :)

The reason I created them is that I didn't see any notification from the Lombok plugin marking these issues. But I will check again to make sure I didn't miss anything.

Right now what I know is that these XML configs can be included in the global config folder of IDEA, or it can be made project specific by putting them into `<project>/.idea/inspectionProfiles/Project_Default.xml` file by the project developers.

I'm not familiar with IntelliJ plugins, so I'm not sure whether they can be used in the plugin in this form or if they would need to be reimplemented in Java.

**Comment by mplushnikov** [comment]
@picimako Please open an issue in https://github.com/mplushnikov/lombok-intellij-plugin. I'm owner of this plugin an can add some usefull inspections to the plugin :)

**Comment by picimako** [comment]
@mplushnikov Alright, I will open an issue there. Thanks. :)
