### ISSUE TITLE
[BUG] Access denied to snapshot repo

### ISSUE THREAD

**Issue by ctoestreich** [rzwitserloot/lombok#2051]
**Describe the bug**
Access denied to snapshots

https://projectlombok.org/edge-releases

Instructions here broken: https://projectlombok.org/download-edge

<img width="512" alt="screen shot 2019-02-27 at 10 18 34 am" src="https://user-images.githubusercontent.com/691357/53505229-14724e00-3a79-11e9-9c70-67626c69a300.png">

**Comment by rzwitserloot** [comment]
maven doesn't need dir listing access as far as I know. But, you can list edge-releases and the subdirs now, so, either way, should be fixed.
