### ISSUE TITLE
[FEATURE]  @SelfLift

### ISSUE THREAD

**Issue by teenriot** [rzwitserloot/lombok#2054]
It would be nice if there would be a possibility to generate override methods that replace the self return type of the superclass. That way boilerplate code for creating fluent methods with inheritance would be reduced without using ugly [self bounding generics](http://makble.com/java-generics-selfbounding)

Example:
```
class Foo {
    @SelfLift  //mark method as 'self liftable'
    public Foo method() {
        return this;
    }
}

@SelfLift  //ask lombok to generate lifted methods
class Bar extends Foo {}
```

would produce Bar as:

```
class Bar extends Foo {
    @Override @SelfLift
    public Bar method() {
        return (Bar) super.method();
    }
}
```

by "lifting" all methods of the superclass which are annoted with @SelfLift.

"self lifting" without marking superclass methods would be better to extend existing thirdparty classes that way. But i see no realistic chance to do this in a stable way without unwanted effects.

(Maybe i had bad design, but that feature would had helped me several times. I guess i miss some critical problems with that idea and it will never be realized. However, thank you for your great work at Lombok.)

**Comment by rzwitserloot** [comment]
Cool feature, but, no can do.

[A] this requires resolution, which is really [difficult](https://github.com/rzwitserloot/lombok/wiki/LOMBOK-CONCEPT:-Resolution).

[B] self-types are in general a missing java feature, and this hack of generating casts is a lot more complex then it sounds. Now imagine generics are involved, for example.

[C] generally this is solved by way of generics, see for example how enums are defined, or Comparable. (`Comparable<E extends Comparable<E>>`). This has various disadvantages compared to a true self-type, but nevertheless it's what is common today.

But mostly the resolution thing.
