### ISSUE TITLE
[FEATURE] @StepBuilder

### ISSUE THREAD

**Issue by Bennett-Lynch** [rzwitserloot/lombok#2055]
Please consider supporting the "Step Builder" pattern.

See:

- http://www.svlada.com/step-builder-pattern/
- http://rdafbn.blogspot.com/2012/07/step-builder-pattern_28.html

I'll copy the pros/cons listed in the first article, since I think they do a good job summarizing the pattern:

> Pros
> 
> 1. User guidance for your API through object creation process step by step.
> 2. API User can call builder's build() method once the object is in the consistent state.
> 3. Reduced opportunity for creation of inconsistent object instances.
> 4. Sequencing initialization of mandatory fields.
> 5. Fluent API.
> 6. No need for providing validate() method for field validation.
> 
> Cons
> 
> 1. Low readability of code needed to implement the pattern itself.
> 2. No eclipse plugin to help with code generation. (On the other hand, there are plenty of code generators for Builder pattern generator).

The cons can mostly be solved by Lombok itself.

**Comment by janrieke** [comment]
Although this sounds like a nice idea at first glance, there are a few other cons. As this feature request already came up several times, there is a wiki page with the reasons why the maintainers think it is not a good idea to add it to lombok: https://github.com/rzwitserloot/lombok/wiki/FEATURE-IDEA:-%22Mandatory%22-fields-with-@Builder

**Comment by Bennett-Lynch** [comment]
Thanks for the reference.  I searched for "step builder" before posting this but was unable to find anything.

That said, I question the reasons listed against it in the wiki.  I think a simple step builder could be implemented very elegantly with Lombok, and I don't think "the cure is worse than the disease".

Taking a desired output from the first article (simplified a little bit):

```
Email email = Email.builder()
    .to("foo@gmail.com")
    .subject("Hello")
    .content("Test email")
    .build();
```

This could be implemented very trivially using Lombok, where you must annotate each field with the step order, and you can optionally give the method a custom name:

```
@StepBuilder
public class Email {
    @Step(1, "to")
    String emailAddress;
    @Step(2)
    String subject;
    @Step(3)
    String content;
}
```

It becomes slightly more complicated if you want to allow multiple options for, e.g., step 2, but I think that is perfectly solvable as well.

Addressing the concerns listed in the wiki:

> 1. It becomes impossible to smear the job of building out across various modules (if this method sets one thing, and that method sets another...)

I'm not sure I follow this, what's the concern here compared to a standard builder?

> 2. You are either forced to first set a, and then b, and then the rest, in that exact order, or you get a combinatorial explosion of interfaces.

That's fine, I _want_ to force an exact order.

> 3. Your autocomplete dialogs and outline views in your IDE get infected with a massive list of weird stuff.

Why does it get infected?  It won't get infected if you require the steps to be declared in specific order and there's no combinatorial explosion.

> 4. You also need to consider the notion of having a builder where you override (set 'again') a value, and the notion of multi-settable things (i.e. it must be set at least once but can be set multiple times, for example with `@Singular`).

Yes, this is slightly more complicated.  I would argue that non-collections should only be able to be set once.  `@Singular` collections could be solved by some type of `.endOfCollection()` method (probably deserving of a better name).

**Comment by janrieke** [comment]
> > 3. Your autocomplete dialogs and outline views in your IDE get infected with a massive list of weird stuff.

> Why does it get infected? It won't get infected if you require the steps to be declared in specific order and there's no combinatorial explosion.

I think this refers to the interfaces for the steps. Those must obviously be public, and this will make them appear in autocompletion dialogs for types.

I'm not a maintainer, but I contributed `@SuperBuilder`. And let me say that this was a hell of a work that took more than 10 full working days overall and more than a year from start to its first release (although admitted that I wasn't a lombok expert before). In comparison, a step builder looks to me as at least equally complex, probably more (just think of all generics possibilities!).
So even if there would be a chance to convince the maintainers that this is a good idea, someone else would have to take it. The maintainers have their hands full with other stuff: bug reports, adaptation to new Java versions, and -- no offense -- adding more useful features.

**Comment by Bennett-Lynch** [comment]
I understand it might be a non-trivial amount of work to implement.  The goal of this issue is only to, as you said, convince the maintainers that it is a good idea.  Prioritization can be addressed separately.

**Comment by rzwitserloot** [comment]
I do think the cure is worse than the disease. I also explained at length in that wiki article what the real cure should be. At risk of sounding arrogant: This is not something we're ever going to implement.
