### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sizzlecar** [rzwitserloot/lombok#2058]
**The get/set method for special name field production is not standardized**
If a bean has a property called mOriginFlagStr, use the `@Data `annotation to generate the method as

   ```
    public String getmOriginFlagStr() {
        return this.mOriginFlagStr;
    }

    public void setmOriginFlagStr(String mOriginFlagStr) {
        this.mOriginFlagStr = mOriginFlagStr;
    }
```

The method of using idea generation is:
```
    public String getMOriginFlagStr() {
        return this.mOriginFlagStr;
    }

    public void setMOriginFlagStr(String mOriginFlagStr) {
        this.mOriginFlagStr = mOriginFlagStr;
    }
```

In some tool classes that copy properties, such as apache's PropertyUtils.copyPropertie(a,b), the default get/set rule is also Idea.
The generation rules are consistent, which causes the property to be unavailable and modified in some scenarios where you need to use get/set.

 - Lombok version 1.16.20

**Comment by rzwitserloot** [comment]
Google around; we've covered this and can't fix it. There are multiple conflicting bean standards; half of them think it should be setMOrigin, the other half setmOrigin. Wontfix.
