### ISSUE TITLE
[BUG] Setting 'lombok.experimental.flagUsage' to ALLOW fails the build

### ISSUE THREAD

**Issue by nbali** [rzwitserloot/lombok#2059]
**Describe the bug**
Setting 'lombok.experimental.flagUsage' to ALLOW fails the build, as it would with ERROR.

**To Reproduce**
```
lombok.experimental.flagUsage = ALLOW
```

**Expected behavior**
It shouldn't show any warning, nor should it fail the build.

**Version info (please complete the following information):**
 - Lombok version 1.18.6
 - Platform irrelevant

**Additional context**
-

**Comment by rzwitserloot** [comment]
heh, woopsie, thanks for the PR. Merged :)
