### ISSUE TITLE
[FEATURE] @TemplateValue @ParseTemplate

### ISSUE THREAD

**Issue by didjee2** [rzwitserloot/lombok#2062]
## Example
```java
        @TemplateValue
        final String name = "John";

        @TemplateValue
        final String lastName = "Doe";

        @TemplateValue
        final int age = 25;

        @ParseTemplate
        final String result = "Hello {name} {lastName} ({age}), how are you?";

        // This would print "Hello John Doe (25), how are you?
        System.out.println(result);
        
        // If possible, maybe @ParseTemplate on top of the method, which will then attempt to parse every string inside the method?
        // Then there is no need to make a separate "result" string.
```

## Example Result:
```java
        // Initializing template map on top, values are added after the variables are created.
        final Map<String, Object> uniqueTemplateValuesMap = new HashMap<>();
        
        final String name = "John";
        uniqueTemplateValuesMap.put("name", name);

        final String lastName = "Doe";
        uniqueTemplateValuesMap.put("lastName", lastName);
        
        final int age = 25;
        uniqueTemplateValuesMap.put("age", age);
        
        // Just an example of a method that could be used (if it were to be like this, ofcourse an import would have to be added) ...
        final String result = LombokUtils.replaceTemplateValues("Hello {name} {lastName} ({age}), how are you?", uniqueTemplateValuesMap);
        System.out.println(result);
```

It would ofcourse be even better if it would be possible like in C#, where they have the $ syntax in front of a string, but I'm not sure if that's possible.

Just for reference, I haven't really searched much for a library that does something like this.

**Comment by Maaartinus** [comment]
> where they have the $ syntax in front of a string, but I'm not sure if that's possible.

I'm afraid, it's not as Lombok comes after the parser. When the parsing fails, there's no Lombok there.

---

> ofcourse an import would have to be added

Currently, Lombok is not needed at runtime and I'm rather sure, the authors want this to stay as is.

But that's no problem here, as an implementation like
```
final String result = "Hello " + uniqueTemplateValuesMap.get("name") + ...
```
would be only slightly more complicated (I know, it was just an example).

Avoiding the map should also be possible, as everything is known at compile time. This would reduce the runtime-overhead to exactly zero.

---

I'm afraid that `@TemplateValue` may make this feature much less usable. As the only advantage of `@ParseTemplate` is a shorter (and more readable) syntax, requiring writing more is counterproductive.

On the one hand, it feels more error-proof, OTOH it's a pain. Lombok could actually show a compile-time error when it sees something like `"Hello {name} {lstName}..."` (note the typo).

---

I guess, Lombok could do it, but I'm not sure, if it fits and whether it's useful enough. There were proposals about adding multi-line and raw strings long time ago, which are now definitely abandoned as it'll come in Java. I have no idea, how big the implementation overhead would be.

**Comment by didjee2** [comment]
What will come in Java exactly? And also, something I forgot to mention, this would be extra useful if that would be possible for string coming out of configuration / language files.

**Comment by rzwitserloot** [comment]
As explained, we can't do it, unfortunately.
