### ISSUE TITLE
[FEATURE] @Getter(type="")

### ISSUE THREAD

**Issue by nlwillia** [rzwitserloot/lombok#2065]
Sometimes a field has a type that is wider inside the class than it should be exposed as outside the class.

For example an implementation that's only externally exposed via an interface.
```
public class SomeBean {
    private FooImpl foo;

    public Foo getFoo() {
        return foo;
    }
}
```

With `@Getter` on the property, the exact type of the property is exposed.

It would be nice if there were an option that could reference a supertype or interface of the actual type for the getter to return.

A more general capability (ex: the `@Getter(processor)` mentioned in #1957) could make this unnecessary, but even if there's resistance to that kind of manipulation this might still be something to consider.

I've had several cases recently where I intended to `@Getter` a field but realized it would expose a type I didn't want to.

**Comment by rzwitserloot** [comment]
This does not come up enough. There's a serious cost associated with piling parameters onto `@Getter`, such a setting could only be applied to the field getter, and how much typing did you truly save between `@Getter(Foo.class)` versus `public Foo getFoo() {return foo;}`? Some - but note that generics would turn this feature into a mess of an implementation and documentation.
