### ISSUE TITLE
Java 6 compilation error when field has javadoc

### ISSUE THREAD

**Issue by tiagocorreia86** [rzwitserloot/lombok#2066]
If the private field has javadoc then the javac (for Java 6) compilation fails.

The steps to reproduce it:

- Have your code running with Java 6.
- Use the latest lombok version (however the issue occurs with previous versions also)
- Create a class like this:

```
import lombok.Getter;

@Getter
public class TestLombok {

    /**
     * The currency
     */
    private String currency;
    
}
```

When building the project (I use intellij Build tool) I get the following error:
`Error:java: error: Lombok annotation handler class lombok.javac.handlers.HandleGetter failed on C:\Users\C60935\TestLombok\lombok\src\main\java\TestLombok.java: java.lang.NoSuchMethodError: java.util.Map.putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;`

This happens because in Java 6 the Map class doesn't contain the method putIfAbsent.
The result is that it's not possible to use javadoc for fields when using Java 6.

**Comment by rspilker** [comment]
I think I've fixed it. Can you please verify it in a soon to be released [edge release](https://projectlombok.org/download-edge)?

**Comment by tiagocorreia86** [comment]
It's fixed in the latest edge release!

**Comment by rspilker** [comment]
Thanks for the feedback!
