### ISSUE TITLE
[FEATURE] @Singular support for LinkedHashMap

### ISSUE THREAD

**Issue by rlangenfeld** [rzwitserloot/lombok#2067]
**Describe the feature**
Add support for LinkedHashMap for the `@Singular` annotation. 
If you look at the list of supported types it is not in there:
[https://projectlombok.org/features/Builder#singular](https://projectlombok.org/features/Builder#singular)

Currently the BuildSingularMaps generates a LinkedHashMap under the hood so this should be easy to add support for:
[https://github.com/rzwitserloot/lombok/blob/master/test/transform/resource/after-delombok/BuilderSingularMaps.java#L168
](https://github.com/rzwitserloot/lombok/blob/master/test/transform/resource/after-delombok/BuilderSingularMaps.java#L168
)
**Describe the target audience**
Anyone who uses objects that need to preserve key order.

**Additional context**
We need LinkedHashMaps in our client interfaces so that our clients will respect JSON ordering. We are using lombok annotate pojos but we current we cannot apply the @Singular annotation to a LinkedHashMap type. Map will not suffice in this case for us.

**Comment by Maaartinus** [comment]
I'm afraid, it can't work as (for more than two elements) `@Builder` generates an unmodifiable Map wrapping a `LinkedHashMap`. The resulting map is not a subclass of `LinkedHashMap`. The good news is that key order gets preserved, the bad news is that you can't modify the map and can't declare it as anything but one of the three interfaces listed in the doc.

> we cannot apply the `@Singular` annotation to a LinkedHashMap type

Indeed, you can't, but you can have a `@Singular private final Map<K, V> map;` and trust the builder to honor your order.

Disclaimer: I'm not a project maintainer. I also may be wrong, now and ever.

**Comment by derekm** [comment]
Lombok could provide itself with its own `unmodifiableLinkedHashMap` call to make this work.

We're using JAX-RS interfaces along with Jersey's `WebResourceFactory` and MicroProfile Rest Client to get POJOs filled up with JSON from the wire such our POJOs honor the JSON-ordering of keys.

**Comment by Maaartinus** [comment]
@derekm Lombok is a compile-time-only dependency. There are a few useful things which could be done if it was present at runtime, but as it stands, it can have no own classes at all.

**Comment by rspilker** [comment]
As @Maaartinus already said, we already preserve insertion order.

We're not planning to add new types. Possibly it is possible for you to switch to Guava types?

**Comment by rspilker** [comment]
Regarding "We're not planning to add new types": I didn't mean that we're not willing to support more existing Collection types. I meant, like @Maaartinus write, Lombok is a compile-time dependency, and we're not willing to change that any time soon. If there is a _popular_, existing library that has an UnmodifiableLinkedHashMap, we're willing to add it to the supported Collection types.

**Comment by derekm** [comment]
I was assuming Lombok could inject at compile-time its own subclasses as needed.

I'm not very familiar with the proprietary compiler extensions that Lombok is hooking into, but maybe the way I imagine Lombok injecting its own internal classes is not possible.

Unfortunately, it is only since Java EE 7/8 and MicroProfile that LinkedHashMap is becoming a common and preferred "interface", invalidating all kinds of static analysis tools and former best practice around always using the Map interface.

If it is impossible for Lombok to inject its own implementations, we may have to take this argument to a library like Guava who is stuck in the now-worst-practice mode of "always use a Map!"
