### ISSUE TITLE
[FEATURE] @CustomLog(factory=xxx.class, type=xxx.class, method="getLogger", topic="xxxx")

### ISSUE THREAD

**Issue by jearton** [rzwitserloot/lombok#2068]
I want an annotation such as the title. The define is:

```java
public @interface CustomLogger {

    Class<?> factory();

    Class<?> type();

    String method() default "getLogger";

    /**
     * @return The category of the constructed Logger. By default, it will use the type where the annotation is placed.
     */
    String topic() default "";
}
```

Usage example:

```java
public class LoggerFactory {
     public static x.y.Logger getLogger(Class<?> clazz){
          // some codes
    }
}

@CustomLogger(factory=x.y.LoggerFactory.class, type=x.y.Logger.class)
public class LogExample {
}
```

Will generate:

```java
public class LogExample {
     private static final x.y.Logger log = x.y.LoggerFactory.getLogger(LogExample.class);
}
```

Because I use a `LoggerFactory` which is written by my company and I hope lombok could be combined with this case.

**Comment by rzwitserloot** [comment]
This barely saves any typing. But it does save you from having to repeat your class name.

This feature is far too exotic to warrant inclusion unfortunately. However, I do have a tip for your company: Have a look at google's fluentlogger stuff; they get to the classname without requiring you to pass it. Maybe you can adapt their trick?
