### ISSUE TITLE
[FEATURE] Benchmark method call

### ISSUE THREAD

**Issue by mmaryo** [rzwitserloot/lombok#2071]
Provide a simple way to benchmark method call.

```
@StopWatch(TimeUnit.SECONDS, LogLevel.INFO)
public void test() {
    // process
}
```

generate

```
public void test() {
    StopWatch sw = new StopWatch();
    sw.start();
    // process
    if(log.isInfoEnabled()) {
        log.info("ClassName.test() run with " + sw.getTime(TimeUnit.SECONDS) + "s");
    }
}
```
 
It will be help people to know quickly code perfomance

**Comment by rspilker** [comment]
That's not the way to benchmark code.

Really, first read up on the subject, it's not up to me to explain. Some keywords: JIT, Tiered Compilation, Hotspot, Garbage Collection.

You probably want to use something like the [Java Microbenchmark Harness](https://openjdk.java.net/projects/code-tools/jmh/).
