### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by hadix-lin** [rzwitserloot/lombok#2073]
**Describe the feature**
`@Accessors(both=true)`
generate both setXXX/getXXX and fluent forms accessors simultaneously. 
 
**Describe the target audience**
someone want to use fluent code , simultaneously , need some third tool process setXXX/getXXX ,for example jackson .

In my project , use many method reference like ClassName::getXXX . I want to shortcut the code to ClassName::XXX, simultaneously, keep the jackson working as well.

**Comment by Maaartinus** [comment]
This has been discussed already... and refused by the team members. Having two getters+setters per field feels much worse than any alternative.

Some tools can be configured to use the fields directly. This is surely true for Hibernate and Gson;  I guess, Jackson can it, too.

**Comment by rzwitserloot** [comment]
Discussed and refused many times.
