### ISSUE TITLE
[BUG] Field names starting with $ cannot be recognized by @Data

### ISSUE THREAD

**Issue by ydq** [rzwitserloot/lombok#2075]
Field names starting with **`$`** cannot be recognized by `@Data`（or `@Getter`/`@Setter` on Class） 
~~~java
@Data
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Model {
	String $ref;
	String name;
}
~~~

 - Lombok version：1.18.6
 - Platform：eclipse 2018-12 (4.10.0)（windows）

![image](https://user-images.githubusercontent.com/8097340/54583234-88878c80-4a4e-11e9-8309-6d3d33b4a3fe.png)

`@FieldDefaults(level = AccessLevel.PRIVATE)`  also doesn't recognize 

But `@Getter`/`@Setter` works on the field

![image](https://user-images.githubusercontent.com/8097340/54583911-ab1aa500-4a50-11e9-8d43-79b5c41a5274.png)

---
 - Lombok version：1.18.6
 - Lombok-plugins version：v0.23-2018.3
 - Platform：IntelliJ IDEA 2018.3.5 (Community Edition)

![image](https://user-images.githubusercontent.com/8097340/54583385-ea47f680-4a4e-11e9-8ffd-6f3a0f0a365e.png)

`@FieldDefaults(level = AccessLevel.PRIVATE)`  can be recognized

But `@Getter`/`@Setter` works on the field

![image](https://user-images.githubusercontent.com/8097340/54583992-fb920280-4a50-11e9-928a-71f8da8f52d0.png)

**Comment by Maaartinus** [comment]
That's not a bug, that's a feature: https://projectlombok.org/features/Data

> By default, any variables that start with a $ symbol are excluded automatically. You can include them by specifying an explicit annotation (@Getter or @ToString, for example) and using the 'of' parameter.

**Comment by ydq** [comment]
> That's not a bug, that's a feature: https://projectlombok.org/features/Data
> 
> > By default, any variables that start with a $ symbol are excluded automatically. You can include them by specifying an explicit annotation (`@getter` or `@tostring`, for example) and using the 'of' parameter.

@Maaartinus  Thank you for your reply , so  `@FieldDefaults(level = AccessLevel.PRIVATE)`  can recognize field start with a $ symbol in IDEA, it's IDEA plugin's bug?
