### ISSUE TITLE
[QUESTION] Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [rzwitserloot/lombok#2076]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by rzwitserloot** [comment]
It does not. The lombok git repo is too big for the free account, and we don't particularly care about these things (the obvious upside, to me anyway, of CI is that you know the tests pass. Which is great and all, but we can't truly decree a lombok release to be stable unless we know it runs well in the various IDEs. A true automated test that is fully trustworthy includes firing up a great many VMs with various releases of eclipse, intellij, and various JVM versions, and custom eclipse plugins to run tests within eclipse to boot. Given that GUI is involved I don't think docker is up to the job, and it'd be one heck of an endeavour to build all that infra).

But, feel free to put in some legwork on making it happen. Presumably it would start by asking travis-CI if they want to make an exception and allow lombok's git repo even though it exceeds their size limits.

Lets hold any further discussion on making this happen, if you are willing to do the effort, to the forum.
