### ISSUE TITLE
[BUG] Eclipse installation

### ISSUE THREAD

**Issue by gorokhmn** [rzwitserloot/lombok#2079]
Default Eclipse Lombok installation does not work out of the box.

**Details:**
After executing command `java -jar lombok-1.18.6.jar` the Lombok Eclipse installation is completed. The installation does the following steps:
1. Copy lombok.jar into Eclipse folder
2. Add line `-javaagent:C:\eclipse\lombok.jar` at the end of `eclipse.ini` file.

The problem is in the step #2. The line  `-javaagent:C:\eclipse\lombok.jar` is **added** at the end of `eclipse.ini` file. However, the line should be **inserted** after line `-vmargs`.

Below is an example of wrong `eclipse.ini` file generated by Lomboc installer.
After this installation Lombok is not recognized.
```
. . .
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=1.8
-Xms256m
-Xmx1024m
--add-modules=ALL-SYSTEM
-javaagent:C:\eclipse\lombok.jar
```
The fixed example `eclipse.ini` file is below. Lombok is recognized.
```
. . .
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-XX:+UseG1GC
-XX:+UseStringDeduplication
-javaagent:C:\eclipse\lombok.jar
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=1.8
-Xms256m
-Xmx1024m
--add-modules=ALL-SYSTEM
```

Lombok version: 1.18.6
Eclipse: Oxygen-2

**Comment by rzwitserloot** [comment]
Can't reproduce: I have a similarly messed up eclipse.ini whilst installing the latest (2019-03, I don't think it has names like 'oxygen-2' anymore), with various lines, notably the --add-modules one, repeated. Lombok adds itself to the very end and.. loads fine. If I update the -vm line to explicitly point to a java1.8 VM (which doesn't even support --add-modules), it still works.

I'm mystified as to how eclipse processes these ini files. Does it just know to skip --add-modules on 1.8 VMs?

At any rate, in either case, lombok loads fine.

Given that I can't reproduce this problem I'm a bit hesitant to just move the javaagent line to for example immediately following the `-vmargs` line, or, to put it right before the first `--add-modules` if it's there, and at the end of there's no such line.

Given that Oxygen-2 is v4.7, and I tend to keep up to date with these, and it works fine now, I don't think it's an oxygen-2 specific issue.

Which raises the question: What DOES trigger this problem?

I've also tried to put the lombok line immediately after an --add-modules line, and then with both java8 and java11 as -vm. Lombok loaded fine in all cases.

Eclipse: 2019-03
Platform: Mac

parked; close if no feedback by 2019-04-08.

**Comment by rspilker** [comment]
Closed due to no feedback from reporter.

**Comment by Katharsas** [comment]
This is a weird one.
I had the exact same problem. It didn't work, then i moved the `-javaagent...` line up, then it worked, then i moved it back to the end and it STILL worked. Then i installed a completely new Eclipse just to test this, and this new installation worked out of the box with the line being at the end. So yeah, not idea whats going on here.
