### ISSUE TITLE
[BUG] JavaDoc API does not work with frames

### ISSUE THREAD

**Issue by gorokhmn** [rzwitserloot/lombok#2080]
API JavaDoc **frames** does not work.
Steps to reproduce:
1. Navigate to [https://projectlombok.org/api/overview-summary.html](url)
The page is opened OK.
2. Click `FRAMES` link. The familiar JavaDoc page with frames is opened but all panes are blank with message `projectlombok.org refused to connect`.

**Comment by rzwitserloot** [comment]
we added CSP headers and the html generated by the javadoc tool is... quaint, to say the least. I'll try to address it.

Separately, the javadoc tool is rather crappy in general, and tries to load lots of things that don't exist. I've addressed that part in a recent commit too.

The frames version loads again, and hopefully, soon it won't trigger a bunch of CSP violations either.
