### ISSUE TITLE
Windows- or Installer-free version of JAR file

### ISSUE THREAD

**Issue by brabster** [rzwitserloot/lombok#2084]
**Describe the feature**

A version of the lombok jar without Windows software.

The OWASP dependency check detects the two `.dll` files in the lombok installer.

- `lombok/installer/WindowsDriveInfo-i386.dll`
- `lombok/installer/WindowsDriveInfo-x86_64.dll`

On Linux that requires installation of a significant amount of extra software to scan those dependencies for vulnerabilities, and can raise questions with security teams. If these dependencies are not required on Linux, a Lombok jar without these dependencies would be helpful.

I'm not sure whether the installers aren't needed at all when you're using Lombok as a build dependency (as I am). In that case, then perhaps just a slim jar that doesn't contain the installers at all would be simpler.

Otherwise, a windows-free version so that use on Linux systems can avoid installing Windows software should work fine.

**Describe the target audience**
People who work on Linux and use the [OWASP dependency check tool](https://www.owasp.org/index.php/OWASP_Dependency_Check).

**Additional context**
I'm not sure I can use Lombok with these Windows dependencies, because I doubt I'll be allowed to install the necessary dependencies to scan those files in my target environment.

**Comment by rspilker** [comment]
We're very hesitant on supplying different dependencies. Lombok is a compile-time dependency, and should not be included in the end product.

We prefer to generate one artifact. The current jar file is small, and it's easier for our maintainers and users to only have this one jar.

Would renaming the .dll inside the jar solve your problem? On Windows only, we extract the .dll file to a temp directory, and only when the installer is run.

I have no idea why you are referring to the OWASP tool, but if it complains about compile-time dependencies, you might want to file a bug report with them.

**Comment by brabster** [comment]
Thanks for the prompt update!

Regarding the compile-time nature of the dependency (certainly an important point), it still means that the dependency needs to be shipped into the infrastructure, specifically to the build server. In some high-security environments, that could be problematic - not sure if it is for me yet. I can suppress the alert, it came as something of a surprise to find Windows binaries present in my build!

Not sure if renaming the dll would help - even if it did, trying to hide the nature of the binaries doesn't sound like the right answer.

**Comment by rspilker** [comment]
I'm not sure if the renaming helps, but I did it anyway, because it  was a possible solution and really simple to implement.

**Comment by rspilker** [comment]
If the scanner still detects it, we can do some simple byte magic. I'm closing this issue, because we have no plans to ship platform dependent jar files, nor a separate installer.

**Comment by abccbaandy** [comment]
Just want to reference this commit.
https://github.com/rzwitserloot/lombok/commit/75601240760bd81ff95fcde7a1b8185769ce64e8

It "fix" the `dependency-check-maven`'s `.NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned.` issue.

It took me a day try to find out why my spring project got .NET issue :D
