### ISSUE TITLE
[FEATURE] constructor documentation enhancement (VERY minor)

### ISSUE THREAD

**Issue by jottinger** [rzwitserloot/lombok#2087]
**Describe the feature**
This is a documentation enhancement. 

@Data is documented as including @RequiredArgsConstructor as one of the implied annotations. However, if it finds constructors already in the code, it does not apply the @RequiredArgsConstructor, even if this would not clash with an already existing constructor. The documentation does not point this out.

**Describe the target audience**
Readers of the website.

**Comment by jottinger** [comment]
In `website/templates/constructor.html` there's already text to this effect (in a parenthetical, see  https://github.com/rzwitserloot/lombok/blob/master/website/templates/features/constructor.html#L12 . I'd suggest putting <em> tags around the relevant phrase in the parenthetical, just for emphasis. I would be happy to submit a PR for this, but it's so minor that chances are it'd be discarded just to save disk space. :)

**Comment by jottinger** [comment]
See also https://github.com/rzwitserloot/lombok/blob/master/website/templates/features/Data.html#L10 which is a better spot for an emphasis than in the constructor annotation documentation.

**Comment by rzwitserloot** [comment]
I'd say the highlighted line (L10 on Data.html) is.. just what you're asking for, no?

Should we mention it earlier (for example around line  https://github.com/rzwitserloot/lombok/blob/master/website/templates/features/Data.html#L8 instead)?

**Comment by rspilker** [comment]
No response from reporter, closing issue.
