### ISSUE TITLE
onlyExplicitlyIncluded still does not work

### ISSUE THREAD

**Issue by sierracc** [rzwitserloot/lombok#2089]
Please reopen bug #1709 (can't do it).

Still seeing this problem in Eclipse+Maven with 1.18.6.
My comments are in #1709.

**Comment by rzwitserloot** [comment]
See #1709 - tried to reproduce and cannot, so it won't be reopened. If you have a testcase I can use to reproduce it, please comment here.

**Comment by sierracc** [comment]
Thanks for checking. Tried your and my testcase again today, can't reproduce it on my computer with Win10 x64, Oracle JRE 8 (1.8.0_211-b12) anymore - not sure why.
But when trying your test on Ubuntu, with either lombok 1.18.6 or even edge-SNAPSHOT (see screenshot below), with Oracle JRE 8 build 1.8.0_144-b01 and JRE 7, I get console output:
```
false
false
```
I don't know what the reason is, but it seems not to be fixed, although depending on unknown side-effects.

![grafik](https://user-images.githubusercontent.com/4683220/57088184-01daf600-6d02-11e9-8ff5-d8d3f27b1224.png)

**Comment by rspilker** [comment]
Can you verify the version of lombok used by your Eclipse by opening _Help_ -> _About Eclipse SDK_ and scrolling the top right credits area down?

![image](https://user-images.githubusercontent.com/93318/57252221-f104ea00-704b-11e9-8dc8-f57ffccb4523.png)

**Comment by sierracc** [comment]
The about is showing 1.16.20 on the Ubuntu machine where the bug occurs.
Sorry, it was my mistake to forget that changing the Maven dependency alone is not enough. Mixed Maven and Eclipse plugin versions are hard to figure out if you're used to just look at the pom.
Couldn't make Eclipse launch after installing recent Lombok plugin there (JVM terminated. Exit code=1), but I suppose it's due to Eclipse Luna being too old to be supported.
I'll update and see, for me this issue is closed. Thanks for your help!
