### ISSUE TITLE
@Data add callSuper default true

### ISSUE THREAD

**Issue by AKcheng** [rzwitserloot/lombok#2091]
When using the @data annotation, it is recommended to add the parent property to the hashcode toString by default

**Comment by rzwitserloot** [comment]
This feature already exists; config keys `lombok.toString.callSuper` and `lombok.equalsAndHashCode.callSuper`.

Changing the default 'out of the box' is not going to happen; that'd be a breaking change.

NB: This is a bad recommendation. You should think about the hierarchy and the relations between child and parent and then make the correct decision. There is no recommendation. Knowledge and some thought is required.
