### ISSUE TITLE
[BUG] Inconsistency with toBuilder() with/without @Singular

### ISSUE THREAD

**Issue by nbali** [rzwitserloot/lombok#2098]
**Describe the bug**
The copy behaviour regarding lists (and I assume other collections) changes depending on the presence of @Singular annotation on the field.

**To Reproduce**
```java
    public static void main(String[] args) {
        ArrayList<String> list1 = Lists.newArrayList("list1");
        ArrayList<String> list2 = Lists.newArrayList("list2");
        
        ToBuilderTester t = new ToBuilderTester(list1, list2);
        System.out.println(t);
        
        t = t.toBuilder().build();
        System.out.println(t);
        
        list1.add("invalid");
        list2.add("invalid");
        System.out.println(t);
    }
    
    @Data
    @Builder(toBuilder = true)
    public static class ToBuilderTester {
        @Singular
        private List<String> list1Values;
        // no @Singular
        private List<String> list2Values;
    }
```
Output:
```
ToBuilderTester(list1Values=[list1], list2Values=[list2])
ToBuilderTester(list1Values=[list1], list2Values=[list2])
ToBuilderTester(list1Values=[list1], list2Values=[list2, invalid])
```

**Expected behavior**
I would prefer this:
```
ToBuilderTester(list1Values=[list1], list2Values=[list2])
ToBuilderTester(list1Values=[list1], list2Values=[list2])
ToBuilderTester(list1Values=[list1], list2Values=[list2])
```
I mean the whole concept of `toBuilder()` is to create a completely new instance like we would with `builder()` without the need to copy over every property manually. Changes on the old shouldn't affect the new, and vica versa.

**Version info (please complete the following information):**
 - v1.18.6 "Envious Ferret"
 - javac 1.8.0_191

**Comment by nbali** [comment]
@fpeter8 FYI

**Comment by Maaartinus** [comment]
> I mean the whole concept of toBuilder() is to create a completely new instance like we would with builder() without the need to copy over every property manually.

This would require deep cloning and that's sort of impossible to implement (in an efficient and generally useful way).

The difference between fields with and without `@Singular` ist that
```
@Singular MyShinyListNobodyHasEverHeartAbout<String> list3;
```
would not compile as the annotation requires a collection/map it knows. This makes the depth-1 cloning possible as all implementations are known.

**Comment by nbali** [comment]
Actually, not impossible - at least with limitations. Known collections can be deep copied easily. If an object has the lombok toBuilder() method, then it could be called recursively, so deep copy is still an option.

BUT that is not my point here. I can even accept that this does no deep-copy whatsoever, because supporting everything is borderline impossible, and requires something like mapstruct. BUT if that is the concept here, then `@Singular` shouldn't break that.

**Comment by rspilker** [comment]
Hmm, currently, we use `@Singular` to add behavior as well as a trigger to signal we're dealing with one of the known collection types/ The field not annotated with `@Singular` are treated as `Object`.

One could argue that IF the type of the field is one of the types supported by `@Singular`, we can give it also special treatment.

However, adding `@Singular` now also checks if it is one of the supported types. If it's not, you get an error. This make it possible for us to support other collection types in the future.

But if we give unannotated fields also special treament, adding a new supported collection types would change existing code, making it a (potential) breaking change.

Is there a good reason to not just add a singular annotation?

**Comment by rspilker** [comment]
Closed due to no feedback from reporter

**Comment by nbali** [comment]
Sorry for the delay.  

Anyway your suggestion is that we should add a @Singular annotation to _every_ collection we have in our code? IMO it would be viable if there would be a way to configure this at lombok.config. If it requires actually writing it out constantly, then it's not a viable option for any project. Devs are lazy. They will forget it.

**Comment by nbali** [comment]
Or maybe the @Builder should have a value like alwaysSingular or copyCollections, and that should be configurable at the lombok.config.

**Comment by nbali** [comment]
@rspilker
