### ISSUE TITLE
[FEATURE] @Getter for a @Log

### ISSUE THREAD

**Issue by wedsa5** [rzwitserloot/lombok#2102]
@Getter does not create getters for static fields (when placed on the class).
If you want the getter for a static field, you must put the @Getter on the static field directly.

If you use the @Log (@Slf4j, ect...), it creates the static log field for you.

If you want a getter for the logger, you would need to put the @Getter on the logger field. 

You can't use both annotations together.

2 options:
Please add a parameter to @Getter(getStatic=true)
OR
Please add a parameter to @Log(getter=true)

**Comment by rspilker** [comment]
I don't think that this is a use-case that occurs a lot. A handwritten getter would in my opinion not be a big penalty for this.
