### ISSUE TITLE
Getters, Setters and Fields unavailable using @Data with @Accessors fluent, chain

### ISSUE THREAD

**Issue by everywwwthing** [rzwitserloot/lombok#2103]
Java Version: 1.8
Gradle Version: 4.10.1
Android Gradle Plugin Version: 3.3.0
Lombok Version: 1.16.0
Andriod Studio Version: 3.4

```
@Accessors(chain = true, fluent = true)
@Data
public class MyClassName {
    String id;
    String userId;
}
```

![smclass](https://user-images.githubusercontent.com/49056982/56422534-90448600-62c5-11e9-8d8a-8e919f270a9b.png)
![seedmasterrs](https://user-images.githubusercontent.com/49056982/56422667-44dea780-62c6-11e9-8408-6253c69cd259.png)

Don't generate getters, setters and properties are invisible, but is visible with `@Data`

```
@Data 
public class MyClassName {
    String id;
    String userId;
}
```
![umrsclass](https://user-images.githubusercontent.com/49056982/56422547-a05c6580-62c5-11e9-937c-b2eea7dc8398.png)
![usermasterrs](https://user-images.githubusercontent.com/49056982/56422699-6770c080-62c6-11e9-9a5b-e4030071318f.png)

The above issue disappears when the project is built in Android Studio <= 3.3 with exactly same setup

**Comment by rspilker** [comment]
Please test with a more recent version of lombok, we've fixed several Android Studio problems in the meantime.

**Comment by rspilker** [comment]
Oh, and not all experimental features are supported by the intellij plugin.

**Comment by rspilker** [comment]
Closed due to no feedback from reporter

**Comment by everywwwthing** [comment]
Sorry for not following up. For time being we reverted back to old studio version. Will try out different install and try once more as suggested.
