### ISSUE TITLE
[BUG] @EqualAndHashCode problems with subclasses

### ISSUE THREAD

**Issue by fortitude001** [rzwitserloot/lombok#2105]
When the superclass has an annotation @EqualAndHashCode ,the lombok will generate a CanEqual function , and the CanEqual function is Protected. As the superclass, the subclass with an annotation @EqualAndHashCode will generate a Protected CanEqual function, too.

But in the java code,the CanEqual function does not has an annotation @Override, So the Eclipse will get an problem:"missing override annotation".

**Comment by rspilker** [comment]
Unfortunately, lombok does not have access to the code of the superclass. This would require resolution. You can instruct lombok to add `lombok.Generated` on the generated methods. Isn't it possible to instruct Eclipse to ignore generated code?
