### ISSUE TITLE
[FEATURE]  添加ToJsonString注解

### ISSUE THREAD

**Issue by MrXuan3168** [rzwitserloot/lombok#2110]
现在的web开发一般都是通过json格式进行数据发送和接收，传统的 toString，转化成 JsonObject 效率比较低，而且可读性比较差，可以考虑添加一个toJsonString的注解，让 toString 出来的String 是Json 格式的。

**Comment by MrXuan3168** [comment]
例如：

**Comment by MrXuan3168** [comment]
@Override
    public String toString() {

        final StringBuilder sb = new StringBuilder("{");
        sb.append("\"fileName\":\"")
            .append(fileName).append('\"');
        sb.append(",\"type\":\"")
            .append(type).append('\"');
        sb.append(",\"size\":")
            .append(size);
        sb.append(",\"FileMD5\":\"")
            .append(FileMD5).append('\"');
        sb.append(",\"Base64fileData\":")
            .append(Arrays.toString(Base64fileData));
        sb.append('}');
        return sb.toString();
    }

**Comment by janrieke** [comment]
This has been discussed a few times already. JSON serialization is far too complex to be implemented in Lombok. Use a dedicated serialization framework instead; for instance, Jackson works very nicely in combination with Lombok.

**Comment by jearton** [comment]
这个适合使用JSON序列化库，而不是手动拼字符串
