### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by xudrogoon** [rzwitserloot/lombok#2112]
Annotation Get /set method for Date class involving deep clone and shallow clone

like this ：

public Date getCreateDate() {
       return (Date) createDate.clone();
   }

   public void setCreateDate(Date createDate) {
       this.createDate = (Date) createDate.clone();
   }

May expose internal representation by incorporating reference to mutable object

**Comment by rspilker** [comment]
Solution: use `LocalDate`, is immutable.

https://github.com/rzwitserloot/lombok/wiki/ISSUES:-Why-we-close-issues-without-a-lot-of-explanation.
