### ISSUE TITLE
How to solve the thread security problem of Date Type in Getter and Setter?

### ISSUE THREAD

**Issue by leyan95** [rzwitserloot/lombok#2116]
In my daily development, the `Getter` method of `Date` is written like this, How is this code generated in Lombok .class files?
```java
private Date a;

public Date getA() {
  if (a != null) return (Date) a.clone();
      return null;
  }
  public void setA(Date a) {
      this.a = a == null ? null : (Date) a.clone();
  }
```

**Comment by Maaartinus** [comment]
Just drop `java.util.Date` and related crap. There's `java.time` containing much better *immutable* classes.

While Lombok could in theory clone known classes, it does not. There were quite a few discussions and proposals, but none made it very far.

While `Date` could be supported rather easily, I don't think anyone will ever implement it as it's nothing but a proof that Java authors had a bad day.

**Comment by leyan95** [comment]
@Maaartinus I've replaced it with Local Date. Thank you for your reply.

**Comment by pashazadeh** [comment]
`clone()` method is not so bulletproof, and it can be cause of some security problems. Consider

`public class HackersDate extend Date {
  @Overrider
  public Date clone() {
    return this;
  }
}`

with this a suspicious user can mutate internals of our class.
What about using the time based constructor of java.util.Date?
