### ISSUE TITLE
[FEATURE] Provide a @ModelGetter annotation

### ISSUE THREAD

**Issue by pashazadeh** [rzwitserloot/lombok#2117]
Some MVC frameworks (such as Struts os Stripes) do not instantiate Model internal objects, so accessing the model should be something like:

```
private SomeType something;

public SomeType getSomething() {
  if (something == null) {
    something = new SomeType();
  }
  return something;
}
```

And as you can see its lot of boilerplate code using such MVC frameworks. 

So I propose creating a `ModelGetter` annotation to handle this issue.

I was thinking to make the code as
`@Getter private SomeType something = new SomeType();`
but there are places which we assign `null` to `something`. So a new instance of the object must be created within getter method, and the getter can not be a simple getter method.

----

I believe annotation can have an optional `Class<?>` type parameter of type which will be used to create the instance variable from. So it can used as

```
@ModelGetter(type=ArrayList.class)
private List<Integer> someList;
```
instead of
```
private List<Integer> someList;

public List<Integer> getSomeList() {
  if (someList == null) {
    someList = new ArrayList<>();
  }
  return someList;
}
```

**Comment by pashazadeh** [comment]
I believe annotation can have an optional `Class<?>` type parameter of type which will be used to create the instance variable from.

**Comment by janrieke** [comment]
But this will only ever work for classes with a no-args constructor. That seriously limits the applicability of this feature.
Besides, in my years of Lombok usage, I never stumbled upon a case where this would be helpful. This makes me think that it would be feature just to work around limitations/bad design of certain frameworks.

Disclaimer: I'm not a Lombok maintainer.

**Comment by rspilker** [comment]
Ah, you're re-inventing Singletons?

Possibly you can use [`@Getter(lazy=true)`](https://projectlombok.org/features/GetterLazy). That would also take care of your threading issues.

https://github.com/rzwitserloot/lombok/wiki/ISSUES:-Why-we-close-issues-without-a-lot-of-explanation.

**Comment by pashazadeh** [comment]
Nope, obviously it is not singleton, because the holder object itself is prototype. I saw `lazy=true` on `@Getter` annotation, but it has some synchronization which is not necessary for Model objects.
