### ISSUE TITLE
[BUG] Lombok 1.18.8 changes the exception message for @NonNull

### ISSUE THREAD

**Issue by robwettach** [rzwitserloot/lombok#2122]
**Describe the bug**
In Lombok 1.18.6 and earlier, the error message produced by the `@NonNull` annotation was "${fieldName} is marked `@NonNull` but is null" ([previous](https://github.com/rzwitserloot/lombok/blob/a0b901c3c04d0377f495a9da853196a3b0433eae/src/core/lombok/core/configuration/NullCheckExceptionType.java#L38)), but was [recently changed](https://github.com/rzwitserloot/lombok/commit/4e7414038ad9df25fb6d2ee76dd22421e1ff7005#diff-08d4adef66eab201bc37dd9b2f83cabb) to "${fieldName} is marked non-null but is null" ([current](https://github.com/rzwitserloot/lombok/blob/4e7414038ad9df25fb6d2ee76dd22421e1ff7005/src/core/lombok/core/configuration/NullCheckExceptionType.java#L44)).

**To Reproduce**
Steps to reproduce the behavior, preferably in the form of the smallest java source file you can make that will show the problem when compiled with `javac -cp lombok.jar ExampleFile.java` or as sole java file in a fresh new eclipse project.

```
import lombok.NonNull;

public class ExampleFile {
    public static void example(@NonNull String field) {

    }

    public static void main(String[] args) {
        try {
            example(null);
        } catch (NullPointerException e) {
            if (!e.getMessage().equals("field is marked @NonNull but is null")) {
                throw new AssertionError("Lombok exception message changed");
            }
        }
    }
}
```

**Expected behavior**
I expect the exception message to be stable across releases unless called out as a (Improbable) Breaking Change in the release notes.

**Version info (please complete the following information):**
 - Lombok version: 1.18.8
 - Platform: javac 1.8.0_202

**Additional context**
This causes unit tests that assert the exception message content to fail.

**Comment by rzwitserloot** [comment]
Pff, not sure it's a good idea to test the content of exception traces, but, touché I guess.

This might be a first, but, discussed it with @rspilker and we'll retroactively update the changelog.

For some context for the change: Turns out not every annotation that marks a parameter as 'null not allowed' is specifically called `@NonNull` which is why we slightly changed the message.

**Comment by rzwitserloot** [comment]
Okay, the site's been updated: https://projectlombok.org/changelog

I'm afraid we can't retroactively change lombok.jar on maven and such (and therefore won't change it on our site either; let's not introduce 2 binarily different lombok jars both tagged with the same stable release version number).

But it will be in changelogs in lombok.jars released from today onwards.
