### ISSUE TITLE
[FEATURE] Builder option to copy entire object except for explicitly set fields

### ISSUE THREAD

**Issue by aklin** [rzwitserloot/lombok#2123]
Hello, I often need to clone entire objects, except for some fields. This is useful when the POJO goes through some external operation and that update needs to be reflected. I will call this new method `fromObject` throughout. Another way of describing this is adding a `clone` method in the `@Builder`.

Example:

### Immutable Foo
```java
// Example object
@Data
@Builder
public Class Foo{
    private final int id;
    private final String name;
}
```

## Proposed feature

```java
final Foo foo = Foo.builder().name("name").build();

try {
    final int assignedId = doStuff(foo) //foo has somehow changed here, maybe an API call or persistence
    return Foo.builder()
        .fromObject(foo) // magic happens here. All foo fields are copied to the new object
        .id(assignedId) //... except for id, which gets explicitly overwritten by the call to the setter
        .build();
} catch(...){}
```

With current Lombok features:

```java
final Foo foo = Foo.builder().name("name").build();

try {
    final int assignedId = doStuff(foo) //foo has somehow changed here, maybe an API call or persistence
    return Foo.builder()
        .name(foo.getName())
        // more setters here
        .id(assignedId)
        .build();
} catch(...){}
```

If we only need to change `id` we can do the above with `@Wither`, but this becomes tediously repetitive when dealing with multiple setters - both in `Foo` definition and when using it to copy objects. It would also help code clarity if the fact that `foo` is being copied is explicitly specified.

I've seen the following with plain Java (and non-final POJOs):

### Mutable Foo
```java
// Non-Lombok object with setters
public Class Foo{
    private int id;
    private String name;

    public Foo setId(final int id){ this.id=id; return this;}
    public Foo setName(final String name){ this.name=name; return this;}

}
```

### Vanilla Java with mutable Foo
```java
try {
    final int assignedId = doStuff(foo) //foo has somehow changed here, maybe an API call or persistence
    return foo.setId(assignedId);
} catch(...){}
```

I hope what I'm trying to get across is clear, of course I'll be happy to clarify as needed. Thank you for your work on Lombok by the way, it kinda took the boring bits out of Java. Looking forward to the response.

**Comment by janrieke** [comment]
I may be missing a point here, but where is the difference to `@Builder(toBuilder=true)`?

**Comment by aklin** [comment]
@janrieke Absolutely none. Thanks for pointing it out, I missed it in the documentation. You've made my life slightly easier.
