### ISSUE TITLE
[FEATURE] Add @Object (and @ServiceObject) to complement @Data/@Value

### ISSUE THREAD

**Issue by alwins0n** [rzwitserloot/lombok#2124]
searched the wiki for duplicates, sorry if I missed one.

**Describe the feature**
Motivation for `@Object`: class design in OO language can range from objects to datastructures. The former hide internal information an expose APIs to manipulate and query internal state whereas the latter expose data "as is" and behave similar to `struct` in the C language. Since datastructures are very well covered in lombok by `@Data` and `@Value` (mutable and immutable) I propose `@Object` for classes that behave like "real" objects.

Essentially objects
- have an internal state which is not queryable
- are comparable/loggable (hc, eq, toString) on that internal state
- expose a well defined API

minimal java sample

```
public class Person {
  
  private String firstName;
  private String lastName;
  private List<String> phoneNumbers;

  public Person(String firstName, String lastName, List<String> phoneNumbers) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.phoneNumbers = phoneNumbers;
  }
  
  public String getDisplayName() {
    return firstName + " " + lastName;
  }
  
  public void changeName(String firstName, String lastName) {
    // ...
  }
  
  public void addPhone(String phone) {
    // some validation
    phoneNumbers.add(phone);
  }
  
  // hc, eq, toString on internal state
  
}
```

Lombok Version

```
@Object
public class Person {

  String firstName;
  String lastName;
  List<String> phoneNumbers;

  public String getDisplayName() {
    return firstName + " " + lastName;
  }

  public void changeName(String firstName, String lastName) {
    // ...
  }

  public void addPhone(String phone) {
    // some validation
    phoneNumbers.add(phone);
  }
}
```

So essentially `@Object` combines
```
@AllArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE)
@EqualsAndHashCode
@ToString
```

Furthermore I find myself rewriting the same combination for a certain type of object over and over again:

```
@Slf4j
@AllArgsConstructor // or required args contructor
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
```

which is why I would like to see an annotation along the lines of: `@ServiceObject` or `@Component`. the latter is preferred by me, but clashes with springs `@Component` unfortunately, which is why `@ServiceComponent` might be a good compromise.

**Describe the target audience**
Developers who take OO/DDD seriously will greatly benefit from `@Object`. All (Enterprise-)Application Developers will benefit from `@ServiceObject` 

---

again sorry if I missed this already being requested. hard to scan 600 issues thouroughly

**Comment by alwins0n** [comment]
added sample for `@ServiceComponent`:

```
public class FooService {
  private static final Logger log = LoggerFactory.getLogger(FooService.class);
  private final FooRepository repository;

  public FooService(FooRepository repository) {
    this.repository = repository;
  }
  
  public void saveFoo(Foo foo) {
    log.info("saving foo");
    
    repository.save(foo);
  }
}
``` 

vs

```
@ServiceObject
public class FooService {
  FooRepository repository;
  
  public void saveFoo(Foo foo) {
    log.info("saving foo");
    
    repository.save(foo);
  }
}
```

**Comment by rzwitserloot** [comment]
Adding `@Slf4j` automatically is annoying; it always injects the field and thus will result in 'unused private variable' warnings unless you actually log something. I can see a feature where we inject the field automatically the moment you actually try to use it (it'll be an error to try to type 'log' and it won't show up in autocomplete dialogs, until you finish the log statement, at which point it will appear. That is its own problem (you might want autocomplete on .warning() and the like, which you probably won't get, not for the first time you use it), and the performance impact of having to scan every file you touch for usage of variables named `log` might be rather heavy.

The combination of these things sounds a lot like `@Data`. I guess here you want automatic private + no automatic getters? Is that worth adding a name and the associated learning curve?

**Comment by alwins0n** [comment]
Ad Slf4j: I already pictured this to be a problem. I just wanted to point out that this combination of annotations is very heavily used by me and stands for one exact thing: a "Service Object". Maybe my requirement could be expanded to "combine lombok annotations into a custom one" - which is probably even more difficult to solve (don't know the architecture behind it)

Ad Object: Does it really? I tried to demonstrate that is exactly the **opposite** of `@Data` and wanted to point out that the lombok **perfectly** supports datastructures or struct-like objects but not objects in the OO-sense. 

I thougt it was worth adding because of the sheer amount of annotations required for such a behaviour (which was probably the motivation for `@Data` and `@Value`) and because you have a defined and exact name for the outcome (which would be `@Object` as opposed to `@Data`). 

Various resources could be linked to here. I picked one random from the top of my search results: https://stackoverflow.com/questions/23406307/whats-the-difference-between-objects-and-data-structures

**Comment by rzwitserloot** [comment]
It sounds too exotic for me (as in, if we allow this, there are about 10 other combos we should add, and clearly having 12 different esoteric combinations each with a different name all in the lombok.* package is bad), so, we're not adding this. If we ever do composable annotations (#2294) you can make this yourself, however.
