### ISSUE TITLE
[BUG] Lombok issue with annotation @SuperBuilder and inheritance

### ISSUE THREAD

**Issue by polibudaMgr** [rzwitserloot/lombok#2129]
Hello,
I cannot create parent and child object which classes are anotated with @SuperBuilder during writing code. Building and run app with Maven works normal, without any errors.

**To Reproduce**
To reproduce error create Parent class and Child class where Child class extends Parent class. Give to both class annotation @SuperBuilder and try to construct them using builder(). Error alert telling cannot resolve method builder().

Below my example classes.

![Parent](https://user-images.githubusercontent.com/48224190/58011715-28b36d80-7af3-11e9-9e18-341690687b1b.png)
![Child](https://user-images.githubusercontent.com/48224190/58011716-28b36d80-7af3-11e9-9e25-c45b38763f74.png)
![MainClass](https://user-images.githubusercontent.com/48224190/58011717-28b36d80-7af3-11e9-915f-bdde5e0d7fe3.png)

**Expected behavior**
I want to be able to use builder constructor to create parent and child object.

**Version info (please complete the following information):**
 - Lombok version - 1.18.8
 - InteliJ 2019.1.1 
 - JDK 1.8.0_202
 - Maven 3.6.1

**Comment by janrieke** [comment]
`@SuperBuilder` is not supported in IntelliJ yet. See https://github.com/mplushnikov/lombok-intellij-plugin/issues/513
