### ISSUE TITLE
[BUG] Ant build fails with JDK 11

### ISSUE THREAD

**Issue by Emdee89** [rzwitserloot/lombok#2133]
**Describe the bug**
The `ant dist` fails with 
```
BUILD FAILED
/home/myname/development/lombok/build.xml:251: javac doesn't support the "modulepath" attribute
```

**To Reproduce**
`cd` into the lombok root folder and run `ant dist` 

**Expected behavior**
The build shall succeed without any error message.

**Version info:**
`java -version`:
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-3ubuntu116.04ppa1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-3ubuntu116.04ppa1, mixed mode, sharing)
```

Apache Ant(TM) version 1.9.6 compiled on July 20 2018

Cloned lombok repository today

Ubuntu 16.04

**Comment by rspilker** [comment]
Cannot reproduce this on Windows and Ant 1.9.9.
```
$   java -version
openjdk version "11.0.2" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.2+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+7, mixed mode)

$ ant -version
Apache Ant(TM) version 1.9.9 compiled on February 2 2017
```

Can you test on a more recent version of ant?

**Comment by janmaterne** [comment]
The <javac modulepath> is supported from Ant 1.9.7+, see the Ant manual of javac
http://ant.apache.org/manual-1.9.x/Tasks/javac.html

We could add a statement in the build.xml which skips the java9 compilation on lower Ant versions or print a message on lower version or document the required Ant version.

**Comment by rspilker** [comment]
We would accept a pull request to improve the error message.

**Comment by janmaterne** [comment]
Implemented a PR.
https://github.com/rzwitserloot/lombok/pull/2206

**Comment by 4devwithgit** [comment]
Which version of ANT supports OpenJDK 11? Thanks in advance.
