### ISSUE TITLE
[BUG] Javadoc generation fails in Java11 when importing builder

### ISSUE THREAD

**Issue by thespags** [rzwitserloot/lombok#2137]
**Describe the bug**
Javadoc generation fails in Java11 when referencing a pojo's builder in an import.

**To Reproduce**
Create a pojo
```
package somePackage;

import lombok.*;

@Generated
@Builder(toBuilder = true)
public class Pojo {

    public int foo;
}
```
Now reference the pojo's builder
```
package somePackage;

// statically import to break javadoc.
import somePackage.Pojo.PojoBuilder;

public class ReferencePojo {

    public void foo() {
        PojoBuilder pojo = Pojo.builder();
    }
}
```
Run `mvn javadoc:jar`.

Fails with 
```
[ERROR] Exit code: 1 - .../somePackage/ReferencePojo.java:4: error: cannot find symbol
[ERROR] import somePackage.Pojo.PojoBuilder;
[ERROR]                        ^
[ERROR]   symbol:   class PojoBuilder
[ERROR]   location: class Pojo
```

**Expected behavior**
javadoc is generated correctly.

**Version info (please complete the following information):**
 - Lombok version 1.18.8
 - Platform javac 11.0.1

**Additional context**
Work around is that you do not import and use the enclosingType.innerType, `Pojo.PojoBuilder`  in your reference.

**Comment by rzwitserloot** [comment]
annotation processors just do not run when the javadoc tool is invoked, as far as I know, which means there's absolutely nothing we can do about it in the workflow you describe.

But, there IS a solution: First delombok your source into a separate directory, then, javadoc that. I believe there is a maven plugin around to make this easier; if there is not, then I foresee a feature request to provide such a plugin :)


So, in a bash-scripty kind of pseudocode:

    find . -name *.java |xargs java -jar lombok.jar delombok -d delomboked -c classpath:goes:here
    find delomboked -name *.java |xargs javadoc

The job of finding (recursively) all java sources in a given dir is something maven, gradle, ant, sbt and every other build system ever written already do fine, so such a plugin isn't complicated to write at all, fortunately.

**Comment by thespags** [comment]
Thanks for the update. I thought it was relating to other java11 issues I was seeing, but looks like this post covers the flow you mention.

https://stackoverflow.com/questions/51947791/javadoc-cannot-find-symbol-error-when-using-lomboks-builder-annotation

I can consider the issue closed with those steps.

**Comment by lucasoares** [comment]
For now on all projects java11+ will need to manually delombok on the build pipeline? @rzwitserloot

**Comment by sabdouni** [comment]
I asked myself do we really need to generate javadoc for mapper generated classes :). My answer was no.
So simple solution, exclude in javadoc plugin configuration the mapper generated classes.
In my case, the mapper classes were generated under a 'mapper' package, to exclude them i used this configuration:
```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <excludePackageNames>*.mapper.*</excludePackageNames>
                </configuration>
            </plugin>
```
