### ISSUE TITLE
[BUG] Delombok causes syntax error for varargs method parameter of a Array-parametrized type

### ISSUE THREAD

**Issue by mp911de** [rzwitserloot/lombok#2140]
**Describe the bug**
Calling delombok for code that contains a method signature using varargs results in code that contains syntax errors. This happens only if the vararg param is a parametrized type with an array parameter (e.g. `Foo<byte[]> ...`).

**To Reproduce**

Original code:

Class with `@RequiredArgsConstructor` and a method signature:

```
public List<ByteRecord> xReadGroup(Consumer consumer, StreamReadOptions readOptions, StreamOffset<byte[]>... streams)
```

([link to full code](https://github.com/spring-projects/spring-data-redis/blob/master/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceStreamCommands.java#L283))

After delombok:

```
public List<ByteRecord> xReadGroup(Consumer consumer, StreamReadOptions readOptions, StreamOffset<byte...>... streams)
```

**Expected behavior**
No change of that method.

**Version info (please complete the following information):**
 - Lombok version: 1.18.6 via Lombok Maven Plugin 1.18.6.0.
 - Platform Javac, java version "1.8.0_201"

**Additional context**
Can be reproduced using https://github.com/spring-projects/spring-data-redis by forcing Lombok plugin version to a newer version than 1.18.4.0 and `mvn clean install -DskipTests -Pci`

**Comment by Maaartinus** [comment]
@mp911de Just to be sure: `StreamOffset<[]>... streams` should be `StreamOffset<byte[]>... streams`, right?

**Comment by mp911de** [comment]
Yes. Updated the description accordingly.
