### ISSUE TITLE
1.18.6 & 1.18.8: Annotations won't work on 'public final static class'

### ISSUE THREAD

**Issue by kangarko** [rzwitserloot/lombok#2142]
Lombok 1.18.6 and 1.18.8
javac 1.8.0_202

Hi there,

When using these two annotations on a public final static inner class, lombok fails to compile. Upon removing them and replacing with vanilla java, the bug is no longer present. I have lombok many other places in my software and it works just fine for many years, I don't understand why the problem suddenly started to pop up.

![a](https://i.imgur.com/v1R6dVb.png)

The lombok library is correctly installed and added, and works for other parts of all software:

![a](https://i.imgur.com/1wxhNOl.png)

**Comment by kangarko** [comment]
I tested removing .m2 folder completely, ALT+F5 to refresh maven project, changing lombok versions etc. but without success.

**Comment by pzygielo** [comment]
It's hard to tell from your picture, but do you actually `import` used annotations?

**Comment by kangarko** [comment]
Yes naturally, all was imported correctly.

**Comment by rspilker** [comment]
Is it a maven only problem?

```java
import lombok.*;
import java.util.List;

public class Test {
	
	@Getter
	@RequiredArgsConstructor
	public static final class Nested {
		private final int foo;
		private final List<String> bar;
	}
}
```
Compiling with `javac -cp lombok-1.18.8.jar Test.java` works on my machine.

**Comment by kangarko** [comment]
Thanks, not really sure but it appeared to disappeared lol. Prob an issue with Maven like you said.
