### ISSUE TITLE
[BUG] too many parameters when using @Builder

### ISSUE THREAD

**Issue by yuanming-xu** [rzwitserloot/lombok#2143]
please see this: https://github.com/rzwitserloot/lombok/issues/1509
I met the same problem, the root cause is Lombok created too many parameters constructor in builder which is used in build() method. So please use no-args constructor and setters instead of all-args constructor in build(), @lombok contributors.
Thank you.

**Comment by rspilker** [comment]
Sorry, our position has not changed. This is not common enough to change our code generation scheme. 

You can put `@Builder` on any constructor or method, and we're going to call the method from the `build()` method. If you put `@Builder` on a type, we first generate the constructor. That's the main difference.
