### ISSUE TITLE
[FEATURE] Add @Externalizable 

### ISSUE THREAD

**Issue by lsong98sh** [rzwitserloot/lombok#2146]
As it‘s name, simply generate writeExternal and readExternal for POJO.

**Comment by rspilker** [comment]
Without a before image (the code without lombok) and after image (the code you would write if lombok would support this) we cannot do anything.

**Comment by rspilker** [comment]
Also, please specify what would be the use case, other libraries that would consume these methods et cetera.

**Comment by mxmlnglt** [comment]
The purpose of this feature is probably the auto-generation of code to implement interface `java.io.Externalizable`: https://docs.oracle.com/javase/8/docs/api/java/io/Externalizable.html

Example code by Baeldung: https://www.baeldung.com/java-externalizable

**Comment by lsong98sh** [comment]
Sorry I'm a chinese. so I can only provide Chinese WebSite to explain Externalizable interface.
Thanks to mxmlnglt, the answer is exact what I want.   

Recently, I'm working on a project that does a fast serialization job of an Java Object.
A project that almost the same as Kyro 【 https://github.com/EsotericSoftware/kryo】
But uses CgLib to generate byecode。

First, I wrote my own UnsafeBufferedOutput, and manually implememts the Externalizable interface.
The test result is about 25% faster that Kyro.
So the rest of the work can ben done in two ways. Using CgLib to generate a Proxy（somthing like BeanCopier ) or using ask Lombok to generate the source。

**Comment by rspilker** [comment]
We're not going to add this. Using java serialization is [basically broken](https://www.javacodegeeks.com/2019/06/motivations-behind-javas-maligned-serialization.html), so we're not going to create code to make it easier.
