### ISSUE TITLE
[BUG] lombok.addLombokGeneratedAnnotation excludes annotated class

### ISSUE THREAD

**Issue by boonware** [rzwitserloot/lombok#2148]
**Describe the bug**
The option `lombok.addLombokGeneratedAnnotation` with Jacoco also excludes the annotated class and not just the generated class when using `@Builder`.

**To Reproduce**
1. Create a simple POJO class and annotate with `@Builder`.
2. Write some unit tests for this class and use Jacoco for code coverage.
3. When executed, Jacoco picks up the generated builder class and shows zero code coverage, as expected.
4. Exclude the generated class by adding `lombok.addLombokGeneratedAnnotation = true` to the `lombok.config` file.
5. Now, Jacoco excludes the generated builder class, _but also excludes the POJO class that I have written myself._

**Expected behavior**
The auto-generated build class should be excluded, but the class annotated with `@Builder` should not be excluded by Jacoco.

**Version info (please complete the following information):**
 - Lombok version: 1.18.8
 - Platform: Windows 7, Java 8, Gradle 5.4.1

**Comment by rspilker** [comment]
Is this a lombok problem or a Jacoco problem?

Can you confirm that in the generated bytecode the `lombok.Generated` annotation is put on the outer class?

What happens if you compile a `delombok` version of your code and feed that to Jacoco?

**Comment by rspilker** [comment]
No response from reporter, closing issue.
