### ISSUE TITLE
[BUG] The default getter may expose internal representation

### ISSUE THREAD

**Issue by afmenez** [rzwitserloot/lombok#2151]
**Describe the bug**
The default getter may expose internal representation by returning a reference to a mutable object.

**To Reproduce**
```
public class Account {
    @Getter
    private Date creation;
}
```
**Expected behavior**
I expect the getter to return a clone of the internal object:
```
	public Date getCreation() {
		return (Date) creation.clone();
	}
```
**Version info (please complete the following information):**
 - Lombok version 1.18.8
 - Platform (Eclipse, Java JDK 11)

**Additional context**
I found this issue with the SpotBugs static analyzer for Eclipse.

**Comment by Maaartinus** [comment]
Disclaimer: I'm not a Lombok team member, just a random guy trying to help.

Yes, but that's not a bug - maybe a missing feature. Already reported a few times.

A getter *should* by default return the value as is, though sometimes cloning could be appropriate. Similarly for the setters, constructors, builders, ...

However, there's no general way of cloning Java objects. And there are options: Shallow/deep, creating mutable/immutable copy, whatever. And various implementations, some can handle loops, others can't, ....

IMHO the only solution is to let the user provide their own `Cloner`, but specifying this on a per-field basis is too verbose and specifying this once per class is a bit hacky - what should the interface of the `Cloner` be?

SpotBugs is surely right about this being a possible problem, but IMHO using things like `java.util.Date` is a sure problem. `java.time` offers much better and immutable classes (even ported back to Java 6, so why `Date`?).

**Comment by hypr2771** [comment]
Hi,

I think this issue as been addressed already : see https://github.com/rzwitserloot/lombok/issues/420
