### ISSUE TITLE
[FEATURE] Support lombok config inside build management tool

### ISSUE THREAD

**Issue by program3935** [rzwitserloot/lombok#2158]
Support lombok config inside `pom.xml` or `build.gradle`. These tools specify the dependency and define the configuration for building.

The current solution, the property file, is better suited for externalized configuration management by devops.

**Before:
lombok.config** (floating somewhere, detached)
```
lombok.equalsAndHashCode.callSuper=call
lombok.addLombokGeneratedAnnotation=true
```

**After:
build.gradle**
```
lombok {
    equalsAndHashCode.callSuper = call
    addLombokGeneratedAnnotation = true
}
```

**Comment by Maaartinus** [comment]
For me, the idea of putting `lombok.config` in a build file is like putting my Java files therein. There are at least two problems with it:
- maven, gradle, ant, ivy, make, :rofl:, ...
- they're per package

You yourself mentioned what the current solution is better for, but I'm missing what the alternative would be better for.

**Comment by janrieke** [comment]
For instance to set company standards (like "no experimental features"). Simply put such options in the company's base pom and you're done.

**Comment by program3935** [comment]
I think this alternative would be better because the lombok config is necessary information to build correctly. It's really bothering me that the configuration is decoupled.

I understand that it's like putting java files within the build tool, but modern build tools are including java to determine the build. Lombok has a gradle annotationProcessor... we're just configuring it.

We would need a neat way to provide package level configuration. I'm not sure how to view that. Perhaps it's okay to offer only global within the build tool.

**Comment by rspilker** [comment]
How would the information from the build file be passed to the java compiler? Command line parameters? Environment variables?

I can only imagine top level defaults, but that's probably good enough.

**Comment by rspilker** [comment]
Although I can see merits for some top level defaults, there are too many complicating factors to warrant the effort.

**Comment by lfvjimisola** [comment]
@rspilker Any chance of reconsidering this? We just stumbled on the limitations with lombok's configuration options (lombok.config only) as we would like to set the configuration in our organization's parent POM (just like mentioned [here](https://github.com/projectlombok/lombok/issues/2158#issuecomment-504143319)).

**Comment by lfvjimisola** [comment]
It's more of a workaround than the solution I was hoping for.  The workaround still clutters each source repository with a lombok.config where as a lombok configuration in a parebt pom.xml would not.

**Comment by rspilker** [comment]
You can put it in a top level directory, like `src/lombok.config` indeed, or even `lombok.config`.

**Comment by lfvjimisola** [comment]
@rspilker Ok. Thanks. But, it still involves a file in each repository instead of being able to configure from a POM when including the dependency. Just to confirm, your opinion is still that "there are too many complicating factors to warrant the effort"?

**Comment by rspilker** [comment]
@lfvjimisola Yes, given that adding a oneliner file for this scenario is the only thing necessary to be able to add enforce company standards from a parent pom, and that any code we add gives us a maintenance load forever, I can still stand by the original conclusion.

You can probable create an 100% pom solution using the `maven-dependency-plugin` to [extract `lombok.config` from a jar](https://stackoverflow.com/questions/5559519/maven-extract-files-from-jar), but I haven't tried that.

**Comment by jonenst** [comment]
Hi @rspilker , is there an example of using the import statement to read from a shared published lombok.config from the maven build class path ? Something similar to maven-checkstyle-plugin with checkstyle.xml : https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/custom-checker-config.html ? This allows to write the config once and dump it into a jar published in a central repository, then reference this jar during the build from many different projects (for example in a shared parent pom). When the config changes, you just republish the config jar and update the version in projects (again probably by updating the shared parent pom)

In the docs you linked to https://projectlombok.org/features/configuration#import , what is the "deps" part in  `../deps/lombok-config.jar` ?

Having a 100% pom solution would be even nicer, but adding a one line import file in all projects that never changes is fine (whereas config will probably change)

Thanks in advance

**Comment by Maze-fr** [comment]
I was looking around for some global "company standard" solution, as expressed by @janrieke .
I understand @rspilker arguments, mainly the one that the IDE needs to read that damn config file.

However, in VS Code, for example, RedHat language support for Java takes the `lombok.jar` from the pom information, so it could do the same for a config file.

I see 2 possibilities to deal with that "concern" :
- the config file can be in a JAR and extracted by the adequate Maven plugin when running a "clean".
- a profile may be active if `lombok.config` is missing and generate it at "clean" with the ant plugin.
