### ISSUE TITLE
[FEATURE] Configure default value for builderMethode name

### ISSUE THREAD

**Issue by GianniGiglio** [rzwitserloot/lombok#2159]
It would be nice to have a configuration property on lombok level that would allow to set a default builderMethodName instead of having to repeat the builderMethodeName in the annotations.

**Comment by rspilker** [comment]
Why would you want this? To what would you change that?

**Comment by GianniGiglio** [comment]
Hi. Inorder to enforce naming on the builders. Rater to have each class override the builder name in the annotations. Greetz

**Comment by rspilker** [comment]
Can you give some examples of what you would use instead of `builder()`?

It's not that we cannot do this, but it does complicate the code, and we've never encountered this in a project. 

We allow to override this for if you have multiple `@Builder` annotations on different (static) methods.

**Comment by GianniGiglio** [comment]
Hey thanks for the reply. I know you can use the static methods for secondary builders.  

today we have to use @Builder(builderClassName = "Builder")

This is for legacy purposes. It would be nice if we could set the builderClassName using configuration

**Comment by rspilker** [comment]
In the [edge release](https://projectlombok.org/download-edge) you can already specify the classname of the builder using a template, like `lombok.builder.className = Builder` or `lombok.builder.className = My*Builder`, where * will be replaced by the type name. The default value is `*Builder`.

**Comment by rspilker** [comment]
However, your initial request was about the ``builderMethodName`. Do you have use-cases for that? Preferably including some examples.

**Comment by GianniGiglio** [comment]
Then my request is unvalid it's really about the builder classname

**Comment by rspilker** [comment]
Thanks.
