### ISSUE TITLE
Lombok does not work with takari 

### ISSUE THREAD

**Issue by f0rmatme** [rzwitserloot/lombok#2170]
when using jdt with takari i'm getting
"You aren't using a compiler supported by lombok, so lombok will not work and has been disabled."

Any way around this? 

https://github.com/takari/takari-lifecycle/issues/29

**Comment by rspilker** [comment]
Did you try something like described in the [GWT documentation](https://projectlombok.org/setup/gwt)?

**Comment by rspilker** [comment]
No response from reporter, closing the issue.
