### ISSUE TITLE
@Cleanup use singletonlist, why？

### ISSUE THREAD

**Issue by yangle94** [rzwitserloot/lombok#2177]
<img width="881" alt="WechatIMG54242" src="https://user-images.githubusercontent.com/21074832/61017052-6d0d0c80-a3c4-11e9-828c-a9241d46906c.png">
Excuse me
Can you tell me why use singletonList ?

**Comment by rzwitserloot** [comment]
To avoid IDE/linter tools saying that we're nullchecking something that cannot be null.

**Comment by yangle94** [comment]
> 为了避免IDE / linter工具说我们在null中检查不能为null的东西。

OMG
