### ISSUE TITLE
@EqualsAndHashCode should also copy field annotations (similar to #1634)

### ISSUE THREAD

**Issue by sharedprophet** [rzwitserloot/lombok#2179]
`@EqualsAndHashCode` should copy field annotations the same way #1634 added this to builder, getter, and setter methods.

I am trying out Facebook's Infer static analyzer, and its Eradicate checker for `@Nullable` annotations complains about the methods generated by `@EqualsAndHashCode`:

```
[snip]/AccountInfoContainer.java:10: warning: ERADICATE_PARAMETER_NOT_NULLABLE
  `AccountInfoContainer$AccountInfo.equals(...)` needs a non-null value in parameter 1 but argument `other.getAccountInfo()` can be null. (Origin: call to getAccountInfo() at line 10).
  8.   import lombok.Data;
  9.
  10. > @Data
  11.   public class AccountInfoContainer {
  12.     @Nullable private AccountInfo accountInfo;
```

**Comment by rzwitserloot** [comment]
I don't understand what you mean. What should we mark nullable?

This sounds like the static analyser isn't inferring nearly enough and not something lombok can or should address.

Which nullable should we even generate? If it involves resolution, the answer is no, we can't do this.

parked: without feedback, close issue if after 2019-07-25.

**Comment by sharedprophet** [comment]
I was thinking the annotation could be copied from a field, but it makes sense that that won't be available... if there were a way to configure an annotation to put on the `other` parameter to the equals method, though, that would fix this.

**Comment by rspilker** [comment]
We _could_ add `@Nullable` to all generated `equals` method's, but that doesn't really make sense. 

Since `equals` is defined in `java.lang.Object` and its contract is well documented, static code analyzers should assume the parameter `other` in `equals(Object)` is always nullable.
