### ISSUE TITLE
[BUG] ToString compile error with fluent accessors

### ISSUE THREAD

**Issue by chsi13** [rzwitserloot/lombok#2186]
The association of Builder and Accessors(fluent = true) annotations generates compile-time errors in toString implementation of Builder.

```
  public String toString() {
            return "AutomaticPeriodCalculationLine.AutomaticPeriodCalculationLineBuilder(automaticPeriodCode=" + this.automaticPeriodCode() + ", targetPeriodCode=" + this.targetPeriodCode() + ", percentage=" + this.percentage() + ")";
        }
```

This.automaticPeriodCode() doesn't work because there isn't generated accessors on the builder class. 

Must be field access ->   ``` this.automaticPeriodCode``` (as with accessors fluent=false)

**Comment by rspilker** [comment]
Can you please provide a complete minimal java example to reproduce the problem?

**Comment by chsi13** [comment]
Nothing special just combine @builder and @accessors(fluent=true) then delombok the class

**Comment by rspilker** [comment]
Can you please provide a complete minimal java example to reproduce the problem? That helps us.

**Comment by rspilker** [comment]
No response from reporter, closing issue.
