### ISSUE TITLE
[FEATURE] add option to @Getter and @Setter on class to ignore transient fields

### ISSUE THREAD

**Issue by rsandidfc** [rzwitserloot/lombok#2188]
When working with classes that have many fields, putting the annotations @Getter and @Setter saves many lines of text even compared to placing the annotations on the individual fields. Think about beans that have dozens of fields here. 

In lieu of having a way to tell the annotation to exclude certain fields which can't otherwise be made final, a good way of handling this is to have the option of excluding transient fields. This fits a nice pattern where configuration fields need to have getters and setters, but other runtime fields would (or should) be marked transient anyway to be excluded from serialization, jaxb etc.

Having an explicit "exclude" capability within the Getter/Setter annotations, or even introducing a new annotation that can be explicitly placed on fields to have them excluded, would also add even more flexibility.

**Comment by rspilker** [comment]
You can already accomplish this by using `@Getter(AccessLevel.NONE)`.

**Comment by jdimeo** [comment]
I would like to vote for this as well. Lombok is fantastic when paired with Jackson for the reasons mentioned above. It's very clunky to add:

```
@Getter(AccessLevel.NONE)
@Setter(AccessLevel.NONE)
@JsonIgnore
private int foo;
```

to every single transient/temporary/private field and `transient` has good semantic meaning. I recommend adding this to `@Accessors`, since it seems like it has precedent with `chain` and `fluent`.

**Comment by Rawi01** [comment]
This can also be solved using meta-annotations (#557)

**Comment by jdimeo** [comment]
Great suggestion @Rawi01 ! I'll use that instead.

**Comment by Rawi01** [comment]
@jdimeo Yeah, should have mentioned that, sorry. Unfortunately there was no feedback on it so far, neither by users nor by one of the maintainers. There are still some things to fix but it should already be usable.
