### ISSUE TITLE
[Website] Dead link

### ISSUE THREAD

**Issue by andys8** [rzwitserloot/lombok#2196]
# Issue

1. Open https://projectlombok.org
1. Open menu (hamburger)
1. Click on "How to use"

# Actual

The link will be rewritten to:
https://projectlombok.org/setup/overview.html

It is dead.

![Screenshot_20190731-185830](https://user-images.githubusercontent.com/13085980/62232028-8c94c500-b3c5-11e9-9c8a-76378d25716f.png)

Tested with mobile Brave (Chromium) and Firefox.

# Expected

Direct link https://projectlombok.org/setup/overview is working fine. It should be the same when coming from another page as described above.

**Comment by rspilker** [comment]
Thanks. It's fixed now.
