### ISSUE TITLE
[BUG] @Data and @NoArgsConstructor used together, then you can't define your own customized constructor

### ISSUE THREAD

**Issue by yuchliu** [rzwitserloot/lombok#2202]
When you use both `@Data` and `@NoArgsConstructor`, then you can't define your own customized constructor, my code is as follow:

```java
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Map;

@Data
@NoArgsConstructor
public class EntityTest
{
    private Integer id;
    private String name;

    public EntityTest(Map<String, String> map)
    {
        if (map.containsKey("name"))
            this.name = map.get("name");
    }

}
```

And the compilation fails with error:
java: constructor EntityTest() is already defined in class EntityTest

**Comment by ddivanshu** [comment]
Same code is working in Lombok 1.18.6 .

**Comment by cezar-tech** [comment]
Also working in Lombok 1.18.8

**Comment by reizy** [comment]
It's related with https://github.com/rzwitserloot/lombok/issues/1712 - @Data creates private constructor and NoArgsConstructor creates public one. It was fixed, so to my mind it should be closed.

**Comment by rspilker** [comment]
What version are you using? I cannot reproduce this problem.
