### ISSUE TITLE
[BUG] Lombok v1.14.4 install breaks Eclipse 2019-6

### ISSUE THREAD

**Issue by MrRedstoner** [rzwitserloot/lombok#2210]
**Describe the bug**
Similar to https://github.com/rzwitserloot/lombok/issues/424 and https://github.com/rzwitserloot/lombok/issues/566
After Lombok installation Eclipse fails to start. The small startup progress window opens as normal, disappears and that is it. There is a process left running preventing the uninstall.
After Lombok uninstall Eclipse starts right up.

**To Reproduce**
exit Eclipse
install Lombok
try to launch Eclipse (link not working at all, through cmd.exe see above) -> fails
try uninstall -> fails as well, because of a stray eclipse process
after succesfull uninstall, Eclipse launches normally

**Expected behavior**
Eclipse to launch

**Version info (please complete the following information):**
 - Lombok version 1.14.4
 - Platform Eclipse 2019-6 on Windows 10

**Additional context**
While the current version may be higher than mine (preexisting project, not my choice), both similar-looking issues seem to lack resolution.

**Comment by rspilker** [comment]
Can you check your `eclipse.ini` file? 

Do you launch your Eclipse with a shortcut or directly from the directory?

Is there a reason why you're not using a more recent version of lombok?

**Comment by MrRedstoner** [comment]
Will check as soon as possible, anything specific to look for?

Typically from the Win 10 search, though when that failed I tried from the commandline, navigating to the folder and launching the .exe

This version is what the project I'm working on uses, I used the file as Maven downloaded it. I'm worried that using a different version than the project is using could bite me in the foot at some point. Also, as most people don't seem to have this problem, I'm hoping it is merely some misconfiguration and not an actuall problem with either product.

Note: One time Eclipse managed to squeze out a dialog telling me to check the .metadata/.log file. If it would be of any help I can create a fresh workspace and post such a log.

**Comment by rspilker** [comment]
Can you give us the following information:
- Where is your eclipse installed?
- Is `lombok.jar` next to `eclipse.exe` and `eclipse.ini`?
- What is the contents of your `eclipse.ini`?

**Comment by MrRedstoner** [comment]
- Eclipse is somewhere along the lines of C:/Users/username/eclipse/, I manually pointed the installer to it.
- The .jar that I ran for the instalation was not (C:/Users/username/.m2/org/projectlombok), however a lombok.jar appeared next to eclipse.exe
- I'm not at the machine at the moment, that will have to wait a few hours

**Comment by MrRedstoner** [comment]
[EclipseIni.txt](https://github.com/rzwitserloot/lombok/files/3547379/EclipseIni.txt)
And there is the .ini, both without and with lombok

**Comment by rspilker** [comment]
The only thing I notice is the line `-Xbootclasspath/a:lombok.jar` that's not in my `eclipse.ini`.

At some point in the past, we got rid of it, but I really don't remember in what version.

I strongly suggest to use a more recent version of lombok.

**Comment by MrRedstoner** [comment]
Luckily I was able to bump the project up to newest Lombok. Everything appears to be working, Eclipse included. I'm therefore closing the issue. Still, I find it interresting that the old versions of Lombok are incompatible with newer Eclipses. Hopefully I'm the only one with this problem.
