### ISSUE TITLE
Support javax.validation.constraints.NotNull

### ISSUE THREAD

**Issue by chrylis** [rzwitserloot/lombok#2211]
Lombok generally supports some annotations named `@Nonnull`, but the most common of these, JSR-305 `javax.annotation.Nonnull`, [is essentially dead](https://stackoverflow.com/questions/4963300/which-notnull-java-annotation-should-i-use), and a common replacement is the Bean Validation `javax.validation.constraints.NotNull`. This annotation doesn't seem to be recognized at all by Lombok for either "required args" or setter validation, and I propose adding it to the general "not-null annotation" list. (This doesn't seem to have been directly raised before, for some reason.)

**Comment by rspilker** [comment]
There is a big difference in the meaning of any `@NonNull` and `javax.validation.constaints.NotNull`. NotNull still allows `null` to be assigned to the field. But it will than fail validation, typically preventing the object from being persisted.

NonNull, in all forms, do not allow `null` to be assigned to the field.

**Comment by rspilker** [comment]
Here you can find the list of all supported annotations that we consider to mean NonNull:

https://github.com/rzwitserloot/lombok/blob/master/src/core/lombok/core/handlers/HandlerUtil.java#L81
