### ISSUE TITLE
[BUG] fails to compile with oracke jdk8 on linux

### ISSUE THREAD

**Issue by dawnbreaks** [rzwitserloot/lombok#2212]
**Describe the bug**
Fails to compile with oracke jdk8 on linux.

**To Reproduce**
1. check out this [repository](https://github.com/dawnbreaks/lombok-builder)
2. build with command:   ./gradlew build
3. build failed with the following error output.
```
$ ./gradlew compileJava           

> Task :compileJava FAILED
/data/projects/lombok-builder/src/main/java/lombok/test/grpcclient/GrpcClient.java:14: error: cannot find symbol
@Builder
^
  symbol:   class AbstractStub
  location: class GrpcClient<B>
  where B is a type-variable:
    B extends AbstractStub<B> declared in class GrpcClient
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```
**Expected behavior**
it should build successfully. 

**Version info (please complete the following information):**
 - Lombok version : 1.18.8
 - Platform: javac 1.8.0_191

**Additional context**
FYI, it compile successfuly on mac OS

**Comment by rspilker** [comment]
Could the problem be that gradle thinks you're compiling test code. You have to configure annotation processors for test sources separately.

**Comment by rspilker** [comment]
Please reduce your code to be the simplest as possible.

**Comment by rspilker** [comment]
Did you try other java versions?

**Comment by rspilker** [comment]
I think you have a problem with `io.grpc.stub.AbstractStub`

If I remove those imports and replace the word `AbstractStub` with `Enum`, and replace `ClientConfig` with `ClientSettings.ClientConfig` in the parameter `clientConfig` everything compiles.

**Comment by dawnbreaks** [comment]
@rspilker it's nothing to do with gradle, and there's bug in lombok. I have try my best to simply the code to reprocue it. The code work file on mac OS, but failed on linux jdk8.

**Comment by dawnbreaks** [comment]
I known how to change my code to bypass this bug to compile successfully, but i need to report this bug.
