### ISSUE TITLE
[FEATURE] Add an Log-annotation for tinylog

### ISSUE THREAD

**Issue by SchulteMarkus** [rzwitserloot/lombok#2213]
**Tl;dr**

Support [tinylog](https://github.com/pmwmedia/tinylog)  by an own Log-annotation

**Add an Log-annotation for tinylog**

Lombok [supports a wide range of different logging libraries](
https://projectlombok.org/features/log) by an own annotation for each logging library.

There is yet another JVM logging library avaialbe: [tinylog](https://github.com/pmwmedia/tinylog).

Please support a Log-annotation for tinylog. _@Tinylog2_ could be it, for example. This would benefit all developers who want to use tinylog.

**Comment by rspilker** [comment]
Uh, this doesn't really make sense. The whole idea of tinylog is that there is no field or boilerplate.

From their website:
```java
import org.tinylog.Logger;
public class Application {
    public static void main(String[] args) {
        Logger.info("Hello World!");
    }
}
```

**Comment by SchulteMarkus** [comment]
Hmm, but from a usage point of view, I would be glad to have sth. like _@Tinylog2_.
