### ISSUE TITLE
[BUG] Static imports for generated methods cause Lombok to stop working

### ISSUE THREAD

**Issue by Mahtaran** [rzwitserloot/lombok#2215]
**Describe the bug**
Whenever I try to add a static import for a method generated by Lombok (I tested it with `@Getter` methods) Lombok just stops working. Annotations are no longer replaced, and thus the build fails.

**To Reproduce**
Add a field. Give it the `@Getter` annotation. In another class, statically import that getter method.

**Expected behavior**
Lombok should not stop working.

**Version info (please complete the following information):**
 - Lombok version: 1.18.8
 - Platform: IDEA, latest JDK-8, javac 11.0.3

**Comment by nils4cosee** [comment]
The also happens for `@Builder` annotation. 
see #2044 for more details

**Comment by Mahtaran** [comment]
Ah, seems like it is a known bug then.

**Comment by nils4cosee** [comment]
And not solvable by Lombok, because the JVM resolves static imports before running the annotation-processor.

**Comment by Mahtaran** [comment]
Yeah, I guess I should close this in favour of #2044.
