### ISSUE TITLE
[FEATURE] example how to declare enum instance?

### ISSUE THREAD

**Issue by henry1992007** [rzwitserloot/lombok#2217]
HI! first of all, lombok is a great project that helps a lot.
and I have some cases where I need to custom my annotation, which will dynamically declare enum instance for me.

say my custom annotation, AutoEnum
before:
`
@AutoEnum
public enum SomeEnum{
}
`

after:
@AutoEnum
public enum SomeEnum{
    AutoInstance,;
}

Can you provide any example how to do that with lombok's ability? Thanks alot

**Comment by Maaartinus** [comment]
There's no such thing.... and I wonder what would it gain you? There's no boilerplate saved and the "before" code is even longer than the "after" code:
```
@AutoEnum public enum SomeEnum {}

public enum SomeEnum {INSTANCE}
```
