### ISSUE TITLE
[BUG] Error:(17, 1) java: constructor Comment() is already defined in class Comment

### ISSUE THREAD

**Issue by dannyZhou** [rzwitserloot/lombok#2225]
**Describe the bug**
Error:(17, 1) java: constructor Comment() is already defined in class com.dannybook.article.model.Comment

**To Reproduce**
```
@AllArgsConstructor
@NoArgsConstructor
public class Comment {

}
```

**Expected behavior**

**Version info (please complete the following information):**
 - Lombok version 1.18.8
 - javac 1.8.0_192

**Comment by janrieke** [comment]
You are defining the same constructor twice. What do you expect?

**Comment by dannyZhou** [comment]
When class is empty, both use 
`@AllArgsConstructor @NoArgsConstructor` will occur this error.

**Comment by janrieke** [comment]
Yes, because you are defining the same (no argument) constructor twice. That's illegal according to the Java spec, and the compiler is right to complain. That's not a bug.

**Comment by dannyZhou** [comment]
I think, if use both of `@AllArgsConstructor @NoArgsConstructor` in an empty class, 
it will build success and generate only one constructor,

##### origin code
```java
@AllArgsConstructor
@NoArgsConstructor
public class Comment {

}
```

##### generated code
```java
public class Comment {
    public Comment() {
    }
}
```
