### ISSUE TITLE
Final field initiliazation error

### ISSUE THREAD

**Issue by Danny-awesome** [rzwitserloot/lombok#2227]
so am using lombok first time, maybe beginner's bad-luck, after adding @Data and @RequiredArgsConstructor annotations, i get this -> 'The blank final field <variable> may not have been initialized' for all final instance variables i declared

**Comment by rspilker** [comment]
Can you give us the smallest java program that demonstrates this behavior, what IDE you are using, and the version of lombok?

**Comment by Danny-awesome** [comment]
I resolved the issue. I declared enum after declaring the Fields, so I did the reverse and the error cleared
