### ISSUE TITLE
[BUG] toBuilder fails to compile with java 9+ when inheritance and ObtainVia is used

### ISSUE THREAD

**Issue by jezior** [rzwitserloot/lombok#2228]
**Describe the bug**
toBuilder fails to compile with java 9+ when inheritance and ObtainVia is used.
The scenario is more complex as usual as we have generic builder class.
Interestingly enough the code compiles fine when there's only one ObtainVia annotation, with more than one compilation fails with type error.
Best explained with the code.
Sample code: [https://github.com/jezior/lombok-playground](https://github.com/jezior/lombok-playground)

**To Reproduce**
Try to compile the code with javac 9+. It compiles just fine with 8.
Run either "mvn clean install" or
 javac -cp lombok-1.18.8.jar src/main/java/playground/*

**Expected behavior**
Code compiles :)

**Version info (please complete the following information):**
 - Lombok version: 1.18.8
 - Platform: javac 9.0.1 (I tested also with 10 and 11)

**Comment by rzwitserloot** [comment]
Fixed by 2335, hopefully? try the edge release.

**Comment by rzwitserloot** [comment]
I guess this has been fixed, then.

**Comment by jezior** [comment]
Sorry for the late response - fixed in edge version.
