### ISSUE TITLE
[FEATURE] Add comments around generated code with delombok

### ISSUE THREAD

**Issue by satob** [rzwitserloot/lombok#2237]
### Request

Like `@lombok.Generated`, it is useful if delombok inserts specified comment around generated methods and field, like:

```java
    // parasoft-begin-suppress ALL  "generated with delombok"
    @Override
    public String toString() {
        return "User(name=" + this.getName() + ", age=" + this.getAge() + ")";
    }
    // parasoft-end-suppress ALL    "generated with delombok"
```
```java
    // parasoft-begin-suppress ALL  "generated with delombok"
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(SomeClass.class);
    // parasoft-end-suppress ALL    "generated with delombok"
```

The content of comment should be specified with preference like:

```xml
  <format value="generatedCodeBeginningComment:// parasoft-begin-suppress ALL &quot;generated with delombok&quot;" />
  <format value="generatedCodeEndingComment:// parasoft-end-suppress ALL &quot;generated with delombok&quot;" />
```

### Background
Some static code analysis tools, such as Parasoft Jtest, ignore `@lombok.Generated` annotation. But they support suppression comment like `// parasoft-begin-suppress` and `// parasoft-end-suppress`.
cf. https://docs.parasoft.com/display/JTEST1040/Suppressing+the+Reporting+of+Findings

**Comment by rspilker** [comment]
Wouldn't it make more sense to ask Parasoft JTest to allow for configurable Generated annotations?

It is possible to instruct delombok to insert `@javax.annotation.Generated`.

**Comment by satob** [comment]
We have already report this problem to Parasoft in Aug 2017. But unfortunately, nothing has changed for now.

**Comment by rspilker** [comment]
Hmm, sorry. We've never heard of this tool before. So far, all other static code analyzers either respect `@javax.annotation.Generated`, or have configurable suppression annotations.
