### ISSUE TITLE
[FEATURE] support for tinylog

### ISSUE THREAD

**Issue by BaumannAxel** [rzwitserloot/lombok#2243]
could you please add the @Tinylog annotation for the logging framework tinylog

https://tinylog.org/v2/

**Comment by rspilker** [comment]
Duplicate of #2213

**Comment by rspilker** [comment]
It would help if you could explain what you mean by "support".

If you would have a plain Java example what you would need to type of you're using Tinylog, and have a the same example using a `@TinyLog` annotation, we could see if the amount of boilerplate removed would warrant a separate annotation.

From reading the Tinylog documentation, my impression was that we wouldn't remove any (significant) boilerplate.
