### ISSUE TITLE
@Cleanup question

### ISSUE THREAD

**Issue by hulvyou** [rzwitserloot/lombok#2252]
hi I have a question 
@Cleanup InputStream is = new FileInputStream();
 generate code
 if (Collections.singletonList(is).get(0) != null) {
      is.close();
   }
not 
 if (is != null) {
      is.close();
   }
why use Collections.singletonList() ?

**Comment by janrieke** [comment]
My guess: To prevent static analysers to complain about unnecessary `null` checks. Doing `if (is != null)` will trigger those warnings if `is` cannot be null. Lombok does not statically analyse the code for which `@Cleanup` is generated, so it cannot know if the check is necessary.

**Comment by Maaartinus** [comment]
The guess is right.... unfortunately, findbugs outsmarts it: The `Collections.singletonList` allocates memory and may end up with an `OutOfMemoryError`, which means that the resource does not get closed. So you get a warning anyway... :(

**Comment by hulvyou** [comment]
Thank you. I see.
