### ISSUE TITLE
[BUG] ToBuilder  and Singular on Maps

### ISSUE THREAD

**Issue by david139** [rzwitserloot/lombok#2254]
Hello,
I believe this is not only for Maps, but my issues was the following:
I have an object that has a Singular map. With the builder I only add one item (singular makes that possible) to the map.
I build the object, then I turn it back to builder with toBuilder.
When I want to add one more object to the map I get UnsupportedOperationException, because the Builder created the object with SingletonMap, making it impossible the add any more items, even in ToBuilder.

**Comment by cezar-tech** [comment]
I'm using Intellij here, and even if you pass more than one element to the collection/map it does create an Immutable variation of the variable.

So you can never change it no matter how many objects you add/put in the builder.

I believe this is intended as in you should have added everything you needed via the builder interface before calling the build method.

Maybe if you require to add more objects later you should consider using @With(er) to create a copy of the instance allowing you to change the @With annotated field.

**Comment by rzwitserloot** [comment]
Cannot reproduce. Tried:

	import lombok.*;
	import java.util.*;

	@Builder(toBuilder = true) class Test {
	        @Singular Map<String, String> elems;

	        public static void main(String[] args) {
	                System.out.println(Test.builder().elem("a", "b").build().toBuilder().elem("c", "d").build().elems);
	        }
	}

which works fine.
