### ISSUE TITLE
[BUG] Builder class generated by @Builder not found as a symbol during compilation using JDK 12

### ISSUE THREAD

**Issue by RobertoGraham** [rzwitserloot/lombok#2257]
When compiling a class annotated with `@Builder` using mvn clean package with OpenJDK 12, the compilation fails with the error, "cannot find symbol."

Compiling the following class using OpenJDK 11 does not fail.

```java
package io.github.robertograham.departureapi.client.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import lombok.Builder;
import lombok.NonNull;
import lombok.Value;

import java.math.BigDecimal;
import java.time.ZonedDateTime;
import java.util.List;

@Builder(builderMethodName = "newBuilder", builderClassName = "Builder")
@Value
@JsonDeserialize(builder = PlacesResponse.Builder.class)
@JsonPOJOBuilder(withPrefix = "")
public class PlacesResponse {

    @JsonProperty("request_time")
    @NonNull
    ZonedDateTime requestTime;

    @JsonProperty("source")
    @NonNull
    String source;

    @JsonProperty("acknowledgements")
    @NonNull
    String acknowledgements;

    @JsonProperty("member")
    @NonNull
    List<Member> members;

    @lombok.Builder(builderMethodName = "newBuilder", builderClassName = "Builder")
    @Value
    @JsonDeserialize(builder = Member.Builder.class)
    @JsonPOJOBuilder(withPrefix = "")
    public static class Member {

        @JsonProperty("type")
        @NonNull
        Type type;

        @JsonProperty("name")
        @NonNull
        String name;

        @JsonProperty("description")
        String description;

        @JsonProperty("latitude")
        @NonNull
        BigDecimal latitude;

        @JsonProperty("longitude")
        @NonNull
        BigDecimal longitude;

        @JsonProperty("accuracy")
        @NonNull
        Integer accuracy;

        @JsonProperty("atcocode")
        String atcoCode;

        @JsonProperty("distance")
        Integer distance;
    }
}
```

Maven error logs:

```text
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /src/main/java/io/github/robertograham/departureapi/client/dto/PlacesResponse.java:[16,42] cannot find symbol
  symbol:   class Builder
  location: class io.github.robertograham.departureapi.client.dto.PlacesResponse
[ERROR] /src/main/java/io/github/robertograham/departureapi/client/dto/PlacesResponse.java:[38,38] cannot find symbol
  symbol:   class Builder
  location: class io.github.robertograham.departureapi.client.dto.PlacesResponse.Member
```

JDK 12, Lombok 1.18.10

Here is my pom:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.9.RELEASE</version>
        <relativePath/>
    </parent>

    <groupId>io.github.robertograham</groupId>
    <artifactId>departure-api</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <name>Departure API</name>
    <description>Transport API abstraction layer</description>

    <properties>
        <java.version>12</java.version>
        <spring-cloud.version>Greenwich.SR3</spring-cloud.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit-jupiter.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by rspilker** [comment]
I cannot see the lombok version in your pom file, so how do you know it's `Lombok 1.18.10`?

**Comment by rspilker** [comment]
Oh, and can you please give a smaller source file and pom that reproduces this problem?

**Comment by RobertoGraham** [comment]
> 
> 
> I cannot see the lombok version in your pom file, so how do you know it's `Lombok 1.18.10`?

```text
$ mvn dependency:tree | grep lombok
[INFO] +- org.projectlombok:lombok:jar:1.18.10:provided
```

**Comment by Andreby42** [comment]
I get the same problem.

lombok jar version 1.18.2

jdk 11 

use annotaions:

@Builder(builderClassName = "Builder", toBuilder = true)
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor

**Comment by jamie-codez** [comment]
I had the same problem.

**Comment by jamie-codez** [comment]
I had the same problem, but after wasting 30 mins I realized I had not added the annotation processors. Just add the annotation processor and it should compile just fine.

**Comment by adrhc** [comment]
package ro.go.adrhc.rclonevirtualstorage.infrastructure.cloud;

import lombok.Builder;

@Builder
public record RCloneLsJsonParams(boolean includeFiles,
		boolean includeDirs, int maxDepth, String partition) {
	public static final int RECURSE = -1;

	public static RCloneLsJsonParams filesAndDirs(int maxDepth, String account) {
		return withPartition(account).includeFiles(true).includeDirs(true).maxDepth(maxDepth).build();
	}

	public static RCloneLsJsonParams.RCloneLsJsonParamsBuilder withPartition(String partition) {
		return RCloneLsJsonParams.builder().partition(partition);
	}

	public static RCloneLsJsonParams.RCloneLsJsonParamsBuilder filesOnlyRecursive(String partition) {
		return withPartition(partition).includeFiles(true).maxDepth(RECURSE);
	}
}

`mvn compile` fails with:

> symbol:   class RCloneLsJsonParamsBuilder
> location: class ro.go.adrhc.rclonevirtualstorage.infrastructure.cloud.RCloneLsJsonParams

It doesn't fail on:
Ubuntu 24.04.1 LTS
java -version
java version "21.0.3" 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)

It only fails on (same Java version):
Ubuntu 22.04.5 LTS 
IntelliJ IDEA 2024.3.1.1 (Community Edition)
Build #IC-243.22562.218, built on December 18, 2024
Runtime version: 21.0.5+8-b631.28 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 5.15.0-130-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  ide.experimental.ui=true
  i18n.locale=
  llm.show.ai.promotion.window.on.start=false
Non-Bundled Plugins:
  Lombook Plugin (243.21565.193)
  org.sonarlint.idea (10.14.1.80220)
Kotlin: 243.22562.218-IJ
Current Desktop: XFCE

**Comment by shubham122334** [comment]
I had the same problem but after adding the below configuration it got resolved .

<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.30</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

**Comment by shubham122334** [comment]
I had the same problem but after adding the below configuration it got resolved.

> <build>
	<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<configuration>
				<annotationProcessorPaths>
					<path>
						<groupId>org.projectlombok</groupId>
						<artifactId>lombok</artifactId>
						<version>1.18.30</version>
					</path>
				</annotationProcessorPaths>
			</configuration>
		</plugin>
	</plugins>
</build>

**Comment by yattorie** [comment]
> I had the same problem but after adding the below configuration it got resolved.
> 
> > 
> 
> ```
> <plugins>
> 	<plugin>
> 		<groupId>org.apache.maven.plugins</groupId>
> 		<artifactId>maven-compiler-plugin</artifactId>
> 		<configuration>
> 			<annotationProcessorPaths>
> 				<path>
> 					<groupId>org.projectlombok</groupId>
> 					<artifactId>lombok</artifactId>
> 					<version>1.18.30</version>
> 				</path>
> 			</annotationProcessorPaths>
> 		</configuration>
> 	</plugin>
> </plugins>
> ```

thank you so much
