### ISSUE TITLE
[BUG] RuntimeException>ClassNotFoundException "lombok.javac.handlers.HandleLog$HandleCustomLog"

### ISSUE THREAD

**Issue by burdoto** [rzwitserloot/lombok#2259]
**Describe the bug**
Lombok refusing to run when compiling, this is the only warning I receive:
![grafik](https://user-images.githubusercontent.com/42473485/66788845-75a44000-eee9-11e9-8194-acc017f92c01.png)

**To Reproduce**
The errror consists in this project, basically just from basic setup.
https://github.com/codebottle-io/codebottle-java

**Expected behavior**
no warning showing up lmao

**Version info (please complete the following information):**
Using IntelliJ 2019.1 and Gradle with the following imports: 
```
    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.10'
    annotationProcessor 'org.projectlombok:lombok:1.18.8'
```
Annotation processing indeed is enabled in IntelliJ.

**Comment by Maaartinus** [comment]
This may be related to the idea plugin and/or the fact that `CustomLog` is rather new. Normally, such errors come from having two different versions of a library on the class path.

All I (just a random guy here) can recommend is to try to upgrade the plugin and/or downgrade Lombok. Or search the [plugin issues](https://github.com/mplushnikov/lombok-intellij-plugin/issues).

**Comment by kushal256** [comment]
I had the the same issue @Maaartinus is correct

I had an old dependency upon 1.18.8 within my ~/.gradle cache so manually removed it, now everything works

**Comment by rspilker** [comment]
@burdoto Did the suggestions from @Maaartinus and @kushal256 help you solve the problem?

**Comment by burdoto** [comment]
I've noticed that I've been depending on two different minor versions of Lombok:
![grafik](https://user-images.githubusercontent.com/42473485/66888178-d319b900-efdd-11e9-98ad-f270be7d3016.png)

Resolving this solved the problem.

**Comment by wshidaijingshen** [comment]
if your os is windows
1)  just delete all the jar files on your local maven repository 
2) mvn clean package 
3) better click button "Rebuild project" 
4) run[or debug] your app, should be ok now !

Takes me alot of time to solve this weird bug! ah.........
![image](https://user-images.githubusercontent.com/34682234/118776675-d1e7f680-b8ba-11eb-84da-46dfbc5f8784.png)

![image](https://user-images.githubusercontent.com/34682234/118776999-3014d980-b8bb-11eb-92d5-13a389355946.png)
