### ISSUE TITLE
lombok custom return type[FEATURE] 

### ISSUE THREAD

**Issue by CBillZhang** [rzwitserloot/lombok#2260]
![89aced40a8dcb36ca2ffdb7a76571a8](https://user-images.githubusercontent.com/12945259/66809142-5a741780-ef5f-11e9-94f5-8408d86aeefe.png)

Sometimes what I define as a parameter is a json String of strings, but the type that needs to be returned by get is List, whether lombok supports custom return types, or there are other ways to solve it

**Comment by janrieke** [comment]
Please describe what you expect Lombok to do. If possible, give
a) some example code with a (hypothetical) Lombok annotation, and
b) what the generated code should look like.

**Comment by CBillZhang** [comment]
![63beb5f7f5dc9b5160f6787beb669df](https://user-images.githubusercontent.com/12945259/66822086-1dffe600-ef76-11e9-9c08-ff8d9d5bf572.png)
Image 1 shows that under normal conditions, get and set are consistent
![f39bf2f540819d0bba2350be6226d42](https://user-images.githubusercontent.com/12945259/66822477-e34a7d80-ef76-11e9-9cef-e6cd43182918.png)

Image 2 is the result I want. String is the data of json type. When I return, I need to convert it into a list or a map.In set,can take an object and convert it to a json string

**Comment by Maaartinus** [comment]
@CBillZhang I guess, you don't expect Lombok transforming `private String messageData;` into image 2 without any annotation. If there was `@lombok.DoWhatIWant`, it could possibly work. But seriously, how should this happen? Something like
```
@GetterUsing("BZJson.toAny(messagedata, new TypeToken<List<String>>() {}")
@SetterUsing("BZJson.decodeJson(messageData)")
private String messageData;
```
is probably not what you want, but how else would you tell Lombok what to do? Using strings is a terrible idea, using methods is impossible in annotation, so what's left?

**Comment by janrieke** [comment]
But how should Lombok know what kind of conversion it should do? You will always have to specify that manually, so the amount of code that can be saved by a Lombok annotation is close to zero.

**Comment by rspilker** [comment]
I agree with @janrieke and @Maaartinus
