### ISSUE TITLE
[BUG] ExtensionMethod fails in specific case in Maven, works in Eclipse

### ISSUE THREAD

**Issue by arjvik** [rzwitserloot/lombok#2261]
**Describe the bug**
This problem is oddly specific in that it fails only when compiling w/ Maven (javac) but works in Eclipse. I have several domain objects, including `Test` (representing an exam) and `Question` (representing an exam question). I have a class with extension methods:

```java
@UtilityClass
public class StringCleanseExtensions {

	public static String cleanse(String s) {
		return s.replaceAll("[‘’]", "'")
			.replaceAll("[“”]", "\"")
			.replaceAll("[^\\n\\p{Print}]", "");
	}

	public static void cleanse(Question q) {
		q.setLabel(cleanse(q.getLabel()));
	}
	
	public static void cleanse(Test t) {
		t.setName(cleanse(t.getName()));
	}
}
```

I then use the extension methods as follows:

```java
@ExtensionMethod(StringCleanseExtensions.class)
public class Demo {
	public void stuff() {
		Question q = new Question();
		Test t = new Test();

		q.cleanse(); //works fine
		// t.cleanse(); //works in Eclipse, fails to compile via Maven
		StringCleanseExtensions.cleanse(t); //works fine, but ugly
	}
}
```

I actually have several more domain objects, including `TestResponse`, `Answer`, and more. and only `Test` causes this problem.

**Expected behavior**
The extension methods should work on both `Test`s and `Question`s.

**Version info:**
 - Lombok version: v18.8
 - Platform: Eclipse 2019-9 R (4.13.0)
 - Maven version: 3.6.0
 - Java version: Source 1.8, Target 1.8 (pom.xml)

**Comment by Rawi01** [comment]
This one is quite interesting, the problem is indeed the name. 

Lombok does not apply extension methods if the type name ends with the variable name. In your case `Test` ends with `t` which is also the name of the used variable. Simply renaming `t` to `test` fixes your problem. I will try to replace the check with something better...

**Comment by arjvik** [comment]
> Lombok does not apply extension methods if the type name ends with the variable name

Why is that? That seems like a very silly assumption to make.

**Comment by Rawi01** [comment]
That was exactly what I thought when I read that line. It is there to exclude static methods. Without that check lombok would transform `Test.cleanse()` to `StringCleanseExtensions.cleanse(Test)`. I think I figured out how this check could be done right, PR is almost done, just need to add a proper test case.

**Comment by arjvik** [comment]
Thank you @Rawi01!
