### ISSUE TITLE
[BUG] getter and setter method consistent with the rules

### ISSUE THREAD

**Issue by rainlinsu** [rzwitserloot/lombok#2266]
I am terribly sorry for my poor English.
**Describe**
The first word is a lowercase letter, the second uppercase, getter/setter method not consistent with the rules

**To Reproduce**
```
@Data
public class User {
    private String uName;
}
```
```
        User user = new User();
        // should be getuName()
        user.setUName("Jim");
```
getter/setter method should be getuName()/setuName()

**Version**
```
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<version>1.18.10</version>
	<scope>provided</scope>
```

**Comment by Maaartinus** [comment]
Duplicate of #757.

**Comment by rzwitserloot** [comment]
Duplicate of #2693
