### ISSUE TITLE
Bug with @Accessors annotation in Lombok[BUG] 

### ISSUE THREAD

**Issue by villebo** [rzwitserloot/lombok#2270]
The following exceptions occur when introspecting using @accessors annotated beans in Lombok:

"Java. Beans. IntrospectionException: Method not found"  

Use the latest version of Lombok in Spring boot2.2.0+lombok 1.18.10

**Comment by Maaartinus** [comment]
By default, Lombok generates mostly Java Beans compatible getter and setter. Any meaningful use of `@Accessors` changes that. For example, a this-returning setter won't get found by introspection.

You can't use both `@Accessors` and the Java Beans Crapification. Here, nothing can be done.

**Comment by rzwitserloot** [comment]
indeed, not a bug, thanks Maaartinus.
