### ISSUE TITLE
[FEATURE] nullchecks in array elements

### ISSUE THREAD

**Issue by Coada** [rzwitserloot/lombok#2271]
Hello,

I am interested in the feature of using `@NonNull` on an array, such that the array's elements are also being checked. Optionally using something such as `@NonNullElements` might be introduced to not modify how `@NonNull` operates.

```
@NonNull String[] stringArray;

stringArray = null; // NOK
stringArray = new String[]{null}; // NOK
```

I believe this is related to #2019 and specifically https://github.com/rzwitserloot/lombok/issues/2019#issuecomment-454184587

The benefits would be for developers who mistakenly think they are safe from doing null-checking on the elements themselves. Despite having [all these null-checking annotations](https://stackoverflow.com/questions/4963300/which-notnull-java-annotation-should-i-use) as help, a developer must _still_ do these checks to be safe.

**Comment by rzwitserloot** [comment]
Too specific, not boilerplate. I also think that developers presuming that `@NonNull` on an array element implies that individual elements also cannot be null is bizarre and not worth catering to. Specifically:

* arrays of non-primitive types are obsolete. Do not use these in your codebase; use `List<String>` instead.
* There are type-use annotations; `String @NonNull []` is more appropriate (but adding explicit nullcheck code to this is not a good idea; whilst for arrays lombok would know how, for something like `List<@NonNull String>` lombok would not.
