### ISSUE TITLE
[FEATURE] lombok with jackson not recognize jsonformat on deserialize

### ISSUE THREAD

**Issue by alencarmo** [rzwitserloot/lombok#2272]
**Before submitting**
Please check our [wiki](https://github.com/rzwitserloot/lombok/wiki) because some feature requests are asked _a lot_ and there are good reasons (as explained on the wiki) why we can't (yet) implement them or why we won't implement them.

**Describe the feature**
A clear and concise description of what the feature request/enhancement is. What is the goal of adding this feature request? This should include 2 java snippets: One 'lomboked' version, which is java code with (for example) an annotation that is short and boilerplate free, and a second snippet that shows precisely what lombok will do under the hood. Lombok can only turn java code that is valid java syntax into different java code.

**Describe the target audience**
Describe which programmers and/or which kinds of programs would benefit from your feature proposal. If the feature proposal interacts with a library that isn't part of the core java libraries, link to this project.

**Additional context**
Add any other context about the feature / enhancement here.

**Comment by alencarmo** [comment]
Hi...the jackson isn't recognizing @jsonformat on deserialize. I already tried many alternatives but unsucessfull, anyone can help me ? What is wrong in this code ?
I'm with java 8 - lombok 1.18.10 - jackson 2.9.9. 
Tks !
`@Data
@JsonDeserialize(builder = ContractRequest.ContractRequestBuilder.class)
@Builder(builderClassName = "ContractRequestBuilder", toBuilder = true)
public class ContractRequest implements Serializable {

	private static final long serialVersionUID = 1L;
	private String source;
	private String contractNumber;
	private String description;

	@JsonIgnore
	private String protocolUuid;
	
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", timezone = "GMT-3")
    private Date startDate;

	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", timezone = "GMT-3")
	private Date endDate;
	@JsonPOJOBuilder(withPrefix = "")
	public static class ContractRequestBuilder {
          }
}
`

**Comment by janrieke** [comment]
That's not a Lombok issue. Please ask at StackOverflow, and close this here.

**Comment by rspilker** [comment]
@alencarmo you can run delombok to test if lombok is the problem.

**Comment by alencarmo** [comment]
Sorry the post in wrong place !! tks !
