### ISSUE TITLE
[BUG] Install lombok 1.18.10 on SpringToolSuite 4.4.1.RELEASE results SpringToolSuite damage

### ISSUE THREAD

**Issue by ozooxo** [rzwitserloot/lombok#2276]
**Describe the bug**
Install lombok 1.18.10 on SpringToolSuite 4.4.1.RELEASE results SpringToolSuite damage. Error message `"springtoolsuite4" is damanged and can't be open`. 

**To Reproduce**
On Mac OS, installed the newest version of SpringToolSuite (version 4.4.1.RELEASE) from https://download.springsource.com/release/STS4/4.4.1.RELEASE/dist/e4.13/spring-tool-suite-4-4.4.1.RELEASE-e4.13.0-macosx.cocoa.x86_64.dmg

```
cd .m2/repository/org/projectlombok/lombok/1.18.10/
sudo java -jar lombok-1.18.10.jar
```

choose `/Applications/SpringToolSuite4.app/Contents/Eclipse/SpringToolSuite4.ini` and install lombok.

Then when opening the SpringToolSuite it errors out with message `"springtoolsuite4" is damanged and can't be open`. 

(Tried the same thing with 1.18.4, and everything works fine. Lombok is up and run.)

**Expected behavior**
SpringToolSuite should still be able to open, and in code `setSomeAttribute` and `getSomeAttribute` should not be treated as error.

**Version info (please complete the following information):**
 - Lombok version: 1.18.10

```
java -version
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```

SpringToolSuite: 4.4.1.RELEASE

OS: MacOS High Sierra 10.13.6

**Comment by devdotlog** [comment]
i has same issue. so i solved it this way. https://secure.clcbio.com/helpspot/index.php?pg=kb.page&id=323

**Comment by rzwitserloot** [comment]
Sounds like it's not our issue then. If you think it is something lombok can fix, please include a full dump of that ini file pre- and post- install, try to undo the install, and run the app prior to invoking lombok to ensure it wasn't already broken.

Nothing changed in the installer between 1.18.10 and 1.18.4 which makes this bug hard to believe.

**Comment by tareynoso** [comment]
> i has same issue. so i solved it this way. https://secure.clcbio.com/helpspot/index.php?pg=kb.page&id=323. It's not a lombok issue.
Thank you.
I solved that way

**Comment by janrieke** [comment]
.
