### ISSUE TITLE
[BUG] @SuperBuilder with Generics

### ISSUE THREAD

**Issue by MertOzdogan** [rzwitserloot/lombok#2278]
Details could be found here;

https://stackoverflow.com/questions/58641279/wrong-number-of-arguments-with-lombok

**Comment by janrieke** [comment]
Does this affect both Eclipse and maven/gradle builds?

**Comment by MertOzdogan** [comment]
@janrieke I do work on IJ, and for maven build, yes it does effect.

**Comment by janrieke** [comment]
Also when running maven manually (not from IJ)?

**Comment by janrieke** [comment]
I just checked it myself: This is not an IJ plugin bug. It affects only javac, Eclipse compilation works.

**Comment by rzwitserloot** [comment]
Duplicate of #2262 See PR #2273  for fix.
