### ISSUE TITLE
[FEATURE] Execution time monitor

### ISSUE THREAD

**Issue by fishjam** [rzwitserloot/lombok#2279]
- Feature description
  Consider add following annotation *Elapse*, and it can monitor the method execute time, If the execution time of the method exceeds the threshold, then log with warning message.I think this can help programer to find the performance issue.

```
@Target({ ElementType.TYPE, ElementType.METHOD} )
@Retention(RetentionPolicy.SOURCE)
public @interface Elapse {
  long max() default 1000;
}
```

- Before lombok handle
```
@Slf4j
@Elapse(max = 500)
public class TestElapse {
  private void hello(String user) {
    log.info("enter hello, {}", user);
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      log.error("InterruptedException in fun_1", e);
    }
    log.info("leave hello, {}", user);
  }
}
```

- After lombok handle
```
  ...
  private void hello(String user) {
    long _startTime = System.currentTimeMillis();
    log.info("enter hello, {}", user);
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      log.error("InterruptedException in fun_1", e);
    }
    log.info("leave hello, {}", user);
    long _elapseTime = System.currentTimeMillis() - _startTime;
    if (_elapseTime > 500L) {
      log.warn("elapse too long, want {} ms, real {} ms", 500L, _elapseTime);
    }
  }
```

- TODO
  - 1. consider this is option for programer, It's good for provide a ConfigurationKey to control whether the function is effective. example: lombok.elapse.enable 
  - 2. it can add String[] exclude() too.

**Comment by rzwitserloot** [comment]
Java timing is very tricky, and just timing a method like this is not how it's done. Use a profiler to find hotspots, and use JMH to thoroughly test them.
