### ISSUE TITLE
[FEATURE] Generate Java 9 System.Logger

### ISSUE THREAD

**Issue by t1** [rzwitserloot/lombok#2281]
**Description**

Java 9 introduced a new logging API that can be implemented by different logging libraries. The fallback implementation is the Java Util Logging. Lombok could add another generator annotation for the Logger field:

Lomboked:
```java
@Log9
public class Foo {
}
```

Deomboked:
```java
import java.lang.System.Logger;
import static java.lang.System.getLogger;

public class Foo {
    private static final Logger log = getLogger(Foo.class.getName());
}
```

**Target Audience**
Programmers that want to use the new `System.Logger` API.

**Comment by t1** [comment]
Reconsidering the goals of [JEP](https://openjdk.java.net/jeps/264), it's not supposed to be a generic logging API, so I think lombok should deliberately _not_ add support for it.
I'm closing the issue.

**Comment by onacit** [comment]
@t1 Would you please reconsider reconsidering the goals of the JEP?

**Comment by t1** [comment]
@onacit : The JEP says clearly: "Define a minimal logging API which platform classes can use to log messages". And with "platform classes" they mean JDK classes, not application code. That's clearly the intention of the JEP.

What is your intention? It may be worth ~re~considering [slf4j](https://www.slf4j.org) for your applications 😁

**Comment by onacit** [comment]
@t1 Thank you for the reply.
Yes that's what they said in the _JEP_.
Yet the ~~speculated~~ intention of the JEP and the fact that they defined it within public `System` class is very re-considerable, I believe.

I'm writing a library, based on Java 11 and Java 11 only.

I'll happily depend on `slf4j-api`(provided) and `logback-classic`(test) when it targets platforms have no problems such as Spring.

But making the code as clean as possible with no 3rd party sometimes matters, I think.

As the example you drew, 

```java
class Foo {
    private static final Logger log = System.getLogger(Foo.class.getName());

    void doSome() {
        log.log(Level.ERROR, "JUL/SLF4j whatever you'll see me");
    }
}
```

Thank you for your time.
My best Regards.

**Comment by rzwitserloot** [comment]
Feature requests whose primary use will clearly be to __write bad code__ are denied.

This is one of those. It doesn't matter that you think it's great to use `System.getLogger` for your use case. The javadoc says you're abusing the API; it's not intended for this kind of thing.

**Comment by t1** [comment]
You also depend on JDK 11 🤪 You even say `Java 11 and Java 11 only`, but I suppose you don't really want to exclude JDK 19ff 😁

What I want to say is this: dependencies _are_ a concern, but you don't have to overreact.

**Comment by jgsuess** [comment]
May I say that the java.util package is one of the biggest and hardest to resolve dependency nodes of the module system in the JDK? I would not consider preventing dragging this in as bad code. Especially for highly streamlined applications in IoT and those with security requirements where every dependency is a validation requirement, I find that statement a bit opinionated. I have experience in those areas, so this is not just reaching for something.

In consequence, this forces lombok users to write clunk code or, as I have done, go back to apt to go around the opinion. For me Lombok up to this point was a sensibly opinionated Java. Alas.

**Comment by jgsuess** [comment]
As for the bible-analysis reading of JEP's intent. This is an API, not an internal interface. Stands to reason that the platform being quoted is the Java runtime platform. Further, from expanding the `A` in API, I think it is for `Application`s to use it. Otherwise, I would assume there would be `JDK classes only` stickers all over it. However, then there would be far less point in publishing it.
