### ISSUE TITLE
[BUG] @Builder.ObtainVia with a super class does not work anymore in JDK1

### ISSUE THREAD

**Issue by slyoldfox** [rzwitserloot/lombok#2284]
Following construct works fine in JDK8

```
@AllArgsConstructor
@Getter
@Setter
public class SuperClass {
    private Long id;
    private Date createdDate;
}

@Getter
@Setter
public class TestClass extends SuperClass {
    private String name;

    @Builder(toBuilder = true)
    protected TestClass( @Builder.ObtainVia(method = "getId") Long id,
                         @Builder.ObtainVia(method = "getCreatedDate") Date createdDate,
                          String name ) {
        super(id, createdDate);
        this.name = name;
    }
}
```

However this fails to compile in JDK11 with the error:
```
[ERROR] /Users/marc/Code/temp/demo/src/main/java/com/example/demo/TestClass.java: incompatible types: java.util.Date cannot be converted to java.lang.Long
```

It's like it keeps looking at the first argument of that builder?

**Comment by devdotlog** [comment]
@slyoldfox 
Remove `toBuilder = false` .  Then no error occurs. Use Builder() insted of toBuilder().

**Comment by slyoldfox** [comment]
@devdotlog thank you for the suggestion, it is exactly what I had to do (and rework a bunch of code). toBuilder is an instance method which copies the existing object (well not quite - not the super class unles you specify your own builder, which is what we have it in place for).

We mainly use it for dto update scenario's.

**Comment by janrieke** [comment]
You could also give `@SuperBuilder` a try. It also supports `toBuilder` and you don't have to manually use `@ObtainVia`.

However, this is still a bug and should be fixed.

**Comment by slyoldfox** [comment]
@janrieke yes I know about that.
But `@SuperBuilder` would imply also a `@SuperBuilder` on the super class?
The super class is not part of our code so we cannot go down that road.

Just adding `@SuperBuilder` on the subclass does not work because it fails to compile with `cannot find symbol SuperClassBuilder`

**Comment by janrieke** [comment]
Yes, then you cannot use `@SuperBuilder`.

**Comment by rzwitserloot** [comment]
I'm pretty sure I fixed this in the latest edge, see issue 2335.
