### ISSUE TITLE
[FEATURE] Text Blocks

### ISSUE THREAD

**Issue by mageddo** [rzwitserloot/lombok#2288]
### Describe the feature

I'm proposing to implement [TextBlocks](https://openjdk.java.net/jeps/355) on lombok, it is a really nice feature to who works with medium or large string literals.

With lombok

```java
public class Stuff {
  public void doSomething(){
    /*
    Lorem Ipsum is simply dummy text of 
    the printing and typesetting industry
     */
    @TextBlock
    final String text = Lombok.lazyInit(); // this method throws an exception if called  then it ensures lombok is working
    System.out.println(text);
  }
}
```

Vanilla

```java
public class Stuff {
  public void doSomething(){
    /*
    Lorem Ipsum is simply dummy text of 
    the printing and typesetting industry
     */
    @TextBlock
    final String text = "\n" +
    "\t\tLorem Ipsum is simply dummy text of \n" +
    "\t\tthe printing and typesetting industry\n" +
    "\t\t "
    System.out.println(text);
  }
}
```

### Describe the target audience

**Programmers who develop software which connect to databases which are based on query languages like SQL, CQL, etc.**

The query below would be much cleaner to understand if it were put on the variable javadoc as the example, it would much simpler to copy and paste it across a database client and the java code, it would make the query troubleshooting much easier too

```java
final String query = "SELECT DISTINCT p.products_id,                    #simple product id\n" +
"                products_name,                    #product name\n" +
"                products_attributes_id,           #color id\n" +
"                pov.products_options_values_name  #color name\n" +
"FROM   products p\n" +
"       LEFT JOIN products_description pd\n" +
"         ON p.products_id = pd.products_id\n" +
"WHERE p.products_id in (\n" +
"       Select products_id from products_attributes pa #This will give you the ID forall bikes that have either red or brown in them\n" +
"       INNER JOIN products_options_values pov\n" +
"         ON pov.products_options_values_id = pa.options_values_id\n" +
"       INNER JOIN products_options_search pos\n" +
"         ON pov.products_options_values_id = pos.products_options_values_id\n" +
"       WHERE  pos.products_options_search_id = 4         #code for red\n" +
"            OR pos.products_options_search_id = 5      #code for brown)"
```

**People who do unit tests comparing texts**

People who work with REST APIs or process text files will have the make the compare while testing, and it would be much nicer if they could see the text without all java boilerplate

```java
// arrange
/*
{
	"id": 32,
	"address": "My Street, 77",
	"district": "Brás",
	"cityId": 16,
	"cep": 3006020,
	"creation": "2018-02-18T13:15:12",
	"update": "2018-02-18T13:15:12"
}
 */
@TextBlock
final var expectedJson = "";

// act 
final var responseJson = doSomeHttpGet();

// assert
org.junit.jupiter.api.Assertions.assertEquals(expectedJson, responseJson)
```

Instead of 

```java
// arrange
final var expectedJson = "{\n" +
			"\t\"id\": 32,\n" +
			"\t\"address\": \"My Street, 77\",\n" +
			"\t\"district\": \"Brás\",\n" +
			"\t\"cityId\": 16,\n" +
			"\t\"cep\": 3006020,\n" +
			"\t\"creation\": \"2018-02-18T13:15:12\",\n" +
			"\t\"update\": \"2018-02-18T13:15:12\"\n" +
			"}";

// act 
final var responseJson = doSomeHttpGet();

// assert
org.junit.jupiter.api.Assertions.assertEquals(expectedJson, responseJson)
```

**Additional context**

* I already developed a simple lib that implement this behavior, it is very simple and only maintened by me anyway, I think it could have a better support and people acceptance if developed at lombok project. 
  * [the lib](https://github.com/mageddo/mageddo-projects/tree/master/raw-string-literals)
  * [a demo](https://github.com/mageddo/mageddo-projects/tree/master/raw-string-literals-demo)

**Comment by rzwitserloot** [comment]
We were considering this, but now that [java itself has them](https://openjdk.java.net/jeps/355) this is off the table. Yes, it is in preview, and even when it's out of preview not everybody is ready to just jump and ship and use JDK15, but, there are so many things we can implement, and this problem goes away with time.
