### ISSUE TITLE
[BUG] @SuperBuilder does work on classes named B or C

### ISSUE THREAD

**Issue by janrieke** [rzwitserloot/lombok#2297]
**Describe the bug**
`@SuperBuilder` causes a compilation error when used on classes named `B` or `C`.

**To Reproduce**
Put `@SuperBuilder` on a class named `B` or `C`.

**Expected behavior**
Compiles.

**Version info:**
 - Lombok version 1.18.10
 - javac and eclipse

**Additional context**
Right now lombok only avoids name clashes between builder generics and the class's type parameters. When I implemented `@SuperBuilder`, I forgot to also check for clashes with the class name itself. :(

**Comment by OLPMO** [comment]
Could you provide a small sample the reproduces that behaviour you've described?

**Comment by janrieke** [comment]
If you insist ;-)

`@SuperBuilder public class B {}`

**Comment by rzwitserloot** [comment]
I'm not too worried about classes named B, but... how about:

    @SuperBuilder class Example<B> {}

Looks like you're already working on a PR; should I wait for you to finish this?

**Comment by janrieke** [comment]
The type parameters on the class are OK, those are already checked against collisions.

It's just the class name or classes referenced e.g. by fields (e.g. `private C myC`).

I'm also not sure if it's worth the effort: We'd have to go through the complete source of the compilation unit to find possible collisions. I don't know the performance impact of that.
