### ISSUE TITLE
[FEATURE] Support for Slf4j 2x

### ISSUE THREAD

**Issue by gonciarz** [rzwitserloot/lombok#2298]
At the moment 1.7.25(26) version of Slf4j is used in lombok. In Jun 2019 Slf4j team released 2.0a. It adds ability to use supplier as an argument to log. API is not so pretty, but does it job:

`logger.atDebug().addArgument(() -> heavyMethod())
.log(msg, "Temperature set to {}. Old temperature was {}.", oldT);`

**Comment by rzwitserloot** [comment]
Lombok just gives you a log variable, it doesn't generate anything else. What should lombok change? Is there a new class we need to make?

Right now we generate:

    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(ClassThatYouPutTheSLf4jAnnotationOn.class);

that is all.

What would be different?

close if no feedback by 2020-02-10.

**Comment by rspilker** [comment]
No feedback from reporter
