### ISSUE TITLE
[FEATURE] Annotation to copy a collection

### ISSUE THREAD

**Issue by cybuch** [rzwitserloot/lombok#2301]
Imagine you have a simple POJO, that you annotate with `@Value`, lets say

```
@Value
@AllArgsConstructor
class Product {
int id;
Set<Category> categories
}
```

So actually what you want is an immutable value object. But do you have one? Not really. Actually the reference to the `categories` will be just the same reference that was passed to the constructor. So if it was mutable implementation of set, then you can change it outside of `Product`. What I'd like to achieve would be some annotation that would create new instance of Set, so it will have it's own.

**Comment by janrieke** [comment]
Most cases can be covered using `@Builder` and `@Singular`.
Do you have a specific case that does not work with that?

**Comment by cybuch** [comment]
Nope, I wasn't aware of `@Singular`, my bad. Clossing this issue.
