### ISSUE TITLE
[FEATURE] lazy local variable

### ISSUE THREAD

**Issue by maciekwiso** [rzwitserloot/lombok#2303]
I'd be useful to be able to use `@Getter(lazy=true)` feature on local variables.
But maybe using a different syntax, for example using keyword `lazy` before variable, like this:
`lazy int myVar = some expression;`
So that this expression would only be executed at most once on first usage of myVar variable.

**Comment by rzwitserloot** [comment]
What you propose is not possible; lombok does not run until the syntax is parsed, and what you wrote isn't valid syntax, thus, lombok wouldn't run. It has to be an annotation.

It's too exotic to otherwise consider.
