### ISSUE TITLE
[FEATURE] @Model shortcut

### ISSUE THREAD

**Issue by nimo23** [rzwitserloot/lombok#2306]
**Describe the feature**
Actually I have entities having all the same lombok annotations

```
// lombok dependency hell 
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Entity {

..}
```

Would be nice to provide another annotation like `@Model `which is a **shortcut** for `@Getter`, `@Setter`, `@Builder`, `@NoArgsConstructor`, `@AllArgsConstructor`.

```
@Model
public class Entity {

..}
```

**Comment by rzwitserloot** [comment]
Closed: Duplicate of #2294
