### ISSUE TITLE
[FEATURE] Add to @Delegate annotation ability of specifying some annotations which must be generated as well

### ISSUE THREAD

**Issue by Kabal163** [rzwitserloot/lombok#2319]
Hello everyone!
Faced a problem when I have an embedded class which I mark with "Delegate" annotation and I don't want to serializde/deserialize it with jackson ObjectMapper. Due to lombok generates getters and setters it's impossible to mark them with "JsonIgnor" annotation. It would be nice to have ability to say to lombok which annotations must be generated with the methods.

Example of how it may be:
```
class Person{

   @DelegateGetter(property = "name", annotations_ = {SomeAnnotations})
   public Car car;
}

class Car {
   public String name;
}
```

**Comment by Wdestroier** [comment]
I was going to suggest this either. But I'm thinking about @Delegate(onMethod_={@SomeAnnotation})}. Then it would be possible to have @SneakyThrows(possible exceptions...) in all methods.

**Comment by rzwitserloot** [comment]
Delegate is really complicated, onMethod/onParam is really complicated, and you want to combine them?

I get the need, but, these two features are both at the raggedy edge of what's possible and, to be perfectly honest, probably hanging off the cliff by a single finger.

There's no way it's sane to attempt to combine the two. I'm just going to  close this one; what with the back log and feature requests that aren't so tricky and more high impact, we're never going to get to this. The maintenance burden would also be high enough to mean we can't accept a PR (unless you staple a 10 year maintenance contract for €0,- to the PR :P). My apologies for being so brash!

**Comment by onacit** [comment]
Though it's been closed, I'm adding my own interest to this topic with an another usecase.

```java
class ToBeDelegated {

    @com.google.gson.annotations.Expose(serialize = false, deserialize = false)
    @com.fasterxml.jackson.annotation.JsonIgnore
    @Transient
    public int getSomeAsInt() {
    }

    public void setSomeAsInt(final int someAsInt) {
    }

    @Setter
    @Getter
    private String some;
}

class Delegating {

    // getSomeAsInt and setSomeAsInt are still generated WITHOUT annotations. 

    @Delegate
    private final ToBeDelegated delegate = new ToBeDelegate();
}
```
