### ISSUE TITLE
[BUG] `toString` method generator error

### ISSUE THREAD

**Issue by xubin2016** [rzwitserloot/lombok#2324]
**Describe the bug**
 when model has two fields , example,`name` and `NAME` , `toString` can't recognized

**To Reproduce**
![image](https://user-images.githubusercontent.com/38581317/71611694-0f6cb680-2bd6-11ea-92d0-b30d3d44af19.png)
idea compiled
![image](https://user-images.githubusercontent.com/38581317/71611711-4c38ad80-2bd6-11ea-9434-f3ba1f233aa0.png)

**Comment by trashytop** [comment]
Could you possibly supply some details for your environment?

toString in your example worked fine with this environment:

- IntelliJ IDEA 2019.2.3 (Community Edition)
- Build #IC-192.6817.14, built on September 24, 2019
- Runtime version: 11.0.4+10-b304.69 amd64
- Windows 7 6.1

<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.18.10</version>
    <scope>provided</scope>
</dependency>

**Comment by rspilker** [comment]
The hashcode also looks wrong.

**Comment by rspilker** [comment]
This is not something we can easily fix, and this is also not common practice to have several fields with the same name but different casing. Therefore we're not going to address this. Lombok is for common, boilerplate scenarios.
