### ISSUE TITLE
[BUG] Maven: Java modules wont' build without explicit <annotationProcessorPaths>

### ISSUE THREAD

**Issue by pabloanahata** [rzwitserloot/lombok#2325]
**Describe the bug**
Upgrading from Java 8 to Java 13.

In Java 8, or non-jigsaw 13 (posibly 9+) listing lombok as a provided maven depdency was enough.

When building a Java module system, it seems that the documentation here:
https://projectlombok.org/setup/javac

And the documentation here:
https://projectlombok.org/setup/maven

Are missing the fact that when combining both maven and java 9+ modules, one needs to  add the following to the maven-compiler-plugin

```
<annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.10</version>
                        </path>
</annotationProcessorPaths>
```

So, wether we call it a documentation bug or a feature request (not having to add that snippet) or a bug, would probably be a good idea to put it up clearly somewhere to save the "surfing through the issues list" to find the workaround. Seems like this "workaround" or "setup step" has been needed for a while and is not visible in the setup docs.

- A lombok fanatic

**Comment by rspilker** [comment]
I've updated the source of the documentation. A new release of the website will contain your suggestion.
