### ISSUE TITLE
[BUG] @SuperBuilder can not Use on this class<T>

### ISSUE THREAD

**Issue by MrWangGang** [rzwitserloot/lombok#2330]
```
@Data
@SuperBuilder
@EqualsAndHashCode(callSuper=false)
public class ImportEntity<T> extends FileProcessEntity {
   @NotNull
   protected byte[] file;

   @NotNull
   @Valid
   protected T data;
}
```

**Comment by MrWangGang** [comment]
@SuperBuilder  
can not Use on this class

**Comment by janrieke** [comment]
Does `FileProcessEntity` also has `@SuperBuilder`? If not, add it. Otherwise please post the compiler error.

**Comment by MrWangGang** [comment]
> 是否`FileProcessEntity`也有`@SuperBuilder`？如果没有，请添加它。否则，请发布编译器错误。

FileProcessEntity class already have @SuperBuildera ,but ImportEntity class have  <T> , remove  <T>
can compile.


`Error: name conflict: the < T > builder() in importentity and the builder() in fileprocessentity have the same query character, but neither hide the other

@SuperBuilder

^

Where t is the type variable:

T extension object declared in method < T > builder()`
lombok-1.18.4        idea-193.5662.53    gradle

**Comment by MrWangGang** [comment]
`@Data
@SuperBuilder(builderMethodName = "builderT")
@EqualsAndHashCode(callSuper=false)
public class ImportEntity<T> extends FileProcessEntity {
   @NotNull
   protected byte[] file;

   @NotNull
   @Valid
   protected T data;
}
`

@SuperBuilder(builderMethodName = "builderT")      resolve
