### ISSUE TITLE
[FEATURE] @Accessors: set fluent=true as default

### ISSUE THREAD

**Issue by nimo23** [rzwitserloot/lombok#2331]
**Describe the feature**
There is no use if one uses an annotation of `@Accessors` without setting any of its properties as the default value of `fluent` is `false`. Hence, we always need to set `fluent = true` also. 

```
@Getter
@Accessors(fluent = true)
public class User{

}
```

Would be better to set `true` as the **default** value of `fluent` because thats the main reason why one would use `@Accessors`.

```
@Getter
// should default to (fluent = true)
@Accessors
public class User{
...
}
```

_Btw, when will this feature leave the experimental state?_

**Comment by Maaartinus** [comment]
> Would be better to set true as the default value of fluent because thats the main reason why one would use @Accessors.

Not necessarily. You can set it globally (see "Supported configuration keys" in https://projectlombok.org/features/experimental/Accessors) and then need to restore the old behavior.

Nonetheless, you're probably right, but because of backwards compatibility, it probably can't be changed.

> Btw, when will this feature leave the experimental state?

"soon" - according to the above link.

I guess, it's used a lot, so I'm not afraid to use it (I actually don't as I use the config instead).

**Comment by nimo23** [comment]
Would be better to set `true` as the default value of `fluent` because thats the main reason why one would use `@Accessors`. Why one should bother with "configuration keys" only to 

>Nonetheless, you're probably right, but because of backwards compatibility, it probably can't be changed.

It can be changed as long as it is **experimental**..

**Comment by rzwitserloot** [comment]
No.

What makes `fluent` so special? Why shouldn't it default to `chain` being default true?

making fluency on by default is not a good idea; the advantage of having getX()/setX() is that it plays well with auto-complete dialogs (wanna load a property and not sure what it is named? type get, hit ctrl+space, have a look).

**Comment by nimo23** [comment]
What is the effect when using `@Accessors`:

```
// has no effect, so this annotation is useless by default
@Accessors
class User {
..}
```
@rzwitserloot Dont you think that the main reason for using this annotation is to make use of its `fluent="true"`? I think most of the people will use this annotation only to make use of the _fluent_-thing. So why should the user turn it on on every call?

```
@Accessors(fluent="true")
class User {
..}
```

It is similar as if you were asking to provide an enable flag to enable `@Getter`:

```
// say it twice what you want?
@Getter(enable="true")
class User {
..}
```

However, I think all problems and debates of this kind of clutter and repeating could be resolved and ignored in future if lombok eventually provide https://github.com/rzwitserloot/lombok/issues/2294.

**Comment by nimo23** [comment]
>What makes fluent so special? Why shouldn't it default to chain being default true? making fluency on by default is not a good idea; 

@rzwitserloot  What is the effect when the class is annotated only with `@Accessors`? 

```
// has no effect, so this annotation is useless by default
@Accessors
class User {
..}
```

You see, what I mean? There is no effect when using `@Accessors` because it is the same as `@Accessors(fluent = false, chain = false)`. 

I don't get the point why you don't want to make `@Accessors(fluent = true, chain = false)` **as default** because without it, this annotation has NO effect. That means the user is always forced to enable the flags of `@Accessors`.
