### ISSUE TITLE
[FEATURE] enrich @Accessor to provide replacement for @Getter and @Setter

### ISSUE THREAD

**Issue by nimo23** [rzwitserloot/lombok#2332]
**Describe the feature**

The `@Accessors` is useless without specifying `@Getter` or `@Setter`:

```
// annotation hell
@Getter
@Setter
@Accessors(fluent = true)
public class User {
 ...
}
```

However, if `@Accessors `would have two additional properties "`getter="true/false`" and "`setter=true/false`", there would be not need to add those annotations additionally:

```
// sleek
@Accessors(fluent = true, getter="true", setter="true)
public class User {
 ...
}
```

**Comment by rzwitserloot** [comment]
No; if we add that, there are now 2 ways to accomplish the exact same thing which is useless clutter; the suggested way is barely shorter, and obviously we can't make the first way go away.

**Comment by nimo23** [comment]
@rzwitserloot ok, got it. However, such debates can be avoided in future if lombok provides https://github.com/rzwitserloot/lombok/issues/2294. With this do not bother to use 



```
Target({ElementType.TYPE})
@Retention(RetentionPolicy.SOURCE)
@Documented
@Getter
@Setter
@Accessors(fluent = true)
public @interface LombokEntity {}
```

because I only need to define it on only one place and can use it on all other places without repeating these annotations all over again:

```
@LombokEntity
public class Entity {
..
}
```
