### ISSUE TITLE
[BUG] About @Slf4j  cannot make a static reference to the non-static field   

### ISSUE THREAD

**Issue by hg460713171** [rzwitserloot/lombok#2334]
**Describe the bug**
when use @Slf4j  
public String org;
ide compile error : cannot make a static reference to the non-static field   org

**To Reproduce**

import lombok.extern.slf4j.Slf4j;
@Slf4j
public class TestSlf4j {
    public String org;
}
this code cannot compile

**Version info (please complete the following information):**
 - Lombok version 1.18.10
 - maven 
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>2.11.2</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.10</version>
        </dependency>

**Comment by rspilker** [comment]
That is indeed the case, not a lot we can do here. We generate a fully qualified name to the Logger factory:

```java
private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(LogExample.class);
```

In this case, the java compiler interprets `org.slf4` as accessing the `slf4j` field of the `org` field, which is not a static field, so we cannot access that field from a static context.

Workarounds:
- Rename the field
- Do not use `@Slf4j` in this code
