### ISSUE TITLE
[FEATURE] @Getter/@Setter misleading warning with @Accessors prefix

### ISSUE THREAD

**Issue by WildOrangutan** [rzwitserloot/lombok#2338]
**Describe the feature**
Look at following example:
```lang=java
@Accessors(prefix="m")
public class Test {
    @Getter
    int m1Field;
}
```
**What happens?**
`@Getter` produces a warning: `Not generating getter for this field: It does not fit your @Accessors prefix list. `

**Why it happens?**
Lombok tries to remove `m` and ends up with invalid `1Field` field (name can't start with number).

**What would I expect to happen?**
Should preferably produce an error.
Or alternatively, produce better warning message.

**Additional context**
Lombok version: 1.18.10
Android Studio:  3.5.3
Java version: 8

**Comment by rzwitserloot** [comment]
That precise code as you pasted produced a getter named 'get1Field' as expected, more or less. In lombok 1.18.10. Cannot reproduce.

**Comment by WildOrangutan** [comment]
When I delombok from terminal, the result is as you say. But when I do this inside of IDE, it doesn't generate getter. Is that annotation processor issue, or should I post this to intellij-plugin repo?

**Comment by Maaartinus** [comment]
> Is that annotation processor issue, or should I post this to intellij-plugin repo?

I'd bet you should. It works for me in both eclipse and delombok, so it must be it.

**Comment by rzwitserloot** [comment]
@WildOrangutan Oh, yeah, absolutely, I know the intellij plugin does its own processing on this one, so there's a bug there. [issue tracker for the lombok intellij plugin](https://github.com/mplushnikov/lombok-intellij-plugin/issues).

**Comment by WildOrangutan** [comment]
Ok, thanks
