### ISSUE TITLE
[FEATURE] SwallowException

### ISSUE THREAD

**Issue by amexboy** [rzwitserloot/lombok#2339]
First of all, thank  you very much for the super awesome tool I love. I tried searching for a ticket related to this, I did not find one. Maybe I missed it.

**Problem**

I have a lot of methods that wrap around an exception and log the exception and return `Optional.empty()` or `null` (Most of the time they are `void`)

```
private void somethingNotCritical() {
  try {
     // do something like sending an email
    sendEmail();
  } catch (Exception up ) {
     log.warn("Exception occurend in somethingNotCritical", up);
  }
}
```

**Suggested Solution** 

```
@SwallowException(exceptions= {IOException.class}, logLevel="warn")
private void somethingNotCritical() {
    sendEmail();
}
```

I think `values` could be bound to `exceptions`. `logLevel` could be `info` by default. 

**Problems with the solution**
There are many available solutions for the logging. My solution for this is to limit the usage of this annotation to classes with a `log` property defind (as done by `@Slf4j` and friends)

Thank you

**Comment by rzwitserloot** [comment]
In general my gut reaction to 'swallow exceptions' is that people write code that does this far too often (for example, the majority of java programmers incorrectly go out of their way to ignore any `IOException` that falls out of an inputstream/reader's `close` method). I am very hesitant, in that I would be really sad if people incorrectly think the best way to deal with exceptions they don't wanna deal with is to start tossing `@SwallowException` on everything (I'd much rather they toss `@SneakyThrows` on there!)

But, in fairness to your proposal, the scenario DOES come up.

The point is: The cost is high; not just maintenance (which is not too bad; this has a lot of overlap with `@SneakyThrows` which is already a supported feature), but mostly in footprint: By supporting the feature we tacitly somewhat approve of it, and a casual glance at the lombok featurelist might cause someone who is really looking for `@SneakyThrows`, to find this instead, and apply the wrong thing.

We have to balance that 'cost' with the 'value' in catering to this boilerplate. Which then leads to the question: How often do you want to swallow an exception? Often enough to warrant a lombok annotation to do it?

I have my doubts that this gets over the 'sufficient value compared to the cost' bar.

Any insights on this would be welcome!

**Comment by Maaartinus** [comment]
> How often do you want to swallow an exception?

The right question is "How often do you *should* swallow an exception?". And the answer is "about never". Unfortunately, (mostly due to the checked exception nonsense and partly due to ill-advised examples in books), swallowing exceptions is the most common and most deadly Java sin.

While "swallow and log" is much better and the use case of the OP is fine, I'm afraid that supporting this would lead to even more beginners spending days with code running seamlessly but doing nothing useful due to swallowed exceptions.

**Comment by rzwitserloot** [comment]
In fact, I'd go so far as to say that if you swallow-and-log it just has GOT to be wrong. There ARE use-cases: Imagine a web request handler runs into a 'client hung up' connection error. That's a classic case of just swallow-and-ignore, or, if you want to log this, then the logging really ought to be quite custom, including IPs and the precise request; none of these things would occur if you use this feature proposal with the `@Log` thing going on.

In other words, I bet anytime you think of swallowing exceptions, one of these things is going on, 50%+ of the time:

* You really shouldn't, it's jumping to the wrong solution. It'd be better to fix APIs to let you throw things, and to add proper handlers at entrypoint invokers to not blow up the world. I _really_ dislike catering to crap APIs with lombok. Feels far too much like tacit approval.
* You want to swallow, but log the event, and the proper way to log it is sufficiently customized that lombok couldn't automatically generate it. In other words, not boilerplate, and lombok really can't help you here.

The remaining 50% is probably almost universally 'I want to swallow exceptions and completely ignore them', and I think I'm being generous when I say that it's as high as 50%; I bet the above 2 'fail cases' are the (vast?) majority.

I'm going to put the kaibosh on this. Feel free to comment further if I'm missing a useful case.
