### ISSUE TITLE
[BUG] @Builder on class level does not include no args constructor

### ISSUE THREAD

**Issue by nimo23** [rzwitserloot/lombok#2343]
**Describe the bug**
Setting `@Builder` on class level with `@NoArgConstructor` and `@AllArgConstructor` will behave not correct: the no arg constructor is **NOT** called within the lombok constructed builder method. 

```
@Builder
@AllArgsConstructor
// this(); is never included in the lombok created AllArgsContructor
@NoArgConstructor
public class User{

public User(){
// some initializiation logic
}
}
```

So I have to put the builder constructor by myself and put the call of the no-arg-constructor within the builder constructor:

```
@NoArgConstructor
public class User{

public User(){
// some initializiation logic
}

@Builder
public User(String firstname, String lastname){
// must call this(); to initialize default things..
this();
...
}
}
```

Would be nice to behave like java standard: the no args constructor is always called before any other constructor.

**Comment by janrieke** [comment]
No, that is not the case. By definition, a default constructor is a no-args constructor that is automatically inserted by the compiler if no other constructor exists. Furthermore, a no-args constructor is _not_ called automatically from other constructors.

**Comment by nimo23** [comment]
yes, thats true. I will close this issue. Thanks!

**Comment by janrieke** [comment]
Unlikely, because `@Builder` is mainly used for immutable value classes, which means that you do not want a no-args constructor. Furthermore, it is not less typing that just `@NoArgsConstructor`.
