### ISSUE TITLE
[BUG] lombok.addJavaxGeneratedAnnotation option is not producing the expected annotation

### ISSUE THREAD

**Issue by ramfree17** [rzwitserloot/lombok#2345]
**Describe the bug**
Using "lombok.addJavaxGeneratedAnnotation = true " is not producing the desired effect of having generated methods have the "@lombok.Generated" annotation. The delomboked files show the annotation is "@java.annotation.Generated("lombok")" instead. This annotation is not propagated to the CLASS so post-test processors like JaCoCo are unable to exclude the generated classes and method from the coverage calculation.

**To Reproduce**
Attaching a small maven-based project. Invoking "mvn clean test" should produce the following:
  - the delomboked files in the  "delomboked" directory
  - the jacoco report in  target/site/jacoco/index.html

**Expected behavior**
All Lombok generated methods should be skipped in the JaCoCo coverage report.

**Version info (please complete the following information):**
 - Tested with lombok v1.8.10 and lombok-maven-plugin v1.8.10.0
 - javac 1.8.0_201 (Ubuntu) ,  javac  1.8.0_162 (windows 64-bit)

**Additional context**
The test cases in the attached zip file has the @Test disabled for testing purposes. If those are enabled, only the generated methods for equals, hashCode, toString, and canEqual are not covered since those were not invoked by the included tests.
[test-project.zip](https://github.com/rzwitserloot/lombok/files/4095117/test-project.zip)

**Comment by ramfree17** [comment]
Logged this as a bug report as my post in the user forum are still under moderator approval.

**Comment by Maaartinus** [comment]
@ramfree17 Aren't you confusing `addJavaxGeneratedAnnotation` with `addLombokGeneratedAnnotation`? See https://projectlombok.org/features/configuration.

**Comment by ramfree17** [comment]
@Maaartinus  :  yes I definitely am.  This is another case of PEBKAC (problem exists between keyboard and chair).  

Closing this bug report now.
