### ISSUE TITLE
[BUG] Lombok @Data not working - The annotation @Generated is disallowed for this location

### ISSUE THREAD

**Issue by shughes151** [rzwitserloot/lombok#2346]
Lombok is installed in STS, I've been using it on multiple other projects. I've imported a new project, tried Maven -> update project, tried cleaning projects.

Issue is only with the `@Data` annotation, it gives a red line underneath and shows the message "The annotation `@Generated` is disallowed for this location"

I've tried `@Getter`, `@Setter`, `@EqualsAndHashCode` and they all work fine.

Can't seem to find anyone with a similar issue and yesI have installed the plugin.

Using v1.18.10 Lombok and STS 4.5.0 release

![Screenshot_1](https://user-images.githubusercontent.com/60184215/72899808-aaad0380-3d1e-11ea-85da-0ba69961ab7d.png)

**Comment by Maaartinus** [comment]
I guess, more information will be needed.
- Can you reduce your example to a single file (or two)?
- Does the problem happen without inheritance?
- Can you add all annotations constituting [`@Data`](https://projectlombok.org/features/Data)?
- Can you reproduce it on the command line?

**Comment by rzwitserloot** [comment]
@shughes151 without a reproducible test case I'm not sure we can pick this up. Installing STS and going on a bug reproduction expedition takes rather long, and as you can see we have plenty of other concerns to get to. Without feedback this issue will be closed.

**Comment by rspilker** [comment]
Closed. No response from reporter.
