### ISSUE TITLE
[BUG] Bad return type in lambda expression

### ISSUE THREAD

**Issue by edinardo** [rzwitserloot/lombok#2353]
I am using `CompletableFuture` and when I use `exceptionally` and I try to return an object that uses `@SuperBuilder` without declaring a local variable inside, the following error is thrown at:

**Eclipse**: Type mismatch: cannot convert from CompletableFuture<capture#1-of ?> to CompletableFuture\<Person>

**javac**: incompatible types: bad return type in lambda expression
    CAP#1 cannot be converted to CAP#2
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends Parent from capture of ?
    CAP#2 extends Parent from capture of ?

Here a simplified example just to reproduce the problem:
```java
import lombok.experimental.SuperBuilder;
@SuperBuilder
public class Person {
	String name;
}
```
```java
import java.util.concurrent.CompletableFuture;
public class Example {
	public CompletableFuture<Person> fail() {
		return CompletableFuture
				.supplyAsync(() -> Person.builder().build())
				.exceptionally(t -> Person.builder().build());
	}
}
```

If I change back to `@Builder` it works as is. To work with `@SuperBuilder` I need to declare a local variable only to immediately return it.
```java
import java.util.concurrent.CompletableFuture;
public class Example {
	public CompletableFuture<Person> works() {
		return CompletableFuture
				.supplyAsync(() -> {
					Person person = Person.builder().build();
					return person;
				})
				.exceptionally(t -> Person.builder().build());
	}
}
```
Environment used:
 - Lombok version 1.18.10 (also tested with 1.18.11 snapshot)
 - Eclipse version 2019-12 (4.14.0)
 - javac version 1.8.0_191

Declare a local variable inside of `exceptionally` doesn't seem matters. Also, if `.exceptionally(t -> Parent.builder().build())` is removed from the chain, it works with `@SuperBuilder`.

**Comment by rzwitserloot** [comment]
This is a java type resolution issue and not a lombok bug. You're asking too much of java's type resolution here (the fact that SuperBuilder makes a whole bunch of generics juuuust to hack a 'self type' into java is convoluting matters considerably, but the point of SuperBuilder is that the concept (a builder that is properly chainable even in a hierarchy of types) __requires__ these generics.

So, not a java bug, not a lombok bug, but an unfortunate array of circumstance that has as end result that type resolution doesn't work in places where you might have expected that it would. Short of java introducing some new language feature (such as a self type) there is nothing lombok can do to alleviate this.
