### ISSUE TITLE
Fresh git clones might not build properly

### ISSUE THREAD

**Issue by rzwitserloot** [rzwitserloot/lombok#2363]
The problem lies in the exact dep of eclipse ecj/jdt you end up compiling against; odds are that it won't have the 'annotations' field for types (suggesting that the dep used to compile against is so old, it predates the time when annotations were allowed on types, so, java 1.8 syntax changes).

See https://groups.google.com/forum/#!topic/project-lombok/qNu0SUGxNjQ

**Comment by mehwhatever** [comment]
What is the work around for this?

**Comment by rzwitserloot** [comment]
@mehwhatever fix the issue, send a PR; not sure there's anything else to do about it.

**Comment by rzwitserloot** [comment]
To all who ran into this: You may have to run `ant distclean` in order to get back to fresh clone status (and `git pull` to pull in @rspilker 's fix of course.

**Comment by theipster** [comment]
As a newcomer looking to contribute, I can replicate the same issue with a fresh checkout of `v1.18.12`.

I can confirm the issue does _not_ occur with a fresh clone and checkout of `v1.18.10` though. (Sadly, this is the only baseline I have, as `master` is failing to build too - see #2495.)

**Comment by randakar** [comment]
Must be related to Reinier's work on rewriting the build system. No idea
what the status of that is, but that is a hard problem.
