### ISSUE TITLE
[FEATURE] Alternative semi keyword `const` working exactly like `val`

### ISSUE THREAD

**Issue by TreffnonX** [rzwitserloot/lombok#2367]
The lombok functionalities `var` and `val` are realized as stub `@interface`, to stay within java syntax. Since both types are named similar, they are easiely confused. An `@interface const` could be realized, to be used alternatively to `val`, and be handled by the same mechanism that handles `val`-replacement today. Both could even coexist, to be backwards compatible. No special configuration is neccessary, but thinkable, for someone wanting to deprecate `val` in their code base.

**Comment by rzwitserloot** [comment]
I wish we'd have thought of that. But as you say, it's a keyword. It is unlikely but plausible that it passes the syntactic validity stage and that usually means that lombok gets to run (at which point we can fix everything), but even if javac works like that (i.e. it invokes lombok before generating error statements and ending the compilation process), I think it's too finnicky to rely on it to continue to do this.

Also, if I could go back in time, _maybe_ const'd be better, but now that the val feature has been out for a few years, the cost of the change makes the cost/benefit analysis no longer work out.

I like the idea though :)
