### ISSUE TITLE
[BUG] Builder on a nested class inside an generic interface in Eclipse

### ISSUE THREAD

**Issue by juriad** [rzwitserloot/lombok#2369]
**Describe the bug**

Nested class annotated `@Builder` in an interface which has a generic parameter compiles in Eclipse only if the class is explicitly declared `static`.

**To Reproduce**

This minimal example does not work in Eclipse:
```
import lombok.Builder;
public interface TestBuilder<S> {
	@Builder
	class Nested {
	}
}
```
The error is: 
> Cannot make a static reference to the non-static type S

It works if the class is marked as `static` (which is the default modifier for classes within an interfaces).

There is no error when building the class with Gradle, so I assume it is ECJ specific.

**Version info (please complete the following information):**
 - Lombok: 1.18.12; also tried 1.18.0 and 1.16.0; the error is present in all of them
 - Platform: Freshly downloaded Eclipse (Version: 2019-12 (4.14.0); Build id: 20191212-1212)

**Comment by rzwitserloot** [comment]
It's a bug in lombok. What's more surprising to me is that it seems to work fine in javac, though. Perhaps the java parser already marks that one as static.

The fully qualified type generator needs to be updated to know that inner classes are inherently static if the enclosing type is an enum or interface (or record, I guess?)
