### ISSUE TITLE
[BUG] JDK 11 javadoc

### ISSUE THREAD

**Issue by aeiplatform** [rzwitserloot/lombok#2372]
**@AllArgsConstructor(onConstructor = @__(@JsonCreator))**
> error: cannot find symbol
> symbol: class __

**@AllArgsConstructor(onConstructor_ = @JsonCreator)**
> error: cannot find symbol
> symbol:   method onConstructor_()
> location: @interface AllArgsConstructor

**Comment by aeiplatform** [comment]
All experimental onX methods are probably affected as well.

**Comment by Maaartinus** [comment]
IIRC this is a known unsolvable (or too difficult) bug (I may be wrong). The workaround is to delombok first and generate javadoc for the delomboked sources.

**Comment by aeiplatform** [comment]
@Maaartinus Thank you, since it'll be solved by Gradle Plugin, so it isn't such a problem.

**Comment by asyschikov** [comment]
@aeiplatform what Gradle Plugin solves it? Did you manage to fix it somehow?
