### ISSUE TITLE
[FEATURE] AsFinalField

### ISSUE THREAD

**Issue by XenoAmess** [rzwitserloot/lombok#2373]
**Describe the feature**
In short, make a field can only be set once.

lombok:
```
public class LombokNewFeatureTest {
    @Setter
    @AsFinalField
    private int value;
}
```

java:
```
public class LombokNewFeatureTest {
    @Setter
    @AsFinalField
    private int value;
    private boolean _lombok_generated_ifSet_value = false;

    public void setValue(int newValue) {
        if (!_lombok_generated_ifSet_value) {
            value = newValue;
            _lombok_generated_ifSet_value = true;
        } else {
            throw new AsFinalFieldReSetException(
                    LombokNewFeatureTest.class, "value"
            );
        }
    }
}
```

**Describe the target audience**
Will be super useful when we want to create a field that shall never be reset, but we cannot let it be final because we can only get this value calculated sometime after the creation of this class.

**Comment by rzwitserloot** [comment]
Your proposed syntax needs some finessing (your way is not threadsafe, and I can foresee that people do need this guarantee to work across threads, also we cannot introduce new types at runtime, so it'd just have to be a `java.lang.IllegalStateException` or something else in java.*, but that seems like a fine exception to use here.

What about:

```java
public class LombokNewFeatureTest {
    @Setter(onlyOnce = true)
    private int value;
}
```

becomes:
```java
public class LombokNewFeatureTest {
    private int value;
    private final AtomicBoolean value$lombokIsSet = new AtomicBoolean();

    public void setValue(int value) {
        synchronized (value$lombokIsSet) {
            if (value$lombokIsSet.getAndSet()) throw new IllegalStateException("value has already been set");
            this.value = value;
        }
    }
}
```

**Comment by rzwitserloot** [comment]
I do foresee some issues; presumably if you have one of these you have more, and you'd want to know if an object is 'locked' (as in, all the set-only-once fields have in fact all been set exactly once at this point, making it effectively immutable now.)

**Comment by XenoAmess** [comment]
1.yes, grammar @Setter(onlyOnce = true) sonds acceptable.
2.I didn't consider about thread safety because this function shall be invoked only once in normal situations.
And IMO people add this Annotation, they will be careful about the property is somehow "final", and shall NEVER set them twice in there code.
And that Anntation also reminds others who try to maintain/read the codes this property is somehow "final",  thus help them understand the codes better.
But since it will be invoked only once in normal situation, it sounds also no performance harm to sync it, so yes your code solution are better.

3.
> I do foresee some issues; presumably if you have one of these you have more, and you'd want to know if an object is 'locked' (as in, all the set-only-once fields have in fact all been set exactly once at this point, making it effectively immutable now.)

I actually don't care about this. For me myself, I do not need this, the reason is stated in section 2.
But it is no harm to add such a function IMO.

**Comment by rspilker** [comment]
I also see more merits in making it an option of `@Setter`, also because we need to copy some of the annotations.

The value field also needs to become `volatile`.

One big difference with actual final field is that those can be cached/inlined after the constructor has completed. That's why I am not a fan of using the word 'final' for this.

In most cases I've observed, refactoring the code to use true final fields was a better solution.

Note: we would also have this for static variables, where it is a much more common idiom.

**Comment by rzwitserloot** [comment]
> And IMO people add this Annotation, they will be careful about the property is somehow "final", and shall NEVER set them twice in there code.

This makes no sense. If nobody would ever do this wrong, there'd be no point to this feature.
Catering to accidents is the whole point. If we're going to cater to that, we should do it for as many cases as can reasonably be covered.

Whether a feature is a good idea or not, is a cost/benefit analysis.

You may not need the 'locked' aspect, but others do. If the feature does not cater to it, the 'benefit' side goes down. And this feature is already likely not crossing the bar.

Between the performance issues and the 'locked' aspect, this feature is clearly going to end up on the wrong side; either it's too 'costly' (too complicated), or doesn't have enough 'benefit' (does not cater properly to enough use cases).
