### ISSUE TITLE
[BUG] Incorrect Documentation for lombok.noArgsConstructor.extraPrivate

### ISSUE THREAD

**Issue by urda** [rzwitserloot/lombok#2377]
**Describe the bug**

According to https://projectlombok.org/changelog one can see:

> BREAKING CHANGE: The in 1.16.22 introduced configuration key lombok.noArgsConstructor.extraPrivate is now false by default. Issue #1708

However the API documentation reports:

https://github.com/rzwitserloot/lombok/blob/7993aa20cd20cdc030f90ee9f33c1b74c023d7ca/src/core/lombok/ConfigurationKeys.java#L166-L171

that this defaults to `true`. This appears to be out-of-date and needs to be corrected.

**To Reproduce**

1. Read https://projectlombok.org/changelog and see "configuration key lombok.noArgsConstructor.extraPrivate is now false by default" as a bullet point.
2. Open https://projectlombok.org/api/lombok/ConfigurationKeys.html#NO_ARGS_CONSTRUCTOR_EXTRA_PRIVATE and see that the API docs do not agree.

**Expected behavior**

`changelog` and `API` documentation needs to agree.

**Additional Info and Related Issues**

- This config change burned my team during some upgrades, the addition of mismatched documentation and changelogs did not help either.  
- Issue #1708 helped ID the config change we needed, which lead us to the API mismatch in the docs.
- I would have cut a PR myself but do not have my GitHub keys on this machine today.

**Comment by rzwitserloot** [comment]
@urda ha, documentation always lead to funny reproduction/expected behaviour stories. I'll write that one up to humorous malicious compliance that you bothered to write something for those sections :)

I'll get right on this, easy enough to address.

**Comment by rzwitserloot** [comment]
While I was there, I now documented these keys on [constructor](https://projectlombok.org/features/constructor), [value]((https://projectlombok.org/features/value), and [data](https://projectlombok.org/features/data)'s docs.
