### ISSUE TITLE
[BUG] lombok.addNullAnnotations treats the custom annotation name in lowercase

### ISSUE THREAD

**Issue by junoyoon** [rzwitserloot/lombok#2380]
**Describe the bug**
```
lombok.addNullAnnotations=CUSTOM:javax.validation.constraints.NotNull
```
When setting addNullAnnotations like above in lombok.config, ```javax.validation.constraints.NotNull``` is evaluated as ```javax.validation.constraints.notnull``` (lower case even for annotation class name". Therefore compile error is occurred due to no class found.

**To Reproduce**
1. put following in lombok.config
```
lombok.addNullAnnotations=CUSTOM:javax.validation.constraints.NotNull
```
2. Then create following code in your project.
```
import lombok.Builder;

import javax.validation.constraints.NotNull;

@Builder
public class Test {
    @NotNull
      Integer a;
}
```
3. Then compile.. it ends up with following error message
```
Error:(7, 1) java: cannot find symbol
  symbol:   class notnull
  location: package javax.validation.constraints
```

**Expected behavior**
 javax.validation.constraints.NotNull is recognized.

**Version info (please complete the following information):**
 - Lombok version : 1.18.12
 - Platform : all platforms

**Additional context**
https://github.com/rzwitserloot/lombok/blob/master/src/core/lombok/core/configuration/NullAnnotationLibrary.java#L128-L133

It's because the nonNullAnnotation and nonNullAnnotation is extracted from  ci variable which is converted to lower case.

**Comment by rzwitserloot** [comment]
I clearly don't 'get' the validations package; how the heck would anyone want to annotate an element to state 'this MUST be null'? What I thought I did understand about it is that it is about validation and not about assertion – you can have an object where a field marked with `@Validation.NotNull` holds a `null` value and that is just fine; that merely means if you were to ask: "hey, is this object valid like this?" – the answer is 'no'. A user can submit a form which doesn't fit the rules. That's still reality - that is the proper representation of what they submitted. The point is not to throw exceptions or get wavy underlines in IDEs, the point of the annotation is to generate a human readable error message.

Which would strongly suggest making lombok generate it in such places is inappropriate. Am I misunderstanding how it works? I have no problem adding this annotation to our list of built in supported stuff, _IF_ it makes sense. I thought it didn't make sense.

Separate from that, the lower-case thing? yeah, bug. Thanks for spotting it, and the PR to fix it, I'll merge it soon :)
