### ISSUE TITLE
[BUG] @Delegate compilation issue

### ISSUE THREAD

**Issue by clembou590** [rzwitserloot/lombok#2382]
hello.
because an example is much better than a lot of words: 
here is a public repo where you can see the issue:
https://github.com/clembou590/lombokFails

two branches in this repo:
**"master" branch** works. (just type mvn clean install)
**"fails" branch** does not work (just type mvn clean install)

the 2 branches should succeed... (the only difference between the 2 branches is the use of @Delegate)

here is the error I get in the "fails" branch
Compilation failure
[ERROR]  cannot find symbol
[ERROR]   symbol:   method save(com.example.deleg.fail.Message)
[ERROR]   location: variable messageService of type com.example.deleg.fail.MessageService

for information 
1.18.12 is the lombok version that is brought in by  org.springframework.boot:spring-boot-starter-parent:2.2.5.RELEASE

**Comment by clembou590** [comment]
Hi. did anyone had some time to dig into this bug?

**Comment by Rawi01** [comment]
There seems to multiple `@Delegate` related bugs, @rzwitserloot or @rspilker mentioned somewhere that they plan to rewrite it. If they will do that soon it would be a waste of time to fix these bugs. If not I can try to fix some of these bugs.

**Comment by rzwitserloot** [comment]
@clembou590 not yet, but your efforts in making this one easy to reproduce is quite useful!

Given that the usage is so simple I assume the problem is due to the interaction between lombok and `@Autowired` - might not be feasible for us to fix this.

**Comment by Rawi01** [comment]
Based on the good example I created a smaller example without Spring to reproduce this issue:
```java
import lombok.experimental.Delegate;

public class Controller {
	@Delegate
	I1 target;

	public void call(String entity) {
		this.save(entity);
	}
}

interface I1 extends I2<String, Integer> {
}
interface I2<T, ID> extends I3<T, ID> {
}
interface I3<T, ID> {
	public T save(T a);
}
```
It compiles
- if you remove `I2`
- if you remove the generics `<T, ID>` 
- in eclipse
