### ISSUE TITLE
[BUG] Lombok @Builder not producing builder class in submodule of multi-module Gradle project

### ISSUE THREAD

**Issue by mklueh** [rzwitserloot/lombok#2389]
Describe the bug

Lombok won´t produce the builder class with the @builder annotation in the library module, but it works as expected in the application module

`Caused by: java.lang.ClassNotFoundException: com.demo.common.model.SharedModel$SharedModelBuilder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 22 more`

This is the original issue that I´ve created in Quarkus with a [Demo Project](https://github.com/mklueh/quarkus-multi-module-lombok-builder-issue) attached: https://github.com/quarkusio/quarkus/issues/7367

**Comment by rzwitserloot** [comment]
This doesn't sound like an issue with lombok; if annotation processors are not invoked there isn't a thing we can do about it; that means we don't run, at all.
