### ISSUE TITLE
[FEATURE] Add support for setterPrefix with @SuperBuilder, similar to @Builder.

### ISSUE THREAD

**Issue by ddcruver** [rzwitserloot/lombok#2394]
I am reading in you documentation that while you discourage it in @Builders I would like to see this functionality in @SuperBuilder as well.

Additionally it would be nice to have a global property for setting this value in the lombok.config configuration so it can be globally set.  I see you do not seem to have this on @Builer as well.

**Comment by janrieke** [comment]
The first part (`setterPrefix` for `@SuperBuilder`) will be in the next release (PR #2357).
