### ISSUE TITLE
[FEATURE] The enum or static property of the entity propertiy for query DB Data program in the process coding

### ISSUE THREAD

**Issue by XingChenTongTu** [rzwitserloot/lombok#2401]
**Describe the feature**
Auto add  Enum static  extra property to JAVA entity , for example: 
before:
public class People{
 private String  name;
}
after:
public class People{
public static final  enum $p {
 name;
}
 private String  name;
}
or 
public class People{
public static final Stirng name = "name"
private String  name;
}
finally:
we can get the name  of the property name instead of reflacting the People class. 
ex: findDataByName(People.$p.name)  or  findDataByName(People.name)

**Describe the target audience**
I request a enum of the JAVA entity propertiy beacuse  we often use  a entity or POJO  property name  to  query DB data , example:  findDataByName("name").  The JPA is not  perfect for us in th process of in the process of coding. We often use a class by extends a generic BaseDao or BaseService.  

**Additional context**

**Comment by janrieke** [comment]
This feature already exists: [`@FieldNameConstants`](https://projectlombok.org/features/experimental/FieldNameConstants)
