### ISSUE TITLE
[BUG] IntelliJ plugin and compiler disagree on @Builder method generation

### ISSUE THREAD

**Issue by ryanwb2** [rzwitserloot/lombok#2402]
**Description**
In IntelliJ, the compiler and plugin disagree on whether an `@Builder` method has been generated. Only seems to occur with the `setterPrefix` param.

**To Reproduce**
```java
import java.util.Optional;
import lombok.Builder;

@Builder(setterPrefix = "with")
public class Query {

  private Optional<String> name;
  private String customerId;

  public static class QueryBuilder {

    private Optional<String> name;
    private String customerId;

    private QueryBuilder() {

    }

    public QueryBuilder withName(String name) {
      this.name = Optional.of(name);
      return this;
    }

//    public QueryBuilder withName(Optional<String> name) {
//      this.name = name;
//      return this;
//    }
  }

  public static void test() {
    Query query = builder()
        .withName(Optional.of("Hello!"))
        .withCustomerId("12345")
        .build();
  }
}

```

The IDE will like this, but it won't compile. Can't find `withName(Optional<String>)`
If you uncomment the extra `withName` method, the IDE will get mad--`withName(Optional<String>)` is already defined. But it will compile.

**Expected behavior**
Expected `withName(Optional<String>)` to already be generated, and the compiler and plugin to produce the same results.

**Version info (please complete the following information):**
 - Lombok version: 1.18.12
 - Platform: IntelliJ ULTIMATE 2019.3

**Comment by janrieke** [comment]
The IntelliJ Lombok plugin at least partially for its own code generation. As the `setterPrefix` is a brand new option, it is probably not supported by the IntelliJ plugin yet.
Please report this issue at the IntelliJ Lombok plugin project.

**Comment by ryanwb2** [comment]
Sure thing.
https://github.com/mplushnikov/lombok-intellij-plugin/issues/760

**Comment by Rawi01** [comment]
This is fixed in the IntelliJ plugin
