### ISSUE TITLE
[BUG] SuperBuilder doesn't work with Eclipse

### ISSUE THREAD

**Issue by minh-thai** [rzwitserloot/lombok#2407]
**Describe the bug**
I receive this error message when trying to compile the following code in Eclipse

"Implicit super constructor ServiceUnit.Parent() is undefined for default constructor. Must define an explicit constructor"

    @SuperBuilder
    @Getter
    public class Child extends ServiceUnit.Parent {
    }

    public interface ServiceUnit {
      @SuperBuilder
      @Getter
      class Parent {
           String data;
      }
   }

**Expected behavior**
Should work without errors. I don't encounter this error when trying with IntelliJ

**Version info (please complete the following information):**
 - Lombok version: 1.18.12
 - Eclipse 2020-03 (4.15.0)
 - Java 1.8.0_201

**Comment by juriad** [comment]
Can you try adding `static` keyword to the nested class?
If it starts working, then it is the same issue as https://github.com/rzwitserloot/lombok/issues/2369

**Comment by minh-thai** [comment]
Hi @juriad , I tried as you suggested, and update maven project in Eclipse, but the error still persists

**Comment by janrieke** [comment]
Can reproduce. Interestingly, this fails both in javac and Eclipse with seemingly unrelated errors.

**Comment by janrieke** [comment]
Correction: Seems to fail in Eclipse only.

**Comment by janrieke** [comment]
PR #2409 should fix this. That never worked in the first place. It seems you found a code branch no one ever used ;)

**Comment by janrieke** [comment]
If you want a quick workaround, import the `Parent` class so you don't need the qualified reference:

    import ServiceUnit.Parent;

    @SuperBuilder
    @Getter
    public class Child extends Parent {
    }
