### ISSUE TITLE
[BUG] Lombok crashes with OpenJ9

### ISSUE THREAD

**Issue by xxDark** [rzwitserloot/lombok#2414]
**Describe the bug**
Lombok annotation processor crashes when trying to build a project with OpenJ9, version 13.

**To Reproduce**
Compile any project, and process will crash.

**Expected behavior**
Everything should work as expected

**Version info (please complete the following information):**
 - Lombok version: 1.18.12
 - javac 13.0.2
[daemon-1420.out.log](https://github.com/rzwitserloot/lombok/files/4433871/daemon-1420.out.log)
[javacore.20200405.151557.5760.0002.txt](https://github.com/rzwitserloot/lombok/files/4433872/javacore.20200405.151557.5760.0002.txt)

**Comment by xxDark** [comment]
[lombok-mre.zip](https://github.com/rzwitserloot/lombok/files/4434601/lombok-mre.zip)

**Comment by ghunteranderson** [comment]
I can reproduce consistently without Gradle. Command below:

`"C:\Program Files\Java\jdk-13.0.2+8-openj9\bin\javac.exe" -cp lombok.jar lombok-mre\src\main\java\Test.java`

It looks like a general protection fault in the OpenJ9 library `j9jit29.dll`. I'm little a fuzzy on this topic but if remember right that usually means that `j9jit29.dll` tried to access memory space it wasn't allowed to access. Windows raised a fault and the JVM couldn't recover.

This works ok when I compile with JDK 13.0.2 and without OpenJ9. I don't think there is anything the Lombok project can do to fix this. It looks like a bug in OpenJ9. I'm linking the OpenJ9 issue that is investigating this. As a workaround, I suspect you can compile without OpenJ9 and then use OpenJ9 for runtime.

https://github.com/eclipse/openj9/issues/6933

**Comment by rspilker** [comment]
Can someone confirm the fix in the [edge release](https://projectlombok.org/download-edge)?

**Comment by fengxue-IS** [comment]
confirms edge release works on my local machine
```
root@holed1:~/tmp/gpf/edge$ mvn compile
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building app 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://projectlombok.org/edge-releases/org/projectlombok/lombok/edge-SNAPSHOT/maven-metadata.xml
Downloaded: https://projectlombok.org/edge-releases/org/projectlombok/lombok/edge-SNAPSHOT/maven-metadata.xml (2 KB at 1.0 KB/sec)
Downloading: https://projectlombok.org/edge-releases/org/projectlombok/lombok/edge-SNAPSHOT/lombok-edge-20200528.222155-1.pom
Downloaded: https://projectlombok.org/edge-releases/org/projectlombok/lombok/edge-SNAPSHOT/lombok-edge-20200528.222155-1.pom (2 KB at 25.5 KB/sec)
Downloading: https://projectlombok.org/edge-releases/org/projectlombok/lombok/edge-SNAPSHOT/lombok-edge-20200528.222155-1.jar
Downloaded: https://projectlombok.org/edge-releases/org/projectlombok/lombok/edge-SNAPSHOT/lombok-edge-20200528.222155-1.jar (1790 KB at 5157.7 KB/sec)
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ app ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /root/tmp/gpf/edge/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.846 s
[INFO] Finished at: 2020-06-01T10:59:02-07:00
[INFO] Final Memory: 26M/45M
[INFO] ------------------------------------------------------------------------
```

**Comment by rspilker** [comment]
Thanks for the verification
