### ISSUE TITLE
[BUG] Lombok plugin does not work with Intellij 2020.1

### ISSUE THREAD

**Issue by bordigoni** [rzwitserloot/lombok#2417]
**Describe the bug**
I get this error on Intellij startup 
Plugin Error: Plugin "Lombok" is incompatible (until build 193.SNAPSHOT < IU-201.6668.113).

**To Reproduce**
Upgrade to the 2020.1 version (using snap -- linux)

**Expected behavior**
It should work or be updated.

**Version info (please complete the following information):**

IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.113, built on April 7, 2020
Licensed to ****************** / ************** (obfuscated)
Subscription is active until January 1, 2021
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-46-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: org.mapstruct.intellij, org.sonarlint.idea, com.jetbrains.ChooseRuntime, BashSupport, ru.adelf.idea.dotenv, com.intellij.plugins.html.instantEditing, org.intellij.scala, org.asciidoctor.intellij.asciidoc
Current Desktop: ubuntu:GNOME

Lombok version
0.29.2019.3

**Comment by BIKASHJYOTI123** [comment]
Yes same here i am facing .Not able to find the Lombok plugin in the marketplace in Intellij

**Comment by janrieke** [comment]
Please report problems for the IntelliJ plugin at the [IntelliJ lombok plugin GitHub repo](https://github.com/mplushnikov/lombok-intellij-plugin/issues).
The IntelliJ plugin is a separate project and is not maintained by the lombok core team.

**Comment by bordigoni** [comment]
@janrieke no need.
It is already done => https://github.com/mplushnikov/lombok-intellij-plugin/issues/775
Thanks.
