### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rouxiaoxiao** [rzwitserloot/lombok#2418]
**Describe the bug**
When I modify the attribute xxx of a POJO, the attribute name under the `@Query` annotation in springboot-jpa becomes getxxx, but this is not the result I want.

```java
import java.util.Set;

public interface DevicePatroluserDao extends JpaRepository<DevicePatroluserModel, Integer>
        , JpaSpecificationExecutor<DevicePatroluserModel> {

    @Query(value = "SELECT distinct(getPatrolUserName) FROM DevicePatroluserModel ")
    Set<String> findAllPatroluserName();



}
```

**Expected behavior**
When I modify the attribute xxx of a POJO, the attribute name after the `@Query` annotation in springboot-jpa is modified without adding get

**Version info (please complete the following information):**
 - Lombok version  1.18.4
 - Platform   idea 2019

**Additional context**

**Comment by janrieke** [comment]
I don't see where Lombok could possibly cause this. I suspect this is a Spring Data JPA issue. Maybe it is configured to assume fluent getters?

You can easily verify that when you replace the relevant Lombok annotations (probably mainly `@Getter`) by manually implemented methods.

**Comment by rspilker** [comment]
Please respond to the question of @janrieke

**Comment by rspilker** [comment]
Actually, since this report has no title, and the text refers to "xxx" but the example code doesn't, I'm closing this.
