### ISSUE TITLE
[BUG] two different constructors with builder should not share properties

### ISSUE THREAD

**Issue by nimo23** [rzwitserloot/lombok#2422]
**Describe the bug**
I have a class with two different constructors annotated with `@Builder`

**To Reproduce**

```
class User {

@Builder(builderMethodName = "builderTask")
public User(String firstname, String lastname, Task task){
...
}

@Builder(builderMethodName = "builderHobby")
public User(String firstname, String lastname, Hobby hobby){
...
}
```
}

**Expected behavior**
To have two different complementary builders. For example, `User.builderTask().hobby(hobby)..` should **not** be possible because `builderTask` does not provide `hobby` property. But with the above code it is possible which should not. 

The same is true also for static builder methods:

```
@Builder(builderMethodName = "builderTask")
public static User buildByTask (String firstname, String lastname, Task task){
...
}

@Builder(builderMethodName = "builderHobby")
public static User buildByHobby(String firstname, String lastname, Hobby hobby){
...
}
```

```
// should not be possible, but it is:
User.buildByHobby.task(task)..
```

**Version info (please complete the following information):**
 - Lombok version v1.18.12
 - Platform java 12, eclipse 2020-03 (4.15.0)

**Comment by nimo23** [comment]
Ok found why: we also have to define `builderClassName`. With this, it works.

**Comment by janrieke** [comment]
As I don't see a use case for generating into the same builder class for two different `@Builder` annotations, maybe Lombok should at least print a warning?

**Comment by Maaartinus** [comment]
@janrieke IIUIC it should be an error as with a shared class the build method is shared as well, i.e., the same static method or constructor get called - this is clearly broken.
