### ISSUE TITLE
[BUG] IntelliJ IDEA Plugin Error: Plugin "Lombok" is incompatible (until build 193.SNAPSHOT < IU-201.6668.121)

### ISSUE THREAD

**Issue by jkouris** [rzwitserloot/lombok#2425]
The latest lombok plugin is not compatible with IDEA2020.1

The following message is displayed when the IDE starts :
Plugin “Lombok” is incompatible (until build 193.SNAPSHOT <IU-201.6668.121).

Plugins page shows version 0.29-2019.3 with a message "Incompatible with the current IntelliJ IDEA Version

**Comment by jkouris** [comment]
Issue belongs to lombok-intellij-plugin project

**Comment by RathnamSai** [comment]
I have tried still not working lombok without install. but not displayed lombok. Any help on this.
