### ISSUE TITLE
[FEATURE]  Delegate that throws UnsupportedException for all unimplemented methods

### ISSUE THREAD

**Issue by strogiyotec** [rzwitserloot/lombok#2431]
Good day, I really like Lombok and I appreciate what you do.
I need to implement my custom **sql.DataSource** , but I'm only interested in two methods namely **getConnection()** and overloaded version of **getConnection();** other methods should throw **UnsupportedException()**
Here is the code
```
public final class SingleConnectionDataSource implements DataSource {

    @Override
    public Connection getConnection() throws SQLException {
        synchronized (this) {
            this.createConnection();
        }
        return this.connection;
    }

    @Override
    public Connection getConnection(final String username, final String password) throws SQLException {
        return this.getConnection();
    }

    @Override
    public <T> T unwrap(final Class<T> iface) throws SQLException {
        throw new UnsupportedOperationException("unwrap() is not supported");
    }

    @Override
    public boolean isWrapperFor(final Class<?> iface) throws SQLException {
        throw new UnsupportedOperationException("isWrapperFor() is not supported");
    }

    @Override
    public PrintWriter getLogWriter() throws SQLException {
        throw new UnsupportedOperationException("getLogWrite() is not supported");
    }
```
I want to replace this vanilla code with something like this
```
@Unsupported
class SingleDataSource implements DataSource{
   public Connection getConnection(){...}
}
```
So class will implement only single method and lombok will generate other methods which will throw UnsupportedException.
Is it possible to implement this feature ?

**Comment by Rawi01** [comment]
This feature is implemented in lombok-pg: [@AutoGenMethodStub](https://github.com/peichhorn/lombok-pg/wiki/@AutoGenMethodStub)

**Comment by strogiyotec** [comment]
@Rawi01 thank you, this is exactly what I am looking for

**Comment by Rawi01** [comment]
Eh, I'm not sure that lombok-pg still works, just want to mentioned that it is there already if someone wants to port it to lombok
