### ISSUE TITLE
[BUG] lombok Eclipse Installer with special chars in Path

### ISSUE THREAD

**Issue by MatthiasSchaefer** [rzwitserloot/lombok#2435]
**Describe the bug**
If the Path of to the Lombok.jar containsspecial chars, like normal brackets ( or ),  then Eclipse will not start anymore. No Error is shown, eclipse will just not open.

**To Reproduce**
Put your the lombok path to a folder which contains the special char, like `G:\Program Files\eclipse\jee-latest-released \(2020-03\)\eclipse\lombok.jar`. Run the jar and choose some Eclipse IDE to Install/Update. This will add the line `-javaagent:G:\Program Files\eclipse\jee-latest-released \(2020-03\)\eclipse\lombok.jar` to the eclipse.ini file. Eclipse is now not able to start anymore.

The Bug can be easily fixed by removing the escaping char before the bracket. So for example the \( must be replaced to (. The correct path in my example qould be `-javaagent:G:\Program Files\eclipse\jee-latest-released (2020-03)\eclipse\lombok.jar`. After changing that line in the eclipse.ini file, the Eclipse IDE is starting again and lombok is working as expected.

**Version hint**
Testet with Eclipse 2020-03 and Lombok 1.18.12

**Comment by rspilker** [comment]
I did find some more characters that don't need escaping. There might be even more, but not on my keyboard...
