### ISSUE TITLE
[FEATURE] Allow overriding the @SuperBuilder c'tor

### ISSUE THREAD

**Issue by o2-mesmer** [rzwitserloot/lombok#2442]
I appear not to be able to do the following:
```
    @SuperBuilder
    class SomeClass {
        protected SomeClass(SomeClassBuilder<?, ?> b){
            // ...
        }
    }
```
as the compiler complains that the c'tor is already defined. I assume the error comes from Lombok inserting the c'tor, even if it is already written in the source. 

This seems to be at odds with other Lombok features, such as for instance `@Builder`. It would really be nice to be able to do this. 

Granted, in order to work like the Lombok-generated c'tor, the manually-written one would have to do quite a bit of voodoo. But this seems better than the alternative, which is to de-lombok the whole class.

**Use case**
I encountered this case while trying to write a data structure with a Map field, where I wanted both to leverage the `@Singular` annotation (for easier building) *and* at the same time have a modifiable map. `@Singular` generates unmodifiable maps. If it had been `@Builder`, I could have written a c'tor taking the builder and made sure my map was mutable. With `@SuperBuilder`, I do not appear to be able to.

The problem at hand might also be solvable if there were an option to have mutable structures with `@Singular`. However, the changed proposed here seems to me both less intrusive and potentially more useful in general.

**Comment by janrieke** [comment]
Can confirm. This is simply not implemented yet, but should not be much of an effort.

However, I think your problem could be solved also right now by manually implementing the singular methods. If you don't need the immutability, it's not that complex. Furthermore, you won't create the same map three times.

**Comment by o2-mesmer** [comment]
> However, I think your problem could be solved also right now by manually implementing the singular methods.

Blimey! Hadn't thought of that. Can confirm it works. Thank you very much, @janrieke. That was... some impressive visualisation there.
