### ISSUE TITLE
[BUG] Delombok removes explicit this

### ISSUE THREAD

**Issue by mkondratek** [rzwitserloot/lombok#2444]
**Describe the bug**
Delombok removes explicit this

**To Reproduce**
Having a class with methods that contain **explicit this**, like:
`public void updateUI(@UnknownInitialization GitMacheteGraphTable this)`
delombok generates code **without** the explicit this

**Expected behavior**
Explicit this kept after delombok 

**Version info (please complete the following information):**
 - Lombok from gradle plugin`io.freefair.lombok` version `5.0.0`
- gradle version 6.3
 - Intellij 2020.1

**Additional context**
origin issue: https://github.com/freefair/gradle-plugins/issues/217

**Comment by rspilker** [comment]
Thanks for reporting this. We did recently look into this (no pun intended) when generating code to support the checker framework.

I can reproduce the problem.

**Comment by Rawi01** [comment]
@rspilker I just fixed this one and can provide a pull request if you haven't already fixed it too.

**Comment by rspilker** [comment]
It was a problem in the pretty printer. We did not print the `recvparam` field. It was introduced in [java8](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.4.1).

**Comment by rspilker** [comment]
I did fix it and added tests.

**Comment by rspilker** [comment]
@Rawi01 Thanks for the offer.

**Comment by Rawi01** [comment]
It's fascinating that we managed to fix the same issue at the same time with exactly the same changes 😂 
Btw your fix looks exactly like mine,
