### ISSUE TITLE
[BUG] missing round brackets in if conditions

### ISSUE THREAD

**Issue by mueller-jens** [rzwitserloot/lombok#2445]
Hi I am trying to use classes which use the `@EqualsAndHashCode` annotation in a project that should be transpilled to javascript using [jsweet](https://github.com/cincheo/jsweet). 
Here i can see that the equals method will be transformed incorectly.
So I took a closer look at the parsing function which shows me that the parser gives me the if conditions without round brackets if I use the annotation:

```
@EqualsAndHashCode
public class EqualsAndHashCodeExample {

	private String property;

	public String getProperty() {
		return property;
	}

	public void setProperty(String property) {
		this.property = property;
	}
	
}
```

Parser result for if conditions:

```
o == this
!(o instanceof EqualsAndHashCodeExample)
!other.canEqual((java.lang.Object)this)
this$property == null ? other$property != null : !this$property.equals(other$property)
```

if i use the generated code instead of the annotation i get the output with round brackets:
```
public class EqualsAndHashCodeExampleExplizitEquals {

	private String property;

	public String getProperty() {
		return property;
	}

	public void setProperty(String property) {
		this.property = property;
	}
	
	   @java.lang.SuppressWarnings(value = "all")
	    public boolean equals(final java.lang.Object o) {
	        if (o == this) return true;
	        if (!(o instanceof EqualsAndHashCodeExampleExplizitEquals)) return false;
	        final EqualsAndHashCodeExampleExplizitEquals other = (EqualsAndHashCodeExampleExplizitEquals)o;
	        if (!other.canEqual((java.lang.Object)this)) return false;
	        final java.lang.Object this$property = this.getProperty();
	        final java.lang.Object other$property = other.getProperty();
	        if (this$property == null ? other$property != null : !this$property.equals(other$property)) return false;
	        return true;
	    }
	    
	    @java.lang.SuppressWarnings(value = "all")
	    protected boolean canEqual(final java.lang.Object other) {
	        return other instanceof EqualsAndHashCodeExampleExplizitEquals;
	    }
	    
	    @java.lang.Override
	    @java.lang.SuppressWarnings(value = "all")
	    public int hashCode() {
	        final int PRIME = 59;
	        int result = 1;
	        final java.lang.Object $property = this.getProperty();
	        result = result * PRIME + ($property == null ? 43 : $property.hashCode());
	        return result;
	    }
}
```

Parser result for if conditions:
```
(o == this)
(!(o instanceof EqualsAndHashCodeExampleExplizitEquals))
(!other.canEqual((java.lang.Object)this))
(this$property == null ? other$property != null : !this$property.equals(other$property))
```

In my understanding both cases should give the same result.

Hope you understand my problem

**To Reproduce**
You can run my [sample project on github](https://github.com/mueller-jens/test-lombok)

**Expected behavior**

**Version info (please complete the following information):**
i use the actual lombok version
`		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.12</version>
			<scope>provided</scope>
		</dependency>`
i run it on command line using mven and can reproduce it on jdk 11 and 13 on windows also reproduceable in eclipe.

The parser looks like:
```
public class TestParser extends TreePathScanner<Void, Trees> {

	public static void main(String[] args) throws IOException, URISyntaxException {
		System.out.println("/de/muellerj/EqualsAndHashCodeExample.java");
		new TestParser().run(new File(TestParser.class.getResource("/de/muellerj/EqualsAndHashCodeExample.java").toURI()).getPath());
		System.out.println("--------------");
		System.out.println("/de/muellerj/EqualsAndHashCodeExampleExplizitEquals.java");
		new TestParser().run(new File(TestParser.class.getResource("/de/muellerj/EqualsAndHashCodeExampleExplizitEquals.java").toURI()).getPath());
		System.out.println("--------------");
	}
	
	public void run(String sourceFile) throws IOException, URISyntaxException {
		JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
		StandardJavaFileManager fileManager = compiler.getStandardFileManager(null, Locale.ENGLISH, Charset.forName("UTF-8"));
		
		ArrayList<String> sourceFileNames = new ArrayList<>();
		sourceFileNames.add(sourceFile);
		
		List<JavaFileObject>  sourceFiles = iterableToList( fileManager
				.getJavaFileObjectsFromStrings(sourceFileNames));
		JavacTask task = ((JavacTask)compiler.getTask(null, fileManager, null, null, null, sourceFiles));
		Iterable elements = task.parse(); 
		task.analyze();
		super.scan(elements, Trees.instance(task));
		
	}
	public static <T> List<T> iterableToList(Iterable<? extends T> iterable) {
		List<T> result = new ArrayList<T>();
		iterable.forEach(result::add);
		return result;
	}
	
	@Override
	public Void visitIf(IfTree ifStatement, Trees trees) {
		System.out.println(ifStatement.getCondition());
		return null;
	}
	
}
```

**Comment by randakar** [comment]
If you run this class through delombok and transpile the result, do you
still get incorrect JavaScript output?

If yes: please report this bug to jsweet.
If no: still report this to jsweet.

Unless lombok produces invalid java code, this is not a lombok issue.

**Comment by mueller-jens** [comment]
@randakar Thanks for the response. Why you think it is a problem in jsweet? As you can see in my example it is pure java no dependency to jsweet. I added tzhe story only to show you what i want to do. My example use pure java compile and th lombok depemency. 

Can you explain the different results from the java parser while using lombok annotation and the "static" code?

BTW: I added a bug report and a pull request with a solution. But for this pull request i tried to add a unit test by using pure java (no lombok dependency) and I am not able to do this. Thats why I try to verify if it is a bug in lombok or not.

I have seen there are a lot of "com.sun" classes in your projekt an I was thinking maybe this cases the problem.

Sorry if I am wrong with it.

**Comment by randakar** [comment]
First of all: not my project. I just help out a little bit by watching bug
reports.

Which parser are you referring to? Javac doesn't really produce text, so
how are you generating that output?

**Comment by mueller-jens** [comment]
I refer to the last code snipped i posted in the first comment:

```
public class TestParser extends TreePathScanner<Void, Trees> {

	public static void main(String[] args) throws IOException, URISyntaxException {
		System.out.println("/de/muellerj/EqualsAndHashCodeExample.java");
		new TestParser().run(new File(TestParser.class.getResource("/de/muellerj/EqualsAndHashCodeExample.java").toURI()).getPath());
		System.out.println("--------------");
		System.out.println("/de/muellerj/EqualsAndHashCodeExampleExplizitEquals.java");
		new TestParser().run(new File(TestParser.class.getResource("/de/muellerj/EqualsAndHashCodeExampleExplizitEquals.java").toURI()).getPath());
		System.out.println("--------------");
	}
	
	public void run(String sourceFile) throws IOException, URISyntaxException {
		JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
		StandardJavaFileManager fileManager = compiler.getStandardFileManager(null, Locale.ENGLISH, Charset.forName("UTF-8"));
		
		ArrayList<String> sourceFileNames = new ArrayList<>();
		sourceFileNames.add(sourceFile);
		
		List<JavaFileObject>  sourceFiles = iterableToList( fileManager
				.getJavaFileObjectsFromStrings(sourceFileNames));
		JavacTask task = ((JavacTask)compiler.getTask(null, fileManager, null, null, null, sourceFiles));
		Iterable elements = task.parse(); 
		task.analyze();
		super.scan(elements, Trees.instance(task));
		
	}
	public static <T> List<T> iterableToList(Iterable<? extends T> iterable) {
		List<T> result = new ArrayList<T>();
		iterable.forEach(result::add);
		return result;
	}
	
	@Override
	public Void visitIf(IfTree ifStatement, Trees trees) {
		System.out.println(ifStatement.getCondition());
		return null;
	}
	
}
```

Which is part of the [small project ](https://github.com/mueller-jens/test-lombok)I used to demonstrade the behavior.

**Comment by randakar** [comment]
Ok.

Well, so you are invoking the java compiler programmatically and then
looking at the output..

Don't know what to tell you. That code went through a full compilation
cycle and you effectively decompiled it. It is valid java, otherwise it
would not compile, so.. what exactly is the problem?

If you really want to know what lombok generates exactly, use delombok.

**Comment by Maaartinus** [comment]
> Hope you understand my problem

No way. I'm not a project maintainer (they don't comment here much, so people like me try to help), but I'm sure, it's hard to understand.

> if i use the generated code instead of the annotation

So you *remove* the (lombok?) annotation and generate some code? Really??? Or do you use delombok? Probably so, because of `final int PRIME = 59`, which is used by lombok.

So you compare what `JavaCompiler` sees when using

- direct lombok compile via maven
- and delombok and compile somehow

right? And in the analysis, once there are parentheses around the condition and once there are none. Should they be there (I guess yes as you get them from plain java and I guess no as it's just an expression)? Does it matter?

I surely agree that the results should be exactly the same, but that may not be possible at all or the cost could be too high.

**Comment by mueller-jens** [comment]
@randakar

>It is valid java, otherwise it would not compile, so.. what exactly is the problem?

I do not say that the generated code is not valid. ANd i do not think that this a problem while compiling the code. I think there is it is a problem while decompiling or analysing it.

> what exactly is the problem?
My expectation is that using the output of the visitif method in my parser get the same result if i use the lombok annotation or the hardcoded equals method.

**Comment by mueller-jens** [comment]
@Maaartinus 

>it's hard to understand.

Sorry that I am not a native english speaker. But I think iut is understandable that the output generated from both codes shuld be the same:

> So you remove the (lombok?) 
No i do not removed it. I only remove the annotation and added the equals method hardcoded. As you can see in my sample project to reproduce the issue.

>Should they be there (I guess yes as you get them from plain java and I guess no as it's just an expression)? Does it matter?

Yes ort no but the result should be the same. I guess yes. Because the hardcoded method has the parentheses.

>but that may not be possible at all or the cost could be too high.
I can't beleave it.

**Comment by mueller-jens** [comment]
@randakar If my exectation is wrong or not understandable feel free to close the issue.

**Comment by randakar** [comment]
Not a project maintainer either, so not going to.
You can do it yourself if you like though.

Thing is, what you expect to happen differing from what actually happens is
not necessarily a bug, is it?

**Comment by mueller-jens** [comment]
>not necessarily a bug 
You are right. But i can not reproduce such behaviour by using plain java so i think it is one.

I think the maintainer should decide it.

**Comment by rspilker** [comment]
I am a maintainer, and my initial thoughts were also that this is most probably a bug in the jsweet compiler. That's why we want to know what happens if you have handwritten non-lombok code without parenthesis.

```java
class Foo {
    String name = "name";
    boolean test(Foo other) {
        return  name == null ? other.name == null : name.equals(other.name)
    }
}
```

What happens if you feed this to jsweet?

**Comment by mueller-jens** [comment]
@rspilker 
it returns me valid javascript code:

```
/* Generated from Java with JSweet 2.2.0-SNAPSHOT - http://www.jsweet.org */
var Foo = (function () {
    function Foo() {
        this.name = "name";
    }
    Foo.prototype.test = function (other) {
        return this.name == null ? other.name == null : (function (o1, o2) { if (o1 && o1.equals) {
            return o1.equals(o2);
        }
        else {
            return o1 === o2;
        } })(this.name, other.name);
    };
    return Foo;
}());
Foo["__class"] = "Foo";
```

**Comment by Rawi01** [comment]
I'm not sure if this one is a lombok issue or not but I analyzed what happens and at least the generated internal structures are different. The regular java if condition gets translated to an AST like this on `JCIf -> JCParens -> JCBinary`, the EqualsAndHashCode if conditions to `JCIf -> JCBinary`. 
You can see that lombok doesn't add JCParens, thats most likely why jsweet fails to parse the the result properly. 

So I think there are two possible solutions: lombok generates the same structure than javac or jsweet learns that not every if condition is wrapped into a JCParens. Given that the `toString()` implementation of `JCIf` prints the lombok code properly I think this one have to be fixed in jsweet. I also noticed that you already created a PR (https://github.com/cincheo/jsweet/pull/581) to fix it in jsweet.

**Comment by mueller-jens** [comment]
@Rawi01 Thanks for the analysis. My faviorit solution is the first one (same structure than javac ).

>I also noticed that you already created a PR (cincheo/jsweet#581) to fix it in jsweet.
Yes that is right, because i also thought that this is a jsweet issue. But as I tried to create an unit test for that i saw that it is not possible without using lombok which @cincheo do not want to have as a dependency. Thats why i opened the bug report here. 

So is it possible that you create the same structure as javac?

**Comment by Rawi01** [comment]
Yes, in theory it is possible to create the same structure as in javac but it is a lot of work and it seems like the lombok structure is valid. The internal print methods of javac supports this (https://github.com/openjdk/jdk/blob/master/src/jdk.compiler/share/classes/com/sun/tools/javac/tree/Pretty.java#L969) so it seems to be a valid structure. I couldn't find a specification or something similar.

**Comment by mueller-jens** [comment]
Ok. Thanks then I will try to fix it in jsweet and close this issue.
