### ISSUE TITLE
[BUG] @ExperimentalMethod is over zealous in converting by converting real class/interface methods

### ISSUE THREAD

**Issue by jm98** [rzwitserloot/lombok#2446]
@ExtensionMethod is so close to MVP as just a Fluent Interface to static method transformation system

**Describe the bug**
When chaining several methods together, it is common to call a real method at the end.  Lombok appears to be attempting to convert the real method to a static call.  It should only convert calls to static methods that exist in the "extension classes"

**To Reproduce**
1  Create a static "extension" method:
public static <T> List<T> toList(Iterator<T> collection) {
  List<T> result  = new ArrayList<T>();
  collection.forEachReamaining(result::add);
  return result;
}

2  Create a static "extension" method:
public static <T> Iterator<T> method1(Iterator<T> collection) { return collection; }

3 Write a calling sequence such as:
List<String> list = new Arrays.asList({"Joe", "Fred", "John", "Mary");
list.iterator().method1().toList().forEach(System.out::println);

Compiling gives:  "Error: java:: no suitable method found for forEach(java.util.List<java.lang.String>,System.out::println)"

But the following call works:
list.iterator().method1().forEachRemaining(System.out::println);
 
**Expected behavior**
The generated source code should look like:
IteratorExtensionMethods.toList(IteratorExtensionMethods.method1(list.iterator())).forEach(System.out::println);

**Version info (please complete the following information):**
 - Lombok 1.18.12
 - Platform intelij IDEA 2020.1 Community Edition

**Additional context**

**Comment by Rawi01** [comment]
I just compiled this example using eclipse and javac without any issues. 
Seems like ExtensionMethods are not supported by the IntelliJ plugin, at least it is not listed as a feature.

**Comment by jm98** [comment]
@Rawi01 - Up to that point the extension methods were working in IntelliJ.  However, the annotation tootips were a bit "iffy" with the IDE highlighting methods as unresolved.  The code did compile and run as expected.

**Comment by Rawi01** [comment]
The lombok IntelliJ plugin now supports extension methods
