### ISSUE TITLE
[BUG] 1.18.12 Internal Compiler Error in Eclipse 2020-03 (4.15.0) JRE 1.8.0-231

### ISSUE THREAD

**Issue by jm98** [rzwitserloot/lombok#2448]
**Describe the bug**
After creating a maven project I could not get the @ExtensionMethods to work.  Every build generates Internal compiler error: java.lang.ArrayIndexOutOfBoundsException	TestSystem.java	/lomboktest/src/main/java/lomboktest	line 0	Java Problem

**To Reproduce**
[lomboktest.zip](https://github.com/rzwitserloot/lombok/files/4565205/lomboktest.zip)
contains the project
You'll need to pull the version of the JRE (1.8.0-231) for yourself

The example code is from the web page description of ExtensionMethods

**Expected behavior**
It should compile

**Version info (please complete the following information):**
 - Lombok version: 1.18.12
 - Platform Eclipse 2020-03 (4.15.0) with JRE 1.8.0-231

**Additional context**
I switched to Eclipse after issues with IntelliJ IDEA

**Comment by Rawi01** [comment]
I'm quite sure that this one is already fixed in the latest edge build (PR: https://github.com/rzwitserloot/lombok/pull/2376)

**Comment by jm98** [comment]
Reading #2376 it does talk about a maven issue.  The attached zipfile is a maven project.
If it is a maven related bug could somebody please tell me how to get a work around so that I can do a demo that is promoting the use of lombok

**Comment by Rawi01** [comment]
No one mentioned maven because it doesn't really matters in eclipse. If you run normal builds (e.g. builds after saves or `Run as -> Java Application`) eclipse uses it's own compiler (ejc). This also happens if a project uses maven. `Run as -> Maven build` invokes the real maven process and uses the compiler defined in your `pom.xml` (usually javac). 
Your error message looks like an eclipse message (ejc) and the exception is the same that is mentioned in the PR. Have you tried installing the edge build (https://projectlombok.org/download-edge)?

**Comment by jm98** [comment]
@Rawi01 any chance you could post an updated pom.xml for the project that I uploaded in the original post.  I'm struggling with getting my head around java IDEs as I've literally just started after spending 15 years in C# and Visual Studio.
I copied the resource and dependencies form the down load page into the pom but and still got the error.
I really want to get this working for a demo on how Extension Methods assist in applying Functional programming techniques within Java8

**Comment by Rawi01** [comment]
@jm98 You have to update the installed lombok version, only updating the maven mananged version is not sufficient. Just install the edge version as you did before or simply replace the `lombok.jar` in you eclipse directory or update the path to the jar in your `eclipse.ini`. Make sure to close and restart eclipse after the installation.

**Comment by jm98** [comment]
@Rawi01 thanks - now compiles in eclipse
