### ISSUE TITLE
[BUG] lombok/launch/PatchFixesHider$ValPortal

### ISSUE THREAD

**Issue by Schoaf** [rzwitserloot/lombok#2454]
**Describe the bug**
Eclipse shows an error dialog on each SonarLint run

`An internal error occurred during: "SonarLint analysis of project shop-interface (100 files processed)".
lombok/launch/PatchFixesHider$ValPortal`

**To Reproduce**
Using the latest lombok version. Using the latest SonarLint version 

**Expected behavior**

**Version info (please complete the following information):**
 - Lombok version: 1.18.12
 - Platform: Eclipse Version: 2020-03 (4.15.0) Build id: 20200313-1211
 - SonarLint:   5.1.0.17086
 - SonarServer: 6.7.7 (build 38951)

**Comment by Schoaf** [comment]
Found a similar issue but not exactly the same. Thats why I updated my lonbok version. But that didn't solve the problem:
https://github.com/rzwitserloot/lombok/issues/2351

**Comment by JohanGoosenOMF** [comment]
I've got exactly the same issue as reported above. 

Eclipse Neon Release (4.6.0), 
SonarLint 5.1, 
Lombok 1.18.12

The following post describes the same issue. Resolution was to upgrade to lombok 1.18.12 which I did, but the issue remains :
[https://community.sonarsource.com/t/internal-error-on-sonarlint-in-eclipse-with-sonarjava-6-0-1/18868](url)

**Comment by IamNGopal** [comment]
I am also having same issue 
sts-4.7.1.RELEASE
sonarlint for eclipse 5.3.0.19940
Lombok 1.18.12
Gradle 6.3

**Comment by Rawi01** [comment]
@Schoaf @IamNGopal 
Can you share a full stacktrace or some more details? It seems to work without any problems for me.

**Comment by IamNGopal** [comment]
> @Schoaf @IamNGopal
> Can you share a full stacktrace or some more details? It seems to work without any problems for me.

After multiple attempts of reloading lombok 1.18.12 I realised that may be my workspace has cached the old version of lombok. So when i created a new workspace the issue got resolved.
Thank you.

**Comment by munekumar** [comment]
After changing the workspace it worked for me as well
