### ISSUE TITLE
[BUG] @Slf4j topic cannot be references to (static) fields.

### ISSUE THREAD

**Issue by jearton** [rzwitserloot/lombok#2469]
**Describe the bug**
Error:(9, 19) java: You must use constant literals in lombok annotations; they cannot be references to (static) fields.

**To Reproduce**
![image](https://user-images.githubusercontent.com/10370433/82339527-b5537d00-9a20-11ea-8a9a-8560b18027e9.png)

compile error!

**Expected behavior**

**Version info (please complete the following information):**
 - Lombok version 1.18.0
 - Platform javac

**Additional context**

With lombok 1.16.20, this case will not compile error. It will use the constant field name to generate code. I hope this feature can be retained or optional.

**Comment by Rawi01** [comment]
This seems to be a general restriction of lombok and it might be impossible to fix it (see #1656). I haven't checked out why it is not possible but for now you have to use a string literal.

**Comment by jearton** [comment]
@Rawi01 But use lombok 1.16.20 can work.

**Comment by Rawi01** [comment]
Hmm, I think you are right. Some features actually support static references (e.g. this one) and completly disabling it seems to be a little bit to much. I will check if I can fix it.

**Comment by Rawi01** [comment]
In 1.16.20 this compiles but doesn't work properly.
Lombok translates your example into
```java
private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger("TEST");
```
instead of
```java
private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(App.TEST);
```

**Comment by jearton** [comment]
> In 1.16.20 this compiles but doesn't work properly.
> Lombok translates your example into
> 
> ```java
> private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger("TEST");
> ```
> 
> instead of
> 
> ```java
> private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(App.TEST);
> ```

Yes, "TEST" is exactly what I want, instead of "App.TEST".  This is something like  @FieldDefaults.
