### ISSUE TITLE
problem found in getter and setter

### ISSUE THREAD

**Issue by himanshujain475** [rzwitserloot/lombok#2476]
getter and setter not working for the field when the first letter is small and the second letter is capital.

**Comment by MichelMunoz** [comment]
No problem with edge version:
```
@ToString
@Getter
@Setter
class SomeClass {
    private String sOmeField;
}
```
and test code:
```
        SomeClass c = new SomeClass();
        c.setSOmeField("value");
        System.out.println(c.getSOmeField());
        System.out.println(c.toString());
```
output :
```
value
SomeClass(sOmeField=value)
```
As expected.

**Comment by Maaartinus** [comment]
@himanshujain475 Duplicate of #2149 and ten others, isn't it?

**Comment by MichelMunoz** [comment]
Ah, yes... the infamous (and ugly) "specification debt" stemming from the day someone thought it was a good idea to tweak a specification to accommodate the implementation of Introspector.decapitalize (that is arbitrary and not coherent with the more general principles of bean specification or CamelCasing).

**Comment by rzwitserloot** [comment]
Duplicate of #2693
