### ISSUE TITLE
Lombok with gradle 2.14.1 not working

### ISSUE THREAD

**Issue by pribic** [rzwitserloot/lombok#2478]
I am trying to set up lombok in our project. We have gradlew 2.14.1. 

I have added following in build.gradle

`compileOnly  group: 'org.projectlombok', name: 'lombok', version: '1.18.12'`
I am not able to add `annotationProcessor` since it was introduced in gradle 4+ version. Can someone help me with right gradle config for this?

Output of `gradlew --version`

------------------------------------------------------------
Gradle 2.14.1
------------------------------------------------------------

```
Build time:   2016-07-18 06:38:37 UTC
Revision:     d9e2113d9fb05a5caabba61798bdb8dfdca83719

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Mac OS X 10.12.6 x86_64

```

**Comment by MichelMunoz** [comment]
Accordind to old docs [Jun 30, 2017 doc](https://github.com/rzwitserloot/lombok/blob/eb928c2a3de2e6203e826b316b85f9b0fd6e735f/website/templates/setup/gradle.html)
the setup would be 
```
repositories {
	mavenCentral()
}

plugins {
    id 'net.ltgt.apt' version '0.10'
}

dependencies {
	compileOnly 'org.projectlombok:lombok:${version}'
	apt "org.projectlombok:lombok:${version}"
}

```
Check old revisions of [https://github.com/rzwitserloot/lombok/blob/master/website/templates/setup/gradle.html]() with a date matching your version.

**Comment by rspilker** [comment]
Hmm, the latest gradle version is v6.4.1.

We have no official supported gradle versions list. But if we would have, 2.x would probably not be on it.
