### ISSUE TITLE
[BUG] @Singular does not work properly with @Jacksonized

### ISSUE THREAD

**Issue by Bittuw** [rzwitserloot/lombok#2479]
**Description**
If a field will be annotated with `@Singular` and `@JsonProperty("someOtherName")` and the class also has `@Jacksonized` with `@(Super)Builder`, Jackson cannot normally deserialize this field.
Possible behaviors with `@Singular#value` and default ObjectMapper:

1. Empty value - "Unrecognized field *someOtherName*";
2. Value equals to field name - "Conflicting setter definitions for property *fieldName*";
2. Value equals to `@JsonProperty#value` - "out of START_ARRAY token" - normal behavior;

**To Reproduce**
Create any POJO annotated with `@jacksonized` and `@(Super)Builder` and field with `@Singular` and `@JsonProperty("otherName")` and try to deserialize object from string with Jackson.

 - Lombok EDGE, latest AdoptOpenJDK-14.0.1.7

**Comment by janrieke** [comment]
The current edge was built on 2020-03-15, PR #2429 (where `@Singular` support was implemented) was merged 2020-04-17. So it's not in edge, yet.

You could build from source, if you want to test it.

**Comment by Bittuw** [comment]
@janrieke, Ok, thanks. I will close this issue.

**Comment by janrieke** [comment]
It's now in the edge release. Could you verify that it works, or otherwise reopen this?

**Comment by Bittuw** [comment]
@janrieke, yes, i think everything good with `@Singular`.

**Comment by rspilker** [comment]
Thanks for the feedback
