### ISSUE TITLE
[BUG] short name for a Java object when use Camel-Case lombok can't work

### ISSUE THREAD

**Issue by Swayingleaves** [rzwitserloot/lombok#2480]
**Describe the bug**
my java object use Camel-Case to named attribute like this:

```java
@Data
public class MyObj {
    private String aUrl;
    private String userId;
}
```

my controller like this:

```java
@RestController
@Slf4j
public class TestController {
    @PostMapping("/test")
    public String getTest(@RequestBody MyObj test){
        log.info("Test:[{}]",test);
        return "ok";
    }
}
```

my request

```json
{
	"aUrl":"aaaaaa",
	"userId":"aaaaa"
}
```
so i use spring-mvc to receive it，But it can't be mapped correctly，
console print log :   Test:[Test(aUrl=null, userId=aaaaa)]
userId mapping correct
aUrl is not 
if you modify  aUrl to  agentUrl  lombok is work

**Version info:**
 > Lombok version   1.18.12
 > Java JDK 1.8.0_231   
 >  Springboot 2.3.0.RELEASE

**Comment by Maaartinus** [comment]
> if you modify aUrl to agentUrl lombok is work

... and that's the only workaround we have. There are two mutually incompatible interpretations of the javabeans crapification and Lombok implements one of them (the less common one, unfortunately). Duplicate of #927 and many others.

**Comment by Swayingleaves** [comment]
> > if you modify aUrl to agentUrl lombok is work
> 
> ... and that's the only workaround we have. There are two mutually incompatible interpretations of the javabeans crapification and Lombok implements one of them (the less common one, unfortunately). Duplicate of #927 and many others.

Thanks...
