### ISSUE TITLE
Is canEqual method really used?

### ISSUE THREAD

**Issue by anandvarkeyphilips** [rzwitserloot/lombok#2486]
**The probable bug**
I am using @EqualsAndHashCode. I would like to know when the below code gets executed in the `equals` method and returns false.
`if (!other.canEqual((Object)this)) return false;`
In you vanilla code [doc](https://projectlombok.org/features/EqualsAndHashCode) also the generated code exist.

**Expected behavior**
If that is not getting returning false ever, can it be not generated?

**Version info:**
 - Lombok version: 1.18.12
 - Platform: Java: javac 1.8.0_201

**Comment by janrieke** [comment]
See [this article](https://www.artima.com/lejava/articles/equality.html) for a discussion on that topic.

**Comment by anandvarkeyphilips** [comment]
> See [this article](https://www.artima.com/lejava/articles/equality.html) for a discussion on that topic.

Thank you.. I am going through it...

**Comment by anandvarkeyphilips** [comment]
Thank you.. This is clear from the article.
