### ISSUE TITLE
[BUG] Getter and Setter does not on Spring input requset input parameter

### ISSUE THREAD

**Issue by raychunghk** [rzwitserloot/lombok#2510]
**Describe the bug**
I am doing the sample code following the youtube tutorial from this URL:
https://www.youtube.com/watch?v=ja2IYFg-KOg&list=PLsyeobzWxl7oA8QOlMtQsRT_I7Rx2hoX4&index=10

The controller method is like this:
`	@RequestMapping("/home")
	public ModelAndView HomeController(MyAlien a) {
		// String name = (String)req.getParameter("name");
		ModelAndView mv = new ModelAndView();
		mv.addObject("alien", a);
		mv.setViewName("home");
		return mv;
	}`

and the "MyAlien" class is provided as below:
 `@Component
public class MyAlien {
	@Override
	public String toString() {
		return "MyAlien [name=" + name + ", id=" + id + ", skills=" + skills + "]";
	}

	@Getter
	@Setter
	public String name;
	@Getter
	@Setter
	public int id;
	@Getter
	@Setter
	public String skills;
}
`
 

**Expected behavior**
 The program does not put the request parameter into a lombok powered object.
**Version info (please complete the following information):**
 - Lombok version
latest as of 2020-07-05
-Java 11
**Additional context**

**Comment by Rawi01** [comment]
This seems to be a spring problem, lombok only generates the getter and setter methods, it is not responsible for mapping the request to the object. 

Disclaimer: I'm not a project owner.
