### ISSUE TITLE
[BUG] UtilityClass - inner classes are not marked as static

### ISSUE THREAD

**Issue by Robert-Ostrowski-Jagoda** [rzwitserloot/lombok#2519]
**Describe the bug**
UtilityClass annotation is not making inner classes static.
I'v checked it by reverse engineering - compiled inner classes got constructor with reference to outer class instance (it means that those classes are not static). 

**To Reproduce**
Just make TestClass with inner class (not manually marked as static) and add UtilityClass annotation to TestClass.

**Version info (please complete the following information):**
 - Lombok version 1.18.12
 - gradle, intellij, java 1.8

**Comment by Rawi01** [comment]
I cannot reproduce this issue. There are testcases for this and they pass. 

Input:
https://github.com/rzwitserloot/lombok/blob/ce92389da76b17b2c8d9f8757d67b4ea3edc8cb5/test/transform/resource/before/UtilityClass.java#L1-L12
Result after transformation:
https://github.com/rzwitserloot/lombok/blob/ce92389da76b17b2c8d9f8757d67b4ea3edc8cb5/test/transform/resource/after-delombok/UtilityClass.java#L1-L13
Can you share some more details?

Disclaimer: I'm not a project owner.

**Comment by Robert-Ostrowski-Jagoda** [comment]
@Rawi01 - that's weird, I can't reproduce it either :/
Maybe that was issue with combination of few annotations.
Closing it.
