### ISSUE TITLE
[BUG] Delombok produces duplicate @NonNull annotations on setters/getters

### ISSUE THREAD

**Issue by KartikChugh** [rzwitserloot/lombok#2520]
**Describe the bug**
Using the delombok tool produces duplicate @NonNull annotations, causing a compile error.

**To Reproduce**

1. Wrote a class annotated with @EqualsAndHashCode(callSuper = true) and @Data 
2. Wrote fields, some of which are @NonNull
3. Selected Refactor > Delombok > All annotations in IntelliJ
4. Setters and getters for @NonNull fields contain duplicate annotations

```java
    @NonNull
    public @NonNull String getName() {
        return this.name;
    }
```

```java
    public void setName(@NonNull @NonNull String name) {
        this.name = name;
    }
```

**Version info (please complete the following information):**
 - Lombok version: 1.18
 - Javac version: 1.8.0_202
- IntelliJ version: Ultimate 2019.3.3

**Comment by Rawi01** [comment]
I can not reproduce the issue using eclipse or javac, seems to be an InteliJ issue. I suggest to report this to the plugin author (https://github.com/mplushnikov/lombok-intellij-plugin/).

Disclaimer: I'm not a project owner.
