### ISSUE TITLE
[FEATURE] Allow inline customization of @NonNull "exceptionType"

### ISSUE THREAD

**Issue by EugeneDrm** [rzwitserloot/lombok#2521]
Lombok already allows configuring type of the null-check it generates by setting global property:
`lombok.nonNull.exceptionType = [NullPointerException | IllegalArgumentException | JDK | Guava | Assertion] (default: NullPointerException)`

**Feature Description**
Allow overriding this property inline by providing an optional property in annotation `@NonNull`. For example:
```java
@NonNull(exceptionType = "JDK")
```
will generate `Objects.requireNonNull(...)` code despite what is set globally.

**Goal**
In some cases, it makes sense to specify `@NonNull` annotation to improve public API, but the null-check is meaningless and it affects code coverage.

Consider `lombok.nonNull.exceptionType = NullPointerException` and the following code:
```java
class Parent {
  private final String name;
  Parent(@NonNull String name) {
    this.name = name;
  }
}

class Child extends Parent {
  Child(@NonNull String name) {
    super(name);
  }
}
```

Compiled code looks like this:
```java
class Parent {
  private final String name;
  Parent(@NonNull String name) {
    if (name == null) {
      throw new NullPointerException("name is marked non-null but is null");
    } else {
      this.name = name;
    }
  }
}

class Child extends Parent {
  Child(@NonNull String name) {
    super(name);
    if (name == null) {
      throw new NullPointerException("name is marked non-null but is null");
    }
  }
}
```

When used with code coverage tools, it is impossible to cover line `throw new NullPointerException("name is marked non-null but is null");` in class `Child`.

But a configurable `@NonNull` annotation would solve this problem.

**Additional Notes**
It is useful to have `lombok.nonNull.exceptionType = NullPointerException` because code coverage tools can catch missing tests for null arguments. If `exceptionType` is changed to `JDK`, then the above mentioned issue disappears, but this can lead to missing tests as well.

Maybe there's a more elegant way of improving this.
For example, Lombok could figure out that parent constructor already performs the same check and there's no need to generate it in the child class. Though this seems quite complicated to  implement.

**Comment by rspilker** [comment]
I understand your case. But adding this adds to the maintenance cost, and to the learning curve for new users.

Both Reinier and I don't have much understanding for 100% test coverage, especially if it concerns generated code.

Combining the arguments above, I'm going to reject this feature request.

**Comment by EugeneDrm** [comment]
Thanks for considering this feature request!

Just to clarify about the code coverage.
We definitely are not aiming for 100% just for the sake of it. But we try to cover all important scenarios. And verification of input parameters is one of those scenarios. And it's nice when tools/frameworks help us with this.

With that said, I completely understand your decision =)
