### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by anupamhaldkar** [rzwitserloot/lombok#2535]
This issue is regarding @someArgsConstructor annotation which have not developed yet . 

I have searched everywhere I can get ,but there seems to be feature coming way back 5 years ago, I have read it on contributor section of stackoverflow.

Target audience
This will be beneficial to all the programmers and coders who require not full argument initialization . These constructors are used in many aspects. this image(users project) will told that many people are looking for this feature. 

![Screenshot 2020-08-04 000745](https://user-images.githubusercontent.com/48323127/89215642-a3788380-d5e6-11ea-9d0e-356ba08db48c.png)

**Comment by randakar** [comment]
We have RequiredArgsConstructor. That should be what you need.

Is there any reason why it isn't?

**Comment by randakar** [comment]
.. or '@Builder', for that matter.

**Comment by anupamhaldkar** [comment]
I do understand that they can be achieved by @RequiredArgsConstructor but there we have to put condition as well.

**Comment by randakar** [comment]
I presume you are referring to the validation framework annotations in
there?

What exactly do you expect lombok to do for that?

Validators run on fully instantiated objects usually, there is no
constructor code we can generate for you there as far as I know.

**Comment by anupamhaldkar** [comment]
I am closing this issue as of now, you may add on later stages. 
cheers ✨🤿
