### ISSUE TITLE
Lombok stopped working randomly

### ISSUE THREAD

**Issue by MrExplode** [rzwitserloot/lombok#2540]
So I have a project I've been making since ~1,5 months, and I've been using Lombok without any problem (in Eclipse, with maven)
However today something happened and it won't build anymore. It just acts like lombok wasn't even there. 100+ compilation errors about missing methods, constructors, etc.

[Build info](https://gist.github.com/MrExplode/b186971f7c508e669a3077eecb8c4b60)

**Comment by juriad** [comment]
This is often (at least in my case) caused by: https://github.com/rzwitserloot/lombok/issues/2044 Check that everything you `static import` actually has `static` modifier.

**Comment by MrExplode** [comment]
The only static import I use is properly marked as `static`

**Comment by MrExplode** [comment]
Update: Removed all static imports, still doesn't work.

**Comment by Rawi01** [comment]
I guess there is a different error that stops the compilation before lombok runs. I skimmed through your log and noticed that this one is different:
```
[ERROR] /D:/user/PvPCore/src/main/java/me/mrexplode/pvpcore/killfarm/KillfarmDetector.java:[29,47] cannot infer type arguments for me.mrexplode.pvpcore.Tuple<>
  reason: cannot infer type-variable(s) K,V
    (actual and formal argument lists differ in length)
```

**Comment by MrExplode** [comment]
I found out that one of the dependencies used jetbrains annotations, but it wasn't included in the dependencies, causing the build to fail.
