### ISSUE TITLE
[BUG]Error when using annotation @Setter(AccessLevel.PROTECTED)

### ISSUE THREAD

**Issue by Ryan-ff** [rzwitserloot/lombok#2542]
@Setter(AccessLevel.PROTECTED) ：The protected setter method is used somewhere, the plugin cannot be rendered to the error there.But an error is reported when compiling.

**Comment by Rawi01** [comment]
Can you please share some more details or an example project? In general `@Setter(AccessLevel.PROTECTED) ` works so there might be something project specific or a configuration problem that leads to this problem.

Disclaimer: I'm not a project owner.

**Comment by Ryan-ff** [comment]
Thank you for your answer.It may be that my idea has an error, the generated set method is protected, but it still shows public when I call
