### ISSUE TITLE
[FEATURE] Plugin "Lombok" is incompatible (until build 201.SNAPSHOT < IU-202.6397.94).

### ISSUE THREAD

**Issue by shalugin** [rzwitserloot/lombok#2543]
Lombok plugin is not compatible with IDEA 2020.2

**Comment by Rawi01** [comment]
The InteliJ plugin can be found in a different repository, it seems like there already is a bug report for this issue: https://github.com/mplushnikov/lombok-intellij-plugin/issues/881

Disclaimer: I'm not a project owner.
