### ISSUE TITLE
[FEATURE] Type-safe builder

### ISSUE THREAD

**Issue by fenuks** [rzwitserloot/lombok#2546]
**Describe the feature**

I think that two main reasons for using builder is to enhance readability (especially when user wants to construct object that has few fields of same type), and when there is large object, possibly with default values (e.g. configuration classes builders), and user wants to tweak only few options.

In first case, builder does increase the readability of code, but opens possibility that field might get not initialized by accident, or after adding to class new field.

My proposition is to add possibility to generate builder which requires on type level that all fields are initialized. Below, I present an example how it could be done.

```java
@Getter
@Setter
@NoArgsConstructor
public class Point {
  private double x;
  private double y;

  public static PointBuilderX builder() {
    return new PointBuilder();
  }

  interface PointBuilderX {
    PointBuilderY x(double x);
  }

  interface PointBuilderY {
    PointBuilderBuild y(double y);
  }

  interface PointBuilderBuild {
    Point build();
  }
}
```

```java
public class PointBuilder implements PointBuilderX, PointBuilderY, PointBuilderBuild {
  private final Point object;
  public PointBuilder() {
    object = new Point();
  }

  @Override
  public PointBuilderY x(double x) {
    object.setX(x);
    return this;
  }

  @Override
  public PointBuilderBuild y(double y) {
    object.setY(y);
    return this;
  }

  @Override
  public Point build() {
    return object;
  }
}
```

Conceptually, builder implements interfaces that restrict which methods can be called on it. For example calling `Point.builder().y(1.0).build()` is not possible, since `build()` methods returns interface that only allows calling `x` method.

After calling `Point.builder()` only possibility is to call `x` method, then `y`, and then `build`. This way object will always have all fields initialized by the user. If afterwards `z` field is added, code will stop to compile.

This could be extended to default arguments. If I had `@Builder.Default` on `x` field, generated `PointBuilderX` should allow user to either call `x` or `y` method, and if latter one was called, then `x` of course should have been initialized with default value.

**Describe the target audience**
Everyone who wants to initialize all fields in the object, and have guarantee that builder invocation will always meet that requirement.

**Comment by Rawi01** [comment]
I know this one as `Step builder pattern`. 
The implementation should be quite simple, it requires no fancy additional stuff and it removes a bunch of boilerplate code so this one seems to be a good candidate for a lombok feature. The only problem is that it creates a bunch of additional interfaces and that might slow down compilation. 
One thing that should be considered is how this one gets enabled. Possible soloutions: `@Builder(required = true)`, `@StepBuilder`, `@Builder(steps = true)`, `@Builder.Steps`, ...

Disclaimer: I'm not a project owner.

**Comment by randakar** [comment]
I remember this being discussed in another bug report. It was rejected by
Reinier I believe because of class generation - lombok in general attorney
does not generate classes, outside builders - and the complexity this would
bring.

**Comment by Rawi01** [comment]
Yeah, you are right:
- Issue: https://github.com/rzwitserloot/lombok/issues/2055
- Wiki: https://github.com/rzwitserloot/lombok/wiki/FEATURE-IDEA:-%22Mandatory%22-fields-with-@Builder

**Comment by fenuks** [comment]
Thank you, somehow I missed that page on wiki. Closing the issue, then.
