### ISSUE TITLE
[BUG] ASM shading; modules collide on JDK11

### ISSUE THREAD

**Issue by geNAZt** [rzwitserloot/lombok#2549]
**Describe the bug**
When using ASM as dependency directly inside a maven project lombok and ASM collide on package org.objectweb.asm.signature.

**To Reproduce**
Have a maven project setup with ASM 8.0.1 dependency and the lombok annotation processor. Build and run the resulting result. This will lead to lombok and ASM being on the module path.

**Expected behavior**
Lombok and ASM should work together when given in the module-path. 

**Version info (please complete the following information):**
 - Lombok version: EDGE-SNAPSHOT
 - Platform: JDK 11.0.4 / Maven 3.6.3

**Comment by Rawi01** [comment]
Hi, it seems like the class is there multiple times at runtime and that leads to this error message. This is most likely a configuration problem, lombok should not be part of the packaged application at all. In maven you should use provided scope:
```xml
<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<version>1.18.12</version>
	<scope>provided</scope>
</dependency>
```
Please let us know if that solves your problem.

Disclaimer: I'm not a project owner.

**Comment by geNAZt** [comment]
I have lombok as provided dependency. Problem is that it needs to be inside the module-list or intellij will not import and mark everything red and refuse to build. But once added you need to have it as runtime module loaded or it will tell you that it can't find the lombok module.

**Comment by randakar** [comment]
Do you have the lombok plugin installed?

**Comment by geNAZt** [comment]
Yeah i have

Floris Kraak <notifications@github.com> schrieb am Do., 20. Aug. 2020,
22:06:

**Comment by rspilker** [comment]
Interesting. If you look in our jar file, you will see that although it contains a "directory" `org/objectweb/asm/signature`, there are no class files in it.

I am curious if any jar that contains a non-empty directory with that name, or even an empty directory, would trigger your build to fail.

**Comment by geNAZt** [comment]
Sorry for the late response, yes this would affect anything which has a package named org.objectweb.asm.signature (i guess a empty folder in the jar is enough to cause this)

**Comment by geNAZt** [comment]
I tried the require static and it seems to solve the problem. But i couldn't find any links in the maven documentation showing that this is needed for a Java 9+ setup, its only linked in javac setup which i guess not many use. Either way this seems to be fixed now. Thanks
