### ISSUE TITLE
Problem with Lombok 1.18.12 in Intellij

### ISSUE THREAD

**Issue by calaban52** [rzwitserloot/lombok#2550]
When I tried to use Lombok version 1.18.12 in Intellij, it complained as follows:

Failed to read artifact descriptor for org.projectlombok:lombok:jar:1.18.12

I switched to version 1.18.10 and had no problem.

**Comment by randakar** [comment]
That means that version of the lombok package is not in your maven/gradle
cache yet. Try building the project using it's proper build tool first.

**Comment by calaban52** [comment]
This is most strange. Two days ago I ran 'mvn -U clean install' and I kept
getting the same error with Lombok 1.18.12. Now today I tried it again, and
it worked fine. I do not understand why the behaviour changed, but the new
version does work now, so I guess I'm ok. Thank you for looking into this.
--
David Diamond
mailto:david.diamondca@gmail.com

**Comment by randakar** [comment]
It's a pretty common issue with maven. If it cannot download an artifact it
caches the result with a fairly long timeout - a day or two, if I recall.
Long enough that I've had to resort to manually throwing away part of the
cache results in the .m2 directory so that maven would retry the download.
