### ISSUE TITLE
Contradictory Builder documentation regarding access level of @AllArgsConstructor 

### ISSUE THREAD

**Issue by mjustin** [rzwitserloot/lombok#2554]
There is an inconsistency between the website documentation and the Javadoc documentation with regards to the access level of the generated constructor.  One claims that it is package access level; the other that it is private.

### Javadoc
https://projectlombok.org/api/lombok/Builder.html
> If a class is annotated, then a private constructor is generated with all fields as arguments (as if `@AllArgsConstructor(access = AccessLevel.PRIVATE)` is present on the class), and it is as if this constructor has been annotated with `@Builder` instead.

### Website
https://projectlombok.org/features/Builder
> Finally, applying `@Builder `to a class is as if you added `@AllArgsConstructor(access = AccessLevel.PACKAGE)` to the class and applied the `@Builder` annotation to this all-args-constructor.

## Expected behavior
The two sources of documentation should be consistent with each other, and match whatever Lombok is actually doing.

## Version info:
 - Lombok version: 1.18.12
 - Platform: N/A

**Comment by Rawi01** [comment]
This is already fixed: https://github.com/rzwitserloot/lombok/pull/2515

**Comment by mjustin** [comment]
> This is already fixed: #2515

Thanks. I did some searching before creating the issue, but I clearly missed that one.
