### ISSUE TITLE
Lombokify/Delombokify should convert/deconvert constructor calls to invoke builder

### ISSUE THREAD

**Issue by DaBlick** [rzwitserloot/lombok#2555]
**Before submitting**

I have not found a pre-existing request for this feature

**Describe the feature**

When Lombok is introduced into a project, I have found it commonplace to find places where the builder pattern should have been used but wasn't done perhaps due to someone not bother to coding the builder (or not knowing that most IDEs can generate it).

Accordingly, it would be nice if there was a way for Lombokify to take and not very-well self-documenting long constructor call like:

      new Member("david", "blickstein", null, "1600 Pennsylvania Ave",  null,  null,    3,   "", new Date(),  0, 0, 4, null, null)

And turn it into an invocation of a Lombok builder.     Or perhaps an IDE plugin.

**Comment by janrieke** [comment]
Lombok itself does not offer such refactoring operations.

When you speak of "lombokify", I think you are referring to a feature of the IntelliJ Lombok plugin. That is a separate project: mplushnikov/lombok-intellij-plugin
