### ISSUE TITLE
[FEATURE] Add the support of MyBatis Dynamic SQL

### ISSUE THREAD

**Issue by Frodez** [rzwitserloot/lombok#2568]
**Describe the feature**

https://github.com/mybatis/mybatis-dynamic-sql

There is a project, named MyBatis Dynamic SQL, for enhancing the MyBatis. And It needs an additional model defined by MyBatis Dynamic SQL for mapping sql.

For example(https://mybatis.org/mybatis-dynamic-sql/docs/quickStart.html), this table
```
create table SimpleTable (
   id int not null,
   first_name varchar(30) not null,
   last_name varchar(30) not null,
   birth_date date not null, 
   employed varchar(3) not null,
   occupation varchar(30) null,
   primary key(id)
);
```
will be mapped into the model:
```
package examples.simple;

import java.sql.JDBCType;
import java.util.Date;

import org.mybatis.dynamic.sql.SqlColumn;
import org.mybatis.dynamic.sql.SqlTable;

public final class SimpleTableDynamicSqlSupport {
    public static final SimpleTable simpleTable = new SimpleTable();
    public static final SqlColumn<Integer> id = simpleTable.id;
    public static final SqlColumn<String> firstName = simpleTable.firstName;
    public static final SqlColumn<String> lastName = simpleTable.lastName;
    public static final SqlColumn<Date> birthDate = simpleTable.birthDate;
    public static final SqlColumn<Boolean> employed = simpleTable.employed;
    public static final SqlColumn<String> occupation = simpleTable.occupation;

    public static final class SimpleTable extends SqlTable {
        public final SqlColumn<Integer> id = column("id", JDBCType.INTEGER);
        public final SqlColumn<String> firstName = column("first_name", JDBCType.VARCHAR);
        public final SqlColumn<String> lastName = column("last_name", JDBCType.VARCHAR);
        public final SqlColumn<Date> birthDate = column("birth_date", JDBCType.DATE);
        public final SqlColumn<Boolean> employed = column("employed", JDBCType.VARCHAR, "examples.simple.YesNoTypeHandler");
        public final SqlColumn<String> occupation = column("occupation", JDBCType.VARCHAR);

        public SimpleTable() {
            super("SimpleTable");
        }
    }
}
```

Another example:
https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/examples/animal/data/AnimalData.java

https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/examples/animal/data/AnimalDataDynamicSqlSupport.java

https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/examples/animal/data/AnimalDataMapper.java

https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/examples/animal/data/AnimalDataTest.java

That's a huge work for coding by the way this project supported. But the project can make the MyBatis works very well by the purposes like typesafe, expressive, flexible, extensible and small.

**Describe the target audience**
If there will exist an annotation, which can generate the XXXDynamicSqlSupport code based on the data model, that's very nice.

**Additional context**

**Comment by randakar** [comment]
There are frameworks that support annotations for defining entity mappings
out of the box already. Hibernate, especially, comes to mind. Eg.
https://www.tutorialspoint.com/hibernate/hibernate_annotations.htm

Lombok can help a little with defining classes by generating constructors,
builders and setters. But the rest of it clearly does not belong in lombok,
but in your ORM framework.
