### ISSUE TITLE
[BUG] @RequiredArgsConstructor in external jar is not preserved

### ISSUE THREAD

**Issue by tillias** [rzwitserloot/lombok#2580]
**Describe the bug**
https://stackoverflow.com/questions/63940034/lombok-requiredargsconstructor-in-external-jar-is-not-preserved

**To Reproduce**
I have a very simple project structure (2 maven modules):
 - dependency-A 
 - sprint-boot-app

In **dependency-A** I declare following class:
```
@RequiredArgsConstructor
@RestController
@Validated
@Slf4j
public abstract class ControllerBase {}
```

Now in **spring-boot-app**:
```
@RequestMapping("/api/v1")
public class ConcreteController extends ControllerBase {

    private final SomeDependency dependency
```

After this IntelliJ says that 
>Variable dependency might not been initialized

If I check decompiled version of *ControllerBase* from ***sprint-boot-app*** module:

```
@RestController
@Validated
public class ControllerBase {
    private static final Logger log = LoggerFactory.getLogger(MyController.class);

    public ControllerBase () {
    }
}

```
Is it restriction of Lombok or I should configure maven-compiler plugin somehow, so @RequiredArgsConstructor will be preserved? Please advise

If this is not possible, give us enough to reproduce the problem. If you have stack traces or error messages please include all of them, and include screen shots if that will help explain the problem.

**Version info (please complete the following information):**
 - 1.18.8
 - Java 8

**Additional context**
https://stackoverflow.com/questions/63940034/lombok-requiredargsconstructor-in-external-jar-is-not-preserved

**Comment by rspilker** [comment]
I don't understand what you mean by "preserved".

The annotation is not inherited. And the way lombok works, that's not possible.

Also, the line for the logger is a bit strange. I would have expected:
```java
    private static final Logger log = LoggerFactory.getLogger(ControllerBase.class);
```

**Comment by rspilker** [comment]
Answered on stackoverflow
