### ISSUE TITLE
[Question] Would it be possible for lombok not to use javac internal APIs, but to generate "real" code when processing annotations?

### ISSUE THREAD

**Issue by oscarfh** [rzwitserloot/lombok#2585]
It is "well known" that Lombok uses javac internal APIs.
My question is:
It is (now?) possible to generate code using annotation processors to generated code (i.e. using java poet) so the code is compiled "as-is" without the usage of internal apis. Would it be feasible to write Lombok so this is done? If yes, is it planned? Is there a reason not to do so?

**Comment by Rawi01** [comment]
Lombok actually is an annotation processor. Unfortunately it is not possible to modify an existing class using the standard api, thats why lombok uses the internal API.

**Comment by oscarfh** [comment]
Thanks a lot!
