### ISSUE TITLE
Lombok setter generates error java.lang.NoSuchMethodError after the deployment

### ISSUE THREAD

**Issue by Reshanpubudu5** [rzwitserloot/lombok#2588]
I have the following code and it generate the 
`java.lang.NoSuchMethodError: com.misyn.aia.camb.coims.common.dto.ManageReportDto.setAgencyTotals(Ljava/util/List;)V` error ONLY AFTER DEPLOYED IN THE SERVER (openSUSE Leap v15.0/ java 1.8).

I run the same jar in the local environment (Windows 10/ jave 1.8) and it works fine. 

```java
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class ManageReportDto implements Serializable {

    private String row;
    private String total;
    private List<String> agencyTotals = new ArrayList<>();
    private List<String> bancaTotals = new ArrayList<>();
    private String percentage;
    private List<String> courier = new ArrayList<>();

}
```

All other dtos with lombok annotated also works perfectly fine.

project versions is as,
* maven v3.6.3
* spring boot v2.1.6
* lombok v1.18.8

  [1]: https://i.stack.imgur.com/on99D.png

**Comment by janrieke** [comment]
As lombok is a compiletime-only dependency, there should be no runtime differences on different machines, even with differing java versions (which you do not seem to have). So I doubt that this is a lombok issue.

My guess is that there is something wrong with your classpath. For instance, you may accidently have a conflicting class `ManageReportDto` somewhere else in your classpath, causing the classloader on your deployment system to load another class file than locally.

**Comment by Reshanpubudu5** [comment]
Yes, that's not a lombok issue. 
another old dependency with ManageReportDto was there in my classpath. That has caused the problem. 
After cleaning and re-deployment,everything is working as expected. thank you @janrieke
