### ISSUE TITLE
[BUG] @SuperBuilder - wrong number of type arguments; required 3

### ISSUE THREAD

**Issue by zorner** [rzwitserloot/lombok#2589]
**Describe the bug**
Cannot use @SuperBuilder with nested Generic types.
Error: wrong number of type arguments; required 3

This is the same error as is in  bug #2359. 
The setup is a bit different, but similar. Bug #2359 has recently been fixed.
version edge-SNAPSHOT as of 09/26/2020 does not resolve the issue.

**To Reproduce**
Generic.java
```
@SuperBuilder
@Getter
public abstract class Generic<T> implements Serializable {

public abstract T getT();
}
```

NestedGeneric.java
```
@SuperBuilder
@Getter
public abstract class NestedGeneric<U extends V> extends Generic implements Serializable {

@Override
    public someClassInExtLib getT() {
        return new someClassInExtLibBuilder<U>()
                .setSomethingOfTypeU(something)
                .build();
    }
}
```

**Expected behavior**
Compile without errors.

**Version info (please complete the following information):**
 - Lombok version: edge-SNAPSHOT as of 09/26/2020
 - Platform: IntelliJ Community 2020.1.3

**Additional context**
T and U are classes with in the package. V is a class from an external lib.
Only one level of inheritance.
IntelliJ likes the above structure and errors with other variants like:
```public abstract class Generic<T, U extends V> implements Serializable {}```
or
```public abstract class NestedGeneric<U extends V> extends Generic<T> implements Serializable {}```

**Comment by janrieke** [comment]
I don't really understand your example. In your code, `T` and `U` are type parameters, not actual classes. Thus, your subclass `NestedGeneric` lacks a type argument for `Generic`. When I fix that (by using `U` or `V` as type argument), your example works in Eclipse and Maven.

So either your example is not correct, or this is solely an IntelliJ problem (which is a [different project](https://github.com/mplushnikov/lombok-intellij-plugin)).

**Comment by zorner** [comment]
Thanks for the quick response. I may have the declarations wrong. But let me give you a some more details.

Class Generic has an abstract function that returns T. Ultimately, the goal is to get a T instant back.
`
public abstract T getT();`

Class NestedGeneric extends Generic and defines getT().
```
private anotherClassInExtLib<U> something;

@Override
    public someClassInExtLib getT() {
        return new someClassInExtLibBuilder<U>()
                .setSomethingOfTypeU(something)
                .build();
    }
```

To satisfy the extLib, U must extend V with being defined in the extLib. 

I will update the info above to match.

**Comment by janrieke** [comment]
`NestedGeneric` still lacks a type argument for its `extend` class `Generic`. Using raw types with `@SuperBuilder` is not supported.

**Comment by zorner** [comment]
Thanks for the help. It looks like my decoration was incorrect. It should have been:
```
@SuperBuilder
@Getter
public abstract class NestedGeneric<T, U extends V> extends Generic<T> implements Serializable {

@Override
    public T getT() {
        return (T) new someClassInExtLibBuilder<U>()
                .setSomethingOfTypeU(something)
                .build();
    }
}
```

Above will compile, although I do not like the cast. But that is a different issue. It even looks like it will compile with Lombok 1.18.8. (The version Spring is pulling in.) I will close this issue.
