### ISSUE TITLE
[BUG] Lombok Does not work with IntelliJ EAP 2020.3 Build 203.4203.26

### ISSUE THREAD

**Issue by filiphr** [rzwitserloot/lombok#2592]
**Describe the bug**
Compiling projects with Lombok in IntelliJ 2020.3 EAP (Build 203.4203.26) leads to:

>java: You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
>  Your processor is: com.sun.proxy.$Proxy32
>  Lombok supports: OpenJDK javac, ECJ

**To Reproduce**
Any project compiled in IntelliJ is affected.

**Version info (please complete the following information):**
 - Lombok version: 1.18.12
 - IntelliJ 2020.3 EAP (Build 203.4203.26)

**Additional context**

IntelliJ is now wrapping the `ProcessingEnvironment` in a `Proxy`. This lead to a problem for us at MapStruct (https://github.com/mapstruct/mapstruct/issues/2215). While trying to fix that and testing with our examples I realized that our examples with Lombok are not compiling anymore.

For us at MapStruct it is quite easy to do this changes, don't know about you at Lombok

Thanks to @bjansen some more information about this:

https://github.com/JetBrains/intellij-community/blob/master/jps/jps-builders-6/src/org/jetbrains/jps/javac/APIWrappers.java

https://github.com/JetBrains/intellij-community/commit/d6f2625c0df5ea7b5be9bad75f5d5c6ecda452d2#commitcomment-42898346

https://youtrack.jetbrains.com/issue/IDEA-250718

Lombok related IntelliJ issue (https://youtrack.jetbrains.com/issue/IDEA-252069)

**Comment by mplushnikov** [comment]
The way you are fixing it here https://github.com/mapstruct/mapstruct/pull/2218/files @filiphr should be also possible for lombok  @rzwitserloot right?

**Comment by Rawi01** [comment]
@mplushnikov I think it requires a little bit more work because lombok needs the actual processing environment. I already downloaded InteliJ to work on a fix for this one, shouldn't be that hard.

**Comment by mplushnikov** [comment]
Great @Rawi01, thank you!

**Comment by ivascaflavius** [comment]
Hi guys, is there a workaround for this issue?

**Comment by bjansen** [comment]
Yes, add `-Djps.track.ap.dependencies=false` to the build process options. See https://youtrack.jetbrains.com/issue/IDEA-250718#focus=Comments-27-4418347.0-0

**Comment by ivascaflavius** [comment]
> Yes, add `-Djps.track.ap.dependencies=false` to the build process options. See https://youtrack.jetbrains.com/issue/IDEA-250718#focus=Comments-27-4418347.0-0

Seems to be working. Thanks!

**Comment by mplushnikov** [comment]
Hello @Rawi01, there is an issue with IntelliJ provided eclipse compiler with latest lombok version. Maybe you can help to figure out, what is going wrong here. 
See https://github.com/mplushnikov/lombok-intellij-plugin/issues/969

**Comment by liorusya** [comment]
![image](https://user-images.githubusercontent.com/33814664/122074503-f2e03080-ce01-11eb-97a7-2dd99cf4d1d2.png)
Hi. Try to go to the Settings->Plugins -> Lombok and check in checkbox

**Comment by CodaGott** [comment]
> ![image](https://user-images.githubusercontent.com/33814664/122074503-f2e03080-ce01-11eb-97a7-2dd99cf4d1d2.png)
> Hi. Try to go to the Settings->Plugins -> Lombok and check in the checkbox. for me it works

Hello!
How did it work for you because i did the same thing and it didnt work for me.
