### ISSUE TITLE
[BUG] Breaking change in 1.18.4 but only patch part of version updated

### ISSUE THREAD

**Issue by Discordia** [rzwitserloot/lombok#2601]
The last version 1.18.4 includes a breaking change: https://projectlombok.org/changelog - but only the patch version was updated. It broke our nightly builds since we have a + on the patch version. Do you not follow https://semver.org/ and can this be expected again?

**Comment by Rawi01** [comment]
One of the maintainers wrote a statement about semver [here](https://github.com/rzwitserloot/lombok/issues/2115#issuecomment-583779474), I think you can expect it to happen again.

**Comment by rspilker** [comment]
There are only two ways to correctly use semver:
- Keep the major version number at 0. According to semver, this means all versions are experimental and there are no guarantees regarding backwards compatibility.
- Always increment the major version number. There are no guarantees regarding backwards compatibility.

Even a bugfix is an observable change in behavior that potentially breaks some other person's build. Given the amount of users we have, this has happened for nearly all bugfixes in the past.

We do increment the minor version number if we expect a bigger impact. You could say we do loose semver.
