### ISSUE TITLE
[FEATURE] extend @Setter to optionally add a boolean condition

### ISSUE THREAD

**Issue by limmmm** [rzwitserloot/lombok#2611]
This can be considered as a new feature or an improvement of @Setter.

Assume that there is an annoation @ConditionSetter which can gennerate setter method of a filed with condition, such as:

```
@ConditionSetter
private String name;

@ConditionSetter
private Integer age;
```

it works as same as:

```
public void setName(boolean condition, String name) {
	if (condition) {
		this.name = name;
	}
}

public void setAge(boolean condition, Integer age) {
	if (condition) {
		this.age = age;
	}
}
```

For @Setter, only will generator setter method without condition. In many case, espacially update an table, we will do like this:

```
String name = "test"; // get from frontend
Integer age = 1; // get from frontend

if (StringUtils.isNotBlank(name)) {
	user.setName(name);
}
if (age != null && age > 0) {
	user.setAge(age);
}
```

With @ConditionSetter, those code will be simplified as:

```
String name = "test"; // get from frontend
Integer age = 1; // get from frontend

user.setName(StringUtils.isNotBlank(name), name);
user.setAge(age != null && age > 0, age);
```

Above is All.

Is there any idea that can gennerate setter method like required, with lombok or other plugins?

**Comment by rzwitserloot** [comment]
> `user.setName(StringUtils.isNotBlank(name), name);`

This seems much harder to read than:

> `if (StringUtils.isNotBlank(name)) user.setName(name);`

I assume the source of this request is misguided style guide hokey pokey, where the above would not pass linter tools and needs to be a 3 liner. As the doctor said when the patient came in and says: Doc, it hurts when I press here!

Stop doing that.

I mean it - style guides, linter tools, code quality checkers - these are tools. If you find you write this code so often you want lombok assistance, maybe they need to be revisited at your org. I would not generally multiline such an interaction, and the fact that you'd be willing to one-liner it if lombok made this method suggests that the fundamental notion of doing 'two' things (writing a condition that needs checking, and writing an expression along with a set method to send it to) on a single line if only lombok made you a single method to do it suggests that as a fundamental principle you're okay with it too. Tools need to be used, until they are no longer fit for the purpose you picked them up for, then they need to be abandoned or changed.

I know that me trying to explain to the java community that mandatory braces is overzealous is probably Old Man Yelling At Cloud levels of futile. However, even if I get past my 'geez, we are working around silly style maxims now?' hangup on this feature request, there's still two further considerable problems:

1. For human eyeballs, it's rather hard to 'parse' `.setAge(age != null && age > 0, age);` Will people immediately clue in that this code sets if the condition is true and is a no-op if not? It's not idiomatic, right? I have never seen this commonly used.
2. I find it morally objectionable to help somebody, if what they want help with, is dig their own grave. The problem with this mindset is that it's the 'silently do nothing on unexpected input' mindset. In my experience, this mindset is extremely detrimental to code quality. So, in general, if this really is idiomatic, I hate it.
