### ISSUE TITLE
[FEATURE] Create object from builder object, instead of all arg constructor

### ISSUE THREAD

**Issue by mtwig** [rzwitserloot/lombok#2613]
Description:
Provide a mechanism to have a constructor generated by `@Builder`  to accept an instance of the builder, rather than an all-args constructor.  This prevents objects from ever being created by calling constructors directly. I believe using auto generated constructors can be dangerous. Changing the order that fields are declared within a class becomes a breaking change.

Here's a sample of a POJO, and how it is delomoked today:
Before Delombok:
```java
@Builder
public class SomePojo {
  
    private final String firstName;
    private final String lastName;
    
}
```

```java
public class SomePojo {
  
    private final String firstName;
    private final String lastName;

    SomePojo(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public static SomePojoBuilder builder() {
        return new SomePojoBuilder();
    }

    public static class SomePojoBuilder {
        private String firstName;
        private String lastName;

        SomePojoBuilder() {
        }

        public SomePojoBuilder firstName(String firstName) {
            this.firstName = firstName;
            return this;
        }

        public SomePojoBuilder lastName(String lastName) {
            this.lastName = lastName;
            return this;
        }

        public SomePojo build() {
            return new SomePojo(firstName, lastName);
        }

        public String toString() {
            return "SomePojo.SomePojoBuilder(firstName=" + this.firstName + ", lastName=" + this.lastName + ")";
        }
    }
}
```

A simple refactoring which may seemingly be non-breaking, but actually be breaking:
```java
@Builder
public class SomePojo {

    private final String lastName;
    private final String firstName;
    

}
```

Now delomboked:
```java
public class SomePojo {

    private final String lastName;
    private final String firstName;

    SomePojo(String lastName, String firstName) {
        this.lastName = lastName;
        this.firstName = firstName;
    }

    public static SomePojoBuilder builder() {
        return new SomePojoBuilder();
    }


    public static class SomePojoBuilder {
        private String lastName;
        private String firstName;

        SomePojoBuilder() {
        }

        public SomePojoBuilder lastName(String lastName) {
            this.lastName = lastName;
            return this;
        }

        public SomePojoBuilder firstName(String firstName) {
            this.firstName = firstName;
            return this;
        }

        public SomePojo build() {
            return new SomePojo(lastName, firstName);
        }

        public String toString() {
            return "SomePojo.SomePojoBuilder(lastName=" + this.lastName + ", firstName=" + this.firstName + ")";
        }
    }
}
```

This isn't a problem for any code creating SomePojo with `SomePojo.builder().firstName("first").lastName("last")`, but could go undetected if any code is calling `new SomePojo("first","last")`.

I think the generated code would be safer if switched to generate a Pojo like:
```java
public class SomePojo {

    private final String lastName;
    private final String firstName;

    private SomePojo(SomePojoBuilder builder) {
        this.lastName = builder.lastName;
        this.firstName = builder.firstName;
    }

    public static SomePojoBuilder builder() {
        return new SomePojoBuilder();
    }


    public static class SomePojoBuilder {
        private String lastName;
        private String firstName;

        private SomePojoBuilder() {
        }

        public SomePojoBuilder lastName(String lastName) {
            this.lastName = lastName;
            return this;
        }

        public SomePojoBuilder firstName(String firstName) {
            this.firstName = firstName;
            return this;
        }

        public SomePojo build() {
            return new SomePojo(this);
        }

        public String toString() {
            return "SomePojo.SomePojoBuilder(lastName=" + this.lastName + ", firstName=" + this.firstName + ")";
        }
    }
}
```

This would be a potentially breaking change. This may be a candidate for a lombok config flag.

**Comment by michaelboyles** [comment]
> but could go undetected if any code is calling new SomePojo("first","last")

Then make the constructor private

```
@Builder
@AllArgsConstructor(access = AccessLevel.PRIVATE)
```

**Comment by rzwitserloot** [comment]
Lombok already accomplishes the stated goal ('prevent all ways of constructing the object except via the builder') by making that all args constructor `private`. We can debate if this strategy is a better way to accomplish the goal than the one lombok has chosen, but at this point your feature request gets the considerable additional burden of being so much better that it warrants a sizable backwards compatibility break, which it stands no chance in hades of getting over.

Perhaps your intent is instead that even code within the same source file needs to forced into going via the builder. Yup, your solution would accomplish this, whereas lombok's current impl doesn't do that. But I don't think that's worthy enough to complicate matters by making e.g. a setting or a parameter on the builder.

Note that `@SuperBuilder` works exactly like this. I don't advise using features just because by total coincidence their implementation details currently lines up with what you need, but, stick a `@SuperBuilder` on there and you'll get this, I think.
