### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by evanbross** [rzwitserloot/lombok#2618]
**Describe the bug**
@Builder results in name shadowing

**To Reproduce**
Using eclipse set name shadowing to be Error instead of Warning or Info.
The @Builder will get a red flag

**Expected behavior**
There shouldn't be any name shadowing happening.

**Version info (please complete the following information):**
 - 1.18.16
 - Java 14
 - Eclipse 2020-09

**Additional context**

**Comment by rspilker** [comment]
The solution: don't set it to Error. We do add @SuppressWarnings, but we cannot suppress Errors.

The errors are the result of an inner type having the same field names as the enclosing type.

But since the inner type is static, Eclipse is in our opinion wrong about the shadowing.

**Comment by rspilker** [comment]
Additional comment: Eclipse already has a relaxed setting where the parameters of constructors or setters are allowed to be the same as the fields, where that _IS_ actual shadowing. 

I think that the Builder patterns, `@With` and `@WithBy` would benefit from the same treatment.

Also, I wouldn't mind if we could somehow tell Eclipse what code is generated, and have different treatment inside generated code.
