### ISSUE TITLE
Create a reference field for POJO

### ISSUE THREAD

**Issue by romantictravel01** [rzwitserloot/lombok#2619]
I have a POJO. I create a VO to reference the field in POJO. If the field of POJO changes, the field in VO will also change. I think this is particularly useful and important. I hope to get your reply

**Comment by Rawi01** [comment]
This sounds like a feature request but I have no idea what you want to achieve. Can you provide an example before/after code snippet and some more context?

**Comment by romantictravel01** [comment]
for example
**entity:**
@Data
public class UserEntity {
    private Long id;
    private String username;
    private Integer sex;
    private Integer age;
}
**vo**
public class UserVo {
    @Refrence(UserEntity::getusername)
    private Object field1;
   @Refrence(UserEntity::getSex)
   private Object field2;
   @Refrence(UserEntity.getAge)
    private Object field3;
}  

After compiling, uservo becomes

public class UserVo {
   
    private String  username;

   private Integer  sex;
 
    private Integer  age;
} 

If I change the field in userentity, userentity:: getxx can follow the change

**Comment by romantictravel01** [comment]
In short, VO refers to the field of entity. If the entity field is modified or deleted, the VO will also be modified and deleted. This will be a great change to the writing of POJO dto VO, which is very meaningful

**Comment by rspilker** [comment]
I'm pretty certain that this could be achieved using a regular annotation processor or model generator.

Lombok is good at generating code inside existing files. But if a whole file is generated, you should use a different tool.
