### ISSUE TITLE
[BUG] Lombok Eclipse plugin breaking my workspace

### ISSUE THREAD

**Issue by krebznet** [rzwitserloot/lombok#2622]
**Describe the bug**
I have installed the latest version of Lombok eclipse plugin to eclipse dsl 2020-03 and in my workspace i have a mix of maven jar, spring boot and eclipse plugins and in all instances when I create a new workspace i eventually get to the point where I cannot open a java editor with this error 

lombok/launch/PatchFixesHider$Transform
Errors running builder 'Java Builder' on project 'dunkware-xxxxx'.
lombok/launch/PatchFixesHider$Transform

**To Reproduce**
Create a workspace with various types of projects that include maven and eclipse plugins and work in the workspace, this error does not show up at first. 

**Expected behavior**
Be able to open up java editors without this build error message popping up. 

**Version info (please complete the following information):**
 - latest
 - Eclipse DSl 2020-03

**Comment by rspilker** [comment]
What version of lombok are you using? 1.18.14 is known broken. That's why you should use 1.18.16. See the [changelog](https://projectlombok.org/changelog).
