### ISSUE TITLE
[BUG] Regression: #2006 breaks Delegate in Tycho

### ISSUE THREAD

**Issue by rgra** [rzwitserloot/lombok#2633]
**Describe the bug**
Inclusion of the new method PatchDelegate.getChildren(IJavaElement[], SourceTypeElementInfo) from #2006 and according implementation with imports from org.eclipse.jdt.internal.core break compatibility with Tycho (which uses ECJ, didn't test with plain ECJ) because the packages are not available there. 
Loading from lombok.eclipse.agent.PatchDelegatePortal.Reflection throws ClassNotFoundExceptions (with -Dlombok.debug.reflection=true).
Thus @Delegate doesn't work at all with the latest Lombok on Tycho.

**To Reproduce**
Reproduction would need my changes for Tycho, but should be reproducable with ECJ only as well.

**Expected behavior**
Delegates should be working on Tycho/ECJ as well.

**Version info (please complete the following information):**
 - 1.18.16
 - Tycho/ECJ >=1.5.0

**Additional context**
@Rawi01 I think it should work if you can put the additions to a new class and load it seperately in PatchDelegatePortal.

Wouldn't it be good to show the Exceptions when Delegate is actually used. Swallowing makes sense when it's not used, but in this case it took me a long time to figure out what was wrong because I didn't see the exception without the lombok.debug.reflection switch.

**Comment by Rawi01** [comment]
@rgra I think the `getChildren` method was added in #2551. I can reproduce the problem using a modified version of `test/ecj/SampleTest.java`. There clearly is a class loading issue but I don't get why it tries to load `org/eclipse/jdt/internal/core/JavaElement`.

**Comment by rgra** [comment]
@Rawi01 lombok.eclipse.agent.PatchDelegateDelegateSourceMethod.forMethodDeclaration(JavaElement, MethodDeclaration)
is using JavaElement so it get's loaded on class load.

**Comment by Rawi01** [comment]
@rgra It clearly tries to use classes that are not there in ECJ and adding a check or a second class as you did in your PR should help here. 
My problem was that I expected that it would fail at the actual method invocation as I expected lazy class loading as usual. Some further investigation showed that it does not fail loading `PatchDelegate`, it fails at the `getMethod` call. Lesson learned: Getting the methods of a class using reflection triggers class loading of all classes used as return type or method parameter.

**Comment by rzwitserloot** [comment]
@rgra Just checking, because I never quite got the tycho build to work - does the current lombok release ([v1.18.20 from April 2nd, 2021](https://projectlombok.org/download)) address this issue?
