### ISSUE TITLE
[FEATURE] @Of

### ISSUE THREAD

**Issue by david-g-williams** [rzwitserloot/lombok#2642]
It would be great to have an `@Of` annotation that combines private final fields and required args constructor into a singe static helper method `of` similar to the `List.of( ... )`, signature.

It is common to do this:

     @FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true) 
     @RequiredArgsConstructor 

But instead of this:

    @RequiredArgsConstructor(onConstructor_ = {@Inject})
 
`@Of` would generate a static constructor called `of`, that includes Lombok `@NonNull` annotation on all parameters.

    public static MyObject of(@NonNull final TypeA typeA, @NonNull final TypeB typeB) {
        return new MyObject(typeA, typeB);
    }

**Comment by andreoss** [comment]
For a single class you can have ` @RequiredArgsConstructor(staticMethod = "of")`.
But note that, in your example  `List` is an interface and to have a proper set of overloaded `of` methods on it you have to know its implementors 
Something like
```
@Of(MyFoo.class, YourFoo.class)
public interface Foo { 
     static Foo of(X abc) { return new MyFoo(abc); } 
     static Foo of(Y xyz) { return new YourFoo(xyz); }
 }
```

**Comment by rzwitserloot** [comment]
@david-g-williams What does NonNull have to do with it? Lombok should absolutely not be making stuff up out of whole cloth - if the field `TypA typeA` is annotated with a non-null marker, then lombok will silently copy it for you. And if not, it won't, and it shouldn't. Thus, this sounds like all you want is a combination of `@RequiredArgsConstructor` and the private/final field defaults.

It sounds like you should be using `@Value`. I don't see why this is so incredibly common, it warrants a boilerplate buster for the boilerplate buster.
