### ISSUE TITLE
[BUG] lombok.config files aren't read in when compiling with sbt 1.4

### ISSUE THREAD

**Issue by rzwitserloot** [rzwitserloot/lombok#2645]
**Describe the bug**
Since about sbt 1.4, there's an incremental compilation thing happening with sbt which is causing the `sourcefile` field of javac's CompilationUnits to report a virtualized URI, which lombok cannot turn into a file path, thus causing lombok to just give up on trying to find the directory to start the chain of looking for `lombok.config` files.

**To Reproduce**
Compile 'Hello, World!' in a java file with sbt while you have a `lombok.config` file present; lombok will completely ignore that config file.

**Additional context**
The URI reported by sbt is something like `vf://tmp/$%7BBASE%7D/src/main/java/example/Main.java`

See also [Pull Request 2643](https://github.com/rzwitserloot/lombok/pull/2643)

**Comment by raphaelNguyen** [comment]
Thanks for fixing this up. Can I ask if there is a release scheduled that would contain this change some time soon?

**Comment by mkurz** [comment]
@rzwitserloot You [fix](https://github.com/rzwitserloot/lombok/commit/e1f82ac4d132769cfc272dccfc916aeba7181718) for this issues is not complete: We ran into problems when using sbt subprojects. I provide a patch here: #2668 Please have a look (and merge :wink) before the next release, thanks!

**Comment by domdorn** [comment]
Any estimate when a new release will be published? This is currently blocking me from upgrading sbt 1.3.12 to 1.4.5. Thanks!

**Comment by rzwitserloot** [comment]
@domdorn are you looking for an edge release or lombok v1.18.18?

**Comment by mkurz** [comment]
The edge release does not yet contain my fix for sbt subprojects (#2668). But it does work already for projects where Lombok is NOT used in a sub-project.

**Comment by mkurz** [comment]
@rzwitserloot Would be nice if you could update the edge release to latest master :wink:

**Comment by rzwitserloot** [comment]
Tonight probably.
