### ISSUE TITLE
[FEATURE] @Builder option to save builder values to existing entity

### ISSUE THREAD

**Issue by alexanderzuban** [rzwitserloot/lombok#2649]
**Problem**
Extend  @Builder to transfer initialized fields to existing entities. This may be useful when the builder is used to collect "new values", so it can just transfer them to the existing object; 

**Sample***
 
```
@Builder(saveTo=true) // it needs to verify that class also has at least @Setter annotation
@Setter
public class Entity{
  private String field1;
  private String field2;
}

```

Which will generate
 
```
...
@java.lang.SuppressWarnings("all")
public Entity saveTo(Entity entity) {			 
	if (this.field1$set) entity.setField1(field1$value);
	if (this.field2$set) entity.setField2(field2$value);
	return entity;
}
...
```

**Comment by rzwitserloot** [comment]
Fun idea, but it feels like this is taking the already colossal utility space that Builder already covers between toBuilder, singular, and superbuilder, and stretching it so far it would burst. I've been working on making the builder handlers more maintainable and I'm happier with where it's at now than last year, but it's still too complex to try to add this stuff.

Maybe one day, but I don't want to give out false hope, so, for now, I'm closing it; features which have basically no chance to make it within ~2 years are better closed, I think.
