### ISSUE TITLE
[BUG] `ant dist` is broken

### ISSUE THREAD

**Issue by mressler** [rzwitserloot/lombok#2653]
**Describe the bug**
`ant dist` results in BUILD FAILED:

```
Compile errors: 
----------
1. ERROR in /.../lombok/src/utils/lombok/permit/Permit.java (at line 41)
import lombok.Lombok;
       ^^^^^^^^^^^^^
The import lombok.Lombok cannot be resolved
```

**To Reproduce**
Check out any commit after 3aace094f336393330ed275e1fb6d6c1f9187e14
```
Author: Reinier Zwitserloot <...>
Date:   Fri Nov 13 04:37:27 2020 +0100

    [refactor] reflection code streamlined by sending it through the Permit class
```

**Expected behavior**
`ant dist` should result in BUILD SUCCESS.

**Version info (please complete the following information):**
 - master branch.
 - Platform javac 11.0.9/ant via command line or Eclipse.

**Additional context**
I posted this to the forum, but thought I'd create an issue here too. Not sure which gets more attention. Very new to Lombok, so I don't know how you'd like to fix this or I'd submit a PR too.

**Comment by Rawi01** [comment]
Can confirm this, there is a reference from `src/utils` to `src/core` which fails during a full rebuild. It works if you just recompile an already compiled version.

**Comment by Rawi01** [comment]
@mressler This was fixed a few hours ago
