### ISSUE TITLE
 [BUG] @Getter(lazy = true) does not generate code according to docs

### ISSUE THREAD

**Issue by gbloggs** [rzwitserloot/lombok#2661]
**Describe the bug**
Using Intellij and the lombok  plugin version 203.5981.41, when I delombok to see what code is generated I do not get the AtomicReference the [lombok GetterLazy docs][1] suggest:

```
    @Getter(lazy=true)
    private final double[] cached = expensive();

    private double[] expensive() {
        double[] result = new double[1000000];
        for (int i = 0; i < result.length; i++) {
            result[i] = Math.asin(i);
        }
        return result;
    }
```

Generates this in Intellij:

```
    private final double[] cached = expensive();

    private double[] expensive() {
        double[] result = new double[1000000];
        for (int i = 0; i < result.length; i++) {
            result[i] = Math.asin(i);
        }
        return result;
    }
```

Not this as the docs suggest:
```
private final java.util.concurrent.AtomicReference<java.lang.Object> cached = new java.util.concurrent.AtomicReference<java.lang.Object>();
  
  public double[] getCached() {
    java.lang.Object value = this.cached.get();
    if (value == null) {
      synchronized(this.cached) {
        value = this.cached.get();
        if (value == null) {
          final double[] actualValue = expensive();
          value = actualValue == null ? this.cached : actualValue;
          this.cached.set(value);
        }
      }
    }
    return (double[])(value == this.cached ? null : value);
  }
  
  private double[] expensive() {
    double[] result = new double[1000000];
    for (int i = 0; i < result.length; i++) {
      result[i] = Math.asin(i);
    }
    return result;
  }
```

Clearly, this is not lazy and so is of limited use, is this a change in how lombok works for lazy getters, or is this a bug in how Delombok works in Intellij?

Furthermore, I have the gradle lombok plugin v 5.3.0 and have run the task ```gradlew clean delombok```. This also generates the same code as shown in the Intellij delombok, so this appears to be a change in how lazy getters are generated?

  [1]: https://projectlombok.org/features/GetterLazy

**To Reproduce**
Delombok the code as shown on the  [lombok GetterLazy docs][1] page and copied above in the description, either using the latest Intellij lombok plugin or the latest gradle lombok plugin.

**Expected behavior**
Expected a lazy local AtomicReference. The generated code does not lazy instantiate the variable.

**Version info (please complete the following information):**
 - Lombok version. 1.18.16. 
 - Gradle plugin. 5.3.0
 - Intellij plugin. 203.5981.41
 - Platform.
java 11.0.8 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)

IntelliJ IDEA 2020.3 Beta (Ultimate Edition)
Build #IU-203.5981.41, built on November 19, 2020
IntelliJ IDEA EAP User
Runtime version: 11.0.9+11-b1145.15 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: compiler.automake.allow.when.app.running=true
Non-Bundled Plugins: org.intellij.plugins.hcl, CheckStyle-IDEA, Dart, Pythonid

Gradle 6.7.1
**Additional context**

**Comment by Rawi01** [comment]
There are [multiple test cases](https://github.com/search?q=repo%3Arzwitserloot%2Flombok+path%3Atest%2Ftransform%2Fresource%2Fafter-delombok+filename%3AGetterLazy*&type=Code&ref=advsearch&l=&l=) and all of them use `AtomicReference`. Most likely this is an IntelliJ problem.

**Comment by rzwitserloot** [comment]
> Furthermore, I have the gradle lombok plugin v 5.3.0 and have run the task gradlew clean delombok

That's bizarre. As Rawi01 said, this sounds like an intellij problem, except for this fragment in your report. Can you reproduce this in a way that does not involve either gradle or intellij whatsoever? Just command line `javac` and/or command line `ecj` and/or eclipse? If you can't, can you reproduce it with just command line files and gradlew, running on the command line?

Or is this only a thing on intellij. WHich would be bizarre, because the point of the intellij plugin is that it just makes intellij know which methods exist, that's all, as intellij ought to be compiling with javac, thus getting the benefit of the full lombok at that point. Hence why I'm confused as to what you're looking at and how you get there.

**Comment by gbloggs** [comment]
I'll take a look at the maven plugin next. If that shows the same result, I'll drop to javac

**Comment by gbloggs** [comment]
I set up a test project for maven, following: http://anthonywhitford.com/lombok.maven/lombok-maven-plugin/usage.html.
`      
    <plugin>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok-maven-plugin</artifactId>
        <version>1.18.16.0</version>
        <executions>
          <execution>
            <phase>generate-sources</phase>
            <goals>
              <goal>delombok</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
`
with a class copied from the docs has created this in the generated source

`
package lombok.test;

import lombok.Getter;

public class GetterLazyExample {
  @Getter(lazy=true) private final double[] cached = expensive();

  private double[] expensive() {
    double[] result = new double[1000000];
    for (int i = 0; i < result.length; i++) {
      result[i] = Math.asin(i);
    }
    return result;
  }
}
`

`
// Generated by delombok at Mon Dec 07 18:17:06 GMT 2020
package lombok.test;

public class GetterLazyExample {
  private final java.util.concurrent.atomic.AtomicReference<java.lang.Object> cached = new java.util.concurrent.atomic.AtomicReference<java.lang.Object>();

  private double[] expensive() {
    double[] result = new double[1000000];
    for (int i = 0; i < result.length; i++) {
      result[i] = Math.asin(i);
    }
    return result;
  }

  @java.lang.SuppressWarnings({"all", "unchecked"})
  @lombok.Generated
  public double[] getCached() {
    java.lang.Object value = this.cached.get();
    if (value == null) {
      synchronized (this.cached) {
        value = this.cached.get();
        if (value == null) {
          final double[] actualValue = expensive();
          value = actualValue == null ? this.cached : actualValue;
          this.cached.set(value);
        }
      }
    }
    return (double[]) (value == this.cached ? null : value);
  }
}
`

I tried using Intellij again to delombok this maven project as it got it wrong again. So it seems (at least) the IntelliJ plugin has this issue. 

The Javacode created by the tmaven plugin looks as expected.

**Comment by gbloggs** [comment]
(I would also add that I learnt something too. Fearing the double checked locking generated I looked up double checked locking on an AtomicReference and discovered it to be safe -- yet another quality genertaed bit of code from an elegant and simple annotation. You really do need to be commended for the work you do on lombok)

**Comment by gbloggs** [comment]
I revisted the gradle plugin. Create a cnew project, and copied the code above. I can now confirm that the gradle lombok plugin generates this from a clean install:

package com.theverygroup.fs.identitymanagement.statuschange.common.model;

    public class GetterLazyExample {
        private final java.util.concurrent.atomic.AtomicReference<Object> cached = new      java.util.concurrent.atomic.AtomicReference<Object>();

        private double[] expensive() {
            double[] result = new double[1000000];
            for (int i = 0; i < result.length; i++) {
                result[i] = Math.asin(i);
            }
            return result;
        }
    
        public double[] getCached() {
            Object value = this.cached.get();
            if (value == null) {
                synchronized (this.cached) {
                    value = this.cached.get();
                    if (value == null) {
                        final double[] actualValue = expensive();
                        value = actualValue == null ? this.cached : actualValue;
                        this.cached.set(value);
                    }
                }
            }
            return (double[]) (value == this.cached ? null : value);
        }
    }


So I now believe the issue is with the delombok in intellij as Intellij generates this wrong regardless of the fact its a gradle or maven project.

**Comment by rzwitserloot** [comment]
Awesome work, @gbloggs!

If you want, the issue tracker for the intellij plugin is in a separate project, you can find it [here](https://github.com/mplushnikov/lombok-intellij-plugin/issues?q=is%3Aissue++lazy).
