### ISSUE TITLE
Add support for behavior from the previous version for FieldNameConstants 

### ISSUE THREAD

**Issue by kkhmelevskoy** [rzwitserloot/lombok#2664]
Add support for behavior from the previous version, when constant generated in main class with prefix. 
For example support innerTypeName ="" with prefix = "NAME_".

For example 
@FieldNameConstants(innerTypeName ="", prefix = "NAME_")
public class FieldNameConstantsExample {
   private final String myField; 
}

Vanilla
public class FieldNameConstantsExample {
   public static final String NAME_MY_FIELD = "myField";
   private final String myField; 
}

**Comment by rzwitserloot** [comment]
Not worth the increase in maintenance burden and documentation. We changed it for a reason.
