### ISSUE TITLE
属性定义成 cGradeId 这种形式 @requestBody接收不到参数

### ISSUE THREAD

**Issue by jiangzongqi11** [rzwitserloot/lombok#2666]
private String cGradeId;
 
	//这是lombok生成的 就是@Data  这种 @requestBody 接收不到值
	
    public void setCGradeId(final String cGradeId) {
        this.cGradeId = cGradeId;
    }
	public String getCGradeId() {
        return this.cGradeId;
    }
	
	
	//这是自己生成的  这种就没有问题
	  public String getcGradeId() {
        return cGradeId;
    }

    public void setcGradeId(String cGradeId) {
        this.cGradeId = cGradeId;
    }

**Comment by Rawi01** [comment]
Duplicate of #1861 and several others

**Comment by rzwitserloot** [comment]
Duplicate of #1861
