### ISSUE TITLE
[FEATURE] EqualsAndHashCode improvements: equals in cached hashcode, alternative "instanceof" checking

### ISSUE THREAD

**Issue by dyorgio** [rzwitserloot/lombok#2678]
**Describe the feature**
Include options or adjustments for it:
1) Equals and canEquals are using **instanceof** to check argument type, when you extends a class in JPA it is not ok, because different entities with same super class return true if EqualsAndHashCode is used only on super class.
2) When using cached hashCode give the option to use it on equals too. in some situations it can improve performance.

### With Lombok
```java
@EqualsAndHashCode(cacheStrategy = LAZY_EQUALS, instanceOfStrategy = IS_INSTANCE)
public class Foo {
    private HeavyHashCodeObject heavy;
}
```

### Vanila Java
```java
public final class Foo {
    private transient int $hashCodeCache = 0;

    private final HeavyHashCodeObject heavy;

    public Foo(HeavyHashCodeObject heavy) {
        this.heavy = heavy;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!getClass().isInstance(o)) return false;
        return hashCode() == o.hashCode();
    }

    @Override
    public int hashCode() {
        if ($hashCodeCache != 0) return $hashCodeCache;

        int result = 0;
        result = 31 * result + Objects.hashCode(heavy);

        $hashCodeCache = result;
        return result;
    }
}
```

**Describe the target audience**
For equals in cached hashcode all programmers that wants and can do that to improve performance.
For alternative instanceof checking JPA programmers that use super classes to code more OO.

**Comment by rzwitserloot** [comment]
> instanceOfStrategy = IS_INSTANCE

This is a fine way to end up with `@EqualsAndHashCode` having 50+ annoparams. We held entire talks about this, we can't give in to that kind of feature creep. Nobody* is going to use this. `instanceOfStrategy` is also a bad name (it presumes a strategy), but even a good name isn't going to help here.

The mechanism to solve this problem is to override `canEqual`.

cached hashcodes is already something @rspilker recently introduced. Check the edge release.

> `return hashCode() == o.hashCode();`

This is invalid. equal hashcode does not imply equality. pigeonhole principle: What you want (for hashcode to be unique) is impossible; it demands perfect hashing __and__ a view of the object universe where only at most 4 billion different objects can possibly exist, and for the vast majority of class defs out there, that is literally mathematically impossible. I don't get to do it often, but I have conclusively proven a feature request to be impossible :P

**Comment by janrieke** [comment]
But what you _could_ do is check the opposite: If the hashcodes differ, you can immediately return false. If the hashcode computation is heavy, it's likely that `equals` will also be, which could lead to a significant boost in the unequal case.
But such an early-return check should only be performed if both hashcodes are already cached. That means 3 more comparisons in the equal case...

**Comment by dyorgio** [comment]
Hi @rzwitserloot, I opened this issue only to open the discussion about theses ideas. It is not a PR. Code and names are just here to clarify.
Note that proposition about custom strategy for instanceof is very usefull for JPA + inheritance, it is a game changer. Maybe a better name could be strictType=[true/false], but again, I really like to see more people talking, given opinion about it, to later start a PR.

I agree with you that hashcode in equals can be dangerous, but not that it IS, programmers sometimes know what they are doing right?
Otherwise @janrieke give us a good idea, I agree that it is very safe for inequality, and could save cpu (if hashcode is heavy, normally equals is heavy too).

You are right about increment field count in this particular annotation, maybe caching needed to be implemented in a new type: @CachedEqualsAndHashCode. Just an idea ok?

**Comment by dyorgio** [comment]
Just to include a real world/production example about "strictType"....
After 2 years using **EqualsAndHashCode** in my JPA super class I made a test:
```java
EntityA a  = new EntityA(1); // Constructor that accepts PK.
EntityB b  =  new EntityB(1);
Assert.assertFalse("Different entities cannot be equal", a.equals(b));
```
Impact: EhCache default second level cache a lot of collisions (~40 entities in default cache that id is generated for a different sequence starting by 1).

So, today I'm adjust all to include **EqualsAndHashCode**, I boilerplate of a boilerplate killer :nerd_face:.

**Comment by RamAnvesh** [comment]
Any thoughts on checking the opposite?
If hashcode is different, then return false in equals().
This doesn't involve any feature/configuration creep as well.
