### ISSUE TITLE
[BUG] org.springframework.lang.NonNull is handled differently from lombok.NonNull

### ISSUE THREAD

**Issue by silh** [rzwitserloot/lombok#2683]
**Describe the bug**
When annotation `@org.springframework.lang.NonNull` is used on a constructor or a method parameter null check is not generated. When `@lombok.NonNull` is used in the same place null check is generated properly.
Interestingly if `@org.springframework.lang.NonNull` is used on the field and `@RequiredArgsConstructor` is used on the class then constructor contains a proper null check.

**To Reproduce**
You can find sample classes and tests for them [here](https://github.com/silh/lombok-nonnull-example).
To execute tests run `./gradlew check`.
Classes for comparison are `org.silh.lombokexample.lomboknonnullexample.SpringNonNull`, `org.silh.lombokexample.lomboknonnullexample.SpringNonNullWithRequiredArgsConstructor`, `org.silh.lombokexample.lomboknonnullexample.LombokNonNull`
The test for problematic case `doesntThrowAnExceptionButShould` fails.

**Expected behavior**
Same handling for both annotations.

**Version info (please complete the following information):**
 - Lombok version - 1.18.16
 - Platform (javac or eclipse, and if so, what is the output of `javac -version` / the version listed in the _about..._ dialog of eclipse. - javac 11.0.9.1
 ```
 silh:lombok-nonnull-example/ (master✗) $ ./gradlew -version                                                                                                                                                                       [21:42:09]

------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.9.1 (AdoptOpenJDK 11.0.9.1+1)
OS:           Mac OS X 10.15.7 x86_64
```

**Additional context**
Project also contains property `lombok.addNullAnnotations=spring` in lombok.config but it works the same way with or without it.

**Comment by rzwitserloot** [comment]
The behaviour you're observing is in fact the desired behaviour. Only `lombok.NonNull` causes nullcheck injection. I can see adding a lombok.config option to make other annotations also inject this nullcheck. There are a few reasons for it, but one big one is that a bunch of frameworks will treat e.g. `@NonNull String x` not so much as a compiler-checked suggestion but more as a type modifier, and will thus in fact __warn__ on lombok's nullcheck, saying: Hey, that is pointless; after all, you just said 'x' cannot possibly be `null` so why are you checking for it?

**Comment by silh** [comment]
Thank you, I've misunderstood documentation a bit.
