### ISSUE TITLE
[FEATURE] Add (Shallow-)CopyConstructor

### ISSUE THREAD

**Issue by flaxel** [rzwitserloot/lombok#2686]
**Describe the feature**
There are different annotations for the constructors. It would also be helpful if there is an annotation like `@(Shallow)IdentityConstructor` or `@(Shallow)CopyConstructor` for the same class so that you can easily create a shallow copy. 

New Lombok Code: 

```java
@CopyConstructor
public class Test {

    private int a;
    private int b;
}
```

Java Code:

```java
public class Test {

    private int a;
    private int b;

    public Test(Test other){
        this.a = other.a;
        this.b = other.b;
    }
}
```

**Describe the target audience**
This feature would help those who often create (shallow) copies of objects or do not need to tediously pass the individual values when creating a new instance.

**Comment by janrieke** [comment]
You can do that already using `@Builder(toBuildet

**Comment by Rawi01** [comment]
There was a similar feature request (#2474) some time ago and it was closed because it seems to be quite hard to do it right if parent classes are present.

**Comment by flaxel** [comment]
> You can do that already using `@[Super]Builder(toBuilder=true)`. Is there something you cannot achieve with that?

Perfect! This is exactly what I was looking for. Thank you!

> There was a similar feature request (#2474) some time ago and it was closed because it seems to be quite hard to do it right if parent classes are present.

Yes, that is correct. But that was also about the discussion of DeepCopies. But ShallowCopies should be possible? 

--- 

If the distinction between shallow and deep copies is not to be made, which I can understand, the Issue can be closed. There is a good work around for shallow copies.
