### ISSUE TITLE
[BUG] SuperBuilder not compatible with lombok.addNullAnnotations = checkerframework

### ISSUE THREAD

**Issue by mattiasgronlund** [rzwitserloot/lombok#2689]
Code generated when using both lombok.addNullAnnotations = checkerframework and @SuperBuilder does not compile, as the return type for the builder() methods have lost the generic arguments <?, ?>.

E.g.
NullAnnotatedCheckerFrameworkSuperBuilder.ZChild.@org.checkerframework.checker.nullness.qual.NonNull ZChildBuilder builder() {
instead of:
NullAnnotatedCheckerFrameworkSuperBuilder.ZChild.@org.checkerframework.checker.nullness.qual.NonNull ZChildBuilder\<?, ?\> builder() {

**To Reproduce**
See pull request.

**Expected behavior**
See pull request.

**Version info (please complete the following information):**
 - Lombok version latest...
 - Platform Ubuntu 18.04 with javac 11.

**Comment by rzwitserloot** [comment]
Fixed via @mattiasgronlund 's PR.

**Comment by fbastien** [comment]
I think this was not compatible with `lombok.addNullAnnotations = eclipse` either as I experienced compilation errors on `@SuperBuilder` methods as well after upgrading to Lombok 1.18.16 if I enabled such config. Upgrading to version 1.18.18 (in which this fix was released) solved my issue.
