### ISSUE TITLE
Feature request [internal]: Universally fix up the Javac.storeEnd table

### ISSUE THREAD

**Issue by rzwitserloot** [rzwitserloot/lombok#2691]
Lombok appears to not always properly add generated nodes to Javac's `storeEnd` table. This doesn't do much (positions of generated nodes are perpetually in a state of limbo, as so many tools make assumptions that do not hold, such as that no 2 exclusive nodes can share a start position, or that nodes have non-zero length), but it should help a little bit sometimes. It is hard to know what the impact is (it'll impact compiler plugins of all stripes, most likely) for example:

* Linters like errorprone (see issue #2605)
* source navigation tools (I can foresee language server-based editor setups such as vi+a java plugin to be affected by this)
* code coverage tools like jacoco
* Editors in general (such as netbeans, see Pull Request #471)
* Other lombok-like APs, though I'm not aware of any
* No doubt I'm forgetting other tools that end up reading that table one way or another

I'm pretty sure it's worth doing this update and then deal with issues as they are raised if doing this causes other tooling to do bizarre things. Most likely it causes other tools to shift from exceptions to undesired reporting on generated code, but we can then start filing requests with those libraries to add facilities for ignoring generated code, and add documentation to the site to explain how to set it up (if we can't convince the project maintainers of things like errorprone to recognize lombok itself and bake into their code that lombok means: generated, so, skip).

**Comment by Rawi01** [comment]
If you haven't started with this yet, I would work on this one. Most likely this will be a pretty huge refctoring as every handler that generates something new has to be updated.

**Comment by rzwitserloot** [comment]
You got the green light from me, I haven't started on this at all, nor has @rspilker
