### ISSUE TITLE
Netbeans and 1.18.16 not working properly

### ISSUE THREAD

**Issue by thordw** [rzwitserloot/lombok#2698]
**Describe the bug**

Upgraded to 1.18.16 and now a class cannot be found by Netbeans if class is not in same package.

For example **se.kgm.test.handler.TestHandler** cannot locate **se.kgm.test.TestObject**.
But to other way around works.

I can manually import the package and it works, however when I import the project into another project it cannot find it.

After downgrading to lombok version 1.18.12 the error disappears.

**To Reproduce**

Create a Maven project in Netbeans (tried in 8.2, 12.0 & 12.2)
Add lombok as a dependency 

`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>se.kgm.test</groupId>
    <artifactId>test-lombok</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>
    
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.16</version>
        </dependency>
    </dependencies>
    
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
    
</project>
`
Create new Class in

`package se.kgm.test

import lombok.Data;

@Data
public class TestObject {

    private int id;

}`

Create another Class in another package **se.kgm.test.package**.

`
package se.kgm.test.newpackage;

import se.kgm.test.TestObject;

public class TestObjectHandler {

    TestObject test;

}
`
Remove import to TestObject, have NetBeans search for import. In 1.18.16 import cannot be  found but 1.18.12 works.

**Expected behavior**

Expects same behaivor as version 1.18.12 (or lower). 

**Version info **
 - Lombok version 1.18.16 (no issue in 1.18.12)
 - Platform Netbeans (8.2, 12, 12.2), Java 8, Windows 10

**Comment by Rawi01** [comment]
Can you try if the latest edge version works? There are some known issues with 1.18.16 and Netbeans that are already fixed.

**Comment by thordw** [comment]
Hi

Edge version works fine. 
Not sure if it's an issue but version 1.18.16 is default version when using SpringBoot as of 2.3.5.RELEASE.

It was because of that we noticed this.

**Comment by rzwitserloot** [comment]
@thordw I think they update their lombok deps pretty frequently. The fix for this isn't in the latest stable release yet. We'll try to do some release planning this thursday.

**Comment by thordw** [comment]
@rzwitserloot Thanks for the info and for the help.
