### ISSUE TITLE
[FEATURE] enable to set if log is static or not per class

### ISSUE THREAD

**Issue by rmannibucau** [rzwitserloot/lombok#2703]
**Describe the feature**
in lombok.config you can select if @Log/@Slf4j/... define a static log field or not.
Would be neat to have it in the annotation to be able to mix it (default being config one).

**Comment by laconicmonk** [comment]
Non static loggers are almost never a good idea.

**Comment by rmannibucau** [comment]
@laconicmonk static loggers are often an anti-pattern too (and from what I saw most of the time). In 75% of the java backend applications (spring, ee, etc) until it is not in a singleton (which is the general case), in most application being graal-ified it is also a trouble. The "only use static logger" recommendation looks very outdated today and based on wrong facts. That said lombok already enables to choose, it just prevents to choose per class which is what this ticket is about.

**Comment by rspilker** [comment]
Did you know that you can have multiple [`lombok.config`](https://projectlombok.org/features/configuration) files, which allows you to already use different settings for different sections of you code-base?

Although you cannot change it per java file or even per class in a java file, we've never seen a real use-case where that's a common thing.

We do see that some projects use different settings for some packages. The servlets use a different configuration than the database classes. Typically, those project organized their codebase in a way that using a different `lombok.config` for part of their code is a good solution.

Currently, I don't think that adding this capability does not contribute enough to warrant the extra maintenance burden.
