### ISSUE TITLE
[BUG] lombok.val make a problem when using delombok

### ISSUE THREAD

**Issue by DVKunion** [rzwitserloot/lombok#2705]
**Describe the bug**
when i use lombok.val and delombok to build the project,delombok rollback the code with `final java.lang.Object` that missed function in my class.

**To Reproduce**
when i use lombok.val :
`val consumer = new ConsumerImplV2(.........)`
and  i use the function setAutoFinish which is declare in class Consumer
`consumer.setAutoFinish(....)`
then use delombok,the code changed like this:
`final java.lang.Object consumer = new ConsumerImplV2()`
 java.lang.Object has no function like setAutoFinish,so it throw an error and get compile false :
java.lang.Object cannot be converted to Consumer

also this code must import lombok.Setter; if only import lombok.val; delombok will not change the code , i don't no why occur this.

**Expected behavior**
val will change like this
`final ConsumerImplV2 consumer = new ConsumerImplV2()`
or delombok can provide a param that user can choose to skip rollback lombok.val (only Setter/Getter)

**Version info (please complete the following information):**
 - lombok v1.18.16
 - jdk 1.8
 - maven 3.6.3

**Comment by rspilker** [comment]
Can you post a more complete example to demonstrate the problem?

**Comment by DVKunion** [comment]
I was already resolve this problem.  When the code build with Maven, using `java -jar lombok.jar delombok src -d src-delomboked` to delombok the project may not find some class(I don't know why this occurd) .So in a Maven project , delomboking your source code by using lombok-maven-plugins (https://github.com/awhitford/lombok.maven) is an effevtive way ~.
Also, i would appreciate it if somebody can  tell me why a maven project can not use `java -jar lombok.jar delombok src -d src-delomboked`  to delombok a project.
