### ISSUE TITLE
[BUG] @Valid not compatible with @Delegate

### ISSUE THREAD

**Issue by drognisep** [rzwitserloot/lombok#2715]
**Describe the bug**
There seems to be some sort of incompatibility between `javax.validation.Valid` and `@Delegate`. The delegate annotation is working great, but when the `@Valid` annotation is added a compile error is reported.

`error: @Delegate can only use concrete class types, not wildcards, arrays, type variables, or primitives.`

**To Reproduce**
1. Create a couple simple DTOs
2. Embed one in the other with `@Delegate`
3. Add `@javax.validation.Valid` to the delegated field.

**Expected behavior**
No compile time errors.

**Version info (please complete the following information):**
 - Lombok version 1.8.4
 - Javac version 1.8.0_74

**Additional Details**
Running a delombok on the code resolves the error, and `@Valid` is able to be placed on the field without a compile error.

**Comment by Rawi01** [comment]
Can you try if this is fixed in a newer lombok version? There was a similar bug (#1935) that is already fixed.

**Comment by rspilker** [comment]
Instead of describing how to create code to reproduce the problem, it really helps a lot if you include the source code of the smallest program that would demonstrate the problem.

**Comment by drognisep** [comment]
> Can you try if this is fixed in a newer lombok version? There was a similar bug (#1935) that is already fixed.

This resolved it. Thank you!
