### ISSUE TITLE
[FEATURE] @With - add boolean attribute control clone vs. mutation

### ISSUE THREAD

**Issue by JeffAtDeere** [rzwitserloot/lombok#2717]
I want to use `@With` Lombok on my JPA entities and can't have them making new instances of themselves. Therefore, I propose adding a boolean attribute to `@With` that controls if a new object is returned or the current instance is mutated. 

Per [@With documentation](https://projectlombok.org/features/With) Lombok generates the method
```
  public WithExample withName(String name) {
    return this.name == name ? this : new WithExample(name, age);
  }
```

whereas `@With(clone=false)` would generate
```
  public WithExample withName(String name) {
    this.name = name;
    return this;
  }
```

The default of the new attribute should be the current behavior so that this is 100% backwards compatible.

**Comment by Rawi01** [comment]
You can archive something similar (with different method names) using [@Accessor](https://projectlombok.org/features/experimental/Accessors). I think that the idea of `@With` is to create setters for immutable objects, at least that is what the documentation says.

**Comment by rspilker** [comment]
We use the `with` prefix for immutables. What you want is a `setter` in combination with chaining accessors.
