### ISSUE TITLE
Commit 8be4b0ffe6b5e5f89e8bb3d94e87d0aa98dc5aeb breaks @Builder delombok [BUG] 

### ISSUE THREAD

**Issue by md-5** [rzwitserloot/lombok#2724]
**Describe the bug**

The aforementioned commit, 8be4b0ffe6b5e5f89e8bb3d94e87d0aa98dc5aeb, breaks delombok of builder annotations containing an AccessLevel, eg `@Builder(access = AccessLevel.PRIVATE)` combined with a getter: `@Getter private final String string;`.

**To Reproduce**
Delombok a file containing an annotation of the above form. For example:
```import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;

@Builder(access = AccessLevel.PRIVATE)
public final class ItemTag
{

    @Getter
    private final String string;
}
```

**Expected behavior**
Delombok succeeds.  Instead delombok fails with the messages:
```
error: cannot find symbol
@Builder(access = AccessLevel.PRIVATE)
                  ^
  symbol: variable AccessLevel
error: an enum annotation value must be an enum constant
@Builder(access = AccessLevel.PRIVATE)
                             ^
```
The resulting delomboked file still contains the `@Builder` annotation. The `HandleBuilderRemove` processor is not run.

**Version info (please complete the following information):**
Any lombok version since 8be4b0ffe6b5e5f89e8bb3d94e87d0aa98dc5aeb (1.18.12 was the last good release).

**Comment by md-5** [comment]
@janrieke pinging since this was your commit

**Comment by md-5** [comment]
Root cause: annotation needs to be removed before HandleDelegate runs

**Comment by md-5** [comment]
PR created: #2725

**Comment by rzwitserloot** [comment]
I'll ask @rspilker tomorrow if he's okay with the reword; I am and I think he will be too, and that 'merge' button was too green not to click.
