### ISSUE TITLE
[BUG] Error during build when nested class is imported

### ISSUE THREAD

**Issue by vlaci002** [rzwitserloot/lombok#2727]
**Describe the bug**

Java compilation error appears when compiling a class that has an import statement for one of its nested classes.

**To Reproduce**

Create file Example.java:
```
package bug;

import bug.Example.NestedClass.NestedClassInNestedClass;
import lombok.NoArgsConstructor;

public class Example {
    private NestedClassInNestedClass nestedClassInstance;

    @NoArgsConstructor
    public static class NestedClass extends OtherNestedClass {
        public static class NestedClassInNestedClass {
        }
    }

    public static class OtherNestedClass {}
}
```

When compiling with javac, the following error occurs:
<span style="color:red">
c:\Lombok_bug\src\main\java\bug\Example.java:9: error: cannot find symbol
    @NoArgsConstructor
     ^
  symbol:   class NoArgsConstructor
  location: class Example
</span>

**Expected behavior**

Compilation should finish without error.

**Version info (please complete the following information):**
 - Lombok version: 1.18.16
 - Platform: javac 1.8.0_181

**Additional context**
It compiles if I remove @NoArgsConstructor.
It also compiles if I remove the import for NestedClassInNestedClass and declare nestedClassInstance field as NestedClass.NestedClassInNestedClass.
Error occurs only when using java version 8. With java version 9 and 15 the error is not present. (I haven't tried it with versions in between but probably the error does not appear with those too.)

**Comment by Rawi01** [comment]
I think you found a `javac` bug that is already fixed in Java 9+. If I replace the `@NoArgsConstructor` with a non-lombok annotation I get the same execption. Can you confirm that?

**Comment by vlaci002** [comment]
I checked it and I can confirm that I get the same exception with e.g. @XmlRootElement. (Not with any annotation, code compiles with e.g. @Deprecated.) I am interested in it so please share a link to the bug if you know which javac bug I have found.
Thanks for your help anyway, you can close this issue.

**Comment by Rawi01** [comment]
Thanks for checking it, I found a similar issue ([JDK-8185328](https://bugs.openjdk.java.net/browse/JDK-8185328)) but there is no explanation why it fails...
