### ISSUE TITLE
[FEATURE] Support for annotations over the required arg constructor's parameters

### ISSUE THREAD

**Issue by pkordis-r7** [rzwitserloot/lombok#2739]
At the moment there is no means of setting annotations to the parameters of the constructor generated with `@RequiredArgsConstructor`. The result it that the developer has to explicitly define the constructor so that the parameters are annotated. While this is fine for a small number of `final` fields it can be frustrating when it comes to classes with a large number of them. A typical situation is when using `org.springframework.boot.context.properties.ConstructorBinding` of [Spring Boot](https://spring.io/projects/spring-cloud-config) where each parameter in the constructor must be annotated with `@DefaultValue` in order to specify fallbacks to missing properties in the resources file. Example:

``` java
@Data
@ConstructorBinding
public final class ClientProperties {
    private final Boolean enabled;
    private final Duration callTimeout;
    private final Duration connectTimeout;
    private final Duration readTimeout;
    private final Duration writeTimeout;
    private final Boolean followRedirects;

    public ClientProperties(
            @DefaultValue("true") final Boolean enabled,
            @DefaultValue("0") final Duration callTimeout,
            @DefaultValue("10s") final Duration connectTimeout,
            @DefaultValue("10s") final Duration readTimeout,
            @DefaultValue("10s") final Duration writeTimeout,
            @DefaultValue("true") final Boolean followRedirects
        ) {
            this.enabled = enabled;
            this.callTimeout = callTimeout;
            this.connectTimeout = connectTimeout;
            this.readTimeout = readTimeout;
            this.writeTimeout = writeTimeout;
            this.followRedirects = followRedirects;
            this.logging = logging;
            this.connections = connections;
        }
}
```
could become
``` java
@Data
@ConstructorBinding
@RequiredArgsConstructor(
    onParameters = @__({
        @__({@DefaultValue("true")}),
        @__({@DefaultValue("0")}),
        @__({@DefaultValue("10s")}),
        @__({@DefaultValue("10s")}),
        @__({@DefaultValue("10s")}),
        @__({@DefaultValue("true")})
    }) // This implies that there may be more than one annotations on each parameter
)
public final class ClientProperties {
    private final Boolean enabled;
    private final Duration callTimeout;
    private final Duration connectTimeout;
    private final Duration readTimeout;
    private final Duration writeTimeout;
    private final Boolean followRedirects;
}
```

**Comment by adwsingh** [comment]
You can put annotations on the individual elements and add the fully qualified annotation name to `lombok.copyableAnnotations` in lombok.config.

This is also called out in the documentation, https://projectlombok.org/features/constructor

**Comment by pkordis-r7** [comment]
Perfect, thank you for the fast response - I shouldn't have missed that!

**Comment by pkordis-r7** [comment]
Already implemented and achievable through `lombok.config`

**Comment by pkordis-r7** [comment]
What I found is that this works perfectly if the `@Target` of each annotation includes the `ElementType.FIELD`. In my case the annotation mentioned only includes the `PARAMETER` which makes the compiler to complain. I wonder if there's any way to cater for the compilation to succeed and the errors on the editor to be supressed...

**Comment by bengbengbalabalabeng** [comment]
Finally found a solution to this problem. THX!!!
And I have another question. I use `lombok.copyableannotations` to mark the annotations on the fields of the constructor. Why are the annotations of the original fields not removed? I think there should be no need to annotate both the constructor and the field at the same time, or what is the advantage of doing so?
