### ISSUE TITLE
[FEATURE] Use memoization for hashcode() for @Value classes

### ISSUE THREAD

**Issue by Meijuh** [rzwitserloot/lombok#2747]
I think the title more or less says it. Since `@Value` classes are immutable, we can use memoization for their hashcodes. I.e. their `hashcode()` method that is generated may be equivalent to the case when the class is annotated with `@EqualsAndHashCode(cacheStrategy = EqualsAndHashCode.CacheStrategy.LAZY)`. It looks like that currently `NEVER` is used for `@Value` classes. Using the `LAZY` strategy would improve performance for `@Value` classes.

**Comment by Rawi01** [comment]
This was also considered in the PR and the original issue but droped becuase there is no easy way to make sure that the object is immutable. It gets even harder if you think about mutable parent classes... Right now you have to add it to every class that should be cached as you are the only one who knows that the object is immutable.

**Comment by Meijuh** [comment]
Seems reasonable enough to me :).

**Comment by AbstractCoderX** [comment]
What about and additional annotation/parameter of @Value annotation for this? Such as @Value(cacheHashCode = true)

**Comment by andrebrait** [comment]
Without even getting into issues related to inheritance, it's easy to see why this cannot be done safely. Collections and other mutable objects are an example. See the two examples below where `@Value` will make all fields final, but this is not enough to really enforce the immutability of the object:

```java
@Value
public class Foo {
    List<String> stringList;
}
```

```java
// This is mutable
@Data
public class Bar {
    String aString;
    int aNumber;
}

@Value
public class Foo {
    Bar aBar;
}
```

As you can see, neither of the 'Foo' classes annotated with `@Value` are immutable. If you mutate the list for the first one and the `Bar` object for the second one it'll also mutate the `Foo` one.
