### ISSUE TITLE
[BUG] lombok still insert a null-check even when using androidx.annotation.NonNull 

### ISSUE THREAD

**Issue by HadadTomer** [rzwitserloot/lombok#2757]
**Describe the bug**

On Android, when using `androidx` `@NonNull` annotation (and not lombok `@NonNull`) with `@RequiredArgsConstructor` or `@AllArgsConstructor`, lombok still insert a null-check at the start of the constructor's body.

**To Reproduce**
```
import androidx.annotation.NonNull;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public class MyClass {
    @NonNull  // Android annotation
    private final String myString;
}
```
Look at the generated code

**Expected behavior**
Lombok should add the null-check only with `lombok.NonNull` annotation.

**Version info (please complete the following information):**
 - Lombok version: 1.18.18
 - Platform: Android Studio 4.1.2

**Comment by Rawi01** [comment]
If I remember correctly that behaviour is intended. Lombok knows a bunch of `NonNull` annotations and generates `null` checks if it create methods that uses these fields. Is there any reason why you think that lombok should not do that?

**Comment by HadadTomer** [comment]
You are right, It's the intended behavior.
Because I don't want lombok to do a null-check at all in my project but still use `@RequiredArgsConstructor` for example, I built a `lombok.jar` with the following changes:

1. Added `None` option to `NullCheckExceptionType`:
```
@ExampleValueString("[NullPointerException | IllegalArgumentException | Assertion | JDK | Guava | None]")
public enum NullCheckExceptionType {
	...
	NONE {
		@Override public String getExceptionType() {
			return null;
		}

		@Override public LombokImmutableList<String> getMethod() {
			return null;
		}
	};
```
2. Check the `exceptionType` inside `generateNullCheck` methods in both `EclipseHandlerUtil` and `JavacHandlerUtil` classes:
```
if (exceptionType == NullCheckExceptionType.NONE) return null;
```

**Comment by Rawi01** [comment]
I understand what you want to archive but I don't get why. 

Documentation:
> androidx.annotation.NonNull
>
> Denotes that a parameter, field or method return value can never be null. 
> This is a marker annotation and it has no specific attributes.

It clearly says that this field should never be `null` and the added check ensures that this condition is met.
