### ISSUE TITLE
@Getter/Setter(onMethod_=...) broken with Eclipse 2020-12

### ISSUE THREAD

**Issue by Maia-Everett** [rzwitserloot/lombok#2760]
I have created a minimal example in Eclipse 2020-12 with Lombok enabled:

```java
package lomboktest;

import lombok.Getter;

public class OnSetter {
	@Deprecated
	@Getter(onMethod_ = @Deprecated)
	private boolean dirty;
}
```

And it gives me this error:
![image](https://user-images.githubusercontent.com/10684/108684828-fa638d00-7525-11eb-8885-3c98ee811a64.png)

~~Eclipse 2020-03 works fine, so I'll roll back to it for now.~~ It seems that issues with Lombok began with Eclipse 2020-06 onwards.

This occurs with both JDK 8 and JDK 11 selected as the project JDK. Eclipse itself runs under JDK 11.

**Comment by Maia-Everett** [comment]
Seems broken with Eclipse 2020-03 as well, which is odd, as I don't remember it being broken before. 

Furthermore, this issue appears whether Eclipse itself us running under JDK 8 or JDK 11 (repository versions of OpenJDK in Ubuntu 20.10).

Tested with latest Lombok 1.18.18.

**Comment by pzygielo** [comment]
> Tested with latest Lombok 1.18.18.

I'm not saying it IS related, but I observed #2729 with ecj once lombok was upgraded to 1.18.18 (from 1.18.16).

**Comment by Rawi01** [comment]
If a field is marked as deprecated lombok also deprecates the generated methods. If you add the deprecated annotation a second time by hand it is there multiple times and the compiler complains about it.

**Comment by Maia-Everett** [comment]
> If a field is marked as deprecated lombok also deprecates the generated methods. If you add the deprecated annotation a second time by hand it is there multiple times and the compiler complains about it.

I originally hit this issue with Jackson's `@JsonIgnore` annotation. Does Lombok automatically propagate it to the getter/setter too?

**Comment by Rawi01** [comment]
Yes, this is the list of all annotations that gets copied: https://github.com/rzwitserloot/lombok/blob/ed4ced1a3bc694f9a9903b5a15b2641236ff2f92/src/core/lombok/core/handlers/HandlerUtil.java#L99-L329

You can also add additional annotations using the configuration system and `lombok.copyAnnotations`.

**Comment by Maia-Everett** [comment]
Closing: working as intended.

Looks like `@JsonIgnore` is propagated to the setter, but not to the getter. It probably should be propagated to the getter too, but that's a different issue.
