### ISSUE TITLE
Add an `Automatic-Module-Name` in the jar MANIFEST

### ISSUE THREAD

**Issue by sebastienh** [rzwitserloot/lombok#2761]
Note: After some more testing, I am able to use the library from a module in intellij. A Gradle configuration was the source of the problem. 

**Describe the feature**
Currently there is not `Automatic-Module-Name` defined in the jar manifest. This value allows jar to not fall under the `unnamed` module which is not well supported by Intellij. eg.

```json
Manifest-Version: 1.0
...
Bundle-SymbolicName: slf4j.api
Bundle-Name: slf4j-api
Bundle-Vendor: SLF4J.ORG
Bundle-RequiredExecutionEnvironment: J2SE-1.5
Automatic-Module-Name: org.slf4j
...
```

**Describe the target audience**
This value would allow Intellij developers working on Java 9 modules to import and use lombok from their modules. 

**Additional context**
This article describes how to add the value: [Automatic-Module-Name: Calling All Java Library Maintainers](https://dzone.com/articles/automatic-module-name-calling-all-java-library-maintainers).

**Comment by Rawi01** [comment]
I just checked the current release and there is an `Automatic-Module-Name` in the MANIFEST.MF and there also is a `module-info.class`. 
![img](https://user-images.githubusercontent.com/5850477/109199632-f93d9480-779f-11eb-8fb5-4765b2d8e7fa.png)

**Comment by sebastienh** [comment]
It's working on my side anyway, but that's not what I saw...

Here is the screenshot from my `External Libraries`:

<img width="985" alt="ScreenShot" src="https://user-images.githubusercontent.com/1621309/109252082-3c8b1800-781f-11eb-83bc-795ccc39840e.png">

**Comment by Rawi01** [comment]
Oh, you are right, it was added in 1.18.18.
