### ISSUE TITLE
[BUG] Delombok: Records are correctly identified, but are converted to classes

### ISSUE THREAD

**Issue by Auties00** [rzwitserloot/lombok#2775]
**Describe the bug**
When using delombok on a record annotated with any lombok annotation, the record is correctly identified and the annotations are correctly resolved. Though, the output file instead of being a record becomes a class. For example:
```
@ToString
public record Wrapper(String abc) {

}
```
becomes
```
// Generated by delombok at Sun Mar 14 11:30:40 CET 2021

public class Wrapper {
    private final String abc;
	
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Wrapper(abc=" + abc + ")";
    }
}
```

**To Reproduce**
Execute this command in a project where preview features are enabled and where there is at least one record annotated with a lombok annotation:
```
java -jar lombok.jar delombok src -d destination
```
To confirm that records are indeed being correctly identified run:
```
java -jar lombok.jar delombok src -d destination --disable-preview
```
This should produce an exception like this:
```
Error: records are a preview feature and are disabled by default.
```

**Version info (please complete the following information):**
 - Lombok version: 1.18.18 or edge version
 - Platform:
   openjdk version "15" 2020-09-15
  OpenJDK Runtime Environment (build 15+36-1562)
  OpenJDK 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

**Comment by Rawi01** [comment]
There already is a PR (#2578) that should fix it

**Comment by Auties00** [comment]
> There already is a PR (#2578) that should fix it

Thanks for the info. I've seen that, even though it was opened a year ago, it still isn't merged

**Comment by Rawi01** [comment]
It was opened last year, not a year ago and one of the maintainers already started to review it. There most likely is a reason why it is not merged, I guess there just wasn't enough time to finish it. `record` also was a preview feature since a few hours ago...

**Comment by Auties00** [comment]
> It was opened last year, not a year ago and one of the maintainers already started to review it. There most likely is a reason why it is not merged, I guess there just wasn't enough time to finish it. `record` also was a preview feature since a few hours ago...

Sorry, I didn't think about that as I've been using them for quite a while as preview features. I've seen that the PR has been merged, but I've found a bug. First of all, it's important to remember that records cannot extend classes, but they can implement interfaces. When using delombok on a record annotated with a Lombok annotation that implements an interface the record header is shifted after the implements clause which is syntactically wrong.

Input:
```
@SomeAnnotation
record Person(String name, int age) implements SomeInterface {

}
```
Output:
```
record Person implements SomeInterface(String name, int age) {

}
```

**Comment by Rawi01** [comment]
Thanks for testing :+1: , I created a PR to fix that. Seems like no one tried it using interfaces.

**Comment by Auties00** [comment]
> Thanks for testing 👍 , I created a PR to fix that. Seems like no one tried it using interfaces.

No problem, thanks for the quick fix!
