### ISSUE TITLE
java.lang.NoSuchMethodError : delombok, jdk-16

### ISSUE THREAD

**Issue by happyhills** [rzwitserloot/lombok#2794]
**Describe the bug**
Delombok fails.

```
Caused by: java.lang.NoSuchMethodError: 'void com.sun.tools.javac.parser.UnicodeReader.<init>(com.sun.tools.javac.parser.ScannerFactory, java.nio.CharBuffer)'
at lombok.javac.java8.CommentCollectingTokenizer$PositionUnicodeReader.<init> (CommentCollectingTokenizer.java:137)
```

CommentCollectingTokenizer.java:136-138
```
public PositionUnicodeReader(ScannerFactory sf, CharBuffer buffer) {
  super(sf, buffer);
}
```

 jdk-16
 jdk.compiler/com.sun.tools.javac.parser.UnicodeReader
`    protected UnicodeReader(ScannerFactory sf, char[] array, int length)`

 jdk-15.0.1
 jdk.compiler/com.sun.tools.javac.parser.UnicodeReader
`    protected UnicodeReader(ScannerFactory sf, CharBuffer buffer)`
`    protected UnicodeReader(ScannerFactory sf, char[] input, int inputLength)`

**Version info:**
lombok 1.18.18, jdk-16, apache-maven-3.6.3, Window10

**Comment by rspilker** [comment]
This has already been fixed.

**Comment by happyhills** [comment]
Solved with edge-SNAPSHOT. Thank you.
