### ISSUE TITLE
[BUG] JDK 16 + maven + edge-SNAPSHOT not working.

### ISSUE THREAD

**Issue by sblantipodi** [rzwitserloot/lombok#2801]
After JDK 16 we could not get Lombok working any more.

The exception reported by Maven compiler is:

`
java: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x607438c5) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x607438c5
`

No issues with earlier JDK 16 releases.

**Comment by Rawi01** [comment]
A simple maven project works without problems, please share some details about you build and make sure that you use the latest edge version.

**Comment by Wern-rm** [comment]
> A simple maven project works without problems, please share some details about you build and make sure that you use the latest edge version.

Where can I get the latest version of edge? I'm having the same problem with the latest version of lombok from the central maven repository.

**Comment by Rawi01** [comment]
https://projectlombok.org/download-edge

**Comment by Wern-rm** [comment]
> https://projectlombok.org/download-edge

Thanks! It seems to work, and it works with a bang.

**Comment by sblantipodi** [comment]
> A simple maven project works without problems, please share some details about you build and make sure that you use the latest edge version.

I narrowed the problem.

without the "annotationProcessorPaths" in the .pom file

```
 <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven.compiler.plugin.version}</version>
        <configuration>
            <source>${java.version}</source>
            <target>${java.version}</target>
            <annotationProcessorPaths>
                <path>
                    <groupId>org.projectlombok</groupId>
                    <artifactId>lombok</artifactId>
                    <version>${lombok.version}</version>
                </path>
            </annotationProcessorPaths>
        </configuration>
    </plugin>
```

I can run my project from intellij without problems.
but then I can't get it to work with maven when creating the package.

If I remove that entry then I have this error:
`
[ERROR] /C:/dev/dpsoftware/ArduinoRaspbery/PUBLIC/firefly_luciferin/src/main/java/org/dpsoftware/gui/TestCanvas.java:[274,75] cannot find symbol
  symbol:   method getScreenResY()
`

it works without problems with JDK15.

Yes I'm sure that I'm using the edge version.

this is the project :)
https://github.com/sblantipodi/firefly_luciferin/tree/color_capture_refactor

**Comment by Rawi01** [comment]
I think that it should work if you also change the version in the annotation processor path or simply update the `lombok.version` property.

**Comment by sblantipodi** [comment]
@Rawi01 ok it worked thanks. closing the issue. 

do you have an ETA for the 1.18.20?
thank you

**Comment by rspilker** [comment]
1.18.20 has just been released.
