### ISSUE TITLE
[BUG] StackOverflowError during compilation

### ISSUE THREAD

**Issue by xxDark** [rzwitserloot/lombok#2805]
**Describe the bug**
`StackOverflowError` during compilation.

**To Reproduce**
https://paste.implario.dev/nasovuyeze.java

**Expected behavior**
No `StackOverflowError`

**Version info (please complete the following information):**

1.18.20
javac 1.8.0_275

**Comment by xxDark** [comment]
[Uage](https://paste.implario.dev/jucoyutexi.java) of local variable for the injector seems to solve the issue.

**Comment by Rawi01** [comment]
Duplicate of #1118
As you already figured out the easiest workaround is to split up the long method invocation chain.
