### ISSUE TITLE
The idea get set code hint is very slow when the entity class has a large number of fields

### ISSUE THREAD

**Issue by lvanYi** [rzwitserloot/lombok#2812]
The project has some entity class fields with about 100, just use the annotation @Data, type get in the idea, the code prompt speed is about 6s, the experience is very poor. The current version used is 2021.1, before using the version before 2020.3 without this problem.

**Comment by Rawi01** [comment]
Please do not report any problems or feature requests for the intellij plugin here; file these with the [intellij lombok plugin github repo](https://github.com/mplushnikov/lombok-intellij-plugin/issues).
Thank you!
