### ISSUE TITLE
Add a hideNulls option to @ToString

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#529]
_Migrated from Google Code (issue 456)_

**Comment by askoning** [comment]
Caught in umbrella #1297.

**Comment by gmathias** [comment]
this most wanted request should not fall under the umbrella #1297. Please resurrect it !
Like many others I'm still waiting for a hideNulls option on ToString (my logs would be so less verbose !). 
As said by someone in #1297 :

> a separate boolean flag for hideNulls is very useful.
> 
> - This is the most wanted feature about ToString annotation
> - It's much easier to use for client
> - It's much easier to implement
