### ISSUE TITLE
Direct (non-maven) downloads of lombok.jar should no longer be hosted at googlecode.

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#657]
*Migrated from Google Code (issue 622)*

**Comment by askoning** [comment]
Migration done in e453c2fafab13c066a7260434f0c08f61e437c8b, 315671e79d118de718ae53b664878dd168f70ca2, e437ff4d3c84102092d6da0f1478cc54fcd84844, et al. I suggest you create a new issue for the download counter if you still want it.
