### ISSUE TITLE
Builder name conflict should be reported

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#730]
_Migrated from Google Code (issue 695)_

**Comment by rzwitserloot** [comment]
Accepted. Should fix three things:

* If two or more builder methods are generated with the same name, error out (usually `builder()`).
* Same for `toBuilder`.
* If two or more builder classes with the same name would be generated, error out.

**Comment by rzwitserloot** [comment]
Whilst we should optimally fix this, it's a little bit complicated to 'see' the effect of the 'other' builder and I think the messup is fairly self evident. Let's just let it go and avoid the code complexity.

**Comment by mEstrazulas** [comment]
Interesting because the same issue happen if we are creating two builders with different names, for different classes, but with the same name.

eg:

    ```
@Builder(builderMethodName = "yyyy")
    private static com.anotherPackage.User builderYYYY(
        UUID id,
        String name,
        String address,
        Boolean status
    ) {
        return new com.anotherPackage.User()
            .id(ofNullable(id).orElse(UUID.randomUUID()))
            .name(ofNullable(name).orElse("NoName")),
            address(ofNullable(address).orElse("address"))
            .status(ofNullable(status).orElse(true));
    }

    
    @Builder(builderMethodName = "xxxx")
    private static com.example.User builderXXXX(
        UUID id,
        String name,
    ) {
        return new com.example.User()
            .id(ofNullable(id).orElse(UUID.randomUUID()))
            .name(ofNullable(id).orElse("NoName"));
    }
```

when call `xxxx().builder()` I get the `com.anotherPackage.User` instead `com.example.User` and the called method is `builderYYYY`
