### ISSUE TITLE
Eclipse throwing LinkageError

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#767]
_Migrated from Google Code (issue 732)_

**Comment by msimko81** [comment]
Having the same problem with 1.16.6.

**Comment by msimko81** [comment]
Having the same problem with 1.16.6.
The error occur when using 'val' type but is not always reproducible even on the same file after several eclipse restarts.
No message inside workbench error log, just the following popup window:

An internal error occurred during: "Requesting Java AST from selection".loader (instance of lombok/launch/ShadowClassLoader): attempted duplicate class definition for name: "lombok/launch/PatchFixesHider$PatchFixes"

**Comment by caarlos0** [comment]
Same here

**Comment by tungpham** [comment]
Same for me as well.

**Comment by rzwitserloot** [comment]
The duplicate class def thing is a different error entirely, it just so happens to also manifest as a LinkageError; the last 3 comments above this one all reference it. I've made issue #1293 to reflect these new ones. I'm going to consider the original fixed.
