### ISSUE TITLE
onX bug with JDK8

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#778]
_Migrated from Google Code (issue 743)_

**Comment by pdinc-oss** [comment]
hmmm, 1.16.4 / 1.8.0_45 works in eclipse luna, but not in maven 3.3.3

**Comment by pdinc-oss** [comment]
confirmed with 1.8.0_60

**Comment by LeRiton** [comment]
Any chance to get this fixed despite onX experimental status ?

**Comment by antechrestos** [comment]
Same here with lombok 1.16.8 and 1.8.0_20

**Comment by maseev** [comment]
I've just ran into the same problem. The following class declaration:

```java
@Service
@RequiredArgsConstructor(onConstructor = @__(@Autowired(required = false)))
public class MagicSpringBean {
  // some fields
}
```
fails the build with:

```
duplicate element '<any?>' in annotation @<any?>.
```

This one doesn't:

```java
@Service
@RequiredArgsConstructor(onConstructor = @__(@Autowired))
public class MagicSpringBean {
  // some fields
}
```

Lombok version: 1.16.2
JDK version: 1.8.0_112

**Comment by zayats103** [comment]
maven 3.3.9, maven-compiler-plugin 3.6.1, Lombok 1.16.14, JDK 1.8.0_91 same issue

**Comment by rzwitserloot** [comment]
Did some research on this. The following holds:

Lombok needs to be invoked by javac, or all bets are off. If we're never called we can't fix anything. So, where I say 'does not work', I mean: We don't ever get invoked, so, there's simply nothing we can do about it.

Assume the following annotation:

    @interface TestAnn {
        String value() default "";
    }

Given that `onMethod` exists, `whatever` does not, `@__` also doesn't, the following code works on JDK6 but not on JDK7 and also not on JDK8:

    @Getter(onMethod = @TestAnn(value = "hello")) // snippet 1

That's nice and clean but doesn't work on 7/8. It's how onX used to work a long time ago.

The following works fine on 7, but fails on 8 with error ('duplicate <any?>'). __This means we cannot fix this issue; it's a bug in javac__ (but note that snippet 2b, 2c, and 2d do work; it fails only if you have a named param:

    @Getter(onMethod = @__(@TestAnn(value = "hello")) //snippet 2
    @Getter(onMethod = @__(@TestAnn("hello")) //snippet 2b
    @Getter(onMethod = @__(@TestAnn()) //snippet 2c
    @Getter(onMethod = @__(@TestAnn) //snippet 2d

The following works fine on 8 but fails in 7:

    @Getter(whatever = @TestAnn(value = "hello")) //snippet 3



Currently, snippet2 is what we suggest you do, and snippet1 technically still gets processed by lombok in case you somehow are still stuck on javac6.

We propose to also make snippet3 be processed by lombok. We'll make up names. Note that this solution is sucky but it's the best we can do. To wit:

* There's nothing we can do to give you a nice error message when it goes wrong. We don't get invoked.
* The method name will not be 'discoverable'; your IDE won't autocomplete it. Javadoc won't really mention it (it will be mentioned in the general docs of `@Getter` and co, but the annotation param __CANNOT EXIST__, that makes it 'work'.
* If you need to add an annotation that has a named parameter, there's no way to write it such that it'll compile under both javac7 and javac8. Again, there is absolutely nothing we can do about it.

**Comment by zayats103** [comment]
@rzwitserloot I have played around it a little and I have created a new issue about it - https://github.com/rzwitserloot/lombok/issues/1317. Looks like it works with maven 3 and Java 8 with named annotation parameters. Problem appeared when I was trying to use maven-compiler-plugin with Java 8. You can look at description of newly created issue. Thank you!
