### ISSUE TITLE
1.16.2 Wrong class loader used to load "lombok.javac.apt.Processor"

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#826]
*Migrated from Google Code (issue 791)*

**Comment by bsodzik** [comment]
I have experienced the same problem with version 1.16.4
> You found a bug in lombok; lombok.javac.apt.Processor is not available. Lombok will not run during this compilation: java.lang.ClassNotFoundException: lombok.javac.apt.Processor

Some more details
> Apache Maven 3.0.4 (r1232337; 2012-01-17 09:44:56+0100)
> Maven home: /home/tprzybyl/softwares/maven
> Java version: 1.7.0_79, vendor: Oracle Corporation
> Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
> Default locale: en_US, platform encoding: UTF-8
> OS name: "linux", version: "3.16.0-44-generic", arch: "amd64", family: "unix"

But the funny thing is that it appears only in some projects, while others work just fine. I am reverting version to 1.14.8. Good luck hunting this bug down!

**Comment by ouaibsky** [comment]
Hello
same probleme
     mvn -V clean package -e
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /Users/clalleme/opt/apache-maven-3.3.3
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"

**Comment by rspilker** [comment]
We've added some debug information in the latest [edge release](https://projectlombok.org/download-edge.html). Can you give this one a try?

**Comment by ouaibsky** [comment]
I tried but sounds the same
Where are the debug information: stdout ? or a file ?
```
[WARNING] /Users/clalleme/IdeaProjects/demog/src/main/java/org/icroco/haura/knxip/KnxHeader.java:[5,26] [deprecation] Builder in lombok.experimental has been deprecated
[WARNING] /Users/clalleme/IdeaProjects/demog/src/main/java/org/icroco/haura/knxip/KnxHpai.java:[5,26] [deprecation] Builder in lombok.experimental has been deprecated
[WARNING] /Users/clalleme/IdeaProjects/demog/src/main/java/org/icroco/haura/knxip/EKnxCode.java:[11,7] You found a bug in lombok; lombok.javac.apt.LombokProcessor is not available. Lombok will not run during this compilation: java.lang.ClassNotFoundException: lombok.javac.apt.LombokProcessor
[WARNING] 356)
/Users/clalleme/IdeaProjects/demog/src/main/java/org/icroco/haura/knxip/KnxHeader.java:[5,26] [deprecation] Builder in lombok.experimental has been deprecated
[WARNING] /Users/clalleme/IdeaProjects/demog/src/main/java/org/icroco/haura/knxip/KnxHpai.java:[5,26] [deprecation] Builder in lombok.experimental has been deprecated
[INFO] 5 warnings 

```

**Comment by lathspell** [comment]
By chance I experienced the same error. NetBeans created my "Maven -> Java Application" project with a pom.xml that used the maven-compiler-plugin version 2.3.2. After updating that version number to the current 3.5.1 it compiled fine. I use JDK 1.8.0_72 with Maven 3.3.9 and NetBeans 8.1.

**Comment by eaaltonen** [comment]
For us this problem has occurred all versions of Lombok since `1.14.8` when used with maven-compiler-plugin version `2.3.2`. Updating to `3.5.1` according to @lathspell s suggestion resolved it.

**Comment by rspilker** [comment]
Several reports suggest that using the `3.5.1` maven-compiler-plugin fixes this problem.
