### ISSUE TITLE
The generated equals and hashCode methods disagree

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#856]
_Migrated from Google Code (issue 821)_

**Comment by rzwitserloot** [comment]
This isn't a bug; it's perfectly fine for 2 non-equal objects to generate an equal hashCode (it's also trivial to prove it must be this way; it is possible to have more than 2^32 distinct different objects of the same type, and yet there are only 2^32 hashCodes, thus...)

Sure, it'd be better if you had fewer collisions but what you're asking is that lombok ditches string's hashCode impl and instead writes its own string hashcode impl that has fewer collisions.

Presumably putting it that way makes it clear that it's absolutely out of the question.
