### ISSUE TITLE
@EqualsAndHashCode shows error when class extends class in a jar file (Eclipse Mars)

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#865]
*Migrated from Google Code (issue 830)*

**Comment by rspilker** [comment]
Could it be that the jar file was compiled against an older version of Lombok? canEquals used to be public in the past, but we changed it to protected later.

**Comment by alvins82** [comment]
Well that did it - thanks for the help. Not sure if this is a bug though.. should lombok try to keep backwards compatibility so not all jars (possibly third-party) need to recompiled for new versions?
