### ISSUE TITLE
@Nonnull causes errors in Findbugs

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#871]
*Migrated from Google Code (issue 836)*

**Comment by rspilker** [comment]
I don't care about `hello world`. People that do typically have switched to another language already.

It's trivial to add `lombok.extern.findbugs.addSuppressFBWarnings=true` to `lombok.config`

We prefer to use the same code in `@Value` as in a plain `@EqualsAndHashcode` and `@Data`
