### ISSUE TITLE
Various code-generation problems with Eclipse 4.5 Mars

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#872]
*Migrated from Google Code (issue 837)*

**Comment by RainerW** [comment]
Before i start building me an ant dev environment, is there some kind of nightly builds?

**Comment by ZiziTheFirst** [comment]
I tried to build a current lombok-master branch on 15. 7. and it has indeed resolved the issues. I can share the JAR on my Google Drive if anyone is interested, it's just a regular ant build of lombok-1.16.5-SNAPSHOT...  https://drive.google.com/file/d/0B_fqmZtODWL9MnRZcGZ5NC00amM/view?usp=sharing

**Comment by okrische2010** [comment]
@ZiziTheFirst  your Jar seem to work for me as well. Phew. Thx for now.

**Comment by olivergierke** [comment]
What's the roadmap for the upcoming 1.16.x release? The milestones don't seem to be up to date. Is there an ETA?

**Comment by dschulten** [comment]
@ZiziTheFirst your jar solves the problem. Thx!

**Comment by bianfeng218** [comment]
I just use ubuntu 14.04 64bit & eclipse mars jdk1.7,but lombok doesn't work at all. I put the @Data annotation on my own class and not see the accessors occurs. so as other annotations too.

**Comment by rspilker** [comment]
Lombok v1.16.6 has just been released and contains several Mars fixes. Can you please verify if this version still contains the problem?

**Comment by olivergierke** [comment]
That's great news! I just gave it a spin and indeed I can see the code completion working again. Thanks!

**Comment by ZiziTheFirst** [comment]
Lombok v 1.16.6 works fine in the problematic cases mentioned - JUnit4 test generation + Generate getters and setters do their job with no errors or warnings.

**Comment by riderarcher** [comment]
Here's a problem. When I use Lombok v1.16.6 with ExtensionMethod, there's no content assist.
e.g.
```
@ExtensionMethod(java.util.Arrays.class)
class Example {
 private void example() {
  long[] values = new long[] { 2, 5, 7, 9 };
  values.copyOf(3).sort();
 }
}
```
When I press "values.",  there's no content assist.

**Comment by rspilker** [comment]
@riderarcher Can you please file a new bug report for your findings?

**Comment by beatjost** [comment]
I still have those Errors with 1.16.6. Also some other strange bugs... (Add throws to method, Moreunit create test is empty, create class wizard with main-class Checkbox results in error...).

Eclipse-Mars: 4.5.1, Gradle-Dependency: 	    compile 'org.projectlombok:lombok:1.16.6'

**Comment by radas** [comment]
We have the same problem with Eclipse-Mars: 4.5.0 with lombok 1.16.6 when we do save. We have some save on actions

**Comment by SWiggels** [comment]
Same here- several wizards don't work.

Eclipse-Mars: 4.5.1, Gradle-Dependency: compile 'org.projectlombok:lombok:1.16.6'

**Comment by agentgonzo** [comment]
Same issues here.
A save participant caused problems.
  The save participant 'Code Clean Up' caused an exception: java.lang.ArrayIndexOutOfBoundsException. See the error log for details.

Lombok 1.16.6 with Mars 4.5.1

**Comment by gerardcarroll** [comment]
Same as previous here

**Comment by michelbetancourt** [comment]
I'm also still seeing this error with latest Lombok and latest Mars releases.

**Comment by michaelfecher** [comment]
same as @michelbetancourt for me

**Comment by agentgonzo** [comment]
From another thread: 

> In experimenting with it, the save action setting Format source code > Format edited lines toggles whether it happens. With it enabled, it won't happen if I add and remove a space, but it will happen if I add a new field to the class or even a new comment/new token.

**Comment by agentgonzo** [comment]
@rspilker - can you re-open this please. Sufficient users are having issues that it is still a problem. I think the difference between it working for some users and not for others is the "Format edited lines" toggle in the Java save actions.

**Comment by agentgonzo** [comment]
Problem still present with 1.16.8

**Comment by sedatcans** [comment]
i am also waiting a fix. Problem still present.

**Comment by walker1c** [comment]
The problem is still present with Eclipse Neon and Lombok 1.16.8.  It appears to be caused by the "Format edited lines" save action.

**Comment by Meeeee123** [comment]
Yes, same here - confirming - "Format edited lines" is the cause.

**Comment by chinleo** [comment]
Problem still present with 1.16.10 on neon

**Comment by sergiomichels** [comment]
Problem still present with 1.16.10 on neon, should we open a new issue?

**Comment by peter-janssen** [comment]
Has been logged under #879
