### ISSUE TITLE
Refactoring in Eclipse 4.5 (Mars) fails sometimes because of Lombok

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#874]
*Migrated from Google Code (issue 839)*

**Comment by eastwood** [comment]
Eclipse mars has some real funny bugs around the formatter (https://bugs.eclipse.org/bugs/show_bug.cgi?id=303519). My first guess would be that this is at least somewhata related to your issues

**Comment by rspilker** [comment]
Lombok v1.16.6 has just been released and contains several Mars fixes. Can you please verify if this version still contains the problem?

**Comment by sergiowww** [comment]
I had experienced this bugs when using refactor commands in Eclipse and it solved when I upgraded to Lombok v1.16.6... Thanks!
