### ISSUE TITLE
Structure options for @ToString Annotation

### ISSUE THREAD

**Issue by daytona01** [rzwitserloot/lombok#876]
It would be nice if there will be an option(like @ToString(structured=true) to get a structured String output from the toString methods created by Lombok. This means that the each Property  would be on an own line(see example above) with respect to the parent objects.

  Patient(
    super=CommonBean(
        modifiedOn=null,
        id=null,
    ),
    key=null,
    person
    Id=null,
    person=Person(
        id=null,
        familyName=Bam,
        givenName=Vam,
        middleName=null,
        maidenName=null,
        nickName=null,
        prefix=null,
        suffix=null,
        dateOfBirth=1980-07-15, 
        sex=null, 
        gender=null,
        salutation=null,
        title=null, 
        photoId=null, 
        photo=null,
        addresses=null,
        bankAccounts=null, 
        citizenships=null,
        identifications=null,
        tags=null,
        languages=null,
        telecoms=null
    ),
    timeOfDeath=null,
    generalPractitionerId=null,
    owningOrganizationUnitId=5AGIGIRTYFWW8B5Y8SZR9XCUB6DGVMJY,
    remark=null, 
    acquaintedSince=2015-07-15, 
)

**Comment by rzwitserloot** [comment]
Pretty sure github kinda ruined your formatting there :/ – prefix it all with 4 spaces and it should format as code.

Pulling this off would require tossing the .toString() result of the composite fields through something like .replace("\n", "  \n") to fix indents. That gets a little hairy for the final newline, and we can't rely on calling methods to format things nicely (lombok is a compile-time only dependency). This one is gonna be tough.

**Comment by rzwitserloot** [comment]
Caught in umbrella #1297.
