### ISSUE TITLE
Version 1.16 doesn't properly construct @Data

### ISSUE THREAD

**Issue by dcapwell** [rzwitserloot/lombok#877]
I was using `1.16.4` and found the following error when compiling with maven:

```
$ mvn clean test -Dlombok.version=1.16.4
...
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ hadoop-project ---
[INFO] Compiling 16 source files to /Users/user/src/example/project/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/user/src/example/project/src/main/java/com/example/hadoop/project/PostScript.java:[6,13] error: variable footerLength might not have been initialized
[ERROR] /Users/user/src/example/project/src/main/java/com/example/hadoop/project/Type.java:[36,12] error: constructor Type in class Type cannot be applied to given types;
[ERROR]  actual and formal argument lists differ in length
/Users/user/src/example/project/src/main/java/com/example/hadoop/project/Type.java:[46,12] error: constructor Type in class Type cannot be applied to given types;
[ERROR]  actual and formal argument lists differ in length
/Users/user/src/example/project/src/main/java/com/example/hadoop/project/Type.java:[56,12] error: constructor Type in class Type cannot be applied to given types;
[INFO] 4 errors
```

When I downgrade to 1.14 or earlier, works just fine

```
$ mvn clean test -Dlombok.version=1.14.8
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

The class in question is the following:

```
import lombok.Data;

@Data
public final class PostScript {
    private final int footerLength;
    private final Version version;
    private final byte[] magic;

    public enum Version {
        V1((byte) 0x01);

        public final byte value;

        Version(byte b) {
            this.value = b;
        }
    }
}
```

Maven and Java version:

```
$ mvn --version
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T13:10:27-07:00)
Maven home: /usr/local/Cellar/maven/3.3.1/libexec
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"
```

**Comment by wiecia** [comment]
I have the same problem. Versions 1.14.* works fine, with 1.16.* I cannot compile my project

Apache Maven 3.3.3 (NON-CANONICAL_2015-04-29T11:04:34_root; 2015-04-29T10:04:34+02:00)
Maven home: /opt/maven
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-jdk/jre
Default locale: pl_PL, platform encoding: UTF-8
OS name: "linux", version: "4.1.2-2-arch", arch: "amd64", family: "unix"

**Comment by elreydetodo** [comment]
I'm also having trouble with this problem. I can't upgrade Lombok to anything >= 1.16.0.

I suspect this has something to do with a combination of class annotations being used, but I can't seem to find an order that works. There are a number of messages about this on the mailing list, so this is not an isolated problem.

**Comment by elreydetodo** [comment]
It might be worth mentioning that the affected classes for me are all subclasses of another class using lombok annotations. Maybe it's not ensuring that parent classes are processed before children?

**Comment by elreydetodo** [comment]
Yeah, I'm pretty sure the problem is with subclasses. It appears all the errors I'm getting are in subclasses of something, and it looks like _nothing_ works in a subclass. @NoArgsConstructor, @Data, and access to the constructors and getters/setters that should have been present in the parent class all don't work.

**Comment by jkwatson** [comment]
I'm having this issue with @Value objects, no subclasses involved.

**Comment by jkwatson** [comment]
Update: My issue was a maven 3 issue.  Apparently, the way that lombok & maven interact changed at in 1.16.x of lombok.  I had to add a new flag to the maven compiler plugin configuration:  
` <forceJavacCompilerUse>true</forceJavacCompilerUse>`

**Comment by elreydetodo** [comment]
That's fixed the problem for me as well. Here's the relevant doc page for maven-compiler-plugin:
https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#forceJavacCompilerUse

And here's the description of that option:
Since: 3.0
compiler can now use javax.tools if available in your current jdk, you can disable this feature using -Dmaven.compiler.forceJavacCompilerUse=true or in the plugin configuration
Default value is: false.
User property is: maven.compiler.forceJavacCompilerUse.

Is it possible to detect when this setting is not enabled and throw some meaningful error? There's no way I was ever going to guess this was the fix. I also probably wasn't going to try downgrading Maven to 2.x series.

Thanks @jkwatson  for finding this!

**Comment by jkwatson** [comment]
I found this by noting that everything worked great in my IDE, but not in maven. Hence, it had to be something maven related. I decompiled the class files that maven had generated and noted that there were none of the lombok methods present. Then, it was just a matter of googling for maven annotation processing, and voila!  Glad it helped, @elreydetodo!

**Comment by wiecia** [comment]
This fixed my issues with 1.16.x also. Thanks!

**Comment by AdamSelene** [comment]
I had the same issue with maven 3 and lombok 1.16.x but simply updating maven-compiler-plugin to 3.3 (from 2.3.2 which does not support forceJavacCompilerUse) fixed it for me (no need for forceJavacCompilerUser, but I'm still using Java 6 so no javax.tools anyway)

**Comment by sedovalx** [comment]
I'm still having the issue with Maven 3.3.3, Java 1.8.0_60, Lombok 1.16.6 and maven-compiler-plugin 3.3.
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.3</version>
	<configuration>
		<source>1.8</source>
		<target>1.8</target>
		<showWarnings>true</showWarnings>
		<showDeprecation>true</showDeprecation>
		<forceJavacCompilerUse>true</forceJavacCompilerUse>
		<compilerArgs>
			<arg>-Xlint</arg>
			<arg>-proc:none</arg>
		</compilerArgs>
	</configuration>
</plugin>
```
No setters and getters are generated when I use @Data on a class.

**Comment by sedovalx** [comment]
My bad - without <arg>-proc:none</arg> everything works just fine...
