### ISSUE TITLE
Add NullConstructor

### ISSUE THREAD

**Issue by rmannibucau** [rzwitserloot/lombok#878]
Sometimes for technical reason (proxying of the framework) the class you develop needs a no arg constructor. To keep using final field you can init them to null. Would be great if lombock could do it, something like:

    @ApplicationScoped // CDI
    @RequiredArgsConstructor(onConstructor = @__(@Inject))
    @NoArgConstructor(setFinalFieldsToNull = true)
    public class MySuperCdiClass {
        // ...
    }

**Comment by rzwitserloot** [comment]
Good idea. Implemented here: https://github.com/rzwitserloot/lombok/tree/force

the biggest issue is the name of the parameter. setFinalFieldsToNull is very long and misleading (ther'es also false and 0 for primitives for example). But 'force' is perhaps not quite enough either. Any ideas?

**Comment by rmannibucau** [comment]
Great! For the naming I agree. Maybe the use case then: proxySubclassAllowed=true. A bit long but explicit.

**Comment by Maaartinus** [comment]
Maybe `force(With)DefaultValues` or `setFinalFieldsToDefault(s)`? But IMHO `force` is good enough as there's nothing else what could be forced.

**Comment by rmannibucau** [comment]
maybe defaults, but yes force is good enough once you meet it once.

**Comment by rzwitserloot** [comment]
Closed in commit fd1d18a29957fc1999b7dd5725641662ad3bd887 which will be in v1.16.6
