### ISSUE TITLE
Feature Request: Provide type inference for non -final variables also on same lines as 'val' for final variables with 'var'

### ISSUE THREAD

**Issue by rkapa2006** [rzwitserloot/lombok#883]
Please provide type inference for non-final variables with 'var' similar to 'val' for final variables.

Ex:

@Data
public class Person {
   val name = "John Doe";
   var age = 41;
   var addressList = new ArrayList<Address>();
}

**Comment by askoning** [comment]
This was discussed before - see [this mailing list thread](https://groups.google.com/forum/#!topic/project-lombok/b1D_NxC0__U). Basically, creating this (difficult!) type inference for non-final variables wouldn't be worth the effort.
