### ISSUE TITLE
'val' is broken when local variable and class field have the same name

### ISSUE THREAD

**Issue by slovit** [rzwitserloot/lombok#889]
The following class fails to compile with `maven`

```java
package tmp;
import lombok.val;

public class Test {
	
	private int age;
	
	public static void main() {
		new Test().test();
	}
	
	public void test() {
		val age = returnAge(age);
	}
	
	private  int returnAge(int a) {
		return a;
	}

}
```
The error is
```
/Test.java:[15,21] Cannot use 'val' here because initializer expression does not have a representable type: Type cannot be resolved
```

There is a problem in the class. The class field is not visible in the method, but it's difficult to detect as in Eclipse this gives no error.

![screen shot 2015-07-29 at 12 45 35 pm](https://cloud.githubusercontent.com/assets/6423938/8963755/bf04b1ec-35ef-11e5-9e1f-87cc1d34243d.png)

**Comment by askoning** [comment]
This would not work without `val` either: `int age = returnAge(age);` would also result in a compilation error. Use `val age = returnAge(this.age);` instead.
