### ISSUE TITLE
@cleanup - multiple method calls

### ISSUE THREAD

**Issue by yaronr** [rzwitserloot/lombok#890]
Hi

It would be nice if  'cleanup' would be able to accept an array of values, representing a sequence of cleanup methods - which will be then executed in order.

Example:
@ cleanup(["disconnect","close"])

**Comment by rschmitt** [comment]
Well, if you're on Java 8, you can always do this:

@Cleanup Server server = ...;
@Cleanup("run") Runnable disconnect = () -> server.disconnect();

**Comment by kazuki-ma** [comment]
:neutral_face:  I think they have no time to do that.

@rschmitt Just copy is enough. It works all supported java versions.

```java
@Cleanup("close") CloseableAndCleanupable instance = ...;
@Cleanup("cleanup") CloseableAndCleanupable copy = instance;
```

makes

```java
CloseableAndCleanupable instance = ...;
try {
	CloseableAndCleanupable copy = instance;
	try {
	} finally {
		if (java.util.Collections.singletonList(copy).get(0) != null) {
			copy.cleanup();
		}
	}
} finally {
	if (java.util.Collections.singletonList(instance).get(0) != null) {
		instance.close();
	}
}
```

**Comment by rspilker** [comment]
It's not (just) about the time. We don't see this pattern a lot so we do not consider it boilerplate. 

Even though the existing code would still work, it is not strictly backwards compatible in the binary. 

It is similar to changing `void foo(String)` to `void foo(String...)`. All code calling `foo(String)` will still compile and on the surface behave the same, but under the hood, now an array is created and a different method is invoked. The method `void foo(String)` is not in the bytecode. This leads to unexpected binary incompatibilities.
