### ISSUE TITLE
@EqualsAndHashCode - redundant null check on @Nonnull attributes

### ISSUE THREAD

**Issue by lguerrin** [rzwitserloot/lombok#891]
When a class has attributes with annotation javax.annotation.@Nonnull, and has annotation @EqualsAndHashCode, the generated code checks if the value is null.
And Sonar notifies about redundant null check:
```
Redundant nullcheck of $attr1, which is known to be non-null in org.example.Test.hashCode()
Redundant nullcheck of $attr1, which is known to be non-null in org.example.Test.equals()
```

Can you skip this check if attribute is annotated with @NonNull?

**Comment by rzwitserloot** [comment]
The java universe (core libraries + all code ever written) simply doesn't work that way. `@NonNull` is a suggestion. It's not a guarantee. Even if some slice of code can be statically analysed to ensure that non-nullness is guaranteed, _WE_ (lombok) isn't going to do it, those checks are very complex and rather expensive. Even if we or the IDE can guarantee that it can't happen, adding or removing the nullcheck silently depending on what you do with your code doesn't really sound like a 'win'.

That's a long way to say: The right thing to do with generated code especially, is to do the safe thing, even if the safe thing is thought to be overkill.

So, we have no intention of 'fixing' this. Our general policy on such things is as follows:

It's generated code. Don't worry. It knows better than your linters and code checkers. Configure your code checkers to not look at lombok code. We generate a `@Generated` annotation on all the methods we generate (including `equals` and `hashCode`), so you might want to file a bug with sonar that they should NOT ignore that annotation (this is exactly what it's for). This is only an option for source-level code checkers (the `@Generated` annotation, in an apparent momentary lapse of all reason and judgement, was marked as retentionlevel = source. Yeah. D'oh. Not our fault.

We can also generate the findbugs annotation, but you have to enable that via the config system:

    lombok.extern.findbugs.addSuppressFBWarnings = true

If some other annotation is needed to do this, er, I guess we could add it. Please give us all the necessary details (mostly: The javadoc of said annotation, and where one would download the dependency jar containing this annotation) and we'll consider it.
