### ISSUE TITLE
Staged @Builder

### ISSUE THREAD

**Issue by Fuud** [rzwitserloot/lombok#896]
Assume we have class:
```
@Builder
public class MyClass {
    private int a;
}
```

After processing it will became:
```
public class MyClass {
    private int a;

    MyClass(int a) {
        this.a = a;
    }

    public static MyClass.MyClassBuilder builder() {
        return new MyClass.MyClassBuilder();
    }

    public static class MyClassBuilder {
        private int a;

        MyClassBuilder() {
        }

        public MyClass.MyClassBuilder a(int a) {
            this.a = a;
            return this;
        }

        public MyClass build() {
            return new MyClass(this.a);
        }

        public String toString() {
            return "MyClass.MyClassBuilder(a=" + this.a + ")";
        }
    }
}
```

And somewhere in code it can be used:
```
MyClass.builder().a(42).build();
```

But what will happen if we add new field b to out class?
```
@Builder
public class MyClass {
    private int a;
    private int b;
}
```

Everything will compile as before. Sometimes (often?) it is not desired. `@Builder` should have option to forbid leave fields unassigned.
Also there is another problem with IDE support (a and b already assigned, but IntelliJ Idea does not understand that it should suggest something else. It is easy to forget set some fields in case of big data class):
![image](https://cloud.githubusercontent.com/assets/283980/9247410/75a4d388-41bb-11e5-9579-0580733e3b7a.png)

Possible solution is to use Staged builder. Generated code will be:
```
public class MyClass {
    private int a;
    private int b;

    MyClass(int a, int b) {
        this.a = a;
        this.b = b;
    }

    public static MyClassBuilderStage1 builder() {
        return new MyClass.MyClassBuilder();
    }

    public static class MyClassBuilder implements MyClassBuilderStage1, MyClassBuilderStage2, MyClassBuilderStage3 {
        private int a;
        private int b;

        MyClassBuilder() {
        }

        public MyClassBuilderStage2 a(int a) {
            this.a = a;
            return this;
        }

        public MyClassBuilderStage3 b(int b) {
            this.b = b;
            return this;
        }

        public MyClass build() {
            return new MyClass(this.a, this.b);
        }

        public String toString() {
            return "MyClass.MyClassBuilder(a=" + this.a + ", b=" + this.b + ")";
        }

    }


    public interface MyClassBuilderStage1{
        MyClassBuilderStage2 a(int a);
    }

    public interface MyClassBuilderStage2{
        MyClassBuilderStage3 b(int a);
    }

    public interface MyClassBuilderStage3{
        MyClass build();
    }

}
```

**Comment by rzwitserloot** [comment]
We've discussed this at length and aren't currently going to go for this. It's too exotic, generates tons of cruft, makes for crappy signature lines, forces you to hit the fields in that exact order, does not make for an easily sharable/reusable builder, and requires extra config to highlight mandatory vs. optional stuff.

Not off the table permanently, but marking it as a wontfix regardless; we won't get around to this soon enough to bother leaving the issue open.

**Comment by jtoselli** [comment]
What a shame this was dicarded. I would give everything to be able to use builders while not losing compile time checking for mandatory fields (something that could be inferred using `final` keyword.

**Comment by bilal-fazlani** [comment]
I reached here searching for safer builder pattern. All what's said about its implementation complexity is true, but given lombok's popularity and widespread adoption, having this feature would be really nice.
