### ISSUE TITLE
Subclass constructors do not include parent fields

### ISSUE THREAD

**Issue by ahoffmann-wi** [rzwitserloot/lombok#898]
## Issue Summary

A constructor generated for a subclass does not include fields that are inherited from its parent. This behavior is identical with `@RequiredArgsConstructor` and `@AllArgsConstructor`.

## Example 

```java
@Data
@Inheritance(strategy = InheritanceType.JOINED)
public abstract class Person {
    @NonNull
    private String name;
}
```

```java
@Data
@AllArgsConstructor
public class Programmer extends Person {
    @NonNull
    private String favoriteLanguage;
}
```

### Expected Constructor

```java
public Programmer(String name, String favoriteLanguage);
```

### Actual Constructor

```java
public Programmer(String favoriteLanguage);
```

### Additional Notes

I have also tried the following with the same result:
* Removing `abstract` keyword from parent class
* Adding `@AllArgsConstructor` to parent class

**Comment by ahoffmann-wi** [comment]
This actually appears to be an issue with the IntelliJ plugin not understanding the inheritance. When I try to compile, a constructor including the parent's fields is expected.

**Comment by ahoffmann-wi** [comment]
Closing issue and will reopen one addressing the IntelliJ plugin.

**Comment by vasuaroraofficial** [comment]
Hey, can you provide the link to the issue you created addressing the intelliJ plugin?
Are you sure this is an issue with the plugin and not with @RequiredArgsConstructor and @AllArgsConstructor?

**Comment by Maaartinus** [comment]
@vasuaroraofficial I'd rather sure, it's not a plugin problem. Lombok can't see other classes (as they possibly weren't compiled yet), and while it can get some information about them, it's complicated and slow. Supporting super constructors would be nice, but IIUIC there's not even a promising approach yet.
