### ISSUE TITLE
new release on the horizon?

### ISSUE THREAD

**Issue by martinlippert** [rzwitserloot/lombok#901]
there are various issues with Lombok on Eclipse Mars and I've seen some fixes in master for that already, but it would be great to get a new release rolled out that works with Eclipse Mars. Any plans for pushing out a new release? That would be great!!!

**Comment by rzwitserloot** [comment]
We just released 1.16.6 :)

**Comment by martinlippert** [comment]
Awesome!!! Many many thanks, great work!!!
