### ISSUE TITLE
Annotation processor 'lombok.core.AnnotationProcessor' not found

### ISSUE THREAD

**Issue by lalib** [rzwitserloot/lombok#905]
Hi,

I'm using lombok in my entities and want to produce MetalModelEntities. So I used lombok Annotation Processor. When i compile the project it gives below error:

#### "Annotation processor 'lombok.core.AnnotationProcessor' not found"

Here are my tools versions :

Maven 3.2.5
Java 1.8
Lombok 1.16.6

Here is how i use lombok:

```xml
 <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>${project.java.version}</source>
                    <target>${project.java.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <!--<compilerArgument>-proc:none</compilerArgument>-->
                    <annotationProcessors>
                        <annotationProcessor>lombok.core.AnnotationProcessor</annotationProcessor>
                    </annotationProcessors>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.bsc.maven</groupId>
                <artifactId>maven-processor-plugin</artifactId>
                <version>2.2.4</version>
                <executions>
                    <execution>
                        <id>process</id>
                        <goals>
                            <goal>process</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <!-- source output directory -->
                            <outputDirectory>${generated-java-source}</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>1.9.1</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${generated-java-source}</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
</plugins>
```

If i use lombok 1.14.8, I don't get see any problem. When i look at the 1.16.6 jar file. lombok.core.AnnotationProcessor is over there but all class extensions are .lombok. I think this causes the problem.

How can i solve it?

**Comment by rzwitserloot** [comment]
We've changed the classloading infrastructure inside our jar between those versions.

The correct annotation processor class has changed to:

lombok.launch.AnnotationProcessorHider$AnnotationProcessor

Try putting that string in the XML at location: plugins/plugin [maven-compiler-plugin]/configuration/annotationProcessors/annotationProcessor.

If this does not work, please re-open the issue.

**Comment by lalib** [comment]
When i change  AnnotationProcessor class like this:

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>${project.java.version}</source>
                    <target>${project.java.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <!--<compilerArgument>-proc:none</compilerArgument>-->
                    <annotationProcessors>
                        <annotationProcessor>lombok.launch.AnnotationProcessorHider$AnnotationProcessor</annotationProcessor>
                    </annotationProcessors>
                </configuration>
            </plugin>
```

The problem was solved. Thank you so much.

**Comment by mnukka** [comment]
I accidentally discovered this same solution to my problem as well.

I am going to paste the error that might lead future googlers to right information.

maven lombok cannot find symbol method

**Comment by chlegou** [comment]
if anyone still looking for right answer, here it is ;) 

link: https://github.com/jhipster/generator-jhipster/issues/5942#issuecomment-335002220

**Comment by mcherb** [comment]
how to add this in a sbt project ?

**Comment by Shreyar20** [comment]
> ```
> <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-compiler-plugin</artifactId>
>                 <version>3.2</version>
>                 <configuration>
>                     <source>${project.java.version}</source>
>                     <target>${project.java.version}</target>
>                     <encoding>${project.build.sourceEncoding}</encoding>
>                     
>                     <annotationProcessors>
>                         <annotationProcessor>lombok.launch.AnnotationProcessorHider$AnnotationProcessor</annotationProcessor>
>                     </annotationProcessors>
>                 </configuration>
>             </plugin>
> ```

**Comment by Shreyar20** [comment]
I am still getting error, don't know what is going wrong.Please help

**Comment by randakar** [comment]
Please correct your pom file. As per https://projectlombok.org/setup/maven
the correct bit of maven compiler plugin configuration looks like this:

<annotationProcessorPaths>
	<path>
		<groupId>org.projectlombok</groupId>
		<artifactId>lombok</artifactId>
		<version>1.18.12</version>
	</path>
</annotationProcessorPaths>

**Comment by robert-gdv** [comment]
@rzwitserloot : Why did you hide it, if this kind of setting requires a simple stable path?
Or do you recommend a totally differnt way to handle the sequence of annotation preprocessors with maven-compile-plugin?
