### ISSUE TITLE
In Java 8 and above @Log (and friends) should be allowed on interfaces

### ISSUE THREAD

**Issue by jmax01** [rzwitserloot/lombok#906]
@Log annotations should be allowed on Java 8 and above as interfaces can have static and default methods.

**Comment by rzwitserloot** [comment]
Actually, thinking about it some more; we'd have to make the field public, and we'd have to ignore attempts to make it non-static, as all fields in interfaces are public, static, and final. More generally, the 'intent' of a field in an interface is for it to be a constant, and a logger isn't semantically speaking a constant.

The upshot is that you'd have to generate the logger elsewhere (for example, an inner class, which has to be public too, but the members in _THAT_ don't have to be), or for the default impl to be a wrapper around an implementation that lives elsewhere. Either way, lombok can't just allow @Log and co on interfaces.

**Comment by jmax01** [comment]
Couple things:
* How is one supposed to log in interface declared methods (default and static)?
* In java 9 private static fields will be allowed on interfaces.
* Can you give an example of when one would attempt to make an interface logger non-static?
