### ISSUE TITLE
Lombok nullpointer in PatchDelegate in Eclipse Mars

### ISSUE THREAD

**Issue by kristjant** [rzwitserloot/lombok#913]
I'm using Eclipse Mars with Lombok 1.16.6 and lombok throws the following exception when compiling:

Internal compiler error: java.lang.NullPointerException at lombok.eclipse.agent.PatchDelegate.addAllMethodBindings0(PatchDelegate.java:702)	
Foo.java	/project/src/foo/line 0	Java Problem

binding.scope is null there and because of that Eclipse throws a nullpointer from lombok when compiling.

**Comment by rspilker** [comment]
Can you back up the claim that on that line `((SourceTypeBinding) binding).scope` is null? The constructor would not have completed for a null scope, and I could not find any evidence that it is set to null later.

**Comment by hnadra** [comment]
I'm getting the same issue. I put a breakpoint and I can see scope is null. The binding is a SourceBinding for a class that is used as a delegate from another class. The stack of the JVM is attached.
[stack.txt](https://github.com/rzwitserloot/lombok/files/105553/stack.txt)

**Comment by rspilker** [comment]
I've added a fix, but haver not been able to reproduce the problem myself. Can someone give the [latest edge release](https://projectlombok.org/download-edge.html) a try?

**Comment by rspilker** [comment]
I've update the edge release, can someone give it a try?

**Comment by hnadra** [comment]
I tested with the edge release and didn't see the error. I also confirmed that the error was occurring with the 1.16.8 release which doesn't include this fix.

**Comment by rspilker** [comment]
Thanks for the confimation. We'll probably ship a new version this week.
