### ISSUE TITLE
@Builder seems to ignore initialization of fields (default value)

### ISSUE THREAD

**Issue by stefansiegl** [rzwitserloot/lombok#916]
Hi,

Great tool that you are building there. Helped me a lot. There is just this tiny issue that I was running against, when using the builders together with default initialization of fields.

Thanks for your time,
Stefan

```
@Builder @Data
public class BuilderInitialization {
    private String aString;
    @Singular private List<String> aListOfStrings = new ArrayList<>();
    
    public void addString(String some) {
        aListOfStrings.add(some);
    }
    
    public static void main(String[] args) {
        // Say we build the instance with a builder
        BuilderInitialization myInstance = BuilderInitialization.builder().aString("some String").build();
        
        myInstance.addString("Some String");
        // NullPointerException: aListOfStrings is <null>
    }
}
```
Note that it also does not work if I put the initialization of the fields in a constructor.

Changing the code to not use the builder and use "normal" constructors work like a charm

**Comment by Maaartinus** [comment]
I tried to reproduce it and I get an `UnsupportedOperationException`, which is actually correct as `@Builder` is primarily meant for immutables (and uses either `Collections.unmodifiableList` or Guava's `ImmutableList` here).

In case you're really getting a `NullPointerException`, this is a bug (I guess you should try the newest version before the developers look into it).

---

Not honoring your initializer expresssion is no bug: When you look at the generated constructor (e.g. in the "members" view), you can see 

     BuilderInitialization(String, List<String>)

which only makes sense, when the initializer expresssion gets ignored. That's not nice (there could be a warning), but it's logical:

> Finally, applying `@Builder` to a class is as if you added `@AllArgsConstructor(access = AccessLevel.PACKAGE)` to the class and applied the `@Builder` annotation to this all-args-constructor.

Add an explicit constructor or another `XArgsConstructor` annotation or **simply make `aListOfStrings` final**.

**Comment by stefansiegl** [comment]
Hello @Maaartinus,

Thank you for your reply. I tried the sample with the newest lombok version and you are right. `UnsupportedOperationException` is thrown instead of `NullPointerException`. 

Your reasoning is completely understandable. I will change this accordingly.

Sorry for not having tried this on the newest version first.
Stefan

**Comment by Maaartinus** [comment]
Another one bit by this issue: http://stackoverflow.com/a/39591047/581205

A good solution is hard to find, but a warning would be really helpful. I guess, `@Builder` should warn whenever there's any non-static initializer expression.
