### ISSUE TITLE
Feature Request: add configuration key lombok.toString.includeClassName

### ISSUE THREAD

**Issue by maximebochon** [rzwitserloot/lombok#918]
It could be useful sometimes to prevent displaying the class name and the parentheses in the string produced by the Lombok generated 'toString' method.

This could be done using a new configuration key:

```
lombok.toString.includeClassName [true|false] (default: true)
```

Here are some examples of the expected result:
1. `ClassName1(field1=value1, field2=ClassName2(field1=value1, field2=value2), field3=value3)`
2. `field1=value1, field2=ClassName2(field1=value1, field2=value2), field3=value3`
3. `field1=value1, field2=(field1=value1, field2=value2), field3=value3`

| Example | ClassName1 | ClassName2 |
| --- | --- | --- |
| 1 | true | true |
| 2 | true | false |
| 3 | false | false |

**Comment by rspilker** [comment]
Your third example is incorrect: it added parenthesis. Removing the parenthesis is, in my opinion, a bad idea. 

The (generated) toString is for debugging purposes only. I can see some value in not adding the class name. However, I don't think a configuration key is the best place here, since then all toStrings in at least a package, will not show the class name resulting in confusing strings. However, adding a field to the `@ToString` might just have enough value: `@ToString(className=false)`

**Comment by maximebochon** [comment]
I perfectly agree with you about using a field instead of a key. Actually I thought it was equivalent when I looked at an example of it in the online documentation. So yes for field, not a key.

About the parenthesis question now, the third example can't be incorrect since it is a feature request, not a description of reality (I will edit my message to make it clearer).

So if I try to explain the idea behind these examples, a think the main point is that `ClassName2` (child class) does not output itself any parenthesis around its fields: it is `ClassName1` (parent class) that produces them in the case `includeClassName` is `false` for `ClassName2`.

I admit, this may greatly complicate `@ToString` algorithm, but personally I find it useful and elegant.

**Comment by rzwitserloot** [comment]
@maximebochon lombok cannot look at the content of ClassName2 when it is processing for ClassName1. That's called 'resolution'; it's possible (Delegate does it a lot; val does it a little), but pricey, and `@Data` and co simply won't get that, they are too important to foist with the performance drawbacks of adding it. So, that is off the table, and given that it's off the table, removing parens is off the table.

At that point this whole 'no class file' starts to not be worth the mental load of even having a setting for it.

Feature request denied, but I'm going to create a new issue to centralize all the various toString requests, I have an idea...

**Comment by rzwitserloot** [comment]
Caught in umbrella #1297.
