### ISSUE TITLE
Maven 3 + Java 7/8 + Lombok 1.16.x = code NOT generated

### ISSUE THREAD

**Issue by Serzhas** [rzwitserloot/lombok#919]
Lombok 1.16.x does not generate any code building project with Maven 3 from command-line. Tried different aproaches with Java 7 and 8 - no results. Downgrading Lombok version to 1.14.8 does the trick. What's wrong with 1.16.x version?
Environment:
Apache Maven 3.2.3
JDK 1.8.0_51, 1.7.0_67
Windows 7 64-bit, Linux
Project used to test: https://filetea.me/t1sQ5rZrdoaRKGBmZHSLDgWnw

**Comment by mjgp2** [comment]
I can confirm this.

**Comment by smoyer64** [comment]
I created issue #926 as a duplicate of this one (accidentally) but there was a relevant [mailing list](https://groups.google.com/forum/#!topic/project-lombok/ZENQEVi41vI) entry on August 12th if more information is needed.  The executive summary is that I'm experiencing the same issue - compiling manually (via javac) works, as does the class outline when 1.16.x is installed in Eclipse, but building with Maven fails to add the expected methods (and SLF4J logger).

**Comment by mstandio** [comment]
Same here, maven compilation fails. win7, JDK 1.8.0_51, mvn 3.3.3
Downgrading to 1.14.2 supposedly helps, but then Mars won't start.

**Comment by elreydetodo** [comment]
I think this is a dupe of #877. You might just need to update maven-compiler-plugin to version 3.3.

**Comment by Serzhas** [comment]
Indeed, updating *maven-compile-plugin* version to *3.3* solves this issue!
