### ISSUE TITLE
Extension method taking lambda parameter causes StackOverflow under certain conditions

### ISSUE THREAD

**Issue by dannyferreira** [rzwitserloot/lombok#921]
Suppose we have the following class with an extension method:

```
import java.util.function.Function;

public class Extensions {

    public static Object apply(Object o, Function<Object, Object> f) {
        return f.apply(o);
    }
}
```

The following program causes a StackOverflowException:

```
import lombok.experimental.ExtensionMethod;

@ExtensionMethod({Extensions.class})
public class ExtensionUser {

    public static void main(String[] args) {
        m(args.apply(x -> x));
        m(args.apply(x -> x));
        m(args.apply(x -> x));
    }

    private static void m(Object s) { }
}
```

The error looks like this:

> Error:java: Lombok annotation handler class lombok.javac.handlers.HandleExtensionMethod failed on <blah>\src\main\java\ExtensionUser.java: java.lang.StackOverflowError

There are several changes that can be made to prevent the exception from occurring:
- remove one of the three invocations in the main method
- pass a non-lambda argument into the extension method
- remove the calls to the private method 'm'

Sorry that I could not reduce the example further.  I hope this helps.

**Comment by ThanksForAllTheFish** [comment]
I am having the same issue, but it seems it is not a `lombok` issue, rather a `javac` one: https://bugs.openjdk.java.net/browse/JDK-8145181
The issue is claimed to be resolved, but with `javac 1.8.0_92` I am still able to reproduce it exactly as it is described in the ticket.

Unfortunately it is not possible to update the ticket now since the site is down for maintenance. Hopefully I will remember to update it later.

FYI, the error is
```
The system is out of resources.
Consult the following stack trace for details.
java.lang.StackOverflowError
        at com.sun.tools.javac.comp.Attr.visitLambda(Attr.java:2295)
        at com.sun.tools.javac.tree.JCTree$JCLambda.accept(JCTree.java:1624)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:575)
        at com.sun.tools.javac.comp.Attr.visitLambda(Attr.java:2434)
        at com.sun.tools.javac.tree.JCTree$JCLambda.accept(JCTree.java:1624)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:575
```
and so on

**Comment by maherm** [comment]
+1
Having the same issue here without lambdas, but only if I build my project with maven. Eclipse compiles just fine.
Strange thing is, there is no lambda expression anywhere near that code. Also the code worked fine for ages and started failing just now, when I changed some unrelated stuff in the same class.

**Comment by NawaMan** [comment]
+1
Still have the same problem in 2018. The frustrating thing is that it does not tell me where :-(.
