### ISSUE TITLE
Serial version UID

### ISSUE THREAD

**Issue by gualtierotesta** [rzwitserloot/lombok#923]
It would be nice to have an annotation to automatically create a field like

``` java
    private static final long serialVersionUID = 8310165171840482032L;
```
for all classes which `implements java.io.Serializable`

**Comment by askoning** [comment]
This has been discussed before and deemed not worth the effort; see e.g. https://groups.google.com/forum/?hl=en#!searchin/project-lombok/@serializable/project-lombok/RQ6VQRRMY38/jli-UYPSgfgJ
