### ISSUE TITLE
Lombok is generating the wrong getter/setter for single small leading letter.

### ISSUE THREAD

**Issue by anpieber** [rzwitserloot/lombok#927]
For something like iMessage Lombok is generating the wrong getters&setters. As **8.8: Capitalization of inferred names of the JavaBeans API specification** defines, and all the IDEs (Intellij, Eclipse, ...) does automatically, iMessage needs to become getiMessage and setiMessage instead of getIMessage and setIMessage.

**Comment by askoning** [comment]
Unfortunately the bean spec isn't followed consistently even within their own implementation - see [this mailing list thread](https://groups.google.com/forum/#!topic/project-lombok/c9WKYhlfe8k), as a result of which it was decided not to change the behaviour.

**Comment by rzwitserloot** [comment]
Duplicate of #2693
