### ISSUE TITLE
@PrivateConstructor

### ISSUE THREAD

**Issue by Punkratz312** [rzwitserloot/lombok#929]
Would be very nice if, lombok could generate a private constructor.

/**
 * Constants concerning {@link DepartmentController}.
 *
 * @author  Aljona Murygina - murygina@synyx.de
 */
public final class DepartmentConstants {

    // JSPs
    public static final String DEPARTMENT_JSP = "department/department_list";
    public static final String DEPARTMENT_FORM_JSP = "department/department_form";

    // Attributes
    public static final String DEPARTMENTS_ATTRIBUTE = "departments";
    public static final String DEPARTMENT_ATTRIBUTE = "department";

    private DepartmentConstants() {

        // Hide constructor for util classes
    }
}

**Comment by askoning** [comment]
It already can! You can specify an access level, for example `@NoArgsConstructor(access=AccessLevel.PRIVATE)`

**Comment by Punkratz312** [comment]
@askoning Thank you very much.
