### ISSUE TITLE
Use FindBugs-compatible @SuppressWarnings on generated methods

### ISSUE THREAD

**Issue by sgrimm-sg** [rzwitserloot/lombok#943]
Lombok annotates generated methods with `@java.lang.SuppressWarnings("all")` to try to get rid of lint warnings. The `"all"` suppression is specific to the Eclipse compiler and is ignored by javac. If I run `delombok` and change the generated code to use `@SuppressWarnings("unchecked")` instead, the unchecked cast warnings on `@Getter(lazy=true)` generated methods go away.

It would be great if Lombok could generate both annotations. The `"unchecked"` suppression is defined by the Java language spec so it ought to work on any compiler.

**Comment by jinahya** [comment]
````
$ javac -version
java 1.8.0_60
$ javac -X
  ...
  -Xlint:{all,auxiliaryclass,
          cast,classfile,
          deprecation,dep-ann,divzero,
          empty,
          fallthrough,finally,
          options,overloads,overrides,
          path,processing,
          rawtypes,
          serial,static,
          try,
          unchecked,
          varargs,
          -auxiliaryclass,
          -cast,-classfile,
          -deprecation,-dep-ann,-divzero,
          -empty,
          -fallthrough,-finally,
          -options,-overloads,-overrides,
          -path,-processing,
          -rawtypes,
          -serial,-static,
          -try,
          -unchecked,
          -varargs,
          none} Enable or disable specific warnings
  ...
$ 
````

**Comment by sgrimm-sg** [comment]
Thanks; my analysis of the problem was wrong. It turns out the unchecked cast warning is coming from FindBugs, not from `javac`. FindBugs is what is ignoring the `"all"` suppression, and it's also not paying attention to the `@Generated` annotation.

While that's arguably a FindBugs bug, Lombok could switch to `"unchecked"` and still achieve the desired goal of suppressing the unchecked warning. Hopefully the Lombok developers will consider doing it.

**Comment by rspilker** [comment]
It's not easy to generate the minimal suppression for each type of code, especially since different tools have slightly different implementations of their analysis and resolution, leading to different conclusions. Also, if we always generate `unchecked` you might get a warning on the `@SuppressWarnings` that it isn't necessary to suppress it since it wouldn't occur.

All in all, we always at least also need to add "all". That says it all.

**Comment by rspilker** [comment]
Did you see on the [configuration system page](https://projectlombok.org/features/configuration.html) that you can instruct Lombok to also generate Fundbugs specific warnings using `lombok.extern.findbugs.addSuppressFBWarnings = true`?
