### ISSUE TITLE
@Wither in an abstract class should declare an abstract method of that behavior

### ISSUE THREAD

**Issue by danthonywalker** [rzwitserloot/lombok#945]
So for example:

>public abstract class Foo {
@Wither int bar;
}

makes

>public abstract class Foo {
int bar;
public abstract Foo setBar(int bar);
}

**Comment by karayv** [comment]
Just asked a question that might be related to this 
https://stackoverflow.com/questions/56761054/lombok-wither-inheritance-super-sub-classes
