### ISSUE TITLE
Delombok option doesn't generate code for @Nonnull check.

### ISSUE THREAD

**Issue by Scythson** [rzwitserloot/lombok#950]
So, what I'm trying to do, is to generate null check code with delombok feature, but it doesn't work:

c:\lib>java -jar lombok.jar delombok -p LombokTest.java
```java
package com.some.test;

import lombok.*;

import java.io.Serializable;

public class LombokTest implements Serializable {

        public String text;

        public LombokTest( @NonNull Object text) {
                this.text = text.toString();
        }

        public int setText( @ NonNull String anotherText) {
                this.text = anotherText;
                return anotherText.length();
        }
}
```
c:\lib>java -jar lombok.jar -version
v1.16.6 "Candid Duck"

c:\lib>java -version
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

**Comment by rspilker** [comment]
I can reproduce the problem. Luckily, the compiler does generate the null-check.

**Comment by rspilker** [comment]
Hmm, delombok doesn't work at all. It no longer detects changes to the AST and therefore just copies the input.

**Comment by Scythson** [comment]
Thank you! Looking forward to see it in the build.

**Comment by kloklo90** [comment]
I have switched to delombok 1.16.16.0 and lombok 1.16.16 the combination does not get rid of the issue with lombok nonnull. Did anyone else fix the issue with lombok.nonnull

**Comment by soach** [comment]
i meet the same problem : java 8, delombok: v1.18.18 "Envious Ferret"
delombok can not remove nonNull annotations.
is there anything wrong when i use delombok?
java -jar ./lombok.jar delombok -f generateDelombokComment:skip  -f javaLangAsFQN:skip -f suppressWarnings:skip   $srcPath  -d $targetPath

**Comment by NicklasWallgren** [comment]
This issue is still present in 1.18.20.
