### ISSUE TITLE
eclipse4.5.1 can not start

### ISSUE THREAD

**Issue by tomasyl** [rzwitserloot/lombok#951]
when i install lombok1.16.6 or 1.16.4 to eclipse4.5.1 the eclipse can not startup, and when I uninstall lombok, it is fine.

**Comment by daddykotex** [comment]
I had a problem with this this morning. When using the installer, it wouldn't find my installation of Eclipse (4.5.1 - Mars). I installed it through homebrew cask which installed it in `/opt/homebrew-cask/Caskroom/eclipse-java/4.5.1/`. I looked at what the installer does and manually installed the tool myself.

The `Eclipse.App` package looks like this on my installation:
```
/opt/homebrew-cask/Caskroom/eclipse-java/4.5.1/Eclipse.app
└── Contents
    ├── Eclipse
    ├── Info.plist
    ├── MacOS
    ├── Resources
    └── _CodeSignature
```

The executable is in `MacOS` but the `eclipse.ini` is in `Eclipse`. Manually copy the `lombok.jar` in `MacOS` and edit `Eclipse/eclipse.ini` to add the following line:
```
-javaagent:lombok.jar
```

**Comment by daddykotex** [comment]
I think the installer need an update. Maybe I can look it up tonight :)

**Comment by tomasyl** [comment]
sorry, my eclipse is run on Windows7, and it copy the jar and add the -javaagent:lombok.jar to eclipse.ini, but it fail to start.

**Comment by daddykotex** [comment]
Is the jar copied next to the execuable?

**Comment by tomasyl** [comment]
yes, copied

**Comment by tomasyl** [comment]
it's work,when I click eclipse.exe not the shortcut at desktop today, wired... some thing wrong with the shortcut I think

**Comment by daddykotex** [comment]
You would have to give us specifics about that shortcut, maybe it adds some unwated parameters?

**Comment by rspilker** [comment]
To get this straight, it is not related to Eclipse Mars but the fact that you launch it using a shortcut?

**Comment by rspilker** [comment]
You can try modifying eclipse.ini and replace `lombok.jar` by the full path to the jar.

Closing this issue since the reporter did not respond.
