### ISSUE TITLE
@ToString annotation doesn't document all its keys.

### ISSUE THREAD

**Issue by Zteve** [rzwitserloot/lombok#953]
Is it my eyes, or are some of the annotations missing from the 'Supported Configuration Keys' list? In particular `exclude`, `of` and `callSuper`.

Please can you make sure the definitive lists are complete and, er, definitive?

Thank you for a great tool (and exemplary project)!

**Comment by rspilker** [comment]
I think you're confusing annotation methods with configuration keys from [lombok.config](https://projectlombok.org/features/configuration.html).

**Comment by rspilker** [comment]
Thanks for the positive feedback. Do you think of a better way to distinguish configuration keys from annotation methods in the documentation?

**Comment by Zteve** [comment]
Ah, you're right; but there isn't a list of annotation parameters in the doc. They are mentioned in the description, but it is not clear if they are all listed, nor what they all mean. The best way to avoid confusion (such as mine) is to formally list all the supported parameters under each annotation. Otherwise there is no way to tell.  Thanks again.

**Comment by rspilker** [comment]
We could add links to the [javadoc](https://projectlombok.org/api/lombok/ToString.html)

**Comment by Zteve** [comment]
That would be good. The javadoc does refer back to the feature page (ironically, for "full documentation"), but hey, between them they work.  Thanks.
