### ISSUE TITLE
@Cache

### ISSUE THREAD

**Issue by Punkratz312** [rzwitserloot/lombok#955]
I think it would be nice to use lombok for method caching.

@Cache
private String fetchBlacklist() {
      return blacklist; (content is static)
}

Lombok should wrap the method and execute it only once and save the return value in a private variable or so.
If the method is called again, the cached value should be returned instead of executing the method again and again.

**Comment by thisisthekap** [comment]
I think this behaviour could be accomplished by using @Getter(lazy=true): https://projectlombok.org/features/GetterLazy.html

**Comment by Punkratz312** [comment]
@thisisthekap oh great, thanks. Did know that feature. But in this case i have to write the variable boilerplate and the calculation occurs if the object gets constructed, not if the method gets called.

**Comment by thisisthekap** [comment]
Using @Getter(lazy=true), the calculation is triggered by the first call of the generated getter (not on object-construction).

**Comment by Punkratz312** [comment]
Oh you'r right. This is quite confusing that lombok removes the private variable. Thank you very much

**Comment by rzwitserloot** [comment]
Lombok still keeps a private variable around. If we were to add this feature we'd.... still have a private variable. We need to store that cache somewhere!

More generally this should be called `@Memoize` and should in theory at least also be applicable to methods with arguments, mapping the argument(s) onto the memoized result. This gets you into discussions on how long to cache this for, etc.

Very complex stuff. Let's stick with what `@Getter(lazy = true)` can do for now.
