### ISSUE TITLE
[enhancement request] Annotation for fluent setter

### ISSUE THREAD

**Issue by josefbetancourt** [rzwitserloot/lombok#956]
example: 
  Class Foo has: 
 >@Setter(Style.FLUENT)
 >public String name;

Will creates a setter:
```
public Foo setName(String name){
     this.name = name;
     return this;
}
```

**Comment by philnate** [comment]
+1, Would be great to have this added.

**Comment by kamkie** [comment]
check this https://github.com/rzwitserloot/lombok/blob/master/src/core/lombok/experimental/Accessors.java

**Comment by josefbetancourt** [comment]
@kamkie Awesome!  Did not see the experimental page.  After my OP, I also thought why even need the prefix.
