### ISSUE TITLE
Bug : lombok.javac.apt.Processor is not available using Netbeans

### ISSUE THREAD

**Issue by narakg** [rzwitserloot/lombok#959]
You found a bug in lombok; lombok.javac.apt.Processor is not available. Lombok will not run during this compilation: java.lang.ClassNotFoundException: lombok.javac.apt.Processor

**Comment by rspilker** [comment]
I've just created an [edge release](https://projectlombok.org/download-edge.html). After download, you probably need to rename the file from `lombok-edge.jar` to `lombok.jar`.

If you use that version, during compilation a warning should occur containing a reference to a report file that's created in your temp directory. You can also just look in your temp directory for files called 
`lombok-processor-report-*.txt`.

This file probable tells you where the duplication comes from. If you cannot figure it out, can you copy the contents of the file to this issue so we can have a look as well?

**Comment by rspilker** [comment]
Closing this issue since the reporter did not respond.
