### ISSUE TITLE
Lombok is throwing error in Jboss even after following all the procedure. Giving error as - Syntax error, insert “EnumBody” and “enum Identifier”

### ISSUE THREAD

**Issue by BharathSandeep** [rzwitserloot/lombok#961]
I can see getters and setters are working for @Data annotation but dont know while compiling sometimes it is throwing the above mentioned error

**Comment by rspilker** [comment]
When does the problem occur? What tools are you using? What does JBoss got to do with it?

Can you give a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/)?

**Comment by rspilker** [comment]
Closing this issue since the reporter did not respond.
