### ISSUE TITLE
New feature: generate constructors from superclass 

### ISSUE THREAD

**Issue by sfussenegger** [rzwitserloot/lombok#962]
It would be nice to let lombok generate constructors from superclasses just like Eclipse does (`Source > Generate Constructors from Superclass...`).

Example:

    @ParentConstructors
    public class MyException extends Exception {}

    new MyException("message");

I think access level should be the same as for the superclass (e.g. protected remains protected, public remains public) with the option to override this and filter:

    // generate protected constructors for all public superclass constructors
    @ParentConstructors(access = AccessLevel.PROTECTED, include = AccessLevel.PUBLIC)
    public class MyException extends Exception {}

**Comment by rzwitserloot** [comment]
This has been on our radar for years but requires resolution which is very difficult. It's possible, but very tricky to support. This doesn't really need an issue for tracking; we won't forget we want to do this, therefore, marked as 'wontfix' even though one day we do intend to address this.
