### ISSUE TITLE
@NonNull should allow specifying custom error message thrown

### ISSUE THREAD

**Issue by archenroot** [rzwitserloot/lombok#963]
In some cases null pointer is hard to debug if one doesn't have full context data available. I understand that it can be done by appropriate log messaging in DEBUG/TRACE mode, but if I can simply print with this @NonNull all relevant objects.toString(), it can make live easier again.

**Comment by rspilker** [comment]
`@NonNull` generated a `NullPointerException` containing the name of the field or parameter as a message. That together with the stacktrace should be enough? Are we missing anything here? Can you at least give an example if the code you would like to be generated and how that would look in your proposal?

**Comment by archenroot** [comment]
I see, I will propose the example first of course. Thank you.

**Comment by psinghwdb** [comment]
Let's say i have different name in json , thus can I return different name
