### ISSUE TITLE
Not working on Eclipse MARS

### ISSUE THREAD

**Issue by sergioszy** [rzwitserloot/lombok#964]
Can't resolve lombok imports  neither eclipse org.eclipse.jdt

I'm using java 1.7 because with 1.8 there are a missing class.

Thanks

**Comment by cforce** [comment]
I can resolve the imports (e.g. @Slf4j ) , but the weaved members/methods are not available in editor - means e.g the log.info()  is marked as compile error, although the sts.ini look like this:

-vm
C:/Program Files/Java/jdk1.8.0_11/jre/bin/javaw
-startup
plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.300.v20150602-1417
-product
org.springsource.sts.ide
--launcher.defaultAction
openFile
--launcher.XXMaxPermSize
256M
-vmargs
-Dosgi.requiredJavaVersion=1.7
-Xms80m
-Xmx2048m
-XX:MaxPermSize=1014m
-Xverify:none
-Dorg.eclipse.swt.browser.IEVersion=10001
-javaagent:lombok.jar

**Comment by rspilker** [comment]
I just downloaded `Mars.1 Release (4.5.1)` and for me it works. Also, you're referring to Mars, but also talk about sts.ini...

Do you have the slf4j api jar on the classpath?

If not you probably get the following error message:

- `org.slf4j cannot be resolved to a type`
- `org.slf4j.LoggerFactory cannot be resolved to a type`

If you open the error log view (`Window\Show View\Error Log`) do you get to see any details?

**Comment by rspilker** [comment]
Possibly if in the ini file you replace `lombok.jar` by the full path to the jar it works.

Closing this issue since the reporter did not respond.
