### ISSUE TITLE
sugguest @Data generate no args constructor by default.

### ISSUE THREAD

**Issue by redhatlinux10** [rzwitserloot/lombok#966]
lombok version 1.16.6
1.  currently @Data does not generate any constructors. this behavior brings big problem to me. i am using spring 3 + jersey to publish restful interfaces. i annotated these methods' input parameter/output parameter classes with @Data. but when those restful interfaces are called (for example through httpclient ), the caller get a 500 HTTP error and  the corresponding method didn't get called  and there are none error logs in the console. after i annotated these classes with @Data @NoArgsConstructor @AllArgsConstructor, everything comes back to normal. this behavior forces me to annotate every class with two more annotations.
i think spring 3 + jersey use no args constructor  to build a object , so if no args constructor is missed,  spring 3 + jersey can not work.
2. by default, all java classes which does not explicitly define a constructor will have a default no args constructor. 
so i strongly sugguest @Data generate no args constructor!

**Comment by rzwitserloot** [comment]
Data does generate a constructor, unless you already have one. It generates a constructor for all _required_ arguments, defined as: Any arguments that are either:

* Non-initialized but marked `final`, or
* Non-initialized but marked `@NonNull`.

If you have no such fields and no explicit constructor, data automatically makes the no-args constructor. If you do have such fields, we will continue to force you to add `@NoArgsConstructor`; it might annoy you with jersey, but it makes no sense. Bad design on jersey's part. Understandable, but the upshot is: Yes, you'll have to add 2 annotations. We will not change this.
