### ISSUE TITLE
@Singular fields in @Builder are always non-null after build()

### ISSUE THREAD

**Issue by Zteve** [rzwitserloot/lombok#968]
`.build()` on a builder with a `@Singular` collection field always constructs a (non-null) collection even if the field isn't ever set(added to).

So, a field like `private final List<String> things;` with a `@Builder Cons(@Singular List<String> things) { this.things = things; }` constructor, means that `Cons.builder().build()` will produce a `Cons` object with an empty non-null list.

I would like `things` to remain `null` (its initial value) if I don't ever "set" it in the builder. This can be achieved if the adders (`thing(String)` and `things(List<String>)`) did the initialisation lazily; creating the list on add only if the field was `null`. Then `build()` could only set the (final) field in `Cons` if it were non-null.

Currently, I find no way to cause this behaviour for collection (`@Singular`) fields in builders; hence this issue. Perhaps there could be an annotation parameter, or a configuration key that enabled/disabled this for all `@Singular` builder fields.

**Comment by rzwitserloot** [comment]
Builder is already lazy. This is non-expected behaviour and a code smell, at least, if a null list is semantically equivalent to the empty one.

I can understand how your suggested behaviour can be preferable in certain cases, but the current behaviour is probably more desired than your suggestion, in more cases, and it now has the considerable bonus of being the de facto standard already.

We could make a setting, but that doesn't sound like it's worth the maintenance headache and the documentation load on the users.

**Comment by Zteve** [comment]
I fully understand your reluctance to disturb the current behaviour; however I feel I have to make the following points:

1. Builder is lazy when creating the final collection; but it is _not_ lazy in creating the `ArrayList`s that it uses to accumulate the collection _before_ `build()`. These are initialised to empty collections and so, at `build()` time, the builder cannot know that this field has never been (set?) added-to. (We could have added an empty collection, btw.)
2. It is precisely the fact that `null` and empty are semantically distinct that I want this behaviour. At the moment I cannot convey this distinction in any `@Singular` field.

I hope you can reconsider.

**Comment by lkamb** [comment]
I would also like to see something like this.  Perhaps a lazy option to Singular:
@Singular(name="addOne", lazy=true)

I am adding lombok annotations to XML-schema driven code generation.  For working with the code, I like to use the builders and be able to iterate through whatever and add the items one by one to the object.  In the event that there are no items added, the XML is generated full of empty collection elements.   This is a case where using lombok (which I love) makes things much more complicated and less concise.
