### ISSUE TITLE
@NonEmpty

### ISSUE THREAD

**Issue by Punkratz312** [rzwitserloot/lombok#969]
Wouldn't it be nice, to have Annotation that enforces an type (Iterateable & String) not to be empty, in the way like @NonNull does?

**Comment by rzwitserloot** [comment]
Can't be done easily without resolution, and not interesting enough as a usecase to warrant the considerable hoops it would require if we do try to resolve. Unfortunately, this one doesn't cross the bar of effort required vs. boilerplateyness.
