### ISSUE TITLE
@RequiredArgsConstructor + @NonNull breaks eclipse highlighting

### ISSUE THREAD

**Issue by xak2000** [rzwitserloot/lombok#977]
I simplified code that breaks highlighting in eclipse:

```
package highlight;

import lombok.NonNull;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum LombokHighlight {
    TYPE1("type1");

    @NonNull
    private final String format;

    public boolean method1(String s1, String s2) {
        return s1.equals(s2);
    }

}
```

Open this file in Eclipse (initially highlight is fine) then click on `equals` method in `return s1.equals(s2);` clause. Important: click just after opening file. Don't click anywhere else.
All upper code will be highlighted as comment (gray in my color scheme).

After this clicking on classname fixing highlight and clicking `equals` again don't break it anymore. But if you click at random places in code then after some time highlight is breaks again. This is not so oftern in this simple file. But in real project with bigger file when this enum is nested in other class etc - this is became very very often.

![lombok-highlight](https://cloud.githubusercontent.com/assets/1576014/11342690/477454c4-9211-11e5-9a67-f9caee1064f4.png)

**Comment by rspilker** [comment]
Using your example code, I observed the behavior, but as you already wrote, it's not always the case. Could you also reproduce this in a non-enum type?

**Comment by xak2000** [comment]
Yes, if you change the `enum` keyword to `class` and remove `TYPE1("type1");` then highlight is still disappearing.

In my real class where I initially observed this bug this enum is actually nested in outer class and this bug eats highlighting in the whole class but only above the line which you click.

After you click `(1)` there is always this:
```
// unhighlighted code
(1) some java code highligted // you clicked here
/* all code below this line (inclusive) is highlighted too */
```

And yes. It is not always the case but with bigger file this is much often than with this small example files.

And to fix the highlighting almost always you need to click somewhere upper the `(1)`. Usually the class name when highlighting is broken. But only until you click somewhere below again (but not always).
