### ISSUE TITLE
Lombok Android Studio linter suggests to add @EqualsAndHashCode to declare callSuper, but already overriden

### ISSUE THREAD

**Issue by bryant1410** [rzwitserloot/lombok#983]
In IntelliJ (Android Studio, specifically), with `@Data` annotation and with the class inheriting from another, if `equals` and `hashCode` methods are overriden it anyway suggests to add `@EqualsAndHashCode` to declare `callSuper` attribute, but it shouldn't.

**Comment by mplushnikov** [comment]
It should be issue of [lombok-intellij-plugin](https://github.com/mplushnikov/lombok-intellij-plugin)
Please open it there.
