### ISSUE TITLE
@Builder.ObtainVia is missing RetentionPolicy

### ISSUE THREAD

**Issue by SPessall** [rzwitserloot/lombok#986]
The _ObtainVia_ annotation is missing the _Retention(RetentionPolicy.SOURCE)_ annotation. Thus the annotation is present in the class files.

The enclosing _Builder_ itself does have the _Retention_ annotation, but I don't think that it is intended that it is inherited by enclosed annotations.

**Comment by rspilker** [comment]
Will be in 1.16.8
