### ISSUE TITLE
Not all lombok features with with some GWT versions

### ISSUE THREAD

**Issue by bpelakh** [rzwitserloot/lombok#987]
Specifically an option to generate something other than a `$` as a starter/separator character. Having this generated code break GWT compilation, preventing us from being able to use Lombok and GWT in tandem.

**Comment by rspilker** [comment]
What version of GWT are you using? According to [this GWT issue](https://code.google.com/p/google-web-toolkit/issues/detail?id=6799) it was already fixed in GWT 2.7.0 RC1.

**Comment by rspilker** [comment]
Duplicate of issue #487

**Comment by rspilker** [comment]
Closing this issue since the reporter did not respond.
