### ISSUE TITLE
use HTTPS to protect developers

### ISSUE THREAD

**Issue by eighthave** [rzwitserloot/lombok#989]
The build system here downloads and executes lots of jars via plain text HTTP connections.  This is a large security risk:
http://blog.ontoillogical.com/blog/2014/07/28/how-to-take-over-any-java-developer/

And there is a simple fix that will help a lot, switch the URLs to use HTTPS:
`find * -name \*.xml|xargs sed -i 's,http://projectlombok.org,https://projectlombok.org,g'`

And changing this in *buildScripts/ivysettings.xml* works for me:
`<ibiblio name="maven-repo2" m2compatible="true" root="https://repo1.maven.org/maven2" />`

**Comment by rspilker** [comment]
There were no occurrences of http://projectlombok.org in the code. I've changed the ivysettings.xml as suggested.
