### ISSUE TITLE
@Getter on Boolean field

### ISSUE THREAD

**Issue by drtimwright** [rzwitserloot/lombok#998]
Hi there,

it looks like using @Getter on a Boolean (with a capital B) field creates a method that starts with get not with is.

Using version 1.16.6

Tim

**Comment by Maaartinus** [comment]
That's pretty stupid. Unfortunately, it's stupid exactly the way the bean specification goes. If you want to be conform, than use it as is.

**Comment by drtimwright** [comment]
I guess if that's the spec, then that's the spec.

It meant that my method names changed when I moved from boolean to Boolean. On the upside, it meant the compiler told me about I all places where I had to check for the new option of a null value. So perhaps it was for the better.
